// Allegheny Health Network vs Cigna — PR War Room Config
// Two rounds: 2023 (1-year deal, resolved June 29) and 2025 (3-year deal, resolved June 28).
// Pittsburgh market. ~20,000 Cigna commercial members affected.

const ENTRIES = [
  // === 2023 ROUND — MEDIA ENTRIES ===
  {
    id: 1,
    date: "2023-06-15",
    source: "CBS Pittsburgh / KDKA-TV",
    sourceType: "tv",
    channel: "media",
    headline: "AHN-Cigna contract talks stall — 20,000 patients could lose in-network access at 14 hospitals",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Jon Delano report. First major local TV coverage of 2023 round. 14 hospitals including Allegheny General, West Penn, Forbes Regional. AHN seeking 'fair and equitable reimbursement rates.' Sets provider-sympathetic tone in Pittsburgh market.",
  },
  {
    id: 2,
    date: "2023-06-16",
    source: "WPXI Pittsburgh",
    sourceType: "tv",
    channel: "media",
    headline: "Allegheny Health Network warns patients Cigna contract may expire — urges members to contact insurer",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "WPXI follow-up to KDKA break. Patient interview: 'We're going to be severely impacted... very difficult to find a new doctor.' AHN's call-to-action framing — directing patients to pressure Cigna.",
  },
  {
    id: 3,
    date: "2023-06-18",
    source: "TribLIVE",
    sourceType: "news",
    channel: "media",
    headline: "AHN-Cigna contract dispute threatens access for thousands of Pittsburgh-area patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Tribune-Review digital. Balanced print coverage. Notes Highmark Health (AHN parent) owns both an insurer and a provider — unique Pittsburgh market dynamic. UPMC-Highmark history frames all local health disputes.",
  },
  {
    id: 4,
    date: "2023-06-20",
    source: "Pittsburgh Post-Gazette",
    sourceType: "news",
    channel: "media",
    headline: "Cigna, Allegheny Health Network at impasse over contract renewal — deadline looms",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Post-Gazette coverage. Paper of record for Pittsburgh. Notes AHN's 14-hospital footprint across western PA. Balanced framing with both sides' statements.",
  },
  {
    id: 5,
    date: "2023-06-22",
    source: "KDKA Radio",
    sourceType: "radio",
    channel: "media",
    headline: "AHN-Cigna dispute dominates Pittsburgh talk radio — callers express anxiety about losing doctors",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "KDKA Radio talk segments. Caller-driven format amplifies patient anxiety. Pittsburgh's blue-collar listener base sympathetic to local hospital system vs national insurer. Radio reach underestimated in Pittsburgh market.",
  },
  {
    id: 6,
    date: "2023-06-25",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "Allegheny Health Network, Cigna contract talks continue as deadline approaches",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press. Hospital executive audience. Notes AHN is part of Highmark Health system. Factual reporting.",
  },
  {
    id: 7,
    date: "2023-06-27",
    source: "HealthLeaders",
    sourceType: "news",
    channel: "media",
    headline: "AHN-Cigna impasse highlights rising provider-payor tensions nationwide",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press. Systemic framing — positions AHN dispute within national trend of provider-insurer brinksmanship. Normalizes AHN's stance.",
  },
  {
    id: 8,
    date: "2023-06-29",
    source: "CBS Pittsburgh / KDKA-TV",
    sourceType: "tv",
    channel: "media",
    headline: "AHN and Cigna reach 11th-hour deal — 1-year contract averts network disruption",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Patrick Damp report. Resolution coverage. '11th-hour' framing. 1-year deal signals temporary truce, not long-term resolution. Both sides signal willingness to revisit. Sets stage for 2025 round.",
  },
  {
    id: 9,
    date: "2023-06-29",
    source: "Pittsburgh Post-Gazette",
    sourceType: "news",
    channel: "media",
    headline: "Allegheny Health Network, Cigna agree to 1-year contract extension",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Post-Gazette resolution story. Notes 1-year deal is short-term fix. Neither side disclosed rate specifics. 'Extension' framing suggests status quo preserved temporarily.",
  },
  {
    id: 10,
    date: "2023-06-29",
    source: "TribLIVE",
    sourceType: "news",
    channel: "media",
    headline: "AHN-Cigna contract deal reached — patients retain in-network access for now",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "'For now' qualifier signals temporary resolution. Tribune-Review notes both parties expect renewed negotiations.",
  },

  // === 2025 ROUND — MEDIA ENTRIES ===
  {
    id: 11,
    date: "2025-06-04",
    source: "CBS Pittsburgh / KDKA-TV",
    sourceType: "tv",
    channel: "media",
    headline: "AHN warns Cigna contract may not be renewed — 20,000 commercial members at risk again",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Bartos report. Dispute goes public June 4. 'Again' framing connects to 2023 round — establishes pattern narrative. AHN VP Dan Laurent: 'fair and equitable reimbursement rates.' Commercial-only dispute (not Medicare Advantage).",
  },
  {
    id: 12,
    date: "2025-06-05",
    source: "CBS Pittsburgh / KDKA-TV",
    sourceType: "tv",
    channel: "media",
    headline: "Cigna responds to AHN contract dispute — says AHN demanding 'unreasonably high rates'",
    frameAdoption: "cigna",
    sentiment: "negative_ahn",
    patientStory: false,
    blameDirection: "ahn",
    reachEstimate: "high",
    notes: "Bartos follow-up. Cigna's primary public counter: 'unreasonably high rates that would significantly increase costs.' One of few media hits adopting Cigna frame. Balanced coverage gives both sides air time on consecutive days.",
  },
  {
    id: 13,
    date: "2025-06-07",
    source: "WPXI Pittsburgh",
    sourceType: "tv",
    channel: "media",
    headline: "Patients caught in middle of AHN-Cigna contract standoff for second time in two years",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "WPXI coverage. 'Second time in two years' is powerful framing — suggests systemic failure. Patient interviews. Repeated disruption creates cumulative anxiety.",
  },
  {
    id: 14,
    date: "2025-06-10",
    source: "TribLIVE",
    sourceType: "news",
    channel: "media",
    headline: "AHN-Cigna contract talks collapse again — Highmark Health cites $147M loss at AHN in 2024",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Key financial data: Highmark Health lost $147M at AHN in 2024. Invested $1.3B+ since 2018. Financial hardship framing strengthens AHN's rate increase justification. $674M system-wide loss projected for 2025.",
  },
  {
    id: 15,
    date: "2025-06-12",
    source: "Pittsburgh Post-Gazette",
    sourceType: "news",
    channel: "media",
    headline: "Allegheny Health Network says Cigna rates unsustainable as Highmark posts hundreds of millions in losses",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Post-Gazette deep dive. Financial framing: $147M AHN loss (2024), $674M Highmark system-wide (2025), $1.3B+ invested since 2018. Paper of record lending credibility to AHN's financial sustainability argument.",
  },
  {
    id: 16,
    date: "2025-06-14",
    source: "WPXI Pittsburgh",
    sourceType: "tv",
    channel: "media",
    headline: "AHN patients scramble for alternatives as Cigna contract deadline nears",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Second WPXI segment. Patient anxiety coverage. 'Scramble' framing creates urgency. Pittsburgh is a tight medical market — UPMC rivalry means AHN patients have limited alternatives.",
  },
  {
    id: 17,
    date: "2025-06-15",
    source: "KDKA Radio",
    sourceType: "radio",
    channel: "media",
    headline: "AHN-Cigna dispute returns to Pittsburgh talk radio — callers recall 2023 anxiety",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Talk radio segments. Callers reference 2023 round — cumulative fatigue with repeated disputes. Local vs national insurer narrative plays well in Pittsburgh's community-oriented media landscape.",
  },
  {
    id: 18,
    date: "2025-06-16",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "Allegheny Health Network, Cigna contract dispute resurfaces — second round in two years",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press. Notes pattern of Cigna disputes nationally. Cigna dispute count: 51 (2022), 86 (2023), 133 (2024). AHN is part of an escalating national trend.",
  },
  {
    id: 19,
    date: "2025-06-18",
    source: "WFMJ Youngstown",
    sourceType: "tv",
    channel: "media",
    headline: "AHN-Cigna dispute impacts patients across western PA and eastern Ohio border region",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Youngstown market coverage. AHN's footprint extends beyond Pittsburgh metro. Border-region patients have even fewer alternatives. Expands geographic awareness of dispute.",
  },
  {
    id: 20,
    date: "2025-06-20",
    source: "WPXI Pittsburgh",
    sourceType: "tv",
    channel: "media",
    headline: "AHN-Cigna negotiations stall with 10 days remaining — patients urged to prepare",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Third WPXI segment. Countdown framing builds urgency. Balanced but anxiety-inducing. 'Urged to prepare' suggests disruption is likely.",
  },
  {
    id: 21,
    date: "2025-06-22",
    source: "Beaver County Radio",
    sourceType: "radio",
    channel: "media",
    headline: "Local radio covers AHN-Cigna dispute impact on Beaver County patients and families",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Hyperlocal radio. Beaver County is working-class community heavily dependent on AHN. Local framing: national insurer threatening community hospital access. Grassroots reach.",
  },
  {
    id: 22,
    date: "2025-06-24",
    source: "TribLIVE",
    sourceType: "news",
    channel: "media",
    headline: "AHN-Cigna talks resume but gap remains — Highmark Health's $674M projected loss adds urgency",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "TribLIVE update. $674M system-wide 2025 projection. Financial data continues to bolster AHN's justification narrative. 'Gap remains' signals deal not imminent.",
  },
  {
    id: 23,
    date: "2025-06-25",
    source: "CBS Pittsburgh / KDKA-TV",
    sourceType: "tv",
    channel: "media",
    headline: "AHN-Cigna deadline looms — patients express frustration with repeated contract brinksmanship",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CBS Pittsburgh deadline-week coverage. Patient: 'causing me some stress in my daily life.' Brinksmanship framing assigns shared blame but patient anxiety works in provider's favor.",
  },
  {
    id: 24,
    date: "2025-06-26",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "Cigna dispute count reaches 133 in 2024, up from 51 in 2022 — AHN among latest",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "KEY SYSTEMIC DATA. Cigna disputes: 51 (2022), 86 (2023), 133 (2024). 160% increase in two years. Positions AHN within escalating national pattern. Undermines 'AHN is uniquely unreasonable' framing.",
  },
  {
    id: 25,
    date: "2025-06-28",
    source: "CBS Pittsburgh / KDKA-TV",
    sourceType: "tv",
    channel: "media",
    headline: "AHN and Cigna reach 3-year contract deal — network access preserved for 20,000 members",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Patrick Damp report. Resolution coverage. 3-year deal (vs 1-year in 2023) signals more substantive agreement. Neither side disclosed rate specifics. Longer term suggests both sides made concessions.",
  },
  {
    id: 26,
    date: "2025-06-28",
    source: "WPXI Pittsburgh",
    sourceType: "tv",
    channel: "media",
    headline: "AHN-Cigna 3-year deal ends weeks of uncertainty for Pittsburgh-area patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "WPXI resolution. 'Weeks of uncertainty' frames the dispute duration. Relief framing. 3-year term noted as improvement over 2023's 1-year stopgap.",
  },
  {
    id: 27,
    date: "2025-06-30",
    source: "Pittsburgh Post-Gazette",
    sourceType: "news",
    channel: "media",
    headline: "Allegheny Health Network, Cigna reach multi-year agreement ending second contract dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Post-Gazette wrap-up. 'Second contract dispute' framing reminds readers of pattern. Neither side disclosed financial terms. Notes deal length suggests deeper structural resolution than 2023.",
  },
  {
    id: 28,
    date: "2025-06-30",
    source: "TribLIVE",
    sourceType: "news",
    channel: "media",
    headline: "AHN-Cigna 3-year deal provides stability after back-to-back contract fights",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "TribLIVE resolution. 'Back-to-back' framing emphasizes repetitive dispute pattern. 'Stability' is the key word — both sides claim credit for longer-term resolution.",
  },

  // === AHN OWNED MEDIA ===
  {
    id: 29,
    date: "2025-06-04",
    source: "AHN (public statement)",
    sourceType: "owned",
    channel: "media",
    headline: "AHN VP Dan Laurent: 'We are seeking fair and equitable reimbursement rates from Cigna'",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "AHN's opening public statement. Dan Laurent, VP. 'Fair and equitable' framing positions AHN as reasonable party. Notes $1.3B+ investment since 2018, $147M loss in 2024. Financial sustainability narrative.",
  },
  {
    id: 30,
    date: "2025-06-28",
    source: "AHN (press release)",
    sourceType: "owned",
    channel: "media",
    headline: "AHN announces 3-year contract agreement with Cigna — patients retain full in-network access",
    frameAdoption: "ahn",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution announcement. 'Patients retain' framing implies AHN secured access Cigna was threatening. 3-year term presented as victory for stability.",
  },

  // === CIGNA OWNED MEDIA ===
  {
    id: 31,
    date: "2025-06-05",
    source: "Cigna (public statement)",
    sourceType: "owned",
    channel: "media",
    headline: "Cigna: AHN demanding 'unreasonably high rates that would significantly increase costs' for members",
    frameAdoption: "cigna",
    sentiment: "negative_ahn",
    patientStory: false,
    blameDirection: "ahn",
    reachEstimate: "medium",
    notes: "Cigna's primary public counter. 'Unreasonably high rates' and 'significantly increase costs' are core Cigna talking points. Frames AHN as cost driver. Standard insurer affordability messaging.",
  },
  {
    id: 32,
    date: "2025-06-28",
    source: "Cigna (press release)",
    sourceType: "owned",
    channel: "media",
    headline: "Cigna announces multi-year agreement with AHN — 'committed to affordable access for our customers'",
    frameAdoption: "cigna",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution statement. 'Affordable access' framing claims credit for cost containment. Conciliatory tone suggests Cigna felt local pressure.",
  },

  // === SOCIAL ENTRIES ===
  {
    id: 33,
    date: "2025-06-06",
    source: "AHN official (LinkedIn)",
    sourceType: "social",
    channel: "social",
    headline: "AHN LinkedIn post highlights $1.3B investment and commitment to western PA patients amid Cigna dispute",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "LinkedIn audience includes local employers and benefits decision-makers. $1.3B investment figure reinforces AHN's community commitment narrative. Professional tone suited to platform.",
  },
  {
    id: 34,
    date: "2025-06-10",
    source: "CBS Pittsburgh (Facebook)",
    sourceType: "social",
    channel: "social",
    headline: "CBS Pittsburgh Facebook post on AHN-Cigna dispute generates hundreds of comments from anxious patients",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Facebook comment sections skew anti-insurer in Pittsburgh market. Local community loyalty to AHN. Comments include patient stories about difficulty finding alternative providers in UPMC-dominated market.",
  },
  {
    id: 35,
    date: "2023-06-20",
    source: "CBS Pittsburgh (Facebook)",
    sourceType: "social",
    channel: "social",
    headline: "2023 round: CBS Pittsburgh Facebook coverage draws patient comments — 'very difficult to find a new doctor'",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "2023 social coverage. Patient comment: 'We're going to be severely impacted... very difficult to find a new doctor.' Pittsburgh's limited provider market (AHN vs UPMC) makes switching genuinely difficult.",
  },
  {
    id: 36,
    date: "2025-06-15",
    source: "Social media (Pittsburgh community)",
    sourceType: "social",
    channel: "social",
    headline: "Pittsburgh community social media buzzes with AHN-Cigna frustration — 'not again'",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "'Not again' sentiment reflects cumulative fatigue from 2023 repeat. Local Facebook groups, Nextdoor, and Reddit r/pittsburgh discussions. Community frustration directed primarily at Cigna as outside entity.",
  },
  {
    id: 37,
    date: "2025-06-20",
    source: "AHN official (LinkedIn)",
    sourceType: "social",
    channel: "social",
    headline: "AHN LinkedIn update: 'We remain committed to reaching a fair agreement that supports our patients'",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Second LinkedIn post. 'Fair agreement' implies Cigna's current offer is unfair. Professional audience engagement. Employee sharing amplifies reach.",
  },
  {
    id: 38,
    date: "2025-06-28",
    source: "AHN official (LinkedIn)",
    sourceType: "social",
    channel: "social",
    headline: "AHN LinkedIn announces 3-year Cigna resolution — celebrates stability for patients and community",
    frameAdoption: "ahn",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution post. Community commitment framing. Employee engagement likely high after weeks of uncertainty.",
  },

  // === STAKEHOLDER ENTRIES ===
  {
    id: 39,
    date: "2025-06-04",
    source: "Dan Laurent, VP, AHN",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "AHN VP Dan Laurent: 'fair and equitable reimbursement rates' needed to sustain $1.3B investment",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Key AHN spokesperson. Financial data: $147M AHN loss (2024), $1.3B+ invested since 2018, $674M Highmark system-wide projected loss (2025). Positions rate increase as existential need, not profit-seeking.",
  },
  {
    id: 40,
    date: "2025-06-10",
    source: "Highmark Health financial disclosures",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Highmark Health reports $147M loss at AHN (2024), projects $674M system-wide loss for 2025",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "CRITICAL FINANCIAL CONTEXT. Highmark Health (AHN parent) lost $147M at AHN in 2024. $674M system-wide projected for 2025. $1.3B+ invested since 2018 acquisition. Financial hardship narrative is AHN's strongest factual argument for rate increases.",
  },
  {
    id: 41,
    date: "2025-06-15",
    source: "Pittsburgh market dynamics (UPMC-Highmark context)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "UPMC-Highmark rivalry limits patient alternatives — AHN patients cannot easily switch to UPMC under Highmark insurance",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "STRUCTURAL CONTEXT. Pittsburgh healthcare market uniquely constrained by UPMC-Highmark rivalry. Many AHN patients have Highmark insurance, limiting UPMC access. Cigna members losing AHN face similar constraints. Duopoly dynamics amplify any network disruption.",
  },
  {
    id: 42,
    date: "2025-06-20",
    source: "Cigna national dispute pattern analysis",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Cigna's national dispute count escalates: 51 (2022), 86 (2023), 133 (2024) — AHN part of systemic pattern",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "PATTERN DATA. Cigna provider disputes: 51 (2022), 86 (2023), 133 (2024). 160% increase in two years. AHN is not an outlier — Cigna is fighting providers nationally. Pattern evidence undermines 'AHN is unreasonable' framing.",
  },
  {
    id: 43,
    date: "2025-06-25",
    source: "Government / regulatory (silence)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "No Pennsylvania government or regulatory intervention in AHN-Cigna dispute — market-driven resolution",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "SILENCE IS DATA. No PA governor, AG, or insurance commissioner public statements. No legislative hearings. Unlike some states (CT created FAQ for Hartford/UHC), Pennsylvania took hands-off approach. Market-driven resolution expected.",
  },
  {
    id: 44,
    date: "2023-06-29",
    source: "2023 resolution precedent",
    sourceType: "news",
    channel: "stakeholder",
    headline: "2023 round: 1-year deal resolved June 29 — short-term fix set stage for 2025 repeat",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "PRECEDENT. 2023's 1-year deal was explicitly a stopgap. Both sides knew 2025 negotiation would be more consequential. The repeat dispute validated concerns that 2023 didn't address underlying rate gap. 3-year 2025 deal suggests deeper resolution.",
  },
];

const LABELS = {
  frameAdoption: { ahn: "AHN Frame", cigna: "Cigna Frame", balanced: "Balanced" },
  sentiment: {
    negative_cigna: "Anti-Cigna",
    negative_ahn: "Anti-AHN",
    neutral: "Neutral",
    positive_cigna: "Pro-Cigna",
    positive_ahn: "Pro-AHN",
  },
  blameDirection: { cigna: "Blames Cigna", ahn: "Blames AHN", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National record (1.5)
  "Becker's Hospital Review": 1.5, "HealthLeaders": 1.5,
  // Tier 2 — Regional authority (1.2)
  "CBS Pittsburgh / KDKA-TV": 1.2, "WPXI Pittsburgh": 1.2, "Pittsburgh Post-Gazette": 1.2,
  "TribLIVE": 1.2, "WFMJ Youngstown": 1.2,
  // Tier 3 — Trade/niche (1.0)
  "KDKA Radio": 1.0, "Beaver County Radio": 1.0,
  // Tier 4 — Organic social (0.7)
  "CBS Pittsburgh (Facebook)": 0.7, "Social media (Pittsburgh community)": 0.7,
  // Tier 5 — Owned/party media (0.3)
  "AHN (public statement)": 0.3, "AHN (press release)": 0.3,
  "AHN official (LinkedIn)": 0.3,
  "Cigna (public statement)": 0.3, "Cigna (press release)": 0.3,
  // Tier 6 — Stakeholder actions (1.3)
  "Dan Laurent, VP, AHN": 1.3, "Highmark Health financial disclosures": 1.3,
  "Pittsburgh market dynamics (UPMC-Highmark context)": 1.3,
  "Cigna national dispute pattern analysis": 1.3,
  "Government / regulatory (silence)": 1.3, "2023 resolution precedent": 1.3,
};

const SEARCH_TRENDS = [
  { week: "2025-05-05", interest: 5 },
  { week: "2025-05-12", interest: 5 },
  { week: "2025-05-19", interest: 5 },
  { week: "2025-05-26", interest: 5 },
  { week: "2025-06-02", interest: 60 },
  { week: "2025-06-09", interest: 50 },
  { week: "2025-06-16", interest: 50 },
  { week: "2025-06-23", interest: 70 },
  { week: "2025-06-30", interest: 100 },
  { week: "2025-07-07", interest: 20 },
  { week: "2025-07-14", interest: 5 },
  { week: "2025-07-21", interest: 5 },
];

export default {
  // Identity
  providerKey: "ahn",
  payorKey: "cigna",
  providerName: "Allegheny Health Network",
  payorName: "Cigna",
  providerShort: "AHN",
  payorShort: "Cigna",
  navShort: "AHN v. Cigna",
  title: "AHN vs Cigna",
  subtitle: "Contract dispute · Pittsburgh · Resolved June 28, 2025 (3-year deal)",
  gradientId: "ahncigna",

  // Dates
  monitorStart: "May 1, 2025",
  monitorEnd: "July 31, 2025",
  disputePublicDate: "2025-06-04",

  // Colors
  colors: {
    providerColor: "#1B4D8E",
    payorColor: "#E87722",
    neutral: "#64748B",
    accent: "#1B4D8E",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#1B4D8E", "#7A6058", "#E87722"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"allegheny health network cigna" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.42,
    nationalMedian: 1.0,
    networkComplaints: 892,
    priorYearComplaints: 614,
    regulatorAction: "No Pennsylvania government or regulatory intervention. No public statements from PA governor, AG, or insurance commissioner. Market-driven resolution.",
    signalRead: "Cigna's national dispute count escalated 160% from 51 (2022) to 133 (2024), indicating a corporate strategy of aggressive rate negotiations. AHN is part of a systemic pattern, not an isolated case. Pittsburgh's UPMC-Highmark duopoly amplifies disruption risk for any network change.",
  },

  // Executive summary
  executiveSummary: {
    statement: "Two-round dispute (2023 and 2025) resolved with progressively longer terms — 1-year stopgap in 2023, 3-year deal in 2025 — suggesting underlying rate gap was eventually addressed. No actual network disruption occurred in either round.",
    keyMessages: [
      "Highmark Health's $147M loss at AHN (2024) and $1.3B+ investment since 2018 are the stickiest financial arguments for rate increases — hard for Cigna to counter with 'affordability' framing.",
      "The repeat-dispute pattern (2023 then 2025) created cumulative patient anxiety and media fatigue that worked against Cigna's position as the perceived aggressor.",
      "Cigna's national dispute escalation (51 to 133 in two years) undermines any framing that AHN is uniquely unreasonable.",
      "Pittsburgh's UPMC-Highmark duopoly means AHN patients have genuinely limited alternatives — network disruption carries outsized real-world impact.",
    ],
    marcomm: [
      "<strong>Repeat disputes are a PR liability for the insurer.</strong> The 'not again' sentiment from 2023 created a pre-loaded narrative of Cigna as a serial disruptor. AHN benefited from community sympathy that compounded across rounds.",
      "<strong>Financial transparency was AHN's strongest weapon.</strong> Publishing specific loss figures ($147M, $674M, $1.3B invested) gave media concrete data points and made 'fair reimbursement' claims credible rather than abstract.",
      "<strong>Pittsburgh's local-vs-national dynamic favors the provider.</strong> AHN is a community institution; Cigna is a national corporation. In a market shaped by the UPMC-Highmark rivalry, local loyalty runs deep and outsider insurers face structural sympathy deficits.",
      "<strong>The 3-year deal signals both sides learned from 2023.</strong> The longer term reduces brinksmanship risk and suggests Cigna accepted the reputational cost of repeated public disputes was not worth the negotiating leverage.",
    ],
  },
  channelTakeaways: {
    media: [
      "CBS Pittsburgh / KDKA-TV was the dominant outlet across both rounds — Jon Delano (2023) and Bartos/Damp (2025) drove the narrative arc.",
      "Pittsburgh Post-Gazette and TribLIVE provided the financial depth coverage (Highmark losses, investment figures) that strengthened AHN's position.",
      "Trade press (Becker's, HealthLeaders) framed AHN within the national Cigna dispute escalation pattern — normalizing AHN's stance.",
      "WFMJ Youngstown and Beaver County Radio extended geographic awareness beyond Pittsburgh metro, reaching underserved AHN patient communities.",
    ],
    social: [
      "CBS Pittsburgh Facebook posts generated the highest social engagement — comment sections ran heavily anti-Cigna with patient stories about limited alternatives.",
      "AHN's LinkedIn strategy targeted employers and benefits decision-makers with investment and financial loss data — appropriate platform-audience match.",
      "Pittsburgh community social media (Nextdoor, Reddit r/pittsburgh, local Facebook groups) reflected 'not again' fatigue from repeated disputes.",
      "Cigna had minimal social presence in the dispute — no visible counter-narrative on social platforms.",
    ],
    stakeholder: [
      "Dan Laurent (AHN VP) was the primary spokesperson — 'fair and equitable reimbursement' became the defining AHN sound bite across both rounds.",
      "Highmark Health financial disclosures ($147M loss, $1.3B investment, $674M projection) were the strongest evidence supporting AHN's rate increase justification.",
      "UPMC-Highmark market dynamics created a structural backdrop that made any network disruption uniquely consequential in Pittsburgh.",
      "Government silence from Pennsylvania officials suggests both parties were expected to resolve without regulatory intervention — and did.",
    ],
    employer: [
      "Commercial-only dispute (not Medicare Advantage) meant employer plans were the primary affected population — approximately 20,000 Cigna commercial members.",
      "AHN's LinkedIn employer-facing messaging emphasized community investment and financial sustainability to frame rate increases as necessary, not excessive.",
      "Cigna's 'unreasonably high rates' counter-narrative targeted employer cost concerns but lacked the emotional weight of patient disruption stories.",
    ],
  },
};
