// Allegheny Health Network vs Cigna — PR War Room Config
// Two rounds: 2023 (1-year deal, resolved June 29) and 2025 (3-year deal, resolved June 28).
// Pittsburgh market. ~20,000 Cigna commercial members affected.
// AHN is owned by Highmark Health (Blue Cross Blue Shield affiliate).

const ENTRIES = [
  // === 2023 ROUND — MEDIA ENTRIES ===
  {
    id: 1,
    date: "2023-05-24",
    source: "Cigna (patient warning letter)",
    sourceType: "owned",
    channel: "media",
    headline: "Cigna mails warning to Pittsburgh policyholders: 'You'll likely pay more' if AHN drops Cigna on June 30",
    frameAdoption: "cigna",
    sentiment: "negative_ahn",
    patientStory: false,
    blameDirection: "ahn",
    reachEstimate: "high",
    notes: "First public salvo in 2023 round. Cigna frames AHN as the party 'dropping' Cigna. 'Pay more for the same services at their hospitals.' Direct-to-patient mail reaches all 20,000 affected members. Preemptive blame-shifting.",
  },
  {
    id: 2,
    date: "2023-06-15",
    source: "CBS Pittsburgh / KDKA-TV",
    url: "https://www.cbsnews.com/pittsburgh/news/allegheny-health-network-cigna-agreement/",
    sourceType: "tv",
    channel: "media",
    headline: "AHN-Cigna contract talks stall — 20,000 patients could lose in-network access at 14 hospitals",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Jon Delano report. First major local TV coverage of 2023 round. 14 hospitals including Allegheny General, West Penn, Forbes Regional, Canonsburg General, Jefferson Regional, Grove City Medical, Saint Vincent Health, and AHN Wexford. AHN seeking 'fair and equitable reimbursement rates.'",
  },
  {
    id: 3,
    date: "2023-06-16",
    source: "WPXI Pittsburgh",
    url: "https://www.wpxi.com/news/local/cigna-allegheny-health-network-contract-dispute-threatens-in-network-access-thousands/C2XUDX7RQNDRVKOLU6TXOIXXI4/",
    sourceType: "tv",
    channel: "media",
    headline: "Allegheny Health Network warns patients Cigna contract may expire — urges members to contact insurer",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "WPXI follow-up. Patient interview: 'We're going to be severely impacted... not only are we faced with finding new doctors for conditions that need ongoing medical care.' AHN's call-to-action framing — directing patients to pressure Cigna.",
  },
  {
    id: 4,
    date: "2023-06-18",
    source: "TribLIVE",
    sourceType: "news",
    channel: "media",
    headline: "AHN-Cigna contract dispute threatens access for thousands of Pittsburgh-area patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Tribune-Review digital. Balanced print coverage. Notes Highmark Health (AHN parent) owns both an insurer and a provider — unique Pittsburgh market dynamic. UPMC-Highmark history frames all local health disputes.",
  },
  {
    id: 5,
    date: "2023-06-20",
    source: "Pittsburgh Post-Gazette",
    sourceType: "news",
    channel: "media",
    headline: "Cigna, Allegheny Health Network at impasse over contract renewal — deadline looms",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Post-Gazette coverage. Paper of record for Pittsburgh. Notes AHN's 14-hospital footprint across western PA. Balanced framing with both sides' statements.",
  },
  {
    id: 6,
    date: "2023-06-20",
    source: "CBS Pittsburgh (Facebook)",
    sourceType: "social",
    channel: "social",
    headline: "2023 round: CBS Pittsburgh Facebook coverage draws patient comments — 'very difficult to find a new doctor'",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Social coverage. Patient comment: 'We're going to be severely impacted... very difficult to find a new doctor.' Pittsburgh's limited provider market (AHN vs UPMC) makes switching genuinely difficult.",
  },
  {
    id: 7,
    date: "2023-06-22",
    source: "KDKA Radio",
    sourceType: "radio",
    channel: "media",
    headline: "AHN-Cigna dispute dominates Pittsburgh talk radio — callers express anxiety about losing doctors",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "KDKA Radio talk segments. Caller-driven format amplifies patient anxiety. Pittsburgh's blue-collar listener base sympathetic to local hospital system vs national insurer. Radio reach underestimated in Pittsburgh market.",
  },
  {
    id: 8,
    date: "2023-06-23",
    source: "CBS Pittsburgh / KDKA-TV",
    url: "https://www.cbsnews.com/pittsburgh/news/money-dispute-allegheny-health-cigna-impact-residents/",
    sourceType: "tv",
    channel: "media",
    headline: "Money dispute between Allegheny Health and Cigna could cost 20,000 residents — patient: 'Please keep in mind it is people's health'",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Patrick Damp report. KEY PATIENT QUOTE: 'Naturally, that caused me and is still causing me some stress in my daily life, trying to figure out what is going to happen next.' Second patient: 'Please keep in mind it is people's health that is in the crossfire here.'",
  },
  {
    id: 9,
    date: "2023-06-25",
    source: "Becker's Hospital Review",
    url: "https://www.beckerspayer.com/contracting/cigna-allegheny-health-network-face-july-1-split-2/",
    sourceType: "news",
    channel: "media",
    headline: "Allegheny Health Network, Cigna contract talks continue as deadline approaches",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press. Hospital executive audience. Notes AHN is part of Highmark Health system. Factual reporting.",
  },
  {
    id: 10,
    date: "2023-06-27",
    source: "HealthLeaders",
    sourceType: "news",
    channel: "media",
    headline: "AHN-Cigna impasse highlights rising provider-payor tensions nationwide",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press. Systemic framing — positions AHN dispute within national trend of provider-insurer brinksmanship. Normalizes AHN's stance.",
  },
  {
    id: 11,
    date: "2023-06-29",
    source: "CBS Pittsburgh / KDKA-TV",
    url: "https://www.cbsnews.com/pittsburgh/news/allegheny-health-network-cigna-reach-agreement/",
    sourceType: "tv",
    channel: "media",
    headline: "AHN and Cigna reach 11th-hour deal — 1-year contract averts network disruption",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution coverage. '11th-hour' framing. 1-year deal signals temporary truce. AHN President James Benedict: 'This agreement is great news for the more than twenty thousand people in this region who are Cigna-insured.'",
  },
  {
    id: 12,
    date: "2023-06-29",
    source: "Pittsburgh Post-Gazette",
    sourceType: "news",
    channel: "media",
    headline: "Pittsburgh-based Allegheny Health Network inks new contract for Cigna members — 1-year deal",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Post-Gazette resolution story. Notes 1-year deal is short-term fix. Neither side disclosed rate specifics. Multi-year deal expected 'within the next couple of weeks.' Sets stage for 2025 round.",
  },
  {
    id: 13,
    date: "2023-06-29",
    source: "TribLIVE",
    sourceType: "news",
    channel: "media",
    headline: "AHN, Cigna ink 1-year contract, working on longer deal",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "'Working on longer deal' qualifier signals this is not a resolution. Tribune-Review notes both parties expect renewed negotiations. Cigna VP Mike Ungvary: 'The collaboration we have with Allegheny Health Network puts quality, affordable care in reach for people.'",
  },
  {
    id: 14,
    date: "2023-06-29",
    source: "HealthLeaders",
    sourceType: "news",
    channel: "media",
    headline: "Allegheny Health Network, Cigna reach agreement — trade press notes temporary nature",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press resolution. Notes 1-year term. Neither side disclosed financial terms. Audience: hospital executives and benefits professionals.",
  },

  // === 2023 ROUND — STAKEHOLDER ===
  {
    id: 15,
    date: "2023-06-15",
    source: "Dan Laurent, VP Corporate Communications, AHN",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "AHN VP: 'fully committed to continuing negotiations with Cigna in hopes that a new contract can be reached'",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Dan Laurent, VP Corporate Communications. 'Fair and equitable reimbursement rates' — establishes AHN's core talking point that carries into 2025 round. Steady professional tone.",
  },
  {
    id: 16,
    date: "2023-06-25",
    source: "Continuity of care protections (PA regulation)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Cancer patients and pregnant women would retain in-network pricing under continuity of care agreement even if contract lapses",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "REGULATORY CONTEXT. Active treatment patients (cancer, pregnancy) protected by continuity of care provisions. But majority of 20,000 members — routine care, chronic conditions — would need to switch providers or insurers immediately.",
  },

  // === 2025 ROUND — MEDIA ENTRIES ===
  {
    id: 17,
    date: "2025-06-04",
    source: "CBS Pittsburgh / KDKA-TV",
    sourceType: "tv",
    channel: "media",
    headline: "AHN warns Cigna contract may not be renewed — 20,000 commercial members at risk again",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Dispute goes public June 4. 'Again' framing connects to 2023 round — establishes pattern narrative. AHN letter to patients: 'unable to reach a fair and mutually acceptable agreement' after 'several months of negotiation.' Commercial-only dispute (not Medicare Advantage — Cigna sold Medicare business to HCSC in March 2025).",
  },
  {
    id: 18,
    date: "2025-06-05",
    source: "CBS Pittsburgh / KDKA-TV",
    sourceType: "tv",
    channel: "media",
    headline: "Cigna responds to AHN contract dispute — says AHN demanding 'unreasonably high rates'",
    frameAdoption: "cigna",
    sentiment: "negative_ahn",
    patientStory: false,
    blameDirection: "ahn",
    reachEstimate: "high",
    notes: "Cigna's primary public counter: 'unreasonably high rates that would significantly increase costs.' One of few media hits adopting Cigna frame. Notes majority of Cigna clients are employers who pay for health benefits — rate increases 'directly impact local companies, their employees and families.'",
  },
  {
    id: 19,
    date: "2025-06-07",
    source: "WPXI Pittsburgh",
    sourceType: "tv",
    channel: "media",
    headline: "Patients caught in middle of AHN-Cigna contract standoff for second time in two years",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "WPXI coverage. 'Second time in two years' is powerful framing — suggests systemic failure. Patient interviews. Repeated disruption creates cumulative anxiety.",
  },
  {
    id: 20,
    date: "2025-06-10",
    source: "TribLIVE",
    sourceType: "news",
    channel: "media",
    headline: "AHN-Cigna contract talks collapse again — Highmark Health cites $147M loss at AHN in 2024",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Key financial data: Highmark Health lost $147M at AHN in 2024. Invested $1.3B+ since 2018. Financial hardship framing strengthens AHN's rate increase justification. $674M system-wide loss projected for 2025.",
  },
  {
    id: 21,
    date: "2025-06-12",
    source: "Pittsburgh Post-Gazette",
    sourceType: "news",
    channel: "media",
    headline: "Allegheny Health Network says Cigna rates unsustainable as Highmark posts hundreds of millions in losses",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Post-Gazette deep dive. Financial framing: $147M AHN loss (2024), $674M Highmark system-wide (2025), $1.3B+ invested since 2018. Paper of record lending credibility to AHN's financial sustainability argument.",
  },
  {
    id: 22,
    date: "2025-06-14",
    source: "WPXI Pittsburgh",
    sourceType: "tv",
    channel: "media",
    headline: "AHN patients scramble for alternatives as Cigna contract deadline nears — limited options in UPMC-dominated market",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Second WPXI segment. Patient anxiety coverage. 'Scramble' framing creates urgency. Pittsburgh is a tight medical market — UPMC rivalry means AHN patients have limited alternatives. Most would need to switch insurers entirely.",
  },
  {
    id: 23,
    date: "2025-06-15",
    source: "KDKA Radio",
    sourceType: "radio",
    channel: "media",
    headline: "AHN-Cigna dispute returns to Pittsburgh talk radio — callers recall 2023 anxiety",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Talk radio segments. Callers reference 2023 round — cumulative fatigue with repeated disputes. Local vs national insurer narrative plays well in Pittsburgh's community-oriented media landscape.",
  },
  {
    id: 24,
    date: "2025-06-16",
    source: "Becker's Payer Issues",
    sourceType: "news",
    channel: "media",
    headline: "Cigna, Allegheny Health Network face July 1 split — second dispute in two years",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press. Notes Cigna sold Medicare business to HCSC in March 2025 — Medicare/Medicare Advantage patients not affected. 'Second dispute in two years' is the key framing point. Hospital executive and payer audience.",
  },
  {
    id: 25,
    date: "2025-06-18",
    source: "WFMJ Youngstown",
    sourceType: "tv",
    channel: "media",
    headline: "AHN-Cigna dispute impacts patients across western PA and eastern Ohio border region",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Youngstown market coverage. AHN's Saint Vincent Health (Erie) and Grove City Medical serve patients in eastern Ohio border region. These patients have even fewer alternatives. Expands geographic awareness beyond Pittsburgh metro.",
  },
  {
    id: 26,
    date: "2025-06-20",
    source: "WPXI Pittsburgh",
    sourceType: "tv",
    channel: "media",
    headline: "Here's the latest in the battle between AHN and Cigna over a new contract — 10 days remaining",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Third WPXI segment. 'Battle' framing. Countdown builds urgency. Balanced but anxiety-inducing. Patients urged to prepare for potential disruption.",
  },
  {
    id: 27,
    date: "2025-06-22",
    source: "Beaver County Radio",
    sourceType: "radio",
    channel: "media",
    headline: "Local radio covers AHN-Cigna dispute impact on Beaver County patients and families",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Hyperlocal radio. Beaver County is working-class community heavily dependent on AHN. Local framing: national insurer threatening community hospital access. Grassroots reach. AHN's Heritage Valley affiliation expands Beaver County footprint.",
  },
  {
    id: 28,
    date: "2025-06-24",
    source: "TribLIVE",
    sourceType: "news",
    channel: "media",
    headline: "AHN-Cigna talks resume but gap remains — Highmark Health's $674M projected loss adds urgency",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "TribLIVE update. $674M system-wide 2025 projection. Financial data continues to bolster AHN's justification narrative. 'Gap remains' signals deal not imminent.",
  },
  {
    id: 29,
    date: "2025-06-25",
    source: "CBS Pittsburgh / KDKA-TV",
    sourceType: "tv",
    channel: "media",
    headline: "AHN warns most Cigna customers could lose in-network coverage unless agreement is reached",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Deadline-week coverage. Patient: 'causing me some stress in my daily life.' AHN 'committed' to ensuring no care disruptions for active treatment patients, but most Cigna customers would 'need to either switch insurance companies or relocate to Cigna-covered medical facilities.'",
  },
  {
    id: 30,
    date: "2025-06-26",
    source: "HealthLeaders",
    sourceType: "news",
    channel: "media",
    headline: "Money dispute between Allegheny Health and Cigna could cost 20,000 residents",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press syndication of CBS Pittsburgh story. National healthcare executive audience. 'Money dispute' framing assigns shared responsibility. '20,000 residents' humanizes the impact.",
  },
  {
    id: 31,
    date: "2025-06-26",
    source: "Becker's Payer Issues",
    sourceType: "news",
    channel: "media",
    headline: "Cigna dispute count reaches 133 in 2024, up from 51 in 2022 — AHN among latest",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "KEY SYSTEMIC DATA. Cigna disputes: 51 (2022), 86 (2023), 133 (2024). 160% increase in two years. Positions AHN within escalating national pattern. Undermines 'AHN is uniquely unreasonable' framing.",
  },
  {
    id: 32,
    date: "2025-06-27",
    source: "KDKA Radio",
    sourceType: "radio",
    channel: "media",
    headline: "AHN-Cigna comes to 11th-hour deal to continue in-network coverage",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "KDKA Radio Audacy report. '11th-hour deal' framing. First outlet to break resolution news on radio. Pittsburgh commuter audience. Relief framing.",
  },
  {
    id: 33,
    date: "2025-06-28",
    source: "CBS Pittsburgh / KDKA-TV",
    sourceType: "tv",
    channel: "media",
    headline: "Allegheny Health Network and Cigna Healthcare announce 3-year contract agreement",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution coverage. 3-year deal through June 30, 2028 (vs 1-year in 2023). Cigna members with appointments scheduled for week of June 29 can keep them. Neither side disclosed rate specifics.",
  },
  {
    id: 34,
    date: "2025-06-28",
    source: "WPXI Pittsburgh",
    sourceType: "tv",
    channel: "media",
    headline: "AHN-Cigna 3-year deal ends weeks of uncertainty for Pittsburgh-area patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "WPXI resolution. 'Weeks of uncertainty' frames the dispute duration. Relief framing. 3-year term noted as improvement over 2023's 1-year stopgap.",
  },
  {
    id: 35,
    date: "2025-06-30",
    source: "Pittsburgh Post-Gazette",
    sourceType: "news",
    channel: "media",
    headline: "AHN renews Cigna Healthcare contract — 3-year deal ends second contract dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Post-Gazette wrap-up. 'Second contract dispute' framing reminds readers of pattern. Mark Sevco quote: 'This contract is fantastic news for the more than 20,000 Cigna members in this region who rely on AHN for their care.'",
  },
  {
    id: 36,
    date: "2025-06-30",
    source: "TribLIVE",
    sourceType: "news",
    channel: "media",
    headline: "AHN-Cigna 3-year deal provides stability after back-to-back contract fights",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "'Back-to-back' framing emphasizes repetitive dispute pattern. 'Stability' is the key word — both sides claim credit for longer-term resolution.",
  },
  {
    id: 37,
    date: "2025-06-28",
    source: "WFMJ Youngstown",
    sourceType: "tv",
    channel: "media",
    headline: "Allegheny Health Network, Cigna Healthcare announce three-year contract — Youngstown-area patients retain access",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Youngstown/eastern Ohio resolution coverage. AHN serves patients across state lines. Resolution announcement syndicated via press release distribution.",
  },
  {
    id: 38,
    date: "2025-06-30",
    source: "KDKA Radio (Audacy)",
    sourceType: "radio",
    channel: "media",
    headline: "AHN reaches new three-year deal with Cigna — full in-network access preserved",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Audacy digital. Notes new contract runs through June 30, 2028. Beneficiaries continue access to AHN's 14 hospitals and employed specialists.",
  },

  // === AHN OWNED MEDIA ===
  {
    id: 39,
    date: "2025-06-04",
    source: "AHN (patient notification letter)",
    sourceType: "owned",
    channel: "media",
    headline: "AHN letter to patients: 'unable to reach a fair and mutually acceptable agreement' with Cigna after months of negotiation",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Direct-to-patient letter. 'Fair and mutually acceptable' implies Cigna's offers are unfair. 'Months of negotiation' establishes AHN as having tried in good faith. 20,000 recipient base. Triggers local media coverage.",
  },
  {
    id: 40,
    date: "2025-06-04",
    source: "AHN (public statement via Dan Laurent)",
    sourceType: "owned",
    channel: "media",
    headline: "AHN VP Dan Laurent: 'We are seeking fair and equitable reimbursement rates from Cigna'",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "AHN's opening public statement. Dan Laurent, VP Corporate Communications. 'Fair and equitable' framing positions AHN as reasonable party. Notes $1.3B+ investment since 2018, $147M loss in 2024. Financial sustainability narrative.",
  },
  {
    id: 41,
    date: "2025-06-28",
    source: "AHN (press release)",
    sourceType: "owned",
    channel: "media",
    headline: "AHN President Mark Sevco: 'fantastic news for the more than 20,000 Cigna members who rely on AHN'",
    frameAdoption: "ahn",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution announcement. Mark Sevco (new AHN President, appointed March 2025): 'ensures continued, in-network access to AHN's expert clinicians, and to the exceptional-quality, high-value care that their members and our patients expect and deserve.' Victory framing — 'continued access' implies Cigna was threatening it.",
  },

  // === CIGNA OWNED MEDIA ===
  {
    id: 42,
    date: "2025-06-05",
    source: "Cigna (public statement)",
    sourceType: "owned",
    channel: "media",
    headline: "Cigna: AHN demanding 'unreasonably high rates that would significantly increase costs' for employers and families",
    frameAdoption: "cigna",
    sentiment: "negative_ahn",
    patientStory: false,
    blameDirection: "ahn",
    reachEstimate: "medium",
    notes: "Cigna's primary public counter. 'Unreasonably high rates' and 'significantly increase costs' are core talking points. Notes majority of Cigna clients are employers — frames AHN rate demands as burden on local businesses. Offered 'reasonable rate increases in line with other local providers.'",
  },
  {
    id: 43,
    date: "2025-06-28",
    source: "Cigna (press release)",
    sourceType: "owned",
    channel: "media",
    headline: "Cigna announces multi-year agreement with AHN — 'committed to affordable access for our customers'",
    frameAdoption: "cigna",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution statement. 'Affordable access' framing claims credit for cost containment. Conciliatory tone suggests Cigna felt local pressure. No financial terms disclosed.",
  },

  // === SOCIAL ENTRIES ===
  {
    id: 44,
    date: "2025-06-06",
    source: "AHN official (LinkedIn)",
    sourceType: "social",
    channel: "social",
    headline: "AHN LinkedIn post highlights $1.3B investment and commitment to western PA patients amid Cigna dispute",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "LinkedIn audience includes local employers and benefits decision-makers. $1.3B investment figure reinforces AHN's community commitment narrative. Professional tone suited to platform.",
  },
  {
    id: 45,
    date: "2025-06-10",
    source: "CBS Pittsburgh (Facebook)",
    sourceType: "social",
    channel: "social",
    headline: "CBS Pittsburgh Facebook post on AHN-Cigna dispute generates hundreds of comments from anxious patients",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Facebook comment sections skew anti-insurer in Pittsburgh market. Local community loyalty to AHN. Comments include patient stories about difficulty finding alternative providers in UPMC-dominated market. Highest social engagement for the dispute.",
  },
  {
    id: 46,
    date: "2025-06-15",
    source: "Social media (Pittsburgh community)",
    sourceType: "social",
    channel: "social",
    headline: "Pittsburgh community social media buzzes with AHN-Cigna frustration — 'not again'",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "'Not again' sentiment reflects cumulative fatigue from 2023 repeat. Local Facebook groups, Nextdoor, and Reddit r/pittsburgh discussions. Community frustration directed primarily at Cigna as outside entity disrupting local healthcare.",
  },
  {
    id: 47,
    date: "2025-06-20",
    source: "AHN official (LinkedIn)",
    sourceType: "social",
    channel: "social",
    headline: "AHN LinkedIn update: 'We remain committed to reaching a fair agreement that supports our patients'",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Second LinkedIn post. 'Fair agreement' implies Cigna's current offer is unfair. Professional audience engagement. Employee sharing amplifies reach among Pittsburgh business community.",
  },
  {
    id: 48,
    date: "2025-06-22",
    source: "Social media (Reddit r/pittsburgh)",
    sourceType: "social",
    channel: "social",
    headline: "Reddit r/pittsburgh threads discuss AHN-Cigna — users share frustration with limited provider options",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Reddit discussion. Users note UPMC-Highmark duopoly makes switching nearly impossible for many patients. 'Cigna is the smallest of the three insurers here and they still pull this.' Anti-corporate insurer sentiment. Younger demographic engagement.",
  },
  {
    id: 49,
    date: "2025-06-28",
    source: "AHN official (LinkedIn)",
    sourceType: "social",
    channel: "social",
    headline: "AHN LinkedIn announces 3-year Cigna resolution — celebrates stability for patients and community",
    frameAdoption: "ahn",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution post. Community commitment framing. Employee engagement likely high after weeks of uncertainty. Mark Sevco quote featured.",
  },

  // === STAKEHOLDER ENTRIES ===
  {
    id: 50,
    date: "2025-06-04",
    source: "Dan Laurent, VP Corporate Communications, AHN",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "AHN VP Dan Laurent: 'fair and equitable reimbursement rates' needed to sustain $1.3B investment in western PA healthcare",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Key AHN spokesperson. Financial data: $147M AHN loss (2024), $1.3B+ invested since 2018, $674M Highmark system-wide projected loss (2025). Positions rate increase as existential need, not profit-seeking.",
  },
  {
    id: 51,
    date: "2025-06-10",
    source: "Highmark Health financial disclosures",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Highmark Health reports $147M loss at AHN (2024), projects $674M system-wide loss for 2025",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "CRITICAL FINANCIAL CONTEXT. Highmark Health (AHN parent) lost $147M at AHN in 2024. $674M system-wide projected for 2025. $1.3B+ invested since 2018 acquisition of West Penn Allegheny. Financial hardship narrative is AHN's strongest factual argument for rate increases.",
  },
  {
    id: 52,
    date: "2025-06-15",
    source: "Pittsburgh market dynamics (UPMC-Highmark context)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "UPMC-Highmark rivalry limits patient alternatives — AHN patients cannot easily switch providers in constrained market",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "STRUCTURAL CONTEXT. Pittsburgh healthcare uniquely constrained by UPMC-Highmark rivalry (2011-2019 'cold war,' resolved by 10-year deal in 2019). Many AHN patients have Highmark insurance; Cigna members losing AHN would need to find non-UPMC, non-AHN providers or switch insurers entirely. Duopoly amplifies any network disruption.",
  },
  {
    id: 53,
    date: "2025-06-20",
    source: "Cigna national dispute pattern analysis",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Cigna provider disputes escalate nationally: 51 (2022), 86 (2023), 133 (2024) — AHN part of systemic pattern",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "PATTERN DATA. 160% increase in two years. Simultaneous 2025 disputes with UNC Health (NC, 65K patients), Piedmont Medical Center (SC), and others. AHN is not an outlier — Cigna is fighting providers nationally. Pattern evidence undermines 'AHN is unreasonable' framing.",
  },
  {
    id: 54,
    date: "2025-06-25",
    source: "Cigna Medicare divestiture (HCSC sale, March 2025)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Cigna sold Medicare business to HCSC in March 2025 — Medicare/Medicare Advantage patients not impacted by AHN dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "STRUCTURAL CONTEXT. Cigna sold Medicare-related business to Health Care Service Corp. (Chicago-based insurer) in March 2025. HCSC coverage of Medicare/Medicare Advantage patients unaffected by commercial dispute. Narrows impact to ~20,000 commercial members.",
  },
  {
    id: 55,
    date: "2025-06-25",
    source: "Government / regulatory (silence)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "No Pennsylvania government or regulatory intervention in AHN-Cigna dispute — market-driven resolution",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "SILENCE IS DATA. No PA governor, AG, or insurance commissioner public statements. No legislative hearings. Unlike CT (Hartford/UHC FAQ) or NC (UNC/Cigna drew legislative attention), Pennsylvania took hands-off approach. Market-driven resolution expected and delivered.",
  },
  {
    id: 56,
    date: "2023-06-29",
    source: "2023 resolution precedent",
    sourceType: "news",
    channel: "stakeholder",
    headline: "2023 round: 1-year deal resolved June 29 — short-term fix explicitly set stage for 2025 repeat",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "PRECEDENT. 2023's 1-year deal was explicitly a stopgap — both sides said multi-year deal would follow 'within weeks.' It never materialized, leading directly to 2025 round. The repeat validated concerns that 2023 didn't address underlying rate gap. 3-year 2025 deal suggests deeper resolution.",
  },
  {
    id: 57,
    date: "2025-06-28",
    source: "Mark Sevco, President, AHN",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "AHN President Sevco: 'ensures continued, in-network access to AHN's expert clinicians and exceptional-quality care'",
    frameAdoption: "ahn",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Mark Sevco (new AHN President, took over late March 2025 from Cynthia Hundorfean). First major public act in role was resolving Cigna dispute. 'Exceptional-quality, high-value care' — subtle dig at Cigna's unwillingness to pay for quality. Quoted across all Pittsburgh outlets.",
  },

  // === EMPLOYER ENTRIES ===
  {
    id: 58,
    date: "2025-06-05",
    source: "Cigna (employer/broker notification)",
    sourceType: "owned",
    channel: "employer",
    headline: "Cigna notifies employer clients: AHN may leave network July 1 — 'rate increases directly impact local companies'",
    frameAdoption: "cigna",
    sentiment: "negative_ahn",
    patientStory: false,
    blameDirection: "ahn",
    reachEstimate: "high",
    notes: "CRITICAL EMPLOYER CHANNEL. Cigna frames AHN as demanding rates that 'directly impact local companies, their employees and families.' Majority of Cigna's Pittsburgh clients are self-insured employers. If employers accept this framing, it pressures AHN. But employee healthcare disruption is a counter-pressure.",
  },
  {
    id: 59,
    date: "2025-06-12",
    source: "Pittsburgh employer benefits community",
    sourceType: "news",
    channel: "employer",
    headline: "Local HR professionals and benefits brokers begin contingency planning for potential AHN network loss",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Employer anxiety begins. Pittsburgh employers with Cigna plans face choice: absorb potential cost increases from AHN or disrupt employee care. In a market where AHN operates 14 hospitals, network loss creates significant workforce impact. Benefits brokers prepare alternative provider maps.",
  },
  {
    id: 60,
    date: "2025-06-20",
    source: "Cigna employer messaging",
    sourceType: "owned",
    channel: "employer",
    headline: "Cigna to employers: 'We offered AHN reasonable rate increases in line with other local providers' — positions AHN as outlier",
    frameAdoption: "cigna",
    sentiment: "negative_ahn",
    patientStory: false,
    blameDirection: "ahn",
    reachEstimate: "medium",
    notes: "Cigna's STRONGEST employer argument. 'In line with other local providers' positions AHN as demanding above-market rates. But AHN's $147M loss data and $1.3B investment counter this framing — other providers may not face same financial pressures.",
  },
  {
    id: 61,
    date: "2025-06-25",
    source: "AHN employer-facing communications",
    sourceType: "owned",
    channel: "employer",
    headline: "AHN reaches out to local employers: '$1.3B invested since 2018 — sustainable rates needed to protect community healthcare'",
    frameAdoption: "ahn",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "AHN's employer counter-messaging. Community investment narrative resonates with Pittsburgh-based employers. $1.3B figure and Allegheny General Hospital $1B expansion plan demonstrate long-term commitment. Frames rate increases as protecting local healthcare infrastructure.",
  },
  {
    id: 62,
    date: "2025-06-28",
    source: "Pittsburgh business community (resolution reaction)",
    sourceType: "news",
    channel: "employer",
    headline: "Local employers relieved by AHN-Cigna 3-year deal — stability reduces benefits planning uncertainty",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "3-year term (through June 2028) gives employers stability through multiple benefits renewal cycles. Eliminates annual brinksmanship risk that characterized 2023-2025 period. Both sides framed as having reached reasonable compromise.",
  },
];

const LABELS = {
  frameAdoption: { ahn: "AHN Frame", cigna: "Cigna Frame", balanced: "Balanced" },
  sentiment: {
    negative_cigna: "Anti-Cigna",
    negative_ahn: "Anti-AHN",
    neutral: "Neutral",
    positive_cigna: "Pro-Cigna",
    positive_ahn: "Pro-AHN",
  },
  blameDirection: { cigna: "Blames Cigna", ahn: "Blames AHN", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National record / major trade (1.5)
  "Becker's Payer Issues": 1.5, "HealthLeaders": 1.5,
  // Tier 2 — Regional authority (1.2)
  "CBS Pittsburgh / KDKA-TV": 1.2, "WPXI Pittsburgh": 1.2, "Pittsburgh Post-Gazette": 1.2,
  "TribLIVE": 1.2, "WFMJ Youngstown": 1.2,
  // Tier 3 — Trade/niche (1.0)
  "Becker's Hospital Review": 1.0, "KDKA Radio": 1.0, "KDKA Radio (Audacy)": 1.0,
  "Beaver County Radio": 1.0,
  // Tier 4 — Organic social (0.7)
  "CBS Pittsburgh (Facebook)": 0.7, "Social media (Pittsburgh community)": 0.7,
  "Social media (Reddit r/pittsburgh)": 0.7,
  // Tier 5 — Comment sections / forums (0.4)
  // (No dedicated entries — comment-level data captured in notes of social entries)
  // Tier 6 — Owned/party media (0.3)
  "AHN (patient notification letter)": 0.3, "AHN (public statement via Dan Laurent)": 0.3,
  "AHN (press release)": 0.3, "AHN official (LinkedIn)": 0.3,
  "AHN employer-facing communications": 0.3,
  "Cigna (patient warning letter)": 0.3, "Cigna (public statement)": 0.3,
  "Cigna (press release)": 0.3, "Cigna (employer/broker notification)": 0.3,
  "Cigna employer messaging": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "Dan Laurent, VP Corporate Communications, AHN": 1.3, "Dan Laurent, VP, AHN": 1.3,
  "Mark Sevco, President, AHN": 1.3,
  "Highmark Health financial disclosures": 1.3,
  "Pittsburgh market dynamics (UPMC-Highmark context)": 1.3,
  "Cigna national dispute pattern analysis": 1.3,
  "Cigna Medicare divestiture (HCSC sale, March 2025)": 1.3,
  "Continuity of care protections (PA regulation)": 1.3,
  "Government / regulatory (silence)": 1.3,
  "2023 resolution precedent": 1.3,
  // Tier 8 — Employer/Benefits (1.5x trade, 1.0x broker)
  "Pittsburgh employer benefits community": 1.5,
  "Pittsburgh business community (resolution reaction)": 1.0,
};

const SEARCH_TRENDS = [
  // 2023 round
  { week: "2023-05-22", interest: 8 },
  { week: "2023-05-29", interest: 10 },
  { week: "2023-06-05", interest: 15 },
  { week: "2023-06-12", interest: 45 },
  { week: "2023-06-19", interest: 70 },
  { week: "2023-06-26", interest: 100 },
  { week: "2023-07-03", interest: 25 },
  { week: "2023-07-10", interest: 8 },
  // gap
  { week: "2025-05-05", interest: 5 },
  { week: "2025-05-12", interest: 5 },
  { week: "2025-05-19", interest: 5 },
  { week: "2025-05-26", interest: 5 },
  { week: "2025-06-02", interest: 60 },
  { week: "2025-06-09", interest: 50 },
  { week: "2025-06-16", interest: 50 },
  { week: "2025-06-23", interest: 70 },
  { week: "2025-06-30", interest: 95 },
  { week: "2025-07-07", interest: 20 },
  { week: "2025-07-14", interest: 5 },
  { week: "2025-07-21", interest: 5 },
];

export default {
  active: false,
  // Identity
  providerKey: "ahn",
  payorKey: "cigna",
  providerName: "Allegheny Health Network",
  payorName: "Cigna",
  providerShort: "AHN",
  payorShort: "Cigna",
  navShort: "AHN v. Cigna",
  title: "AHN vs Cigna",
  subtitle: "Contract dispute · Pittsburgh · Resolved June 28, 2025 (3-year deal)",
  gradientId: "ahncigna",

  // Dates
  monitorStart: "May 1, 2023",
  monitorEnd: "July 31, 2025",
  disputePublicDate: "2023-05-24",

  // Colors
  colors: {
    providerColor: "#1B4D8E",
    payorColor: "#E87722",
    neutral: "#64748B",
    accent: "#1B4D8E",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#1B4D8E", "#7A6058", "#E87722"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"allegheny health network cigna" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.42,
    nationalMedian: 1.0,
    networkComplaints: 892,
    priorYearComplaints: 614,
    regulatorAction: "No Pennsylvania government or regulatory intervention. No public statements from PA governor, AG, or insurance commissioner. Market-driven resolution in both 2023 and 2025 rounds.",
    signalRead: "Cigna's national dispute count escalated 160% from 51 (2022) to 133 (2024), indicating a corporate strategy of aggressive rate negotiations across its provider network. AHN is part of a systemic pattern that also includes UNC Health (NC), Piedmont Medical (SC), and others. Pittsburgh's UPMC-Highmark duopoly amplifies disruption risk for any network change, making Cigna's negotiating posture particularly high-stakes in this market.",
  },

  talkingPoints: {
    provider: [
      { name: "Fair & equitable reimbursement", keywords: ["fair and equitable", "fair.*reimbursement", "equitable.*rate", "sustainable.*rate"] },
      { name: "$147M loss / financial hardship", keywords: ["\\$147M", "147M.*loss", "\\$674M", "674M.*loss", "\\$1\\.3B.*invest", "1\\.3 billion", "hundreds of millions"] },
      { name: "20,000 patients at risk", keywords: ["20,?000", "20K", "patients.*lose", "lose.*access", "14 hospitals"] },
      { name: "Repeat dispute / pattern offender", keywords: ["second time", "not again", "back-to-back", "repeat", "2023.*2025", "two years"] },
      { name: "Cigna national dispute escalation", keywords: ["51.*2022", "133.*2024", "160%", "dispute.*escalat", "systemic pattern", "dozens of providers"] },
      { name: "UPMC duopoly / limited alternatives", keywords: ["UPMC", "duopoly", "limited.*alternative", "constrained market", "cannot.*switch", "limited.*option"] },
      { name: "$1.3B community investment", keywords: ["\\$1\\.3B", "\\$1B.*expansion", "allegheny general.*expansion", "invested.*western PA", "community.*investment"] },
      { name: "Patient anxiety / community impact", keywords: ["scramble", "anxious", "anxiety", "people.*health", "difficult.*find.*doctor", "please keep in mind"] },
    ],
    payor: [
      { name: "Unreasonably high rates", keywords: ["unreasonably high", "unreasonable.*rate", "significantly increase cost"] },
      { name: "Employer cost impact", keywords: ["employer.*pay", "local companies", "directly impact", "families.*cost", "rate.*impact.*compan"] },
      { name: "AHN dropping Cigna framing", keywords: ["AHN.*drop", "dropping.*cigna", "pay more.*if.*drop"] },
      { name: "Affordable quality care", keywords: ["affordable.*care", "quality.*affordable", "affordable.*quality", "in reach for people"] },
      { name: "Cigna Medicare divestiture", keywords: ["Medicare.*HCSC", "sold.*Medicare", "divestiture", "Medicare.*not.*impact"] },
      { name: "3-year deal = stability", keywords: ["3-year", "three-year", "long-term", "stability", "through.*2028"] },
    ],
  },

  // Executive summary
  executiveSummary: {
    statement: "Two-round dispute (2023 and 2025) resolved with progressively longer terms — 1-year stopgap in 2023, 3-year deal through June 2028 in 2025 — suggesting the underlying rate gap was eventually addressed. No actual network disruption occurred in either round, but cumulative patient anxiety and media coverage favored AHN's position.",
    keyMessages: [
      "Highmark Health's $147M loss at AHN (2024) and $1.3B+ investment since 2018 are the stickiest financial arguments for rate increases — hard for Cigna to counter with pure 'affordability' framing.",
      "The repeat-dispute pattern (2023 then 2025) created cumulative patient anxiety and media fatigue that worked against Cigna's position as the perceived aggressor.",
      "Cigna's national dispute escalation (51 to 133 in two years) undermines any framing that AHN is uniquely unreasonable — AHN is one of dozens of providers in similar fights.",
      "Pittsburgh's UPMC-Highmark duopoly means AHN patients have genuinely limited alternatives — network disruption carries outsized real-world impact compared to other markets.",
      "Cigna's March 2025 Medicare divestiture to HCSC narrowed the dispute to ~20,000 commercial members, reducing the total affected population but concentrating impact on employer-sponsored plans.",
    ],
    marcomm: [
      "<strong>Repeat disputes are a PR liability for the insurer.</strong> The 'not again' sentiment from 2023 created a pre-loaded narrative of Cigna as a serial disruptor. AHN benefited from community sympathy that compounded across rounds.",
      "<strong>Financial transparency was AHN's strongest weapon.</strong> Publishing specific loss figures ($147M, $674M, $1.3B invested) gave media concrete data points and made 'fair reimbursement' claims credible rather than abstract. Cigna's counter ('unreasonably high rates') lacked equivalent specificity.",
      "<strong>Pittsburgh's local-vs-national dynamic favors the provider.</strong> AHN is a community institution backed by Highmark (local Blue Cross); Cigna is a national corporation. In a market shaped by the UPMC-Highmark rivalry, local loyalty runs deep and outsider insurers face structural sympathy deficits.",
      "<strong>The 3-year deal signals both sides learned from 2023.</strong> The longer term reduces brinksmanship risk and suggests Cigna accepted the reputational cost of repeated public disputes was not worth the negotiating leverage gained.",
      "<strong>Employer channel was Cigna's best argument.</strong> Framing rate increases as 'directly impacting local companies and families' was Cigna's most effective counter-narrative, but it was overwhelmed by patient anxiety stories and AHN's financial hardship data.",
    ],
  },
  channelTakeaways: {
    media: [
      "CBS Pittsburgh / KDKA-TV was the dominant outlet across both rounds — Jon Delano (2023) and Bartos/Damp (2025) drove the narrative arc with the most segments and deepest sourcing.",
      "Pittsburgh Post-Gazette and TribLIVE provided the financial depth coverage (Highmark losses, investment figures) that strengthened AHN's position with data-driven reporting.",
      "Trade press (Becker's, HealthLeaders) framed AHN within the national Cigna dispute escalation pattern (51 to 133 disputes in two years), normalizing AHN's stance.",
      "WFMJ Youngstown and Beaver County Radio extended geographic awareness beyond Pittsburgh metro, reaching underserved AHN patient communities in border regions.",
      "KDKA Radio talk segments generated organic patient advocacy — caller-driven format amplified anti-Cigna sentiment in Pittsburgh's blue-collar media landscape.",
    ],
    social: [
      "CBS Pittsburgh Facebook posts generated the highest social engagement — comment sections ran heavily anti-Cigna with patient stories about limited alternatives in the UPMC-dominated market.",
      "AHN's LinkedIn strategy targeted employers and benefits decision-makers with investment and financial loss data — appropriate platform-audience match for the employer cost debate.",
      "Reddit r/pittsburgh threads reflected younger demographic engagement and highlighted the UPMC-Highmark duopoly as a structural barrier to switching providers.",
      "Pittsburgh community social media (Nextdoor, local Facebook groups) reflected 'not again' fatigue from repeated disputes — cumulative sentiment worked against Cigna.",
      "Cigna had minimal social presence in the dispute — no visible counter-narrative on social platforms beyond formal statements.",
    ],
    stakeholder: [
      "Dan Laurent (AHN VP Corporate Communications) was the primary spokesperson through both rounds — 'fair and equitable reimbursement' became the defining AHN sound bite.",
      "Highmark Health financial disclosures ($147M loss, $1.3B investment, $674M projection) were the strongest evidence supporting AHN's rate increase justification.",
      "Mark Sevco (new AHN President, March 2025) delivered the resolution statement — first major public act signaled leadership continuity on Cigna negotiations.",
      "UPMC-Highmark market dynamics created a structural backdrop that made any network disruption uniquely consequential in Pittsburgh vs other markets.",
      "Government silence from Pennsylvania officials in both rounds suggests the dispute was expected to resolve without regulatory intervention — and it did both times.",
    ],
    employer: [
      "Commercial-only dispute (not Medicare Advantage post-HCSC sale) meant employer-sponsored plans were the primary affected population — approximately 20,000 Cigna commercial members.",
      "Cigna's 'rate increases directly impact local companies' was its strongest employer-facing argument but lacked the emotional weight of patient disruption stories.",
      "AHN's employer counter-messaging ($1.3B invested, $1B Allegheny General expansion) framed rate increases as protecting community healthcare infrastructure that employers depend on.",
      "The 3-year deal term provides employer stability through multiple benefits renewal cycles, reducing annual brinksmanship risk that characterized 2023-2025.",
      "Pittsburgh benefits brokers were key intermediaries — their contingency planning visibility signaled dispute severity to the employer community.",
    ],
  },
  arguments: {
    payor: [
      { phase: "2023 Round (May–Jun 2023)", points: ["Cigna mailed patient warning letters framing AHN as the party <strong>'dropping' Cigna</strong> — preemptive blame-shifting", "Told patients <strong>'You'll likely pay more'</strong> if AHN drops Cigna, centering cost to members", "VP Mike Ungvary at resolution: 'The collaboration we have with Allegheny Health Network puts quality, affordable care in reach for people'"] },
      { phase: "2025 Round — Early (Jun 2025)", points: ["Claimed AHN was demanding <strong>'unreasonably high rates that would significantly increase costs'</strong>", "Argued that most Cigna clients are <strong>employers who pay for health benefits</strong> — rate increases 'directly impact local companies, their employees and families'"] },
      { phase: "2025 Round — Resolution (Jun 2025)", points: ["Agreed to a <strong>3-year deal</strong> through June 30, 2028 — significant improvement over 2023's 1-year stopgap", "Framed resolution as ensuring 'affordable, quality care' for Pittsburgh-area patients"] },
    ],
    provider: [
      { phase: "2023 Round (May–Jun 2023)", points: ["VP Dan Laurent established core talking point: seeking <strong>'fair and equitable reimbursement rates'</strong>", "Directed patients to pressure Cigna — call-to-action framing positioned AHN as patient advocate", "Secured 1-year deal; AHN President James Benedict: <strong>'great news for the more than twenty thousand people'</strong>"] },
      { phase: "2025 Round — Early (Jun 2025)", points: ["Cited Highmark Health's <strong>$147M loss at AHN in 2024</strong> and $1.3B+ invested since 2018 as evidence rates are unsustainable", "Leveraged Becker's systemic data: <strong>Cigna disputes rose 160% in two years</strong> (51 in 2022 to 133 in 2024) — AHN is not uniquely unreasonable", "'Second time in two years' framing established Cigna as a <strong>pattern offender</strong> in Pittsburgh"] },
      { phase: "2025 Round — Resolution (Jun 2025)", points: ["Secured a 3-year agreement — long-term stability vs 2023's stopgap 1-year deal signals meaningful rate improvement", "Neither side disclosed rate specifics, but deal length suggests AHN achieved closer to fair market terms"] },
    ],
  },
  timeline: [
    { date: "2023-05-24", type: "newsBreak", label: "Round 1 news breaks publicly" },
    { date: "2023-06-30", type: "termination", label: "Round 1 contract deadline" },
    { date: "2023-06-29", type: "agreement", label: "Round 1 one-year deal" },
    { date: "2025-05-15", type: "newsBreak", label: "Round 2 news breaks publicly" },
    { date: "2025-06-30", type: "termination", label: "Round 2 contract deadline" },
    { date: "2025-06-28", type: "agreement", label: "Round 2 three-year deal" },
  ],
};
