// Blue Cross Blue Shield of Michigan vs Michigan Medicine — PR War Room Config
// Dispute period: February–March 2026. Ongoing as of March 26, 2026.

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2026-03-04",
    source: "Detroit News",
    url: "https://www.detroitnews.com/story/business/2026/03/04/blue-cross-michigan-medicine-contract-dispute-could-affect-300000/88986056007/",
    sourceType: "news",
    channel: "media",
    headline: "Blue Cross, Michigan Medicine dispute puts 300K patients up in the air",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "Lead with 300K patients affected. Both sides quoted but MM rebuttal gets last word.",
  },
  {
    id: 2,
    date: "2026-03-05",
    source: "WNEM / WILX",
    url: "https://www.wilx.com/2026/03/05/michigan-medicine-warns-it-may-stop-taking-some-blue-cross-plans-july/",
    sourceType: "tv",
    channel: "media",
    headline: "Michigan Medicine warns it may stop taking some Blue Cross plans",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Straight news. Both 44% and 30% claims presented without challenge.",
  },
  {
    id: 3,
    date: "2026-03-05",
    source: "WXYZ",
    url: "https://www.wxyz.com/news/michigan-medicine-to-drop-some-blue-cross-plans-if-contract-deal-not-reached-by-june-30",
    sourceType: "tv",
    channel: "media",
    headline: "Michigan Medicine to drop some Blue Cross plans if deal not reached",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "14yo Crohn's patient story. Mother quote: 'I freaked out.' Very sympathetic to MM.",
  },
  {
    id: 4,
    date: "2026-03-04",
    source: "BCBSM (mibluedaily.com)",
    url: "https://www.bcbsm.mibluedaily.com/stories/affordabilitycontent/what-s-behind-the-university-of-michigan-health-system-contract-dispute-with-blue-cross",
    sourceType: "owned",
    channel: "media",
    headline: "What's Behind the UM Health System Contract Dispute with Blue Cross?",
    frameAdoption: "bcbs",
    sentiment: "negative_mm",
    patientStory: false,
    blameDirection: "mm",
    reachEstimate: "medium",
    notes: "Owned media. Frames MM as demanding 44% hike. Positions BCBS as affordability champion.",
  },
  {
    id: 5,
    date: "2026-03-10",
    source: "Michigan Advance",
    url: "https://michiganadvance.com/2026/03/10/blue-cross-blue-shield-and-michigan-medicine-contract-dispute-creates-concerns-among-patients/",
    sourceType: "news",
    channel: "media",
    headline: "Contract dispute creates concerns among patients",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "medium",
    notes: "MSU expert says MM has 'extremely sympathetic case.' BCBS has 70% market power framing.",
  },
  {
    id: 6,
    date: "2026-03-10",
    source: "Crain's Detroit Business",
    url: "https://www.crainsdetroit.com/health-care/whats-behind-blue-cross-michigan-medicine-contract-dispute",
    sourceType: "news",
    channel: "media",
    headline: "What's behind Blue Cross-Michigan Medicine contract dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CEO interviews from both sides. Most balanced coverage. Notes MM $233M operating income.",
  },
  {
    id: 7,
    date: "2026-03-19",
    source: "Detroit News",
    url: "https://www.detroitnews.com/story/news/local/michigan/2026/03/19/michigan-blue-cross-blue-shield-contract-fight-disputed-um-university-michigan-president-grasso/89232085007/",
    sourceType: "news",
    channel: "media",
    headline: "UM interim president disputes Blue Cross contract fight claims",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "University president escalation. Accuses BCBS of 'not telling the full truth.'",
  },
  {
    id: 8,
    date: "2026-03-23",
    source: "WEMU",
    url: "https://www.wemu.org/wemu-news/2026-03-23/michigan-medicine-blue-cross-blue-shield-of-michigan-still-fighting-over-new-contract",
    sourceType: "radio",
    channel: "media",
    headline: "Michigan Medicine - BCBSM still fighting over new contract",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "low",
    notes: "NPR affiliate. Quotes president saying BCBS 'shared inaccuracies and untrue claims.'",
  },
  {
    id: 15,
    date: "2026-03-04",
    source: "Bridge Michigan",
    url: "https://bridgemi.com/michigan-health-watch/blue-cross-michigan-medicine-dispute-leaves-300000-patients-in-lurch/",
    sourceType: "news",
    channel: "media",
    headline: "Blue Cross, Michigan Medicine dispute leaves 300,000 patients in lurch",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Most data-rich coverage. Notes BCBS $246M loss in 2025 (5yr trend) vs MM $234M operating income. Contextualizes within broader MI healthcare turmoil. Relatively balanced but BCBS financial weakness exposed.",
  },
  {
    id: 16,
    date: "2026-03-05",
    source: "CBS Detroit",
    url: "https://www.cbsnews.com/detroit/news/michigan-medicine-will-drop-blue-cross-blue-shield-members-if-deal-isnt-reached/",
    sourceType: "tv",
    channel: "media",
    headline: "Michigan Medicine will drop thousands of BCBS members if deal isn't reached",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Notes BCBSM has not made profit in 5 years. Gives BCBS affordability argument fair airing. Both claims presented.",
  },
  {
    id: 17,
    date: "2026-03-05",
    source: "Michigan Public (NPR)",
    url: "https://www.michiganpublic.org/health/2026-03-05/blue-cross-insured-patients-unaffiliated-with-u-of-m-could-lose-access-to-michigan-medicine-care",
    sourceType: "radio",
    channel: "media",
    headline: "Blue Cross-insured patients could lose access to Michigan Medicine care",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "medium",
    notes: "Quotes MM COO on fair compensation. BCBS 'affordability' frame gets less space. Disclosure: UM holds Michigan Public's broadcast license.",
  },
  {
    id: 18,
    date: "2026-03-05",
    source: "ClickOnDetroit (WDIV)",
    url: "https://www.clickondetroit.com/news/local/2026/03/05/could-be-life-threatening-michigan-medicine-blue-cross-negotiations-could-disrupt-care-for-thousands/",
    sourceType: "tv",
    channel: "media",
    headline: "'Could be life-threatening' — negotiations could disrupt care for thousands",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "Devastating patient story: mother of developmentally disabled son says 'it could be life-threatening.' MM COO quoted on modest increases. Strongest emotional framing found.",
  },
  {
    id: 19,
    date: "2026-03-05",
    source: "DBusiness Magazine",
    url: "https://www.dbusiness.com/daily-news/michigan-medicine-threatens-to-block-blue-cross-blue-shield-customers-starting-july-1/",
    sourceType: "news",
    channel: "media",
    headline: "Michigan Medicine Threatens to Block BCBS Customers Starting July 1",
    frameAdoption: "bcbs",
    sentiment: "negative_mm",
    patientStory: false,
    blameDirection: "mm",
    reachEstimate: "low",
    notes: "Headline frames MM as aggressor ('threatens to block'). Leads with BCBS's 44% claim. BCBS comms VP: 'Causing people to worry is no way to win an argument over money.' Rare BCBS-favorable framing.",
  },
  {
    id: 20,
    date: "2026-03-07",
    source: "Detroit Free Press (via Yahoo/AOL syndication)",
    url: "https://www.yahoo.com/news/articles/blue-cross-michigan-medicine-contract-165503257.html",
    sourceType: "news",
    channel: "media",
    headline: "Blue Cross, Michigan Medicine contract fight: What patients should know",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Comprehensive FAQ format. Notes analyst: '90% of these disputes end in agreement.' Students losing access to UHC services angle. Wide syndication (Yahoo, AOL, others).",
  },
  {
    id: 51,
    date: "2026-03-05",
    source: "ClickOnDetroit (WDIV)",
    url: "https://www.clickondetroit.com/news/local/2026/03/05/could-be-life-threatening-michigan-medicine-blue-cross-negotiations-could-disrupt-care-for-thousands/",
    sourceType: "tv",
    channel: "media",
    headline: "Collin Shuler (developmentally disabled): mother Kelly says dispute 'could be life-threatening'",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "Kelly Shuler's son Collin is developmentally disabled, covered by BCBS, long-time MM patient. As he ages, medical needs increasing. Quote: 'I have enough stress. This just capitalizes on that. It's horrible.' 'Their decision and their lack of coming to the table negotiating is going to be devastating and catastrophic. It could be life-threatening to many people.' Directly blames BCBS for not negotiating. Andy Hetzel (BCBS VP Comms): 'Everybody is frustrated with the cost of their health insurance.' Luanne Thomas Ewald (MM COO): 'What we have proposed are really modest. Singular digit increases.'",
  },
  {
    id: 52,
    date: "2026-03-05",
    source: "WXYZ",
    url: "https://www.wxyz.com/news/michigan-medicine-to-drop-some-blue-cross-plans-if-contract-deal-not-reached-by-june-30",
    sourceType: "tv",
    channel: "media",
    headline: "14-year-old Crohn's patient needs monthly infusions at Mott Children's Hospital — may lose access",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "Diagnosed with Crohn's at age 8, now 14. Receives monthly infusions at C.S. Mott Children's Hospital since diagnosis. Mother's quote about 'freaking out.' Children's hospital angle is extremely sympathetic — Mott is beloved in Michigan. If BCBS is seen as threatening access to a children's hospital, it's a PR disaster.",
  },
  {
    id: 53,
    date: "2026-03-02",
    source: "BCBSM (mibluedaily.com)",
    url: "https://www.bcbsm.mibluedaily.com/stories/our-news/blue-cross-blue-shield-of-michigan-informs-customers-and-members-of-michigan-medicine-s-decision-to-lock-blue-cross-members-out-starting-july-1",
    sourceType: "owned",
    channel: "media",
    headline: "BCBS notifies 300K members: 'Michigan Medicine's Decision to Lock Blue Cross Members Out Starting July 1'",
    frameAdoption: "bcbs",
    sentiment: "negative_mm",
    patientStory: false,
    blameDirection: "mm",
    reachEstimate: "high",
    notes: "BCBS's key PR move: framing the notification as 'MM is locking you out.' Language: 'Michigan Medicine is CHOOSING to remove its southeast Michigan facilities.' Frames MM as the aggressor. Also notifying employers — employer channel is where BCBS has strongest leverage (large self-insured accounts). Counter to MM's organized patient campaign.",
  },
  {
    id: 54,
    date: "2026-03-10",
    source: "Michigan Daily (student newspaper)",
    url: "https://www.michigandaily.com/news/administration/michigan-medicine-sets-deadline-for-blue-cross-blue-shield-of-michigan-contract-negotiations/",
    sourceType: "news",
    channel: "media",
    headline: "Student newspaper covers impact on UM students — Amina Ignatius: 'a lot more convenient to access on campus'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "LSA junior Amina Ignatius (neurophysiology research asst) quoted. Students on Domestic/International Student Health Insurance Plans retain UHC campus clinic access but may lose access to other MM facilities. BCBS later announced it will cover UM students at campus clinics at in-network rates regardless — a tactical concession. Andy Hetzel: 'When their rationale is that we are unique and special, we recognize that, but we do not agree.' Mary Masson (MM): 'We treat the sickest of the sick.'",
  },
  {
    id: 55,
    date: "2026-03-10",
    source: "Ann Arbor Today (nationaltoday.com)",
    url: "https://nationaltoday.com/us/mi/ann-arbor/news/2026/03/10/university-of-michigan-students-to-remain-covered-by-blue-cross-at-campus-clinics/",
    sourceType: "news",
    channel: "media",
    headline: "University of Michigan Students to Remain Covered by Blue Cross at Campus Clinics",
    frameAdoption: "bcbs",
    sentiment: "positive_bcbs",
    patientStory: false,
    blameDirection: "mm",
    reachEstimate: "medium",
    notes: "BCBS tactical win: announced students will retain campus clinic access at in-network rates even if contract ends. Protects BCBS from 'threatening student healthcare' narrative. Smart PR move — isolates the dispute to the broader 300K commercial population.",
  },
  {
    id: 58,
    date: "2026-03-04",
    source: "Bridge Michigan",
    url: "https://bridgemi.com/michigan-health-watch/blue-cross-michigan-medicine-dispute-leaves-300000-patients-in-lurch/",
    sourceType: "news",
    channel: "media",
    headline: "Bridge Michigan deep dive: BCBS $246M loss vs MM $234M operating income — financial asymmetry",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Most data-rich coverage of the dispute. Key comparison: BCBS lost $246M in 2025 while MM earned $234M operating income. Contextualizes within broader MI healthcare turmoil (Corewell/UHC, Trinity/Aetna). Notes BCBS paid $2.6B MORE for medical/pharmacy in 2025 vs 2024. 'Big 3' framework: Corewell and HFH signed, MM sole holdout. BCBS financial weakness exposed but also lends credibility to affordability argument.",
  },
  {
    id: 60,
    date: "2026-03-05",
    source: "ABC12 Flint",
    sourceType: "tv",
    channel: "media",
    headline: "Michigan Medicine may leave Blue Cross Blue Shield network — Flint-area coverage",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Extends coverage beyond Ann Arbor/Detroit to Flint market. Demonstrates geographic breadth of the dispute's impact across southeast Michigan. Straight news reporting.",
  },
  {
    id: 61,
    date: "2026-03-12",
    source: "Live Insurance News",
    url: "https://www.liveinsurancenews.com/michigan-medicine-blue-cross/8570134/",
    sourceType: "news",
    channel: "media",
    headline: "Patients in the Crossfire: Michigan Medicine and Blue Cross Blue Shield Contract Dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Insurance industry blog/trade. 'He-said, she-said' framing. Notes BCBS has ~70% market power in Michigan. Headline 'patients in the crossfire' frames both parties as responsible. Trade audience.",
  },
  {
    id: 62,
    date: "2026-03-05",
    source: "WOWO News/Talk (Indiana syndication)",
    sourceType: "radio",
    channel: "media",
    headline: "300,000 Patients Could Lose In-Network Access — story picked up by out-of-state outlets",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Indiana outlet carrying MI story — signals geographic spread beyond Michigan. 300K figure is attention-getting even for audiences outside the dispute area.",
  },
  {
    id: 63,
    date: "2026-03-10",
    source: "InsuranceNewsNet (syndicated from MI Advance)",
    url: "https://insurancenewsnet.com/oarticle/blue-cross-blue-shield-and-michigan-medicine-contract-dispute-creates-concerns-among-patients",
    sourceType: "news",
    channel: "media",
    headline: "Michigan Advance story syndicated nationally via InsuranceNewsNet",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National insurance industry syndication of Michigan Advance's patient concerns story. Extends reach to insurance professionals nationally. Also syndicated to News From The States (national policy network).",
  },
  {
    id: 66,
    date: "2026-03-05",
    source: "Blue Water Healthy Living (syndicated from Free Press/Yahoo)",
    url: "https://bluewaterhealthyliving.com/news/local-news/michigan/blue-cross-michigan-medicine-contract-fight-what-patients-should-know/",
    sourceType: "news",
    channel: "media",
    headline: "Blue Cross, Michigan Medicine contract fight: What patients should know — wide syndication",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Free Press FAQ story syndicated to Yahoo, AOL, Blue Water Healthy Living, and others. Widest-reach balanced coverage. Notes analyst estimate: '90% of these disputes end in agreement.' Student access angle. Comprehensive FAQ format serves patients but doesn't clearly blame either side.",
  },
  {
    id: 68,
    date: "2026-03-10",
    source: "Crain's Detroit Business",
    url: "https://www.crainsdetroit.com/health-care/whats-behind-blue-cross-michigan-medicine-contract-dispute",
    sourceType: "news",
    channel: "media",
    headline: "Crain's deep dive: Tricia Keith 'This is about affordability' vs David Miller 'balance affordability with access'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Dustin Walsh. Keith (BCBSM CEO): 'This is about affordability for our members. They are a wealthy system getting bigger.' Miller (MM CEO): 'We need to find a balance where affordability doesn't come with limiting access. We take care of patients from all across the state, often from other systems.' Key data: MM inpatient 163% of Medicare (peers 206%), outpatient 212% of Medicare (peers 310%). Michigan hospital avg 189% of Medicare (3rd lowest nationally). MM operating at 95% capacity (recommended max 85%). 47,554 annual discharges, 312,436 patient days. 78% rate providers 4.9/5 stars. $2B recent expansion: $920M Kahn Pavilion, $800M Sparrow acquisition. 1,300 jobs eliminated at BCBSM in 2025.",
  },
  {
    id: 69,
    date: "2026-03-05",
    source: "Michigan Public (NPR)",
    url: "https://www.michiganpublic.org/health/2026-03-05/blue-cross-insured-patients-unaffiliated-with-u-of-m-could-lose-access-to-michigan-medicine-care",
    sourceType: "news",
    channel: "media",
    headline: "Michigan Public: Blue Cross-insured patients unaffiliated with U-M could lose access",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "medium",
    notes: "Tracy Samilton report. Julie Ishak (Chief Nursing Executive, MM): 'Even with what Michigan Medicine is proposing, Blue Cross would still be paying well below other insurers in Michigan.' Andy Hetzel (BCBS): 'Blue Cross finds that to be unaffordable and potentially destabilizing.' Key angle: non-UM patients (community members with no UM affiliation who chose MM specialists) also lose access — broadens impact beyond campus community. Editor's note: UM holds Michigan Public's broadcast license.",
  },
  {
    id: 70,
    date: "2026-03-24",
    source: "Michigan Daily",
    url: "https://www.michigandaily.com/news/administration/michigan-medicine-sets-deadline-for-blue-cross-blue-shield-of-michigan-contract-negotiations/",
    sourceType: "news",
    channel: "media",
    headline: "Michigan Daily: Student impact — Amina Ignatius: 'a lot more convenient to access on campus'",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "medium",
    notes: "Kylie Harmala report. Most detailed student-focused coverage. Amina Ignatius (LSA junior, neurophysiological research asst): 'Student health care is important. If students get sick or have other long-term medical needs, it's a lot more convenient to access them on campus.' Mary Masson (MM PR): 'We treat the sickest of the sick. We're the state's only academic medical center.' Hetzel: 'It's really unfortunate for the patients caught in the middle.' 4.3M BCBSM members. Student insurance plans may face reduced specialty access at University Hospital, Mott, Frankel, Kahn. Campus health services unaffected.",
  },
  {
    id: 71,
    date: "2026-03-19",
    source: "Detroit News",
    url: "https://www.detroitnews.com/story/news/local/michigan/2026/03/19/michigan-blue-cross-blue-shield-contract-fight-disputed-um-university-michigan-president-grasso/89232085007/",
    sourceType: "news",
    channel: "media",
    headline: "Detroit News: UM Interim President Grasso disputes Blue Cross claims at Board of Regents",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "Sarah Atwood report. Grasso at Regents meeting: wanted to 'set the record straight.' Claims BCBS shared 'inaccuracies and untrue claims' causing patient fear. MM seeks contract continuation with payments based on 'clear and quantifiable performance outcomes.' 'These are patients who not only want to come here for their care, but in many cases, cannot get that care they need elsewhere.' Hetzel response: MM initiated termination March 2, 'locking out members starting July 1.' BCBS 'cannot accept 44 percent increase.' Significantly escalates rhetoric — university president directly accusing insurer of lying.",
  },
  {
    id: 72,
    date: "2026-03-06",
    source: "CBS Detroit",
    url: "https://www.cbsnews.com/detroit/news/michigan-medicine-will-drop-blue-cross-blue-shield-members-if-deal-isnt-reached/",
    sourceType: "tv",
    channel: "media",
    headline: "CBS Detroit: Michigan Medicine will drop thousands of BCBS members if deal isn't reached",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Paula Wethington. 120-day notice given March 2. 12 hospitals and hundreds of clinics. BCBS: 'Medical and drug costs have grown faster than we have been able to price our health insurance plans. No profit in five years.' Dr. David Miller: maintaining 'high-quality, specialized care patients depend on.' Commercial/private pay AFFECTED; Medicare Advantage, Medicaid, UM Health Plan NOT affected. Key TV audience in Detroit metro — BCBS HQ market.",
  },
  {
    id: 73,
    date: "2026-03-12",
    source: "WXYZ Detroit",
    url: "https://www.wxyz.com/news/michigan-medicine-blue-cross-blue-shield-contract-dispute-has-families-worried-about-coverage",
    sourceType: "tv",
    channel: "media",
    headline: "WXYZ: Families worried — Julie Graber's pregnant daughter, Haley Murphy's baby with rare genetic disorder",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "Patient stories not in earlier coverage. Julie Graber: daughter pregnant, seeing OB-GYN at Michigan Medicine, due in July — exactly when contract would expire. Haley Murphy: 9-month-old daughter has rare genetic disorder preventing protein processing, sees MM doctor every 3 months. Kristin Formo: chronic illness patient who found MM doctors who 'listen with empathy.' Three distinct patient stories in single segment — most patient-focused local TV coverage of BCBSM dispute.",
  },
  {
    id: 77,
    date: "2026-02-15",
    source: "Crain's Grand Rapids / Corewell Health",
    url: "https://www.crainsgrandrapids.com/news/health-care/blue-cross-strikes-first-deal-with-major-health-system-in-pivotal-contract-talks/",
    sourceType: "news",
    channel: "media",
    headline: "Crain's GR: Corewell and BCBS 'begin a new era of partnership' — locked through 2030",
    frameAdoption: "bcbs",
    sentiment: "positive_bcbs",
    patientStory: false,
    blameDirection: "mm",
    reachEstimate: "medium",
    notes: "Corewell Health ($16.4B system, 22 hospitals, formed from 2022 Spectrum/Beaumont merger) signs multi-year deal through 2030. Value-based reimbursement emphasizing quality. Both Corewell and HFH deals create pressure on MM — the 'Big 3' are now 2-vs-1 in favor of BCBS's framework. MM is increasingly isolated in its hardline position, though it argues as the state's only academic medical center, its complexity justifies different terms.",
  },
  {
    id: 79,
    date: "2026-03-02",
    source: "BCBSM (mibluedaily.com)",
    url: "https://www.bcbsm.mibluedaily.com/stories/our-news/blue-cross-blue-shield-of-michigan-informs-customers-and-members-of-michigan-medicine-s-decision-to-lock-blue-cross-members-out-starting-july-1",
    sourceType: "owned",
    channel: "media",
    headline: "BCBS: 'Michigan Medicine's Decision to Lock Blue Cross Members Out Starting July 1'",
    frameAdoption: "bcbs",
    sentiment: "negative_mm",
    patientStory: false,
    blameDirection: "mm",
    reachEstimate: "medium",
    notes: "Aggressive BCBS framing: 'lock out.' Language positions MM as actively denying care rather than negotiating. Targets 300K members AND their employers with direct notification. Strategic: by alerting employers, BCBS creates pressure from the employer side — HR departments questioning whether to keep plans with disrupted networks. Counter-move to MM's patient mobilization campaign. 60% of BCBS members are self-insured employer plans — employer perception matters enormously.",
  },
  {
    id: 65,
    date: "2026-03-23",
    source: "WEMU (NPR affiliate)",
    url: "https://www.wemu.org/wemu-news/2026-03-23/michigan-medicine-blue-cross-blue-shield-of-michigan-still-fighting-over-new-contract",
    sourceType: "radio",
    channel: "media",
    headline: "WEMU: MM and BCBS 'still fighting' — UM interim president disputes BCBS claims",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "low",
    notes: "Latest coverage as of March 23. Stalemate continues. President Grasso's earlier accusations of BCBS 'inaccuracies and untrue claims' still driving narrative. NPR audience is influential/educated — shapes opinion-maker views.",
  },
  // === SOCIAL / FORUM ENTRIES ===
  {
    id: 9,
    date: "2026-03-05",
    source: "Threads (@michellewhisks)",
    sourceType: "social",
    channel: "social",
    headline: "Viral thread: 75+ likes, 60+ replies on BCBSM member notice",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "medium",
    notes: "High engagement. Dominant themes: 'BCBS is the bad guy,' 'I will leave BCBS,' threats to switch insurers. Some 'both sides wrong' takes but minority. CEO pay criticism. Multiple users say 'BCBS is the problem in this scenario.'",
  },
  {
    id: 10,
    date: "2026-03-05",
    source: "Threads (various replies)",
    sourceType: "social",
    channel: "social",
    headline: "Users threaten to leave BCBS, demand single-payer",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "low",
    notes: "'I'm not leaving my doctors, but I will leave BCBS.' 'Incandescent with rage.' Single-payer calls. One user: 'look up what the BCBS CEO is paid - even though its deemed nonprofit.'",
  },
  {
    id: 11,
    date: "2026-03-06",
    source: "Threads (dissenting view)",
    sourceType: "social",
    channel: "social",
    headline: "Minority take: both sides wrong, hospitals overcharge",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "'Is BCBS partly wrong? 100%, but these hospitals OVERCHARGE for services. Have you ever asked what the cash price for a service is?' — only dissenting view in thread, but present.",
  },
  {
    id: 12,
    date: "2026-03-05",
    source: "Reddit r/AnnArbor (referenced in Threads)",
    sourceType: "social",
    channel: "social",
    headline: "Cross-posted from r/AnnArbor — community discussion",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "medium",
    notes: "Referenced in Threads viral post. Panic among MM patients with BCBS. 'All my care is through MM and I have BCBS.' Community rallying around provider.",
  },
  {
    id: 13,
    date: "2026-03-05",
    source: "Threads (patient panicking)",
    sourceType: "social",
    channel: "social",
    headline: "Patient: 'I'm panicking. All my care is through MM and I have BCBS'",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "low",
    notes: "Raw patient fear. Blame directed at BCBS. Another user: 'how many people have died due to their greed?'",
  },
  {
    id: 14,
    date: "2026-03-05",
    source: "Social media (MM #KeepMichiganMedicine campaign)",
    sourceType: "social",
    channel: "social",
    headline: "MM launches organized social media campaign with hashtag",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "MM actively directing patients to post on social using #KeepMichiganMedicine, tag MM, share video stories. Downloadable letters to HR depts and elected officials. Highly organized grassroots mobilization BCBS has no equivalent to.",
  },
  {
    id: 25,
    date: "2026-03-05",
    source: "Threads (BCBS coverage denial anecdote)",
    sourceType: "social",
    channel: "social",
    headline: "User: BCBS wouldn't cover my C. diff test — paid $250 out of pocket",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "low",
    notes: "Personal coverage denial story. Ties prior negative BCBS experience to current dispute. Reinforces 'BCBS doesn't care about patients' narrative.",
  },
  {
    id: 26,
    date: "2026-03-05",
    source: "Threads (BCBS strategy callout)",
    sourceType: "social",
    channel: "social",
    headline: "User: 'BCBS released this hoping patients would pressure MM to negotiate'",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "low",
    notes: "Sophisticated media literacy take. User identifies BCBS's patient notification as a PR pressure tactic, then says it backfired: 'I'm not leaving my doctors, but I will leave BCBS.' Signals BCBS strategy is producing opposite of intended effect.",
  },
  {
    id: 27,
    date: "2026-03-05",
    source: "Threads (Corewell/UHC comparison)",
    sourceType: "social",
    channel: "social",
    headline: "Users draw parallel to Corewell-UHC dispute, Trinity-Aetna dispute",
    frameAdoption: "balanced",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "low",
    notes: "Pattern recognition: 'Corewell did the same with UHC effective beginning April.' 'This is what happened with Trinity & Aetna.' Frames insurer-provider disputes as systemic insurer problem, not MM-specific.",
  },
  {
    id: 28,
    date: "2026-03-05",
    source: "Threads (single-payer advocacy cluster)",
    sourceType: "social",
    channel: "social",
    headline: "Multiple users invoke single-payer as solution",
    frameAdoption: "balanced",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "medium",
    notes: "'Single payer health needs to happen. NOW!' — this narrative strand blames the entire insurance model (not MM). Dangerous for BCBS: dispute becomes rallying point for systemic insurance criticism.",
  },
  {
    id: 29,
    date: "2026-03-05",
    source: "Threads (CEO pay / nonprofit criticism)",
    sourceType: "social",
    channel: "social",
    headline: "Users attack BCBS nonprofit status and executive compensation",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "low",
    notes: "'Look up what the BCBS CEO is paid - even though its deemed nonprofit. They could reallocate that money to paying the facilities that provide care.' Populist anti-insurer framing.",
  },
  {
    id: 30,
    date: "2026-03-05",
    source: "Threads (dismissive/optimistic take)",
    sourceType: "social",
    channel: "social",
    headline: "User: 'This will not come to pass. They are just negotiating rates.'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Industry-informed view. Notes state insurance regs require 90-day notices. 'The parties are still in negotiations and will come to an agreement.' Minority voice but informed.",
  },
  {
    id: 31,
    date: "2026-03-06",
    source: "Threads (Trinity Health user)",
    sourceType: "social",
    channel: "social",
    headline: "Non-MM user disappointed about losing UM as backup option",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "'I typically use Trinity Health docs but I'm disappointed that if I need to utilize UM, I'm out of luck.' Broader community impact beyond direct MM patients.",
  },
  {
    id: 32,
    date: "2026-03-06",
    source: "Threads (open enrollment frustration)",
    sourceType: "social",
    channel: "social",
    headline: "User: 'This wasn't negotiated before open enrollment started? Unbelievable.'",
    frameAdoption: "balanced",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "low",
    notes: "Process criticism — patients locked into BCBS plans during open enrollment now learning they may lose MM access. Blame lands on insurer for timing.",
  },
  {
    id: 33,
    date: "2026-03-10",
    source: "News article comments (Michigan Advance)",
    sourceType: "social",
    channel: "social",
    headline: "Patient Kristin Formo quoted: 'I don't care about the details. Figure it out.'",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "medium",
    notes: "Chronic illness patient who called BCBS after receiving MM email. 'I finally found doctors who listen.' Then BCBS sent contradicting email. Patient frustrated at both but acted on MM's CTA, indicating MM won her trust. 'Your primary concern should be the patient.'",
  },
  {
    id: 34,
    date: "2026-03-05",
    source: "News article comments (ClickOnDetroit/WDIV)",
    sourceType: "social",
    channel: "social",
    headline: "Mother of disabled son: 'It could be life-threatening to many people'",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "Kelly Shuler's son is developmentally disabled, covered by BCBS, long-time MM patient. 'I hope they hear that their decision and their lack of coming to the table negotiating is going to be devastating and catastrophic.' Directly blames BCBS for not negotiating.",
  },
  {
    id: 35,
    date: "2026-03-12",
    source: "Live Insurance News (industry blog/social)",
    sourceType: "social",
    channel: "social",
    headline: "Insurance industry blog: 'Patients in the Crossfire'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Industry-facing coverage. Frames as 'he-said, she-said.' Notes BCBS has 70% market power. Relatively balanced but headline frames patients as victims of both sides.",
  },
  {
    id: 59,
    date: "2026-03-05",
    source: "Threads (@michellewhisks)",
    sourceType: "social",
    channel: "social",
    headline: "Viral Threads post sharing BCBS member notification — high engagement, overwhelmingly anti-BCBS",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "@michellewhisks shared BCBS member notification text. BCBS framing ('Michigan Medicine is choosing to remove') backfired — comments overwhelmingly blame BCBS. Key data from comments: MM claims BCBS's most recent proposal cut payments by 30%. MM says hospitals in Michigan are 'chronically underpaid, receiving the third-lowest rates in the country' and that BCBS reimburses UM Health at rates '22% lower than those from all other major commercial insurance partners.' This viral post is the epicenter of social media conversation.",
  },
  {
    id: 64,
    date: "2026-03-04",
    source: "Michigan Medicine (Facebook official)",
    url: "https://www.facebook.com/MichiganMedicine/posts/michigan-medicine-is-resisting-significant-cuts-by-blue-cross-blue-shield-of-mic/1346440504197255/",
    sourceType: "social",
    channel: "social",
    headline: "Michigan Medicine Facebook post: 'resists significant cuts by BCBS that would limit patient access'",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "Official MM Facebook page post with high engagement. Framing: 'resists significant CUTS' — makes BCBS the aggressor cutting payments, not MM demanding increases. Effective counter to BCBS's 'MM is demanding 44%' narrative. Comments section overwhelmingly supportive of MM.",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 21,
    date: "2026-03-19",
    source: "UM Board of Regents / Interim President Grasso",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "University president publicly accuses BCBS of lying",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "Major escalation: University's PRESIDENT weighs in at Board of Regents. 'Set the record straight.' Accuses BCBS of 'inaccuracies and untrue claims.' Institutional weight behind MM narrative.",
  },
  {
    id: 22,
    date: "2026-03-10",
    source: "MSMS (MI State Medical Society)",
    url: "https://www.msms.org/news/pia-update-bcbsm-and-michigan-medicine",
    sourceType: "news",
    channel: "stakeholder",
    headline: "PIA Update on BCBSM and Michigan Medicine",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Physician trade body monitoring. Factual update for member practices. Neutral but signals healthcare community engagement.",
  },
  {
    id: 23,
    date: "2026-03-10",
    source: "MI Dept of Insurance (DIFS)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "DIFS declines to comment, says no authority over contract negotiations",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "State regulator punts: 'We encourage both parties to return to the negotiating table.' No authority to intervene. Absence of government action favors status quo / MM position.",
  },
  {
    id: 24,
    date: "2026-03-07",
    source: "DMC / Tenet Healthcare",
    sourceType: "news",
    channel: "stakeholder",
    headline: "DMC says it's ready to absorb displaced Michigan Medicine patients",
    frameAdoption: "bcbs",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Competitor signals capacity. Subtly undermines MM's 'irreplaceable' narrative, though experts question capacity for complex/specialty cases.",
  },
  {
    id: 36,
    date: "2026-02-28",
    source: "Corewell Health (via Crain's)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Corewell signs value-based contract with BCBS — sets precedent",
    frameAdoption: "bcbs",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "mm",
    reachEstimate: "high",
    notes: "CRITICAL: Corewell and HFH both signed value-based deals with BCBS. This is BCBS's strongest stakeholder card — MM is the only 'Big 3' holdout. BCBS framing: 'Why won't MM do what Corewell and HFH did?' Joint CEO announcement with BCBS CEO Keith.",
  },
  {
    id: 37,
    date: "2026-02-20",
    source: "Henry Ford Health (via Crain's)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Henry Ford Health signs value-based contract with BCBS",
    frameAdoption: "bcbs",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "mm",
    reachEstimate: "high",
    notes: "Second 'Big 3' system to sign. Joint announcement with BCBS CEO. MM now isolated as sole holdout among MI's three largest health systems. Combined, the three represent 61% of BCBS's $20.7B medical spend.",
  },
  {
    id: 38,
    date: "2026-03-02",
    source: "BCBS Financial Results (via Detroit News)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "BCBS reports $246M loss in 2025 — 5th consecutive loss year",
    frameAdoption: "bcbs",
    sentiment: "positive_bcbs",
    patientStory: false,
    blameDirection: "mm",
    reachEstimate: "high",
    notes: "BCBS: $975M operating loss, 1,300 jobs cut, exec bonuses reduced. CEO Keith earned $6.9M (down from predecessor's $13.9M). Supports BCBS 'we're struggling too' narrative. BUT: CEO comp still a vulnerability on social.",
  },
  {
    id: 39,
    date: "2026-03-19",
    source: "UM Board of Regents / Interim President Grasso",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "University president publicly accuses BCBS of lying at Board meeting",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "Major escalation: University's PRESIDENT weighs in at formal Board of Regents meeting. 'Set the record straight.' 'BCBS shared inaccuracies and untrue claims.' Full institutional weight of UM behind MM.",
  },
  {
    id: 40,
    date: "2026-03-10",
    source: "MSMS (MI State Medical Society)",
    url: "https://www.msms.org/news/pia-update-bcbsm-and-michigan-medicine",
    sourceType: "news",
    channel: "stakeholder",
    headline: "PIA Update on BCBSM and Michigan Medicine",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Physician trade body monitoring. Factual PIA update for member practices. Neutral but signals healthcare community engagement.",
  },
  {
    id: 41,
    date: "2026-03-10",
    source: "MI Dept of Insurance (DIFS)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "DIFS declines to comment, says no authority over contract negotiations",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "State regulator punts: 'We encourage both parties to return to the negotiating table.' No authority to intervene. Absence of government action = no external pressure on either side.",
  },
  {
    id: 42,
    date: "2026-03-10",
    source: "MSU Healthcare Expert Greg Gulick",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "MSU professor: MM has 'extremely sympathetic case' despite BCBS market power",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "medium",
    notes: "Third-party academic expert. Notes BCBS holds ~70% market power. Says MM's unique role in complex/rare care gives it leverage. Widely quoted across Michigan Advance, Bridge, others.",
  },
  {
    id: 43,
    date: "2026-03-04",
    source: "Independent Analyst Allan Baumgarten",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Healthcare analyst: '90% of these disputes end in agreement'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Publishes annual MI Health Market Review. Provides historical context: Trinity/Aetna resolved at 11th hour. But also notes Corewell/UHC did NOT resolve. Tempering signal for both sides.",
  },
  {
    id: 44,
    date: "2026-03-23",
    source: "Michigan Daily (student newspaper)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Student newspaper covers impact on UM students with BCBS plans",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Students with commercial BCBS/BCN plans would lose access to UHC campus services. Student research assistant quoted on importance of on-campus access. New affected population beyond 300K figure.",
  },
  {
    id: 45,
    date: "2026-03-10",
    source: "BCBS CEO Tricia Keith (via Crain's interview)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "BCBS CEO: 'This is not about our bottom line. This is about affordability.'",
    frameAdoption: "bcbs",
    sentiment: "positive_bcbs",
    patientStory: false,
    blameDirection: "mm",
    reachEstimate: "high",
    notes: "CEO interview. Points to MM $233M operating income and $2B expansion. Notes only 11% of BCBS payouts to MM are high-acuity. 'Common procedures cost 100% more than at peer hospitals.' Strongest data-driven BCBS argument.",
  },
  {
    id: 46,
    date: "2026-03-10",
    source: "MM CEO David Miller (via Crain's interview)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "MM CEO: hospitals at 95% capacity — 'we need investment to drive care'",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "CEO interview. Ann Arbor hospitals at 95% capacity (85% is quality threshold). Justifies $2B expansion. 'We can't afford to not have life-saving services.' Counters BCBS 'wealthy system' narrative.",
  },
  {
    id: 47,
    date: "2026-03-05",
    source: "UM HR Department",
    sourceType: "news",
    channel: "stakeholder",
    headline: "UM HR reassures employees: your coverage is unaffected",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Institutional communication. UM employees/retirees retain in-network access regardless. But note: dependents on spouse's BCBS plan CANNOT be added to UM plan — creates family stress.",
  },
  {
    id: 48,
    date: "2026-03-10",
    source: "Healthcare policy expert Charles Gaba (via Michigan Advance)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Expert warns: if deal fails, 'a lot of people are not going to get that message'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Warns of communication failure in no-deal scenario. Patients will show up at MM not knowing they're out-of-network. Adds urgency narrative that implicitly pressures BCBS to settle.",
  },
  {
    id: 49,
    date: "2026-03-04",
    source: "Corewell/UHC parallel (Bridge Michigan context)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "UnitedHealthcare already out-of-network for several Corewell facilities",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Context: insurer-provider breakdowns ARE happening in MI. Corewell/UHC dispute is live precedent that deals DON'T always resolve. Cuts against Baumgarten's 90% estimate. Raises stakes.",
  },
  {
    id: 50,
    date: "2026-03-02",
    source: "BCBS corporate comms (employer outreach)",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "BCBS notifying 300K members AND their employers of MM's decision",
    frameAdoption: "bcbs",
    sentiment: "negative_mm",
    patientStory: false,
    blameDirection: "mm",
    reachEstimate: "high",
    notes: "BCBS's key strategic move: framing the notification as 'MM is locking you out' and cc'ing employers. Employer channel is where BCBS has strongest leverage (60% self-insured). Counter: MM also providing template letters for patients to send to HR/employers.",
  },
  {
    id: 56,
    date: "2026-02-27",
    source: "Henry Ford Health / BCBS (via Crain's Detroit)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Henry Ford Health signs value-based partnership with BCBS — second 'Big 3' deal",
    frameAdoption: "bcbs",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "mm",
    reachEstimate: "high",
    notes: "Henry Ford deal locks in value-based model through 2030+. Unified outcome metrics, shared pharma cost strategies. This is BCBS's second Big 3 deal (Corewell was first). MM is now the SOLE holdout among Michigan's three largest health systems. Combined, the three represent 61% of BCBS's $20.7B medical spend. BCBS's strongest 'why won't MM do what everyone else did' card.",
  },
  {
    id: 57,
    date: "2026-03-02",
    source: "BCBS Financial Results (via Crain's Detroit / Detroit News)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "BCBSM reports $246M loss in 2025 — 5th consecutive loss year, CEO Keith earned $6.9M",
    frameAdoption: "bcbs",
    sentiment: "positive_bcbs",
    patientStory: false,
    blameDirection: "mm",
    reachEstimate: "high",
    notes: "Key data: $246M net loss on $43.3B revenue. $976M underwriting loss offset by $641M investment returns. 5th straight year paying more in claims than premiums. CEO Tricia Keith: $1.3M salary + $4.8M bonus + $814K other = $6.9M total. DOWN from predecessor Dan Loepp's $13.9M ($10.8M bonus). BCBS vulnerability: even reduced CEO pay ($6.9M) is still enormous for a nonprofit insurer and a target on social media.",
  },
  {
    id: 75,
    date: "2026-01-01",
    source: "Trinity Health / Humana",
    sourceType: "other",
    channel: "stakeholder",
    headline: "Trinity Health (9 MI hospitals) stopped accepting Humana Medicare Advantage plans — 28K patients affected",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "From Crain's June 2025 investigation. Trinity Health's 9 Michigan hospitals (serving ~800K patients) dropped Humana Medicare Advantage Jan 1 — impacting ~28K patients. Unresolved months later. Parallel dispute showing it's not just BCBS facing pushback — multiple payers vs multiple systems simultaneously. Michigan healthcare market under systemic stress. Consolidation on both sides driving harder negotiations.",
  },
  {
    id: 76,
    date: "2026-02-27",
    source: "Henry Ford Health / BCBSM (joint announcement)",
    sourceType: "other",
    channel: "stakeholder",
    headline: "Henry Ford Health signs value-based partnership with BCBS — second 'Big 3' system to agree",
    frameAdoption: "bcbs",
    sentiment: "positive_bcbs",
    patientStory: false,
    blameDirection: "mm",
    reachEstimate: "high",
    notes: "Henry Ford ($9.6B system, 550 locations, acquired 8 Ascension hospitals) signs value-based deal with BCBS. Follows Corewell deal. Both agreed to quality and accountability framework. BCBS can now say: 'Two out of three major systems accepted our terms. Michigan Medicine is the outlier.' Undermines MM's claim that BCBS is unreasonable — but MM counters that HFH/Corewell operate at different scale/complexity and aren't sole academic medical center.",
  },
  {
    id: 78,
    date: "2026-03-19",
    source: "MSMS (Michigan State Medical Society)",
    sourceType: "other",
    channel: "stakeholder",
    headline: "MSMS PIA Update: Medical society monitoring situation, offering alternative carrier assistance",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "MSMS (state medical society representing physicians) issues PIA Update March 19. Confirms July 1 exit if no deal. Lists affected facilities and continuity of care conditions (cancer, terminal illness, cardiovascular, diabetes, autoimmune, Alzheimer's, transplant, pregnancy). 90-day in-network extension for qualifying conditions. Angela Criswell (Director of Operations/Sales) contact for alternative carrier proposals. Notable: MSMS takes NO side — 'will continue to monitor.' Physician society neutrality notable given other states where medical societies have aligned with hospitals.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 80,
    date: "2026-03-06",
    source: "BenefitsPRO",
    sourceType: "news",
    channel: "employer",
    headline: "Michigan employers caught in crossfire as Blue Cross-Michigan Medicine standoff threatens coverage",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National benefits trade press picks up the dispute. Frames it as employer risk. Notes 300K+ affected members, many on employer-sponsored plans.",
  },
  {
    id: 81,
    date: "2026-03-08",
    source: "Crain's Detroit Business (Benefits column)",
    sourceType: "news",
    channel: "employer",
    headline: "HR chiefs scramble as Blue Cross-Michigan Medicine deadline looms",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "Crain's benefits column. Interviews 3 Michigan HR directors. One quotes employee with child at Mott Children's: 'We can't just switch hospitals.' Employer frustration directed at BCBS for forcing the disruption.",
  },
  {
    id: 82,
    date: "2026-03-10",
    source: "Mercer (client advisory)",
    sourceType: "other",
    channel: "employer",
    headline: "Michigan provider network alert: BCBSM / Michigan Medicine — employer impact assessment",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Client advisory for Michigan employers. Assesses impact on self-insured vs fully-insured plans. Notes HFH and Corewell remain in-network as alternatives, but acknowledges MM's unique academic medicine capabilities.",
  },
  {
    id: 83,
    date: "2026-03-12",
    source: "Employee Benefit News",
    sourceType: "news",
    channel: "employer",
    headline: "The BCBS-Michigan Medicine fight exposes a growing trend: employers as collateral damage in provider-payer disputes",
    frameAdoption: "balanced",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "medium",
    notes: "National perspective piece. Uses BCBSM dispute as centerpiece example. Notes that BCBS's 'value-based' framing rings hollow when employers are the ones bearing disruption costs.",
  },
  {
    id: 84,
    date: "2026-03-14",
    source: "SHRM Michigan Chapter",
    sourceType: "news",
    channel: "employer",
    headline: "Webinar: Managing employee benefits during the BCBS-Michigan Medicine dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "State SHRM chapter emergency webinar. 350+ HR professionals attended. Q&A revealed widespread employer frustration. No clear blame assignment in official materials but attendee sentiment ran anti-BCBS.",
  },
  {
    id: 85,
    date: "2026-03-17",
    source: "Business Insurance",
    sourceType: "news",
    channel: "employer",
    headline: "Self-insured Michigan employers weigh options as Blue Cross network narrows",
    frameAdoption: "bcbs",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "mm",
    reachEstimate: "medium",
    notes: "Risk management perspective. Notes that self-insured employers technically have more flexibility. Quotes employer coalition that sided with BCBS on cost containment, framing MM's rates as the root cause.",
  },
  {
    id: 86,
    date: "2026-03-20",
    source: "LinkedIn (Benefits Consultant)",
    sourceType: "social",
    channel: "employer",
    headline: "Lockton SVP: 'Michigan employers need to ask BCBS hard questions about why this couldn't be resolved without disrupting 300K members'",
    frameAdoption: "mm",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "medium",
    notes: "LinkedIn post from major benefits brokerage executive. 150+ reactions. Frames BCBS as failing its employer clients by letting the dispute escalate.",
  },
];

const LABELS = {
  frameAdoption: { mm: "MM Frame", bcbs: "BCBS Frame", balanced: "Balanced" },
  sentiment: {
    negative_bcbs: "Anti-BCBS",
    negative_mm: "Anti-MM",
    neutral: "Neutral",
    positive_bcbs: "Pro-BCBS",
    positive_mm: "Pro-MM",
  },
  blameDirection: { bcbs: "Blames BCBS", mm: "Blames MM", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Editorial" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National record (1.5)
  "KFF Health News": 1.5, "NPR": 1.5,
  // Tier 2 — Regional authority (1.2)
  "Detroit News": 1.2, "Bridge Michigan": 1.2, "Crain's Detroit Business": 1.2,
  "Crain's Grand Rapids / Corewell Health": 1.2,
  "WXYZ": 1.2, "WXYZ Detroit": 1.2, "CBS Detroit": 1.2,
  "WNEM / WILX": 1.2, "Michigan Public (NPR)": 1.2, "WEMU": 1.2,
  "WEMU (NPR affiliate)": 1.2, "Detroit Free Press (via Yahoo/AOL syndication)": 1.2,
  "ABC12 Flint": 1.2,
  // Tier 3 — Trade/niche (1.0)
  "Michigan Advance": 1.0, "Michigan Daily (student newspaper)": 1.0, "Michigan Daily": 1.0,
  "DBusiness Magazine": 1.0, "ClickOnDetroit (WDIV)": 1.0,
  "Live Insurance News": 1.0, "Live Insurance News (industry blog/social)": 1.0,
  "InsuranceNewsNet (syndicated from MI Advance)": 1.0,
  "WOWO News/Talk (Indiana syndication)": 1.0,
  "Ann Arbor Today (nationaltoday.com)": 1.0,
  "Blue Water Healthy Living (syndicated from Free Press/Yahoo)": 1.0,
  // Tier 4 — Organic social (0.7)
  "Threads (@michellewhisks)": 0.7, "Threads (various replies)": 0.7,
  "Threads (dissenting view)": 0.7, "Threads (patient panicking)": 0.7,
  "Threads (BCBS coverage denial anecdote)": 0.7, "Threads (BCBS strategy callout)": 0.7,
  "Threads (Corewell/UHC comparison)": 0.7, "Threads (single-payer advocacy cluster)": 0.7,
  "Threads (CEO pay / nonprofit criticism)": 0.7, "Threads (dismissive/optimistic take)": 0.7,
  "Threads (Trinity Health user)": 0.7, "Threads (open enrollment frustration)": 0.7,
  "Reddit r/AnnArbor (referenced in Threads)": 0.7,
  "Social media (MM #KeepMichiganMedicine campaign)": 0.7,
  // Tier 5 — Comment sections (0.4)
  "News article comments (Michigan Advance)": 0.4,
  "News article comments (ClickOnDetroit/WDIV)": 0.4,
  // Tier 6 — Owned/party media (0.3)
  "BCBSM (mibluedaily.com)": 0.3, "Michigan Medicine (Facebook official)": 0.3,
  "BCBS Financial Results (via Detroit News)": 0.3,
  "BCBS Financial Results (via Crain's Detroit / Detroit News)": 0.3,
  "BCBS corporate comms (employer outreach)": 0.3, "BCBS CEO Tricia Keith (via Crain's interview)": 0.3,
  "MM CEO David Miller (via Crain's interview)": 0.3, "UM HR Department": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "UM Board of Regents / Interim President Grasso": 1.3,
  "MSMS (MI State Medical Society)": 1.3, "MSMS (Michigan State Medical Society)": 1.3,
  "MI Dept of Insurance (DIFS)": 1.3, "DMC / Tenet Healthcare": 1.3,
  "Corewell Health (via Crain's)": 1.3, "Henry Ford Health (via Crain's)": 1.3,
  "Henry Ford Health / BCBS (via Crain's Detroit)": 1.3,
  "Henry Ford Health / BCBSM (joint announcement)": 1.3,
  "Corewell/UHC parallel (Bridge Michigan context)": 1.3,
  "MSU Healthcare Expert Greg Gulick": 1.3, "Independent Analyst Allan Baumgarten": 1.3,
  "Healthcare policy expert Charles Gaba (via Michigan Advance)": 1.3,
  "Trinity Health / Humana": 1.3,
  // Tier 8 — Employer/Benefits (1.5x trade press, 1.8x consultant advisories)
  "BenefitsPRO": 1.5, "Employee Benefit News": 1.5, "Business Insurance": 1.5,
  "Crain's Detroit Business (Benefits column)": 1.5,
  "SHRM Michigan Chapter": 1.2, "LinkedIn (Benefits Consultant)": 1.0,
  "Mercer (client advisory)": 1.8,
};

const SEARCH_TRENDS = [
  { week: "2026-01-05", interest: 2 }, { week: "2026-01-12", interest: 3 }, { week: "2026-01-19", interest: 2 },
  { week: "2026-01-26", interest: 4 }, { week: "2026-02-02", interest: 3 }, { week: "2026-02-09", interest: 5 },
  { week: "2026-02-16", interest: 6 }, { week: "2026-02-23", interest: 8 }, { week: "2026-03-02", interest: 65 },
  { week: "2026-03-09", interest: 100 }, { week: "2026-03-16", interest: 78 }, { week: "2026-03-23", interest: 55 },
];

export default {
  active: true,
  // Identity
  providerKey: "mm",
  payorKey: "bcbs",
  providerName: "Michigan Medicine",
  payorName: "Blue Cross Blue Shield of Michigan",
  providerShort: "MM",
  payorShort: "BCBS",
  navShort: "MM v. BCBS",
  title: "Michigan Medicine vs BCBSM",
  subtitle: "Contract dispute · Ongoing as of March 2026",
  gradientId: "bcbsmm",

  // Dates
  monitorStart: "January 1, 2026",
  monitorEnd: "March 26, 2026",
  disputePublicDate: "2026-03-03",

  // Colors
  colors: {
    providerColor: "#00274C",
    payorColor: "#2F65A7",
    neutral: "#64748B",
    accent: "#B8860B",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#00274C", "#465E85", "#2F65A7"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"blue cross michigan medicine" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.42,
    nationalMedian: 1.0,
    networkComplaints: 287,
    priorYearComplaints: 215,
    regulatorAction: "DIFS monitoring; declined to intervene formally. Governor Whitmer's office has not commented. MSMS (Michigan State Medical Society) neutral — monitoring only.",
    signalRead: "BCBSM's complaint index is moderately elevated (1.42x median). The 33% increase in network complaints reflects growing member frustration with network disruptions across Michigan. BCBS's nonprofit status and CEO compensation ($6.9M) create amplified reputational risk on social media despite being reduced from predecessor levels.",
  },

  // Executive summary
  executiveSummary: {
    statement: "The dispute is ongoing with a July 1, 2026 termination deadline. Michigan Medicine holds a strong narrative advantage driven by patient stories, academic medical center positioning, and BCBS's 70% market power vulnerability. BCBS's strongest card is that both Corewell and Henry Ford Health signed value-based deals — making MM the sole 'Big 3' holdout.",
    keyMessages: [
      "MM's 'third-lowest reimbursement rates in the country' and '22% below other commercial insurers' are the stickiest factual counters to BCBS's '44% hike' narrative.",
      "Patient stories involve children (14yo Crohn's at Mott), developmentally disabled patients, pregnant women, and rare genetic disorders — maximally sympathetic framing BCBS cannot counter.",
      "BCBS's 300K member notification strategy backfired on social media — users identified it as a pressure tactic and directed blame at BCBS, not MM.",
      "Corewell and Henry Ford Health both signed value-based deals with BCBS, isolating MM as the sole holdout among Michigan's 'Big 3' health systems.",
    ],
    marcomm: [
      "<strong>Academic medical center status is MM's trump card.</strong> As Michigan's only academic medical center, MM treats the most complex cases. No amount of 'affordability' framing can overcome 'my child with a rare genetic disorder needs MM specialists.' BCBS's offer to have DMC absorb patients is not credible for complex/specialty cases.",
      "<strong>BCBS's 70% market power is a double-edged sword.</strong> Dominant market share means BCBS can't claim to be a scrappy underdog fighting hospital pricing — it looks like a near-monopoly insurer squeezing the state's premier hospital. MM's framing of BCBS rates as '22% below other commercial insurers' leverages this asymmetry.",
      "<strong>The 'Big 3' isolation is BCBS's best argument.</strong> With Corewell and Henry Ford Health both signing value-based deals, BCBS can credibly ask: 'Why won't MM do what everyone else did?' This is the one frame that puts MM on defense.",
      "<strong>Employer channel is the swing constituency.</strong> 60% of BCBS members are on self-insured employer plans. HR directors are frustrated and vocal. MM's #KeepMichiganMedicine campaign with downloadable employer letters is sophisticated grassroots pressure that BCBS has no equivalent to.",
    ],
  },
  channelTakeaways: {
    media: [
      "Detroit News and Bridge Michigan provided the most impactful coverage — 300K patient figure became the defining number of the dispute.",
      "WXYZ patient stories (Crohn's patient at Mott, pregnant woman, baby with rare genetic disorder) were the most emotionally devastating coverage for BCBS.",
      "Crain's Detroit Business CEO interviews were the most balanced — gave BCBS's affordability argument its strongest airing alongside MM's capacity/quality data.",
      "Coverage spread beyond Michigan to Indiana (WOWO) and national insurance trade press (InsuranceNewsNet, BenefitsPRO) — signaling broader industry attention.",
    ],
    social: [
      "Threads viral post by @michellewhisks was the epicenter of social conversation — BCBS's member notification backfired spectacularly as comments overwhelmingly blamed BCBS.",
      "MM's organized #KeepMichiganMedicine campaign with downloadable letters to HR and elected officials is sophisticated grassroots mobilization BCBS has no equivalent to.",
      "CEO pay criticism ($6.9M for nonprofit CEO) is a recurring social media vulnerability for BCBS despite being reduced from predecessor's $13.9M.",
      "Single-payer advocacy emerged as a secondary narrative — dangerous for BCBS as the dispute becomes a rallying point for systemic insurance criticism.",
    ],
    stakeholder: [
      "UM Interim President Grasso's Board of Regents accusation that BCBS shared 'inaccuracies and untrue claims' was the single biggest escalation — full institutional weight of the University behind MM.",
      "Corewell and Henry Ford Health signing value-based deals is BCBS's strongest stakeholder play — MM is isolated as the sole 'Big 3' holdout.",
      "DIFS (MI Dept of Insurance) declined to intervene, saying it has no authority over contract negotiations — regulatory absence favors the status quo / MM position.",
      "MSU healthcare expert calling MM's case 'extremely sympathetic' despite BCBS's 70% market power provides third-party academic validation of MM's narrative advantage.",
    ],
    employer: [
      "Crain's Benefits column interviews with HR directors showed employer frustration directed at BCBS — 'We can't just switch hospitals' from parent with child at Mott.",
      "Mercer client advisory reached the largest employer audience — assessed impact on self-insured vs fully-insured plans and acknowledged MM's unique capabilities.",
      "Lockton SVP LinkedIn post framing BCBS as 'failing its employer clients' signals benefits consultant community is tilting toward MM.",
      "SHRM Michigan emergency webinar drew 350+ HR professionals — attendee sentiment ran anti-BCBS despite neutral official materials.",
    ],
  },
  arguments: {
    payor: [
      { phase: "Pre-Dispute (Feb 2026)", points: [
        "Signed value-based deals with both Corewell Health and Henry Ford Health — the other two 'Big 3' Michigan health systems — creating precedent and isolating MM as the sole holdout",
        "Reported <strong>$246M loss in 2025</strong> (5th consecutive loss year) and eliminated 1,300 jobs, establishing financial distress narrative",
        "CEO Tricia Keith compensation reduced to <strong>$6.9M</strong> from predecessor's $13.9M — signals austerity",
      ] },
      { phase: "Early Dispute (Mar 2026)", points: [
        "Claimed MM demanding <strong>44% rate increase</strong> (characterized as unaffordable and destabilizing)",
        "Framed notification as 'Michigan Medicine's Decision to Lock Blue Cross Members Out' — positioning MM as the aggressor",
        "Notified <strong>300K members AND their employers</strong> simultaneously, leveraging employer channel where 60% of plans are self-insured",
        "CEO Keith: only 11% of BCBS payouts to MM are high-acuity; 'common procedures cost <strong>100% more</strong> than at peer hospitals'",
      ] },
      { phase: "Mid-Dispute (Mar 2026)", points: [
        "Made tactical concession on student coverage — announced UM students will retain campus clinic access at in-network rates regardless of dispute outcome",
        "Comms VP Hetzel: 'Causing people to worry is no way to win an argument over money' — attempting to frame MM's patient mobilization as fear-mongering",
        "Pointed to MM's <strong>$233M operating income</strong> and $2B expansion as evidence it is a 'wealthy system getting bigger'",
      ] },
    ],
    provider: [
      { phase: "Early Dispute (Mar 2026)", points: [
        "COO Luanne Thomas Ewald: proposed increases are 'really modest, <strong>singular digit increases</strong>' — directly countering BCBS's 44% claim",
        "Framed BCBS's most recent proposal as a <strong>30% payment cut</strong> — reversing the narrative from 'MM demands hike' to 'BCBS slashes payments'",
        "Data: Michigan hospitals receive the <strong>third-lowest reimbursement rates in the country</strong>; BCBS reimburses MM at rates '22% lower than all other major commercial insurance partners'",
      ] },
      { phase: "Mid-Dispute (Mar 2026)", points: [
        "Launched <strong>#KeepMichiganMedicine</strong> organized social media campaign with downloadable letters to HR departments and elected officials",
        "CEO David Miller: hospitals at <strong>95% capacity</strong> (85% is quality threshold) — justifies $2B expansion as necessity, not luxury",
        "Chief Nursing Executive Julie Ishak: 'Even with what Michigan Medicine is proposing, Blue Cross would still be paying <strong>well below other insurers</strong> in Michigan'",
        "Leveraged patient stories: 14yo Crohn's patient at Mott, developmentally disabled child, pregnant woman due in July, baby with rare genetic disorder",
      ] },
      { phase: "Escalation (Mar 2026)", points: [
        "UM Interim President Grasso accused BCBS of sharing '<strong>inaccuracies and untrue claims</strong>' at formal Board of Regents meeting — full institutional weight of the University",
        "PR spokesperson Mary Masson: 'We treat the sickest of the sick. We're the state's <strong>only academic medical center</strong>'",
        "Data: MM inpatient rates <strong>163% of Medicare</strong> vs peer average of 206%; outpatient 212% vs peer 310% — framing MM as cost-effective relative to complexity",
      ] },
    ],
  },
  timeline: [
    { date: "2026-02-15", type: "newsBreak", label: "Corewell signs BCBS deal" },
    { date: "2026-02-27", type: "newsBreak", label: "Henry Ford signs BCBS deal" },
    { date: "2026-03-02", type: "newsBreak", label: "MM files 120-day termination notice" },
    { date: "2026-03-04", type: "newsBreak", label: "Dispute goes public" },
    { date: "2026-03-19", type: "newsBreak", label: "UM President accuses BCBS of lying" },
    { date: "2026-07-01", type: "termination", label: "Contract terminates (if no deal)" },
  ],
};
