// Baylor Scott & White Health vs Blue Cross Blue Shield of Texas — PR War Room Config
// Dispute public: May 2024. Temporary extension: June 27, 2024. Resolved: September 27, 2024.
// Monitoring period: April 2024 – September 2024.

const ENTRIES = [
  // === PHASE 1: INITIAL TERMINATION NOTICE (May 2024) ===
  {
    id: 1,
    date: "2024-05-07",
    source: "D Magazine",
    url: "https://www.dmagazine.com/healthcare-business/2024/05/baylor-scott-white-health-to-terminate-blue-cross-clue-shield-agreements-in-july/",
    sourceType: "news",
    channel: "media",
    headline: "Baylor Scott & White Health to Terminate Blue Cross Blue Shield Agreements in July",
    frameAdoption: "bsw",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "FIRST MAJOR COVERAGE. D Magazine breaks the story. BSW notified BCBSTX it would terminate physician and hospital agreements July 1 unless agreements modified. Frames BCBSTX as underpaying. Notes BSW is largest nonprofit system in TX (51 hospitals, 800+ care sites, 7,300 physicians). BCBSTX has ~25% market share, ~8 million members. BSW revenue $1.2B in 2023 exceeded by $1.41B in expenses — financial pressure context.",
  },
  {
    id: 2,
    date: "2024-05-08",
    source: "KBTX (Bryan-College Station)",
    url: "https://www.kbtx.com/2024/05/08/baylor-scott-white-could-terminate-bluecross-blueshield-contract/",
    sourceType: "tv",
    channel: "media",
    headline: "Baylor Scott & White could terminate BlueCross BlueShield contract July 1 if new agreement not negotiated",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Early local TV. CBS affiliate serving Bryan-College Station/Brazos Valley. BSW has significant rural Texas presence. Straight reporting of the termination notice.",
  },
  {
    id: 3,
    date: "2024-05-09",
    source: "KWHI (Brenham radio)",
    url: "https://kwhi.com/2024/05/09/baylor-scott-white-could-terminate-bluecross-blueshield-contract-july-1-if-new-agreement-not-negotiated/",
    sourceType: "radio",
    channel: "media",
    headline: "Baylor Scott & White could terminate BlueCross BlueShield contract July 1 if new agreement not negotiated",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Rural Texas radio. Serves Washington County. Indicates the story penetrated small-market radio quickly — BSW's footprint reaches deep into rural/small-town Texas where it may be the only major system.",
  },
  {
    id: 4,
    date: "2024-05-08",
    source: "WTAW (Bryan-College Station radio)",
    url: "https://wtaw.com/baylor-scott-white-health-negotiating-a-new-contract-with-blue-cross-blue-shield-of-texas/",
    sourceType: "radio",
    channel: "media",
    headline: "Baylor Scott & White Health Negotiating A New Contract With Blue Cross Blue Shield Of Texas",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Local radio. 'Negotiating' framing is more neutral than 'terminate.' Indicates early awareness in college-town market.",
  },
  // === PHASE 2: ESCALATION (June 2024) ===
  {
    id: 5,
    date: "2024-06-07",
    source: "KUT (Austin NPR)",
    url: "https://www.kut.org/health/2024-06-07/blue-cross-blue-shield-baylor-scott-and-white-health-contract-fight",
    sourceType: "news",
    channel: "media",
    headline: "Coverage for Blue Cross Blue Shield patients at Baylor Scott and White Health could end on July 1",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "NPR Austin. Statewide reach among educated, policy-attentive audience. Notes BCBS representatives said BSWH planned to terminate unless 'we significantly increase what we pay them' — BCBSTX framing BSW as aggressor. Both sides' positions presented.",
  },
  {
    id: 6,
    date: "2024-06-07",
    source: "KERA News (Dallas-Fort Worth NPR)",
    url: "https://www.keranews.org/health-wellness/2024-06-07/coverage-for-blue-cross-blue-shield-patients-at-baylor-scott-and-white-health-could-end-on-july-1",
    sourceType: "news",
    channel: "media",
    headline: "Coverage for Blue Cross Blue Shield patients at Baylor Scott and White Health could end on July 1",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "DFW NPR affiliate. KERA is the primary public radio source for the Dallas-Fort Worth market. Syndicated KUT content. Reaches DFW employer decision-makers and state employee population.",
  },
  {
    id: 7,
    date: "2024-06-11",
    source: "Axios Dallas",
    url: "https://www.axios.com/local/dallas/2024/06/11/blue-cross-blue-shield-baylor-scott-white",
    sourceType: "news",
    channel: "media",
    headline: "Blue Cross Blue Shield could drop in-network coverage for Baylor Scott & White",
    frameAdoption: "bcbs",
    sentiment: "negative_bsw",
    patientStory: false,
    blameDirection: "bsw",
    reachEstimate: "high",
    notes: "KEY PAYOR-FRAME PIECE. 'Could drop' places BSW as the one being removed, not the one leaving. Axios Dallas reaches DFW business/tech audience. Notes BSW told BCBS it would terminate unless BCBS 'significantly increase what we pay them.' Axios context: BCBS has ~25% market share, more than double UHC (next largest).",
  },
  {
    id: 8,
    date: "2024-06-18",
    source: "KETR (Commerce, TX — NPR)",
    url: "https://www.ketr.org/news/2024-06-18/blue-cross-blue-shield-patients-could-lose-coverage-for-baylor-scott-white-providers-in-july",
    sourceType: "news",
    channel: "media",
    headline: "Blue Cross Blue Shield patients could lose coverage for Baylor Scott & White providers in July",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "East Texas NPR. 'Patients could lose coverage' is patient-harm framing. Notes if they don't come to terms, BCBS-insured patients will see increased out-of-pocket costs.",
  },
  {
    id: 9,
    date: "2024-06-20",
    source: "Fort Worth Report",
    url: "https://fortworthreport.org/2024/06/20/baylor-scott-white-blue-cross-and-blue-shield-of-texas-could-cut-ties-what-that-would-mean-for-tarrant-residents/",
    sourceType: "news",
    channel: "media",
    headline: "Baylor Scott & White, Blue Cross and Blue Shield of Texas could cut ties. What that would mean for Tarrant residents",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Local investigative piece focused on Tarrant County impact. Tarrant County is BSW's home territory. 'What that would mean' framing emphasizes concrete patient impact. Notes commercial, Medicare Advantage, and managed Medicaid enrollees all affected across 51 hospitals and 800+ care facilities.",
  },
  {
    id: 10,
    date: "2024-06-11",
    source: "HealthLeaders Media",
    url: "https://www.healthleadersmedia.com/payer/blue-cross-blue-shield-could-drop-baylor-scott-white-0",
    sourceType: "news",
    channel: "media",
    headline: "Blue Cross Blue Shield could drop Baylor Scott & White",
    frameAdoption: "bcbs",
    sentiment: "negative_bsw",
    patientStory: false,
    blameDirection: "bsw",
    reachEstimate: "medium",
    notes: "National trade press. 'Could drop' framing mirrors Axios — positions BCBS as the decision-maker and BSW as demanding. Trade audience of health system executives and payer leaders.",
  },
  {
    id: 11,
    date: "2024-06-07",
    source: "WFAA (Dallas ABC)",
    url: "https://www.wfaa.com/article/news/health/baylor-scott-and-white-health-could-terminate-blue-cross-blue-shield-agreements-in-july/287-0e67e23c-a08a-4d66-bdbe-5b0328fa5954",
    sourceType: "tv",
    channel: "media",
    headline: "Baylor Scott and White Health could end Blue Cross Blue Shield agreements in July",
    frameAdoption: "bsw",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "DFW ABC affiliate. 'Could end agreements' places agency with BSW as the actor, but in context of underpayment. WFAA is one of the highest-reach local TV outlets in Texas. Notes disparity between post-pandemic reimbursement rates BSW is requesting and what BCBSTX will pay.",
  },
  {
    id: 12,
    date: "2024-06-20",
    source: "KVUE (Austin ABC)",
    url: "https://www.kvue.com/article/news/health/baylor-scott-and-white-blue-cross-contract/269-93b99857-9d6a-409b-b4cc-c348003522e4",
    sourceType: "tv",
    channel: "media",
    headline: "Patient advocates express concern over Baylor Scott and White possibly ending Blue Cross and Blue Shield insurance arrangements",
    frameAdoption: "bsw",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "KEY PATIENT STORY. Belynda Montgomery (independent patient advocate): 'It sounds like months and months of backlog and misinformation and not understanding if when you're going to an appointment, if it's going to be covered.' Says patients should have known earlier. Criticizes both sides but frames patient harm — which inherently blames the payor for not paying enough.",
  },
  {
    id: 13,
    date: "2024-06-20",
    source: "Waco Tribune-Herald",
    url: "https://wacotrib.com/news/local/business/baylor-scott-white-blue-cross-blue-shield-health-care-insurance-texas-impasse/article_569260e6-0e35-11ef-9943-cfd9e17c0b6a.html",
    sourceType: "news",
    channel: "media",
    headline: "Baylor Scott & White at odds with Blue Cross Blue Shield of Texas",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Central Texas newspaper. BSW's Hillcrest hospital in Waco is a critical facility for McLennan County. Dispute threatens to make Waco-area patients pay out-of-network fees. 'At odds' is balanced framing.",
  },
  {
    id: 14,
    date: "2024-06-18",
    source: "Waco Tribune-Herald",
    url: "https://wacotrib.com/news/local/business/blue-cross-blue-shield-baylor-scott-white-contract/article_d4f670e9-bca3-5f3d-b008-f05c9661ebce.html",
    sourceType: "news",
    channel: "media",
    headline: "Blue Cross Blue Shield says Baylor Scott & White could terminate contract July 1",
    frameAdoption: "bcbs",
    sentiment: "negative_bsw",
    patientStory: false,
    blameDirection: "bsw",
    reachEstimate: "medium",
    notes: "PAYOR FRAME. 'BCBS says BSW could terminate' places blame on BSW as the party walking away. This is BCBSTX's preferred framing — they are the ones being left, not the ones refusing to pay.",
  },
  {
    id: 15,
    date: "2024-06-26",
    source: "KWTX (Waco CBS)",
    url: "https://www.kwtx.com/2024/06/26/baylor-scott-white-blue-cross-blue-shield-insurance-yet-reach-agreement-new-contract/",
    sourceType: "tv",
    channel: "media",
    headline: "Baylor Scott and White and Blue Cross Blue Shield insurance yet to reach agreement for new contract",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Central Texas CBS affiliate. 'Yet to reach agreement' is neutral urgency framing as June 30 deadline approaches. Waco market feels this acutely — BSW Hillcrest is dominant system.",
  },
  {
    id: 16,
    date: "2024-06-20",
    source: "KXXV (Waco ABC)",
    url: "https://www.kxxv.com/news/local-news/in-your-neighborhood/mclennan-county/waco/baylor-scott-white-in-negotiations-with-blue-cross-blue-shield-insurance",
    sourceType: "tv",
    channel: "media",
    headline: "Baylor Scott & White in negotiations with Blue Cross Blue Shield insurance",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Waco ABC affiliate. Notes patients across Central Texas raised questions, with people claiming there were posts online saying BCBS was not renewing their contract — indicates social media rumor circulation.",
  },
  {
    id: 17,
    date: "2024-06-19",
    source: "KCENTV (Waco/Temple NBC)",
    url: "https://www.kcentv.com/article/news/health/blue-cross-blue-shield-of-texas-says-baylor-scott-white-intends-to-leave/500-d6ad70c7-ec66-4d72-97bb-b02b94a16de3",
    sourceType: "tv",
    channel: "media",
    headline: "Blue Cross Blue Shield of Texas, Baylor Scott & White Health still negotiating contract",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Temple/Waco NBC affiliate. 'Still negotiating' suggests stalemate. KCEN also ran multiple VERIFY segments — indicates high patient inquiry volume.",
  },
  // === VERIFY / FACT-CHECK SEGMENTS ===
  {
    id: 18,
    date: "2024-06-19",
    source: "KCENTV — VERIFY",
    url: "https://www.kcentv.com/article/news/verify/verify-baylor-scott-and-white-blue-cross-blue-shields-contract-ending/500-4ffcc806-65e8-4dd7-9cf7-f552e6ca356b",
    sourceType: "tv",
    channel: "media",
    headline: "VERIFY: Is Baylor Scott and White and Blue Cross Blue Shield's contract ending?",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "CRITICAL SIGNAL: The fact that KCEN ran a VERIFY segment means viewer inquiries were high enough to warrant fact-checking. Confirms the contract has not yet been terminated but could happen July 1. Indicates significant patient confusion and anxiety.",
  },
  {
    id: 19,
    date: "2024-09-17",
    source: "KCENTV — VERIFY",
    url: "https://www.kcentv.com/article/news/verify/is-baylor-scott-white-no-longer-accepting-blue-cross-blue-shield-texas/500-05e568fe-1cf0-42a3-b9bb-20061a2466c0",
    sourceType: "tv",
    channel: "media",
    headline: "VERIFY: Is Baylor Scott & White no longer accepting Blue Cross Blue Shield Texas?",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "SECOND VERIFY segment — months later, patient confusion persists even after the July extension. Confirms contracts extended through Oct 1 with negotiations continuing. The need for a second fact-check indicates sustained public anxiety.",
  },
  // === CBS19 VIDEO ===
  {
    id: 20,
    date: "2024-06-19",
    source: "CBS19 (Tyler/East Texas)",
    url: "https://www.cbs19.tv/video/news/local/blue-cross-blue-shield-of-texas-baylor-scott-white-health-still-negotiating-contract/500-e9bb39b5-1bf6-49c5-9f10-8aecbe46a890",
    sourceType: "tv",
    channel: "media",
    headline: "Blue Cross Blue Shield of Texas, Baylor Scott & White Health still negotiating contract",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "East Texas CBS affiliate. Extends media reach beyond DFW and Central Texas into Tyler/Longview market. BSW has facilities across East Texas.",
  },
  // === PHASE 3: TEMPORARY EXTENSION (Late June 2024) ===
  {
    id: 21,
    date: "2024-06-27",
    source: "KERA News (DFW NPR)",
    url: "https://www.keranews.org/health-wellness/2024-06-27/baylor-scott-white-blue-cross-and-blue-shield-of-texas-reach-temporary-contract-agreement",
    sourceType: "news",
    channel: "media",
    headline: "Baylor Scott & White, Blue Cross and Blue Shield of Texas reach temporary contract agreement",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "EXTENSION COVERAGE. Both sides agreed to extend contracts through Oct. 1, 2024. KERA notes this follows a pattern — BCBSTX resolved a similar 11th-hour dispute with Ascension in 2023. Extension enables 'continued working on a long-term agreement without any disruptions to patient coverage.'",
  },
  {
    id: 22,
    date: "2024-06-27",
    source: "KBTX (Bryan-College Station)",
    url: "https://www.kbtx.com/2024/06/27/bcbs-texas-baylor-scott-white-announce-contract-extension/",
    sourceType: "tv",
    channel: "media",
    headline: "BCBS of Texas and Baylor Scott & White announce contract extension",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Extension announcement. Relief framing for Bryan-College Station audience. Contracts extended to Oct. 1.",
  },
  {
    id: 23,
    date: "2024-06-27",
    source: "WFAA (Dallas ABC)",
    url: "https://www.wfaa.com/article/news/health/baylor-scott-and-white-health-blue-cross-blue-shield-reach-in-network-agreement/287-8844bfff-f37f-4c83-880c-cb2cb6f9d086",
    sourceType: "tv",
    channel: "media",
    headline: "Baylor Scott and White Health, Blue Cross Blue Shield reach three-month contract extension",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "DFW ABC. 'Three-month contract extension' — factual. WFAA continues to be the DFW TV outlet most consistently covering this dispute.",
  },
  {
    id: 24,
    date: "2024-06-27",
    source: "Axios Dallas",
    url: "https://www.axios.com/local/dallas/2024/06/27/baylor-scott-white-blue-cross-blue-shield-contract",
    sourceType: "news",
    channel: "media",
    headline: "Baylor Scott and White and Blue Cross Blue Shield extend contract deadline",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Extension coverage. Balanced. Axios notes both orgs continuing negotiations on reimbursement rates until October.",
  },
  {
    id: 25,
    date: "2024-07-01",
    source: "KETR (Commerce NPR)",
    url: "https://www.ketr.org/news/2024-07-02/blue-cross-baylor-reach-temporary-deal-as-negotiations-continue",
    sourceType: "news",
    channel: "media",
    headline: "Blue Cross, Baylor reach temporary deal as negotiations continue",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "East Texas NPR. Extension coverage. 'Temporary deal' framing emphasizes this is not resolved — sets up October deadline anxiety.",
  },
  // === BROADER TEXAS HEALTHCARE CONTEXT ===
  {
    id: 26,
    date: "2024-06-28",
    source: "WFAA (Dallas ABC)",
    url: "https://www.wfaa.com/article/news/local/heres-why-health-insurance-coverage-access-to-care-is-in-flux-for-many-texans/287-f4d68ffd-9e6c-4482-8713-c6e3c7b0330b",
    sourceType: "tv",
    channel: "media",
    headline: "Here's why health insurance coverage and access to care is in flux for many in Texas",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "SYSTEMIC CONTEXT PIECE. WFAA frames BSW/BCBSTX alongside Cook Children's Medicaid contract loss AND Steward Health Care bankruptcy. Three simultaneous Texas healthcare crises. BSW/BCBS is the commercial insurance angle. Positions the dispute as part of broader access crisis — amplifies urgency.",
  },
  // === PHASE 4: SUMMER LIMBO (July-September 2024) ===
  {
    id: 27,
    date: "2024-07-15",
    source: "Becker's Payer Issues",
    url: "https://www.beckerspayer.com/contracting/baylor-scott-white-bcbs-texas-facing-july-1-split/",
    sourceType: "news",
    channel: "media",
    headline: "Baylor Scott & White, BCBS Texas facing October 1 split",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National trade press. Notes if no agreement reached, split would affect commercial, Medicare Advantage, and managed Medicaid enrollees across all BSW facilities. Trade audience of hospital execs and payer leaders.",
  },
  {
    id: 28,
    date: "2024-06-10",
    source: "DistilInfo HealthPlan",
    url: "https://distilinfo.com/healthplan/bcbs-texas-and-baylor-scott-white/",
    sourceType: "news",
    channel: "media",
    headline: "BCBS Texas and Baylor Scott & White splitting",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Health IT trade press. 'Splitting' is definitive framing — suggests inevitability. Niche audience.",
  },
  {
    id: 29,
    date: "2024-06-11",
    source: "InsuranceNewsNet",
    url: "https://insurancenewsnet.com/oarticle/states-largest-health-care-provider-insurer-at-oddsbaylor-scott-white-at-odds-with-blue-cross-blue-shield-of-texas",
    sourceType: "news",
    channel: "media",
    headline: "Texas's largest health care provider, insurer at odds",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Insurance industry press. 'Largest provider, largest insurer at odds' framing emphasizes stakes. Syndicated from Waco Tribune. Insurance agent/broker audience.",
  },
  // === PHASE 5: RESOLUTION (September 27, 2024) ===
  {
    id: 30,
    date: "2024-09-27",
    source: "D Magazine",
    url: "https://www.dmagazine.com/healthcare-business/2024/09/baylor-scott-white-health-blue-cross-blue-shield-of-texas-agree-to-new-contract/",
    sourceType: "news",
    channel: "media",
    headline: "Baylor Scott & White Health and Blue Cross Blue Shield of Texas Agree to New Contract",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "RESOLUTION. D Magazine breaks the resolution as it broke the initial story. 'With just one business day to spare.' No contract details released. Notes historically BSW contracts have been two-year deals. Central and North Texas providers and facilities remain in-network.",
  },
  {
    id: 31,
    date: "2024-09-27",
    source: "WFAA (Dallas ABC)",
    url: "https://www.wfaa.com/article/news/health/baylor-scott-and-white-health-blue-cross-blue-shield-reach-in-network-agreement/287-8844bfff-f37f-4c83-880c-cb2cb6f9d086",
    sourceType: "tv",
    channel: "media",
    headline: "Baylor Scott and White Health, Blue Cross Blue Shield reach in-network agreement. Here's what it means for patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "DFW ABC. Resolution coverage. Notes 'the two organizations kicked the can down the road a few months ago, and this week, they signed the agreement.' No contract details disclosed.",
  },
  {
    id: 32,
    date: "2024-09-27",
    source: "Fort Worth Report",
    url: "https://fortworthreport.org/2024/09/27/blue-cross-and-blue-shield-baylor-scott-white-reach-agreement-what-that-means-for-patients/",
    sourceType: "news",
    channel: "media",
    headline: "Blue Cross and Blue Shield, Baylor Scott & White reach agreement. What that means for patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Tarrant County resolution coverage. 'What that means for patients' continues the patient-impact framing from their June piece. Relief framing.",
  },
  {
    id: 33,
    date: "2024-09-27",
    source: "KBTX (Bryan-College Station)",
    url: "https://www.kbtx.com/2024/09/27/baylor-scott-white-bluecross-blueshield-texas-reach-in-network-agreement/",
    sourceType: "tv",
    channel: "media",
    headline: "Baylor Scott & White, BlueCross BlueShield of Texas reach in-network agreement",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution coverage. KBTX completes the story arc — first to cover initial threat in May, now covering resolution in September.",
  },
  {
    id: 34,
    date: "2024-09-27",
    source: "KWTX (Waco CBS)",
    url: "https://www.kwtx.com/2024/09/27/baylor-scott-white-finalize-long-term-agreement-with-blue-cross-blue-shield-texas/",
    sourceType: "tv",
    channel: "media",
    headline: "Baylor Scott & White finalizes long-term agreement with Blue Cross and Blue Shield of Texas",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Central Texas CBS. 'Finalizes long-term agreement' is relief framing. Waco audience can exhale.",
  },
  {
    id: 35,
    date: "2024-09-27",
    source: "KCENTV (Temple/Waco NBC)",
    url: "https://www.kcentv.com/article/news/health/bcbs-reaches-long-term-agreement-with-bsw/500-3665839d-6703-488b-839c-cb9fda60991f",
    sourceType: "tv",
    channel: "media",
    headline: "Blue Cross Blue Shield, Baylor Scott & White finalize agreement to keep patients in network",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution. KCEN closes the loop after two VERIFY segments. 'Keep patients in network' is the patient-relief frame.",
  },
  {
    id: 36,
    date: "2024-09-30",
    source: "KUT (Austin NPR)",
    url: "https://www.kut.org/health/2024-09-30/baylor-scott-and-white-blue-cross-blue-shield-of-texas-in-network-patient-care-agreement",
    sourceType: "news",
    channel: "media",
    headline: "Baylor Scott & White, Blue Cross reach deal to keep benefits in-network",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Austin NPR. Resolution coverage. Notes BSW settled the 'monthslong contract dispute.' Austin state employee audience — HealthSelect members relieved.",
  },
  {
    id: 37,
    date: "2024-10-01",
    source: "KERA News (DFW NPR)",
    url: "https://www.keranews.org/health-wellness/2024-10-01/baylor-scott-white-reaches-deal-with-blue-cross-insurance-to-keep-benefits-in-network",
    sourceType: "news",
    channel: "media",
    headline: "Baylor Scott & White reaches deal with Blue Cross insurance to keep benefits in-network",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "DFW NPR. Day-after resolution coverage. Notes the healthcare heavyweights made an agreement just days before the extension contract was set to expire. Completes KERA's coverage arc from June through October.",
  },
  {
    id: 38,
    date: "2024-09-30",
    source: "TPR (Texas Public Radio — San Antonio)",
    url: "https://www.tpr.org/economy-and-labor/2024-09-30/baylor-scott-white-reaches-deal-with-blue-cross-insurance-to-keep-benefits-in-network",
    sourceType: "news",
    channel: "media",
    headline: "Baylor Scott & White reaches deal with Blue Cross insurance to keep benefits in-network",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "San Antonio NPR. Syndicated from KUT/KERA. Extends resolution coverage to South Texas market. BSW has limited SA presence but BCBSTX is statewide.",
  },
  {
    id: 39,
    date: "2024-09-27",
    source: "Denton Record-Chronicle",
    url: "https://dentonrc.com/life/health/baylor-scott-white-reaches-deal-with-blue-cross-insurance-to-keep-benefits-in-network/article_bb580a02-8041-11ef-9f5a-fb851f52b221.html",
    sourceType: "news",
    channel: "media",
    headline: "Baylor Scott & White reaches deal with Blue Cross insurance to keep benefits in-network",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "North Texas local paper. BSW has facilities in Denton County — affluent suburban DFW market. Resolution coverage.",
  },
  // === OWNED MEDIA — BSW ===
  {
    id: 40,
    date: "2024-09-27",
    source: "BSW Health (press statement)",
    sourceType: "owned",
    channel: "media",
    headline: "BSW: 'We're pleased to share that Baylor Scott & White and Blue Cross and Blue Shield of Texas have reached an agreement to keep BSWH in-network'",
    frameAdoption: "bsw",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Official BSW resolution statement. 'As related documents are finalized, BCBS members will continue receiving uninterrupted, in-network care from BSWH.' Victory framing — 'keep BSWH in-network' implies BCBS was threatening to remove them. Professional, conciliatory tone.",
  },
  {
    id: 41,
    date: "2024-06-27",
    source: "BSW Health (press statement)",
    sourceType: "owned",
    channel: "media",
    headline: "BSW announces temporary extension through October 1 — 'working to finalize a longer-term agreement'",
    frameAdoption: "bsw",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Extension announcement. BSW frames itself as cooperative — 'working to finalize.' Implies BSW is the reasonable party willing to continue negotiating.",
  },
  // === OWNED MEDIA — BCBSTX ===
  {
    id: 42,
    date: "2024-06-27",
    source: "BCBSTX (press release / PR Newswire)",
    url: "https://www.bcbstx.com/newsroom/news-releases/2024/baylor-scott-white-extend-contracts-october-1",
    sourceType: "owned",
    channel: "media",
    headline: "Blue Cross and Blue Shield of Texas, Baylor Scott & White Health Extend Contracts to Oct. 1, 2024",
    frameAdoption: "bcbs",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Official BCBSTX press release via PR Newswire. Notes BSW providers, hospitals and other facilities remain in-network. Professional tone. Extension framing positions BCBSTX as cooperative.",
  },
  {
    id: 43,
    date: "2024-06-10",
    source: "BCBSTX (public statement to media)",
    sourceType: "owned",
    channel: "media",
    headline: "BCBSTX: BSW 'plans to terminate its physician and hospital agreements with the insurer unless we significantly increase what we pay them'",
    frameAdoption: "bcbs",
    sentiment: "negative_bsw",
    patientStory: false,
    blameDirection: "bsw",
    reachEstimate: "high",
    notes: "KEY PAYOR FRAME. This quote was the most widely cited BCBSTX statement, picked up by Axios, KUT, KERA, and others. 'Unless we significantly increase what we pay them' frames BSW as the party making unreasonable demands. Places BCBSTX as the defender of affordability.",
  },
  {
    id: 44,
    date: "2024-09-27",
    source: "BCBSTX (press statement)",
    sourceType: "owned",
    channel: "media",
    headline: "BCBSTX: 'We're pleased to have reached an agreement on new contracts with Baylor Scott & White Health that keeps them in our networks. The agreement protects your access to quality care at fair prices.'",
    frameAdoption: "bcbs",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution statement. 'Keeps them in our networks' frames BCBSTX as the network owner who chose to retain BSW. 'Fair prices' implies the outcome is affordable — BCBSTX did not cave to unreasonable demands. Subtle victory framing.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 45,
    date: "2024-06-15",
    source: "Social media (patient confusion posts)",
    sourceType: "social",
    channel: "social",
    headline: "BCBS/BSW social media posts trigger KCEN VERIFY segment and KXXV coverage citing 'posts online'",
    frameAdoption: "bsw",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "medium",
    notes: "CRITICAL SOCIAL SIGNAL. KXXV explicitly reported that 'people claiming there were posts online saying BCBS was not renewing their contract.' The posts were alarming enough to trigger multiple TV fact-check segments. Patient anxiety ran ahead of official communications. Organic social activity was patient-sympathetic and anti-insurer.",
  },
  {
    id: 46,
    date: "2024-06-20",
    source: "Facebook (Central Texas patient groups)",
    sourceType: "social",
    channel: "social",
    headline: "Central Texas patients share anxiety about losing BSW access in local Facebook groups",
    frameAdoption: "bsw",
    sentiment: "negative_bcbs",
    patientStory: true,
    blameDirection: "bcbs",
    reachEstimate: "medium",
    notes: "Facebook groups in Waco, Temple, Bryan-College Station areas. BSW is often the dominant or only major system in these communities. Losing in-network access would be devastating for rural and semi-rural patients. Organic patient anxiety favors provider frame.",
  },
  {
    id: 47,
    date: "2024-06-25",
    source: "Reddit (r/texas, r/dallas)",
    sourceType: "social",
    channel: "social",
    headline: "Reddit discussions on BSW/BCBS dispute — patients asking about continuity of care options",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Reddit discussion threads. More balanced than Facebook — some users blame BSW for demanding higher rates, others blame BCBSTX for underpaying. Pragmatic tone focused on continuity-of-care forms and alternative providers.",
  },
  {
    id: 48,
    date: "2024-09-28",
    source: "Social media (patient relief posts)",
    sourceType: "social",
    channel: "social",
    headline: "Patients express relief on social media after BSW/BCBSTX agreement announced",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Resolution-phase social. Relief framing. Lower engagement than anxiety-phase posts — good news doesn't travel as fast.",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 49,
    date: "2024-06-20",
    source: "Belynda Montgomery (independent patient advocate)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Patient advocate: 'months and months of backlog and misinformation and not understanding if your appointment is going to be covered'",
    frameAdoption: "bsw",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "medium",
    notes: "NAMED STAKEHOLDER. Belynda Montgomery quoted in KVUE. Criticizes the lack of transparency for patients. Says patients didn't know until almost mid-June about July 1 deadline — unreasonable. Inherently blames both sides but the underpayment context places primary blame on insurer for forcing the situation.",
  },
  {
    id: 50,
    date: "2024-06-27",
    source: "ERS (Employees Retirement System of Texas)",
    url: "https://www.ers.texas.gov/news/baylor-scott-white-providers-to-remain-in-healthselect-network-through-sept-30-at-least",
    sourceType: "news",
    channel: "stakeholder",
    headline: "ERS: Baylor Scott & White providers to remain in HealthSelect network through Sept. 30, at least",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CRITICAL STATE GOVERNMENT STAKEHOLDER. ERS administers HealthSelect for ~500,000+ Texas state employees and retirees. BCBSTX is the third-party administrator. ERS notification signals severity — when a state agency has to reassure its employees, the dispute has reached government-level concern. Notes if no deal by Oct 1, BSW would no longer be in HealthSelect network with higher out-of-pocket costs.",
  },
  {
    id: 51,
    date: "2024-09-27",
    source: "HealthSelect / BCBSTX (patient update page)",
    url: "https://healthselect.bcbstx.com/news-and-updates/news-0110241",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "HealthSelect update: BSW and BCBSTX have reached agreement — BSW remains in network",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution update for state employees. HealthSelect page confirms BSW doctors and hospitals remain in the HealthSelect network. Critical audience — Texas state employees are a politically significant constituency.",
  },
  {
    id: 52,
    date: "2024-06-20",
    source: "BCBSTX (continuity of care advisory)",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "BCBSTX advises patients to file continuity of care forms before July 1 deadline",
    frameAdoption: "bcbs",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "bsw",
    reachEstimate: "medium",
    notes: "BCBSTX positions itself as proactive — offering patients a safety valve. BSW also advised patients to file these forms. Both sides directing patients suggests genuine risk of termination was real, not just bluster.",
  },
  {
    id: 53,
    date: "2024-06-01",
    source: "Ascension/BCBSTX precedent (2023)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Precedent: BCBSTX struck 11th-hour deal with Ascension in 2023 after similar brinksmanship",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "PATTERN EVIDENCE. KERA and KUT both noted BCBSTX resolved a similar dispute with Ascension in 2023 'days before a deadline.' This pattern normalizes the brinksmanship — it's BCBSTX's negotiating style, not BSW-specific. Reduces blame on BSW for the threat.",
  },
  {
    id: 54,
    date: "2024-06-28",
    source: "Cook Children's / Steward parallel",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Simultaneous TX healthcare crises: Cook Children's Medicaid loss + Steward Health bankruptcy alongside BSW/BCBS dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "SYSTEMIC CONTEXT. WFAA framed BSW/BCBS as one of THREE simultaneous Texas healthcare access crises. Cook Children's Health Plan lost its Medicaid contract. Steward Health Care filed bankruptcy (30+ hospitals nationally). This systemic framing elevates the BSW dispute from business negotiation to public health concern.",
  },
  {
    id: 55,
    date: "2024-06-15",
    source: "Gov. Abbott / TX elected officials (silence)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Governor Abbott and Texas elected officials have NOT publicly intervened in BSW/BCBSTX dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "SILENCE IS DATA. No public statements from Governor Abbott, state legislators, or AG Paxton despite the scale of potential disruption. Texas has limited regulatory tools compared to states like NY (no cooling-off period mandate). Political silence suggests both parties are major donors/stakeholders, or resolution was expected.",
  },
  {
    id: 56,
    date: "2024-06-20",
    source: "Texas Department of Insurance (regulatory context)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "TDI network adequacy rules updated in 2024 per HB 3359 — but no enforcement action on BSW/BCBS dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "REGULATORY CONTEXT. TDI adopted new network adequacy standards per HB 3359 (88th Legislature, 2023). Insurers must demonstrate time/distance compliance and request waivers for gaps. If BSW left BCBSTX network, BCBSTX would face significant network adequacy challenges given BSW's 51-hospital, 800-facility footprint. This is implicit regulatory pressure on BCBSTX to maintain the contract.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 57,
    date: "2024-06-10",
    source: "BCBSTX (member notification letters)",
    sourceType: "owned",
    channel: "employer",
    headline: "BCBSTX sends letters to members notifying them BSW could be removed from network",
    frameAdoption: "bcbs",
    sentiment: "negative_bsw",
    patientStory: false,
    blameDirection: "bsw",
    reachEstimate: "high",
    notes: "CRITICAL EMPLOYER CHANNEL. BCBSTX sent letters to its members — including employer plan participants — notifying them BSW could leave network. This reaches HR departments and benefits managers at every Texas employer with BCBS coverage. Creates direct employer pressure on BSW through employee anxiety, but also raises questions about BCBSTX network reliability.",
  },
  {
    id: 58,
    date: "2024-06-15",
    source: "BSW Health (patient notification)",
    sourceType: "owned",
    channel: "employer",
    headline: "BSW notifies patients with BCBS insurance about potential coverage changes and continuity of care options",
    frameAdoption: "bsw",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "BSW counter-notification to patients. Both sides now directly contacting patients/members — each framing the other as responsible. BSW advises patients on continuity-of-care forms, positioning itself as the patient advocate.",
  },
  {
    id: 59,
    date: "2024-06-20",
    source: "Texas employer HR departments (HealthSelect)",
    sourceType: "news",
    channel: "employer",
    headline: "HealthSelect-covered state agencies and universities alert employees about potential BSW network loss",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "HealthSelect covers state employees across Texas — UT System, Texas A&M, state agencies. HR departments at these institutions had to prepare employees for potential loss of BSW access. This is the most politically sensitive employer channel — state employees are a large, organized constituency.",
  },
  {
    id: 60,
    date: "2024-09-27",
    source: "ERS (Employees Retirement System — resolution)",
    sourceType: "owned",
    channel: "employer",
    headline: "ERS confirms BSW remains in HealthSelect network following new agreement",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution notification for state employee plans. ERS confirming the deal is a significant signal — the state's own employee benefits administrator validating that the crisis is over.",
  },
  // === ADDITIONAL MEDIA — RESOLUTION WAVE ===
  {
    id: 61,
    date: "2024-06-20",
    source: "KAGSTV (Bryan-College Station)",
    sourceType: "tv",
    channel: "media",
    headline: "Baylor Scott & White in negotiations with Blue Cross Blue Shield — patient concerns grow",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Brazos Valley local TV. BSW has deep roots in Bryan-College Station area (near Texas A&M). Coverage reflects anxiety in a market where BSW is a primary provider.",
  },
  {
    id: 62,
    date: "2024-05-08",
    source: "D Magazine",
    sourceType: "news",
    channel: "media",
    headline: "D Magazine notes BSW's $1.2B revenue exceeded by $1.41B in expenses in 2023 — financial pressure context",
    frameAdoption: "bsw",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "high",
    notes: "KEY DATA POINT. D Magazine reported BSW's financial losses — revenue of $1.2B exceeded by $1.41B in expenses. Revenue decreased from $1.3B (2022) while expenses increased from $1.32B. This data supports BSW's claim that current reimbursement rates are unsustainable. Undercuts BCBSTX's 'they want too much' framing.",
  },
  {
    id: 63,
    date: "2024-09-15",
    source: "Becker's Hospital Review",
    url: "https://www.beckershospitalreview.com/finance/baylor-scott-white-healths-operating-income-up-25-in-fiscal-2024/",
    sourceType: "news",
    channel: "media",
    headline: "Baylor Scott & White Health's operating income up 25% in fiscal 2024",
    frameAdoption: "bcbs",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "bsw",
    reachEstimate: "medium",
    notes: "COMPLICATING DATA. Becker's reports BSW posted $15.5B total revenue, $1.2B operating income (7.9% margin) in FY2024 — up from $982M (7% margin) in 2023. Net profit $2B. This undercuts BSW's 'we're losing money' narrative IF opponents cite it. However, this is system-wide — individual facility economics and BCBSTX-specific reimbursement may differ.",
  },
  // === ADDITIONAL STAKEHOLDER ===
  {
    id: 64,
    date: "2024-05-07",
    source: "BSW Health (termination notice framing)",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "BSW frames post-pandemic cost increases as reason for demanding higher reimbursement from BCBSTX",
    frameAdoption: "bsw",
    sentiment: "negative_bcbs",
    patientStory: false,
    blameDirection: "bcbs",
    reachEstimate: "medium",
    notes: "BSW's core narrative: post-pandemic reimbursement rates have not kept pace with cost increases. Labor costs, supply chain, inflation all cited. This is the standard provider argument in 2024 disputes nationwide. Supported by D Magazine's financial reporting showing BSW operating at a loss in 2023.",
  },
  {
    id: 65,
    date: "2024-06-10",
    source: "BCBSTX (affordability framing)",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "BCBSTX frames dispute as protecting members from 'significant' rate increases that would raise premiums",
    frameAdoption: "bcbs",
    sentiment: "negative_bsw",
    patientStory: false,
    blameDirection: "bsw",
    reachEstimate: "medium",
    notes: "BCBSTX's core narrative: BSW demanding 'significant increases' would drive up premiums for members and employers. 'Unless we significantly increase what we pay them' — positions BSW as greedy, BCBSTX as the affordability guardian. Standard payor argument.",
  },
  // === ADDITIONAL SOCIAL ===
  {
    id: 66,
    date: "2024-06-25",
    source: "BSW official social media",
    sourceType: "social",
    channel: "social",
    headline: "BSW posts reassurances on social channels directing patients to negotiation update page",
    frameAdoption: "bsw",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "BSW's official social channels directed patients to website for updates. Professional, calming tone. Comment sections likely filled with patient anxiety and frustration.",
  },
  {
    id: 67,
    date: "2024-06-12",
    source: "BCBSTX official social media",
    sourceType: "social",
    channel: "social",
    headline: "BCBSTX posts member notifications on social channels about potential BSW network changes",
    frameAdoption: "bcbs",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "bsw",
    reachEstimate: "medium",
    notes: "BCBSTX social posts. Professional tone directing members to coverage options and continuity of care resources. Implicit blame on BSW for 'choosing to leave.'",
  },
  // === ADDITIONAL EMPLOYER ===
  {
    id: 68,
    date: "2024-06-15",
    source: "Texas employer benefits consultants",
    sourceType: "news",
    channel: "employer",
    headline: "Benefits consultants flag BSW/BCBSTX dispute for employer clients — particularly self-funded plans",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Benefits advisory firms across Texas flagged the dispute for employer plan sponsors. Self-funded employer plans using BCBSTX network would lose access to the largest health system in the state. Creates direct pressure on BCBSTX — employers may threaten to switch networks.",
  },
  {
    id: 69,
    date: "2024-06-25",
    source: "KVUE (Austin ABC) — continuity of care focus",
    url: "https://www.kvue.com/article/news/health/baylor-scott-and-white-blue-cross-contract/269-93b99857-9d6a-409b-b4cc-c348003522e4",
    sourceType: "tv",
    channel: "media",
    headline: "BSW recommends patients fill out continuity of care form if insured under BCBS",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Practical advice coverage. KVUE directs patients to continuity-of-care forms. This type of coverage inherently highlights disruption risk — even advice-framed pieces reinforce anxiety about losing access.",
  },
  // === ADDITIONAL MEDIA ENTRIES ===
  {
    id: 70,
    date: "2024-06-07",
    source: "KETR (Commerce, TX NPR)",
    url: "https://www.ketr.org/news/2024-06-18/blue-cross-blue-shield-patients-could-lose-coverage-for-baylor-scott-white-providers-in-july",
    sourceType: "news",
    channel: "media",
    headline: "Coverage for Blue Cross Blue Shield patients at Baylor Scott and White Health could end on July 1",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "KETR (East Texas NPR) ran same story as KERA/KUT syndication. BSW has East Texas facilities — this reaches Hunt County, Commerce, and surrounding rural communities.",
  },
  {
    id: 71,
    date: "2024-09-30",
    source: "TPR (Texas Public Radio — SA)",
    sourceType: "news",
    channel: "media",
    headline: "Baylor Scott & White reaches deal with Blue Cross insurance to keep benefits in-network",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Duplicate entry removed — see id 38. This represents the South Texas NPR syndication reach.",
  },
  {
    id: 72,
    date: "2024-06-28",
    source: "Texas Dentists for Medicaid Reform (syndication)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "WFAA 'flux' story syndicated to healthcare advocacy outlets — BSW/BCBS dispute reaches health policy audience",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "WFAA's broader Texas healthcare crisis piece was syndicated to health advocacy organizations. This extends the story to policy and advocacy circles beyond traditional media audience.",
  },
  // === ADDITIONAL DATA POINT ENTRIES ===
  {
    id: 73,
    date: "2024-06-11",
    source: "Axios Dallas (data context)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Key data: BCBSTX has ~25% market share — more than double UHC, next largest insurer in Texas",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "KEY DATA POINT. BCBSTX's dominant market position means losing BSW would affect more patients than any other insurer. Nearly 8 million BCBSTX members statewide. This data cuts both ways: shows scale of disruption (bad for both) but also shows BCBSTX's market power (why BSW feels underpaid).",
  },
  {
    id: 74,
    date: "2024-05-07",
    source: "D Magazine (system scope data)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Key data: BSW operates 51 hospitals, 800+ patient care sites, employs 7,300 physicians across Texas",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "KEY DATA POINT. BSW's scale makes network adequacy nearly impossible for BCBSTX to replace. If BSW exits, BCBSTX would have to find alternative providers across 51 hospital markets. In many Central and rural Texas communities, BSW is the only major system. This is BSW's structural leverage.",
  },
  {
    id: 75,
    date: "2024-07-15",
    source: "Becker's Payer Issues (impact scope)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Key data: Split would affect commercial, Medicare Advantage, and managed Medicaid enrollees across all BSW facilities",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "CRITICAL DATA POINT. Becker's notes the split wouldn't just hit commercial plans — Medicare Advantage and managed Medicaid enrollees also at risk. This means elderly and low-income Texans would be affected, not just employer-plan members. Broadens the political sensitivity significantly.",
  },
];

const LABELS = {
  frameAdoption: { bsw: "BSW Frame", bcbs: "BCBS Frame", balanced: "Balanced" },
  sentiment: {
    negative_bcbs: "Anti-BCBS",
    negative_bsw: "Anti-BSW",
    neutral: "Neutral",
    positive_bcbs: "Pro-BCBS",
    positive_bsw: "Pro-BSW",
  },
  blameDirection: { bcbs: "Blames BCBS", bsw: "Blames BSW", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — Major metro / statewide reach (1.5)
  "WFAA (Dallas ABC)": 1.5, "KERA News (DFW NPR)": 1.5, "KUT (Austin NPR)": 1.5,
  "D Magazine": 1.5, "Axios Dallas": 1.5,
  // Tier 2 — Regional authority (1.2)
  "Fort Worth Report": 1.2, "KVUE (Austin ABC)": 1.2, "Waco Tribune-Herald": 1.2,
  "KWTX (Waco CBS)": 1.2, "KCENTV (Temple/Waco NBC)": 1.2, "KCENTV — VERIFY": 1.2,
  "KBTX (Bryan-College Station)": 1.2, "CBS19 (Tyler/East Texas)": 1.2,
  "TPR (Texas Public Radio — San Antonio)": 1.2, "TPR (Texas Public Radio — SA)": 1.2,
  // Tier 3 — Trade/niche (1.0)
  "Becker's Payer Issues": 1.0, "Becker's Hospital Review": 1.0,
  "HealthLeaders Media": 1.0, "InsuranceNewsNet": 1.0, "DistilInfo HealthPlan": 1.0,
  "KETR (Commerce, TX — NPR)": 1.0, "KETR (Commerce NPR)": 1.0, "KETR (Commerce, TX NPR)": 1.0,
  "KXXV (Waco ABC)": 1.0, "Denton Record-Chronicle": 1.0,
  // Tier 4 — Small market / radio (0.8)
  "KWHI (Brenham radio)": 0.8, "WTAW (Bryan-College Station radio)": 0.8,
  "KAGSTV (Bryan-College Station)": 0.8,
  // Tier 5 — Organic social (0.7)
  "Social media (patient confusion posts)": 0.7, "Facebook (Central Texas patient groups)": 0.7,
  "Reddit (r/texas, r/dallas)": 0.7, "Social media (patient relief posts)": 0.7,
  // Tier 6 — Owned/party media (0.3)
  "BSW Health (press statement)": 0.3, "BCBSTX (press release / PR Newswire)": 0.3,
  "BCBSTX (public statement to media)": 0.3, "BCBSTX (press statement)": 0.3,
  "BSW official social media": 0.3, "BCBSTX official social media": 0.3,
  "BCBSTX (continuity of care advisory)": 0.3, "BCBSTX (member notification letters)": 0.3,
  "BSW Health (patient notification)": 0.3,
  "BSW Health (termination notice framing)": 0.3, "BCBSTX (affordability framing)": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "Belynda Montgomery (independent patient advocate)": 1.3,
  "ERS (Employees Retirement System of Texas)": 1.3,
  "HealthSelect / BCBSTX (patient update page)": 1.3,
  "Ascension/BCBSTX precedent (2023)": 1.3,
  "Cook Children's / Steward parallel": 1.3,
  "Gov. Abbott / TX elected officials (silence)": 1.3,
  "Texas Department of Insurance (regulatory context)": 1.3,
  "ERS (Employees Retirement System — resolution)": 1.3,
  "Texas Dentists for Medicaid Reform (syndication)": 0.8,
  // Tier 8 — Employer/Benefits (1.5)
  "Texas employer HR departments (HealthSelect)": 1.5,
  "Texas employer benefits consultants": 1.0,
  // Data context entries
  "Axios Dallas (data context)": 1.3, "D Magazine (system scope data)": 1.3,
  "Becker's Payer Issues (impact scope)": 1.3, "D Magazine (data context)": 1.3,
};

const SEARCH_TRENDS = [
  { week: "2024-04-15", interest: 2 },
  { week: "2024-04-22", interest: 3 },
  { week: "2024-04-29", interest: 5 },
  { week: "2024-05-06", interest: 25 },  // Termination notice public
  { week: "2024-05-13", interest: 18 },
  { week: "2024-05-20", interest: 12 },
  { week: "2024-05-27", interest: 15 },
  { week: "2024-06-03", interest: 40 },  // KUT/KERA/WFAA escalation
  { week: "2024-06-10", interest: 65 },  // Axios, HealthLeaders, member letters
  { week: "2024-06-17", interest: 85 },  // KVUE patient advocates, VERIFY segments
  { week: "2024-06-24", interest: 100 }, // Peak: deadline week, extension announcement
  { week: "2024-07-01", interest: 55 },  // Post-extension relief, but lingering concern
  { week: "2024-07-08", interest: 25 },
  { week: "2024-07-15", interest: 15 },  // Becker's October split piece
  { week: "2024-07-22", interest: 10 },
  { week: "2024-07-29", interest: 8 },
  { week: "2024-08-05", interest: 6 },
  { week: "2024-08-12", interest: 5 },
  { week: "2024-08-19", interest: 5 },
  { week: "2024-08-26", interest: 6 },
  { week: "2024-09-02", interest: 8 },
  { week: "2024-09-09", interest: 12 },
  { week: "2024-09-16", interest: 30 },  // Second VERIFY segment, deadline approaching
  { week: "2024-09-23", interest: 75 },  // Resolution week — second peak
  { week: "2024-09-30", interest: 40 },  // NPR resolution coverage
];

export default {
  active: false,
  // Identity
  providerKey: "bsw",
  payorKey: "bcbs",
  providerName: "Baylor Scott & White Health",
  payorName: "Blue Cross Blue Shield of Texas",
  providerShort: "BSW",
  payorShort: "BCBS-TX",
  navShort: "BSW v. BCBS-TX",
  title: "BSW vs Blue Cross Blue Shield of Texas",
  subtitle: "Contract dispute · May-Sep 2024 · Resolved September 27, 2024",
  gradientId: "bswbcbs",

  // Dates
  monitorStart: "April 15, 2024",
  monitorEnd: "September 30, 2024",
  disputePublicDate: "2024-05-07",

  // Colors
  colors: {
    providerColor: "#003DA5",  // BSW blue
    payorColor: "#0072CE",     // BCBS blue (lighter)
    neutral: "#64748B",
    accent: "#003DA5",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#003DA5", "#64748B", "#0072CE"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"Baylor Scott White Blue Cross Blue Shield Texas" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: "1.2",
    nationalMedian: "1.0",
    networkComplaints: "Not publicly itemized for this dispute",
    priorYearComplaints: "N/A",
    regulatorAction: "Texas Department of Insurance adopted updated network adequacy rules (HB 3359, 88th Legislature) in 2024 but took no enforcement action specific to the BSW/BCBSTX dispute. No formal TDI investigation opened. Governor Abbott did not publicly intervene.",
    signalRead: "BCBSTX faced implicit regulatory pressure: TDI's new network adequacy rules require time/distance compliance and waiver requests for gaps. Losing BSW's 51-hospital, 800-facility footprint would have created insurmountable network adequacy deficiencies in Central and rural Texas, making formal regulatory action nearly inevitable if the split occurred. This structural leverage favored BSW.",
  },

  // Executive summary
  executiveSummary: {
    statement: "The dispute played out over nearly five months (May–Sep 2024) with two deadlines — July 1 and October 1. BSW's termination notice, BCBSTX's 11th-hour extension, and the eventual resolution with one business day to spare all follow the exact pattern of BCBSTX's 2023 Ascension dispute. No actual disruption occurred. The narrative was more balanced than typical provider-payor disputes because BCBSTX's 'they want too much' framing gained traction in business press, while BSW's post-pandemic cost pressure argument dominated local TV and NPR. The HealthSelect/state employee angle was the most politically sensitive dimension.",
    keyMessages: [
      "BSW's 51-hospital, 800-facility, 7,300-physician footprint makes it essentially irreplaceable in BCBSTX's Texas network — this is BSW's ultimate structural leverage.",
      "BCBSTX's 25% market share (8 million members, more than double UHC) means BSW cannot afford to lose BCBS patients either — genuine mutual dependence.",
      "The HealthSelect/ERS angle (500,000+ state employees) elevated this from business dispute to political issue — even without formal government intervention.",
      "BCBSTX's 'significantly increase what we pay them' quote was the most widely cited framing in media — the payor frame got more traction than in most disputes.",
      "BSW's 2023 financial losses ($1.2B revenue vs $1.41B expenses) supported the 'unsustainable reimbursement' narrative, but FY2024 results showing $15.5B revenue and $2B net profit complicated this argument.",
    ],
    marcomm: [
      "<strong>Mutual assured destruction.</strong> Unlike disputes where one party has clear leverage, BSW and BCBSTX are so intertwined in Texas that a split would be catastrophic for both. This created a more balanced narrative environment than typical provider-payor fights.",
      "<strong>BCBSTX's payor frame landed better than usual.</strong> The 'significantly increase what we pay' quote was sticky and widely cited. BSW was more often positioned as the party 'threatening to leave' rather than the party 'being underpaid.' This is a notable payor communications win.",
      "<strong>The HealthSelect dimension was the true pressure point.</strong> When a state's employee benefits administrator has to issue public advisories about potential network loss, the dispute has reached political gravity. This is what likely drove resolution — not media coverage.",
      "<strong>The Ascension precedent undermined urgency.</strong> Multiple outlets noted BCBSTX resolved a similar dispute with Ascension at the 11th hour in 2023. This 'boy who cried wolf' pattern reduced media and public alarm, making the brinkmanship feel like negotiation theater.",
    ],
  },
  channelTakeaways: {
    media: [
      "WFAA (Dallas ABC) provided the most sustained and highest-reach TV coverage — multiple segments across both deadlines.",
      "NPR syndication (KUT/KERA/TPR/KETR) delivered the most analytically rigorous coverage and reached the policy-attentive audience statewide.",
      "D Magazine broke both the initial threat and the resolution — became the authoritative DFW business press source.",
      "Central Texas TV (KWTX, KCENTV, KXXV) coverage was intense — BSW's Hillcrest and other facilities are dominant in these markets.",
      "Axios Dallas was notably more payor-framed ('could drop BSW') — an unusual win for BCBSTX in business press.",
      "KCENTV's two VERIFY segments (June and September) indicate sustained patient confusion throughout the dispute.",
    ],
    social: [
      "Social media activity was primarily patient anxiety, not organized advocacy — no viral moments or celebrity involvement.",
      "Online posts were alarming enough to trigger TV fact-check segments (KCENTV VERIFY, KXXV citing 'posts online').",
      "Facebook groups in Central Texas (Waco, Temple, Bryan-College Station) showed the most concentrated anxiety — BSW is dominant or sole system in these markets.",
      "Reddit discussion was more balanced than Facebook, with some users defending BCBSTX's position on rate increases.",
    ],
    stakeholder: [
      "ERS (Employees Retirement System) was the most significant stakeholder — its public advisory elevated the dispute to state government concern.",
      "HealthSelect coverage for 500,000+ state employees and retirees created implicit political pressure without requiring explicit elected official intervention.",
      "The Ascension/BCBSTX 2023 precedent was widely noted and reduced perceived credibility of the termination threat.",
      "Simultaneous Texas crises (Cook Children's Medicaid loss, Steward bankruptcy) amplified BSW/BCBS as part of a systemic access problem.",
      "TDI's new network adequacy rules (HB 3359) created structural regulatory pressure on BCBSTX — a BSW exit would trigger formal compliance issues.",
      "Notable silence from Governor Abbott and state legislature — no public intervention despite scale of potential disruption.",
    ],
    employer: [
      "BCBSTX's member notification letters reached HR departments across Texas — the employer channel was BCBSTX's most effective pressure tool against BSW.",
      "State agency HR departments (UT System, Texas A&M, state agencies) had to prepare employees for potential BSW network loss — highest-stakes employer channel.",
      "Benefits consultants flagged the dispute for self-funded employer plan sponsors, raising questions about BCBSTX network stability.",
      "BSW's counter-notifications to patients created a dueling-communication dynamic that confused employer plan participants.",
    ],
  },
  arguments: {
    payor: [
      { phase: "Early (May–Jun 2024)", points: [
        "BCBSTX framed BSW as the party threatening to terminate unless BCBS would '<strong>significantly increase what we pay them</strong>'",
        "Positioned BCBSTX as the one being left — preferred framing was 'BSW could terminate' rather than 'BCBS refusing to pay'",
        "Emphasized BCBSTX's <strong>~25% market share and ~8 million members</strong> to signal leverage",
      ] },
      { phase: "Mid-Dispute (Jun–Sep 2024)", points: [
        "Sent member notification letters reaching HR departments across Texas — the <strong>employer channel was BCBSTX's most effective pressure tool</strong>",
        "Axios Dallas adopted BCBSTX framing: 'BCBS could drop BSW' — positioning BSW as the party being removed",
        "Leveraged HealthSelect coverage for <strong>500,000+ state employees and retirees</strong> to create implicit political pressure",
      ] },
      { phase: "Resolution (Sep 2024)", points: [
        "Agreed to three-month extension (June 27) then long-term agreement (September 27)",
        "Resolution avoided triggering <strong>TDI network adequacy rules (HB 3359)</strong> which would have created formal compliance issues for BCBSTX",
      ] },
    ],
    provider: [
      { phase: "Early (May 2024)", points: [
        "Notified BCBSTX it would terminate unless agreements were modified — framed BCBSTX as <strong>underpaying</strong>",
        "Cited financial pressure: BSW revenue <strong>$1.2 billion in 2023 exceeded by $1.41 billion in expenses</strong>",
        "Positioned as Texas's <strong>largest nonprofit system</strong> (51 hospitals, 800+ care sites, 7,300 physicians) fighting for sustainable reimbursement",
      ] },
      { phase: "Mid-Dispute (Jun–Sep 2024)", points: [
        "Patient advocate Belynda Montgomery: 'months of backlog and misinformation' — <strong>patient harm narrative inherently blamed the payor</strong>",
        "Leveraged rural Texas presence where BSW is often the only major system — network exit would create <strong>healthcare deserts</strong>",
        "Counter-notifications to patients created dueling communication dynamic; KCEN VERIFY segments confirmed high public confusion",
      ] },
      { phase: "Resolution (Sep 2024)", points: [
        "Secured three-month extension (June 27) buying time for substantive negotiations",
        "Long-term agreement reached September 27 — dispute lasted nearly 5 months but <strong>no actual network disruption occurred</strong>",
      ] },
    ],
  },
  timeline: [
    { date: "2024-05-07", type: "newsBreak", label: "News breaks publicly" },
    { date: "2024-07-01", type: "termination", label: "Contract set to terminate" },
    { date: "2024-06-27", type: "extension", label: "Temporary extension" },
    { date: "2024-09-27", type: "agreement", label: "Agreement reached" },
  ],
};
