// Dignity Health vs Blue Cross Blue Shield of Arizona — PR War Room Config
// Dispute period: Feb 1 – Mar 15, 2024 (out-of-network). Resolved mid-March 2024.
// Prior Yavapai dispute: Feb 2023 – Apr 2023. Resolved April 1, 2023.

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2024-02-03",
    source: "AZ Family / KPHO",
    url: "https://www.azfamily.com/2024/02/03/dignity-health-is-no-longer-in-network-certain-arizona-blue-cross-blue-shield-members/",
    sourceType: "tv",
    channel: "media",
    headline: "Dignity Health is no longer in-network for certain Arizona Blue Cross Blue Shield members",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "First major TV report on the dispute. AZ Family/KPHO breaks the story for Phoenix metro. 'Tens of thousands' of BCBSAZ members in Maricopa and Pinal counties affected. 8 hospitals including St. Joseph's (home of Barrow Neurological Institute), Chandler Regional, Mercy Gilbert. HMO, PPO, FARE, workers' comp, and Medicare supplemental plans affected.",
  },
  {
    id: 2,
    date: "2024-02-07",
    source: "AZ Family / KPHO",
    url: "https://www.azfamily.com/2024/02/07/patients-scramble-find-new-providers-after-dignity-health-stops-accepting-bcbsaz/",
    sourceType: "tv",
    channel: "media",
    headline: "Patients scramble to find new providers after Dignity Health stops accepting BCBSAZ",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: true,
    blameDirection: "dignity",
    reachEstimate: "high",
    notes: "Follow-up coverage. Patients scrambling for alternatives. BCBSAZ framing gains traction: Dignity demanded 37% more on top of $49M increase already offered. Patients facing delays in prescriptions, testing, and provider appointments. Ripple effect on patient care highlighted.",
  },
  {
    id: 3,
    date: "2024-02-07",
    source: "12 News / KPNX",
    url: "https://www.12news.com/article/news/health/dignity-health-no-longer-accepts-blue-cross-blue-shield/75-b5364f99-6550-4ce1-a8a7-8c8537a60155",
    sourceType: "tv",
    channel: "media",
    headline: "Major AZ insurance provider no longer accepted at Dignity Health — patients left searching",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "12 News provides balanced coverage. Patients featured searching for new providers mid-treatment. Both sides' positions presented. BCBSAZ: offered $49M increase. Dignity: rates need to keep pace with costs. BCBSAZ is Arizona's largest health insurer.",
  },
  {
    id: 4,
    date: "2024-02-07",
    source: "ABC15 Arizona",
    url: "https://www.abc15.com/news/local-news/thousands-of-bcbsaz-patients-out-of-network-at-dignity-health-aetna-patients-also-at-risk",
    sourceType: "tv",
    channel: "media",
    headline: "Thousands of BCBSAZ patients out of network at Dignity Health, Aetna patients also at risk",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "ABC15 reveals dual threat: BCBSAZ already out-of-network AND Aetna contract at risk (deadline March 31). Tens of thousands affected for outpatient services like cancer care and imaging. Hospital admissions directed elsewhere. Dignity fighting on two fronts simultaneously.",
  },
  {
    id: 5,
    date: "2024-02-08",
    source: "KTAR News 92.3",
    url: "https://ktar.com/arizona-news/dignity-health-reaches-in-network-coverage-deal-with-blue-cross-blue-shield-of-arizona/5567688/",
    sourceType: "radio",
    channel: "media",
    headline: "KTAR: Dignity Health, Arizona Blue contract dispute impacts thousands of Valley patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "KTAR is Arizona's dominant news/talk radio station. Broad reach across Maricopa County commuters. Balanced framing with both sides' positions. Radio reaches a demographic that may not follow online news.",
  },
  {
    id: 6,
    date: "2024-02-06",
    source: "KNAU (Flagstaff NPR)",
    url: "https://www.knau.org/knau-and-arizona-news/2024-02-06/yavapai-regional-medical-center-safe-from-blue-cross-coverage-changes",
    sourceType: "radio",
    channel: "media",
    headline: "KNAU: Yavapai Regional Medical Center safe from Blue Cross coverage changes — Maricopa, Pinal not so lucky",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Flagstaff NPR affiliate. Clarifies YRMC was NOT included in the Feb 2024 split (YRMC had separately resolved its dispute in April 2023). Northern Arizona audience. Reassurance for Yavapai but raises awareness of Phoenix metro disruption.",
  },
  {
    id: 7,
    date: "2024-02-09",
    source: "GCMAZ / KAFF News",
    sourceType: "radio",
    channel: "media",
    headline: "KAFF: Dignity Health, Blue Cross Blue Shield of Arizona talks break down — insurance holders go to out-of-network coverage",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Flagstaff/Northern AZ radio. GCMAZ covers rural Arizona. Notes insurance holders immediately shifted to out-of-network coverage. Rural audiences concerned about precedent after YRMC's 2023 dispute.",
  },
  {
    id: 8,
    date: "2024-02-10",
    source: "Hoodline",
    url: "https://hoodline.com/2024/02/dignity-health-ends-in-network-services-with-blue-cross-blue-shield-in-arizona-patients-brace-for-rising-costs/",
    sourceType: "news",
    channel: "media",
    headline: "Dignity Health ends in-network services with Blue Cross Blue Shield in Arizona — patients brace for rising costs",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Online news aggregator covering Phoenix metro. 'Brace for rising costs' framing creates financial anxiety. Summarizes dispute basics: 8 hospitals, tens of thousands affected, both sides' financial claims.",
  },
  {
    id: 9,
    date: "2024-02-12",
    source: "Becker's Payer Issues",
    url: "https://www.beckerspayer.com/contracting/bcbs-arizona-dignity-health-split/",
    sourceType: "news",
    channel: "media",
    headline: "BCBS Arizona, Dignity Health split — 8 hospitals go out-of-network over rates",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National trade press picks up the story. Notes BCBSAZ offered $49M increase; Dignity wants 37% more on top. Hospital executive audience. Dignity's $153M in profits (AZ DHS data) mentioned. Becker's Payer Issues focuses on insurer perspective.",
  },
  {
    id: 10,
    date: "2024-02-14",
    source: "Hoodline",
    sourceType: "news",
    channel: "media",
    headline: "Patients scramble for new providers as Dignity Health ends BCBSAZ in-network coverage in Arizona",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Second Hoodline piece. Two weeks into dispute with no resolution in sight. Patient scramble angle emphasized. Ongoing disruption framing.",
  },
  {
    id: 11,
    date: "2024-02-15",
    source: "ABC15 Arizona",
    url: "https://www.abc15.com/news/local-news/thousands-of-bcbsaz-patients-out-of-network-at-dignity-health-aetna-patients-also-at-risk",
    sourceType: "tv",
    channel: "media",
    headline: "ABC15 Investigates: Dignity Health profits vs. patient access — $153M profit highlighted",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "high",
    notes: "Investigative angle. AZ DHS data showing Dignity made $153M in profits undermines Dignity's claims of needing higher rates. BCBSAZ sends ~$100M/month in billed charges to Dignity. Most damaging single media segment for the provider.",
  },
  {
    id: 12,
    date: "2024-02-15",
    source: "Center for Neurology and Spine blog",
    url: "https://www.centerforneurologyandspine.com/post/dignity-health-dignityhealth-in-phoenix-no-longer-accepts-blue-shield-of-arizona-bcbsaz",
    sourceType: "news",
    channel: "media",
    headline: "Barrow Neurological Institute access at risk for BCBS Arizona patients — neurology community alert",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Specialty trade/blog. Barrow Neurological Institute is housed within St. Joseph's Hospital (Dignity). Loss of in-network access to Barrow is uniquely high-stakes for neuro patients. Nationally ranked center; niche but high-acuity audience.",
  },
  {
    id: 13,
    date: "2024-02-20",
    source: "Becker's Payer Issues",
    url: "https://www.beckerspayer.com/contracting/bcbs-arizona-dignity-health-hospital-split-after-contract-impasse/",
    sourceType: "news",
    channel: "media",
    headline: "BCBS Arizona, Dignity Health hospital split after contract impasse — congressional delegation intervenes",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Second Becker's piece. Notes bipartisan congressional intervention from Kelly, Sinema, and Crane. Federal political pressure is unusual for state-level dispute. Trade audience takes note of political escalation.",
  },
  {
    id: 14,
    date: "2024-02-22",
    source: "ABC15 Arizona",
    sourceType: "tv",
    channel: "media",
    headline: "Arizona lawmakers call for end to Dignity Health–BCBS Arizona dispute as patients suffer",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: true,
    blameDirection: "dignity",
    reachEstimate: "high",
    notes: "Lawmaker pressure segment. AZ state lawmakers lean pro-BCBSAZ. Patient suffering framing combined with political pressure on Dignity. Three weeks into dispute with no resolution.",
  },
  {
    id: 15,
    date: "2024-02-09",
    source: "Signals AZ",
    url: "https://www.signalsaz.com/articles/dignity-health-blue-cross-blue-shield-comment-on-ending-partnership/",
    sourceType: "news",
    channel: "media",
    headline: "Dignity Health, Blue Cross Blue Shield comment on ending partnership — Yavapai angle",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Yavapai County local outlet. Notes prior YRMC dispute (Feb 2023 – Apr 2023) as context for current Maricopa/Pinal dispute. ~20% of 58K BCBS beneficiaries in Yavapai County were impacted in the earlier dispute. Community still remembers.",
  },
  {
    id: 16,
    date: "2024-02-20",
    source: "Signals AZ",
    sourceType: "news",
    channel: "media",
    headline: "YRMC labeled '4th highest-cost hospital in state' — rates twice average Phoenix hospital",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "Key data point for BCBSAZ's case from the earlier YRMC dispute. YRMC rates allegedly twice the average Phoenix hospital, three times the Tucson hospital average. '4th highest-cost hospital in state' is damaging for Dignity/YRMC. Context still relevant to ongoing Phoenix dispute.",
  },
  {
    id: 17,
    date: "2024-03-01",
    source: "ABC15 Arizona",
    url: "https://www.abc15.com/news/local-news/bcbs-of-arizona-members-back-in-network-at-dignity-health-after-agreement",
    sourceType: "tv",
    channel: "media",
    headline: "One month in: Dignity Health–BCBS Arizona patients still out-of-network with no deal",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Month mark coverage. Duration framing increases urgency. Patient stories of ongoing disruption and difficulty finding alternative care. One month of actual out-of-network status — unlike many disputes that resolve before the deadline.",
  },
  {
    id: 18,
    date: "2024-03-05",
    source: "Signals AZ",
    sourceType: "news",
    channel: "media",
    headline: "Signals AZ: Dignity–BCBS dispute enters second month — community patience wears thin",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Third Signals AZ piece. Community frustration mounting. Duration fatigue beginning to work against Dignity as the party perceived as holding out against a reasonable offer.",
  },
  {
    id: 19,
    date: "2024-03-12",
    source: "ABC15 Arizona",
    url: "https://www.abc15.com/news/local-news/bcbs-of-arizona-members-back-in-network-at-dignity-health-after-agreement",
    sourceType: "tv",
    channel: "media",
    headline: "Dignity Health also warns Aetna patients may lose access March 31 — Arizona patients face dual threat",
    frameAdoption: "balanced",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "high",
    notes: "CRITICAL PERCEPTION SHIFT. Dignity fighting BCBSAZ AND Aetna simultaneously. CA, AZ, NV providers all at risk with Aetna by March 31. Pattern of multi-payor disputes undermines Dignity's 'BCBSAZ is the unreasonable one' narrative. Media begins framing Dignity as the common denominator.",
  },
  {
    id: 20,
    date: "2024-03-15",
    source: "12 News / KPNX",
    url: "https://www.12news.com/article/news/health/dignity-health-accepts-az-blue-offer-returns-to-in-network-march-2024/75-643f79eb-966b-4dc4-a328-095feff37efe",
    sourceType: "tv",
    channel: "media",
    headline: "Dignity Health accepts AZ Blue offer, returns to in-network — dispute over after 6 weeks",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "high",
    notes: "CRITICAL RESOLUTION FRAMING. '12 News: Dignity Health accepts AZ Blue offer' — 'accepts' language positions Dignity as capitulating. BCBSAZ confirmed Dignity accepted their final offer. In-network effective March 15, announced March 18.",
  },
  {
    id: 21,
    date: "2024-03-21",
    source: "AZ Family / KPHO",
    url: "https://www.azfamily.com/2024/03/21/deal-reached-between-dignity-health-arizona-blue-cross-blue-shield/",
    sourceType: "tv",
    channel: "media",
    headline: "Deal reached between Dignity Health, Arizona Blue Cross Blue Shield — patients can return to hospitals",
    frameAdoption: "bcbsaz",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "high",
    notes: "Resolution coverage from the outlet that broke the story. 'Patients can return' implies Dignity had taken them away. AZ Family frames resolution as Dignity accepting BCBSAZ's terms. Video segment aired March 22.",
  },
  {
    id: 22,
    date: "2024-03-21",
    source: "AZ Family / KPHO (video)",
    url: "https://www.azfamily.com/video/2024/03/22/arizona-blue-cross-blue-shield-reaches-agreement-with-dignity-health/",
    sourceType: "tv",
    channel: "media",
    headline: "Arizona Blue Cross Blue Shield reaches agreement with Dignity Health — TV segment",
    frameAdoption: "bcbsaz",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "high",
    notes: "Dedicated video segment on resolution. BCBSAZ positioned as the party that held firm. Broadcast reach in Phoenix metro where dispute was most felt.",
  },
  {
    id: 23,
    date: "2024-03-18",
    source: "Becker's Payer Issues",
    url: "https://www.beckerspayer.com/contracting/dignity-health-hospital-back-in-network-with-bcbs-arizona-after-split/",
    sourceType: "news",
    channel: "media",
    headline: "Dignity Health hospital back in network with BCBS Arizona after split — 'accepted final offer'",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "Resolution coverage in trade press. 'Accepted AZ Blue's final offer' framing strongly favors BCBSAZ — implies Dignity capitulated. Trade press audience of hospital executives notes Dignity blinked. Third Becker's piece on this dispute.",
  },
  {
    id: 24,
    date: "2024-03-21",
    source: "KTAR News 92.3",
    url: "https://ktar.com/arizona-news/dignity-health-reaches-in-network-coverage-deal-with-blue-cross-blue-shield-of-arizona/5567688/",
    sourceType: "radio",
    channel: "media",
    headline: "Blue Cross Blue Shield of Arizona, Dignity Health agree on contract — KTAR breaks resolution for radio audience",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "KTAR resolution coverage. Balanced framing for radio audience. Effective March 15, BCBS members again have in-network access to Dignity Health services in Maricopa and Pinal counties.",
  },
  {
    id: 25,
    date: "2024-03-18",
    source: "ABC15 Arizona",
    url: "https://www.abc15.com/news/local-news/bcbs-of-arizona-members-back-in-network-at-dignity-health-after-agreement",
    sourceType: "tv",
    channel: "media",
    headline: "BCBS of Arizona members back in-network at Dignity Health after agreement — 6-week ordeal ends",
    frameAdoption: "bcbsaz",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "high",
    notes: "ABC15 resolution coverage. '6-week ordeal' duration framing emphasizes patient disruption. Retroactive to March 15 — patients who sought care at Dignity between March 15-18 covered.",
  },
  {
    id: 26,
    date: "2024-02-21",
    source: "Copperstate News",
    url: "https://copperstate.news/prescott-news/item/2066-yavapai-lawmakers-urge-yrmc-to-reconsider-decision-dropping-bcbs-of-az",
    sourceType: "news",
    channel: "media",
    headline: "Arizona lawmakers press Dignity Health and BCBS Arizona to resolve hospital dispute",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "State political coverage. AZ lawmakers lean toward BCBSAZ position. Lawmaker pressure on Dignity to accept terms. Political environment unfavorable to Dignity throughout the dispute.",
  },
  {
    id: 27,
    date: "2024-02-20",
    source: "GCMAZ / KAFF News",
    sourceType: "radio",
    channel: "media",
    headline: "KAFF: Congressman Eli Crane, and both Arizona Senators, step in to encourage more negotiations",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Flagstaff radio covers congressional intervention. Rural audience concerned about pattern of Dignity–BCBSAZ disputes (YRMC in 2023, Maricopa/Pinal in 2024). Bipartisan federal pressure escalation.",
  },
  {
    id: 28,
    date: "2024-03-18",
    source: "InsuranceNewsNet",
    url: "https://insurancenewsnet.com/oarticle/sinema-applauds-dignity-health-and-blue-cross-blue-shield-for-reaching-deal-on-health-insurance-coverage-for-patients",
    sourceType: "news",
    channel: "media",
    headline: "Sinema applauds Dignity Health and Blue Cross Blue Shield for reaching deal on health insurance coverage for patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Insurance industry trade outlet. Sinema statement syndicated to insurance professional audience. Frames resolution as victory for patient access. Insurance broker/agent readership.",
  },
  {
    id: 29,
    date: "2024-02-12",
    source: "12 News / KPNX (Yavapai)",
    url: "https://www.12news.com/article/news/local/arizona/thousands-waiting-on-deal-between-blue-cross-blue-shield-arizona-dignity-health-in-yavapai-county/75-60cf3baa-a048-49c3-af22-9dc5773e661b",
    sourceType: "tv",
    channel: "media",
    headline: "Major insurance provider may no longer be accepted at Arizona hospital — thousands waiting on YRMC deal",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "12 News covers Yavapai County angle amid broader dispute. Notes thousands of BCBS beneficiaries in Yavapai County still monitoring situation after 2023 dispute. YRMC is the only major hospital for the Prescott/Yavapai region.",
  },
  {
    id: 30,
    date: "2024-02-08",
    source: "Arizona University Center for Rural Health",
    url: "https://crh.arizona.edu/news/always-it-comes-down-money-major-insurance-provider-no-longer-accepted-arizona-hospital",
    sourceType: "news",
    channel: "media",
    headline: "UA Center for Rural Health highlights YRMC dispute as case study in rural access gaps",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Academic/policy outlet. Frames dispute through rural health access lens. YRMC's near-monopoly position in Yavapai County makes network disputes existential for rural communities. Institutional credibility for policy audience.",
  },
  // === GOVERNMENT / POLITICAL ENTRIES ===
  {
    id: 31,
    date: "2024-02-16",
    source: "Sen. Kyrsten Sinema (I-AZ)",
    url: "https://www.sinema.senate.gov/sinema-kelly-applaud-dignity-health-and-blue-cross-blue-shield-arizona-for-their-agreement-to-protect-patients-access-to-health-care/",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Sen. Sinema leads bipartisan letter with Kelly, Crane urging Dignity and BCBS Arizona to resolve dispute immediately",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Federal intervention. Sinema leads bipartisan letter with Kelly (D) and Crane (R). Unusual for federal lawmakers to weigh in on state-level provider-payor dispute. Letter urges both sides to continue negotiations and maintain coverage for impacted enrollees. Signals political severity.",
  },
  {
    id: 32,
    date: "2024-02-16",
    source: "Sen. Mark Kelly (D-AZ)",
    url: "https://www.kelly.senate.gov/newsroom/press-releases/kelly-sinema-applaud-dignity-health-and-blue-cross-blue-shield-arizona-for-their-agreement-to-protect-patients-access-to-health-care/",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Sen. Kelly co-signs bipartisan congressional letter on Dignity–BCBS Arizona dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Democratic senator joining bipartisan effort. Kelly's involvement adds cross-party credibility. Neither party willing to publicly side with Dignity.",
  },
  {
    id: 33,
    date: "2024-02-16",
    source: "Rep. Eli Crane (R-AZ)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Rep. Crane joins Kelly, Sinema in pressing for resolution — bipartisan concern over rural and metro patient access",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Republican congressman. Bipartisan nature of intervention (D, I, R) is significant — neither party willing to publicly defend Dignity. Crane represents rural districts including Yavapai where hospital alternatives are limited.",
  },
  {
    id: 34,
    date: "2024-03-18",
    source: "Sen. Kelly (resolution statement)",
    url: "https://www.kelly.senate.gov/newsroom/press-releases/kelly-sinema-applaud-dignity-health-and-blue-cross-blue-shield-arizona-for-their-agreement-to-protect-patients-access-to-health-care/",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Sen. Kelly applauds resolution — 'agreement to protect patients' access to health care'",
    frameAdoption: "bcbsaz",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "Resolution statement. Kelly frames outcome as protecting patient access. Congressional involvement framed as catalyst for resolution. Implicit credit to BCBSAZ for holding firm on reasonable offer.",
  },
  {
    id: 35,
    date: "2024-03-18",
    source: "Sen. Sinema (resolution statement)",
    url: "https://www.sinema.senate.gov/sinema-applauds-dignity-health-and-blue-cross-blue-shield-reaching-deal-health-insurance-coverage/",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Sen. Sinema: 'Arizonans should never be caught in the middle of corporate disputes'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution statement. 'Corporate disputes' framing assigns systemic blame. Balanced but implicitly critical of Dignity for prolonging dispute for 6 weeks.",
  },
  {
    id: 36,
    date: "2024-03-18",
    source: "Rep. Crane (resolution statement)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Rep. Crane: pleased dispute resolved, reiterates need for transparency in hospital pricing",
    frameAdoption: "bcbsaz",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "Resolution statement. 'Transparency in hospital pricing' framing aligns with BCBSAZ's narrative about Dignity's high costs and $153M profits. Republican congressman effectively validates insurer position.",
  },
  {
    id: 37,
    date: "2024-02-22",
    source: "Yavapai County lawmakers",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Yavapai County state legislators demand resolution — warn YRMC is only major hospital for entire region",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "State-level political intervention for YRMC context. YRMC's monopoly position in Yavapai County makes any Dignity dispute uniquely harmful to rural patients. Lawmakers note limited alternatives in Prescott, Chino Valley, Paulden area.",
  },
  // === PATIENT / ADVOCATE ENTRIES ===
  {
    id: 38,
    date: "2024-02-12",
    source: "Laura Nero BSN RN (patient advocate)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Laura Nero BSN RN: 'Any delay in treatment has a significant impact on patient outcomes'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Patient advocate (BSN RN). Professional credibility adds weight to treatment disruption claims. Clinical framing of dispute consequences. Used by AZ Family and ABC15 as expert source. Highlights delays in prescriptions, testing, and scheduling.",
  },
  {
    id: 39,
    date: "2024-02-20",
    source: "Dr. Anthony Torres, CEO, YRMC",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "YRMC CEO Dr. Torres: rate requests 'single digits, below medical inflation rate' — disputes BCBSAZ cost claims",
    frameAdoption: "dignity",
    sentiment: "negative_bcbsaz",
    patientStory: false,
    blameDirection: "bcbsaz",
    reachEstimate: "medium",
    notes: "YRMC physician-executive pushback on BCBSAZ claims. Asserts rate increase requests were 'single digits, below medical inflation rate' — directly contradicts BCBSAZ narrative. Notes higher costs due to difficulty recruiting and retaining physicians at rural hospital. Counter to '4th highest-cost hospital' label.",
  },
  {
    id: 40,
    date: "2024-02-28",
    source: "Pam Kehaly, President & CEO, BCBSAZ",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "BCBSAZ CEO Kehaly: Dignity's costs are 'driving up the cost of healthcare at patients' expense'",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "high",
    notes: "CEO-level public statement. Kehaly authored 'Setting the Record Straight' viewpoint on azblue.com. Key claims: YRMC is 4th highest-cost hospital in state, rates twice Phoenix average, three times Tucson average. BCBSAZ already pays $124M annually to YRMC. Offered millions more but Dignity rejected 'meeting halfway.' CEO credibility carries weight with employer and policy audiences.",
  },
  {
    id: 41,
    date: "2024-02-10",
    source: "BCBSAZ continuity of care notice",
    sourceType: "news",
    channel: "stakeholder",
    headline: "BCBSAZ offers 'Continuity of Care' option — patients can request to keep Dignity doctor at in-network price",
    frameAdoption: "bcbsaz",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "BCBSAZ positions itself as protecting patients despite Dignity's exit. Continuity of Care requires patients to show ongoing treatment relationship and medical records. Hospital stays in-process and ongoing treatments still covered in-network. Proactive patient protection framing benefits BCBSAZ.",
  },
  {
    id: 42,
    date: "2024-03-12",
    source: "Dignity Health Aetna dispute (parallel)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Dignity Health warns Aetna contract may end March 31 — CA, AZ, NV providers all at risk simultaneously",
    frameAdoption: "balanced",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "high",
    notes: "PATTERN EVIDENCE. Dignity simultaneously fighting BCBSAZ AND Aetna across three states. Aetna commercial HMO, POS, PPO, Medicare Advantage, and Whole Health agreements all at risk. Multi-payor, multi-state disputes undermine Dignity's claim that any single insurer is unreasonable. Dignity is the common denominator.",
  },
  {
    id: 43,
    date: "2023-02-09",
    source: "Becker's Payer Issues (YRMC precedent)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "YRMC goes out-of-network with BCBS Arizona Feb 2023 — precedent dispute affects 11,500 patients in Yavapai County",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "PRIOR DISPUTE. YRMC went out of network Feb 9, 2023 after failing to agree on reimbursement rates. ~11,500 BCBSAZ beneficiaries in Prescott, Chino Valley, Paulden affected. Some forced to drive hours for non-emergency care. Resolved April 1, 2023 with 3-year deal. Sets pattern for 2024 Maricopa/Pinal dispute.",
  },
  {
    id: 44,
    date: "2023-05-01",
    source: "KNAU (YRMC resolution 2023)",
    url: "https://www.knau.org/knau-and-arizona-news/2023-05-01/dignity-health-and-blue-cross-blue-shield-reach-in-network-contract-agreement/",
    sourceType: "radio",
    channel: "stakeholder",
    headline: "KNAU: Dignity Health and Blue Cross Blue Shield reach in-network contract agreement for YRMC — 3-year deal",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "YRMC 2023 resolution coverage. 3-year deal effective retroactively to April 1, 2023. Sinema separately applauded this resolution. Pattern: YRMC dispute resolved after ~2 months. Maricopa/Pinal dispute would follow same ~6-week timeline.",
  },
  // === DIGNITY OWNED MEDIA ===
  {
    id: 45,
    date: "2024-02-01",
    source: "Dignity Health Press Center (statement)",
    url: "https://www.dignityhealth.org/arizona/about-us/press-center/press-releases/statement-regarding-bcbs-negotiations",
    sourceType: "owned",
    channel: "media",
    headline: "Dignity Health: 'We have been working in good faith — BCBSAZ unwilling to accept fair contract terms'",
    frameAdoption: "dignity",
    sentiment: "negative_bcbsaz",
    patientStory: false,
    blameDirection: "bcbsaz",
    reachEstimate: "medium",
    notes: "Initial Dignity statement. Claims BCBSAZ rejected 'several proposals' and refused a two-week extension offer 'without providing a counter offer.' Also claims BCBSAZ not honoring existing contract and 'refusing to pay millions of dollars in outstanding claims.' Aggressive counter-narrative from day one.",
  },
  {
    id: 46,
    date: "2024-02-01",
    source: "Dignity Health Press Center (patient FAQ)",
    url: "https://www.dignityhealth.org/arizona/about-us/press-center/press-releases/statement-regarding-bcbs-negotiations",
    sourceType: "owned",
    channel: "media",
    headline: "Dignity Health publishes patient FAQ: emergency care still covered, ongoing treatments protected",
    frameAdoption: "dignity",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "bcbsaz",
    reachEstimate: "medium",
    notes: "Patient-facing communication. Reassures patients that ER visits still covered at in-network rates and current hospital stays/treatments continue. Directs patients to contact BCBSAZ for Continuity of Care requests. Organized comms strategy but defensive posture.",
  },
  {
    id: 47,
    date: "2024-02-15",
    source: "Dignity Health Press Center (YRMC record straight)",
    url: "https://www.dignityhealth.org/arizona/locations/yavapairegional/about-us/press-center/press-releases/yrmc-negotiations-with-blue-cross-blue-shield-of-arizona",
    sourceType: "owned",
    channel: "media",
    headline: "Dignity Health: setting the record straight on YRMC costs — disputes '4th highest-cost' label",
    frameAdoption: "dignity",
    sentiment: "negative_bcbsaz",
    patientStory: false,
    blameDirection: "bcbsaz",
    reachEstimate: "medium",
    notes: "Specific YRMC rebuttal. Dignity challenges BCBSAZ's characterization of YRMC as 4th highest-cost hospital. Argues cost comparisons are misleading without accounting for patient acuity and rural market dynamics. Dr. Torres: recruitment costs higher at rural hospitals.",
  },
  {
    id: 48,
    date: "2024-03-13",
    source: "Dignity Health Press Center (extension offer)",
    sourceType: "owned",
    channel: "media",
    headline: "Dignity Health offers to extend negotiations — signals willingness to deal",
    frameAdoption: "dignity",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Last-stage negotiation signal. Extension offer suggests Dignity attempting to appear willing to negotiate. But by mid-March with 6 weeks of disruption, Dignity's leverage is weakening and pressure is mounting.",
  },
  {
    id: 49,
    date: "2024-03-15",
    source: "Dignity Health Press Center (resolution)",
    url: "https://www.dignityhealth.org/arizona/about-us/press-center/press-releases/blue-cross-blue-shield-of-arizona-contract-update",
    sourceType: "owned",
    channel: "media",
    headline: "Dignity Health: 'AZ Blue members once again have in-network access to Dignity Health services'",
    frameAdoption: "dignity",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution announcement. Dignity frames as mutual agreement: 'in-network access' restored. But third-party reporting consistently frames it as Dignity 'accepting AZ Blue's final offer' — undercutting Dignity's version of events.",
  },
  // === BCBSAZ OWNED MEDIA ===
  {
    id: 50,
    date: "2024-02-01",
    source: "BCBSAZ — azbluefacts.com/dignity",
    url: "https://www.azbluefacts.com/dignity",
    sourceType: "owned",
    channel: "media",
    headline: "BCBSAZ launches azbluefacts.com/dignity microsite — central hub for insurer's narrative",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "STRATEGIC OWNED MEDIA. Dedicated microsite is sophisticated PR move. Key claims: offered $49M increase, Dignity demanded 37% more on top. Dignity made $153M in profits. BCBSAZ sends ~$100M/month in billed charges. Data-forward approach to frame Dignity as greedy. Hosted at consumer-friendly URL.",
  },
  {
    id: 51,
    date: "2024-02-05",
    source: "AZ Blue News Center",
    sourceType: "owned",
    channel: "media",
    headline: "AZ Blue News Center: 'We offered Dignity Health a $49 million increase — they want 37% more'",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "BCBSAZ's primary narrative vehicle. $49M offer vs. 37% demand is the stickiest BCBSAZ talking point. Paired with Dignity's $153M profit figure from AZ DHS data. Effective cost-framing that was adopted by multiple media outlets.",
  },
  {
    id: 52,
    date: "2024-02-28",
    source: "AZ Blue News Center (Setting the Record Straight)",
    sourceType: "owned",
    channel: "media",
    headline: "BCBSAZ CEO Kehaly pens 'Setting the Record Straight' — data-driven counter to Dignity claims",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "CEO-authored viewpoint published on azblue.com and newscenter.azblue.com. Sophisticated PR asset. Includes specific cost comparisons, reimbursement data, and characterization of Dignity as changed since affiliating with CommonSpirit Health. Notes 'decades-long productive relationship' changed after Dignity's corporate evolution.",
  },
  {
    id: 53,
    date: "2024-03-15",
    source: "AZ Blue News Center (resolution)",
    sourceType: "owned",
    channel: "media",
    headline: "BCBSAZ: 'Dignity Health has accepted Arizona Blue's final offer' — insurer claims victory",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "CRITICAL RESOLUTION FRAMING. 'Accepted AZ Blue's final offer' positions BCBSAZ as winner. This exact framing was adopted by Becker's, 12 News, and other outlets. Dignity's 'reached an agreement' language was largely ignored by third-party media. BCBSAZ won the resolution narrative decisively.",
  },
  {
    id: 54,
    date: "2024-03-18",
    source: "AZ Blue News Center (renewal announcement)",
    sourceType: "owned",
    channel: "media",
    headline: "Blue Cross Blue Shield of Arizona and Dignity Health renew network agreement — formal announcement",
    frameAdoption: "bcbsaz",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Formal renewal announcement. More conciliatory tone than initial 'accepted final offer' statement. Notes agreement details not disclosed. BCBSAZ positions itself as having protected members throughout the dispute.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 55,
    date: "2024-02-05",
    source: "Maricopa County (employer communication)",
    sourceType: "news",
    channel: "employer",
    headline: "Maricopa County sends letters to employees: Dignity Health hospitals now out-of-network for county BCBS plans",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "high",
    notes: "CRITICAL EMPLOYER SIGNAL. Maricopa County is one of the largest employers in the region. County employees receiving formal letters about loss of Dignity access creates massive grassroots pressure. Government employer communication carries institutional weight.",
  },
  {
    id: 56,
    date: "2024-02-12",
    source: "Maricopa County (follow-up)",
    sourceType: "news",
    channel: "employer",
    headline: "Maricopa County HR directs employees to alternative hospitals — Dignity access remains disrupted",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "Second employer communication. County actively directing employees away from Dignity to alternative facilities. This kind of employer action creates lasting reputational damage even after resolution.",
  },
  {
    id: 57,
    date: "2024-02-10",
    source: "Independent Health Agents of Arizona",
    sourceType: "news",
    channel: "employer",
    headline: "Independent health agents advise clients on navigating Dignity–BCBSAZ dispute — broker channel activated",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Insurance broker/agent channel. Independent agents advising individual and small group clients. Broker activation signals dispute has reached the retail insurance market, not just large employers.",
  },
  {
    id: 58,
    date: "2024-02-15",
    source: "Phoenix-area employers (HR departments)",
    sourceType: "news",
    channel: "employer",
    headline: "Phoenix-area employer HR teams field questions about Dignity access — workers' comp plans also affected",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Workers' compensation plans included in the out-of-network split alongside HMO, PPO, FARE plans. Employers with workplace injury claims at Dignity facilities face immediate disruption. Workers' comp angle not widely covered in media but significant for employer decision-makers.",
  },
  {
    id: 59,
    date: "2024-03-01",
    source: "Arizona employer benefits consultants",
    sourceType: "news",
    channel: "employer",
    headline: "Benefits consultants advise mid-renewal employers to weigh BCBSAZ network stability against Dignity disruption risk",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "One month into dispute, employers mid-renewal cycle begin questioning BCBSAZ network stability. Some consultants raise whether switching to UHC or Aetna avoids Dignity risk — ironic given Dignity's simultaneous Aetna dispute. Network disruption creates long-term employer confidence issue for all parties.",
  },
  {
    id: 60,
    date: "2024-03-18",
    source: "Maricopa County (resolution notice)",
    sourceType: "news",
    channel: "employer",
    headline: "Maricopa County notifies employees: Dignity Health back in-network effective March 15",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution notice to county employees. Relief for government workforce but lingering distrust. Employees who switched providers during 6-week gap may not immediately return to Dignity.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 61,
    date: "2024-02-01",
    source: "Social media (Phoenix patient community)",
    sourceType: "social",
    channel: "social",
    headline: "Phoenix-area patients share confusion on social media after Dignity hospitals go out-of-network overnight",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Early social chatter. Patients waking up to out-of-network status on Feb 1. Confusion about which hospitals affected, what it means for ongoing care, whether ER visits covered. Organic community anxiety before media coverage catches up.",
  },
  {
    id: 62,
    date: "2024-02-05",
    source: "Social media (pregnant patients)",
    sourceType: "social",
    channel: "social",
    headline: "Pregnant patients at Dignity hospitals panic over delivery coverage — 'I'm 8 months pregnant, now what?'",
    frameAdoption: "dignity",
    sentiment: "negative_bcbsaz",
    patientStory: true,
    blameDirection: "bcbsaz",
    reachEstimate: "medium",
    notes: "Pregnant patients at Chandler Regional and Mercy Gilbert face delivery coverage crisis. Highly sympathetic patient stories. Women mid-pregnancy cannot easily switch hospitals and OBs. Some blame BCBSAZ for not extending contract; others blame Dignity for demanding too much.",
  },
  {
    id: 63,
    date: "2024-02-08",
    source: "Social media (Yavapai County)",
    sourceType: "social",
    channel: "social",
    headline: "Yavapai County residents voice alarm — 'where else can we go?' — YRMC monopoly fear",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Rural community social media response recalling 2023 YRMC dispute. YRMC's near-monopoly in Yavapai County makes any Dignity dispute existential for local residents. 'Where else can we go?' captures rural access crisis. Some patients had to drive hours to Phoenix during 2023 gap.",
  },
  {
    id: 64,
    date: "2024-02-15",
    source: "Social media (Barrow Neuro patients)",
    sourceType: "social",
    channel: "social",
    headline: "Barrow Neurological Institute patients express fear of losing access to specialized neuro care",
    frameAdoption: "dignity",
    sentiment: "negative_bcbsaz",
    patientStory: true,
    blameDirection: "bcbsaz",
    reachEstimate: "medium",
    notes: "Niche but high-acuity community. Barrow is nationally ranked neurological institute within St. Joseph's (Dignity). Neuro patients (epilepsy, MS, brain tumors) have few comparable alternatives in Arizona. This subset of patient stories is most sympathetic to Dignity.",
  },
  {
    id: 65,
    date: "2024-02-20",
    source: "Social media (cancer patient community)",
    sourceType: "social",
    channel: "social",
    headline: "Cancer patients at Dignity facilities share disruption stories — treatment delays, referral chaos",
    frameAdoption: "dignity",
    sentiment: "negative_bcbsaz",
    patientStory: true,
    blameDirection: "bcbsaz",
    reachEstimate: "medium",
    notes: "Cancer treatment disruption stories. Dignity operates major oncology services across Arizona. Patients mid-chemotherapy or awaiting surgery face referral chaos. Cancer patients generate maximum public sympathy regardless of who is at fault.",
  },
  {
    id: 66,
    date: "2024-02-25",
    source: "Social media (BCBS Arizona members)",
    sourceType: "social",
    channel: "social",
    headline: "BCBSAZ members question why insurer 'dropped' Dignity — 'I pay my premiums, I should have access'",
    frameAdoption: "dignity",
    sentiment: "negative_bcbsaz",
    patientStory: false,
    blameDirection: "bcbsaz",
    reachEstimate: "medium",
    notes: "Member frustration directed at BCBSAZ. 'I pay my premiums' sentiment is powerful grassroots counter to BCBSAZ's cost-control narrative. Some members threaten to switch insurers at next open enrollment. Counter-current to media narrative favoring BCBSAZ.",
  },
  {
    id: 67,
    date: "2024-03-01",
    source: "Social media (frustration with both sides)",
    sourceType: "social",
    channel: "social",
    headline: "Month-long dispute drives social media fatigue — patients blame both Dignity and BCBSAZ equally",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Social sentiment shifts from targeted blame to frustration with both parties as dispute drags on. Duration fatigue works against the party perceived as holding out — increasingly Dignity given BCBSAZ's '$49M offer' framing.",
  },
  {
    id: 68,
    date: "2024-03-10",
    source: "Social media (Aetna crossover anxiety)",
    sourceType: "social",
    channel: "social",
    headline: "Aetna patients join alarm as March 31 deadline looms — 'Dignity is fighting everyone'",
    frameAdoption: "balanced",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "Aetna dispute deadline creates second wave of social anxiety. 'Dignity is fighting everyone' perception takes hold. Simultaneous disputes with two major insurers undermines Dignity's framing of any single insurer as unreasonable.",
  },
  {
    id: 69,
    date: "2024-03-15",
    source: "Social media (resolution reaction)",
    sourceType: "social",
    channel: "social",
    headline: "Relief on social media as Dignity–BCBSAZ deal announced — but patients note 6 weeks of unnecessary disruption",
    frameAdoption: "bcbsaz",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "Resolution social response. Relief mixed with lingering resentment toward Dignity for 6 weeks of disruption. 'Accepted final offer' framing circulates on social platforms, reinforcing BCBSAZ narrative. Some patients say they won't return to Dignity after being forced to switch.",
  },
  {
    id: 70,
    date: "2024-02-10",
    source: "Nextdoor (Phoenix metro)",
    sourceType: "social",
    channel: "social",
    headline: "Nextdoor threads in Chandler, Gilbert, Tempe neighborhoods explode with questions about Dignity access",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Hyperlocal social platform. Chandler Regional and Mercy Gilbert are community hospitals — patients live nearby. Nextdoor skews older, more affluent, politically active. Neighborhood-level discussion creates concentrated grassroots pressure. Neighbors sharing alternative hospital recommendations.",
  },
  // === ADDITIONAL MEDIA ===
  {
    id: 71,
    date: "2024-02-03",
    source: "AZ Family / KPHO (initial video)",
    sourceType: "tv",
    channel: "media",
    headline: "Dignity Health not considered in-network for most BCBSAZ members — initial broadcast report",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Video broadcast segment on AZ Family. First visual coverage for Phoenix TV audience. Notes FEP, Medicare Advantage, and ACA plans still in-network until January 1, 2025. Partial exclusion creates confusion about which plans are affected.",
  },
  {
    id: 72,
    date: "2024-02-08",
    source: "Evolving Healthcare blog (Center for Neurology)",
    sourceType: "news",
    channel: "media",
    headline: "Insights into Aetna and Dignity Health's contract negotiations — dual threat analysis",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Specialty blog provides detailed analysis of Dignity's simultaneous negotiations with BCBSAZ and Aetna. Notes Aetna commercial HMO, POS, PPO, Medicare Advantage all at risk. Physician audience concerned about multi-payor disruption.",
  },
  {
    id: 73,
    date: "2024-03-21",
    source: "WBRC (national syndication)",
    sourceType: "tv",
    channel: "media",
    headline: "Arizona Blue Cross Blue Shield reaches agreement with Dignity Health — syndicated video",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution video syndicated beyond Arizona to WBRC (Birmingham) and potentially other affiliates. Limited national pickup compared to MSK/UHC but indicates some out-of-state awareness of the dispute.",
  },
  // === ADDITIONAL STAKEHOLDER ===
  {
    id: 74,
    date: "2024-02-05",
    source: "AZ Department of Health Services (data cited)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "AZ DHS data: Dignity Health Arizona earned $153M in profits — key data point in BCBSAZ's narrative",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "high",
    notes: "PUBLIC DATA. AZ DHS profit data gave BCBSAZ its most powerful talking point. $153M in profits is concrete, verifiable, and difficult for Dignity to rebut. Adopted by ABC15 investigative coverage, Becker's, and multiple outlets. Dignity's parent CommonSpirit had $11.3B in revenue (FY2024) — scale makes profit argument even more potent.",
  },
  {
    id: 75,
    date: "2024-02-20",
    source: "CommonSpirit Health (parent company context)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "CommonSpirit Health parent company context: $33B national system negotiating against state-level insurer",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "STRUCTURAL CONTEXT. Dignity Health is part of CommonSpirit Health — one of the largest health systems in the U.S. with ~$33B in revenue and 140+ hospitals across 21 states. BCBSAZ is a regional insurer. The David vs. Goliath dynamic favors BCBSAZ in public perception. 'Corporate hospital system squeezing local insurer' is damaging framing for Dignity.",
  },
  {
    id: 76,
    date: "2024-02-28",
    source: "Arizona Hospital and Healthcare Association (context)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "AZ hospital association notes rising costs statewide — context for Dignity's rate demands",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Industry association context. Rising labor costs, supply chain pressures, and inflation affect all Arizona hospitals. Provides some contextual support for Dignity's claims of needing higher rates. But $153M profit figure undermines the 'can't afford current rates' argument.",
  },
  {
    id: 77,
    date: "2024-02-01",
    source: "AZ DOI (regulatory silence)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Arizona Department of Insurance does not intervene in Dignity–BCBSAZ dispute — no formal investigation",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "SILENCE IS DATA. Arizona DOI did not open a formal investigation or mandate cooling-off period. Unlike New York's 60-day rule, Arizona has no automatic network continuity protections. Regulatory passivity left resolution entirely to market and political pressure. Congressional delegation filled the regulatory vacuum.",
  },
  {
    id: 78,
    date: "2024-02-12",
    source: "Gualdoni v. Dignity Health (lawsuit filed)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Gualdoni v. Dignity Health lawsuit filed in U.S. District Court — patient legal action over dispute",
    frameAdoption: "balanced",
    sentiment: "negative_dignity",
    patientStory: true,
    blameDirection: "dignity",
    reachEstimate: "low",
    notes: "Federal lawsuit filed (Case 2:2024cv00219, District of Arizona). Patient-initiated legal action related to the contract dispute. Legal channel escalation indicates severity of patient harm. Low immediate media pickup but signals potential liability exposure for Dignity.",
  },
];

const LABELS = {
  frameAdoption: { dignity: "Dignity Frame", bcbsaz: "BCBSAZ Frame", balanced: "Balanced" },
  sentiment: {
    negative_bcbsaz: "Anti-BCBSAZ",
    negative_dignity: "Anti-Dignity",
    neutral: "Neutral",
    positive_bcbsaz: "Pro-BCBSAZ",
    positive_dignity: "Pro-Dignity",
  },
  blameDirection: { bcbsaz: "Blames BCBSAZ", dignity: "Blames Dignity", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National trade (1.5)
  "Becker's Payer Issues": 1.5, "InsuranceNewsNet": 1.5,
  // Tier 2 — Regional authority (1.2)
  "AZ Family / KPHO": 1.2, "12 News / KPNX": 1.2, "ABC15 Arizona": 1.2,
  "KTAR News 92.3": 1.2, "12 News / KPNX (Yavapai)": 1.2,
  "AZ Family / KPHO (initial video)": 1.2, "AZ Family / KPHO (video)": 1.2,
  // Tier 3 — Local/niche print (1.0)
  "Hoodline": 1.0, "Signals AZ": 1.0, "Copperstate News": 1.0,
  "Center for Neurology and Spine blog": 1.0, "GCMAZ / KAFF News": 1.0,
  "KNAU (Flagstaff NPR)": 1.0, "KNAU (YRMC resolution 2023)": 1.0,
  "Evolving Healthcare blog (Center for Neurology)": 1.0,
  "WBRC (national syndication)": 1.0,
  "Arizona University Center for Rural Health": 1.0,
  "Becker's Payer Issues (YRMC precedent)": 1.0,
  // Tier 4 — Organic social (0.7)
  "Social media (Phoenix patient community)": 0.7,
  "Social media (pregnant patients)": 0.7,
  "Social media (Yavapai County)": 0.7,
  "Social media (Barrow Neuro patients)": 0.7,
  "Social media (cancer patient community)": 0.7,
  "Social media (BCBS Arizona members)": 0.7,
  "Social media (frustration with both sides)": 0.7,
  "Social media (Aetna crossover anxiety)": 0.7,
  "Social media (resolution reaction)": 0.7,
  "Nextdoor (Phoenix metro)": 0.7,
  // Tier 5 — Comment sections (0.4)
  // (none identified)
  // Tier 6 — Owned/party media (0.3)
  "Dignity Health Press Center (statement)": 0.3,
  "Dignity Health Press Center (patient FAQ)": 0.3,
  "Dignity Health Press Center (YRMC record straight)": 0.3,
  "Dignity Health Press Center (extension offer)": 0.3,
  "Dignity Health Press Center (resolution)": 0.3,
  "BCBSAZ — azbluefacts.com/dignity": 0.3,
  "AZ Blue News Center": 0.3,
  "AZ Blue News Center (Setting the Record Straight)": 0.3,
  "AZ Blue News Center (resolution)": 0.3,
  "AZ Blue News Center (renewal announcement)": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "Sen. Kyrsten Sinema (I-AZ)": 1.3, "Sen. Mark Kelly (D-AZ)": 1.3,
  "Rep. Eli Crane (R-AZ)": 1.3,
  "Sen. Kelly (resolution statement)": 1.3, "Sen. Sinema (resolution statement)": 1.3,
  "Rep. Crane (resolution statement)": 1.3, "Yavapai County lawmakers": 1.3,
  "Laura Nero BSN RN (patient advocate)": 1.3,
  "Dr. Anthony Torres, CEO, YRMC": 1.3,
  "Pam Kehaly, President & CEO, BCBSAZ": 1.3,
  "BCBSAZ continuity of care notice": 1.3,
  "Dignity Health Aetna dispute (parallel)": 1.3,
  "AZ Department of Health Services (data cited)": 1.3,
  "CommonSpirit Health (parent company context)": 1.3,
  "Arizona Hospital and Healthcare Association (context)": 1.3,
  "AZ DOI (regulatory silence)": 1.3,
  "Gualdoni v. Dignity Health (lawsuit filed)": 1.3,
  // Tier 8 — Employer (1.5x county, 1.0x broker)
  "Maricopa County (employer communication)": 1.5,
  "Maricopa County (follow-up)": 1.0,
  "Maricopa County (resolution notice)": 1.0,
  "Independent Health Agents of Arizona": 1.0,
  "Phoenix-area employers (HR departments)": 1.0,
  "Arizona employer benefits consultants": 1.0,
};

const SEARCH_TRENDS = [
  { week: "2024-01-15", interest: 3 },
  { week: "2024-01-22", interest: 5 },
  { week: "2024-01-29", interest: 12 },
  { week: "2024-02-05", interest: 100 },
  { week: "2024-02-12", interest: 75 },
  { week: "2024-02-19", interest: 55 },
  { week: "2024-02-26", interest: 35 },
  { week: "2024-03-04", interest: 30 },
  { week: "2024-03-11", interest: 45 },
  { week: "2024-03-18", interest: 80 },
  { week: "2024-03-25", interest: 25 },
  { week: "2024-04-01", interest: 10 },
  { week: "2024-04-08", interest: 5 },
];

export default {
  active: false,
  // Identity
  providerKey: "dignity",
  payorKey: "bcbsaz",
  providerName: "Dignity Health",
  payorName: "Blue Cross Blue Shield of Arizona",
  providerShort: "Dignity",
  payorShort: "BCBSAZ",
  navShort: "Dignity v. BCBSAZ",
  title: "Dignity Health vs BCBSAZ",
  subtitle: "Out-of-network dispute · Feb 1 – Mar 15, 2024",
  gradientId: "dignitybcbsaz",

  // Dates
  monitorStart: "January 15, 2024",
  monitorEnd: "April 15, 2024",
  disputePublicDate: "2024-02-01",

  // Colors
  colors: {
    providerColor: "#1B6B3A",
    payorColor: "#2F65A7",
    neutral: "#64748B",
    accent: "#1B6B3A",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#1B6B3A", "#4A7E5E", "#2F65A7"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"dignity health blue cross blue shield arizona" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 0.92,
    nationalMedian: 1.0,
    networkComplaints: 634,
    priorYearComplaints: 481,
    regulatorAction: "No formal AZ DOI investigation opened. No state-mandated cooling-off period exists in Arizona (unlike NY's 60-day rule). Bipartisan congressional delegation (Sinema, Kelly, Crane) sent joint letter urging resolution. AZ state lawmakers publicly pressured both sides but leaned toward BCBSAZ position.",
    signalRead: "BCBSAZ complaint index is below national median (0.92x), reflecting its regional footprint and generally positive member satisfaction. The 32% increase in network complaints is directly attributable to the Dignity dispute. Congressional intervention is unusual for a state-level dispute and signals political severity. Dignity's simultaneous Aetna dispute created perception of pattern aggressiveness.",
  },

  // Executive summary
  executiveSummary: {
    statement: "The dispute resolved mid-March 2024 after 6 weeks of actual out-of-network status — a rare case where patients experienced real disruption, not just threatened disruption. Resolution framing of Dignity 'accepting AZ Blue's final offer' strongly favored BCBSAZ across media and political channels.",
    keyMessages: [
      "BCBSAZ's '$49M increase offered, Dignity wants 37% more' was the stickiest talking point — adopted by trade press, broadcast media, and political actors alike.",
      "Dignity's $153M in profits (AZ DHS data) undermined its claims of needing higher rates to cover costs — publicly available government data is nearly impossible to rebut.",
      "YRMC's '4th highest-cost hospital' and 'rates twice average Phoenix hospital' labels from the prior 2023 dispute provided ready-made ammunition for BCBSAZ's 2024 narrative.",
      "Simultaneous Dignity disputes with BCBSAZ AND Aetna (CA, AZ, NV deadline March 31) created 'fighting everyone' perception that undermined Dignity's insurer-blaming strategy.",
      "Bipartisan congressional intervention (Sinema, Kelly, Crane) is rare for state-level disputes — notably, no federal lawmaker was willing to publicly defend Dignity's position.",
    ],
    marcomm: [
      "<strong>BCBSAZ won the narrative war decisively.</strong> The 'accepted our final offer' resolution framing was adopted by 12 News, Becker's, and multiple outlets, positioning Dignity as the party that capitulated. Dignity's own 'reached an agreement' language was largely ignored by third-party media.",
      "<strong>Profit data neutralized Dignity's cost arguments.</strong> $153M in profits from AZ DHS data gave BCBSAZ a concrete, verifiable counter to Dignity's 'underpaid for cost of care' narrative. CommonSpirit's $33B national revenue scale made Dignity look like a corporate giant squeezing a regional insurer.",
      "<strong>The Aetna parallel destroyed Dignity's single-insurer framing.</strong> Fighting two major insurers simultaneously across multiple states made it impossible for Dignity to credibly argue that BCBSAZ alone was being unreasonable. Dignity became the common denominator in the public's mind.",
      "<strong>BCBSAZ's dedicated microsite (azbluefacts.com/dignity) was a sophisticated PR asset.</strong> Data-forward, consumer-friendly, and constantly referenced by media. Dignity had no equivalent counter-narrative hub — its press releases were reactive rather than strategic.",
      "<strong>Maricopa County as employer created decisive grassroots pressure.</strong> County employee letters about lost Dignity access created a large, politically connected constituency pressuring Dignity to settle. Government employer communications carry institutional credibility that cannot be replicated.",
    ],
  },
  channelTakeaways: {
    media: [
      "AZ Family/KPHO broke the story and bookended it with resolution coverage — dominant local TV outlet for this dispute across the full 6-week arc.",
      "ABC15's investigative angle on Dignity's $153M profit was the most damaging single media segment — turned publicly available government data into a devastating counter-narrative.",
      "Becker's Payer Issues adopted BCBSAZ's 'accepted final offer' resolution framing — set the industry narrative read by hospital executives nationally.",
      "KTAR radio provided critical reach among Phoenix metro commuters who may not follow online health news.",
      "KNAU and KAFF reached rural/northern AZ audiences still remembering the 2023 YRMC dispute — pattern recognition worked against Dignity.",
    ],
    social: [
      "Pregnant patients at Chandler Regional and Mercy Gilbert generated the most sympathetic Dignity-aligned patient stories on social media.",
      "Barrow Neurological Institute patients were the highest-acuity constituency expressing alarm — nationally ranked specialty center with few Arizona alternatives.",
      "Social sentiment fatigue after one month increasingly blamed Dignity as the party holding out against BCBSAZ's '$49M offer' — duration worked against the provider.",
      "Nextdoor threads in Chandler/Gilbert/Tempe created hyperlocal grassroots pressure in communities adjacent to Dignity hospitals.",
      "'Dignity is fighting everyone' perception emerged on social platforms when Aetna dispute became public — multi-payor pattern was devastating.",
    ],
    stakeholder: [
      "Bipartisan congressional letter (Sinema, Kelly, Crane) was the most impactful stakeholder action — rare federal intervention in a state-level dispute, and no lawmaker defended Dignity.",
      "BCBSAZ CEO Pam Kehaly's 'Setting the Record Straight' authored viewpoint provided executive-level credibility to the insurer's cost arguments.",
      "YRMC CEO Dr. Torres was Dignity's strongest stakeholder voice but 'single-digit, below inflation' claims gained limited traction against BCBSAZ's specific cost comparisons.",
      "Gualdoni v. Dignity Health federal lawsuit filed during the dispute signals potential legal liability for patient harm during the 6-week out-of-network period.",
      "Arizona's lack of a cooling-off regulation (unlike NY's 60-day rule) meant resolution depended entirely on market and political pressure — no regulatory backstop for patients.",
    ],
    employer: [
      "Maricopa County employee communications were the most impactful employer channel — large government workforce with direct political connections to lawmakers pressuring Dignity.",
      "Workers' compensation plans being included in the out-of-network split created a unique employer pain point not widely covered in media.",
      "Independent health agents activated the retail insurance channel, extending dispute awareness from large employers to small businesses and individuals.",
      "Benefits consultants advising mid-renewal employers questioned BCBSAZ network stability — but Dignity's simultaneous Aetna dispute made switching insurers futile.",
    ],
  },
  arguments: {
    payor: [
      { phase: "Early (Feb 2024)", points: ["BCBSAZ revealed it had already offered a <strong>$49M rate increase</strong> — Dignity demanded 37% more on top of that", "Positioned as Arizona's largest health insurer protecting members from excessive hospital pricing", "Leaked Dignity's <strong>$153M in profits</strong> (AZ DHS data) to undermine the provider's claims of financial need"] },
      { phase: "Mid-Dispute (Feb–Mar 2024)", points: ["Won support from <strong>AZ state lawmakers</strong> who leaned pro-BCBSAZ — political environment unfavorable to Dignity", "YRMC data point: rates allegedly <strong>twice the average Phoenix hospital and three times Tucson average</strong> — '4th highest-cost hospital in state'", "Held firm on final offer as Dignity fought on two fronts simultaneously (BCBSAZ and Aetna)"] },
      { phase: "Resolution (Mar 2024)", points: ["Resolution framed as Dignity <strong>'accepting AZ Blue's final offer'</strong> — media positioned BCBSAZ as the party that won", "12 News: 'Dignity Health accepts AZ Blue offer' — 'accepts' language positioned Dignity as capitulating after 6 weeks"] },
    ],
    provider: [
      { phase: "Early (Feb 2024)", points: ["Argued rates needed to <strong>keep pace with rising costs</strong> of care delivery in Arizona", "Emphasized affected facilities included <strong>Barrow Neurological Institute</strong> (nationally ranked) and 8 hospitals serving tens of thousands"] },
      { phase: "Mid-Dispute (Feb–Mar 2024)", points: ["Fighting on two fronts — BCBSAZ <strong>and</strong> Aetna simultaneously — undermined the 'BCBSAZ is unreasonable' narrative", "Media began framing Dignity as the <strong>common denominator</strong> across multiple payor disputes", "Congressional intervention (Kelly, Sinema, Crane) created bipartisan pressure to resolve"] },
      { phase: "Resolution (Mar 2024)", points: ["Accepted BCBSAZ's final offer after 6 weeks out-of-network — widely perceived as Dignity <strong>blinking first</strong>", "In-network effective March 15; community patience had worn thin and political pressure was mounting"] },
    ],
  },
  timeline: [
    { date: "2024-02-01", type: "termination", label: "Contract terminates" },
    { date: "2024-02-03", type: "newsBreak", label: "News breaks publicly" },
    { date: "2024-03-15", type: "agreement", label: "Agreement reached" },
  ],
};
