// Dignity Health vs Blue Cross Blue Shield of Arizona — PR War Room Config
// Dispute period: Feb 1 – Mar 15, 2024 (out-of-network). Resolved mid-March 2024.

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2024-02-03",
    source: "AZ Family / KPHO",
    sourceType: "tv",
    channel: "media",
    headline: "Dignity Health, Blue Cross Blue Shield of Arizona fail to reach deal — tens of thousands now out-of-network",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "First major TV report on the dispute. AZ Family/KPHO breaks the story for Phoenix metro. 'Tens of thousands' of BCBSAZ members in Maricopa and Pinal counties affected. 8 hospitals including St. Joseph's (home of Barrow Neurological Institute), Chandler Regional, Mercy Gilbert.",
  },
  {
    id: 2,
    date: "2024-02-07",
    source: "AZ Family / KPHO",
    sourceType: "tv",
    channel: "media",
    headline: "BCBSAZ members scramble for care as Dignity Health contract lapse enters second week",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: true,
    blameDirection: "dignity",
    reachEstimate: "high",
    notes: "Follow-up coverage. Patients scrambling for alternatives. BCBSAZ framing gains traction: Dignity demanded 37% more on top of $49M increase already offered. Patient disruption angle emerges.",
  },
  {
    id: 3,
    date: "2024-02-07",
    source: "12 News / KPNX",
    sourceType: "tv",
    channel: "media",
    headline: "Dignity Health–BCBS Arizona contract dispute leaves patients searching for new providers",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "12 News provides balanced coverage. Patients featured searching for new providers mid-treatment. Both sides' positions presented. BCBSAZ: offered $49M increase. Dignity: rates need to keep pace with costs.",
  },
  {
    id: 4,
    date: "2024-02-07",
    source: "ABC15 Arizona",
    sourceType: "tv",
    channel: "media",
    headline: "Patients caught in the middle as Dignity Health and BCBS Arizona can't agree on rates",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "ABC15 joins coverage wave. Patient-in-the-middle framing. Notes 8 hospitals affected across Phoenix metro. Both sides quoted.",
  },
  {
    id: 5,
    date: "2024-02-08",
    source: "KTAR News",
    sourceType: "radio",
    channel: "media",
    headline: "KTAR: Dignity Health, Arizona Blue contract dispute impacts thousands of Valley patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "KTAR is Arizona's dominant news/talk radio. Broad reach across Maricopa County commuters. Balanced framing with both sides' positions.",
  },
  {
    id: 6,
    date: "2024-02-10",
    source: "Hoodline",
    sourceType: "news",
    channel: "media",
    headline: "Dignity Health and Blue Cross Blue Shield of Arizona contract dispute disrupts care for thousands",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Online news aggregator covering Phoenix metro. Summarizes dispute basics: 8 hospitals, tens of thousands affected, both sides' financial claims.",
  },
  {
    id: 7,
    date: "2024-02-14",
    source: "Hoodline",
    sourceType: "news",
    channel: "media",
    headline: "Dignity Health–BCBSAZ stalemate continues; patients face Valentine's Day without resolution",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Second Hoodline piece. Two weeks into dispute with no resolution in sight. Ongoing disruption framing.",
  },
  {
    id: 8,
    date: "2024-02-12",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "Dignity Health, BCBS of Arizona at impasse over rates — 8 hospitals go out-of-network",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National trade press picks up the story. Notes BCBSAZ offered $49M increase; Dignity wants 37% more on top. Hospital executive audience. Dignity's $153M in profits (AZ DHS data) mentioned.",
  },
  {
    id: 9,
    date: "2024-02-20",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "Dignity Health–Arizona Blue dispute drags on: congressional delegation intervenes",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Second Becker's piece. Notes bipartisan congressional intervention from Kelly, Sinema, and Crane. Federal political pressure is unusual for state-level dispute.",
  },
  {
    id: 10,
    date: "2024-03-18",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "Dignity Health accepts Blue Cross Blue Shield of Arizona's final offer — dispute resolved",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "Resolution coverage. 'Accepts AZ Blue's final offer' framing strongly favors BCBSAZ — implies Dignity capitulated. Trade press audience notes Dignity blinked.",
  },
  {
    id: 11,
    date: "2024-02-15",
    source: "ABC15 Arizona",
    sourceType: "tv",
    channel: "media",
    headline: "ABC15 Investigates: Dignity Health profits vs. patient access — $153M profit highlighted",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "high",
    notes: "Investigative angle. AZ DHS data showing Dignity made $153M in profits undermines Dignity's claims of needing higher rates. BCBSAZ sends ~$100M/month in billed charges to Dignity.",
  },
  {
    id: 12,
    date: "2024-02-22",
    source: "ABC15 Arizona",
    sourceType: "tv",
    channel: "media",
    headline: "Arizona lawmakers call for end to Dignity Health–BCBS Arizona dispute as patients suffer",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: true,
    blameDirection: "dignity",
    reachEstimate: "high",
    notes: "Lawmaker pressure segment. AZ state lawmakers lean pro-BCBSAZ. Patient suffering framing combined with political pressure on Dignity.",
  },
  {
    id: 13,
    date: "2024-03-01",
    source: "ABC15 Arizona",
    sourceType: "tv",
    channel: "media",
    headline: "One month in: Dignity Health–BCBS Arizona patients still out-of-network with no deal",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Month mark coverage. Duration framing increases urgency. Patient stories of ongoing disruption and difficulty finding alternative care.",
  },
  {
    id: 14,
    date: "2024-03-21",
    source: "AZ Family / KPHO",
    sourceType: "tv",
    channel: "media",
    headline: "Dignity Health and Blue Cross Blue Shield of Arizona reach deal — patients can return to hospitals",
    frameAdoption: "bcbsaz",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "high",
    notes: "Resolution coverage. 'Patients can return' implies Dignity had taken them away. AZ Family frames resolution as Dignity accepting BCBSAZ's terms.",
  },
  {
    id: 15,
    date: "2024-03-21",
    source: "12 News / KPNX",
    sourceType: "tv",
    channel: "media",
    headline: "12 News: Dignity Health, Arizona Blue reach new agreement after weeks-long dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution coverage from 12 News. Balanced. Notes weeks of disruption now over.",
  },
  {
    id: 16,
    date: "2024-02-09",
    source: "Signals AZ",
    sourceType: "news",
    channel: "media",
    headline: "YRMC patients face out-of-network chaos as Dignity–BCBS dispute hits Yavapai County",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Yavapai County local outlet. YRMC (Yavapai Regional Medical Center) separately affected. ~20% of 58K BCBS beneficiaries in Yavapai County impacted. Rural community has fewer alternatives than Phoenix metro.",
  },
  {
    id: 17,
    date: "2024-02-20",
    source: "Signals AZ",
    sourceType: "news",
    channel: "media",
    headline: "YRMC labeled '4th highest-cost hospital in state' — rates twice average Phoenix hospital",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "Key data point for BCBSAZ's case. YRMC rates allegedly twice the average Phoenix hospital despite being in a smaller market. '4th highest-cost hospital in state' is damaging for Dignity/YRMC.",
  },
  {
    id: 18,
    date: "2024-03-05",
    source: "Signals AZ",
    sourceType: "news",
    channel: "media",
    headline: "Signals AZ: YRMC dispute enters second month — Yavapai patients demand resolution",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Third Signals AZ piece. Community frustration mounting in Yavapai County. Rural patients have fewer hospital options than Phoenix metro residents.",
  },
  {
    id: 19,
    date: "2024-03-21",
    source: "12 News / KPNX",
    sourceType: "tv",
    channel: "media",
    headline: "12 News: YRMC included in Dignity–BCBS Arizona resolution — Yavapai patients relieved",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "YRMC-specific resolution coverage. Relief framing for Yavapai County community.",
  },
  {
    id: 20,
    date: "2024-02-21",
    source: "Copperstate News",
    sourceType: "news",
    channel: "media",
    headline: "Arizona lawmakers press Dignity Health and BCBS Arizona to resolve hospital dispute",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "State political coverage. AZ lawmakers lean toward BCBSAZ position. Lawmaker pressure on Dignity to accept terms. Political environment unfavorable to Dignity.",
  },
  {
    id: 21,
    date: "2024-02-15",
    source: "Center for Neurology blog",
    sourceType: "news",
    channel: "media",
    headline: "Barrow Neurological Institute access at risk for BCBS Arizona patients — neurology community alert",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Specialty trade/blog. Barrow Neurological Institute is housed within St. Joseph's Hospital (Dignity). Loss of in-network access to Barrow is uniquely high-stakes for neuro patients. Niche but high-acuity audience.",
  },
  // === GOVERNMENT / POLITICAL ENTRIES ===
  {
    id: 22,
    date: "2024-02-16",
    source: "Sen. Mark Kelly (D-AZ)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Sen. Kelly joins bipartisan letter urging Dignity Health and BCBS Arizona to resolve dispute immediately",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Federal intervention. Bipartisan letter from Kelly, Sinema, and Crane. Unusual for federal lawmakers to weigh in on state-level provider-payor dispute. Signals political severity of disruption.",
  },
  {
    id: 23,
    date: "2024-02-16",
    source: "Sen. Kyrsten Sinema (I-AZ)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Sen. Sinema co-signs bipartisan congressional letter on Dignity–BCBS Arizona dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Independent senator joining bipartisan effort. Sinema's involvement adds cross-party credibility. Letter urges both sides but political environment slightly favors BCBSAZ framing.",
  },
  {
    id: 24,
    date: "2024-02-16",
    source: "Rep. Eli Crane (R-AZ)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Rep. Crane joins Kelly, Sinema in pressing for resolution — bipartisan concern over patient access",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Republican congressman. Bipartisan nature of intervention (D, I, R) is significant — neither party willing to publicly side with Dignity. Crane represents rural districts where hospital alternatives are limited.",
  },
  {
    id: 25,
    date: "2024-03-18",
    source: "Sen. Kelly (resolution statement)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Sen. Kelly welcomes resolution — credits congressional pressure for breaking impasse",
    frameAdoption: "bcbsaz",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "Resolution statement. Kelly frames outcome as Dignity accepting reasonable terms. Congressional involvement framed as catalyst for resolution.",
  },
  {
    id: 26,
    date: "2024-03-18",
    source: "Sen. Sinema (resolution statement)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Sen. Sinema: 'Arizonans should never be caught in the middle of corporate disputes'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution statement. 'Corporate disputes' framing assigns systemic blame. Balanced but implicitly critical of Dignity for prolonging dispute.",
  },
  {
    id: 27,
    date: "2024-03-18",
    source: "Rep. Crane (resolution statement)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Rep. Crane: pleased dispute resolved, reiterates need for transparency in hospital pricing",
    frameAdoption: "bcbsaz",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "Resolution statement. 'Transparency in hospital pricing' framing aligns with BCBSAZ's narrative about Dignity's high costs. Republican congressman effectively validates insurer position.",
  },
  {
    id: 28,
    date: "2024-02-22",
    source: "Yavapai County lawmakers",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Yavapai County state legislators demand resolution — YRMC is only major hospital for region",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "State-level political intervention for YRMC specifically. YRMC's monopoly position in Yavapai County makes dispute uniquely harmful to rural patients. Lawmakers note limited alternatives.",
  },
  // === PATIENT / ADVOCATE ENTRIES ===
  {
    id: 29,
    date: "2024-02-12",
    source: "Laura Nero BSN RN (patient advocate)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Laura Nero BSN RN: 'Delay in treatment has significant impact' on patients caught in dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Patient advocate (BSN RN), not a patient herself. Professional credibility adds weight to treatment disruption claims. 'Delay in treatment has significant impact' — clinical framing of dispute consequences. Used by media as expert source.",
  },
  // === YRMC STAKEHOLDER ===
  {
    id: 30,
    date: "2024-02-20",
    source: "Dr. Torres, YRMC",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "YRMC Dr. Torres: rate requests 'single digits, below medical inflation rate' — disputes BCBSAZ cost claims",
    frameAdoption: "dignity",
    sentiment: "negative_bcbsaz",
    patientStory: false,
    blameDirection: "bcbsaz",
    reachEstimate: "medium",
    notes: "YRMC physician pushback on BCBSAZ claims. Dr. Torres asserts rate increase requests were 'single digits, below medical inflation rate' — directly contradicts BCBSAZ narrative of excessive demands. Counter-data point to '4th highest-cost hospital' and 'twice average' claims.",
  },
  // === DIGNITY OWNED MEDIA ===
  {
    id: 31,
    date: "2024-02-01",
    source: "Dignity Health Press Center (statement)",
    sourceType: "owned",
    channel: "media",
    headline: "Dignity Health: 'We are committed to our patients and communities — BCBS AZ offer does not cover cost of care'",
    frameAdoption: "dignity",
    sentiment: "negative_bcbsaz",
    patientStory: false,
    blameDirection: "bcbsaz",
    reachEstimate: "medium",
    notes: "Initial Dignity statement. Frames dispute as BCBSAZ underpaying for cost of care. Community commitment messaging. Defensive posture from day one.",
  },
  {
    id: 32,
    date: "2024-02-15",
    source: "Dignity Health Press Center (YRMC record straight)",
    sourceType: "owned",
    channel: "media",
    headline: "Dignity Health sets the record straight on YRMC costs — disputes '4th highest-cost' label",
    frameAdoption: "dignity",
    sentiment: "negative_bcbsaz",
    patientStory: false,
    blameDirection: "bcbsaz",
    reachEstimate: "medium",
    notes: "Specific YRMC rebuttal. Dignity challenges BCBSAZ's characterization of YRMC as 4th highest-cost hospital. Argues cost comparisons are misleading without accounting for patient acuity and rural market dynamics.",
  },
  {
    id: 33,
    date: "2024-03-13",
    source: "Dignity Health Press Center (48hr extension)",
    sourceType: "owned",
    channel: "media",
    headline: "Dignity Health announces 48-hour extension for negotiations with BCBS Arizona",
    frameAdoption: "dignity",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Last-stage negotiation signal. 48-hour extension suggests Dignity attempting to appear willing to negotiate. But extension framing also signals Dignity is running out of leverage.",
  },
  {
    id: 34,
    date: "2024-03-15",
    source: "Dignity Health Press Center (resolution)",
    sourceType: "owned",
    channel: "media",
    headline: "Dignity Health: 'We have reached an agreement with Blue Cross Blue Shield of Arizona'",
    frameAdoption: "dignity",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution announcement. Dignity frames as mutual agreement. But third-party reporting consistently frames it as Dignity 'accepting AZ Blue's final offer' — undercutting Dignity's victory narrative.",
  },
  // === BCBSAZ OWNED MEDIA ===
  {
    id: 35,
    date: "2024-02-01",
    source: "BCBSAZ — azbluefacts.com/dignity",
    sourceType: "owned",
    channel: "media",
    headline: "BCBSAZ launches azbluefacts.com/dignity microsite — central hub for insurer's narrative",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "STRATEGIC OWNED MEDIA. Dedicated microsite is sophisticated PR move. Key claims: offered $49M increase, Dignity demanded 37% more on top. Dignity made $153M in profits. BCBSAZ sends ~$100M/month in billed charges. Data-forward approach to frame Dignity as greedy.",
  },
  {
    id: 36,
    date: "2024-02-05",
    source: "AZ Blue News Center",
    sourceType: "owned",
    channel: "media",
    headline: "AZ Blue News Center: 'We offered Dignity Health a $49 million increase — they want 37% more'",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "BCBSAZ's primary narrative vehicle. $49M offer vs. 37% demand is the stickiest BCBSAZ talking point. Paired with Dignity's $153M profit figure from AZ DHS data. Effective cost-framing.",
  },
  {
    id: 37,
    date: "2024-03-15",
    source: "AZ Blue News Center",
    sourceType: "owned",
    channel: "media",
    headline: "AZ Blue News Center: 'Dignity Health has accepted Arizona Blue's final offer'",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "CRITICAL RESOLUTION FRAMING. 'Accepted AZ Blue's final offer' positions BCBSAZ as winner. This framing was adopted by Becker's and other outlets. Dignity's resolution statement says 'reached an agreement' but third-party coverage favored BCBSAZ's version.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 38,
    date: "2024-02-05",
    source: "Maricopa County (employer communication)",
    sourceType: "news",
    channel: "employer",
    headline: "Maricopa County sends letters to employees: Dignity Health hospitals now out-of-network for county BCBS plans",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "high",
    notes: "CRITICAL EMPLOYER SIGNAL. Maricopa County is one of the largest employers in the region. County employees receiving formal letters about loss of Dignity access creates massive grassroots pressure. Government employer communication carries institutional weight.",
  },
  {
    id: 39,
    date: "2024-02-12",
    source: "Maricopa County (follow-up)",
    sourceType: "news",
    channel: "employer",
    headline: "Maricopa County HR directs employees to alternative hospitals — Dignity access remains disrupted",
    frameAdoption: "bcbsaz",
    sentiment: "negative_dignity",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "Second employer communication. County actively directing employees away from Dignity. This kind of employer action creates lasting reputational damage even after resolution.",
  },
  {
    id: 40,
    date: "2024-02-10",
    source: "Independent Health Agents of Arizona",
    sourceType: "news",
    channel: "employer",
    headline: "Independent health agents advise clients on navigating Dignity–BCBSAZ dispute — broker channel activated",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Insurance broker/agent channel. Independent agents advising individual and small group clients. Broker activation signals dispute has reached the retail insurance market, not just large employers.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 41,
    date: "2024-02-03",
    source: "Social media (Phoenix patient community)",
    sourceType: "social",
    channel: "social",
    headline: "Phoenix-area patients share confusion on social media after Dignity hospitals go out-of-network overnight",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Early social chatter. Patients waking up to out-of-network status on Feb 1. Confusion about which hospitals affected, what it means for ongoing care. Organic community anxiety.",
  },
  {
    id: 42,
    date: "2024-02-08",
    source: "Social media (Yavapai County)",
    sourceType: "social",
    channel: "social",
    headline: "Yavapai County residents voice alarm over YRMC access — 'where else can we go?'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Rural community social media response. YRMC's near-monopoly in Yavapai County makes dispute existential for local residents. 'Where else can we go?' captures rural access crisis. ~20% of 58K BCBS beneficiaries affected.",
  },
  {
    id: 43,
    date: "2024-02-15",
    source: "Social media (Barrow Neuro patients)",
    sourceType: "social",
    channel: "social",
    headline: "Barrow Neurological Institute patients express fear of losing access to specialized neuro care",
    frameAdoption: "dignity",
    sentiment: "negative_bcbsaz",
    patientStory: true,
    blameDirection: "bcbsaz",
    reachEstimate: "medium",
    notes: "Niche but high-acuity community. Barrow is a nationally ranked neurological institute within St. Joseph's (Dignity). Neuro patients have few comparable alternatives. This subset of patient stories is most sympathetic to Dignity.",
  },
  {
    id: 44,
    date: "2024-03-01",
    source: "Social media (frustration with both sides)",
    sourceType: "social",
    channel: "social",
    headline: "Month-long dispute drives social media fatigue — patients blame both Dignity and BCBSAZ",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Social sentiment shifts from targeted blame to frustration with both parties as dispute drags on. Duration fatigue works against the party perceived as holding out — increasingly Dignity.",
  },
  {
    id: 45,
    date: "2024-03-15",
    source: "Social media (resolution reaction)",
    sourceType: "social",
    channel: "social",
    headline: "Relief on social media as Dignity–BCBSAZ deal announced — but patients note weeks of disruption",
    frameAdoption: "bcbsaz",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "dignity",
    reachEstimate: "medium",
    notes: "Resolution social response. Relief mixed with lingering resentment toward Dignity for weeks of disruption. 'Accepted final offer' framing circulates on social platforms, reinforcing BCBSAZ narrative.",
  },
];

const LABELS = {
  frameAdoption: { dignity: "Dignity Frame", bcbsaz: "BCBSAZ Frame", balanced: "Balanced" },
  sentiment: {
    negative_bcbsaz: "Anti-BCBSAZ",
    negative_dignity: "Anti-Dignity",
    neutral: "Neutral",
    positive_bcbsaz: "Pro-BCBSAZ",
    positive_dignity: "Pro-Dignity",
  },
  blameDirection: { bcbsaz: "Blames BCBSAZ", dignity: "Blames Dignity", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National trade (1.5)
  "Becker's Hospital Review": 1.5,
  // Tier 2 — Regional authority (1.2)
  "AZ Family / KPHO": 1.2, "12 News / KPNX": 1.2, "ABC15 Arizona": 1.2, "KTAR News": 1.2,
  // Tier 3 — Local/niche print (1.0)
  "Hoodline": 1.0, "Signals AZ": 1.0, "Copperstate News": 1.0, "Center for Neurology blog": 1.0,
  // Tier 4 — Organic social (0.7)
  "Social media (Phoenix patient community)": 0.7, "Social media (Yavapai County)": 0.7,
  "Social media (Barrow Neuro patients)": 0.7, "Social media (frustration with both sides)": 0.7,
  "Social media (resolution reaction)": 0.7,
  // Tier 6 — Owned/party media (0.3)
  "Dignity Health Press Center (statement)": 0.3, "Dignity Health Press Center (YRMC record straight)": 0.3,
  "Dignity Health Press Center (48hr extension)": 0.3, "Dignity Health Press Center (resolution)": 0.3,
  "BCBSAZ — azbluefacts.com/dignity": 0.3, "AZ Blue News Center": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "Sen. Mark Kelly (D-AZ)": 1.3, "Sen. Kyrsten Sinema (I-AZ)": 1.3, "Rep. Eli Crane (R-AZ)": 1.3,
  "Sen. Kelly (resolution statement)": 1.3, "Sen. Sinema (resolution statement)": 1.3,
  "Rep. Crane (resolution statement)": 1.3, "Yavapai County lawmakers": 1.3,
  "Laura Nero BSN RN (patient advocate)": 1.3, "Dr. Torres, YRMC": 1.3,
  // Tier 8 — Employer (1.5)
  "Maricopa County (employer communication)": 1.5, "Maricopa County (follow-up)": 1.0,
  "Independent Health Agents of Arizona": 1.0,
};

const SEARCH_TRENDS = [
  { week: "2024-01-15", interest: 5 },
  { week: "2024-01-22", interest: 5 },
  { week: "2024-01-29", interest: 5 },
  { week: "2024-02-01", interest: 60 },
  { week: "2024-02-05", interest: 80 },
  { week: "2024-02-07", interest: 100 },
  { week: "2024-02-12", interest: 70 },
  { week: "2024-02-19", interest: 50 },
  { week: "2024-02-26", interest: 30 },
  { week: "2024-03-04", interest: 35 },
  { week: "2024-03-11", interest: 50 },
  { week: "2024-03-18", interest: 70 },
  { week: "2024-03-21", interest: 80 },
  { week: "2024-03-25", interest: 30 },
  { week: "2024-04-01", interest: 15 },
  { week: "2024-04-08", interest: 8 },
  { week: "2024-04-15", interest: 5 },
];

export default {
  // Identity
  providerKey: "dignity",
  payorKey: "bcbsaz",
  providerName: "Dignity Health",
  payorName: "Blue Cross Blue Shield of Arizona",
  providerShort: "Dignity",
  payorShort: "BCBSAZ",
  navShort: "Dignity v. BCBSAZ",
  title: "Dignity Health vs BCBSAZ",
  subtitle: "Out-of-network dispute · Feb 1 – Mar 15, 2024",
  gradientId: "dignitybcbsaz",

  // Dates
  monitorStart: "January 15, 2024",
  monitorEnd: "April 30, 2024",
  disputePublicDate: "2024-02-01",

  // Colors
  colors: {
    providerColor: "#1B6B3A",
    payorColor: "#2F65A7",
    neutral: "#64748B",
    accent: "#1B6B3A",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#1B6B3A", "#4A7E5E", "#2F65A7"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"dignity health blue cross blue shield arizona" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 0.92,
    nationalMedian: 1.0,
    networkComplaints: 634,
    priorYearComplaints: 481,
    regulatorAction: "No formal AZ DOI investigation opened. Bipartisan congressional delegation (Kelly, Sinema, Crane) sent joint letter urging resolution. AZ state lawmakers publicly pressured Dignity Health.",
    signalRead: "BCBSAZ complaint index is below national median (0.92x), reflecting its regional footprint and generally positive member satisfaction. The 32% increase in network complaints is directly attributable to the Dignity dispute. Congressional intervention is unusual for a state-level dispute and signals political severity.",
  },

  // Executive summary
  executiveSummary: {
    statement: "The dispute resolved mid-March 2024 with Dignity 'accepting AZ Blue's final offer' — resolution framing strongly favored BCBSAZ across media and political channels.",
    keyMessages: [
      "BCBSAZ's '$49M increase offered, Dignity wants 37% more' was the stickiest talking point — adopted by trade press and political actors.",
      "Dignity's $153M in profits (AZ DHS data) undermined its claims of needing higher rates to cover costs.",
      "YRMC's '4th highest-cost hospital' and 'rates twice average Phoenix hospital' labels were damaging data points Dignity struggled to counter.",
      "Bipartisan congressional intervention (Kelly, Sinema, Crane) is rare for state-level disputes and signaled that neither party was willing to defend Dignity publicly.",
    ],
    marcomm: [
      "<strong>BCBSAZ won the narrative war decisively.</strong> The 'accepted our final offer' resolution framing was adopted by third-party outlets, positioning Dignity as the party that capitulated. Dignity's own 'reached an agreement' language was largely ignored.",
      "<strong>Profit data neutralized Dignity's cost arguments.</strong> $153M in profits from AZ DHS data gave BCBSAZ a concrete, verifiable counter to Dignity's 'underpaid for cost of care' narrative. Publicly available financial data is difficult to rebut.",
      "<strong>YRMC was Dignity's weakest flank.</strong> The '4th highest-cost hospital' and 'twice average Phoenix hospital' data points were devastating. Dr. Torres's counter-claim of 'single-digit, below inflation' requests gained limited traction against specific cost comparisons.",
      "<strong>Maricopa County as employer created grassroots pressure.</strong> County employee letters about lost Dignity access created a large, politically connected constituency pressuring Dignity to settle. Government employer communications carry institutional credibility.",
    ],
  },
  channelTakeaways: {
    media: [
      "AZ Family/KPHO broke the story and bookended it with resolution coverage — dominant local TV outlet for this dispute.",
      "ABC15 investigative angle on Dignity's $153M profit was the most damaging single media segment for the provider.",
      "Becker's trade coverage adopted BCBSAZ's 'accepted final offer' framing in resolution headline — set the industry narrative.",
      "Signals AZ provided critical YRMC-specific local coverage that amplified rural access concerns in Yavapai County.",
    ],
    social: [
      "Phoenix patient community social media reflected confusion more than blame early on — shifted to anti-Dignity as duration increased.",
      "Yavapai County social response was uniquely intense due to YRMC's near-monopoly position — 'where else can we go?' framing.",
      "Barrow Neurological Institute patients were the most sympathetic Dignity-aligned constituency on social platforms.",
      "Social sentiment fatigue after one month increasingly blamed Dignity as the party holding out against a reasonable offer.",
    ],
    stakeholder: [
      "Bipartisan congressional letter (Kelly, Sinema, Crane) was the most impactful stakeholder action — rare federal intervention in state dispute.",
      "AZ state lawmakers leaned pro-BCBSAZ, creating an unfavorable political environment for Dignity throughout the dispute.",
      "Laura Nero BSN RN provided professional-credibility patient advocate voice: 'delay in treatment has significant impact.'",
      "Dr. Torres (YRMC) was Dignity's strongest stakeholder voice but gained limited traction against BCBSAZ's specific cost data.",
    ],
    employer: [
      "Maricopa County employee communications were the most impactful employer channel — large government workforce with political influence.",
      "Independent health agents activated the retail insurance channel, extending dispute awareness beyond large employer groups.",
      "BCBSAZ's $100M/month billed charges figure positioned Dignity as already well-compensated — effective employer-facing data point.",
    ],
  },
};
