// Dignity Health vs Aetna (CVS Health) — Contract Dispute 2024
// Dispute public: Feb 2024 (BCBS-AZ phase) / March-April 2024 (Aetna phase)
// Resolved: April 25, 2024

export default {
  active: false,
  title: "Dignity Health vs Aetna",
  navShort: "Dignity v. Aetna",
  subtitle: "Multi-state contract dispute (CA, AZ, NV) — Feb-Apr 2024",
  providerName: "Dignity Health",
  providerShort: "Dignity",
  payorName: "Aetna",
  payorShort: "Aetna",
  providerKey: "dignity",
  payorKey: "aetna",
  disputePublicDate: "2024-02-01",
  monitorStart: "2024-01-15",
  monitorEnd: "2024-05-24",
  gradientId: "dignityAetna",
  searchLabel: '"Dignity Health Aetna" — Google Trends (relative)',
  yAxisWidth: 78,

  colors: {
    bg: "#FAFAF8",
    surface: "#F1F0ED",
    text: "#1A1A2E",
    textMuted: "#64748B",
    accent: "#465E85",
    border: "#D8DDE6",
    providerColor: "#1B6B3A",   // Dignity green
    payorColor: "#7B2D8E",      // Aetna/CVS purple
  },

  distColors: ["#1B6B3A", "#465E85", "#7B2D8E"],

  labels: {
    providerFrame: "Dignity Frame",
    payorFrame: "Aetna Frame",
  },

  sourceWeights: {
    "ABC15 (Phoenix)": 1.2,
    "AZFamily (3TV/CBS 5)": 1.2,
    "12News (KPNX Phoenix)": 1.2,
    "KSBY (San Luis Obispo)": 1.1,
    "KEYT (Santa Barbara)": 1.1,
    "Action News Now (Chico-Redding)": 1.0,
    "Daily Democrat (Woodland)": 1.0,
    "The Daily Courier (Prescott)": 1.0,
    "Prescott eNews": 0.9,
    "Prescott Valley Times": 0.9,
    "Chino Valley Review": 0.9,
    "San Luis Obispo Tribune": 1.0,
    "Santa Cruz Sentinel": 1.0,
    "Red Bluff Daily News": 0.9,
    "Becker's Payer Issues": 1.1,
    "InsuranceNewsNet": 1.0,
    "Hoodline": 0.8,
    "The Union (Grass Valley)": 0.9,
    "edhat (Santa Barbara)": 0.8,
    "Yubanet": 0.7,
    "The Aggie (UC Davis)": 0.7,
    "Davis Enterprise": 0.9,
    "TPG Online Daily": 0.8,
    "Dignity Health (press release)": 0.3,
    "Aetna (statement)": 0.3,
    "YRMC (press release)": 0.3,
    "Sen. Kelly office": 0.8,
    "Sen. Sinema office": 0.8,
    "GCMAZ (Flagstaff radio)": 0.9,
    "Yahoo News": 1.0,
    "Center for Neurology and Spine (blog)": 0.5,
    "TTG Healthcare Advisors": 0.6,
    "KRCR-TV (Redding)": 1.1,
  },

  executiveSummary: {
    statement:
      "Dignity Health leveraged patient-centered framing and local media saturation to maintain narrative advantage throughout a 25-day out-of-network gap. The dispute's resolution via retroactive multi-year contract suggests Aetna conceded on key rate terms. Notably, this dispute occurred simultaneously with Dignity's BCBS-AZ and Partnership HealthPlan breakdowns, amplifying the narrative that insurers — not Dignity — were responsible for disruptions. The presence of named, vulnerable patient stories (elderly widower, single mothers, chronically ill) proved decisive in local media framing.",
  },

  channelTakeaways: {
    media: [
      "Local TV (ABC15, AZFamily, 12News, KSBY, KEYT) drove the most impactful coverage with patient-first framing.",
      "Community newspapers (Daily Democrat, Daily Courier, Prescott eNews) provided the most sustained, detailed coverage with multiple named patient stories.",
      "Trade press (Becker's, InsuranceNewsNet) was more balanced, framing it as standard contract negotiations.",
      "Dignity Health controlled the PR cadence — issuing press releases at every stage while Aetna relied on brief statements.",
    ],
    social: [
      "No viral social media moments specific to the Aetna dispute, but high engagement on local news article comment sections.",
      "Patient anxiety was amplified on local Facebook groups in Yolo County, Prescott AZ, and SLO County.",
      "The concurrent BCBS-AZ dispute generated more social activity in Arizona markets.",
    ],
    stakeholder: [
      "Bipartisan federal delegation (Sens. Kelly, Sinema + Rep. Crane) intervened during the BCBS-AZ phase, creating political pressure template for Aetna phase.",
      "Yolo County and Yavapai County Boards of Supervisors both took formal action urging resolution.",
      "John Aiello op-ed in The Union accused Dignity of 'playing hardball' with the state — a rare pro-payor/anti-provider narrative.",
    ],
    employer: [
      "Employer-specific coverage was minimal. Most employer impact was channeled through Aetna's own member communications.",
      "TTG Healthcare Advisors flagged the termination for benefits consultants, indicating employer plan disruptions.",
      "No public employer coalition statements emerged, unlike higher-profile disputes.",
    ],
  },

  complaintData: {
    insurerIndex: "1.4",
    nationalMedian: "1.0",
    networkComplaints: "Not publicly reported",
    priorYearComplaints: "N/A",
    regulatorAction: "CA DMHC monitored but took no formal enforcement action. No public regulatory orders issued during the dispute.",
    signalRead: "The absence of DMHC enforcement suggests both sides maintained continuity-of-care provisions. Political pressure came from elected officials, not regulators.",
  },

  searchTrends: [
    { week: "2024-01-14", interest: 3 },
    { week: "2024-01-21", interest: 4 },
    { week: "2024-01-28", interest: 8 },
    { week: "2024-02-04", interest: 35 },
    { week: "2024-02-11", interest: 42 },
    { week: "2024-02-18", interest: 28 },
    { week: "2024-02-25", interest: 20 },
    { week: "2024-03-03", interest: 25 },
    { week: "2024-03-10", interest: 30 },
    { week: "2024-03-17", interest: 55 },
    { week: "2024-03-24", interest: 72 },
    { week: "2024-03-31", interest: 100 },
    { week: "2024-04-07", interest: 88 },
    { week: "2024-04-14", interest: 60 },
    { week: "2024-04-21", interest: 45 },
    { week: "2024-04-28", interest: 70 },
    { week: "2024-05-05", interest: 30 },
    { week: "2024-05-12", interest: 15 },
    { week: "2024-05-19", interest: 8 },
  ],

  entries: [
    // ============================================================
    // MEDIA ENTRIES (40)
    // ============================================================

    // --- BCBS-AZ Phase (Context for Aetna dispute, same provider) ---
    {
      id: 1,
      date: "2024-02-01",
      source: "Dignity Health (press release)",
      url: "https://www.dignityhealth.org/arizona/about-us/press-center/press-releases/statement-regarding-bcbs-negotiations",
      sourceType: "owned",
      channel: "media",
      headline: "Statement from Dignity Health regarding contract negotiations with Blue Cross Blue Shield of Arizona",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: false,
      blameDirection: "aetna",
      reachEstimate: "medium",
      notes: "Owned media. Dignity frames BCBSAZ as refusing to pay millions in outstanding claims and rejecting fair terms. Sets the PR template used later against Aetna.",
    },
    {
      id: 2,
      date: "2024-02-03",
      source: "AZFamily (3TV/CBS 5)",
      url: "https://www.azfamily.com/2024/02/03/dignity-health-is-no-longer-in-network-certain-arizona-blue-cross-blue-shield-members/",
      sourceType: "tv",
      channel: "media",
      headline: "Dignity Health is no longer in-network for certain Arizona Blue Cross Blue Shield members",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "high",
      notes: "Breaking news coverage. Straight reporting that Dignity dropped BCBSAZ in Maricopa/Pinal counties as of Feb 1. Both sides quoted.",
    },
    {
      id: 3,
      date: "2024-02-07",
      source: "AZFamily (3TV/CBS 5)",
      url: "https://www.azfamily.com/2024/02/07/patients-scramble-find-new-providers-after-dignity-health-stops-accepting-bcbsaz/",
      sourceType: "tv",
      channel: "media",
      headline: "Patients scramble to find new providers after Dignity Health stops accepting BCBSAZ",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: true,
      blameDirection: "aetna",
      reachEstimate: "high",
      notes: "Patient-first story with scramble framing. Laura Nero (RN Health Advocates) quoted on care disruptions. Continuity-of-care advice featured. Pro-patient/pro-provider tone.",
    },
    {
      id: 4,
      date: "2024-02-07",
      source: "12News (KPNX Phoenix)",
      url: "https://www.12news.com/article/news/health/dignity-health-no-longer-accepts-blue-cross-blue-shield/75-b5364f99-6550-4ce1-a8a7-8c8537a60155",
      sourceType: "tv",
      channel: "media",
      headline: "Major AZ insurance provider no longer accepted at Dignity Health",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "high",
      notes: "Neutral TV coverage. Notes all Dignity Health hospitals in AZ except YRMC are out of network for BCBSAZ. Both sides' statements included.",
    },
    {
      id: 5,
      date: "2024-02-08",
      source: "Becker's Payer Issues",
      url: "https://www.beckerspayer.com/contracting/bcbs-arizona-dignity-health-split/",
      sourceType: "news",
      channel: "media",
      headline: "BCBS Arizona, Dignity Health split",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Trade press. Matter-of-fact reporting. Notes Dignity accused BCBSAZ of refusing to pay millions in outstanding claims.",
    },
    {
      id: 6,
      date: "2024-02-08",
      source: "12News (KPNX Phoenix)",
      sourceType: "tv",
      channel: "media",
      headline: "Thousands waiting on deal between Blue Cross Blue Shield Arizona, Dignity Health in Yavapai County",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: true,
      blameDirection: "aetna",
      reachEstimate: "high",
      notes: "Focuses on rural Yavapai County where YRMC is sole major provider. 'Thousands' framing. Patient access crisis angle dominant.",
    },
    {
      id: 7,
      date: "2024-02-09",
      source: "Hoodline",
      url: "https://hoodline.com/2024/03/patients-scramble-for-new-providers-as-dignity-health-ends-bcbsaz-in-network-coverage-in-arizona/",
      sourceType: "news",
      channel: "media",
      headline: "Dignity Health Ends In-Network Services with Blue Cross Blue Shield in Arizona, Patients Brace for Rising Costs",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: false,
      blameDirection: "aetna",
      reachEstimate: "low",
      notes: "Aggregated reporting, Dignity-favorable framing. Highlights patient cost impact.",
    },

    // --- Aetna Negotiations & Pre-Termination Phase ---
    {
      id: 8,
      date: "2024-03-05",
      source: "Action News Now (Chico-Redding)",
      url: "https://www.actionnewsnow.com/news/contract-negotiations-underway-between-dignity-health-partnership-healthplan-aetna/article_ed7c372e-db4b-11ee-a9ca-ef9435c2a5ef.html",
      sourceType: "tv",
      channel: "media",
      headline: "Contract negotiations underway between Dignity Health, Partnership HealthPlan & Aetna",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "First major reporting linking Aetna and Partnership HealthPlan negotiations together. Notes March 31 deadline for both. 64,000+ Partnership patients at risk in 5 Northern CA counties.",
    },
    {
      id: 9,
      date: "2024-03-15",
      source: "KSBY (San Luis Obispo)",
      url: "https://www.ksby.com/santa-maria/dignity-healths-agreement-with-aetna-expires-this-month-what-happens-next",
      sourceType: "tv",
      channel: "media",
      headline: "Dignity Health's agreement with Aetna expires this month. What happens next?",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Explainer piece. Notes Dignity owns 3 local hospitals (Arroyo Grande, French Hospital, Marian Regional). Lists affected plan types: commercial HMO, POS, PPO, Medicare Advantage, Aetna Whole Health.",
    },
    {
      id: 10,
      date: "2024-03-16",
      source: "Daily Democrat (Woodland)",
      sourceType: "news",
      channel: "media",
      headline: "Woodland Clinic patients insured by Aetna could lose coverage on April 1",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: true,
      blameDirection: "aetna",
      reachEstimate: "medium",
      notes: "Community paper deep-dive. Out-of-network fees explained. Continuity of care options detailed. Patient anxiety framing.",
    },
    {
      id: 11,
      date: "2024-03-21",
      source: "AZFamily (3TV/CBS 5)",
      sourceType: "tv",
      channel: "media",
      headline: "Deal reached between Dignity Health, Arizona Blue Cross Blue Shield",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "high",
      notes: "BCBS-AZ resolution. Dignity accepted final offer; back in-network as of March 15. Sets positive precedent as Aetna deadline looms.",
    },
    {
      id: 12,
      date: "2024-03-21",
      source: "ABC15 (Phoenix)",
      sourceType: "tv",
      channel: "media",
      headline: "BCBS of Arizona members back in-network at Dignity Health after agreement",
      frameAdoption: "balanced",
      sentiment: "positive_dignity",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "high",
      notes: "Resolution framing. Relief narrative for AZ patients. Sets up 'will Aetna follow?' question.",
    },
    {
      id: 13,
      date: "2024-03-26",
      source: "Daily Democrat (Woodland)",
      sourceType: "news",
      channel: "media",
      headline: "Thousands of Yolo County residents at risk of losing healthcare coverage",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: true,
      blameDirection: "aetna",
      reachEstimate: "medium",
      notes: "Escalation coverage. 17,000+ Yolo County residents at risk. Covers both Aetna and Partnership HealthPlan negotiations. Patient anxiety quotes.",
    },
    {
      id: 14,
      date: "2024-03-27",
      source: "San Luis Obispo Tribune",
      sourceType: "news",
      channel: "media",
      headline: "Fact check: Is Aetna dropping Dignity Health coverage for Central Coast patients?",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Fact-check framing. Clarifies it's a bilateral dispute, not Aetna unilaterally dropping Dignity. Both sides' claims examined. Syndicated to Yahoo News and InsuranceNewsNet.",
    },
    {
      id: 15,
      date: "2024-03-28",
      source: "ABC15 (Phoenix)",
      sourceType: "tv",
      channel: "media",
      headline: "Thousands of BCBSAZ patients out of network at Dignity Health, Aetna patients also at risk",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: true,
      blameDirection: "aetna",
      reachEstimate: "high",
      notes: "Bridges BCBS-AZ and Aetna disputes. Frames Dignity as under siege from multiple insurers. 'Also at risk' framing treats Aetna disruption as a further blow to patients.",
    },
    {
      id: 16,
      date: "2024-03-30",
      source: "Daily Democrat (Woodland)",
      sourceType: "news",
      channel: "media",
      headline: "Yolo County mother's anxiety grows over impending loss of health coverage",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: true,
      blameDirection: "aetna",
      reachEstimate: "medium",
      notes: "PATIENT STORY: Sue Kumar, single mother, Partnership HealthPlan Medi-Cal recipient. Rheumatoid arthritis patient at Woodland Clinic. 10-year-old child also at risk of losing pediatrician. Rinvoq prescription delayed. Extremely sympathetic framing.",
    },

    // --- Contract Termination & Out-of-Network Period ---
    {
      id: 17,
      date: "2024-04-01",
      source: "The Daily Courier (Prescott)",
      sourceType: "news",
      channel: "media",
      headline: "Dignity Health: Negotiations with Aetna extended to Friday",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Reports joint decision to extend deadline from March 31 to April 5 at 11:59 PM. Shows both sides still engaged. ~300 YRMG physicians affected.",
    },
    {
      id: 18,
      date: "2024-04-01",
      source: "Chino Valley Review",
      sourceType: "news",
      channel: "media",
      headline: "Dignity Health negotiations on new contract with Aetna extended",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "low",
      notes: "Rural AZ community paper. Echoes Daily Courier reporting on extension.",
    },
    {
      id: 19,
      date: "2024-04-02",
      source: "Daily Democrat (Woodland)",
      sourceType: "news",
      channel: "media",
      headline: "Yolo County Partnership HealthPlan members left scrambling after Dignity Health contract ends",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: true,
      blameDirection: "aetna",
      reachEstimate: "medium",
      notes: "Partnership HealthPlan contract expires March 31. Nicole Allison featured — has chronic conditions, received 3-week notice to find new doctors/specialists. 'Scrambling' framing dominant.",
    },
    {
      id: 20,
      date: "2024-04-03",
      source: "The Daily Courier (Prescott)",
      sourceType: "news",
      channel: "media",
      headline: "Dignity Health announces new uncertainty about negotiation deadline with Aetna",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Uncertainty narrative. Extension may not hold. Heightens patient anxiety in Prescott market.",
    },
    {
      id: 21,
      date: "2024-04-04",
      source: "The Daily Courier (Prescott)",
      sourceType: "news",
      channel: "media",
      headline: "Dignity Health Yavapai Regional Medical Group/Aetna negotiations for new contract remain stalled",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: false,
      blameDirection: "aetna",
      reachEstimate: "medium",
      notes: "Stalled language implies failure. Aetna positioned as cause of impasse. YRMG framed as community anchor at risk.",
    },
    {
      id: 22,
      date: "2024-04-05",
      source: "Dignity Health (press release)",
      sourceType: "owned",
      channel: "media",
      headline: "Statement from Dignity Health regarding contract negotiations with Aetna",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: false,
      blameDirection: "aetna",
      reachEstimate: "medium",
      notes: "Official termination statement. Key quote: Aetna 'unwilling to agree to responsible terms that help address the unprecedented financial challenges experienced by Dignity Health over the last several years.' Published on multiple Dignity sites (AZ, YRMC, etc.).",
    },
    {
      id: 23,
      date: "2024-04-05",
      source: "KSBY (San Luis Obispo)",
      sourceType: "tv",
      channel: "media",
      headline: "Aetna and Dignity Health fail to work out negotiations for new contract",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Balanced reporting. Quotes Aetna spokesperson Alex Kepnes: 'focused on avoiding unsupportable increases in reimbursement rates.' Central Coast hospitals listed: Arroyo Grande, French Hospital, Marian Regional.",
    },
    {
      id: 24,
      date: "2024-04-05",
      source: "The Daily Courier (Prescott)",
      sourceType: "news",
      channel: "media",
      headline: "Aetna and Dignity Health Yavapai Regional Medical Group contract has expired",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: false,
      blameDirection: "aetna",
      reachEstimate: "medium",
      notes: "Confirms expiration. 300 physicians no longer in Aetna network. Rural healthcare desert framing implicit.",
    },
    {
      id: 25,
      date: "2024-04-06",
      source: "Prescott eNews",
      sourceType: "news",
      channel: "media",
      headline: "Dignity Health Yavapai Regional Medical Group is no longer in the Aetna Network",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: false,
      blameDirection: "aetna",
      reachEstimate: "low",
      notes: "Local online news. Follows Dignity's own framing closely. Continuity of care and emergency access provisions noted.",
    },
    {
      id: 26,
      date: "2024-04-06",
      source: "InsuranceNewsNet",
      sourceType: "news",
      channel: "media",
      headline: "Aetna, Dignity fail to agree on contract. What does that mean?",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Industry trade press. Both sides' positions presented fairly. Syndicated from SLO Tribune. Explains impact on commercial HMO, POS, PPO, Medicare Advantage plans.",
    },
    {
      id: 27,
      date: "2024-04-07",
      source: "Prescott Valley Times",
      sourceType: "news",
      channel: "media",
      headline: "Dignity Health/Aetna negotiations",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: false,
      blameDirection: "aetna",
      reachEstimate: "low",
      notes: "Community paper recap. Follows Dignity press release framing.",
    },
    {
      id: 28,
      date: "2024-04-09",
      source: "Daily Democrat (Woodland)",
      sourceType: "news",
      channel: "media",
      headline: "Dignity Health terminates contracts with two health insurers, leaves patients in 'healthcare limbo'",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: true,
      blameDirection: "aetna",
      reachEstimate: "medium",
      notes: "Consolidates Aetna and Partnership HealthPlan terminations. 'Healthcare limbo' quote in headline. Thousands of Californians in limbo. Out-of-pocket cost hikes detailed. Most widely cited article in the dispute.",
    },
    {
      id: 29,
      date: "2024-04-09",
      source: "Center for Neurology and Spine (blog)",
      sourceType: "other",
      channel: "media",
      headline: "Evolving Healthcare in Arizona: Insights into Aetna and Dignity Health's Contract Negotiations",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "low",
      notes: "Phoenix specialty practice blog. Notes CVS Health acquisition of Aetna in 2018 as context. Neutral analysis of rate negotiation dynamics.",
    },
    {
      id: 30,
      date: "2024-04-21",
      source: "Daily Democrat (Woodland)",
      sourceType: "news",
      channel: "media",
      headline: "Woodland senior loses wife and health coverage within the same month",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: true,
      blameDirection: "aetna",
      reachEstimate: "medium",
      notes: "PATIENT STORY: Bill Findley, 80 years old. Lost his wife and then lost Dignity Health coverage in same month. Refused to leave Dignity Health. Among most emotionally impactful stories in the dispute.",
    },

    // --- Resolution Phase ---
    {
      id: 31,
      date: "2024-04-25",
      source: "Dignity Health (press release)",
      sourceType: "owned",
      channel: "media",
      headline: "Dignity Health and Aetna Reach Agreement",
      frameAdoption: "dignity",
      sentiment: "positive_dignity",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Official resolution announcement. Multi-year contract. Retroactive to April 1. All services since April 1 covered at in-network rates. Quote: 'This is a win for our patients.' Cathy Hughes (Aetna VP) quoted as 'pleased to reach an agreement.'",
    },
    {
      id: 32,
      date: "2024-04-26",
      source: "KSBY (San Luis Obispo)",
      sourceType: "tv",
      channel: "media",
      headline: "Dignity Health, Aetna reach agreement on new contract",
      frameAdoption: "dignity",
      sentiment: "positive_dignity",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Resolution coverage. Retroactive to April 1 emphasized. Central Coast patients can resume in-network care.",
    },
    {
      id: 33,
      date: "2024-04-26",
      source: "KEYT (Santa Barbara)",
      sourceType: "tv",
      channel: "media",
      headline: "Dignity Health reaches new multi-year agreement with Aetna",
      frameAdoption: "dignity",
      sentiment: "positive_dignity",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "News Channel 3-12 coverage. Emphasizes CA, AZ, NV scope. In-network benefit levels retroactive.",
    },
    {
      id: 34,
      date: "2024-04-26",
      source: "Daily Democrat (Woodland)",
      sourceType: "news",
      channel: "media",
      headline: "Dignity Health and Aetna reach agreement, relieve Yolo County patients' worries",
      frameAdoption: "dignity",
      sentiment: "positive_dignity",
      patientStory: true,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Resolution with patient relief angle. Follows up on earlier patient stories. 'Relieve worries' framing credits Dignity for resolution.",
    },
    {
      id: 35,
      date: "2024-04-26",
      source: "Becker's Payer Issues",
      sourceType: "news",
      channel: "media",
      headline: "Aetna, Dignity Health strike deal",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Trade press resolution piece. Quotes Cathy Hughes, Aetna VP and chief network officer, Western/South Central region. Multi-year deal across 3 states.",
    },
    {
      id: 36,
      date: "2024-04-26",
      source: "edhat (Santa Barbara)",
      sourceType: "news",
      channel: "media",
      headline: "Dignity Health and Aetna Reach Agreement",
      frameAdoption: "dignity",
      sentiment: "positive_dignity",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "low",
      notes: "Local news site. Reprints key details from Dignity press release.",
    },
    {
      id: 37,
      date: "2024-04-26",
      source: "The Daily Courier (Prescott)",
      sourceType: "news",
      channel: "media",
      headline: "Dignity Health/Aetna settle on new multi-year contract dated back to April 1",
      frameAdoption: "balanced",
      sentiment: "positive_dignity",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Prescott resolution coverage. 'Standoff came to a close' language. Notes 300 YRMG physicians back in network.",
    },
    {
      id: 38,
      date: "2024-04-26",
      source: "Prescott eNews",
      sourceType: "news",
      channel: "media",
      headline: "Dignity Health and Aetna Reach Agreement",
      frameAdoption: "dignity",
      sentiment: "positive_dignity",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "low",
      notes: "Local Prescott coverage of resolution.",
    },
    {
      id: 39,
      date: "2024-04-26",
      source: "Santa Cruz Sentinel",
      sourceType: "news",
      channel: "media",
      headline: "Dignity Health, Aetna reach partnership agreement",
      frameAdoption: "balanced",
      sentiment: "positive_dignity",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Santa Cruz market coverage. Dignity Health Medical Network of Santa Cruz patients restored.",
    },
    {
      id: 40,
      date: "2024-04-27",
      source: "Red Bluff Daily News",
      sourceType: "news",
      channel: "media",
      headline: "Dignity Health and Aetna reach agreement",
      frameAdoption: "dignity",
      sentiment: "positive_dignity",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "low",
      notes: "Northern CA rural market. Resolution coverage.",
    },
    {
      id: 41,
      date: "2024-04-27",
      source: "Yubanet",
      sourceType: "news",
      channel: "media",
      headline: "Dignity Health and Aetna Reach Agreement",
      frameAdoption: "dignity",
      sentiment: "positive_dignity",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "low",
      notes: "Sierra Nevada foothills community news. Press release reprint.",
    },
    {
      id: 42,
      date: "2024-04-27",
      source: "TPG Online Daily",
      sourceType: "news",
      channel: "media",
      headline: "Dignity Health, Aetna Agree on Contract for In-Network Access",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "low",
      notes: "Industry publication. Factual resolution coverage.",
    },
    {
      id: 43,
      date: "2024-04-29",
      source: "YRMC (press release)",
      sourceType: "owned",
      channel: "media",
      headline: "Dignity Health and Aetna Reach Agreement",
      frameAdoption: "dignity",
      sentiment: "positive_dignity",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "low",
      notes: "YRMC-specific press release. Confirms Yavapai Regional Medical Group back in Aetna network.",
    },
    {
      id: 44,
      date: "2024-04-26",
      source: "Yahoo News / SLO Tribune",
      sourceType: "news",
      channel: "media",
      headline: "Dignity Health, Aetna reach contract agreement -- restoring access for SLO County patients",
      frameAdoption: "dignity",
      sentiment: "positive_dignity",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "high",
      notes: "Syndicated to Yahoo Finance. 'Restoring access' framing credits the deal. Broad reach via Yahoo syndication.",
    },

    // --- Post-Resolution / Op-Eds ---
    {
      id: 45,
      date: "2024-05-06",
      source: "The Aggie (UC Davis)",
      sourceType: "news",
      channel: "media",
      headline: "Recent contract to return healthcare services for over 16,000 Yolo County residents",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "low",
      notes: "Student newspaper. Reports 16,000 Yolo County residents affected. Context on both Aetna and Partnership HealthPlan resolutions.",
    },
    {
      id: 46,
      date: "2024-05-24",
      source: "The Union (Grass Valley)",
      sourceType: "opinion",
      channel: "media",
      headline: "Ideas & Opinions — John Aiello: Dignity Health plays hard-ball with the State of California — 64,000 of its low-income patients end up the real losers",
      frameAdoption: "aetna",
      sentiment: "negative_dignity",
      patientStory: true,
      blameDirection: "dignity",
      reachEstimate: "medium",
      notes: "RARE ANTI-PROVIDER FRAMING. Op-ed by journalist John Aiello (fmr. SF Chronicle). Accuses Dignity of using 64,000 impoverished Medi-Cal patients as 'pawns' to leverage higher reimbursement. Calls it a 'fight about dollars and cents.' Most critical coverage of Dignity in the dispute.",
    },

    // ============================================================
    // SOCIAL MEDIA ENTRIES (8)
    // ============================================================
    {
      id: 47,
      date: "2024-02-08",
      source: "Facebook (AZ local groups)",
      sourceType: "social",
      channel: "social",
      headline: "Arizona patient discussions: BCBSAZ/Dignity termination frustration",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: true,
      blameDirection: "aetna",
      reachEstimate: "low",
      notes: "Maricopa County Facebook groups. Patients sharing insurance company complaints. Blame directed at insurer for breaking access.",
    },
    {
      id: 48,
      date: "2024-03-28",
      source: "Facebook (Yolo County groups)",
      sourceType: "social",
      channel: "social",
      headline: "Yolo County parents anxious about losing Woodland Clinic access",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: true,
      blameDirection: "aetna",
      reachEstimate: "low",
      notes: "Parents sharing concerns about pediatrician and specialist access. Community solidarity tone.",
    },
    {
      id: 49,
      date: "2024-04-05",
      source: "Facebook (Prescott area groups)",
      sourceType: "social",
      channel: "social",
      headline: "Prescott Aetna members react to YRMG going out of network",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: true,
      blameDirection: "aetna",
      reachEstimate: "low",
      notes: "Rural AZ community. Some posts express frustration with both sides; majority blame insurance company. 'Where are we supposed to go?' theme.",
    },
    {
      id: 50,
      date: "2024-04-06",
      source: "News article comment sections",
      sourceType: "social",
      channel: "social",
      headline: "Comment sections on Daily Democrat, Daily Courier articles skew anti-insurer",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: true,
      blameDirection: "aetna",
      reachEstimate: "low",
      notes: "Comment sentiment: 'Greedy insurance companies' theme dominant. Some commenters blame both sides. A few note Dignity's own rate demands.",
    },
    {
      id: 51,
      date: "2024-04-09",
      source: "Facebook (SLO County groups)",
      sourceType: "social",
      channel: "social",
      headline: "Central Coast patients share frustration over Dignity-Aetna breakup",
      frameAdoption: "dignity",
      sentiment: "negative_aetna",
      patientStory: true,
      blameDirection: "aetna",
      reachEstimate: "low",
      notes: "San Luis Obispo, Santa Maria area discussions. French Hospital and Marian Regional patients affected. Some employers mentioned as intermediaries.",
    },
    {
      id: 52,
      date: "2024-04-10",
      source: "X/Twitter",
      sourceType: "social",
      channel: "social",
      headline: "Scattered tweets from patients and local journalists about Dignity-Aetna termination",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "low",
      notes: "Low overall X engagement compared to other healthcare disputes. No viral moments. Local journalists sharing their own articles.",
    },
    {
      id: 53,
      date: "2024-04-12",
      source: "Reddit (r/insurance, r/SLO)",
      sourceType: "social",
      channel: "social",
      headline: "Reddit threads discussing Dignity-Aetna dispute and insurance options",
      frameAdoption: "balanced",
      sentiment: "negative_aetna",
      patientStory: true,
      blameDirection: "aetna",
      reachEstimate: "low",
      notes: "Limited Reddit activity. Posts seeking advice on continuity of care provisions. Some blaming 'corporate healthcare' broadly. Sub-100 upvote threads.",
    },
    {
      id: 54,
      date: "2024-04-26",
      source: "Facebook (multiple CA/AZ groups)",
      sourceType: "social",
      channel: "social",
      headline: "Patient relief shared on social media after Dignity-Aetna resolution",
      frameAdoption: "dignity",
      sentiment: "positive_dignity",
      patientStory: true,
      blameDirection: "both",
      reachEstimate: "low",
      notes: "Resolution celebration. 'Finally!' sentiment. Some residual anger at insurance companies for causing disruption.",
    },

    // ============================================================
    // STAKEHOLDER ENTRIES (15)
    // ============================================================
    {
      id: 55,
      date: "2024-02-06",
      source: "Sen. Sinema office",
      sourceType: "other",
      channel: "stakeholder",
      headline: "Sinema leads bipartisan letter (with Sen. Kelly, Rep. Crane) urging BCBSAZ and Dignity to extend coverage during negotiations",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "high",
      notes: "FEDERAL INTERVENTION. Bipartisan letter from Sens. Sinema (I), Kelly (D), Rep. Crane (R-AZ-02). Urges good-faith negotiations and coverage extension. Focuses on rural Yavapai County patients. High-profile political signal.",
    },
    {
      id: 56,
      date: "2024-02-06",
      source: "GCMAZ (Flagstaff radio)",
      sourceType: "radio",
      channel: "stakeholder",
      headline: "Congressman Eli Crane and both Arizona senators step in to encourage more negotiations between Dignity Health and Blue Cross Blue Shield",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Radio coverage of federal delegation intervention. Notes rural healthcare access as primary concern.",
    },
    {
      id: 57,
      date: "2024-02-08",
      source: "Yavapai County Board of Supervisors",
      sourceType: "other",
      channel: "stakeholder",
      headline: "Yavapai County Board Chairman James Gregory urges both sides to continue negotiations",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "LOCAL GOVERNMENT ACTION. Chairman Gregory: 'This failure to come to an agreement will adversely affect thousands of Yavapai County residents.' Highlights Dignity as 'sole provider of medical services in the region.'",
    },
    {
      id: 58,
      date: "2024-02-09",
      source: "Arizona state legislators",
      sourceType: "other",
      channel: "stakeholder",
      headline: "Local Republican state legislators send letter to YRMC regarding BCBSAZ dispute",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "State-level political pressure. Concerned about constituents relying on Dignity Health services in rural AZ.",
    },
    {
      id: 59,
      date: "2024-03-21",
      source: "Sen. Kelly office",
      sourceType: "other",
      channel: "stakeholder",
      headline: "Kelly, Sinema applaud Dignity Health and Blue Cross Blue Shield Arizona for their agreement to protect patients' access to health care",
      frameAdoption: "balanced",
      sentiment: "positive_dignity",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "high",
      notes: "Senators claim credit for BCBS-AZ resolution. Press release from both Kelly and Sinema offices. Sets expectation for Aetna to follow suit.",
    },
    {
      id: 60,
      date: "2024-03-31",
      source: "Action News Now (Chico-Redding)",
      sourceType: "tv",
      channel: "stakeholder",
      headline: "Contract negotiations end between Dignity Health and Partnership HealthPlan, contract extended with Aetna",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Reports Partnership HealthPlan contract ended while Aetna negotiations got brief extension. 64,000 Partnership members across 5 counties affected.",
    },
    {
      id: 61,
      date: "2024-04-02",
      source: "KRCR-TV (Redding)",
      sourceType: "tv",
      channel: "stakeholder",
      headline: "Dignity enters renegotiations with Partnership Health",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Northern CA market. Reports renegotiation attempt. Concurrent with Aetna deadline pressure.",
    },
    {
      id: 62,
      date: "2024-04-12",
      source: "Yolo County Board of Supervisors",
      sourceType: "other",
      channel: "stakeholder",
      headline: "Yolo County Board of Supervisors urges Dignity Health and Partnership HealthPlan to resolve dispute",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "LOCAL GOVERNMENT ACTION. Formal agenda item. Board sends letter to both organizations. Over 17,000 Yolo County residents affected. Mirrors Yavapai County's earlier action on BCBS-AZ dispute.",
    },
    {
      id: 63,
      date: "2024-04-15",
      source: "Aetna (statement)",
      sourceType: "owned",
      channel: "stakeholder",
      headline: "Aetna statement on Dignity Health contract status",
      frameAdoption: "aetna",
      sentiment: "negative_dignity",
      patientStory: false,
      blameDirection: "dignity",
      reachEstimate: "medium",
      notes: "Aetna spokesperson Alex Kepnes: 'focused on avoiding unsupportable increases in reimbursement rates that would raise costs for our members and plan sponsors.' Positions Aetna as affordability guardian.",
    },
    {
      id: 64,
      date: "2024-05-18",
      source: "Yolo County Board of Supervisors",
      sourceType: "other",
      channel: "stakeholder",
      headline: "Yolo County Board of Supervisors urge Partnership, Dignity Health to use state mediator",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Board escalates to calling for state mediation on the separate Partnership HealthPlan dispute (Aetna already resolved). Shows sustained government pressure on provider-payor disputes.",
    },
    {
      id: 65,
      date: "2024-05-23",
      source: "Davis Enterprise",
      sourceType: "news",
      channel: "stakeholder",
      headline: "Yolo Supes briefed on Dignity Health and Partnership Health Plan's new contract",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "low",
      notes: "Partnership HealthPlan resolution briefing. Board of Supervisors updated. ~32,000 Medi-Cal enrollees restored across 5 counties.",
    },
    {
      id: 66,
      date: "2024-03-01",
      source: "TTG Healthcare Advisors",
      sourceType: "other",
      channel: "stakeholder",
      headline: "AETNA & Dignity Health Termination Effective April 1, 2021 — updated 2024 alert",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "low",
      notes: "Benefits consulting firm. Historical context — notes this is a recurring pattern (also happened in 2021). Alerts employer clients to potential disruptions.",
    },

    // ============================================================
    // EMPLOYER / BENEFITS ENTRIES (5)
    // ============================================================
    {
      id: 67,
      date: "2024-03-20",
      source: "TTG Healthcare Advisors",
      sourceType: "other",
      channel: "employer",
      headline: "Benefits advisory alert: Aetna-Dignity termination impact on employer plans",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "low",
      notes: "Consultant alert to employer clients. Notes commercial HMO, PPO, POS plan disruptions. Advises on continuity of care provisions.",
    },
    {
      id: 68,
      date: "2024-04-01",
      source: "Aetna member communications",
      sourceType: "owned",
      channel: "employer",
      headline: "Aetna notifies employer plan sponsors and members of Dignity Health network status change",
      frameAdoption: "aetna",
      sentiment: "negative_dignity",
      patientStory: false,
      blameDirection: "dignity",
      reachEstimate: "medium",
      notes: "Direct-to-employer and member notifications. Frames Dignity as responsible for out-of-network status. Provides alternative provider options.",
    },
    {
      id: 69,
      date: "2024-04-05",
      source: "Employer benefits departments (inferred)",
      sourceType: "other",
      channel: "employer",
      headline: "Central Coast and Arizona employers field employee questions about Dignity-Aetna disruption",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "low",
      notes: "Inferred from local coverage quoting 'plan sponsors' as affected. No named employer statements publicly available. HR departments likely absorbed inquiry volume.",
    },
    {
      id: 70,
      date: "2024-04-10",
      source: "InsuranceNewsNet (syndicated)",
      sourceType: "news",
      channel: "employer",
      headline: "Fact check: Is Aetna dropping Dignity Health coverage for Central Coast patients?",
      frameAdoption: "balanced",
      sentiment: "neutral",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Syndicated from SLO Tribune. Relevant for employer/benefits audience of InsuranceNewsNet. Clarifies bilateral dispute dynamics.",
    },
    {
      id: 71,
      date: "2024-04-26",
      source: "Aetna (employer notification)",
      sourceType: "owned",
      channel: "employer",
      headline: "Aetna notifies plan sponsors of Dignity Health agreement restoration",
      frameAdoption: "balanced",
      sentiment: "positive_dignity",
      patientStory: false,
      blameDirection: "both",
      reachEstimate: "medium",
      notes: "Resolution notification to employer clients. Retroactive to April 1 — no member cost exposure for the gap period. Key relief for HR/benefits teams.",
    },
  ],
  arguments: {
    payor: [
      { phase: "Early (Feb–Mar 2024)", points: [
        "Aetna spokesperson Alex Kepnes: 'focused on avoiding <strong>unsupportable increases in reimbursement rates</strong>'",
        "Framed Dignity as demanding excessive rate hikes that would raise costs for employers and families",
        "Positioned dispute as Dignity choosing to leave the network, not Aetna refusing to pay",
      ] },
      { phase: "Mid-Dispute (Apr 2024)", points: [
        "Brief, corporate-tone public statements with <strong>no patient voices or community advocates</strong>",
        "Relied on employer notifications framing Dignity as the party disrupting care",
        "Could not match Dignity's local media saturation in rural AZ, CA, and NV markets",
      ] },
      { phase: "Resolution (Apr 2024)", points: [
        "Agreed to <strong>retroactive multi-year contract</strong> effective back to April 1 — no member cost exposure for the gap period",
        "Notified plan sponsors of restoration — resolution suggests Aetna conceded on key rate terms",
      ] },
    ],
    provider: [
      { phase: "Early (Feb–Mar 2024)", points: [
        "Dignity framed BCBS-AZ as refusing to pay <strong>millions in outstanding claims</strong> — set the PR template later used against Aetna",
        "Highlighted 'unprecedented financial challenges' as justification for rate increases",
        "Patient letters warned of April 1 network exit — created patient anxiety that drove local media coverage",
      ] },
      { phase: "Mid-Dispute (Apr 2024)", points: [
        "Aetna 'unwilling to agree to <strong>responsible terms</strong> that help address the unprecedented financial challenges experienced by Dignity Health'",
        "Deployed vulnerable patient stories: Sue Kumar (single mother, rheumatoid arthritis, 10-year-old at risk of losing pediatrician); Nicole Allison (chronic conditions, 3-week notice to find new doctors)",
        "Leveraged simultaneous disputes with BCBS-AZ and Partnership HealthPlan to frame <strong>insurers — not Dignity — as responsible</strong> for disruptions",
      ] },
      { phase: "Resolution (Apr 2024)", points: [
        "Controlled the PR cadence throughout — issuing <strong>press releases at every stage</strong> while Aetna relied on brief statements",
        "Retroactive contract restoration framed as Dignity's successful fight for fair reimbursement",
      ] },
    ],
  },
  timeline: [
    { date: "2024-02-01", type: "newsBreak", label: "News breaks publicly" },
    { date: "2024-04-01", type: "termination", label: "Aetna contract terminates" },
    { date: "2024-04-25", type: "agreement", label: "Agreement reached" },
  ],
};
