// Duke Health vs Aetna — PR War Room Config
// NC State Health Plan dispute · July–October 2025. Resolved October 3, 2025.

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2025-07-23",
    source: "Southpoint Access",
    url: "https://southpointaccess.news/2025/07/23/duke-health-warns-of-potential-split-with-aetna/",
    sourceType: "news",
    channel: "media",
    headline: "Duke Health warns Aetna-insured NC State Health Plan members may lose in-network access",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "First public report of the dispute. Duke frames Aetna as refusing reasonable rate increases — no rate increase in 4 years. Sets the narrative early for the Triangle area.",
  },
  {
    id: 2,
    date: "2025-07-25",
    source: "WRAL",
    url: "https://www.wral.com/story/duke-health-could-drop-aetna-over-contract-dispute-state-employees-among-the-thousands-affected/22097543/",
    sourceType: "tv",
    channel: "media",
    headline: "Duke Health may leave Aetna's NC State Health Plan network — 70K Triangle members at risk",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "WRAL is the dominant Triangle TV station. 70K at-risk members and 22K who list Duke as PCP are key numbers that drive all subsequent coverage. First major broadcast hit.",
  },
  {
    id: 3,
    date: "2025-07-28",
    source: "CBS17",
    sourceType: "tv",
    channel: "media",
    headline: "State employees fear losing Duke Health access amid Aetna contract dispute",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "CBS17 (WNCN) reaches Raleigh-Durham DMA. State employee anxiety framing. Features unnamed patient worried about continuity of care. Triangle-focused coverage.",
  },
  {
    id: 4,
    date: "2025-08-01",
    source: "WRAL",
    url: "https://www.wral.com/story/duke-health-could-drop-aetna-over-contract-dispute-state-employees-among-the-thousands-affected/22097543/",
    sourceType: "tv",
    channel: "media",
    headline: "No rate increase in 4 years: Duke Health says Aetna has refused to negotiate fair contract",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "WRAL follow-up focused on Duke's core argument: no rate increase from Aetna in 4 years while costs have risen. Duke asking for increase 'below inflation.' Sticky talking point.",
  },
  {
    id: 5,
    date: "2025-08-05",
    source: "Carolina Journal",
    url: "https://www.carolinajournal.com/duke-aetna-dispute-could-raise-premiums-cut-coverage-for-ncs-state-employees/",
    sourceType: "news",
    channel: "media",
    headline: "Duke Health-Aetna standoff threatens NC State Health Plan members; SHP inherited $507M deficit",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Conservative-leaning policy outlet. Provides fiscal context: SHP inherited $507M deficit. NC General Assembly gave $150M boost plus $100M additional. Balanced but notes systemic funding shortfalls.",
  },
  {
    id: 6,
    date: "2025-08-10",
    source: "Carolina Journal",
    url: "https://www.carolinajournal.com/duke-aetna-dispute-could-raise-premiums-cut-coverage-for-ncs-state-employees/",
    sourceType: "news",
    channel: "media",
    headline: "Treasurer Briner calls Duke's rate demand 'incredibly tone deaf' — cites $4.3B investments",
    frameAdoption: "aetna",
    sentiment: "negative_duke",
    patientStory: false,
    blameDirection: "duke",
    reachEstimate: "medium",
    notes: "Key Briner offensive. Board member Brian Miller MD reveals Duke's financials: $4.3B investments, $566M operating cash flows, $202M operating income. Briner: 'Duke is more than fine with our existing rates.' Frames Duke as greedy.",
  },
  {
    id: 7,
    date: "2025-08-12",
    source: "The Assembly NC",
    url: "https://www.theassemblync.com/news/health/duke-health-negotiations-aetna/",
    sourceType: "news",
    channel: "media",
    headline: "Inside the Duke-Aetna breakdown: how NC's largest health system and state plan reached an impasse",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "In-depth investigative piece from NC's premier nonprofit newsroom. Examines both sides' financial claims. Notes SHP seeking new TPA by January 2028. The Assembly reaches policy-engaged NC audience.",
  },
  {
    id: 8,
    date: "2025-08-15",
    source: "Carolina Journal",
    url: "https://www.carolinajournal.com/duke-aetna-dispute-could-raise-premiums-cut-coverage-for-ncs-state-employees/",
    sourceType: "news",
    channel: "media",
    headline: "NC General Assembly weighs in on State Health Plan funding — $150M boost approved",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Legislative angle. $150M plus additional $100M from General Assembly to shore up SHP. Context for why Treasurer's office is aggressively pushing back on provider rate increases.",
  },
  {
    id: 9,
    date: "2025-08-18",
    source: "NC Newsline",
    url: "https://ncnewsline.com/2025/09/26/nc-state-health-plan-to-help-members-find-alternatives-to-duke-doctors/",
    sourceType: "news",
    channel: "media",
    headline: "743K State Health Plan members watch Duke-Aetna dispute — out-of-pocket costs could double",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "NC Newsline (nonprofit, nonpartisan). Key data: OOP costs would jump from $5,900 to $11,800 if Duke goes out-of-network. 743K total SHP members gives scale. Patient anxiety framing.",
  },
  {
    id: 10,
    date: "2025-08-20",
    source: "Duke Chronicle",
    url: "https://dukechronicle.com/article/duke-university-health-aetna-insurance-negotiations-in-network-provider-access-patients-concern-20250820",
    sourceType: "news",
    channel: "media",
    headline: "Duke Health contract dispute with Aetna puts state employees, university community on edge",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Campus newspaper. Reaches Duke faculty, staff, students, and alumni — many of whom are SHP members or Duke Health patients. Campus perspective amplifies Duke's narrative internally.",
  },
  {
    id: 11,
    date: "2025-08-20",
    source: "WRAL",
    url: "https://www.wral.com/story/duke-health-could-drop-aetna-over-contract-dispute-state-employees-among-the-thousands-affected/22097543/",
    sourceType: "tv",
    channel: "media",
    headline: "Cancer patient 'devastated' by potential loss of Duke access — out-of-pocket could double",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "CRITICAL PATIENT STORY. Unnamed patient at Duke Cancer Center describes being 'devastated' at prospect of losing access. OOP doubling from $5,900 to $11,800 is concrete and devastating. WRAL's highest-impact segment on this dispute.",
  },
  {
    id: 12,
    date: "2025-08-22",
    source: "Indy Week",
    url: "https://indyweek.com/news/northcarolina/state-health-plan-negotiations-continue-as-deadline-looms/",
    sourceType: "news",
    channel: "media",
    headline: "Duke vs Aetna: state workers caught in the crossfire of a billion-dollar healthcare fight",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Triangle alt-weekly. Progressive readership. 'Billion-dollar fight' framing casts both sides as large institutions squeezing patients. Notes Duke plans to triple revenue to $20B+.",
  },
  {
    id: 13,
    date: "2025-08-25",
    source: "InsuranceNewsNet",
    url: "https://insurancenewsnet.com/oarticle/with-duke-and-aetna-fighting-nc-state-health-plan-lays-out-contingency-plan",
    sourceType: "news",
    channel: "media",
    headline: "Aetna-Duke Health standoff highlights growing payer-provider tensions nationwide",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Insurance trade press. Places Duke-Aetna in national trend context. Notes 1.5M Aetna-insured NC residents gives scale. Balanced — insurance industry audience.",
  },
  {
    id: 14,
    date: "2025-08-28",
    source: "Becker's Hospital Review",
    url: "https://www.beckerspayer.com/contracting/duke-health-aetna-finalize-multi-year-contract/",
    sourceType: "news",
    channel: "media",
    headline: "Duke Health, Aetna contract dispute puts 70K Triangle members at risk — no rate increase in 4 years",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National hospital trade press. '4 years without a rate increase' is the sticky data point. Hospital executive audience pays attention to payer negotiation precedents.",
  },
  {
    id: 15,
    date: "2025-09-01",
    source: "CBS17",
    sourceType: "tv",
    channel: "media",
    headline: "Duke Health patients brace for October deadline — state employees demand answers",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "September opens with renewed urgency as Oct 20 deadline approaches. State employee voices dominate. Patient: 'We are paying attention... prioritize our well-being over profit margins.'",
  },
  {
    id: 16,
    date: "2025-09-05",
    source: "WAVY",
    url: "https://www.wavy.com/news/north-carolina/negotiations-between-duke-health-and-aetna-continue-as-october-deadline-nears/amp/",
    sourceType: "tv",
    channel: "media",
    headline: "Eastern NC state employees worry about Duke Health access as Aetna contract deadline looms",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Hampton Roads/eastern NC TV. Extends geographic reach beyond Triangle. State employees in eastern NC also use Duke Health for specialty care. Regional amplification.",
  },
  {
    id: 17,
    date: "2025-09-09",
    source: "WRAL",
    url: "https://www.wral.com/news/local/duke-health-ceo-resigns-sept-2025/",
    sourceType: "tv",
    channel: "media",
    headline: "Duke Health CEO Craig Albanese departs for Kaiser amid Aetna contract dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CEO departure mid-dispute is significant. Craig Albanese left for Kaiser Permanente Sept 9. Thomas Owens (EVP/COO) takes over as key Duke negotiator. Leadership transition creates uncertainty.",
  },
  {
    id: 18,
    date: "2025-09-10",
    source: "InsuranceNewsNet",
    url: "https://insurancenewsnet.com/oarticle/contingency-plan-for-members-in-place-as-duke-health-state-battle",
    sourceType: "news",
    channel: "media",
    headline: "Duke Health CEO exits as Aetna standoff intensifies — COO Thomas Owens to lead negotiations",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Insurance trade coverage of CEO departure. Notes Owens is EVP/COO. Industry audience tracking leadership dynamics in major payer-provider disputes.",
  },
  {
    id: 19,
    date: "2025-09-12",
    source: "Business NC",
    url: "https://businessnc.com/n-c-health-plan-mulls-duke-health-exit/",
    sourceType: "news",
    channel: "media",
    headline: "Duke Health's $20B growth ambitions collide with state plan reimbursement reality",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "NC business press. Frames Duke's plan to triple revenue to $20B+ as context for why rate increases are sought. Balanced but gives ammunition to both sides. Business audience.",
  },
  {
    id: 20,
    date: "2025-09-15",
    source: "Carolina Journal",
    url: "https://www.carolinajournal.com/duke-aetna-dispute-could-raise-premiums-cut-coverage-for-ncs-state-employees/",
    sourceType: "news",
    channel: "media",
    headline: "Treasurer Briner doubles down: 'greedy' Duke is 'putting profit before people'",
    frameAdoption: "aetna",
    sentiment: "negative_duke",
    patientStory: false,
    blameDirection: "duke",
    reachEstimate: "medium",
    notes: "Briner escalates rhetoric. 'Greedy' and 'putting profit before people' are the Treasurer's sharpest attacks. Unusual for a state official to so directly attack a major health system. Plays to taxpayer-protection framing.",
  },
  {
    id: 21,
    date: "2025-09-18",
    source: "The Center Square",
    url: "https://www.thecentersquare.com/north_carolina/article_ea9c76aa-cdcc-4303-ad9c-8852bdaddca1.html",
    sourceType: "news",
    channel: "media",
    headline: "NC State Health Plan dispute with Duke Health could cost taxpayers if rates rise",
    frameAdoption: "aetna",
    sentiment: "negative_duke",
    patientStory: false,
    blameDirection: "duke",
    reachEstimate: "medium",
    notes: "Conservative fiscal outlet. Taxpayer-cost framing favors Treasurer's position. Notes SHP's $507M inherited deficit. Duke's financials used as evidence they don't need more.",
  },
  {
    id: 22,
    date: "2025-09-20",
    source: "NC Newsline",
    url: "https://ncnewsline.com/2025/09/26/nc-state-health-plan-to-help-members-find-alternatives-to-duke-doctors/",
    sourceType: "news",
    channel: "media",
    headline: "Stage 4 melanoma patient faces OOP doubling if Duke leaves Aetna network — 'putting profit before people'",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "DEVASTATING PATIENT STORY. Unnamed patient with stage 4 metastatic melanoma. OOP from $5,900 to $11,800. Patient quote: '[Duke] putting profit before people' — ironically echoes Briner's language but directed at system that forces patients out of network.",
  },
  {
    id: 23,
    date: "2025-09-22",
    source: "WRAL",
    url: "https://www.wral.com/news/local/duke-health-aetna-standoff-deadline-nears-september-2025/",
    sourceType: "tv",
    channel: "media",
    headline: "With Oct 20 deadline weeks away, Duke and Aetna still at impasse — 22K patients list Duke as PCP",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "WRAL keeps pressure on. 22K PCP patients is the human-scale number. These are not specialty referrals — these are primary care relationships. Disruption would be immediate and personal.",
  },
  {
    id: 24,
    date: "2025-09-23",
    source: "InsuranceNewsNet",
    url: "https://insurancenewsnet.com/oarticle/contingency-plan-for-members-in-place-as-duke-health-state-battle",
    sourceType: "news",
    channel: "media",
    headline: "NC Treasurer releases financial analysis of Duke Health — questions need for rate increases",
    frameAdoption: "aetna",
    sentiment: "negative_duke",
    patientStory: false,
    blameDirection: "duke",
    reachEstimate: "medium",
    notes: "Covers Treasurer's Sept 23 press release. Financial data: $4.3B investments, $566M cash flows, $202M operating income. Briner's strongest data-driven argument against Duke's rate request.",
  },
  {
    id: 25,
    date: "2025-09-25",
    source: "The Assembly NC",
    url: "https://www.theassemblync.com/news/health/duke-health-negotiations-aetna/",
    sourceType: "news",
    channel: "media",
    headline: "Inside the numbers: Duke Health's finances and the State Health Plan's $507M hole",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Deep dive into both sides' finances. Duke's strong balance sheet vs SHP's structural deficit. Notes General Assembly's $250M total infusion. The Assembly provides the most nuanced coverage.",
  },
  {
    id: 26,
    date: "2025-09-26",
    source: "WRAL",
    url: "https://www.wral.com/news/local/duke-health-aetna-standoff-deadline-nears-september-2025/",
    sourceType: "tv",
    channel: "media",
    headline: "Treasurer Briner: 'Duke is more than fine with our existing rates' — releases detailed financial brief",
    frameAdoption: "aetna",
    sentiment: "negative_duke",
    patientStory: false,
    blameDirection: "duke",
    reachEstimate: "high",
    notes: "PEAK MEDIA COVERAGE. Briner's Sept 26 press release gets major WRAL play. 'More than fine with existing rates' becomes the defining Treasurer quote. Coincides with peak search interest (90).",
  },
  {
    id: 27,
    date: "2025-09-28",
    source: "CBS17",
    sourceType: "tv",
    channel: "media",
    headline: "Clock ticking: Duke Health-Aetna dispute enters final weeks before Oct 20 network exit",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "Deadline urgency framing. Oct 20 date repeated. CBS17 audience in Raleigh-Durham is directly affected. 'Clock ticking' creates maximum viewer anxiety.",
  },
  {
    id: 28,
    date: "2025-09-30",
    source: "The Black Chronicle",
    url: "https://blackchronicle.com/healthcare/briner-duke-health-jeopardizing-state-health-plan/",
    sourceType: "news",
    channel: "media",
    headline: "Duke Health-Aetna dispute threatens care access for NC Black communities reliant on state plan",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Black press coverage. State employees skew disproportionately minority. Duke Health is a major provider for Black communities in Durham. Health equity angle adds moral dimension to dispute.",
  },
  {
    id: 29,
    date: "2025-10-01",
    source: "WRAL",
    url: "https://www.wral.com/news/local/duke-health-aetna-agreement-october-2025/",
    sourceType: "tv",
    channel: "media",
    headline: "Last-minute negotiations underway between Duke Health and Aetna — resolution possible",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Pre-resolution reporting. WRAL signals deal is near. Thomas Owens leading Duke's side after Albanese departure.",
  },
  {
    id: 30,
    date: "2025-10-03",
    source: "WRAL",
    url: "https://www.wral.com/news/local/duke-health-aetna-agreement-october-2025/",
    sourceType: "tv",
    channel: "media",
    headline: "Duke Health and Aetna reach agreement on NC State Health Plan — 17 days before deadline",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "RESOLUTION COVERAGE. Deal reached Oct 3, 17 days before Oct 20 deadline. Agreement won't force 2027 premium increases. WRAL breaks resolution. Peak search interest (100) coincides.",
  },
  {
    id: 31,
    date: "2025-10-03",
    source: "CBS17",
    sourceType: "tv",
    channel: "media",
    headline: "Duke Health remains in-network for State Health Plan — deal reached with Aetna",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CBS17 resolution coverage. 'Remains in-network' is relief framing. Notes agreement won't force 2027 premium increases — key talking point for both sides.",
  },
  {
    id: 32,
    date: "2025-10-03",
    source: "Duke Chronicle",
    url: "https://dukechronicle.com/article/duke-university-aetna-health-insurance-reach-agreement-in-network-provider-20251003",
    sourceType: "news",
    channel: "media",
    headline: "Duke Health resolves Aetna State Health Plan dispute — campus community breathes easier",
    frameAdoption: "duke",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Campus resolution coverage. Relief framing for Duke employees and students on SHP. Notes ~2,800 patients were in continuity of care provisions.",
  },
  {
    id: 33,
    date: "2025-10-03",
    source: "Becker's Hospital Review",
    url: "https://www.beckerspayer.com/contracting/duke-health-aetna-finalize-multi-year-contract/",
    sourceType: "news",
    channel: "media",
    headline: "Duke Health, Aetna resolve NC State Health Plan contract dispute ahead of deadline",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National trade press resolution. Balanced. Notes neither side disclosed rate terms. Hospital executive audience. Precedent tracking for other payer-provider negotiations.",
  },
  {
    id: 34,
    date: "2025-10-05",
    source: "InsuranceNewsNet",
    url: "https://insurancenewsnet.com/oarticle/contingency-plan-for-members-in-place-as-duke-health-state-battle",
    sourceType: "news",
    channel: "media",
    headline: "Aetna, Duke Health settle NC dispute — agreement avoids 2027 premium hikes",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Insurance trade resolution coverage. 'Avoids 2027 premium hikes' is the Treasurer's key win — politically important for SHP sustainability narrative.",
  },
  // === DUKE OWNED MEDIA ===
  {
    id: 35,
    date: "2025-07-25",
    source: "DukeHealth.org/aetna",
    url: "https://www.dukehealth.org/aetna",
    sourceType: "owned",
    channel: "media",
    headline: "Duke Health creates dedicated page for Aetna/SHP patients — 'no rate increase in 4 years'",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Patient-facing page explaining dispute. Core claim: Aetna has not increased rates in 4 years. Duke asking for increase 'below inflation.' Directs patients to contact Treasurer's office. Strategic patient mobilization.",
  },
  {
    id: 36,
    date: "2025-08-20",
    source: "Duke Today",
    url: "https://today.duke.edu/2025/07/update-duke-health-negotiations-aetna",
    sourceType: "owned",
    channel: "media",
    headline: "Duke Today: Duke Health committed to NC State Health Plan patients amid contract discussions",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Duke University's official news outlet. Reaches entire Duke community. 'Committed to patients' framing positions Duke as patient-first while Aetna blocks fair rates.",
  },
  {
    id: 37,
    date: "2025-10-03",
    source: "Duke Today",
    url: "https://today.duke.edu/2025/07/update-duke-health-negotiations-aetna",
    sourceType: "owned",
    channel: "media",
    headline: "Duke Health announces resolution with Aetna — Thomas Owens: 'patients come first'",
    frameAdoption: "duke",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution announcement via Duke's channel. Thomas Owens (EVP/COO) leads messaging after Albanese departure. 'Patients come first' claims credit for resolution.",
  },
  // === GOVERNMENT / TREASURER OWNED ===
  {
    id: 38,
    date: "2025-09-23",
    source: "NC Treasurer (press release)",
    url: "https://www.nctreasurer.gov/news/press-releases/2025/09/23/treasurer-brad-briner-updates-state-health-plan-members-dukeaetna-negotiations",
    sourceType: "owned",
    channel: "media",
    headline: "Treasurer Briner releases Duke Health financial analysis — $4.3B investments, $566M cash flows",
    frameAdoption: "aetna",
    sentiment: "negative_duke",
    patientStory: false,
    blameDirection: "duke",
    reachEstimate: "high",
    notes: "FIRST MAJOR TREASURER OFFENSIVE. Board member Brian Miller MD provides data: $4.3B investments, $566M operating cash flows, $202M operating income. Briner: Duke's rate demands 'incredibly tone deaf.' Official government channel gives data credibility.",
  },
  {
    id: 39,
    date: "2025-09-26",
    source: "NC Treasurer (press release)",
    url: "https://www.nctreasurer.gov/news/press-releases/2025/09/26/state-health-plan-board-trustees-takes-action-ensure-continuity-care",
    sourceType: "owned",
    channel: "media",
    headline: "Treasurer Briner: 'Duke is more than fine with our existing rates' — second financial brief",
    frameAdoption: "aetna",
    sentiment: "negative_duke",
    patientStory: false,
    blameDirection: "duke",
    reachEstimate: "high",
    notes: "Second press release in 3 days. Escalation strategy. 'More than fine' is the quotable line that gets picked up by every outlet. Coincides with peak search interest.",
  },
  {
    id: 40,
    date: "2025-10-03",
    source: "NC Treasurer (press release)",
    url: "https://www.nctreasurer.gov/news/press-releases/2025/10/03/state-health-plan-members-win-duke-healthaetna-agreement",
    sourceType: "owned",
    channel: "media",
    headline: "Treasurer announces Duke-Aetna resolution — agreement won't force 2027 premium increases",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution announcement. Key: 'won't force 2027 premium increases' is the Treasurer's victory claim. Frames the deal as protecting taxpayers while maintaining access.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 41,
    date: "2025-08-01",
    source: "X/Twitter (state employee posts)",
    sourceType: "social",
    channel: "social",
    headline: "NC state employees flood social media with concerns about Duke-Aetna dispute — #NCStateHealthPlan",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "State employees organize online. Cancer patients, expectant mothers, chronic condition patients all share fears. 743K SHP member base generates significant organic social volume.",
  },
  {
    id: 42,
    date: "2025-08-25",
    source: "Facebook (NC state employee groups)",
    sourceType: "social",
    channel: "social",
    headline: "NC state employee Facebook groups amplify Duke-Aetna anxiety — sharing OOP doubling scenarios",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Facebook groups for NC state employees share OOP cost scenarios ($5,900 to $11,800). Concrete dollar amounts drive engagement. Facebook skews older — matches SHP demographic.",
  },
  {
    id: 43,
    date: "2025-09-20",
    source: "Social media (patient advocacy)",
    sourceType: "social",
    channel: "social",
    headline: "Cancer patients at Duke share stories online — 'devastated' and 'scared' about losing access",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Cancer patient stories go viral in NC social media. Stage 4 melanoma patient story widely shared. ~2,800 continuity of care patients create large sympathetic base.",
  },
  {
    id: 44,
    date: "2025-09-26",
    source: "X/Twitter (political commentary)",
    sourceType: "social",
    channel: "social",
    headline: "Treasurer Briner's 'greedy' Duke comments spark debate — taxpayer advocates vs healthcare access voices",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Political social media divides on this dispute. Fiscal conservatives back Briner's taxpayer framing. Healthcare advocates focus on patient access. Unusual bipartisan engagement.",
  },
  {
    id: 45,
    date: "2025-10-03",
    source: "Social media (resolution reaction)",
    sourceType: "social",
    channel: "social",
    headline: "NC state employees express relief as Duke-Aetna deal announced — 'finally some good news'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution relief. High engagement. Both sides claim victory in comments. Patient access preserved. No premium increase for 2027.",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 46,
    date: "2025-08-15",
    source: "SEANC (State Employees Association of NC)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "SEANC demands transparency in Duke-Aetna negotiations — 'members deserve to know'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "State employee union weighs in. SEANC does not take sides but demands transparency from both Duke and the Treasurer's office. Represents large organized constituency. Adds political pressure.",
  },
  {
    id: 47,
    date: "2025-09-23",
    source: "Treasurer Brad Briner",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Briner: Duke's demands 'incredibly tone deaf' given $4.3B in investments — 'greedy'",
    frameAdoption: "aetna",
    sentiment: "negative_duke",
    patientStory: false,
    blameDirection: "duke",
    reachEstimate: "high",
    notes: "KEY ANTAGONIST. Briner is the most quotable voice against Duke. 'Incredibly tone deaf,' 'greedy,' 'more than fine with existing rates.' Unusual for elected official to so aggressively attack major employer/provider. High credibility with taxpayer-focused audience.",
  },
  {
    id: 48,
    date: "2025-09-23",
    source: "Board member Brian Miller MD",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "SHP Board member reveals Duke financials: $4.3B investments, $566M cash flows, $202M operating income",
    frameAdoption: "aetna",
    sentiment: "negative_duke",
    patientStory: false,
    blameDirection: "duke",
    reachEstimate: "high",
    notes: "MD credential lends authority to financial argument. $4.3B investments is the attention-getting number. Frames Duke as wealthy system that doesn't need rate increases. Data-driven counter to Duke's 'below inflation' ask.",
  },
  {
    id: 49,
    date: "2025-09-25",
    source: "NC General Assembly context",
    sourceType: "news",
    channel: "stakeholder",
    headline: "NC General Assembly approved $150M boost + $100M additional for State Health Plan stabilization",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Legislative context. $250M total state investment in SHP. Creates political imperative to show fiscal discipline — Treasurer can't approve big rate increases after getting legislative bailout.",
  },
  {
    id: 50,
    date: "2025-10-03",
    source: "Thomas Owens, EVP/COO, Duke Health",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Owens leads Duke to resolution after Albanese departure — 'commitment to NC patients'",
    frameAdoption: "duke",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Owens stepped in after CEO Albanese left for Kaiser Sept 9. Handled final negotiations and resolution messaging. 'Commitment to NC patients' is Duke's resolution frame.",
  },
  {
    id: 51,
    date: "2025-09-09",
    source: "Craig Albanese departure (Kaiser)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Duke Health CEO Craig Albanese departs for Kaiser Permanente — leadership vacuum mid-dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "CEO departure mid-negotiation is unusual. Creates narrative of leadership instability at Duke. Briner side can frame as 'even the CEO is leaving.' Owens stepped in effectively.",
  },
  {
    id: 52,
    date: "2025-08-30",
    source: "NC SHP website",
    url: "https://www.shpnc.gov/blog/2025/09/30/aetnaduke-updates",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "State Health Plan posts member FAQ on Duke-Aetna dispute — outlines continuity of care protections",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Official SHP member communication. Notes ~2,800 members in active continuity of care with Duke. FAQ format addresses member anxiety. Neutral government tone.",
  },
  {
    id: 53,
    date: "2025-09-28",
    source: "SHP seeking new TPA",
    sourceType: "news",
    channel: "stakeholder",
    headline: "NC State Health Plan seeking new third-party administrator by January 2028 — Aetna contract sunset",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Structural context: SHP is moving away from Aetna as TPA by Jan 2028 regardless. This dispute is partly about the transition period. New TPA selection adds complexity to all provider negotiations.",
  },
  // === DUKE RADIO/CAMPAIGN ===
  {
    id: 54,
    date: "2025-08-10",
    source: "Duke Health (radio ads)",
    sourceType: "radio",
    channel: "media",
    headline: "Duke Health launches radio ad campaign urging patients to call Aetna and demand in-network access",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "AGGRESSIVE PUBLIC CAMPAIGN. Duke ran radio ads across Triangle market urging patients to call Aetna (number on back of card) and demand in-network access. Briner called this a 'very public high-pressure tactic.' Unusual for a health system to weaponize patient outreach this directly.",
  },
  {
    id: 55,
    date: "2025-08-10",
    source: "Duke Health (patient letters)",
    sourceType: "owned",
    channel: "media",
    headline: "Duke Health sends direct letters to Aetna patients urging them to contact Aetna — Briner calls it 'scare tactics'",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "Direct mail to Aetna patients. Briner characterized Duke's letter campaign as intended to 'scare' patients into arguing on the health system's behalf. Patient mobilization tactic that backfired with Treasurer's office but may have worked with patients themselves.",
  },
  // === ADDITIONAL MEDIA ===
  {
    id: 56,
    date: "2025-08-20",
    source: "Duke Chronicle",
    url: "https://dukechronicle.com/article/duke-university-health-aetna-insurance-negotiations-in-network-provider-access-patients-concern-20250820",
    sourceType: "news",
    channel: "media",
    headline: "Elizabeth Taylor, Duke Cancer Center patient: 'I would be devastated' if Aetna goes out of network",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "NAMED PATIENT STORY. Elizabeth Taylor, Duke Health Cancer Center patient covered by Aetna, publicly stated she would be 'devastated' by loss of in-network access. Named patient quotes are powerful for Duke's narrative.",
  },
  {
    id: 57,
    date: "2025-08-20",
    source: "Duke Chronicle",
    url: "https://dukechronicle.com/article/duke-university-health-aetna-insurance-negotiations-in-network-provider-access-patients-concern-20250820",
    sourceType: "news",
    channel: "media",
    headline: "Patient pushback on Duke: 'They're not hurting for money — putting profit before people'",
    frameAdoption: "aetna",
    sentiment: "negative_duke",
    patientStory: true,
    blameDirection: "duke",
    reachEstimate: "low",
    notes: "COUNTER-NARRATIVE PATIENT. Rare patient voice blaming Duke: '[Duke is] not hurting for money. [It's] putting profit before people and that's a huge problem.' Demonstrates dispute was genuinely two-sided even among patients. Echoes Briner's 'greedy' framing.",
  },
  {
    id: 58,
    date: "2025-09-26",
    source: "WRAL",
    url: "https://www.wral.com/story/nc-officials-begin-process-to-help-thousands-of-state-workers-switch-doctors-as-duke-negotiations-sour/22175350/",
    sourceType: "tv",
    channel: "media",
    headline: "NC officials begin process to help thousands of state workers switch doctors as Duke negotiations sour",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "State preparing contingency plans. Officials voted to approve a resolution formally starting work to identify new providers for at-risk members. Signal of how seriously the state was treating the possibility of no deal.",
  },
  {
    id: 59,
    date: "2025-09-15",
    source: "WRAL",
    url: "https://www.wral.com/story/state-workers-could-face-another-health-premium-hike-depending-on-duke-aetna-contract-fight/22161874/",
    sourceType: "tv",
    channel: "media",
    headline: "State workers could face another health premium hike depending on Duke-Aetna contract fight",
    frameAdoption: "aetna",
    sentiment: "negative_duke",
    patientStory: false,
    blameDirection: "duke",
    reachEstimate: "high",
    notes: "Premium hike angle is Briner's strongest public argument. After SHP Board already approved 2026 premium increases due to $507M shortfall, another increase driven by Duke rate hikes would be politically devastating.",
  },
  {
    id: 60,
    date: "2025-09-23",
    source: "Carolina Journal",
    url: "https://www.carolinajournal.com/duke-health-requested-aetna-rate-hike-would-have-small-impact-on-state-workers/",
    sourceType: "news",
    channel: "media",
    headline: "Duke Health responds: requested rate hike would have 'small impact' on state workers' premiums",
    frameAdoption: "duke",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Duke's counter to Briner's premium-hike narrative. Claims 6-10% of SHP members use Duke services, so rate increase impact would be small. Attempts to defuse the premium-anxiety argument. Data-driven rebuttal.",
  },
  {
    id: 61,
    date: "2025-10-03",
    source: "HealthLeaders Media",
    url: "https://www.healthleadersmedia.com/payer/duke-health-aetna-reach-agreement-keep-providers-network",
    sourceType: "news",
    channel: "media",
    headline: "Duke Health, Aetna reach agreement to keep providers in-network",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National healthcare executive trade press. Resolution coverage. Balanced framing. Notes multi-year agreement covers Aetna Commercial and Medicare Advantage plans. C-suite audience tracking payer-provider deal precedents.",
  },
  {
    id: 62,
    date: "2025-10-03",
    source: "WNCT",
    url: "https://www.wnct.com/news/nc-state-health-plan-relieved-as-duke-health-aetna-prioritizes-care/",
    sourceType: "tv",
    channel: "media",
    headline: "NC State Health Plan relieved as Duke Health/Aetna prioritizes care",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Eastern NC TV coverage. 'Relieved' and 'prioritizes care' is resolution framing. Reaches eastern NC state employees who use Duke for specialty referrals. Geographic reach beyond Triangle.",
  },
  {
    id: 63,
    date: "2025-10-03",
    source: "NC Newsline",
    url: "https://ncnewsline.com/briefs/duke-aetna-contract-nc-state-employees/",
    sourceType: "news",
    channel: "media",
    headline: "Duke and Aetna have a new contract, relieving pressure on state employees to find new doctors",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Nonprofit nonpartisan outlet. 'Relieving pressure' captures the emotional release for 743K SHP members. Notes terms were not disclosed.",
  },
  {
    id: 64,
    date: "2025-10-05",
    source: "Carolina Coast Online",
    url: "https://www.carolinacoastonline.com/regional/article_910b5f31-57bd-472d-8754-931a13b8dd5c.html",
    sourceType: "news",
    channel: "media",
    headline: "Duke Health, Aetna announce new agreement — coastal NC coverage via syndication",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Syndicated resolution coverage reaching coastal NC. State employees in coastal communities also affected. Geographic reach demonstrates statewide nature of dispute.",
  },
  {
    id: 65,
    date: "2025-10-03",
    source: "The Assembly NC",
    url: "https://www.theassemblync.com/health/duke-health-aetna-contract/",
    sourceType: "news",
    channel: "media",
    headline: "Duke Health and Aetna reach contract agreement — months of escalating exchanges conclude",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "The Assembly's resolution coverage. Reporter Johanna F. Still provided the most comprehensive narrative arc. 'Summer of escalating exchanges' captures the dispute's intensity. Notes confidential deal terms.",
  },
  {
    id: 66,
    date: "2025-10-03",
    source: "Carolina Journal",
    url: "https://www.carolinajournal.com/duke-health-aetna-announce-new-agreement/",
    sourceType: "news",
    channel: "media",
    headline: "Duke Health, Aetna announce new agreement — contingency plan no longer needed",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Carolina Journal resolution coverage. Notes the contingency plan approved by SHP Board of Trustees is no longer needed. Conservative policy audience.",
  },
  // === AETNA OWNED MEDIA ===
  {
    id: 67,
    date: "2025-08-05",
    source: "Aetna/CVS Health (public statement)",
    sourceType: "owned",
    channel: "media",
    headline: "Aetna: NC already has among highest healthcare costs in the nation — Duke demanding unreasonable rate increase",
    frameAdoption: "aetna",
    sentiment: "negative_duke",
    patientStory: false,
    blameDirection: "duke",
    reachEstimate: "medium",
    notes: "Aetna's core public argument. NC healthcare costs already among highest nationally. Duke's request to raise costs further is 'unreasonable.' Corporate defensive tone. No patient voices.",
  },
  {
    id: 68,
    date: "2025-10-03",
    source: "Duke Health Corporate (press release)",
    url: "https://corporate.dukehealth.org/news/duke-health-and-aetna-extend-partnership-new-multi-year-agreement",
    sourceType: "owned",
    channel: "media",
    headline: "Duke Health and Aetna extend partnership with new multi-year agreement — Thomas Owens statement",
    frameAdoption: "duke",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Official corporate press release. Thomas Owens (EVP/COO) statement. Multi-year agreement covers Aetna Commercial and Medicare Advantage. Notes focus on 'better outcomes and efficiency.' Victory framing for Duke.",
  },
  // === ADDITIONAL STAKEHOLDER ===
  {
    id: 69,
    date: "2025-09-26",
    source: "NC SHP Board of Trustees",
    sourceType: "news",
    channel: "stakeholder",
    headline: "SHP Board of Trustees votes to approve contingency resolution — 'white-glove service' for affected members",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "FORMAL GOVERNMENT ACTION. Board approved resolution directing staff to prepare contingency plans. 'White-glove service' to help ~2,800 continuity-of-care members find new providers. Official vote signals seriousness of potential network exit.",
  },
  {
    id: 70,
    date: "2025-09-30",
    source: "NC SHP website (Aetna/Duke Updates)",
    url: "https://www.shpnc.gov/blog/2025/09/30/aetnaduke-updates",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "State Health Plan publishes dedicated Aetna/Duke updates page — timeline and member resources",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Official SHP member communication hub. Timeline of dispute, member FAQ, and contingency resources. Posted Sept 30, 20 days before deadline. Government neutral tone addresses member anxiety.",
  },
  {
    id: 71,
    date: "2025-09-20",
    source: "SEANC Podcast (The SEANC View)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "SEANC View Podcast: Duke-Aetna standoff exposes need for transparency in SHP contracts",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Jonathan Owens and Ardis Watkins host. Unpacks how secret hospital reimbursement rates affect SHP members and push up premiums. Urges members to demand transparency from Treasurer and lawmakers. Organized labor channel reaching state employees directly.",
  },
  {
    id: 72,
    date: "2025-10-03",
    source: "Treasurer Brad Briner (resolution statement)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Briner: 'I appreciate the steps Duke took to keep costs down' — resolution signals mutual concession",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Briner's conciliatory resolution tone contrasts sharply with his 'greedy' attacks weeks earlier. 'Keep costs down' implies Duke made concessions. Both sides claim victory. Political resolution framing.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 73,
    date: "2025-08-22",
    source: "UNC HR page",
    sourceType: "owned",
    channel: "employer",
    headline: "UNC system HR notifies employees of Duke-Aetna dispute — advises checking provider status",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "UNC system is a major SHP employer. HR advisory reaches tens of thousands of UNC employees who may use Duke Health. Factual, neutral tone. Signals employer-level concern.",
  },
  {
    id: 74,
    date: "2025-09-05",
    source: "Appalachian State HR",
    sourceType: "owned",
    channel: "employer",
    headline: "Appalachian State HR advises employees on Duke-Aetna dispute — SHP coverage implications",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Even western NC state universities issuing advisories despite geographic distance from Duke. Shows statewide impact of dispute on SHP employers. App State HR reaching faculty and staff.",
  },
  {
    id: 75,
    date: "2025-09-15",
    source: "NC state agency HR communications",
    sourceType: "owned",
    channel: "employer",
    headline: "Multiple NC state agencies issue HR bulletins on Duke-Aetna dispute — open enrollment implications",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Statewide HR communications across agencies. Dispute coincides with open enrollment planning. State employees considering switching plans to maintain Duke access. Administrative burden on HR offices.",
  },
  {
    id: 76,
    date: "2025-09-26",
    source: "NC SHP Board contingency plan (employer impact)",
    sourceType: "news",
    channel: "employer",
    headline: "SHP Board approves contingency: personalized assistance for every member relying on Duke for care",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Employer-facing dimension of Board vote. Contingency plan included personalized outreach to help each affected member find new high-quality providers. ~2,800 in active continuity of care. Administrative cost of contingency planning adds pressure for resolution.",
  },
  {
    id: 77,
    date: "2025-09-28",
    source: "NC K-12 school district HR",
    sourceType: "owned",
    channel: "employer",
    headline: "NC public school teachers receive Duke-Aetna dispute notices — largest SHP employer group affected",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Teachers are the single largest SHP demographic. School district HR offices across NC distributed dispute information. Teacher anxiety creates political pressure on Treasurer and legislators. Politically sympathetic workforce.",
  },
];

const LABELS = {
  frameAdoption: { duke: "Duke Frame", aetna: "Aetna/Treasurer Frame", balanced: "Balanced" },
  sentiment: {
    negative_aetna: "Anti-Aetna/SHP",
    negative_duke: "Anti-Duke",
    neutral: "Neutral",
    positive_aetna: "Pro-Aetna/SHP",
    positive_duke: "Pro-Duke",
  },
  blameDirection: { aetna: "Blames Aetna/SHP", duke: "Blames Duke", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — Regional authority TV (1.5)
  "WRAL": 1.5, "CBS17": 1.5, "WAVY": 1.2,
  // Tier 2 — Policy/investigative press (1.2)
  "The Assembly NC": 1.2, "Carolina Journal": 1.2, "NC Newsline": 1.2,
  "Business NC": 1.2, "Indy Week": 1.0,
  // Tier 3 — Trade press (1.0)
  "Becker's Hospital Review": 1.0, "InsuranceNewsNet": 1.0,
  // Tier 4 — Campus/community press (0.8)
  "Duke Chronicle": 0.8, "Southpoint Access": 0.8,
  "The Black Chronicle": 1.0, "The Center Square": 1.0,
  // Tier 5 — Organic social (0.7)
  "X/Twitter (state employee posts)": 0.7, "Facebook (NC state employee groups)": 0.7,
  "Social media (patient advocacy)": 0.7, "X/Twitter (political commentary)": 0.7,
  "Social media (resolution reaction)": 0.7,
  // Tier 6 — Owned/party media (0.3)
  "DukeHealth.org/aetna": 0.3, "Duke Today": 0.3,
  "NC Treasurer (press release)": 0.3, "NC SHP website": 0.3,
  "UNC HR page": 0.3, "Appalachian State HR": 0.3,
  "NC state agency HR communications": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "Treasurer Brad Briner": 1.3, "Board member Brian Miller MD": 1.3,
  "SEANC (State Employees Association of NC)": 1.3,
  "Thomas Owens, EVP/COO, Duke Health": 1.3,
  "Craig Albanese departure (Kaiser)": 1.3,
  "NC General Assembly context": 1.3,
  "SHP seeking new TPA": 1.3,
};

const SEARCH_TRENDS = [
  { week: "2025-07-01", interest: 5 }, { week: "2025-07-07", interest: 5 },
  { week: "2025-07-14", interest: 5 }, { week: "2025-07-21", interest: 40 },
  { week: "2025-07-28", interest: 30 }, { week: "2025-08-04", interest: 30 },
  { week: "2025-08-11", interest: 35 }, { week: "2025-08-18", interest: 50 },
  { week: "2025-08-25", interest: 35 }, { week: "2025-09-01", interest: 35 },
  { week: "2025-09-08", interest: 40 }, { week: "2025-09-15", interest: 55 },
  { week: "2025-09-22", interest: 75 }, { week: "2025-09-29", interest: 90 },
  { week: "2025-10-06", interest: 100 }, { week: "2025-10-13", interest: 25 },
  { week: "2025-10-20", interest: 10 }, { week: "2025-10-27", interest: 5 },
];

export default {
  active: false,
  // Identity
  providerKey: "duke",
  payorKey: "aetna",
  providerName: "Duke Health",
  payorName: "Aetna",
  providerShort: "Duke",
  payorShort: "Aetna",
  navShort: "Duke v. Aetna",
  title: "Duke Health vs Aetna",
  subtitle: "NC State Health Plan dispute \u00b7 Resolved October 3, 2025",
  gradientId: "dukeaetna",

  // Dates
  monitorStart: "July 1, 2025",
  monitorEnd: "October 31, 2025",
  disputePublicDate: "2025-07-23",

  // Colors
  colors: {
    providerColor: "#003366",
    payorColor: "#7B2D8E",
    neutral: "#64748B",
    accent: "#003366",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#003366", "#4A4A78", "#7B2D8E"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"duke health aetna state health plan" \u00b7 weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.42,
    nationalMedian: 1.0,
    networkComplaints: 892,
    priorYearComplaints: 614,
    regulatorAction: "NC Treasurer Brad Briner publicly attacked Duke's rate demands. No formal NCDOI investigation opened. NC General Assembly provided $250M in SHP funding. SHP seeking new TPA by January 2028.",
    signalRead: "Aetna's complaint index is moderately elevated (1.42x median). The NC State Health Plan's inherited $507M deficit and upcoming TPA transition create structural tension with all providers. Treasurer Briner's aggressive public posture against Duke is unusual and reflects political dynamics unique to government-run plans.",
  },

  talkingPoints: {
    provider: [
      { name: "No rate increase in 4 years", keywords: ["no rate increase", "4 year", "four year", "refused to negotiate"] },
      { name: "Below-inflation request", keywords: ["below inflation", "below.inflation", "small impact.*premium"] },
      { name: "70K members / 22K PCP at risk", keywords: ["70,?000", "70K", "22,?000", "22K", "Triangle member", "list Duke as.*PCP"] },
      { name: "Cancer patient stories", keywords: ["cancer", "melanoma", "devastated", "Elizabeth Taylor", "Duke Cancer Center"] },
      { name: "State employee access", keywords: ["state employee", "state worker", "public school teacher", "university", "743K", "NC State Health Plan"] },
      { name: "OOP cost doubling ($5,900-$11,800)", keywords: ["\\$5,?900", "\\$11,?800", "out.of.pocket.*double", "OOP.*double"] },
      { name: "CEO departure / leadership", keywords: ["Albanese", "depart.*Kaiser", "Owens", "leadership.*vacuum", "COO"] },
      { name: "Radio ad / patient mobilization", keywords: ["radio ad", "direct letter", "call Aetna", "scare tactic", "urging patient"] },
    ],
    payor: [
      { name: "Duke is greedy / tone deaf", keywords: ["greedy", "tone deaf", "incredibly tone deaf", "profit before people"] },
      { name: "Duke's $4.3B investments", keywords: ["\\$4\\.3B", "\\$4\\.3 billion", "\\$566M", "\\$202M", "operating income", "strong.*balance sheet"] },
      { name: "SHP $507M deficit", keywords: ["\\$507M", "507.*deficit", "inherited deficit", "underfunded"] },
      { name: "Taxpayer protection", keywords: ["taxpayer", "premium.*hike", "cost.*taxpayer", "fiscal.*conservative"] },
      { name: "Treasurer Briner attacks", keywords: ["Briner", "Treasurer", "more than fine", "existing rates"] },
      { name: "$150M+ legislative funding", keywords: ["\\$150M", "\\$100M", "General Assembly", "250.*million", "SHP funding"] },
      { name: "NC highest healthcare costs", keywords: ["highest.*cost.*nation", "unreasonable.*rate", "Aetna.*cost"] },
    ],
  },

  // Executive summary
  executiveSummary: {
    statement: "The dispute resolved October 3, 2025 — 17 days before the October 20 network exit deadline. The agreement won't force 2027 premium increases, giving both sides a political win.",
    keyMessages: [
      "Duke's 'no rate increase in 4 years' is the stickiest talking point — frames Aetna/SHP as systematically underpaying while costs rise.",
      "Treasurer Briner's aggressive public attacks ('greedy,' 'incredibly tone deaf') made this dispute uniquely two-sided — most payer-provider disputes don't feature an elected official as active combatant.",
      "The $5,900-to-$11,800 OOP doubling scenario gave patients a concrete, devastating number that drove media and social engagement.",
      "CEO Albanese's mid-dispute departure for Kaiser created a leadership narrative that Briner's side could exploit, but Owens handled the resolution effectively.",
    ],
    marcomm: [
      "<strong>This dispute was uniquely two-sided.</strong> Unlike most payer-provider disputes where the insurer absorbs blame, Treasurer Briner's aggressive public posture and Duke's strong financials ($4.3B investments) created a genuine two-front narrative war. Neither side had a clear PR advantage.",
      "<strong>Government plan dynamics change the playbook.</strong> The Treasurer is an elected official with public accountability obligations that private insurers don't have. Briner's willingness to publicly attack Duke reflects political incentives unique to government-run plans.",
      "<strong>The 'below inflation' framing was Duke's strongest asset.</strong> No rate increase in 4 years while asking for 'below inflation' is a simple, sticky message that resonates universally. It neutralizes the 'greedy hospital' counter-narrative.",
      "<strong>Patient stories cut both ways.</strong> While cancer patients fearing loss of access favor Duke, the Treasurer's framing of Duke as 'putting profit before people' redirected patient anger. The 'profit before people' quote originated from patients themselves.",
    ],
  },
  channelTakeaways: {
    media: [
      "WRAL dominated coverage with 5+ segments — the most influential single outlet for Triangle-area perception of this dispute.",
      "Carolina Journal provided the strongest Treasurer-side coverage, amplifying Briner's financial arguments to a conservative policy audience.",
      "The Assembly NC delivered the most balanced, in-depth investigative coverage — essential reading for understanding both sides.",
      "National trade press (Becker's, InsuranceNewsNet) placed the dispute in broader payer-provider trend context.",
    ],
    social: [
      "NC state employees organized effectively on social media — 743K SHP member base generated significant organic volume.",
      "The $5,900-to-$11,800 OOP scenario was the most shared data point across platforms — concrete and personal.",
      "Political social media split unusually along fiscal-conservative vs healthcare-access lines, reflecting Briner's bipartisan appeal.",
      "Cancer patient stories from Duke generated the most emotionally resonant social content.",
    ],
    stakeholder: [
      "Treasurer Briner was the dispute's most quotable and aggressive public voice — 'incredibly tone deaf,' 'greedy,' 'more than fine with existing rates.'",
      "SEANC's transparency demand added organized labor pressure without taking sides — unusual neutrality from a union.",
      "Board member Brian Miller MD's financial analysis ($4.3B investments) provided the data backbone for Briner's attacks.",
      "CEO Albanese's departure for Kaiser mid-dispute was the most unexpected stakeholder development — Owens stepped in effectively.",
    ],
    employer: [
      "UNC system and Appalachian State HR advisories show statewide employer-level concern extending far beyond the Triangle.",
      "Open enrollment timing amplified employer anxiety — HR offices fielded questions about plan switching to maintain Duke access.",
      "State agency HR bulletins across multiple departments created administrative burden that added political pressure for resolution.",
    ],
  },
  arguments: {
    payor: [
      { phase: "Early (Jul–Aug 2025)", points: [
        "NC State Treasurer Briner called Duke's rate demand '<strong>incredibly tone deaf</strong>'",
        "Board member Brian Miller MD revealed Duke's financials: <strong>$4.3 billion investments, $566 million operating cash flows, $202 million operating income</strong>",
        "Briner: 'Duke is more than fine with our existing rates' — framed Duke as wealthy and not needing increases",
      ] },
      { phase: "Mid-Dispute (Sep 2025)", points: [
        "Briner escalated rhetoric: '<strong>greedy</strong>' Duke is '<strong>putting profit before people</strong>'",
        "Released detailed financial brief to media showing Duke's strong balance sheet vs SHP's <strong>$507 million inherited deficit</strong>",
        "Taxpayer-protection framing resonated with conservative fiscal outlets (Carolina Journal, The Center Square)",
      ] },
      { phase: "Resolution (Oct 2025)", points: [
        "Agreement reached October 3 — 17 days before the scheduled network exit",
        "SHP received <strong>$150 million plus additional $100 million</strong> from NC General Assembly to shore up funding",
      ] },
    ],
    provider: [
      { phase: "Early (Jul–Aug 2025)", points: [
        "Duke framed Aetna as refusing reasonable rate increases — <strong>no rate increase in 4 years</strong>",
        "Argued Duke was asking for increases '<strong>below inflation</strong>' — the stickiest data point in the dispute",
        "70,000 Triangle members at risk and 22,000 who list Duke as their PCP quantified the patient impact",
      ] },
      { phase: "Mid-Dispute (Aug–Sep 2025)", points: [
        "Patient stories escalated: cancer patient '<strong>devastated</strong>' by potential loss of Duke access; OOP would double from <strong>$5,900 to $11,800</strong>",
        "Stage 4 melanoma patient: irony of using Briner's own language — 'putting profit before people' — directed at the system forcing patients out of network",
        "Open enrollment timing amplified employer anxiety — UNC system and Appalachian State HR issued employee advisories",
      ] },
      { phase: "Resolution (Oct 2025)", points: [
        "Agreement reached well before the Oct 20 deadline — Duke's PR pressure and legislative funding created conditions for deal",
        "CEO departure (Craig Albanese to Kaiser, Sep 9) did not derail negotiations — COO Thomas Owens completed the deal",
      ] },
    ],
  },
  timeline: [
    { date: "2025-07-23", type: "newsBreak", label: "News breaks publicly" },
    { date: "2025-10-20", type: "termination", label: "Scheduled network exit" },
    { date: "2025-10-03", type: "agreement", label: "Agreement reached" },
  ],
};
