// Hartford HealthCare vs UnitedHealthcare — PR War Room Config
// Dispute period: Feb–Apr 2025. Resolved April 1, 2025.

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2025-02-20",
    source: "NBC Connecticut",
    sourceType: "tv",
    channel: "media",
    headline: "Hartford HealthCare warns patients may lose UHC in-network access if contract expires",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "First major local TV coverage. NBC CT warns patients of potential disruption. HHC positioned as protecting access while UHC frames rate demands as excessive. Sets early alarm for 608,000+ CT members.",
  },
  {
    id: 2,
    date: "2025-03-15",
    source: "NBC Connecticut",
    sourceType: "tv",
    channel: "media",
    headline: "Patients urged to prepare as Hartford HealthCare-UHC contract deadline looms",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "Mid-March preparation segment. Patients told to consider alternatives. HHC's 7 hospitals and ~500 locations make disruption scope enormous. Patient anxiety drives sympathy toward provider.",
  },
  {
    id: 3,
    date: "2025-04-01",
    source: "NBC Connecticut",
    sourceType: "tv",
    channel: "media",
    headline: "Hartford HealthCare and UnitedHealthcare reach last-minute agreement",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution coverage. Deal reached in early morning hours April 1, just after March 31 midnight deadline. Relief framing. NBC CT provided consistent coverage throughout dispute arc.",
  },
  {
    id: 4,
    date: "2025-03-26",
    source: "WFSB (CBS Connecticut)",
    sourceType: "tv",
    channel: "media",
    headline: "Contract deadline approaching: Hartford HealthCare and UHC patients face uncertainty",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "CBS affiliate deadline countdown coverage. Patient stories of anxiety over losing access to HHC's 7 hospitals. Five days before expiration creates maximum urgency.",
  },
  {
    id: 5,
    date: "2025-03-31",
    source: "WFSB (CBS Connecticut)",
    sourceType: "tv",
    channel: "media",
    headline: "Hartford HealthCare-UHC contract expires at midnight — thousands of patients in limbo",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "Deadline-day coverage. 608,000+ UHC CT members potentially affected. 'In limbo' framing places blame on insurer for failing to reach agreement. Maximum-urgency local broadcast.",
  },
  {
    id: 6,
    date: "2025-04-01",
    source: "WFSB (CBS Connecticut)",
    sourceType: "tv",
    channel: "media",
    headline: "Deal reached: Hartford HealthCare and UnitedHealthcare agree to new contract",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution coverage from CBS affiliate. Early morning deal announcement. Relief framing across CBS CT coverage.",
  },
  {
    id: 7,
    date: "2025-03-20",
    source: "Fox 61 (Hartford)",
    sourceType: "tv",
    channel: "media",
    headline: "Hartford HealthCare patients in jeopardy as UHC contract negotiations stall",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "'In jeopardy' framing is provider-sympathetic. Fox 61 covers Greater Hartford — core HHC service area. 'Stall' implies UHC is not negotiating in good faith.",
  },
  {
    id: 8,
    date: "2025-03-31",
    source: "Fox 61 (Hartford)",
    sourceType: "tv",
    channel: "media",
    headline: "HHC-UHC contract expires tonight — patients scramble for answers",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "Deadline-day Fox coverage. 'Scramble' framing emphasizes patient chaos caused by contract expiration. Multiple patient interviews expressing fear and confusion.",
  },
  {
    id: 9,
    date: "2025-04-01",
    source: "Fox 61 (Hartford)",
    sourceType: "tv",
    channel: "media",
    headline: "Hartford HealthCare, UHC settle contract dispute overnight",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution coverage. 'Settle' framing implies both sides compromised. Fox 61 completes three-segment arc from jeopardy to expiration to settlement.",
  },
  {
    id: 10,
    date: "2025-03-28",
    source: "WTNH (ABC Connecticut)",
    sourceType: "tv",
    channel: "media",
    headline: "What patients need to know as Hartford HealthCare-UHC contract hangs in the balance",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "ABC affiliate patient guide segment. Practical information for affected patients. Balanced but anxiety-inducing coverage three days before deadline.",
  },
  {
    id: 11,
    date: "2025-03-15",
    source: "Hartford Courant",
    sourceType: "news",
    channel: "media",
    headline: "Patient advocates warn of harm if Hartford HealthCare leaves UHC network",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "Connecticut's paper of record. Patient advocate framing places blame on UHC for threatening access. HHC is CT's 2nd-largest system — disruption would be statewide. Courant readership includes policymakers.",
  },
  {
    id: 12,
    date: "2025-04-01",
    source: "Hartford Courant",
    sourceType: "news",
    channel: "media",
    headline: "Good news for patients: Hartford HealthCare, UHC reach agreement after tense negotiations",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "'Good news for patients' framing implies bad news was expected. 'Tense negotiations' signals brinkmanship from both sides. Courant resolution piece anchors the narrative for print audience.",
  },
  {
    id: 13,
    date: "2025-03-10",
    source: "Hartford Business Journal",
    sourceType: "news",
    channel: "media",
    headline: "Clock is ticking on Hartford HealthCare-UHC contract — employers brace for impact",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Business press. Employer impact angle. HBJ audience is CT business decision-makers. Notes 65%+ of cost impact would hit self-insured employers. Nine businesses facing $500K+ increases.",
  },
  {
    id: 14,
    date: "2025-03-21",
    source: "Hartford Business Journal",
    sourceType: "news",
    channel: "media",
    headline: "Hartford HealthCare and UHC still talking as deadline approaches — no deal yet",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "'Still talking' framing suggests slow progress. HBJ tracks negotiation closely for employer audience. Ten days before deadline with no resolution creates business uncertainty.",
  },
  {
    id: 15,
    date: "2025-04-01",
    source: "Hartford Business Journal",
    sourceType: "news",
    channel: "media",
    headline: "Hartford HealthCare-UHC agreement reached — employers exhale",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution from business angle. 'Employers exhale' captures relief of self-insured employers who faced worst-case $1.3-6.3M cost exposure. HBJ completes employer-focused four-part arc.",
  },
  {
    id: 16,
    date: "2025-04-03",
    source: "Hartford Business Journal",
    sourceType: "news",
    channel: "media",
    headline: "HHC-UHC dispute signals growing trend of hospital-insurer brinkmanship in Connecticut",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Post-resolution trend analysis. Notes CT healthcare costs grew 7.8% in 2022-2023 — highest ever. Contextualizes dispute within broader CT cost crisis. Business audience takeaway: more disputes coming.",
  },
  {
    id: 17,
    date: "2025-04-02",
    source: "CT News Junkie",
    sourceType: "news",
    channel: "media",
    headline: "Hartford HealthCare and UHC reach deal just past midnight — patients spared disruption",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "CT political news outlet. 'Just past midnight' detail emphasizes how close to disruption patients came. CT News Junkie audience includes state legislators and policy staff.",
  },
  {
    id: 18,
    date: "2025-03-28",
    source: "Trumbull Times",
    sourceType: "news",
    channel: "media",
    headline: "Local patients face uncertainty in Hartford HealthCare-UHC standoff",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "low",
    notes: "Hyperlocal coverage. Trumbull is Fairfield County — affluent suburban community. Patient stories from specific community make dispute tangible for local readership. 'Standoff' implies UHC intransigence.",
  },
  {
    id: 19,
    date: "2025-03-26",
    source: "CT Public / WNPR",
    sourceType: "radio",
    channel: "media",
    headline: "CT Public Radio examines Hartford HealthCare-UHC dispute and what's at stake for patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Public radio in-depth segment. WNPR reaches educated, politically engaged CT audience. Explores both sides: UHC claims ~20% hike over 3 years ($185-200M); HHC says UHC offer of 1.8%/yr is below CT benchmark of 2.9%/yr.",
  },
  {
    id: 20,
    date: "2025-04-01",
    source: "CT Public / WNPR",
    sourceType: "radio",
    channel: "media",
    headline: "Hartford HealthCare-UHC contract dispute resolved — analysis of what it means for CT healthcare costs",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution analysis on public radio. Policy-oriented discussion of CT healthcare cost trends. Notes 7.8% growth rate in 2022-2023. NPR audience is key influencer demographic.",
  },
  {
    id: 21,
    date: "2025-03-26",
    source: "WSHU Public Radio",
    sourceType: "radio",
    channel: "media",
    headline: "WSHU covers Hartford HealthCare-UHC standoff as March 31 deadline nears",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Southern CT / Long Island Sound NPR station. Covers Fairfield County and New Haven areas — key HHC patient geography. Balanced reporting with deadline urgency framing.",
  },
  {
    id: 22,
    date: "2025-03-31",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "Hartford HealthCare, UnitedHealthcare contract set to expire — 608,000 members at risk",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National trade press. '608,000 members at risk' quantifies scope for hospital executive audience. Becker's covers pattern of UHC disputes nationally — HHC alongside MSK, M Health Fairview.",
  },
  {
    id: 23,
    date: "2025-03-30",
    source: "NewsBreak",
    sourceType: "news",
    channel: "media",
    headline: "Hartford HealthCare-UHC dispute trending on NewsBreak — CT readers follow closely",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "NewsBreak trending signals high local digital engagement. App-based news aggregator with strong CT user base. Algorithmic amplification of dispute coverage in final days before deadline.",
  },
  // === HHC OWNED MEDIA ===
  {
    id: 24,
    date: "2025-03-01",
    source: "hartfordhealthcare.org/united",
    sourceType: "owned",
    channel: "media",
    headline: "HHC launches dedicated UHC dispute page for patients — 'Your care is our priority'",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Patient-facing dedicated page. Positions HHC as patient advocate. Directs patients to resources and provides negotiation updates. 'Your care is our priority' implies UHC's priority is cost-cutting.",
  },
  {
    id: 25,
    date: "2025-03-20",
    source: "HHC CEO Jeffrey Flaks (public statement)",
    sourceType: "owned",
    channel: "media",
    headline: "HHC CEO Flaks: 'We will not accept an agreement that undermines our ability to care for Connecticut'",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "CEO statement anchors HHC's public narrative. 'Care for Connecticut' frames dispute as UHC vs. the state. Jeffrey Flaks positions HHC as community defender against out-of-state insurer.",
  },
  // === UHC OWNED MEDIA ===
  {
    id: 26,
    date: "2025-03-10",
    source: "uhc.com/hhc",
    sourceType: "owned",
    channel: "media",
    headline: "UHC creates dedicated HHC dispute page: claims HHC seeking ~20% rate hike over 3 years, costing $185-200M",
    frameAdoption: "uhc",
    sentiment: "negative_hhc",
    patientStory: false,
    blameDirection: "hhc",
    reachEstimate: "medium",
    notes: "UHC's primary public-facing dispute page. Key claims: HHC physicians already ~20% above UHC CT average. ~20% hike over 3 years = $185-200M. 65%+ would hit self-insured employers. UHC offered 1.8%/yr vs CT benchmark 2.9%/yr. Employer cost framing.",
  },
  {
    id: 27,
    date: "2025-03-15",
    source: "UHC employer/broker communication",
    sourceType: "owned",
    channel: "employer",
    headline: "UHC warns employers: HHC rate demands would cost 9 businesses $500K+ each — worst cases $1.3-6.3M",
    frameAdoption: "uhc",
    sentiment: "negative_hhc",
    patientStory: false,
    blameDirection: "hhc",
    reachEstimate: "high",
    notes: "CRITICAL EMPLOYER CHANNEL. UHC's strongest argument: specific dollar impacts on named employers. $1.3-6.3M worst-case figures are attention-grabbing for C-suite audiences. 65%+ hitting self-insured employers makes this a direct business cost issue.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 28,
    date: "2025-03-20",
    source: "Social media (CT patient anxiety)",
    sourceType: "social",
    channel: "social",
    headline: "CT patients share fears on social media: 'What happens to my doctor if HHC leaves UHC?'",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Organic patient anxiety posts across Facebook, X/Twitter, local forums. HHC's ~500 locations means patients are spread across Connecticut. Doctor continuity concerns drive emotional engagement.",
  },
  {
    id: 29,
    date: "2025-03-26",
    source: "Social media (anti-UHC sentiment)",
    sourceType: "social",
    channel: "social",
    headline: "CT social media channels amplify anti-UHC sentiment — pattern of disputes cited",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Post-Thompson assassination anti-UHC sentiment remains elevated. CT users cite simultaneous MSK and M Health Fairview disputes as evidence of UHC's aggressive national strategy. Pattern framing undermines UHC's position.",
  },
  {
    id: 30,
    date: "2025-03-31",
    source: "Social media (deadline-day surge)",
    sourceType: "social",
    channel: "social",
    headline: "Deadline-day social media surge: 'Tonight at midnight Hartford HealthCare drops from UHC'",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "Peak social engagement on deadline day. Misinformation mixed with legitimate patient concern. 'Drops from UHC' framing places blame on insurer. Correlates with Google Trends peak (100).",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 31,
    date: "2025-03-18",
    source: "U.S. Rep. John Larson, Sen. Richard Blumenthal, Rep. Joe Courtney",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "CT congressional delegation sends letter demanding UHC protect Medicare Advantage enrollees in HHC dispute",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "FEDERAL POLITICAL PRESSURE. Bipartisan CT delegation letter focused on Medicare Advantage — 60-day cooling-off does not cover MA plans. Federal officials explicitly siding with provider signals UHC's political vulnerability. Rep. Larson, Sen. Blumenthal, Rep. Courtney all signed.",
  },
  {
    id: 32,
    date: "2025-03-22",
    source: "CT OHA Director Kathleen Holt",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "CT Office of Health Advocacy: 'Brinkmanship leaves consumers with no voice' — three legislative proposals",
    frameAdoption: "balanced",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "KEY REGULATORY VOICE. Kathleen Holt frames dispute as 'brinkmanship' — implies both sides but 'consumers with no voice' creates sympathy for patients against insurer. Three legislative proposals signal regulatory intent. OHA call volume up 10% during dispute.",
  },
  {
    id: 33,
    date: "2025-03-25",
    source: "State Sen. Dr. Saud Anwar",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "State Sen. Dr. Anwar: 'The system does not protect patients' — calls for reform",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Physician-legislator carries dual credibility. 'System does not protect patients' is systemic critique that indicts UHC's negotiating posture. Dr. Anwar's medical background gives policy statement clinical weight.",
  },
  {
    id: 34,
    date: "2025-03-15",
    source: "CT 60-day cooling-off regulation",
    sourceType: "news",
    channel: "stakeholder",
    headline: "CT 60-day cooling-off provides continuity for fully insured — but does NOT cover Medicare Advantage",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "REGULATORY GAP: CT cooling-off law provides 60-day extension for fully insured plans, but Medicare Advantage enrollees have no protection. This gap is precisely what the congressional delegation's letter targets. MA patients are older, sicker, more sympathetic.",
  },
  {
    id: 35,
    date: "2025-03-24",
    source: "Senate Bill 454 (proposed)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Senate Bill 454 introduced to strengthen consumer protections during hospital-insurer disputes",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Legislative response to HHC-UHC dispute. SB 454 would expand protections beyond current 60-day cooling-off. Dispute directly catalyzed new legislation — signals lasting policy impact regardless of resolution.",
  },
  {
    id: 36,
    date: "2025-03-20",
    source: "CT Hospital Association",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "CT Hospital Association backs Hartford HealthCare: insurers must fund sustainable care",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Industry association support for HHC. 'Sustainable care' framing adopted from HHC's messaging. CHA represents all CT hospitals — positions dispute as insurer vs. entire provider community, not just HHC.",
  },
  {
    id: 37,
    date: "2025-03-28",
    source: "CT OHA press release",
    sourceType: "news",
    channel: "stakeholder",
    headline: "CT Office of Health Advocacy issues press release on HHC-UHC dispute: patient rights and resources",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Official government press release from OHA. Patient-facing resource guide. OHA call volume up 10% signals consumer distress. Government intervention creates legitimacy for regulatory reform narrative.",
  },
  // === PATIENT STORY ENTRIES ===
  {
    id: 38,
    date: "2025-03-24",
    source: "NBC Connecticut",
    sourceType: "tv",
    channel: "media",
    headline: "Kristen Whitney Daniels (34): post-concussion syndrome patient faces $10K out-of-pocket if HHC leaves UHC",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "KEY PATIENT STORY. Kristen Whitney Daniels (34): car accident July 2024, post-concussion syndrome, requires injection every 3 months. Faces $10,000 out-of-pocket if forced out of network. Young, sympathetic, specific dollar amount makes abstract dispute tangible. Most-cited patient in CT coverage.",
  },
  {
    id: 39,
    date: "2025-03-27",
    source: "WFSB (CBS Connecticut)",
    sourceType: "tv",
    channel: "media",
    headline: "Colorectal cancer patient: 'I'm under threat of having my cancer treatments taken away'",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "CRITICAL PATIENT STORY. Unnamed colorectal cancer patient — 'under threat of cancer treatments taken away.' Cancer treatment disruption is maximally sympathetic. Direct quote creates devastating soundbite for UHC. Echoes MSK-UHC dynamic where cancer angle is impossible for insurer to counter.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 40,
    date: "2025-03-12",
    source: "UHC employer impact analysis",
    sourceType: "owned",
    channel: "employer",
    headline: "UHC to employers: 65%+ of HHC rate hike costs would fall on self-insured employers",
    frameAdoption: "uhc",
    sentiment: "negative_hhc",
    patientStory: false,
    blameDirection: "hhc",
    reachEstimate: "high",
    notes: "UHC's strongest employer argument. 65%+ cost pass-through to self-insured employers. Nine businesses facing $500K+; worst cases $1.3-6.3M annually. Positions HHC as threat to employer bottom lines. But employee healthcare disruption creates counter-pressure.",
  },
  {
    id: 41,
    date: "2025-03-18",
    source: "CT employer groups (private concern)",
    sourceType: "news",
    channel: "employer",
    headline: "CT employers caught between UHC cost warnings and employee access concerns",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Employer perspective is bifurcated: CFOs worry about $500K-$6.3M cost increases; HR leaders worry about employee access to CT's 2nd-largest health system. Dual pressure makes employer channel unusually volatile.",
  },
  // === ADDITIONAL MEDIA/SOCIAL ===
  {
    id: 42,
    date: "2025-03-29",
    source: "Social media (Kristen Whitney Daniels story shared)",
    sourceType: "social",
    channel: "social",
    headline: "Kristen Whitney Daniels' story goes viral in CT — '$10K out of pocket' becomes rallying point",
    frameAdoption: "hhc",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Patient story amplified across CT social media. $10,000 figure is specific and relatable — turns abstract dispute into kitchen-table issue. Young woman (34) with car accident injury is broadly sympathetic.",
  },
  {
    id: 43,
    date: "2025-03-25",
    source: "UHC CT rate comparison data",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "UHC data: HHC physicians already ~20% above UHC Connecticut average — rate hike would widen gap",
    frameAdoption: "uhc",
    sentiment: "negative_hhc",
    patientStory: false,
    blameDirection: "hhc",
    reachEstimate: "medium",
    notes: "UHC's key data point. HHC physicians ~20% above UHC CT average is designed to frame HHC as already overpaid. UHC offered 1.8%/yr; CT benchmark 2.9%/yr. HHC can counter: 1.8% is below inflation and below state benchmark.",
  },
  {
    id: 44,
    date: "2025-03-26",
    source: "CT healthcare cost data (OHA)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "CT healthcare spending grew 7.8% in 2022-2023 — highest rate ever recorded",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "CONTEXTUAL DATA. 7.8% growth rate is highest in CT history. Provides backdrop for both sides: HHC argues costs are rising and 1.8% is unsustainable; UHC argues costs are already too high and must be contained. OHA data gives both frames credibility.",
  },
  {
    id: 45,
    date: "2025-03-31",
    source: "MSK vs UHC / M Health Fairview vs UHC parallel",
    sourceType: "news",
    channel: "stakeholder",
    headline: "HHC dispute part of pattern: UHC simultaneously fighting MSK in NY and M Health Fairview in MN",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "PATTERN EVIDENCE. UHC fighting three major health systems simultaneously (HHC, MSK, M Health Fairview). Pattern undermines UHC's claim that any single provider is unreasonable. Suggests corporate strategy of aggressive cost containment across markets.",
  },
  {
    id: 46,
    date: "2025-04-01",
    source: "HHC CEO Jeffrey Flaks (resolution statement)",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "HHC CEO Flaks: agreement protects access for Connecticut patients",
    frameAdoption: "hhc",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution statement from HHC CEO. 'Protects access' framing implies UHC was threatening it — victory language even in resolution. Positions HHC as having fought for patients against insurer cost-cutting.",
  },
  {
    id: 47,
    date: "2025-03-31",
    source: "Google Trends (CT)",
    sourceType: "news",
    channel: "social",
    headline: "Google search interest for 'Hartford HealthCare UnitedHealthcare' peaks at 100 on March 31",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Peak search interest on deadline day. Trajectory: early Feb (5) -> late Feb (20) -> Mar 15 (35) -> Mar 21 (55) -> Mar 26 (75) -> Mar 31 (100) -> Apr 1 (95) -> Apr 7 (25) -> Apr 14 (10). Classic dispute curve with sharp peak and rapid decline after resolution.",
  },
  {
    id: 48,
    date: "2025-03-22",
    source: "Social media (employer frustration)",
    sourceType: "social",
    channel: "social",
    headline: "CT business owners vent on LinkedIn: 'We're caught in the middle of a fight we didn't start'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Employer social engagement. LinkedIn posts from CT business leaders expressing frustration at being caught between insurer and provider. Self-insured employer anger directed at both parties but especially UHC for creating disruption.",
  },
];

const LABELS = {
  frameAdoption: { hhc: "HHC Frame", uhc: "UHC Frame", balanced: "Balanced" },
  sentiment: {
    negative_uhc: "Anti-UHC",
    negative_hhc: "Anti-HHC",
    neutral: "Neutral",
    positive_uhc: "Pro-UHC",
    positive_hhc: "Pro-HHC",
  },
  blameDirection: { uhc: "Blames UHC", hhc: "Blames HHC", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National record (1.5)
  "Becker's Hospital Review": 1.5,
  // Tier 2 — Regional authority (1.2)
  "NBC Connecticut": 1.2, "WFSB (CBS Connecticut)": 1.2, "Fox 61 (Hartford)": 1.2,
  "WTNH (ABC Connecticut)": 1.2, "Hartford Courant": 1.2,
  // Tier 3 — Trade/niche (1.0)
  "Hartford Business Journal": 1.0, "CT News Junkie": 1.0, "Trumbull Times": 1.0,
  "NewsBreak": 1.0,
  // Tier 3.5 — Public radio (1.1)
  "CT Public / WNPR": 1.1, "WSHU Public Radio": 1.1,
  // Tier 4 — Organic social (0.7)
  "Social media (CT patient anxiety)": 0.7, "Social media (anti-UHC sentiment)": 0.7,
  "Social media (deadline-day surge)": 0.7, "Social media (Kristen Whitney Daniels story shared)": 0.7,
  "Social media (employer frustration)": 0.7, "Google Trends (CT)": 0.7,
  // Tier 6 — Owned/party media (0.3)
  "hartfordhealthcare.org/united": 0.3, "HHC CEO Jeffrey Flaks (public statement)": 0.3,
  "HHC CEO Jeffrey Flaks (resolution statement)": 0.3,
  "uhc.com/hhc": 0.3, "UHC employer/broker communication": 0.3, "UHC employer impact analysis": 0.3,
  "UHC CT rate comparison data": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "U.S. Rep. John Larson, Sen. Richard Blumenthal, Rep. Joe Courtney": 1.3,
  "CT OHA Director Kathleen Holt": 1.3, "State Sen. Dr. Saud Anwar": 1.3,
  "CT 60-day cooling-off regulation": 1.3, "Senate Bill 454 (proposed)": 1.3,
  "CT Hospital Association": 1.3, "CT OHA press release": 1.3,
  "CT healthcare cost data (OHA)": 1.3,
  "MSK vs UHC / M Health Fairview vs UHC parallel": 1.3,
  // Tier 8 — Employer/Benefits (1.5x trade)
  "CT employer groups (private concern)": 1.5,
};

const SEARCH_TRENDS = [
  { week: "2025-02-03", interest: 5 }, { week: "2025-02-10", interest: 5 }, { week: "2025-02-17", interest: 8 },
  { week: "2025-02-24", interest: 20 }, { week: "2025-03-03", interest: 25 }, { week: "2025-03-10", interest: 30 },
  { week: "2025-03-17", interest: 35 }, { week: "2025-03-24", interest: 55 }, { week: "2025-03-31", interest: 100 },
  { week: "2025-04-07", interest: 25 }, { week: "2025-04-14", interest: 10 }, { week: "2025-04-21", interest: 5 },
];

export default {
  // Identity
  providerKey: "hhc",
  payorKey: "uhc",
  providerName: "Hartford HealthCare",
  payorName: "UnitedHealthcare",
  providerShort: "HHC",
  payorShort: "UHC",
  navShort: "Hartford v. UHC",
  title: "Hartford HealthCare vs UnitedHealthcare",
  subtitle: "Contract dispute · Resolved April 1, 2025",
  gradientId: "hartforduhc",

  // Dates
  monitorStart: "February 1, 2025",
  monitorEnd: "April 30, 2025",
  disputePublicDate: "2025-02-15",

  // Colors
  colors: {
    providerColor: "#1B4D8E",
    payorColor: "#8B2332",
    neutral: "#64748B",
    accent: "#1B4D8E",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#1B4D8E", "#465E85", "#8B2332"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"hartford healthcare unitedhealthcare" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 2.14,
    nationalMedian: 1.0,
    networkComplaints: 1847,
    priorYearComplaints: 1205,
    regulatorAction: "CT Office of Health Advocacy issued press release, created patient FAQ, and reported 10% increase in call volume. OHA Director Kathleen Holt proposed three legislative reforms. Senate Bill 454 introduced. CT 60-day cooling-off regulation provided transitional coverage for fully insured plans but did not cover Medicare Advantage.",
    signalRead: "UHC's national complaint index is elevated (2.14x median) driven by multi-state provider disputes simultaneously. The HHC dispute occurred alongside MSK (NY) and M Health Fairview (MN) — pattern evidence of aggressive UHC network strategy. CT's 7.8% healthcare cost growth (highest ever) provides context for both sides' positions.",
  },

  // Executive summary
  executiveSummary: {
    statement: "The dispute resolved via early-morning deal on April 1 — just past the March 31 midnight deadline. No actual disruption occurred, but significant political and regulatory fallout including federal congressional intervention and new state legislation.",
    keyMessages: [
      "UHC's 1.8%/yr offer vs. CT benchmark of 2.9%/yr is the stickiest factual counter to UHC's 'price hike' narrative — UHC was offering below-market rates.",
      "Federal congressional delegation (Larson, Blumenthal, Courtney) explicitly pressured UHC on Medicare Advantage gap — rare federal intervention in state-level dispute.",
      "CT OHA's 'brinkmanship' and 'consumers with no voice' framing created regulatory momentum: three legislative proposals and Senate Bill 454.",
      "UHC fighting three major systems simultaneously (HHC, MSK, M Health Fairview) undermines 'HHC is uniquely unreasonable' framing.",
    ],
    marcomm: [
      "<strong>Scale makes this dispute impossible to contain.</strong> HHC's 7 hospitals and ~500 locations across CT mean 608,000+ UHC members potentially affected. No insurer can quietly walk away from a state's 2nd-largest health system without massive public backlash.",
      "<strong>The Medicare Advantage gap is UHC's political vulnerability.</strong> CT's 60-day cooling-off does not cover MA plans, triggering federal congressional intervention. Older, sicker MA patients are maximally sympathetic — and their representatives took notice.",
      "<strong>Employer channel is double-edged for UHC.</strong> UHC's cost data ($500K-$6.3M employer impacts) is compelling for CFOs, but employee healthcare disruption creates counter-pressure HR leaders cannot ignore. Self-insured employers (65%+ of impact) are caught in the middle.",
      "<strong>Regulatory momentum outlasts the dispute.</strong> Senate Bill 454 and OHA's three legislative proposals ensure this dispute has lasting policy impact in CT regardless of resolution. Future disputes will face tighter regulatory constraints.",
    ],
  },
  channelTakeaways: {
    media: [
      "All four major CT TV stations (NBC CT, WFSB/CBS, Fox 61, WTNH) provided multi-segment coverage — complete saturation of local broadcast market.",
      "Hartford Courant's 'patient advocates warn of harm' framing set the print narrative early and was reinforced by Hartford Business Journal's employer-focused coverage.",
      "Public radio (WNPR, WSHU) reached educated, politically engaged audience with balanced but urgency-driven coverage in final week.",
      "Becker's Hospital Review placed HHC-UHC in national context alongside other UHC disputes — pattern evidence for hospital executive audience.",
    ],
    social: [
      "Kristen Whitney Daniels' $10K out-of-pocket story became the dispute's most viral patient narrative — specific dollar amount made abstract dispute tangible.",
      "Google Trends peak of 100 on March 31 (deadline day) with sharp post-resolution decline shows classic dispute engagement curve.",
      "Post-Thompson anti-UHC sentiment amplified negative framing — UHC disputes now land in structurally hostile social environment.",
      "LinkedIn employer frustration posts created unusual business-community social engagement typically absent from healthcare disputes.",
    ],
    stakeholder: [
      "Federal congressional letter (Larson, Blumenthal, Courtney) targeting Medicare Advantage gap was the highest-impact stakeholder action — rare federal pressure on state dispute.",
      "CT OHA Director Kathleen Holt's 'brinkmanship' and 'consumers with no voice' quotes became defining regulatory framing for the dispute.",
      "State Sen. Dr. Saud Anwar's dual physician-legislator credibility amplified 'system does not protect patients' narrative.",
      "Senate Bill 454 and OHA's three legislative proposals ensure regulatory legacy — future CT disputes will face expanded consumer protections.",
    ],
    employer: [
      "UHC's employer data (65%+ cost pass-through, 9 businesses at $500K+, worst cases $1.3-6.3M) was the strongest pro-UHC argument in any channel.",
      "Hartford Business Journal's four-part coverage arc tracked employer sentiment from anxiety through resolution — key business audience channel.",
      "Self-insured employers faced dual pressure: UHC cost warnings vs. employee access to CT's 2nd-largest system. Neither side could fully capture employer sympathy.",
    ],
  },
  timeline: [
    { date: "2025-02-20", type: "newsBreak", label: "News breaks publicly" },
    { date: "2025-03-31", type: "termination", label: "Contract terminates" },
    { date: "2025-04-01", type: "agreement", label: "Agreement reached" },
  ],
};
