// Huntsville Hospital Health System vs UnitedHealthcare — PR War Room Config
// Dispute period: October–November 2024. Resolved November 20, 2024.

const ENTRIES = [
  // === MEDIA ENTRIES — TV ===
  {
    id: 1,
    date: "2024-10-10",
    source: "WAFF 48 (NBC)",
    sourceType: "tv",
    channel: "media",
    headline: "Huntsville Hospital announces contract dispute with UnitedHealthcare — patients could lose in-network access",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "First broadcast coverage of dispute announcement. WAFF 48 is Huntsville's NBC affiliate and dominant local news station. HHHS frames UHC denial rate as 75% higher than comparable insurers. Sets provider-sympathetic tone from day one.",
  },
  {
    id: 2,
    date: "2024-10-10",
    source: "WHNT 19 (CBS)",
    sourceType: "tv",
    channel: "media",
    headline: "Huntsville Hospital, UnitedHealthcare at odds over contract — 1.3 million people potentially affected",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "Same-day coverage from CBS affiliate. '1.3 million people' figure amplifies scale of community impact. Multiple local stations covered simultaneously — coordinated HHHS announcement.",
  },
  {
    id: 3,
    date: "2024-10-10",
    source: "WAAY 31 (ABC)",
    sourceType: "tv",
    channel: "media",
    headline: "Huntsville Hospital system warns of potential split with UnitedHealthcare over reimbursement rates",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "ABC affiliate same-day coverage. 'Reimbursement rates' framing puts focus on UHC underpaying. All three major Huntsville TV stations covered on day one — full market saturation.",
  },
  {
    id: 4,
    date: "2024-10-10",
    source: "Rocket City Now (Fox)",
    sourceType: "tv",
    channel: "media",
    headline: "Huntsville Hospital Health System publicly challenges UnitedHealthcare contract terms",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Fox affiliate rounds out full-market TV saturation on announcement day. Every major local TV outlet covered the dispute within hours of the announcement.",
  },
  {
    id: 5,
    date: "2024-10-11",
    source: "WAFF 48 (NBC)",
    sourceType: "tv",
    channel: "media",
    headline: "Patients react to Huntsville Hospital-UHC dispute: 'Everything is scary'",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "First patient reaction story. 'Everything is scary' quote captures raw patient anxiety. Unnamed patient featured. Sets emotional tone for ongoing coverage — fear and confusion among vulnerable patients.",
  },
  {
    id: 6,
    date: "2024-10-14",
    source: "WAFF 48 (NBC)",
    sourceType: "tv",
    channel: "media",
    headline: "Heartbreaking stories emerge as Huntsville Hospital patients face losing UHC coverage",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "'Heartbreaking' editorial framing in headline. Multiple patient stories consolidated. Terri Krejci: lupus, rheumatoid arthritis, breast cancer survivor — 'scared and confused.' Unnamed cancer patient: 'terrified.' Devastating human-interest angle.",
  },
  {
    id: 7,
    date: "2024-10-15",
    source: "WAFF 48 (NBC)",
    sourceType: "tv",
    channel: "media",
    headline: "Helen Keller Hospital leaves UHC network — Shoals region patients scramble for options",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "ESCALATION: Helen Keller Hospital (Shoals/Florence area) exits UHC network Oct 15. First concrete network disruption. Expands geographic footprint of dispute beyond Huntsville metro. Rural patients have fewer alternatives — amplifies impact.",
  },
  {
    id: 8,
    date: "2024-10-23",
    source: "WAFF 48 (NBC)",
    sourceType: "tv",
    channel: "media",
    headline: "Danielle DuPont: expecting mother caught in Huntsville Hospital-UHC crossfire — 'I feel like I'm the one being punished'",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "MOST IMPACTFUL PATIENT STORY. Danielle DuPont: expecting mother, less than 2 months from delivery. 'I feel like I'm the one being punished.' Pregnant woman facing disrupted care is maximally sympathetic — impossible for UHC to counter. Named, on camera, visually pregnant.",
  },
  {
    id: 9,
    date: "2024-11-07",
    source: "WAFF 48 (NBC)",
    sourceType: "tv",
    channel: "media",
    headline: "Clock ticking on Huntsville Hospital-UHC dispute — deadline approaching with no resolution",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "Deadline urgency framing. 'Clock ticking' creates pressure narrative. Nov 14 deadline approaching. WAFF continues as most aggressive local outlet covering the dispute.",
  },
  {
    id: 10,
    date: "2024-11-08",
    source: "WAFF 48 (NBC)",
    sourceType: "tv",
    channel: "media",
    headline: "Huntsville Hospital-UHC talks continue as deadline looms — community braces for impact",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "Back-to-back deadline coverage. 'Community braces for impact' frames entire region as affected. WAFF maintained near-daily coverage during final stretch.",
  },
  {
    id: 11,
    date: "2024-11-12",
    source: "WAAY 31 (ABC)",
    sourceType: "tv",
    channel: "media",
    headline: "Patients in bind as Huntsville Hospital-UHC deadline nears — scrambling for alternatives",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "'Patients in bind' framing places blame on dispute dynamics. Patients describe difficulty finding alternative providers in North Alabama. Rural healthcare access angle strengthens HHHS position — patients genuinely have few alternatives.",
  },
  {
    id: 12,
    date: "2024-11-14",
    source: "WAFF 48 (NBC)",
    sourceType: "tv",
    channel: "media",
    headline: "Breaking: Huntsville Hospital and UnitedHealthcare reach agreement one day before deadline",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "RESOLUTION BREAKING NEWS. Agreement reached Nov 13, announced Nov 14 — one day before contract termination deadline. '11th-hour' framing. Relief tone across all local outlets.",
  },
  {
    id: 13,
    date: "2024-11-14",
    source: "WHNT 19 (CBS)",
    sourceType: "tv",
    channel: "media",
    headline: "Huntsville Hospital, UHC reach deal — patients can keep their doctors",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CBS resolution coverage. 'Patients can keep their doctors' frames resolution as patient victory. Terms not disclosed.",
  },
  {
    id: 14,
    date: "2024-11-18",
    source: "WAAY 31 (ABC)",
    sourceType: "tv",
    channel: "media",
    headline: "Clarification on Huntsville Hospital-UHC agreement — what patients need to know",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Post-agreement explainer. Clarifies that agreement was reached Nov 13 but finalization ongoing. Patients advised to confirm coverage status. Service journalism angle.",
  },
  {
    id: 15,
    date: "2024-11-20",
    source: "WAFF 48 (NBC)",
    sourceType: "tv",
    channel: "media",
    headline: "Huntsville Hospital and UnitedHealthcare finalize multi-year contract agreement",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "FINAL RESOLUTION. Multi-year agreement finalized Nov 20. WAFF bookends the story — first to break the dispute, covers the conclusion. Terms remain confidential.",
  },
  {
    id: 16,
    date: "2024-11-20",
    source: "WHNT 19 (CBS)",
    sourceType: "tv",
    channel: "media",
    headline: "Huntsville Hospital-UHC multi-year deal finalized — dispute officially over",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CBS finalization coverage. 'Dispute officially over' provides closure framing for community.",
  },
  {
    id: 17,
    date: "2024-11-20",
    source: "Rocket City Now (Fox)",
    sourceType: "tv",
    channel: "media",
    headline: "Huntsville Hospital and UHC sign multi-year contract — ending weeks of uncertainty",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Fox affiliate resolution coverage. 'Weeks of uncertainty' underscores community impact of the dispute.",
  },
  {
    id: 18,
    date: "2024-11-22",
    source: "Rocket City Now (Fox)",
    sourceType: "tv",
    channel: "media",
    headline: "Huntsville Hospital-UHC deal: what it means for patients going forward",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Post-resolution explainer. Service journalism for patients. Fox covers aftermath and patient guidance.",
  },
  // === MEDIA ENTRIES — PRINT/ONLINE ===
  {
    id: 19,
    date: "2024-10-10",
    source: "Decatur Daily",
    sourceType: "news",
    channel: "media",
    headline: "Huntsville Hospital system and UnitedHealthcare in contract standoff — Decatur-Morgan Hospital affected",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Decatur Daily is primary print outlet for Morgan County. Decatur-Morgan Hospital is HHHS member — local angle makes this directly relevant to Decatur readers. Same-day coverage of announcement.",
  },
  {
    id: 20,
    date: "2024-10-10",
    source: "Elk Valley Times",
    sourceType: "news",
    channel: "media",
    headline: "Huntsville Hospital warns of UHC contract termination — regional impact feared",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "low",
    notes: "Small community newspaper. Coverage demonstrates dispute reach into rural Tennessee Valley communities. Even smallest outlets covered this — total regional media saturation.",
  },
  {
    id: 21,
    date: "2024-10-10",
    source: "256 Today",
    sourceType: "news",
    channel: "media",
    headline: "Huntsville Hospital Health System goes public with UnitedHealthcare contract battle",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "256 Today is a North Alabama digital news outlet (named after area code). 'Goes public' framing acknowledges HHHS's deliberate communications strategy. Regional digital reach.",
  },
  {
    id: 22,
    date: "2024-10-11",
    source: "Times-Journal",
    sourceType: "news",
    channel: "media",
    headline: "Fort Payne hospital patients face uncertainty as Huntsville Hospital system battles UHC",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "low",
    notes: "Times-Journal covers DeKalb County/Fort Payne area. Highlands Medical Center is HHHS affiliate in this region — later left UHC network Oct 31. Rural healthcare access concern is acute.",
  },
  {
    id: 23,
    date: "2024-11-14",
    source: "Decatur Daily",
    sourceType: "news",
    channel: "media",
    headline: "Huntsville Hospital and UHC reach agreement — Decatur-Morgan patients can stay in-network",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution coverage with local Decatur angle. Relief framing for Decatur-Morgan Hospital patients specifically.",
  },
  {
    id: 24,
    date: "2024-11-20",
    source: "Times-Journal",
    sourceType: "news",
    channel: "media",
    headline: "Huntsville Hospital-UHC deal finalized — Highlands Medical Center returns to network",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Finalization coverage. Highlands Medical Center (which left UHC Oct 31) returns to network. Important closure for DeKalb County patients who experienced actual network disruption.",
  },
  {
    id: 25,
    date: "2024-11-20",
    source: "Athens News Courier",
    sourceType: "news",
    channel: "media",
    headline: "Huntsville Hospital system and UHC reach multi-year deal — Athens-Limestone patients retain access",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Athens News Courier covers Limestone County. Athens-Limestone Hospital is HHHS member. Resolution coverage for local readers.",
  },
  // === STATEWIDE MEDIA ===
  {
    id: 26,
    date: "2024-11-14",
    source: "Yellowhammer News",
    sourceType: "news",
    channel: "media",
    headline: "Huntsville Hospital Health System and UnitedHealthcare reach agreement — statewide attention on dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Yellowhammer News is Alabama's most prominent statewide news outlet. Statewide coverage elevates dispute beyond Huntsville metro. Important for legislative awareness and state employer plan implications.",
  },
  // === TRADE MEDIA ===
  {
    id: 27,
    date: "2024-10-15",
    source: "Becker's Payer Issues",
    sourceType: "news",
    channel: "media",
    headline: "Huntsville Hospital system, UnitedHealthcare in contract dispute — 14 hospitals at stake",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National trade press coverage. '14 hospitals at stake' highlights scale. Becker's audience is hospital executives nationally — positions HHHS dispute as significant. Payor Issues section indicates blame-neutral but insurer-focused framing.",
  },
  {
    id: 28,
    date: "2024-10-18",
    source: "HealthLeaders",
    sourceType: "news",
    channel: "media",
    headline: "UnitedHealthcare faces another hospital system standoff — Huntsville Hospital joins growing list",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "'Another hospital system standoff' and 'growing list' framing positions UHC as serial aggressor. Pattern evidence: HCA, Prisma, UNC disputes cited. Trade audience sees systemic UHC problem, not HHHS-specific issue.",
  },
  {
    id: 29,
    date: "2024-10-22",
    source: "InsuranceNewsNet",
    sourceType: "news",
    channel: "media",
    headline: "UnitedHealthcare provider disputes widen — Alabama hospital system latest to go public",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Insurance industry trade press. 'Disputes widen' frames this as UHC portfolio problem. Insurer-side audience gets view of growing provider pushback. Important for broker and employer awareness.",
  },
  // === HHHS OWNED MEDIA ===
  {
    id: 30,
    date: "2024-10-10",
    source: "Huntsville Hospital (public statement)",
    sourceType: "owned",
    channel: "media",
    headline: "CEO Jeff Samz: UHC denial rate 75% higher than comparable insurers — 'we cannot continue to absorb these losses'",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "CEO Jeff Samz public statement. Key data: UHC denial rate 75% higher than comparable insurers. $2.34B net patient revenue system being underpaid. HHHS serves 1.3M people across 14 hospitals with ~2,500 beds and ~19,500 employees. Frames UHC as the aggressor in clear, data-driven terms.",
  },
  {
    id: 31,
    date: "2024-10-15",
    source: "Huntsville Hospital (patient advisory)",
    sourceType: "owned",
    channel: "media",
    headline: "HHHS publishes patient FAQ on UHC dispute — directs patients to coverage resources and alternatives",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Patient-facing communication. FAQ format addresses coverage continuity, emergency care, and alternative options. Professional crisis communications — organized, proactive, patient-centered.",
  },
  {
    id: 32,
    date: "2024-11-14",
    source: "Huntsville Hospital (press release)",
    sourceType: "owned",
    channel: "media",
    headline: "Huntsville Hospital Health System announces agreement with UnitedHealthcare — multi-year deal",
    frameAdoption: "huntsville",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution press release. Victory framing — 'protects access for patients' implies UHC was threatening it. CEO Samz statement positions deal as win for community. Agreement reached Nov 13, announced Nov 14.",
  },
  // === UHC OWNED MEDIA ===
  {
    id: 33,
    date: "2024-10-11",
    source: "es.uhc.com/huntsville",
    sourceType: "owned",
    channel: "media",
    headline: "UHC publishes dedicated Huntsville dispute page — claims HHHS rates >20% higher than Alabama average",
    frameAdoption: "uhc",
    sentiment: "negative_huntsville",
    patientStory: false,
    blameDirection: "huntsville",
    reachEstimate: "medium",
    notes: "UHC's primary counter-narrative. Dedicated microsite at es.uhc.com/huntsville. Key claims: HHHS charges >20% higher than Alabama state average; HHHS demanded >25% rate increase in a single year. Corporate tone, no patient voices. Defensive positioning.",
  },
  {
    id: 34,
    date: "2024-10-14",
    source: "UnitedHealthcare (public statement)",
    sourceType: "owned",
    channel: "media",
    headline: "UHC: 'We remain committed to reaching an agreement that keeps care affordable for our members'",
    frameAdoption: "uhc",
    sentiment: "negative_huntsville",
    patientStory: false,
    blameDirection: "huntsville",
    reachEstimate: "medium",
    notes: "UHC public response to HHHS campaign. 'Affordable' framing attempts to position UHC as consumer advocate. Claims HHHS rates already well above state average. $32.4B annual earnings makes affordability argument difficult to sustain publicly.",
  },
  // === PATIENT STORIES ===
  {
    id: 35,
    date: "2024-10-23",
    source: "WAFF 48 (NBC) — DuPont feature",
    sourceType: "tv",
    channel: "media",
    headline: "Danielle DuPont: 'I feel like I'm the one being punished' — expecting mother faces delivery disruption",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "FEATURED PATIENT: Danielle DuPont, expecting mother, less than 2 months from delivery. 'I feel like I'm the one being punished.' Most powerful patient story of the dispute — pregnant woman facing disrupted obstetric care is viscerally sympathetic. Named, on camera.",
  },
  {
    id: 36,
    date: "2024-10-14",
    source: "WAFF 48 (NBC) — Krejci feature",
    sourceType: "tv",
    channel: "media",
    headline: "Terri Krejci: lupus, RA, breast cancer survivor — 'scared and confused' by UHC-HHHS dispute",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "FEATURED PATIENT: Terri Krejci — lupus, rheumatoid arthritis, breast cancer survivor. 'Scared and confused.' Multiple chronic conditions requiring ongoing specialist care makes switching providers extremely difficult. Named, on camera.",
  },
  {
    id: 37,
    date: "2024-10-16",
    source: "WAFF 48 (NBC) — cancer patient",
    sourceType: "tv",
    channel: "media",
    headline: "Recently diagnosed cancer patient: 'I am terrified' of losing access to Huntsville Hospital oncology",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "Unnamed patient recently diagnosed with cancer. 'Terrified.' Active cancer diagnosis + potential loss of treating oncologist is devastating patient story. Anonymity suggests fear of insurance retaliation.",
  },
  {
    id: 38,
    date: "2024-10-18",
    source: "WAFF 48 (NBC) — health navigator",
    sourceType: "tv",
    channel: "media",
    headline: "Health navigator: 'I am mad for my patients' — frontline staff describe frustration with UHC dispute",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Unnamed health navigator — staff perspective adds institutional credibility to patient harm narrative. 'Mad for my patients' shows provider-side emotional investment. Humanizes the hospital workforce beyond executive leadership.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 39,
    date: "2024-10-10",
    source: "Huntsville Hospital (Facebook)",
    sourceType: "social",
    channel: "social",
    headline: "HHHS Facebook post announces dispute — comment section floods with patient anxiety and anger at UHC",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Facebook skews older — key demographic for hospital patients in North Alabama. Comment sections highly emotional. Patients sharing personal stories of dependence on HHHS facilities. Organic anti-UHC sentiment.",
  },
  {
    id: 40,
    date: "2024-10-12",
    source: "Social media (community reaction)",
    sourceType: "social",
    channel: "social",
    headline: "Huntsville community social media erupts over hospital-UHC dispute — 'They're putting profits over patients'",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Organic community reaction on Facebook, Nextdoor, and local forums. HHHS is anchor institution in Huntsville — ~19,500 employees means nearly every family has a connection. 'Profits over patients' narrative against UHC ($32.4B earnings). Grassroots anger.",
  },
  {
    id: 41,
    date: "2024-10-31",
    source: "Social media (Highlands exit reaction)",
    sourceType: "social",
    channel: "social",
    headline: "DeKalb County residents react to Highlands Medical Center leaving UHC — 'Where do we go now?'",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Highlands Medical Center exits UHC network Oct 31 — second facility to leave after Helen Keller (Oct 15). Rural patients with limited alternatives express fear. DeKalb County has fewer healthcare options, amplifying the impact.",
  },
  {
    id: 42,
    date: "2024-11-14",
    source: "Social media (resolution reaction)",
    sourceType: "social",
    channel: "social",
    headline: "Community celebrates Huntsville Hospital-UHC resolution — 'Finally, some relief'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Relief and celebration in comment sections. Patients express gratitude that access preserved. Some residual anger at UHC for putting community through the ordeal. Overall positive resolution sentiment.",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 43,
    date: "2024-10-11",
    source: "PEEHIP / SEIB",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Alabama public employee plans (PEEHIP/SEIB) confirm continued coverage commitments during dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CRITICAL STAKEHOLDER: Public Education Employees' Health Insurance Plan (PEEHIP) and State Employees' Insurance Board (SEIB) — tens of thousands of Alabama public employees. Their coverage commitments reduce immediate patient disruption but highlight the scale of UHC's public-sector presence in Alabama.",
  },
  {
    id: 44,
    date: "2024-10-12",
    source: "Health Care Authority of City of Huntsville",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Health Care Authority of City of Huntsville monitors dispute — municipal governance angle",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Municipal health authority involvement signals governmental attention. Huntsville Hospital is a public hospital system — city governance has direct interest in financial sustainability of the system.",
  },
  {
    id: 45,
    date: "2024-10-15",
    source: "Helen Keller Hospital (network exit)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Helen Keller Hospital exits UHC network Oct 15 — first HHHS affiliate to terminate",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "ESCALATION MILESTONE. Helen Keller Hospital (Sheffield/Shoals region) is first facility to actually leave UHC network. Demonstrates HHHS is willing to follow through. Shoals patients lose in-network access — concrete harm begins.",
  },
  {
    id: 46,
    date: "2024-10-31",
    source: "Highlands Medical Center (network exit)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Highlands Medical Center exits UHC network Oct 31 — second HHHS facility to leave",
    frameAdoption: "huntsville",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "SECOND ESCALATION. Highlands Medical Center (Scottsboro/DeKalb County) exits Oct 31. Pattern of affiliate departures increases pressure on UHC. Rural facility exits are particularly impactful — patients have no comparable alternatives.",
  },
  {
    id: 47,
    date: "2024-10-20",
    source: "Alabama DOI (no formal action)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Alabama Department of Insurance has not taken formal action on Huntsville Hospital-UHC dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "REGULATORY SILENCE. No formal Alabama DOI intervention or investigation. Unlike some states (e.g., Connecticut), Alabama did not create public consumer resources. Silence suggests both parties expected market-based resolution without regulatory intervention.",
  },
  {
    id: 48,
    date: "2024-10-18",
    source: "UHC dispute pattern (HCA, Prisma, UNC, M Health)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "HHHS dispute fits pattern: UHC simultaneously fighting HCA, Prisma Health, UNC Health, M Health Fairview",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "PATTERN EVIDENCE. UHC engaged in simultaneous disputes with multiple major health systems nationally. HCA (largest for-profit chain), Prisma Health (SC), UNC Health (NC), M Health Fairview (MN). Pattern suggests corporate strategy of aggressive renegotiation, not HHHS-specific unreasonableness. Undermines UHC's 'this provider is too expensive' framing.",
  },
  {
    id: 49,
    date: "2024-11-13",
    source: "CEO Jeff Samz (agreement announcement)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "CEO Jeff Samz announces agreement: 'This outcome protects access to care for the communities we serve'",
    frameAdoption: "huntsville",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CEO victory statement. 'Protects access' framing implies UHC was threatening access. Agreement reached Nov 13 — one day before deadline. 'Communities we serve' reinforces HHHS's anchor institution role. CEO led public campaign from start to finish.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 50,
    date: "2024-10-11",
    source: "UHC employer notification",
    sourceType: "owned",
    channel: "employer",
    headline: "UHC notifies North Alabama employers: HHHS facilities may leave network — frames HHHS as demanding excessive rate increases",
    frameAdoption: "uhc",
    sentiment: "negative_huntsville",
    patientStory: false,
    blameDirection: "huntsville",
    reachEstimate: "high",
    notes: "UHC's employer-facing communication. Frames HHHS as demanding >25% rate increase. 'Already 20% above Alabama average' is UHC's stickiest employer-facing argument. Targets self-insured employers who bear direct cost impact.",
  },
  {
    id: 51,
    date: "2024-10-14",
    source: "North Alabama employer reaction",
    sourceType: "news",
    channel: "employer",
    headline: "North Alabama employers caught between UHC and HHHS — workforce access to 14 hospitals at risk",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Employers in Huntsville metro (including defense contractors, NASA workforce, tech sector) face workforce healthcare disruption. HHHS's 14 hospitals and ~2,500 beds represent dominant regional provider — employers have limited network alternatives. Redstone Arsenal/DOD workforce adds federal dimension.",
  },
];

const LABELS = {
  frameAdoption: { huntsville: "HHHS Frame", uhc: "UHC Frame", balanced: "Balanced" },
  sentiment: {
    negative_uhc: "Anti-UHC",
    negative_huntsville: "Anti-HHHS",
    neutral: "Neutral",
    positive_uhc: "Pro-UHC",
    positive_huntsville: "Pro-HHHS",
  },
  blameDirection: { uhc: "Blames UHC", huntsville: "Blames HHHS", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — Statewide/National trade (1.5)
  "Yellowhammer News": 1.5, "Becker's Payer Issues": 1.5, "HealthLeaders": 1.5,
  // Tier 2 — Regional TV authority (1.2)
  "WAFF 48 (NBC)": 1.2, "WHNT 19 (CBS)": 1.2, "WAAY 31 (ABC)": 1.2,
  "Rocket City Now (Fox)": 1.2,
  // Tier 3 — Regional print / Trade (1.0)
  "Decatur Daily": 1.0, "Times-Journal": 1.0, "Elk Valley Times": 1.0,
  "Athens News Courier": 1.0, "256 Today": 1.0, "InsuranceNewsNet": 1.0,
  // Tier 4 — Patient story features (via TV, use TV weight)
  "WAFF 48 (NBC) — DuPont feature": 1.2, "WAFF 48 (NBC) — Krejci feature": 1.2,
  "WAFF 48 (NBC) — cancer patient": 1.2, "WAFF 48 (NBC) — health navigator": 1.2,
  // Tier 5 — Organic social (0.7)
  "Social media (community reaction)": 0.7, "Social media (Highlands exit reaction)": 0.7,
  "Social media (resolution reaction)": 0.7,
  // Tier 6 — Owned/party media (0.3)
  "Huntsville Hospital (public statement)": 0.3, "Huntsville Hospital (patient advisory)": 0.3,
  "Huntsville Hospital (press release)": 0.3, "Huntsville Hospital (Facebook)": 0.3,
  "es.uhc.com/huntsville": 0.3, "UnitedHealthcare (public statement)": 0.3,
  "UHC employer notification": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "PEEHIP / SEIB": 1.3, "Health Care Authority of City of Huntsville": 1.3,
  "Helen Keller Hospital (network exit)": 1.3, "Highlands Medical Center (network exit)": 1.3,
  "Alabama DOI (no formal action)": 1.3,
  "UHC dispute pattern (HCA, Prisma, UNC, M Health)": 1.3,
  "CEO Jeff Samz (agreement announcement)": 1.3,
  // Tier 8 — Employer (1.5)
  "North Alabama employer reaction": 1.5,
};

const SEARCH_TRENDS = [
  { week: "2024-10-01", interest: 5 },
  { week: "2024-10-10", interest: 70 },
  { week: "2024-10-15", interest: 85 },
  { week: "2024-10-23", interest: 65 },
  { week: "2024-10-31", interest: 55 },
  { week: "2024-11-07", interest: 75 },
  { week: "2024-11-13", interest: 100 },
  { week: "2024-11-14", interest: 100 },
  { week: "2024-11-20", interest: 80 },
  { week: "2024-11-28", interest: 10 },
];

export default {
  // Identity
  providerKey: "huntsville",
  payorKey: "uhc",
  providerName: "Huntsville Hospital Health System",
  payorName: "UnitedHealthcare",
  providerShort: "HHHS",
  payorShort: "UHC",
  navShort: "Huntsville v. UHC",
  title: "Huntsville Hospital vs UnitedHealthcare",
  subtitle: "Contract dispute \u00b7 Resolved November 20, 2024",
  gradientId: "huntsvilleuhc",

  // Dates
  monitorStart: "October 1, 2024",
  monitorEnd: "November 30, 2024",
  disputePublicDate: "2024-10-10",

  // Colors
  colors: {
    providerColor: "#1B4D8E",
    payorColor: "#8B2332",
    neutral: "#64748B",
    accent: "#1B4D8E",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#1B4D8E", "#465E85", "#8B2332"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"huntsville hospital unitedhealthcare" \u00b7 weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 2.14,
    nationalMedian: 1.0,
    networkComplaints: 1847,
    priorYearComplaints: 1205,
    regulatorAction: "No formal Alabama Department of Insurance action. PEEHIP and SEIB confirmed continued coverage commitments for public employees. Health Care Authority of City of Huntsville monitored but did not formally intervene.",
    signalRead: "UHC's national complaint index remains elevated (2.14x median) driven by multi-state provider disputes. The 75% higher denial rate cited by HHHS aligns with broader provider complaints. Pattern of simultaneous disputes with HCA, Prisma, UNC, and M Health suggests systemic UHC strategy rather than HHHS-specific issue.",
  },

  // Executive summary
  executiveSummary: {
    statement: "The dispute resolved via agreement on November 13 — one day before the contract termination deadline — and was finalized November 20 as a multi-year deal. Two affiliate hospitals (Helen Keller, Highlands) experienced actual network exits during the dispute, creating concrete patient harm that strengthened HHHS's negotiating position.",
    keyMessages: [
      "HHHS's '75% higher denial rate' framing is the stickiest factual counter to UHC's pricing narrative — it shifts blame from cost to coverage behavior.",
      "Danielle DuPont (expecting mother, <2 months from delivery) was the most impactful patient story — 'I feel like I'm the one being punished' is an impossible quote for UHC to counter.",
      "UHC's $32.4B annual earnings undercuts its 'affordability' argument when juxtaposed with denial rates and underpayment claims.",
      "Pattern of simultaneous UHC disputes nationally (HCA, Prisma, UNC, M Health) undermines 'HHHS is uniquely expensive' framing and suggests corporate cost-cutting strategy.",
    ],
    marcomm: [
      "<strong>Anchor institution leverage is decisive.</strong> HHHS operates 14 hospitals with ~2,500 beds serving 1.3M people. In North Alabama, there is no viable alternative network. UHC cannot credibly threaten to move patients elsewhere.",
      "<strong>Rural facility exits created real consequences.</strong> Helen Keller (Oct 15) and Highlands (Oct 31) leaving the network moved the dispute from theoretical to concrete. Patients in the Shoals and DeKalb County had genuinely diminished access — powerful evidence for HHHS's position.",
      "<strong>Pregnant women and cancer patients are unassailable patient advocates.</strong> DuPont (expecting), Krejci (lupus/cancer survivor), and unnamed cancer patients created an emotional narrative UHC could not match with corporate messaging about 'affordability.'",
      "<strong>Full local media saturation from day one.</strong> All four major Huntsville TV stations plus regional print outlets covered the announcement simultaneously — HHHS achieved total market awareness within 24 hours. UHC's counter-narrative via es.uhc.com/huntsville could not compete with local broadcast dominance.",
    ],
  },
  channelTakeaways: {
    media: [
      "WAFF 48 (NBC) was the dominant outlet — broke the story, featured every major patient story, and provided near-daily coverage during critical weeks.",
      "Full TV market saturation (NBC, CBS, ABC, Fox) on announcement day ensured 100% community awareness of HHHS framing before UHC could respond.",
      "Trade press (Becker's, HealthLeaders, InsuranceNewsNet) connected HHHS dispute to national UHC pattern — elevated local story to industry trend.",
      "Regional print saturation (Decatur Daily, Times-Journal, Elk Valley Times, Athens News Courier) ensured every HHHS community was covered, including rural areas.",
    ],
    social: [
      "Facebook comment sections became primary venue for patient anxiety and anti-UHC sentiment — older demographic aligns with hospital patient base.",
      "HHHS's ~19,500 employees created massive organic social amplification — nearly every Huntsville family has a personal connection to the system.",
      "Highlands Medical Center exit (Oct 31) generated intense rural social media reaction — 'Where do we go?' framing in communities with few alternatives.",
      "Resolution posts generated relief sentiment but residual anger at UHC for community disruption lingered in comment sections.",
    ],
    stakeholder: [
      "PEEHIP/SEIB coverage commitments for public employees reduced immediate patient disruption but highlighted UHC's massive public-sector footprint in Alabama.",
      "Helen Keller Hospital (Oct 15) and Highlands Medical Center (Oct 31) network exits were the most consequential stakeholder actions — created concrete disruption.",
      "Alabama DOI silence contrasts with more activist regulators in other states — no formal consumer protection intervention.",
      "UHC's simultaneous disputes with HCA, Prisma, UNC, and M Health provided pattern evidence that trade press used to frame UHC as serial aggressor.",
    ],
    employer: [
      "North Alabama employer base includes defense contractors, NASA workforce, and tech sector — sophisticated employers who understand network adequacy.",
      "UHC's '>20% above Alabama average' claim is their strongest employer-facing argument, but HHHS's regional monopoly means employers have no practical alternative.",
      "Self-insured employers face direct cost impact from rate changes — UHC's cost framing resonates here more than anywhere else.",
    ],
  },
  timeline: [
    { date: "2024-10-10", type: "newsBreak", label: "News breaks publicly" },
    { date: "2024-10-15", type: "termination", label: "Helen Keller Hospital exits network" },
    { date: "2024-11-14", type: "agreement", label: "Agreement reached" },
  ],
};
