// Jefferson Health vs Cigna — PR War Room Config
// Dispute period: Mar 15–Apr 4, 2025 (20 days). Resolved retroactive to Mar 15, 2025.

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2025-03-12",
    source: "Bucks County Herald",
    url: "https://www.buckscountyherald.com/news/health-wellness/jefferson-health-now-out-of-network-for-cigna-members/article_c01c9ac0-01cf-11f0-b5be-5b1a19fae111.html",
    sourceType: "news",
    channel: "media",
    headline: "Jefferson Health–Cigna contract deadline looms — patients brace for potential out-of-network shift",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Pre-deadline local coverage. Bucks County Herald reaches suburban Philadelphia audience heavily reliant on Jefferson facilities. Article frames Cigna as forcing the issue by refusing adequate rate increases.",
  },
  {
    id: 2,
    date: "2025-03-15",
    source: "Philadelphia Inquirer",
    url: "https://www.inquirer.com/health/jefferson-out-of-network-cigna-20250315.html",
    sourceType: "news",
    channel: "media",
    headline: "Jefferson Health drops out of Cigna network — 32 hospitals, 700+ locations affected across Philadelphia region",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "FLAGSHIP PHILLY COVERAGE. Philadelphia Inquirer is the paper of record. '32 hospitals, 700+ locations' scale framing maximizes perceived disruption. Jefferson's post-LVHN merger size makes this the largest provider-insurer disruption in Philadelphia history.",
  },
  {
    id: 3,
    date: "2025-03-15",
    source: "6ABC/WPVI",
    url: "https://6abc.com/post/cigna-now-network-jefferson-health-what-know-patients-can-do/16058617/",
    sourceType: "tv",
    channel: "media",
    headline: "Jefferson Health now out of network with Cigna — patients scramble for alternatives",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "6ABC is #1-rated local news in Philadelphia market. Day-of out-of-network coverage. Patient anxiety framing. Also reported on TikTok video from Dr. Pribitkin urging patients to lobby Cigna — amplified owned media into earned media.",
  },
  {
    id: 4,
    date: "2025-03-15",
    source: "WFMZ",
    url: "https://www.wfmz.com/news/area/lehighvalley/jefferson-health-now-out-of-network-for-cigna-members/article_9bdbacf7-0039-41ab-acab-a12d62b17283.html",
    sourceType: "tv",
    channel: "media",
    headline: "Jefferson Health goes out of network with Cigna; LVHN clarifies its contract is separate and unaffected",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Lehigh Valley market coverage. Key detail: LVHN (owned by Jefferson) maintained separate Cigna contract and remained in-network. Important clarification for LVHN patients. WFMZ reaches Allentown-Bethlehem-Easton market.",
  },
  {
    id: 5,
    date: "2025-03-17",
    source: "PhillyVoice",
    url: "https://www.phillyvoice.com/cigna-jefferson-health-contract-negotiations-out-of-network/",
    sourceType: "news",
    channel: "media",
    headline: "What Jefferson Health patients need to know after Cigna contract lapses — detailed FAQ",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Detailed explainer article. Notes Cigna reimbursement increased only ~3% since 2020 while Hospital Wage Index rose 20% and CPI-U rose 21%. Jefferson framing: 'We cannot continue to absorb these costs.' Service journalism format builds sympathy for Jefferson.",
  },
  {
    id: 6,
    date: "2025-03-15",
    source: "Healthcare Dive",
    url: "https://www.healthcaredive.com/news/jefferson-health-cigna-contract-dispute/742842/",
    sourceType: "news",
    channel: "media",
    headline: "Jefferson Health–Cigna contract spat leaves Philadelphia patients out of network",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National trade press. 'Contract spat' framing minimizes both sides. Notes Jefferson's $196M operating loss in FY2025 and $15.8B revenue post-LVHN merger. Trade audience of hospital executives.",
  },
  {
    id: 7,
    date: "2025-03-17",
    source: "Patch Abington",
    sourceType: "news",
    channel: "media",
    headline: "Jefferson Health patients in Abington area face out-of-network Cigna costs — local impact story",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Hyperlocal coverage. Abington Hospital (Jefferson) is anchor institution in Montgomery County. Local patient stories. Patch format drives high local engagement.",
  },
  {
    id: 8,
    date: "2025-03-19",
    source: "Patch Abington",
    sourceType: "news",
    channel: "media",
    headline: "Cigna–Jefferson dispute update: no resolution in sight as patients call for action",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Follow-up coverage. 'No resolution in sight' sustains pressure. Patient advocacy angle.",
  },
  {
    id: 9,
    date: "2025-03-17",
    source: "NewtownPANow",
    url: "https://newtownpanow.com/2025/03/18/contract-dispute-leaves-jefferson-health-cigna-patients-in-limbo/",
    sourceType: "news",
    channel: "media",
    headline: "Patients in limbo as Jefferson Health–Cigna contract expires — Bucks County families affected",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "'Patients in limbo' framing. Bucks County suburban families — key demographic for both Jefferson and Cigna commercial plans. Newtown/Council Rock area relies heavily on Jefferson facilities.",
  },
  {
    id: 10,
    date: "2025-03-18",
    source: "North Penn Now",
    url: "https://northpennnow.com/news/2025/mar/18/jefferson-health-cigna-fail-to-reach-contract-agreement/",
    sourceType: "news",
    channel: "media",
    headline: "North Penn residents caught in Jefferson–Cigna crossfire — local providers affected",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Lansdale/North Penn hyperlocal. Jefferson has significant presence in this corridor. Community journalism format with reader comments.",
  },
  {
    id: 11,
    date: "2025-03-17",
    source: "LevittownNow",
    url: "https://levittownnow.com/2025/03/17/jefferson-health-cigna-fail-to-reach-contract-agreement/",
    sourceType: "news",
    channel: "media",
    headline: "Jefferson Health out of Cigna network — Lower Bucks County patients seek guidance",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Lower Bucks County hyperlocal. Blue-collar suburban demographic especially sensitive to out-of-network cost exposure.",
  },
  {
    id: 12,
    date: "2025-03-16",
    source: "Glenside Local",
    url: "https://glensidelocal.com/jefferson-health-now-out-of-network-for-cigna-members-following-failed-contract-negotiations/",
    sourceType: "news",
    channel: "media",
    headline: "Abington–Jefferson campus goes out of network with Cigna — Glenside patients react",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Glenside hyperlocal. Abington Hospital is literally in this community's backyard. Patient reaction stories. High local engagement.",
  },
  {
    id: 13,
    date: "2025-03-20",
    source: "Glenside Local",
    url: "https://glensidelocal.com/jefferson-health-again-in-network-for-cigna-members-following-contract-negotiations/",
    sourceType: "news",
    channel: "media",
    headline: "Jefferson–Cigna dispute drags on — Glenside residents share frustrations",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Follow-up hyperlocal piece. 'Drags on' framing at day 5 creates time pressure narrative.",
  },
  {
    id: 14,
    date: "2025-03-15",
    source: "Bucks County Herald",
    url: "https://www.buckscountyherald.com/news/health-wellness/jefferson-health-now-out-of-network-for-cigna-members/article_c01c9ac0-01cf-11f0-b5be-5b1a19fae111.html",
    sourceType: "news",
    channel: "media",
    headline: "Jefferson Health officially out of Cigna network — Bucks County patients face uncertainty",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Day-of coverage from Bucks County Herald. 'Uncertainty' framing sustains patient anxiety.",
  },
  {
    id: 15,
    date: "2025-03-18",
    source: "MontCo Today",
    url: "https://montco.today/2025/04/jefferson-health-cigna-agreement/",
    sourceType: "news",
    channel: "media",
    headline: "Montgomery County patients caught between Jefferson Health and Cigna — what to know",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Montgomery County digital outlet. Service journalism format. Jefferson has multiple MontCo facilities including Abington, Lansdale, Einstein.",
  },
  {
    id: 16,
    date: "2025-03-18",
    source: "DelCo Today",
    sourceType: "news",
    channel: "media",
    headline: "Delaware County Jefferson patients lose in-network Cigna access — dispute continues",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Delaware County coverage. Jefferson has significant DelCo presence. 'Lose access' framing places blame on Cigna's refusal to agree to rates.",
  },
  {
    id: 17,
    date: "2025-03-19",
    source: "Vista Today",
    sourceType: "news",
    channel: "media",
    headline: "Jefferson Health–Cigna breakdown affects Chester County patients — alternatives explored",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Chester County digital outlet. Practical 'alternatives' framing. Chester County is affluent suburban — these patients have choices, which increases Cigna pressure.",
  },
  {
    id: 18,
    date: "2025-03-17",
    source: "MoreThanTheCurve",
    url: "https://morethanthecurve.com/jefferson-health-again-in-network-for-cigna-members-following-contract-negotiations/",
    sourceType: "news",
    channel: "media",
    headline: "Conshohocken-area patients impacted by Jefferson–Cigna network disruption",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Conshohocken/Plymouth Meeting hyperlocal. Young professional suburban demographic. High social media sharing from this outlet.",
  },
  {
    id: 19,
    date: "2025-03-16",
    source: "Yahoo Finance",
    url: "https://finance.yahoo.com/news/jefferson-health-goes-network-cigna-140719294.html",
    sourceType: "news",
    channel: "media",
    headline: "Jefferson Health drops Cigna — 32-hospital system goes out of network in Philadelphia market",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "National syndication via Yahoo Finance. Investor/financial audience. '32-hospital system' scale framing. Notes Jefferson's $15.8B revenue and $196M operating loss. High reach due to Yahoo distribution.",
  },
  {
    id: 20,
    date: "2025-03-17",
    source: "NewsBreak",
    sourceType: "news",
    channel: "media",
    headline: "Jefferson Health and Cigna fail to reach deal — patients out of network across region",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "NewsBreak syndication reaches broad mobile audience. Algorithm-driven distribution amplifies patient anxiety stories. High engagement with local health content.",
  },
  {
    id: 21,
    date: "2025-03-20",
    source: "HealthLeaders",
    url: "https://www.healthleadersmedia.com/ceo/why-jefferson-health-went-out-network-cigna",
    sourceType: "news",
    channel: "media",
    headline: "Why Jefferson Health went out of network with Cigna — deliberate strategy to leverage public opinion against insurer",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "KEY TRADE ANALYSIS. HealthLeaders explicitly identified Jefferson's deliberate strategy to 'leverage public opinion against the insurer.' Notes pattern of provider systems using PR pressure campaigns. Hospital executive audience recognizes the playbook.",
  },
  {
    id: 22,
    date: "2025-03-16",
    source: "DistilInfo HealthPlan",
    url: "https://distilinfo.com/healthplan/jefferson-health-cigna/",
    sourceType: "news",
    channel: "media",
    headline: "Jefferson Health exits Cigna network — Philadelphia's largest health system goes out of network",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Health plan trade press. Factual reporting. 'Philadelphia's largest health system' framing emphasizes scale of disruption.",
  },
  {
    id: 23,
    date: "2025-04-04",
    source: "Philadelphia Inquirer",
    url: "https://www.inquirer.com/health/jefferson-in-network-cigna-contract-20250404.html",
    sourceType: "news",
    channel: "media",
    headline: "Jefferson Health and Cigna reach deal — patients back in network retroactive to March 15",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution coverage from paper of record. Retroactive to March 15 means no patient claims will be processed at out-of-network rates. Multi-year agreement. Neither side disclosed specific rate terms.",
  },
  {
    id: 24,
    date: "2025-04-04",
    source: "6ABC/WPVI",
    url: "https://6abc.com/post/jefferson-health-reaches-multi-year-agreement-cigna/16129529/",
    sourceType: "tv",
    channel: "media",
    headline: "Jefferson Health back in network with Cigna — 20-day dispute ends with new multi-year contract",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution coverage on top-rated Philly news. '20-day dispute' framing. Relief angle for patients. Retroactive coverage terms highlighted.",
  },
  {
    id: 25,
    date: "2025-04-04",
    source: "WFMZ",
    url: "https://www.wfmz.com/news/area/lehighvalley/jefferson-health-reaches-deal-with-cigna-all-health-network-providers-to-remain-in-network/article_f0839e2c-4960-4fed-b783-3743b11d70b0.html",
    sourceType: "tv",
    channel: "media",
    headline: "Deal reached: Jefferson Health and Cigna agree to new contract after 20-day standoff",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Lehigh Valley resolution coverage. 'Standoff' language. Notes LVHN was never affected due to separate contract.",
  },
  {
    id: 26,
    date: "2025-04-04",
    source: "Becker's Hospital Review",
    url: "https://www.beckershospitalreview.com/finance/cigna-jefferson-health-split/",
    sourceType: "news",
    channel: "media",
    headline: "Jefferson Health, Cigna reach multi-year agreement ending network dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press resolution coverage. Notes multi-year agreement. Hospital executive audience. Factual reporting.",
  },
  {
    id: 27,
    date: "2025-04-04",
    source: "HealthLeaders",
    url: "https://www.healthleadersmedia.com/payer/jefferson-health-reaches-multi-year-agreement-cigna",
    sourceType: "news",
    channel: "media",
    headline: "Jefferson Health–Cigna dispute ends with multi-year agreement — public pressure campaign worked",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "HealthLeaders resolution analysis. Explicitly frames outcome as validation of Jefferson's PR pressure strategy. Notes retroactive coverage and multi-year term as Jefferson wins.",
  },
  {
    id: 28,
    date: "2025-04-05",
    source: "Bucks County Herald",
    url: "https://www.buckscountyherald.com/news/health-wellness/jefferson-health-reaches-settlement-with-cigna-healthcare/article_5f527666-7a48-46d4-b74b-746acb55af6e.html",
    sourceType: "news",
    channel: "media",
    headline: "Jefferson–Cigna settlement brings relief to Bucks County patients — retroactive coverage confirmed",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Local resolution coverage. Relief framing. Third Bucks County Herald article across dispute lifecycle — full arc coverage.",
  },
  // === JEFFERSON OWNED MEDIA ===
  {
    id: 29,
    date: "2025-03-14",
    source: "JeffersonHealth.org — Out-of-Network Notice",
    url: "https://www.jeffersonhealth.org/about-us/news/2025/03/cigna-network",
    sourceType: "owned",
    channel: "media",
    headline: "Jefferson publishes patient notice with Dr. Pribitkin video urging patients to contact Cigna",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "KEY PR MOVE. Dr. Edmund Pribitkin (Chief Physician Executive) recorded video directing patients to lobby Cigna. Physician-as-advocate framing. Video shared on TikTok and picked up by 6ABC. Deliberate strategy to weaponize patient base against insurer.",
  },
  {
    id: 30,
    date: "2025-04-04",
    source: "JeffersonHealth.org — Agreement Announcement",
    url: "https://www.jeffersonhealth.org/about-us/news/2025/04/cigna-network",
    sourceType: "owned",
    channel: "media",
    headline: "Jefferson announces new multi-year Cigna agreement — retroactive to March 15",
    frameAdoption: "jefferson",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution announcement. Victory framing — retroactive coverage and multi-year term presented as Jefferson's success in fighting for fair rates. Notes ~65,000 employees and 32 hospitals protected.",
  },
  {
    id: 31,
    date: "2025-03-16",
    source: "LVHN.org — Clarification",
    url: "https://www.lvhn.org/news/lvhn-continues-accept-cigna",
    sourceType: "owned",
    channel: "media",
    headline: "LVHN clarifies: Lehigh Valley Health Network maintains separate Cigna contract — patients unaffected",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "IMPORTANT CLARIFICATION. LVHN (owned by Jefferson since merger) kept separate contract with Cigna and stayed in-network. Limits geographic scope of disruption to Philadelphia metro only. Reduces pressure on Cigna from Lehigh Valley patients.",
  },
  // === CIGNA OWNED MEDIA ===
  {
    id: 32,
    date: "2025-03-15",
    source: "Cigna (public statement)",
    sourceType: "owned",
    channel: "media",
    headline: "Cigna: Jefferson demanding 'unreasonable rate hike that would raise health costs for employers and families'",
    frameAdoption: "cigna",
    sentiment: "negative_jefferson",
    patientStory: false,
    blameDirection: "jefferson",
    reachEstimate: "medium",
    notes: "Cigna's primary public defense. 'Unreasonable rate hike demands' framing attempts to position Jefferson as cost driver. Notes Cigna offered 'fair and competitive' rates. Corporate defensive tone. No patient voices or physician advocates — pure corporate messaging.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 33,
    date: "2025-03-15",
    source: "Dr. Pribitkin TikTok video",
    sourceType: "social",
    channel: "social",
    headline: "Jefferson Chief Physician Executive posts TikTok urging patients to call Cigna — goes viral in Philly",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "CRITICAL SOCIAL ASSET. Dr. Edmund Pribitkin's TikTok video crossed from owned to social to earned media (picked up by 6ABC). Physician-as-patient-advocate framing is powerful. Directs patient anger at Cigna. Unusual for C-suite physician to use TikTok — signals coordinated strategy.",
  },
  {
    id: 34,
    date: "2025-03-16",
    source: "X/Twitter (patient reaction)",
    sourceType: "social",
    channel: "social",
    headline: "Philadelphia patients share anxiety about losing Jefferson providers — #JeffersonCigna trending locally",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Organic patient social reaction. Philadelphia is a tight-knit media market — local health disputes spread fast on social. Patient stories about upcoming appointments and established provider relationships.",
  },
  {
    id: 35,
    date: "2025-03-17",
    source: "Facebook (community groups)",
    sourceType: "social",
    channel: "social",
    headline: "Montgomery County and Bucks County Facebook groups flooded with Jefferson–Cigna questions",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Suburban community Facebook groups. Parents asking about pediatrician access, upcoming procedures, specialist referrals. Facebook skews older — key commercial insurance demographic. High engagement in local community groups.",
  },
  {
    id: 36,
    date: "2025-03-18",
    source: "Reddit r/philadelphia",
    sourceType: "social",
    channel: "social",
    headline: "Reddit thread: 'My entire family's healthcare is Jefferson — what do we do about Cigna?'",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Reddit Philly community. Detailed personal stories about family provider relationships. Comments overwhelmingly blame Cigna. Thread links to Pribitkin video and Jefferson's cost data.",
  },
  // === BLOG / COMMUNITY ENTRIES ===
  {
    id: 37,
    date: "2025-03-16",
    source: "Center City Pediatrics Blog",
    sourceType: "owned",
    channel: "media",
    headline: "Center City Pediatrics: Important changes for families with Cigna insurance — Jefferson providers affected",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Pediatric practice blog. Direct-to-parent communication. Children's healthcare disruption is highly emotional framing. Practice advising families on navigating out-of-network period.",
  },
  {
    id: 38,
    date: "2025-03-25",
    source: "Center City Pediatrics Blog",
    sourceType: "owned",
    channel: "media",
    headline: "Center City Pediatrics update: Jefferson–Cigna negotiations continue — guidance for affected families",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Mid-dispute update. Practice continuing to field parent questions. 'Negotiations continue' maintains pressure narrative.",
  },
  {
    id: 39,
    date: "2025-04-05",
    source: "Center City Pediatrics Blog",
    sourceType: "owned",
    channel: "media",
    headline: "Center City Pediatrics: Jefferson–Cigna dispute resolved — retroactive coverage for all visits",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Resolution post. Relief for families. Confirms retroactive coverage means no unexpected bills. Closes the arc for concerned parents.",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 40,
    date: "2025-03-15",
    source: "Dr. Edmund Pribitkin, Chief Physician Executive",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Jefferson CPE: Cigna reimbursement up only ~3% since 2020 while Hospital Wage Index rose 20% and CPI-U rose 21%",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "KEY DATA POINT. 3% vs 20-21% comparison is Jefferson's stickiest argument. Hospital Wage Index is an objective CMS metric. CPI-U is Bureau of Labor Statistics data. Cigna's reimbursement hasn't kept pace with any reasonable cost benchmark. Pribitkin as physician-executive carries dual credibility.",
  },
  {
    id: 41,
    date: "2025-03-17",
    source: "David Rosenberg, patient (Fairmount)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "David Rosenberg: wife's providers all Jefferson, upcoming mammogram critical due to family breast cancer history",
    frameAdoption: "jefferson",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "NAMED PATIENT STORY. Fairmount resident. Wife's providers all within Jefferson network. Upcoming mammogram — family history of breast cancer makes delay potentially dangerous. Children's pediatrician also Jefferson. Entire family healthcare ecosystem disrupted. Maximally sympathetic — cancer screening delay angle.",
  },
  {
    id: 42,
    date: "2025-03-18",
    source: "Cigna national dispute pattern",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Cigna in pattern of national disputes: Hartford, Hackensack Meridian, UNC, Tenet, Baptist, Bon Secours, Piedmont",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "PATTERN EVIDENCE. Cigna has been in provider disputes with major systems across the country — Hartford HealthCare (CT), Hackensack Meridian (NJ), UNC Health (NC), Tenet (multi-state), Baptist Health (FL), Bon Secours Mercy (multi-state), Piedmont Healthcare (GA). Pattern suggests corporate strategy of hardball negotiation, not Jefferson-specific unreasonableness.",
  },
  {
    id: 43,
    date: "2025-03-20",
    source: "PA Insurance Dept (non-intervention)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Pennsylvania Insurance Department does not intervene in Jefferson–Cigna dispute — short duration cited",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "REGULATORY SILENCE. No PA Insurance Department intervention. Short 20-day duration likely a factor — insufficient time for regulatory machinery to engage. Commercial plans only (Medicare Advantage unaffected) reduces political urgency. Contrast with CT regulator intervention in Hartford/Cigna dispute.",
  },
  {
    id: 44,
    date: "2025-03-15",
    source: "Jefferson financial context",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Jefferson Health: $15.8B revenue post-LVHN merger, $196M operating loss FY2025 — financial pressure behind dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "FINANCIAL CONTEXT. $196M operating loss provides credibility for Jefferson's claim that current Cigna rates are unsustainable. $15.8B revenue and 32 hospitals post-merger means Jefferson has significant market leverage but also significant fixed costs. ~65,000 employees depend on adequate reimbursement.",
  },
  {
    id: 45,
    date: "2025-03-16",
    source: "LVHN separate contract (stakeholder context)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "LVHN's separate Cigna contract limited Jefferson's leverage — Cigna could point to continued LVHN access",
    frameAdoption: "cigna",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "STRATEGIC NUANCE. LVHN maintaining separate in-network status with Cigna cut both ways: reduced patient disruption in Lehigh Valley but also reduced Jefferson's total pressure on Cigna. Cigna could argue patients had alternative Jefferson-affiliated access via LVHN.",
  },
  {
    id: 46,
    date: "2025-03-15",
    source: "Medicare Advantage exclusion",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Medicare Advantage plans NOT affected by Jefferson–Cigna dispute — commercial plans only",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "IMPORTANT SCOPE LIMITER. Medicare Advantage patients unaffected. This is significant because it reduces political pressure (seniors vote, lobby, contact representatives). Dispute limited to commercial/employer plans — primarily working-age adults and families.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 47,
    date: "2025-03-15",
    source: "Cigna employer notification",
    sourceType: "owned",
    channel: "employer",
    headline: "Cigna notifies Philadelphia-area employers: Jefferson Health no longer in network — alternative providers available",
    frameAdoption: "cigna",
    sentiment: "negative_jefferson",
    patientStory: false,
    blameDirection: "jefferson",
    reachEstimate: "medium",
    notes: "Employer channel. Cigna frames Jefferson as choosing to leave network. 'Alternative providers available' messaging attempts to minimize perceived disruption. But in Philadelphia, Jefferson's 32-hospital footprint makes alternatives limited for many employees.",
  },
  {
    id: 48,
    date: "2025-03-18",
    source: "Philadelphia employer benefits advisors",
    sourceType: "news",
    channel: "employer",
    headline: "Philadelphia benefits brokers field surge of employer questions about Jefferson–Cigna impact on employee plans",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Employer anxiety channel. Philadelphia-area employers with significant Jefferson-using employee populations scrambling for guidance. HR departments fielding employee questions. Benefits consultants issuing advisories.",
  },
];

const LABELS = {
  frameAdoption: { jefferson: "Jefferson Frame", cigna: "Cigna Frame", balanced: "Balanced" },
  sentiment: {
    negative_cigna: "Anti-Cigna",
    negative_jefferson: "Anti-Jefferson",
    neutral: "Neutral",
    positive_cigna: "Pro-Cigna",
    positive_jefferson: "Pro-Jefferson",
  },
  blameDirection: { cigna: "Blames Cigna", jefferson: "Blames Jefferson", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National record (1.5)
  "Yahoo Finance": 1.5, "Healthcare Dive": 1.5,
  // Tier 2 — Regional authority (1.2)
  "Philadelphia Inquirer": 1.2, "6ABC/WPVI": 1.2, "WFMZ": 1.2, "PhillyVoice": 1.2,
  // Tier 3 — Trade/niche (1.0)
  "Becker's Hospital Review": 1.0, "HealthLeaders": 1.0, "DistilInfo HealthPlan": 1.0,
  "NewsBreak": 1.0,
  // Tier 4 — Hyperlocal (0.8)
  "Patch Abington": 0.8, "NewtownPANow": 0.8, "North Penn Now": 0.8, "LevittownNow": 0.8,
  "Glenside Local": 0.8, "Bucks County Herald": 0.8, "MontCo Today": 0.8, "DelCo Today": 0.8,
  "Vista Today": 0.8, "MoreThanTheCurve": 0.8,
  // Tier 5 — Organic social (0.7)
  "Dr. Pribitkin TikTok video": 0.7, "X/Twitter (patient reaction)": 0.7,
  "Facebook (community groups)": 0.7, "Reddit r/philadelphia": 0.7,
  // Tier 6 — Owned/party media (0.3)
  "JeffersonHealth.org — Out-of-Network Notice": 0.3, "JeffersonHealth.org — Agreement Announcement": 0.3,
  "LVHN.org — Clarification": 0.3, "Cigna (public statement)": 0.3,
  "Center City Pediatrics Blog": 0.3, "Cigna employer notification": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "Dr. Edmund Pribitkin, Chief Physician Executive": 1.3,
  "David Rosenberg, patient (Fairmount)": 1.3,
  "Cigna national dispute pattern": 1.3, "PA Insurance Dept (non-intervention)": 1.3,
  "Jefferson financial context": 1.3, "LVHN separate contract (stakeholder context)": 1.3,
  "Medicare Advantage exclusion": 1.3,
  // Tier 8 — Employer/Benefits (1.5)
  "Philadelphia employer benefits advisors": 1.5,
};

const SEARCH_TRENDS = [
  { week: "2025-02-03", interest: 5 }, { week: "2025-02-10", interest: 5 }, { week: "2025-02-17", interest: 5 },
  { week: "2025-02-24", interest: 5 }, { week: "2025-03-03", interest: 15 }, { week: "2025-03-10", interest: 80 },
  { week: "2025-03-17", interest: 100 }, { week: "2025-03-24", interest: 50 }, { week: "2025-03-31", interest: 90 },
  { week: "2025-04-07", interest: 10 }, { week: "2025-04-14", interest: 10 }, { week: "2025-04-21", interest: 5 },
];

export default {
  active: false,
  // Identity
  providerKey: "jefferson",
  payorKey: "cigna",
  providerName: "Jefferson Health",
  payorName: "Cigna",
  providerShort: "Jefferson",
  payorShort: "Cigna",
  navShort: "Jefferson v. Cigna",
  title: "Jefferson Health vs Cigna",
  subtitle: "Contract dispute \u00B7 Resolved April 4, 2025",
  gradientId: "jeffersoncigna",

  // Dates
  monitorStart: "February 1, 2025",
  monitorEnd: "April 30, 2025",
  disputePublicDate: "2025-03-12",

  // Colors
  colors: {
    providerColor: "#003DA5",
    payorColor: "#E87722",
    neutral: "#64748B",
    accent: "#003DA5",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#003DA5", "#4A6B9A", "#E87722"],
  yAxisWidth: 82,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"jefferson health cigna" \u00B7 weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.72,
    nationalMedian: 1.0,
    networkComplaints: 1134,
    priorYearComplaints: 892,
    regulatorAction: "PA Insurance Department did not intervene. Short 20-day dispute duration and limitation to commercial plans (Medicare Advantage excluded) reduced political urgency. No formal investigation opened.",
    signalRead: "Cigna's national complaint index is elevated (1.72x median) driven by multi-state provider disputes. The 27% increase in network complaints reflects a pattern of hardball negotiations with major health systems nationally, including Hartford HealthCare, Hackensack Meridian, UNC, and others.",
  },

  talkingPoints: {
    provider: [
      { name: "3% vs 20% reimbursement gap", keywords: ["3%", "20%", "Hospital Wage Index", "CPI-U", "reimbursement.*since 2020"] },
      { name: "32 hospitals / 700+ locations", keywords: ["32 hospital", "700\\+", "700 location", "largest.*health system"] },
      { name: "$196M operating loss", keywords: ["\\$196M", "196.*million", "operating loss", "financial pressure"] },
      { name: "Dr. Pribitkin TikTok / physician advocate", keywords: ["Pribitkin", "TikTok", "physician.*advocate", "Chief Physician", "CPE"] },
      { name: "Hyperlocal media saturation", keywords: ["Patch", "Glenside Local", "Bucks County Herald", "MontCo Today", "hyperlocal", "suburban"] },
      { name: "Patient stories / family impact", keywords: ["Rosenberg", "mammogram", "breast cancer", "pediatric", "children.*pediatrician", "family.*healthcare"] },
      { name: "Cigna national dispute pattern", keywords: ["pattern", "Hartford", "Hackensack", "UNC", "Tenet", "Baptist", "Bon Secours", "Piedmont"] },
      { name: "Retroactive coverage victory", keywords: ["retroactive", "back.*network", "multi-year agreement", "resolution"] },
    ],
    payor: [
      { name: "Unreasonable rate hike", keywords: ["unreasonable.*rate", "rate hike", "raise.*cost", "health costs"] },
      { name: "Fair and competitive rates", keywords: ["fair.*competitive", "fair.*rate", "competitive.*rate"] },
      { name: "Alternative providers available", keywords: ["alternative.*provider", "robust.*provider", "LVHN.*separate", "LVHN.*unaffected"] },
      { name: "Employer/affordability framing", keywords: ["employer", "affordab", "families", "raise.*cost.*employer"] },
      { name: "Jefferson chose to leave", keywords: ["chose.*leave", "Jefferson.*decision", "chose.*out.*network"] },
    ],
  },

  // Executive summary
  executiveSummary: {
    statement: "The dispute lasted 20 days (Mar 15–Apr 4) and resolved with a multi-year agreement retroactive to March 15 — meaning no patients were ultimately billed at out-of-network rates. Jefferson's deliberate PR pressure campaign, anchored by Dr. Pribitkin's TikTok video and a wall of hyperlocal media coverage, forced Cigna back to the table.",
    keyMessages: [
      "Jefferson's '3% reimbursement increase vs 20% Hospital Wage Index rise since 2020' is the stickiest factual argument — objective CMS and BLS data that Cigna cannot dispute.",
      "Dr. Pribitkin's TikTok video directing patients to lobby Cigna was a calculated escalation that crossed from owned to social to earned media (6ABC pickup).",
      "LVHN's separate Cigna contract limited Jefferson's total leverage but also limited patient harm — a strategic trade-off.",
      "Cigna's pattern of national disputes (Hartford, Hackensack Meridian, UNC, Tenet, Baptist, Bon Secours, Piedmont) undermines 'Jefferson is uniquely unreasonable' framing.",
    ],
    marcomm: [
      "<strong>Hyperlocal media saturation was Jefferson's decisive weapon.</strong> Over a dozen suburban outlets (Patch, Bucks County Herald, Glenside Local, MontCo Today, etc.) created a drumbeat of patient anxiety stories that Cigna's corporate communications could not match.",
      "<strong>The physician-as-advocate playbook works.</strong> Dr. Pribitkin's TikTok video was the single most impactful communication asset — a physician executive personally directing patients to pressure the insurer is far more credible than any press release.",
      "<strong>Retroactive coverage was the face-saving exit ramp.</strong> Both sides could claim victory: Jefferson got a multi-year deal at presumably higher rates; Cigna could say no patients were actually harmed.",
      "<strong>Medicare Advantage exclusion was Cigna's safety valve.</strong> By keeping MA plans in-network, Cigna avoided the political firestorm of disrupting senior care — limiting exposure to commercial/employer plans where the PR calculus is less explosive.",
    ],
  },
  channelTakeaways: {
    media: [
      "Philadelphia Inquirer coverage on day one set the narrative frame — '32 hospitals, 700+ locations' scale framing dominated subsequent coverage.",
      "6ABC/WPVI as #1-rated Philly news amplified the Pribitkin TikTok video into mainstream earned media — the cross-platform jump was decisive.",
      "Hyperlocal outlets (Patch, Glenside Local, Bucks County Herald, MontCo Today, etc.) created geographic saturation that national outlets cannot replicate.",
      "HealthLeaders explicitly named Jefferson's 'leverage public opinion against the insurer' strategy — the playbook is now documented in trade press.",
    ],
    social: [
      "Dr. Pribitkin's TikTok was the breakout social asset — physician-executive on TikTok is novel and credible, earning 6ABC earned media pickup.",
      "Suburban Facebook community groups were the highest-engagement organic channel — parents asking about pediatricians and upcoming procedures.",
      "Reddit r/philadelphia thread generated detailed personal stories that reinforced Jefferson's framing.",
      "Cigna had no effective social media counter-strategy — corporate statements cannot compete with physician video and patient stories.",
    ],
    stakeholder: [
      "Dr. Pribitkin's 3% vs 20-21% reimbursement data was the most impactful factual argument — objective benchmarks that Cigna could not credibly dispute.",
      "David Rosenberg (Fairmount) as named patient — wife's mammogram with breast cancer family history, children's pediatrician — provided a maximally sympathetic human face.",
      "Cigna's national dispute pattern (7+ major systems) provided critical context that this is a corporate strategy, not a Jefferson-specific problem.",
      "PA Insurance Department non-intervention was notable — 20-day duration and commercial-only scope kept political pressure below regulatory threshold.",
    ],
    employer: [
      "Cigna's employer notifications framed Jefferson as choosing to leave — but employers with Jefferson-dependent workforces faced immediate HR headaches.",
      "Philadelphia-area benefits advisors fielded surge of employer questions — signals that Cigna's network reliability reputation took damage with employer clients.",
      "Retroactive coverage resolution neutralized the employer impact — but the disruption created lasting questions about Cigna network stability in Philadelphia market.",
    ],
  },
  arguments: {
    payor: [
      { phase: "Early (Mar 2025)", points: [
        "Claimed Jefferson was demanding an '<strong>unreasonable rate hike</strong> that would raise health costs for employers and families'",
        "Stated Cigna offered 'fair and competitive' rates",
        "Framed Jefferson as choosing to leave the network — employer notifications positioned Cigna as the victim",
      ] },
      { phase: "Mid-Dispute (Mar 2025)", points: [
        "Notified Philadelphia-area employers that Jefferson was no longer in network, emphasizing 'alternative providers available'",
        "Maintained corporate defensive tone throughout — <strong>no patient voices or physician advocates</strong> in any Cigna communications",
        "Could point to LVHN (Jefferson-owned) maintaining separate Cigna contract as evidence of continued access",
      ] },
      { phase: "Resolution (Apr 2025)", points: [
        "Agreed to retroactive coverage to March 15 — no patients ultimately billed at out-of-network rates",
        "Multi-year agreement terms not disclosed publicly",
      ] },
    ],
    provider: [
      { phase: "Early (Mar 2025)", points: [
        "Dr. Edmund Pribitkin (Chief Physician Executive): Cigna reimbursement increased <strong>only ~3% since 2020</strong> while Hospital Wage Index rose 20% and CPI-U rose 21%",
        "Cited Jefferson's <strong>$196 million operating loss</strong> in FY2025 as evidence current Cigna rates are unsustainable",
        "Published patient notice with Dr. Pribitkin <strong>TikTok video</strong> urging patients to contact Cigna directly",
      ] },
      { phase: "Mid-Dispute (Mar 2025)", points: [
        "Dr. Pribitkin's TikTok video went viral — crossed from owned to social to earned media (<strong>picked up by 6ABC</strong>)",
        "Saturated hyperlocal media: 12+ suburban outlets (Patch, Bucks County Herald, Glenside Local, MontCo Today) created drumbeat of patient anxiety coverage",
        "Named patient David Rosenberg: wife's mammogram critical due to <strong>family breast cancer history</strong>, children's pediatrician also Jefferson — entire family healthcare ecosystem disrupted",
      ] },
      { phase: "Resolution (Apr 2025)", points: [
        "Multi-year agreement <strong>retroactive to March 15</strong> — presented as Jefferson's victory in fighting for fair rates",
        "HealthLeaders explicitly credited Jefferson's '<strong>public pressure campaign</strong>' as the decisive factor",
      ] },
    ],
  },
  timeline: [
    { date: "2025-03-12", type: "newsBreak", label: "News breaks publicly" },
    { date: "2025-03-15", type: "termination", label: "Contract terminates" },
    { date: "2025-04-04", type: "agreement", label: "Agreement reached" },
  ],
};
