// Memorial Sloan Kettering vs UnitedHealthcare — PR War Room Config
// Dispute period: May–July 2025. Resolved July 1, 2025.

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2025-06-19",
    source: "CBS New York",
    url: "https://www.cbsnews.com/newyork/news/united-healthcare-memorial-sloan-kettering-contract-negotiations/",
    sourceType: "tv",
    channel: "media",
    headline: "UHC, Memorial Sloan Kettering set to take contract squabbles to mediation — Sheila Kolt: 'MSK saved my life'",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "Jenna DeAngelis report. Sheila Kolt (45): preventive bilateral mastectomy, precancerous cells discovered. 'Not having that access to MSK is very scary. It's very scary.' 'MSK saved my life.' First major local TV coverage — sets patient-sympathetic tone.",
  },
  {
    id: 2,
    date: "2025-06-26",
    source: "CBS New York",
    url: "https://www.cbsnews.com/newyork/video/contract-dispute-between-memorial-sloan-kettering-unitedhealthcare-continues/",
    sourceType: "tv",
    channel: "media",
    headline: "Contract dispute between Memorial Sloan Kettering, UnitedHealthcare continues — clock ticking",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Follow-up CBS segment. Both sides quoted. Urgency framing as June 30 deadline approaches. Multiple CBS segments throughout final week.",
  },
  {
    id: 3,
    date: "2025-06-30",
    source: "CBS New York",
    url: "https://www.cbsnews.com/newyork/video/clock-is-ticking-on-united-healthcare-memorial-sloan-kettering-to-reach-contract-agreement/",
    sourceType: "tv",
    channel: "media",
    headline: "Clock is ticking on United Healthcare, Memorial Sloan Kettering to reach contract agreement",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "Deadline-day coverage. Patient anxiety stories. CBS continues to be most impactful local outlet for this dispute. Cancer patients mid-treatment is maximally sympathetic framing.",
  },
  {
    id: 4,
    date: "2025-06-30",
    source: "NBC Nightly News",
    url: "https://www.nbcnews.com/nightly-news/video/patients-in-limbo-over-cancer-center-s-contract-feud-242398277833",
    sourceType: "tv",
    channel: "media",
    headline: "Patients in limbo over cancer center's contract feud — national broadcast coverage",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "NATIONAL BROADCAST. NBC Nightly News is highest-reach single segment. Cancer patients in limbo is devastating framing for UHC. Aired on deadline day for maximum impact.",
  },
  {
    id: 5,
    date: "2025-07-01",
    source: "CNN",
    url: "https://www.cnn.com/2025/07/01/health/united-healthcare-memorial-sloan-kettering-contract-cancer",
    sourceType: "news",
    channel: "media",
    headline: "Insurer and cancer center reach agreement in contract dispute that left thousands of patients in limbo — Marla Puccetti featured",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "CNN wire — syndicated to 10+ local affiliates nationally. Marla Puccetti (53): restaurant co-owner, active cancer treatment, no out-of-network coverage. Spent all day on phone. Going anywhere but MSK 'unthinkable.' Patient-sympathetic framing even in resolution coverage.",
  },
  {
    id: 6,
    date: "2025-07-01",
    source: "Bloomberg",
    url: "https://www.bloomberg.com/news/articles/2025-07-01/unitedhealth-deadlocks-in-ny-contract-fight-with-sloan-kettering",
    sourceType: "news",
    channel: "media",
    headline: "UnitedHealth, Sloan Kettering Resolve Contract Dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Financial press. Balanced reporting. Notes deal reached 'just after midnight.' Neither side disclosed contract length or rate specifics. Bloomberg Law also covered. Investor audience.",
  },
  {
    id: 7,
    date: "2025-07-01",
    source: "Fierce Healthcare",
    url: "https://www.fiercehealthcare.com/payers/memorial-sloan-kettering-set-go-out-unitedhealthcares-network-july-1",
    sourceType: "news",
    channel: "media",
    headline: "Memorial Sloan Kettering, UnitedHealthcare reach contract agreement",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press. Factual reporting of resolution. Notes MSK's claim of 1.6% annual increases over prior 5 years vs UHC's claim of 30% demanded hike. Both sides' numbers presented.",
  },
  {
    id: 8,
    date: "2025-07-01",
    source: "Becker's Hospital Review",
    url: "https://www.beckershospitalreview.com/oncology/memorial-sloan-kettering-cancer-center-unitedhealthcarereach-11th-hour-deal/",
    sourceType: "news",
    channel: "media",
    headline: "Memorial Sloan Kettering Cancer Center, UnitedHealthcare reach 11th-hour deal",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press. '11th-hour deal' framing suggests brinksmanship from both sides. Notes neither side disclosed contract length or rate details. Hospital executive audience.",
  },
  {
    id: 9,
    date: "2025-07-01",
    source: "KFF Health News",
    url: "https://kffhealthnews.org/morning-breakout/unitedhealthcare-reaches-agreement-with-cancer-center-over-coverage/",
    sourceType: "news",
    channel: "media",
    headline: "UnitedHealthcare Reaches Agreement With Cancer Center Over Coverage",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "KFF is the gold standard for health policy coverage. Balanced framing. National reach among policy professionals.",
  },
  {
    id: 10,
    date: "2025-08-26",
    source: "KFF Health News",
    url: "https://kffhealthnews.org/news/article/hospitals-insurers-contract-dispute-patients-coverage-in-limbo/",
    sourceType: "news",
    channel: "media",
    headline: "When Hospitals and Insurers Fight, Patients Get Caught in the Middle — MSK/UHC as case study",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Major investigative piece. 18% of non-federal hospitals had public brinksmanship case (June 2021–May 2025). ~500-600 disputes per year. MSK/UHC featured alongside other disputes. Systemic framing normalizes MSK's position. Syndicated to Cancer Therapy Advisor.",
  },
  {
    id: 11,
    date: "2025-06-26",
    source: "Snopes",
    url: "https://www.snopes.com/news/2025/06/26/cancer-unitedhealthcare-memorial-sloan-kettering/",
    sourceType: "news",
    channel: "media",
    headline: "Unraveling rumors UnitedHealthcare no longer covers cancer care at Memorial Sloan Kettering",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Fact-check triggered by viral social media posts. Confirms dispute is real but clarifies timeline — UHC had not yet 'dropped' MSK at time of posting. The fact that Snopes had to fact-check indicates significant social virality.",
  },
  {
    id: 12,
    date: "2025-06-19",
    source: "Mediate.com",
    url: "https://mediate.com/news/united-healthcare-memorial-sloan-kettering-set-to-take-contract-squabbles-to-mediation/",
    sourceType: "news",
    channel: "media",
    headline: "United Healthcare, Memorial Sloan Kettering set to take contract squabbles to mediation",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Mediation-focused outlet. Notes formal mediation scheduled. Factual reporting.",
  },
  {
    id: 13,
    date: "2025-06-30",
    source: "DistilInfo HospitalIT",
    url: "https://distilinfo.com/hospitalit/2025/06/30/msk-unitedhealthcare-network/",
    sourceType: "news",
    channel: "media",
    headline: "MSK UnitedHealthcare Network Dispute Threatens Patients",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "low",
    notes: "Health IT trade press. 'Threatens patients' headline places blame on dispute dynamics that UHC initiated by refusing sustainable rates.",
  },
  {
    id: 14,
    date: "2025-07-01",
    source: "Seeking Alpha",
    url: "https://seekingalpha.com/news/4464143-unitedhealth-contract-dispute-sloan-kettering",
    sourceType: "news",
    channel: "media",
    headline: "UnitedHealth ends contract dispute with Sloan Kettering (UNH)",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Investor audience. Financial framing. UHC stock impact angle. Balanced.",
  },
  {
    id: 15,
    date: "2025-07-01",
    source: "Crain's New York Business",
    url: "https://www.crainsnewyork.com/health-pulse/memorial-sloan-kettering-reaches-new-contract-unitedhealthcare",
    sourceType: "news",
    channel: "media",
    headline: "Memorial Sloan Kettering reaches new contract with UnitedHealthcare — neither side discloses terms",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "NYC business press. Notes neither side would answer questions about contract length or average rate increase. Crain's audience is NYC employer decision-makers. Key for employer perception of UHC network reliability.",
  },
  {
    id: 16,
    date: "2025-07-01",
    source: "PIX11",
    url: "https://pix11.com/news/local-news/unitedhealthcare-reaches-agreement-with-memorial-sloan-kettering/",
    sourceType: "tv",
    channel: "media",
    headline: "UnitedHealthcare reaches agreement with Memorial Sloan Kettering",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Local TV. Resolution coverage. Balanced.",
  },
  {
    id: 17,
    date: "2025-06-30",
    source: "News 12 Long Island",
    url: "https://longisland.news12.com/cancer-treatment-at-memorial-sloan-kettering-cancer-center-could-no-longer-be-in-network-for-those-with-unitedhealthcare-insurance",
    sourceType: "tv",
    channel: "media",
    headline: "Cancer treatment at MSK could no longer be in-network for those with UnitedHealthcare insurance",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "Suburban Long Island coverage. MSK has significant Long Island patient base. 'Could no longer be in-network' creates immediate anxiety.",
  },
  {
    id: 18,
    date: "2025-06-30",
    source: "News 12 Westchester",
    url: "https://westchester.news12.com/tens-of-thousands-of-united-healthcare-cancer-patients-could-lose-treatment-access-by-midnight-across-hudson-valley",
    sourceType: "tv",
    channel: "media",
    headline: "Tens of thousands of UHC cancer patients could lose treatment access by midnight across Hudson Valley",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "'Tens of thousands' and 'by midnight' creates maximum urgency. Hudson Valley/Westchester is affluent demographic — these patients have political influence.",
  },
  {
    id: 19,
    date: "2025-07-01",
    source: "News 12 Long Island",
    url: "https://longisland.news12.com/memorial-sloan-kettering-unitedhealthcare-reach-multiyear-agreement-to-ensure-continued-in-network-service-for-nyc-cancer-patients",
    sourceType: "tv",
    channel: "media",
    headline: "Memorial Sloan-Kettering, UnitedHealthcare strike deal; no disruption for patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution coverage across News 12 affiliates (LI, Brooklyn, Westchester). Relief framing.",
  },
  {
    id: 20,
    date: "2025-07-01",
    source: "Westfair Communications",
    url: "https://westfaironline.com/combined/sloan-kettering-and-unitedhealthcare-reach-contract-agreement/",
    sourceType: "news",
    channel: "media",
    headline: "Sloan Kettering and UnitedHealthcare reach contract agreement",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Westchester/Fairfield County business press. Local employer audience.",
  },
  {
    id: 21,
    date: "2025-07-01",
    source: "NBC News",
    url: "https://www.nbcnews.com/health/health-news/hospitals-insurers-dispute-contract-patients-lurch-rcna258248",
    sourceType: "news",
    channel: "media",
    headline: "Hospitals and insurers are fighting over money, leaving patients in the lurch — MSK featured",
    frameAdoption: "balanced",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "National trend piece. MSK/UHC alongside other disputes. Systemic framing. Patient stories all favor provider side. Leemore Dafny (Harvard Kennedy): 'Hospital prices have grown tremendously.' Jason Buxbaum (Brown): ~500-600 disputes annually.",
  },
  // === MSK OWNED MEDIA ===
  {
    id: 22,
    date: "2025-06-25",
    source: "mskcc.org — UHC Claims vs Facts",
    url: "https://www.mskcc.org/sites/default/files/node/325446/documents/msk-uhc-claims-vs.facts.pdf",
    sourceType: "owned",
    channel: "media",
    headline: "MSK publishes 'UHC Claims vs. Facts' rebuttal PDF — detailed counter-narrative",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Professional PDF rebuttal document. Key claims: UHC kept rates at 1.6%/year over 5 years (less than 1/3 of cost increases). MSK total cost per cancer episode 4-16% LOWER than other NCI centers. 25% fewer inpatient days, 76% fewer outpatient encounters. Sophisticated data-driven counter to UHC's '30% hike' framing.",
  },
  {
    id: 23,
    date: "2025-06-25",
    source: "mskcc.org — Insurance Update Page",
    url: "https://www.mskcc.org/insurance-assistance/insurance-information/msk-unitedhealthcare-contract-negotiations",
    sourceType: "owned",
    channel: "media",
    headline: "MSK creates dedicated insurance negotiation page for patients",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Patient-facing page with updates on negotiation status. Part of organized communication strategy. Directs patients to resources.",
  },
  {
    id: 24,
    date: "2025-07-01",
    source: "mskcc.org — Press Release",
    url: "https://www.mskcc.org/news-releases/mskcc-and-united-healthcare-uhc-announce-new-multi-year-agreement",
    sourceType: "owned",
    channel: "media",
    headline: "MSK and UHC announce new multi-year agreement — CEO Vickers statement",
    frameAdoption: "msk",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Selwyn M. Vickers, MD (President & CEO): 'We have reached an agreement that protects access to MSK for thousands of patients and ensures we can continue delivering the highest standard of cancer care.' Victory framing — 'protects access' implies UHC was threatening it.",
  },
  // === UHC OWNED MEDIA ===
  {
    id: 25,
    date: "2025-06-26",
    source: "UnitedHealthcare (public statement)",
    sourceType: "owned",
    channel: "media",
    headline: "UHC: MSK demanding 30% average price hike, 36% for cancer center — would cost $469M",
    frameAdoption: "uhc",
    sentiment: "negative_msk",
    patientStory: false,
    blameDirection: "msk",
    reachEstimate: "medium",
    notes: "UHC's primary public statement. Key claims: 30% average hike, 36% for cancer center, $469M cost increase. 'We already reimburse MSK at levels significantly higher than other NCI-designated health systems.' Defensive corporate tone. No patient voices.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 26,
    date: "2025-06-25",
    source: "MSK official (X/Twitter)",
    sourceType: "social",
    channel: "social",
    headline: "MSK reassures patients on X: 'doing everything we can to come to a reasonable agreement with UHC'",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Official MSK social. 'Reasonable agreement' implies UHC is being unreasonable. Responds to patient @citeyourwork concern. Professional tone.",
  },
  {
    id: 27,
    date: "2025-07-01",
    source: "MSK official (X/Twitter)",
    sourceType: "social",
    channel: "social",
    headline: "MSK announces resolution on X: 'uninterrupted in-network access'",
    frameAdoption: "msk",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution announcement. 'Uninterrupted' framing claims credit for preventing disruption UHC would have caused.",
  },
  {
    id: 28,
    date: "2025-06-25",
    source: "MSK official (Facebook)",
    sourceType: "social",
    channel: "social",
    headline: "MSK Facebook: 'Please be assured we are doing everything we can to reach a fair agreement'",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Facebook skews older — key Anthem/UHC enrollment demographic. Comment sections likely highly emotional given cancer patient base.",
  },
  {
    id: 29,
    date: "2025-07-01",
    source: "MSK official (Facebook)",
    sourceType: "social",
    channel: "social",
    headline: "MSK Facebook resolution post: 'MSK has reached a contract agreement with UnitedHealthcare'",
    frameAdoption: "msk",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution post. High engagement expected given anxiety level in comment sections during dispute.",
  },
  {
    id: 30,
    date: "2025-06-25",
    source: "X/Twitter (viral patient post)",
    sourceType: "social",
    channel: "social",
    headline: "Viral post claims UHC 'disrupting cancer treatment' for 20,000 people — triggers Snopes fact-check",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "CRITICAL SOCIAL SIGNAL. Post went viral enough to trigger Snopes investigation. Patient claiming to be MSK patient with UHC insurance. Post-Thompson assassination anti-UHC sentiment amplifies virality. Cancer treatment disruption is maximally sympathetic angle.",
  },
  {
    id: 31,
    date: "2025-06-26",
    source: "Social media (anti-UHC meta-narrative)",
    sourceType: "social",
    channel: "social",
    headline: "MSK dispute fuels broader post-Thompson anti-UHC social media rage",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "STRUCTURAL CONTEXT: This dispute occurred ~6 months after Brian Thompson (UHC CEO) assassination (Dec 2024). UHC had hired defamation law firm (Fortune, Feb 2025) to combat social posts. Reddit r/medicine previously deleted 500+ reply thread. Every UHC dispute now lands in intensely hostile social environment. MSK has enormous structural advantage.",
  },
  {
    id: 32,
    date: "2025-06-30",
    source: "CNN wire syndication (10+ affiliates)",
    sourceType: "news",
    channel: "social",
    headline: "CNN wire story 'Thousands of cancer patients fear disruptions' syndicated to ABC17, KRDO, WAOW, KESQ, KVIA, others",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "CNN wire reach: 10+ local affiliate websites carried the story with Puccetti patient story. National footprint beyond NYC. Cancer disruption angle resonates universally.",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 33,
    date: "2025-06-25",
    source: "Dr. Cardinale Smith, CMO, MSK",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "MSK CMO: 'UHC is putting the care of 19,000 patients with cancer at risk by refusing a sustainable agreement'",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "Inaugural CMO, thoracic medical oncologist. Key data: UHC rate increases just 1.6%/year over 5 years, less than 1/3 of MSK's actual cost increases. MSK total cost per cancer episode 4-16% lower than other NCI centers. 25% fewer inpatient days. Powerful credibility — clinician-executive.",
  },
  {
    id: 34,
    date: "2025-06-30",
    source: "NY State 60-day cooling-off regulation",
    sourceType: "news",
    channel: "stakeholder",
    headline: "NY State regulation provides 60-day extension for fully insured plans — but NOT for ASO/self-funded or physician services",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "CRITICAL REGULATORY GAP: 60-day rule covers fully insured hospital services through Aug 30. But does NOT cover physician services or ASO/self-funded employer plans — which is the MAJORITY of large employer plans. These patients would lose access immediately July 1. This gap amplifies employer anxiety.",
  },
  {
    id: 35,
    date: "2025-06-30",
    source: "Mt Sinai vs UHC precedent (2023-2024)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Mt Sinai/UHC dispute (2023-24): UHC moved 6 hospitals out of network — eventually resolved",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "PATTERN: UHC has a history of aggressive network disputes in NYC. Mt Sinai sought 43% hike/$574M; UHC said Mt Sinai paid 30-50% less than competitors. Pattern normalizes MSK's position and positions UHC as serial disruptor.",
  },
  {
    id: 36,
    date: "2025-06-30",
    source: "Hartford HealthCare vs UHC parallel",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Hartford HealthCare/UHC dispute active simultaneously in CT — CT Office of Health Advocacy created FAQ",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Simultaneous UHC dispute in another state. CT regulator created public FAQ — more intervention than NY. Pattern evidence: UHC fighting multiple major systems at once.",
  },
  {
    id: 37,
    date: "2025-06-30",
    source: "M Health Fairview vs UHC parallel",
    sourceType: "news",
    channel: "stakeholder",
    headline: "M Health Fairview/UHC dispute could leave 100K-125K patients in limbo in Minnesota",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "ANOTHER simultaneous UHC dispute. 100K-125K patients. UHC is fighting on multiple fronts — MSK, Hartford, M Health Fairview, HCA. Pattern suggests corporate strategy, not MSK-specific unreasonableness.",
  },
  {
    id: 38,
    date: "2025-06-30",
    source: "KFF Health News (systemic analysis)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "KFF: 18% of non-federal hospitals had public brinksmanship case (2021-2025); ~500-600 disputes per year",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Academic/policy data. 18% figure normalizes MSK's position — this is a systemic trend, not MSK being uniquely aggressive. Cited by multiple outlets. Brown University research (Jason Buxbaum).",
  },
  {
    id: 39,
    date: "2025-07-01",
    source: "Junior Harewood, UHC CEO for New York",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "UHC NY CEO: 'We understand how difficult and deeply personal this negotiation has been'",
    frameAdoption: "uhc",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution statement. Conciliatory tone. 'Deeply personal' acknowledgment is unusual for UHC — suggests they felt the PR pressure. 'Pleased to renew our relationship' frames it as UHC's choice.",
  },
  {
    id: 40,
    date: "2025-06-30",
    source: "Gov. Hochul / NY officials (silence)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Governor Hochul and NY AG have NOT intervened in MSK/UHC dispute — regulatory silence",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "SILENCE IS DATA. No public pressure from Governor despite MSK's significance. Hochul separately announced $188M partnership with MSK for Queens cancer center — political relationship intact. Silence suggests both parties expected resolution without state intervention.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 41,
    date: "2025-05-29",
    source: "UHC (employer/broker update letter)",
    url: "https://www.fnainsurance.com/-/media/Project/FNA/FNA/PDFs/Carrier-News--Updates/2025/May-2025/UHC_MSK-employer-broker-update_529.pdf",
    sourceType: "owned",
    channel: "employer",
    headline: "UHC sends employer/broker notification: MSK may leave network July 1 — ASO plans at particular risk",
    frameAdoption: "uhc",
    sentiment: "negative_msk",
    patientStory: false,
    blameDirection: "msk",
    reachEstimate: "high",
    notes: "CRITICAL EMPLOYER CHANNEL. UHC frames MSK as choosing to leave. Warns ASO/self-funded plans would lose access immediately with NO cooling-off protection. This is where employer anxiety begins. PDF hosted at fnainsurance.com — broker distribution channel.",
  },
  {
    id: 42,
    date: "2025-06-20",
    source: "AmWINS Connect",
    url: "https://www.amwinsconnect.com/news/unitedhealthcare-negotiations-memorial-sloan-kettering",
    sourceType: "news",
    channel: "employer",
    headline: "AmWINS Connect: UnitedHealthcare Negotiations with Memorial Sloan Kettering — broker advisory",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Benefits broker advisory. AmWINS is major wholesale broker. Client-facing communication signals severity of disruption for employer plans.",
  },
  {
    id: 43,
    date: "2025-07-01",
    source: "Professional Group Plans (PGP Benefits)",
    sourceType: "news",
    channel: "employer",
    headline: "PGP Benefits: UnitedHealthcare, Memorial Sloan Kettering agree to new multi-year contract",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Benefits firm client communication. Resolution announcement for employer clients.",
  },
  {
    id: 44,
    date: "2025-07-01",
    source: "Sweny's Insurance",
    sourceType: "news",
    channel: "employer",
    headline: "UnitedHealthcare Keeps Stony Brook Medicine & Memorial Sloan Kettering In-Network",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Insurance broker update. Notes both MSK and Stony Brook disputes resolved. Employer relief framing.",
  },
  {
    id: 45,
    date: "2025-06-26",
    source: "UHC employer messaging",
    sourceType: "owned",
    channel: "employer",
    headline: "UHC frames to employers: 35% price hike would increase costs by $469M, directly impacting self-insured employers",
    frameAdoption: "uhc",
    sentiment: "negative_msk",
    patientStory: false,
    blameDirection: "msk",
    reachEstimate: "high",
    notes: "UHC's STRONGEST employer-facing argument. $469M figure is attention-getting. Self-insured employer plans are UHC's primary customer base. If employers accept this framing, it pressures MSK. But cancer treatment disruption for employees is a counter-pressure.",
  },
  // === ADDITIONAL SOCIAL ===
  {
    id: 46,
    date: "2025-06-30",
    source: "News 12 Westchester",
    url: "https://westchester.news12.com/unitedhealthcare-drops-msk-patients-in-hudson-valley-face-out-of-network-cancer-care-costs",
    sourceType: "tv",
    channel: "media",
    headline: "UnitedHealthcare drops MSK, patients in Hudson Valley face out-of-network cancer care costs",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "'UHC drops MSK' framing places blame squarely on insurer. 'Out-of-network cancer care costs' creates financial anxiety on top of health anxiety. Hudson Valley patients are affluent, politically active.",
  },
  {
    id: 47,
    date: "2025-06-30",
    source: "News 12 Brooklyn",
    url: "https://brooklyn.news12.com/memorial-sloan-kettering-unitedhealthcare-reach-multiyear-agreement-to-ensure-continued-in-network-service-for-nyc-cancer-patients",
    sourceType: "tv",
    channel: "media",
    headline: "MSK-UHC deadline coverage reaches Brooklyn audience via News 12 affiliate",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Same content as LI/Westchester but reaching Brooklyn audience. MSK has outpatient facilities across boroughs. Multi-affiliate coverage amplifies geographic reach.",
  },
  {
    id: 48,
    date: "2025-06-30",
    source: "Social media (cancer patient community)",
    sourceType: "social",
    channel: "social",
    headline: "Cancer patient communities share MSK/UHC dispute — 'my treatment could be interrupted'",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: true,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Cancer patient support communities and forums. MSK patients include some of the most medically complex cases in the country. The prospect of losing access mid-chemotherapy is terrifying. Organic sharing highly sympathetic to MSK.",
  },
  {
    id: 49,
    date: "2025-06-28",
    source: "Reddit/social (anti-UHC sentiment)",
    sourceType: "social",
    channel: "social",
    headline: "MSK dispute feeds into post-Thompson anti-UHC Reddit/social conversation",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "medium",
    notes: "Reddit r/medicine previously deleted 500+ reply thread about Thompson killing where doctors criticized UHC. MSK dispute provides new ammunition. UHC's social media reputation is at historic low.",
  },
  {
    id: 50,
    date: "2025-06-26",
    source: "MSK CMO Dr. Cardinale Smith (press materials)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "MSK CMO data: MSK's total cost of care per cancer episode is 4-16% LOWER than other NCI centers",
    frameAdoption: "msk",
    sentiment: "negative_uhc",
    patientStory: false,
    blameDirection: "uhc",
    reachEstimate: "high",
    notes: "KEY DATA POINT. If MSK costs 4-16% less per episode than peers, UHC's 'price hike' framing is undermined. MSK argues: we deliver better outcomes at lower total cost, but UHC underpays on a per-service basis. This is MSK's stickiest factual argument.",
  },
];

const LABELS = {
  frameAdoption: { msk: "MSK Frame", uhc: "UHC Frame", balanced: "Balanced" },
  sentiment: {
    negative_uhc: "Anti-UHC",
    negative_msk: "Anti-MSK",
    neutral: "Neutral",
    positive_uhc: "Pro-UHC",
    positive_msk: "Pro-MSK",
  },
  blameDirection: { uhc: "Blames UHC", msk: "Blames MSK", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National record (1.5)
  "NBC Nightly News": 1.5, "NBC News": 1.5, "CNN": 1.5, "KFF Health News": 1.5, "Bloomberg": 1.5,
  // Tier 2 — Regional authority (1.2)
  "CBS New York": 1.2, "PIX11": 1.2, "News 12 Long Island": 1.2, "News 12 Westchester": 1.2,
  "News 12 Brooklyn": 1.2, "Crain's New York Business": 1.2,
  // Tier 3 — Trade/niche (1.0)
  "Fierce Healthcare": 1.0, "Becker's Hospital Review": 1.0, "Seeking Alpha": 1.0,
  "Mediate.com": 1.0, "DistilInfo HospitalIT": 1.0, "Snopes": 1.0,
  "Westfair Communications": 1.0, "Bloomberg Law": 1.0,
  // Tier 4 — Organic social (0.7)
  "X/Twitter (viral patient post)": 0.7, "Social media (anti-UHC meta-narrative)": 0.7,
  "Social media (cancer patient community)": 0.7, "Reddit/social (anti-UHC sentiment)": 0.7,
  "CNN wire syndication (10+ affiliates)": 0.7,
  // Tier 5 — Comment sections (0.4)
  // Tier 6 — Owned/party media (0.3)
  "mskcc.org — UHC Claims vs Facts": 0.3, "mskcc.org — Insurance Update Page": 0.3,
  "mskcc.org — Press Release": 0.3, "MSK official (X/Twitter)": 0.3,
  "MSK official (Facebook)": 0.3,
  "UnitedHealthcare (public statement)": 0.3, "UHC (employer/broker update letter)": 0.3,
  "UHC employer messaging": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "Dr. Cardinale Smith, CMO, MSK": 1.3, "MSK CMO Dr. Cardinale Smith (press materials)": 1.3,
  "NY State 60-day cooling-off regulation": 1.3,
  "Mt Sinai vs UHC precedent (2023-2024)": 1.3, "Hartford HealthCare vs UHC parallel": 1.3,
  "M Health Fairview vs UHC parallel": 1.3, "KFF Health News (systemic analysis)": 1.3,
  "Junior Harewood, UHC CEO for New York": 1.3, "Gov. Hochul / NY officials (silence)": 1.3,
  // Tier 8 — Employer/Benefits (1.5x trade, 1.8x consultant)
  "AmWINS Connect": 1.5, "Professional Group Plans (PGP Benefits)": 1.0,
  "Sweny's Insurance": 1.0,
};

const SEARCH_TRENDS = [
  { week: "2025-05-05", interest: 2 }, { week: "2025-05-12", interest: 3 }, { week: "2025-05-19", interest: 4 },
  { week: "2025-05-26", interest: 8 }, { week: "2025-06-02", interest: 12 }, { week: "2025-06-09", interest: 18 },
  { week: "2025-06-16", interest: 45 }, { week: "2025-06-23", interest: 85 }, { week: "2025-06-30", interest: 100 },
  { week: "2025-07-07", interest: 35 }, { week: "2025-07-14", interest: 15 }, { week: "2025-07-21", interest: 8 },
];

export default {
  active: false,
  // Identity
  providerKey: "msk",
  payorKey: "uhc",
  providerName: "Memorial Sloan Kettering",
  payorName: "UnitedHealthcare",
  providerShort: "MSK",
  payorShort: "UHC",
  navShort: "MSK v. UHC",
  title: "MSK vs UnitedHealthcare",
  subtitle: "Contract dispute · Resolved July 1, 2025",
  gradientId: "mskuhc",

  // Dates
  monitorStart: "May 1, 2025",
  monitorEnd: "July 31, 2025",
  disputePublicDate: "2025-06-19",

  // Colors
  colors: {
    providerColor: "#1B4D8E",
    payorColor: "#8B2332",
    neutral: "#64748B",
    accent: "#1B4D8E",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#1B4D8E", "#465E85", "#8B2332"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"memorial sloan kettering unitedhealthcare" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 2.14,
    nationalMedian: 1.0,
    networkComplaints: 1847,
    priorYearComplaints: 1205,
    regulatorAction: "NY 60-day cooling-off regulation provided transitional coverage for fully insured plans. No formal DFS investigation opened. Governor Hochul did not publicly intervene.",
    signalRead: "UHC's national complaint index is elevated (2.14x median) driven by multi-state provider disputes simultaneously. The 53% increase in network complaints reflects broader UHC-provider tensions, not just MSK. Post-Thompson sentiment creates amplified regulatory risk for UHC.",
  },

  // Executive summary
  executiveSummary: {
    statement: " The dispute resolved via 11th-hour deal just after midnight July 1 — no actual disruption occurred, but the PR damage to UHC was significant.",
    keyMessages: [
      "MSK's '4-16% lower total cost per cancer episode' is the stickiest factual counter to UHC's price hike narrative.",
      "Every named patient story involves active cancer treatment — maximally sympathetic, impossible for UHC to counter with equivalent patient advocates.",
      "Post-Thompson assassination context means every UHC dispute now lands in intensely hostile social media environment.",
      "UHC fighting multiple major systems simultaneously (MSK, Hartford, M Health Fairview, HCA) undermines 'MSK is uniquely unreasonable' framing.",
    ],
    marcomm: [
      "<strong>Cancer is the ultimate trump card.</strong> No framing about 'affordability' or 'price hikes' can overcome the image of cancer patients losing access to the nation's top cancer center. MSK holds a structural narrative advantage that is nearly impossible to overcome.",
      "<strong>The ASO gap is UHC's real vulnerability.</strong> Self-funded employer plans (majority of large employers) would have lost access immediately with no cooling-off protection. This creates direct employer pressure on UHC.",
      "<strong>Post-Thompson social environment is permanently hostile to UHC.</strong> Any dispute involving UHC will be framed through the 'greedy insurer' lens for the foreseeable future. UHC has no path to social media sympathy.",
      "<strong>Resolution framing still favors MSK.</strong> Even the deal announcement positions MSK as 'protecting access' — implying UHC was threatening it. UHC's conciliatory tone ('deeply personal') signals they felt the pressure.",
    ],
  },
  channelTakeaways: {
    media: [
      "NBC Nightly News coverage on deadline day was the single highest-reach segment — national broadcast + cancer angle is devastating for UHC.",
      "CNN wire syndication to 10+ affiliates extended reach far beyond NYC metro area.",
      "Trade press (KFF, Becker's, Fierce) framed this as systemic trend, not MSK-specific — normalizes MSK's position.",
      "MSK's 'Claims vs Facts' PDF provided data-driven counter-narrative that media could cite.",
    ],
    social: [
      "Viral patient post triggered Snopes fact-check — indicates significant organic social engagement.",
      "Post-Thompson assassination (Dec 2024) sentiment creates structural anti-UHC environment on all social platforms.",
      "UHC hired defamation law firm (Feb 2025) to combat social posts — signals they recognize social media is a losing front.",
      "Cancer patient communities generated intense organic anxiety that amplified MSK's position.",
    ],
    stakeholder: [
      "MSK CMO Dr. Cardinale Smith provided the most impactful data: 4-16% lower total cost per episode than NCI peers.",
      "NY State 60-day cooling-off rule's gap (no coverage for ASO/self-funded plans) was the key pressure point for UHC.",
      "Simultaneous UHC disputes with Hartford, M Health Fairview, and HCA created pattern evidence of UHC's aggressive posture.",
      "Governor Hochul's silence was notable — MSK has strong political relationships but intervention wasn't needed.",
    ],
    employer: [
      "UHC's employer notification (May 29) warned ASO plans would lose access immediately — created significant employer anxiety.",
      "Benefits brokers (AmWINS, PGP, Sweny's) all issued client advisories — signals severity of disruption for employer plans.",
      "UHC's $469M cost framing is their strongest employer argument, but cancer treatment disruption for employees creates counter-pressure that employers can't ignore.",
    ],
  },
  arguments: {
    payor: [
      { phase: "Early (Jun 2025)", points: [
        "Claimed MSK was demanding a <strong>30% average price hike</strong> (36% for the cancer center specifically)",
        "Framed the rate increase as costing <strong>$469 million</strong>, directly impacting self-insured employers and families",
        "Stated UHC 'already reimburses MSK at levels significantly higher than other NCI-designated health systems'",
      ] },
      { phase: "Mid-Dispute (Jun 2025)", points: [
        "Sent employer/broker notifications framing MSK as choosing to leave the network",
        "Warned ASO/self-funded employer plans would lose access immediately with <strong>no cooling-off protection</strong>",
        "Emphasized $469M cost figure to position MSK's demands as a threat to employer bottom lines",
      ] },
      { phase: "Resolution (Jul 2025)", points: [
        "UHC NY CEO Junior Harewood: 'We understand how <strong>deeply personal</strong> this negotiation has been' — unusually conciliatory tone suggesting PR pressure was felt",
        "Framed resolution as UHC's choice: 'pleased to renew our relationship'",
      ] },
    ],
    provider: [
      { phase: "Early (Jun 2025)", points: [
        "CMO Dr. Cardinale Smith: UHC kept rates at just <strong>1.6% annual increases</strong> over 5 years — less than one-third of actual cost increases",
        "Published 'UHC Claims vs. Facts' rebuttal PDF with detailed data countering UHC's '30% hike' narrative",
        "Argued MSK's <strong>total cost per cancer episode is 4–16% lower</strong> than other NCI-designated centers, with 25% fewer inpatient days and 76% fewer outpatient encounters",
      ] },
      { phase: "Mid-Dispute (Jun 2025)", points: [
        "Created dedicated insurance negotiation page for patients, directing them to resources",
        "Social media messaging framed UHC as 'unreasonable': 'doing everything we can to come to a <strong>reasonable agreement</strong> with UHC'",
        "Leveraged structural advantage: every named patient story involved <strong>active cancer treatment</strong> — maximally sympathetic framing impossible for UHC to counter",
      ] },
      { phase: "Resolution (Jul 2025)", points: [
        "CEO Selwyn Vickers: agreement 'protects access to MSK for thousands of patients' — victory framing implying <strong>UHC was threatening access</strong>",
        "'Uninterrupted in-network access' messaging claimed credit for preventing disruption",
      ] },
    ],
  },
  timeline: [
    { date: "2025-06-19", type: "newsBreak", label: "News breaks publicly" },
    { date: "2025-06-30", type: "termination", label: "Contract terminates" },
    { date: "2025-07-01", type: "agreement", label: "Agreement reached" },
  ],
};
