// Mount Sinai vs Anthem Blue Cross Blue Shield — PR War Room Config
// Dispute period: Oct 2025–ongoing. Hospital exited Anthem network March 4, 2026.

const ENTRIES = [
  // === MEDIA ENTRIES (19) ===
  {
    id: 1,
    date: "2026-03-04",
    source: "CBS New York",
    sourceType: "tv",
    channel: "media",
    headline: "DeQuevedo family: 12-year-old with Tourette's and pituitary tumor faces care disruption",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Lead story on March 4 breakdown. Mother describes fear of losing specialists mid-treatment. Most impactful patient story in local TV coverage. Repeated across multiple CBS segments.",
  },
  {
    id: 2,
    date: "2026-03-06",
    source: "CBS New York",
    sourceType: "tv",
    channel: "media",
    headline: "Massiel Lugo: lupus patient from Queens, single mom working 3 jobs, may lose Mt Sinai access",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Lugo's story extremely sympathetic — chronic illness, economic hardship, caregiving burden. Cross-posted to TikTok where it went viral. CBS framing clearly favors patient/provider side.",
  },
  {
    id: 3,
    date: "2026-03-08",
    source: "CBS New York",
    sourceType: "tv",
    channel: "media",
    headline: "John Esposito of Huntington calls himself a 'health care refugee' after losing Mt Sinai access",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Long Island patient. 'Health care refugee' language is powerful and quotable. Esposito actively seeking new coverage. CBS continues to be most impactful local outlet.",
  },
  {
    id: 4,
    date: "2026-03-10",
    source: "CBS New York",
    sourceType: "tv",
    channel: "media",
    headline: "Susan Kim, Upper West Side patient, fears losing oncologist at Mt Sinai",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Fourth CBS patient story. Kim is Upper West Side — affluent demographic that votes, donates, and complains loudly. Cancer care disruption angle is devastating for Anthem.",
  },
  {
    id: 5,
    date: "2026-03-05",
    source: "NBC News",
    sourceType: "tv",
    channel: "media",
    headline: "Natalie Reichel: cancer patient mid-therapy worried about losing Mt Sinai coverage",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "NATIONAL pickup. NBC News is the biggest reach of any single story. Cancer mid-therapy is the most sympathetic possible patient scenario. Anthem has zero equivalent patient advocates in public.",
  },
  {
    id: 6,
    date: "2026-03-07",
    source: "Gothamist / WNYC",
    sourceType: "radio",
    channel: "media",
    headline: "Elisabeth Benjamin of Community Service Society calls for systemic reform of insurer-provider negotiations",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Benjamin is a respected healthcare advocate. Frames dispute as systemic insurer problem, not Mt Sinai-specific. Calls for standardized contracting calendar. Gothamist audience is politically engaged NYC.",
  },
  {
    id: 7,
    date: "2026-03-05",
    source: "PIX11",
    sourceType: "tv",
    channel: "media",
    headline: "Mt Sinai and Anthem fail to reach deal — what patients need to know",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Most balanced local TV coverage. Both sides quoted at comparable length. Patient-focused FAQ format. Does not clearly favor either party's framing.",
  },
  {
    id: 8,
    date: "2026-03-09",
    source: "News 12 Long Island",
    sourceType: "tv",
    channel: "media",
    headline: "Fischman family in Valley Stream fears losing Mt Sinai specialists",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Suburban Long Island angle. Nicole & James Fischman — family with kids needing specialists. Suburban patient stories expand the geographic impact narrative beyond Manhattan.",
  },
  {
    id: 9,
    date: "2026-03-12",
    source: "Healthcare Dive",
    sourceType: "news",
    channel: "media",
    headline: "Mt Sinai-Anthem breakdown highlights growing trend of provider-insurer disputes",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press. Contextualizes within national trend of hospital-insurer breakdowns. Notes 18% of hospitals had public disputes 2021-2025. Balanced but the systemic framing implicitly normalizes Mt Sinai's position.",
  },
  {
    id: 10,
    date: "2026-03-11",
    source: "MedCity News",
    sourceType: "news",
    channel: "media",
    headline: "NYC's Mt Sinai goes fully out of network with Anthem BCBS",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press. Factual reporting on the breakdown. Quotes both sides' claims. Notes 200K patients affected. Provides financial context on Elevance's $5.7B profit.",
  },
  {
    id: 11,
    date: "2026-03-13",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "Mt Sinai says Anthem owes $450M in unpaid claims",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Trade press leads with Mt Sinai's $450M claim — the stickiest message in the dispute. Anthem's counter (95.4% paid within 15 days) buried lower. Hospital executive audience.",
  },
  {
    id: 12,
    date: "2026-03-14",
    source: "HR Brew",
    sourceType: "news",
    channel: "media",
    headline: "What NYC employers need to know about the Mt Sinai-Anthem split",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Employer/HR angle. Critical channel — employers choosing health plans are Anthem's real customers. If HR professionals start questioning Anthem network adequacy, that's a business risk for Anthem.",
  },
  {
    id: 13,
    date: "2026-03-15",
    source: "Crain's New York Business",
    sourceType: "news",
    channel: "media",
    headline: "32BJ SEIU bypasses Anthem with direct Mt Sinai contract for 100K+ workers",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "DEVASTATING for Anthem. A major union bypassing Anthem entirely validates Mt Sinai's pricing and positions Anthem as the unnecessary middleman. Crain's audience is NYC business decision-makers. Most significant stakeholder story.",
  },
  {
    id: 14,
    date: "2026-03-04",
    source: "keepmountsinai.org",
    sourceType: "owned",
    channel: "media",
    headline: "Mt Sinai launches dedicated campaign site with patient call-to-action",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Owned media but highly effective. Directs patients to: call Anthem, contact HR dept, file DFS complaints. Organized grassroots mobilization. Anthem has nothing equivalent.",
  },
  {
    id: 15,
    date: "2026-03-06",
    source: "choosemountsinai.org / The Vitals podcast",
    sourceType: "owned",
    channel: "media",
    headline: "34-minute podcast episode + choosemountsinai.org enrollment guide + Setting the Record Straight PDF",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Multi-channel owned media blitz: dedicated podcast, second campaign website, formal PDF rebuttal of Anthem's claims. Also partnered with Chapter.org for Medicare enrollment assistance. Sophisticated PR operation.",
  },
  {
    id: 16,
    date: "2026-03-04",
    source: "anthem.com/update/mountsinai",
    sourceType: "owned",
    channel: "media",
    headline: "Anthem FAQ page: 'What you need to know about Mt Sinai'",
    frameAdoption: "anthem",
    sentiment: "negative_mtsinai",
    patientStory: false,
    blameDirection: "mtsinai",
    reachEstimate: "medium",
    notes: "Anthem's primary response — a single FAQ page. Claims Mt Sinai wants 50%+ increase and to eliminate billing checks. Vastly outmatched by Mt Sinai's multi-platform PR operation.",
  },
  {
    id: 17,
    date: "2026-03-05",
    source: "anthem.com — Myths vs Facts",
    sourceType: "owned",
    channel: "media",
    headline: "Anthem publishes Myths vs Facts page countering Mt Sinai claims",
    frameAdoption: "anthem",
    sentiment: "negative_mtsinai",
    patientStory: false,
    blameDirection: "mtsinai",
    reachEstimate: "low",
    notes: "Claims Mt Sinai refused a ready contract, wants to block claim reviews, and demands rates far above peer systems. Defensive tone. No patient voices. 'Myths vs Facts' format feels corporate.",
  },
  {
    id: 18,
    date: "2026-03-13",
    source: "Becker's Payer Issues",
    sourceType: "news",
    channel: "media",
    headline: "Anthem BCBS responds to Mt Sinai's $450M unpaid claims allegation",
    frameAdoption: "anthem",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "mtsinai",
    reachEstimate: "medium",
    notes: "Rare Anthem-favorable trade coverage. Anthem says 95.4% of claims paid within 15 days, Mt Sinai has not provided documentation for $450M figure. Payer-focused trade audience more receptive to Anthem's framing.",
  },
  {
    id: 19,
    date: "2026-03-18",
    source: "NY Post",
    sourceType: "news",
    channel: "media",
    headline: "Mt Sinai patients scramble as Anthem network access vanishes",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Post readership skews populist — anti-corporate framing resonates. Includes patient quotes about scrambling for new providers. $5.7B Elevance profit mentioned prominently.",
  },
  // === SOCIAL ENTRIES (19) ===
  {
    id: 20,
    date: "2026-03-05",
    source: "TikTok (@massiellugo)",
    sourceType: "social",
    channel: "social",
    headline: "Massiel Lugo viral TikTok: lupus patient, Queens, single mom, 3 jobs — may lose Mt Sinai",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Most impactful social post. Lugo's personal story — lupus, single mom, 3 jobs, Queens — is maximally sympathetic. Viral engagement. Cross-covered by CBS. TikTok audience skews young and shares aggressively.",
  },
  {
    id: 21,
    date: "2026-03-04",
    source: "YouTube / CBS share",
    sourceType: "social",
    channel: "social",
    headline: "DeQuevedo family CBS story shared widely on YouTube and Facebook",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "CBS segment reshared across platforms. Comment sections overwhelmingly sympathetic to family. 12-year-old with Tourette's and pituitary tumor — audience naturally sides with child patient.",
  },
  {
    id: 22,
    date: "2026-03-06",
    source: "CBS News comment section",
    sourceType: "social",
    channel: "social",
    headline: "CBS comment sections overwhelmingly anti-Anthem",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Dominant themes: 'Anthem is greedy,' 'insurance companies don't care about patients,' references to Elevance profit. Almost no pro-Anthem comments visible. Post-UHC CEO shooting sentiment amplifies anti-insurer feeling.",
  },
  {
    id: 23,
    date: "2026-03-07",
    source: "Gothamist comment section",
    sourceType: "social",
    channel: "social",
    headline: "Gothamist readers discuss systemic insurer-provider power dynamics",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "More policy-literate commentary. Readers connect dispute to broader insurance industry critique. Elisabeth Benjamin interview drives sophisticated anti-insurer framing in comments.",
  },
  {
    id: 24,
    date: "2026-03-05",
    source: "PIX11 comment section",
    sourceType: "social",
    channel: "social",
    headline: "PIX11 comment section: mixed but majority blames Anthem",
    frameAdoption: "balanced",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "low",
    notes: "More balanced than CBS comments. Some 'both sides' takes. But majority sentiment still anti-Anthem. A few comments note Mt Sinai also dropped Molina — rare counter-narrative in social.",
  },
  {
    id: 25,
    date: "2026-03-06",
    source: "Yahoo News comment section",
    sourceType: "social",
    channel: "social",
    headline: "Yahoo News syndication comments: national audience weighs in",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Yahoo syndication extends reach to national audience. Comments strongly anti-insurer. 'This is why we need Medicare for All' — dispute becomes vehicle for broader healthcare reform advocacy.",
  },
  {
    id: 26,
    date: "2026-03-04",
    source: "Mt Sinai official (Facebook)",
    sourceType: "social",
    channel: "social",
    headline: "Mt Sinai launches coordinated social campaign across Facebook",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Coordinated campaign: patient testimonials, infographics on $450M owed, call-to-action to pressure Anthem. Professional production quality. Facebook audience skews older — key Anthem enrollment demographic.",
  },
  {
    id: 27,
    date: "2026-03-04",
    source: "Mt Sinai official (Instagram)",
    sourceType: "social",
    channel: "social",
    headline: "Mt Sinai Instagram campaign: visual storytelling on patient impact",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Instagram Stories and posts featuring patient quotes and provider testimonials. Visual format effective for emotional engagement. Part of coordinated cross-platform campaign.",
  },
  {
    id: 28,
    date: "2026-03-04",
    source: "Mt Sinai official (X/Twitter)",
    sourceType: "social",
    channel: "social",
    headline: "Mt Sinai X campaign: threading key data points and patient stories",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "X threads with key talking points: $450M owed, 35% underpayment, single-digit increases. Journalist and policy community engagement. Provides shareable data for media covering the story.",
  },
  {
    id: 29,
    date: "2026-03-04",
    source: "Mt Sinai official (LinkedIn)",
    sourceType: "social",
    channel: "social",
    headline: "Mt Sinai LinkedIn posts target employer and HR professional audience",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "LinkedIn audience = employers, HR professionals, healthcare executives. Strategic channel — employers choose health plans. Framing: 'your employees deserve Mt Sinai access, Anthem is blocking it.'",
  },
  {
    id: 30,
    date: "2026-03-10",
    source: "LinkedIn (Leslie Schlachter, PA-C)",
    sourceType: "social",
    channel: "social",
    headline: "Mt Sinai PA-C posts personal account of patient care disruption",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Clinician voice adds credibility. Schlachter describes patients crying in her office about losing access. Provider-as-witness framing. Other Mt Sinai clinicians reposting and adding their own stories.",
  },
  {
    id: 31,
    date: "2026-03-05",
    source: "keepmountsinai.org (social share)",
    sourceType: "social",
    channel: "social",
    headline: "Organized call-to-action: call Anthem, contact HR, file DFS complaints",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "CRITICAL asymmetry: Mt Sinai has organized patient pressure campaigns with specific action items. Anthem has no equivalent grassroots mobilization. Patients are calling Anthem AND filing regulatory complaints. This is the game-changer.",
  },
  {
    id: 32,
    date: "2026-03-12",
    source: "Medicare patient forum",
    sourceType: "social",
    channel: "social",
    headline: "Medicare patients confused about whether they're affected by Mt Sinai-Anthem dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Data gap signal: Medicare patients (not directly affected) are confused and worried. Demonstrates how the dispute creates ambient anxiety beyond the directly affected 200K. Mt Sinai's Chapter.org partnership addresses this.",
  },
  {
    id: 33,
    date: "2026-03-14",
    source: "HR professional community (LinkedIn/forums)",
    sourceType: "social",
    channel: "social",
    headline: "HR professionals discuss network adequacy concerns with Anthem plans",
    frameAdoption: "balanced",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Employer channel is where this dispute becomes an Anthem business risk. HR professionals discussing whether to offer Anthem plans if Mt Sinai isn't in-network. Cost framing ('50% increase') has some traction here.",
  },
  {
    id: 34,
    date: "2026-03-08",
    source: "Reddit r/nyc",
    sourceType: "social",
    channel: "social",
    headline: "Reddit r/nyc thread on Mt Sinai-Anthem dispute — limited but anti-Anthem",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "low",
    notes: "Limited visibility via web search. Estimated anti-Anthem based on Reddit's general anti-corporate lean and post-UHC shooting sentiment. DATA GAP: need direct Reddit monitoring for full picture.",
  },
  {
    id: 35,
    date: "2026-03-06",
    source: "Social media (patient switching intent)",
    sourceType: "social",
    channel: "social",
    headline: "Patients posting about switching away from Anthem to keep Mt Sinai access",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "CRITICAL SIGNAL: direction of switching intent is overwhelmingly 'leave Anthem to keep Mt Sinai,' not 'leave Mt Sinai to keep Anthem.' This is the strongest indicator of who patients value more.",
  },
  {
    id: 36,
    date: "2026-03-20",
    source: "Facebook groups (NYC healthcare)",
    sourceType: "social",
    channel: "social",
    headline: "Facebook group discussions: parents worried about pediatric specialist access",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "low",
    notes: "DATA GAP: web search has minimal reach into Facebook groups. Estimated from fragments. Pediatric angle is powerful — parents of sick children are the most vocal advocacy group.",
  },
  {
    id: 37,
    date: "2026-03-15",
    source: "Social media (anti-insurer meta-narrative)",
    sourceType: "social",
    channel: "social",
    headline: "Post-UHC CEO shooting: Mt Sinai dispute fuels broader anti-insurer sentiment",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "The UHC CEO shooting (Dec 2024) created a persistent anti-insurer undercurrent. Mt Sinai's dispute lands in this environment — every Anthem defense is read through a 'greedy insurer' lens. Structural advantage for Mt Sinai.",
  },
  {
    id: 38,
    date: "2026-03-10",
    source: "Mt Sinai employee social posts",
    sourceType: "social",
    channel: "social",
    headline: "Mt Sinai employees sharing personal stories of patient impact on social media",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Nurses, PAs, social workers posting about patient distress. Organic-feeling but clearly encouraged by Mt Sinai comms. Employee voices add authenticity that corporate messaging lacks.",
  },
  // === STAKEHOLDER ENTRIES (12) ===
  {
    id: 39,
    date: "2026-03-15",
    source: "32BJ SEIU",
    sourceType: "news",
    channel: "stakeholder",
    headline: "32BJ SEIU bypasses Anthem with direct Mt Sinai contract for 100K+ workers",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "MOST SIGNIFICANT STAKEHOLDER MOVE. A major union bypassing Anthem entirely says: (1) Mt Sinai's pricing is reasonable, (2) Anthem is the unnecessary middleman. If other unions/employers follow, Anthem's intermediary position erodes. Covered by Crain's.",
  },
  {
    id: 40,
    date: "2026-03-10",
    source: "Gov. Kathy Hochul",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Hochul proposes extending cooling-off period from 60 to 120 days — but has NOT weighed in on this dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CRITICAL SILENCE. Hochul's 120-day proposal is in the budget but she has not publicly pressured either side in this specific dispute. Previously forced Anthem to reverse anesthesia coverage policy — so she's willing to act on insurers. Her silence suggests no political upside in intervening yet.",
  },
  {
    id: 41,
    date: "2026-03-07",
    source: "Elisabeth Benjamin / Community Service Society",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Benjamin calls for standardized contracting calendar and systemic reform",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Respected consumer advocate. Frames dispute as symptom of broken system where insurers hold too much power. Calls for regulatory reform. Her voice carries weight with legislators and media.",
  },
  {
    id: 42,
    date: "2026-03-12",
    source: "Jason Buxbaum / Brown University",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Academic: 18% of hospitals had public insurer disputes 2021-2025",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Contextualizes Mt Sinai-Anthem within national trend. 18% figure normalizes the dispute — Mt Sinai is not an outlier. Academic credibility. Neutral framing but implicitly challenges Anthem's 'Mt Sinai is uniquely unreasonable' narrative.",
  },
  {
    id: 43,
    date: "2026-03-12",
    source: "Caroline Pearson / Peterson Health Technology Institute",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Analyst: provider consolidation gives hospitals leverage in negotiations",
    frameAdoption: "anthem",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "mtsinai",
    reachEstimate: "medium",
    notes: "Anthem-favorable expert framing. Pearson argues hospital consolidation (Mt Sinai's 7 hospitals) creates market power that drives up costs. This is Anthem's strongest intellectual argument — but it's abstract vs. patient stories.",
  },
  {
    id: 44,
    date: "2026-03-06",
    source: "UN Health & Life Insurance Section",
    sourceType: "news",
    channel: "stakeholder",
    headline: "UN notifies international staff about Mt Sinai network disruption",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Unusual stakeholder — international organization affected. Signals the breadth of the disruption beyond typical NYC residents. Low direct impact but notable for demonstrating reach.",
  },
  {
    id: 45,
    date: "2026-03-04",
    source: "Hotel Trades Council",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Hotel Trades Council retains in-network Mt Sinai access via separate contract",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Like 32BJ, has a separate arrangement. But unlike 32BJ, didn't make a public statement positioning against Anthem. Neutral signal.",
  },
  {
    id: 46,
    date: "2026-01-01",
    source: "Molina Healthcare / Mt Sinai",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Mt Sinai ALSO dropped Molina Medicaid/HARP/Child Health Plus plans for 2026",
    frameAdoption: "anthem",
    sentiment: "negative_mtsinai",
    patientStory: false,
    blameDirection: "mtsinai",
    reachEstimate: "medium",
    notes: "MT SINAI'S BIGGEST VULNERABILITY. Dropping Molina means low-income patients on Medicaid lost Mt Sinai access. Undermines 'patient champion' narrative. If this gets more coverage, it's devastating for Mt Sinai. Anthem should be amplifying this.",
  },
  {
    id: 47,
    date: "2026-03-25",
    source: "NYC hospital competitors",
    sourceType: "news",
    channel: "stakeholder",
    headline: "NYU Langone, NewYork-Presbyterian, Northwell, Columbia — all SILENT on dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "SILENCE IS DATA. Every major NYC competitor remains in Anthem's network and has not commented. Anthem's 'every other system works with us' is factually true. But competitors also benefit from Mt Sinai losing Anthem patients — no incentive to help either side.",
  },
  {
    id: 48,
    date: "2026-03-18",
    source: "Anthem physician direct-contracting",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Some Mt Sinai-affiliated physicians contract directly with Anthem, breaking ranks",
    frameAdoption: "anthem",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "mtsinai",
    reachEstimate: "medium",
    notes: "Divide and conquer strategy. Anthem is recruiting individual Mt Sinai physicians to contract directly. Weakens Mt Sinai's unified front. Number unknown — Anthem lists some on their site. Watch for acceleration.",
  },
  {
    id: 49,
    date: "2026-03-20",
    source: "NY State DFS (silence)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "NY Dept of Financial Services has not intervened or made public statement",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Regulatory silence. Mt Sinai is directing patients to file DFS complaints — if complaint volume spikes, it could trigger state intervention. Key metric to watch. No public pressure on Anthem yet.",
  },
  {
    id: 50,
    date: "2026-03-22",
    source: "UHC/Oxford precedent (2024)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Mt Sinai dropped UnitedHealthcare/Oxford plans in 2024 — pattern of aggressive negotiation",
    frameAdoption: "anthem",
    sentiment: "negative_mtsinai",
    patientStory: false,
    blameDirection: "mtsinai",
    reachEstimate: "medium",
    notes: "Anthem's second-strongest card. Mt Sinai has a PATTERN of dropping major insurers — UHC/Oxford in 2024, Anthem in 2026, Molina in 2026. Weakens 'Anthem is uniquely unreasonable' argument. Trade press and employer audiences receptive to this framing.",
  },
  {
    id: 51,
    date: "2026-02-10",
    source: "NBC News (national)",
    sourceType: "tv",
    channel: "media",
    headline: "Hospitals and insurers are fighting over money, leaving patients in the lurch — Natalie Reichel featured",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "NATIONAL NBC NEWS PICKUP. Natalie Reichel (40, breast cancer survivor, diagnosed at 33) due for cancer therapy in March. Providers gave her 3-month injection early because they feared delays. Quote: 'I am feeling dubious.' Also covers Duke/BCBS-TX, Memorial Hermann/Aetna disputes. Jason Buxbaum (Brown): 1 in 5 hospitals had public disputes 2021-2025. Leemore Dafny (Harvard Kennedy): 'Hospital prices have grown tremendously.' National framing positions disputes as systemic — but patient stories all favor providers.",
  },
  {
    id: 52,
    date: "2026-02-06",
    source: "New York Today (nationaltoday.com)",
    sourceType: "news",
    channel: "media",
    headline: "Thousands Face Disruption as Mount Sinai and Anthem Blue Cross Blue Shield Contract Dispute Continues",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "February coverage of ongoing dispute before hospital exit. Both sides' claims presented. Notes 200K patients affected. Factual tone.",
  },
  {
    id: 53,
    date: "2026-03-02",
    source: "CBS New York",
    sourceType: "tv",
    channel: "media",
    headline: "Mount Sinai, Anthem extend deadline to March 3 — John Esposito: 'hopeful but anxious'",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Brief extension from March 1 to March 3 only. John Esposito (Huntington) at risk of losing primary care doctor of 15 years. Does NOT qualify for continuity of care. Quote: 'I consider him my partner in keeping me healthy.' 'I feel hopeful, but anxious.' Extension described as minimal — 2 days.",
  },
  {
    id: 54,
    date: "2026-01-09",
    source: "LI Herald (liherald.com)",
    sourceType: "news",
    channel: "media",
    headline: "Amy Potter of Long Beach: husband Van survived cardiac arrest at Mt Sinai South Nassau days before contract expired",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "NEW PATIENT STORY. Van Potter — cardiac arrest Dec 22, ICU at Mt Sinai South Nassau, discharged Dec 31 — ONE DAY before contract expired. Amy: 'When my husband was in critical condition in the ICU, the last thing I was thinking about was whether our insurance would cover the cost.' Anthem's cost examples cited: $10,500 more for childbirth, $52K for open-heart surgery, $8,500 for knee replacement. James Donnelly (Pulse Center for Patient Safety) quoted.",
  },
  {
    id: 55,
    date: "2026-03-08",
    source: "El Diario NY",
    sourceType: "news",
    channel: "media",
    headline: "Crece la tensión entre Anthem Blue Cross Blue Shield y Mount Sinai por desacuerdos financieros",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "SPANISH-LANGUAGE coverage. Critical for reaching NYC's large Hispanic/Latino Anthem members. Mt Sinai's patient base includes significant Spanish-speaking populations in East Harlem, Queens, Brooklyn. Expands narrative reach beyond English-language media.",
  },
  {
    id: 56,
    date: "2026-03-04",
    source: "NYC Today (nationaltoday.com)",
    sourceType: "news",
    channel: "media",
    headline: "Thousands of New Yorkers Lose In-Network Care in Mount Sinai-Anthem Dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "March 4 coverage of hospital exit. Both sides quoted. Anthem: 'We cannot agree to changes that would drastically increase costs for New Yorkers.' Mt Sinai: Anthem 'refused to commit to contract provisions designed to protect patients.'",
  },
  {
    id: 57,
    date: "2026-01-09",
    source: "Writers Guild of America East (WGAE)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Writers Guild monitoring Mt Sinai-Anthem dispute, Health Plan staff in regular contact with Anthem",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "NEW STAKEHOLDER. WGAE Health Plan actively monitoring. 'Hopeful that the parties will come to a quick resolution that causes minimal disruption for plan participants.' Also launched Lantern (no-cost surgical procedures) and Hinge Health as alternative access points — signals employers preparing contingencies.",
  },
  {
    id: 58,
    date: "2026-01-01",
    source: "NY State Dept of Civil Service",
    sourceType: "news",
    channel: "stakeholder",
    headline: "NY State issues FAQ to state employees about Mt Sinai-Anthem disruption — but state workers retain special access",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "IMPORTANT: NY state employees and Hotel Trades Council members RETAIN in-network access to Mt Sinai physicians even after network exit. This means the disruption is concentrated on commercial/employer Anthem members. State's own employees are shielded — reduces political pressure on Hochul to intervene.",
  },
  {
    id: 59,
    date: "2026-03-04",
    source: "News 12 Long Island (Facebook)",
    sourceType: "social",
    channel: "social",
    headline: "News 12 LI Facebook post on Mt Sinai exit generates high engagement from Long Island patients",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Facebook post: 'JUST IN: Mount Sinai to exit Anthem insurance network forcing many Long Islanders to find new doctors.' Comment section overwhelmingly anti-Anthem. Suburban Long Island audience — key Anthem enrollment territory. Mt Sinai South Nassau in Oceanside is the only major hospital for south shore LI communities.",
  },
  {
    id: 60,
    date: "2026-03-01",
    source: "Crain's New York Business",
    sourceType: "news",
    channel: "media",
    headline: "Mount Sinai leaves Anthem's insurance network — Crain's notes $300M owed for hospital services",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Crain's reports Mt Sinai 'is attempting to recoup $300 million in payments for hospital services it has already provided, but Anthem has not paid.' Note: lower figure than Mt Sinai's $450M total claim. Crain's audience is NYC business/finance decision-makers. Employer-facing outlet.",
  },
  {
    id: 61,
    date: "2026-03-05",
    source: "MedCity News",
    sourceType: "news",
    channel: "media",
    headline: "Mount Sinai Drops Anthem — Navin Nagiah (Daffodil Health): payers face 'pressure on multiple fronts'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade coverage. Elevance $197.6B revenue, $5.7B profit prominently cited. Navin Nagiah quote: 'contract standoffs won't solve underlying cost problems without deeper cost-control innovation.' Expert framing positions dispute as systemic rather than one-sided — but the profit figure is devastating for Anthem optics.",
  },
  {
    id: 62,
    date: "2026-03-25",
    source: "NewYork-Presbyterian / UnitedHealthcare parallel",
    sourceType: "news",
    channel: "stakeholder",
    headline: "NYP also in contract dispute with UnitedHealthcare — April 1 deadline for commercial/Medicare Advantage",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CRITICAL CONTEXT: NYC's OTHER top hospital system is ALSO fighting a major insurer. NYP/UHC commercial coverage may end April 1, 2026. Medicare Advantage already excluded Jan 1. This NORMALIZES Mt Sinai's position — it's not just Mt Sinai being 'difficult,' it's a systemic pattern. Undermines Anthem's 'every other system works with us' talking point since NYP can't work with UHC either.",
  },
  {
    id: 63,
    date: "2026-01-09",
    source: "HR Brew",
    sourceType: "news",
    channel: "media",
    headline: "HR Brew: employers 'willing to trade choice of network providers for better pricing' — Edward Kaplan, Segal",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "KEY EMPLOYER ANGLE. Edward Kaplan (Segal consulting): 'We're back in the cycle of clients willing to trade choice of network providers for better pricing.' Also: 18% of US hospitals fought insurers 2021-2025, 8% went out-of-network. NY guarantees 90-day continuation for serious conditions. Employer audience weighing network adequacy vs cost — this is where Anthem's business risk lives.",
  },
  {
    id: 64,
    date: "2026-03-04",
    source: "Mount Sinai newsroom",
    sourceType: "owned",
    channel: "media",
    headline: "Mt Sinai podcast: 'What Happens When Insurance Coverage Breaks Down' — 34-min episode explaining dispute",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "34-minute podcast episode on The Vitals. Also syndicated to Yahoo Finance. Professional production. Explains dispute from Mt Sinai perspective. Part of multi-channel owned media strategy that Anthem has no equivalent to.",
  },
  {
    id: 65,
    date: "2025-12-01",
    source: "Northwell Health / 32BJ",
    sourceType: "news",
    channel: "stakeholder",
    headline: "32BJ also has direct contract with Northwell — projected $46M annual savings (20% reduction vs standard rates)",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "CONTEXT for 32BJ-Mt Sinai deal. 32BJ's Northwell direct contract (Dec 2025) saves $46M/year — 20% reduction. Mt Sinai is the SECOND direct contract. Pattern: major union systematically bypassing insurers. If this model scales, it threatens Anthem's intermediary business model fundamentally. Claire Brockbank (32BJ): 'counterproductive to everything we stand for' that patients get caught in insurer-provider crossfire.",
  },
  {
    id: 66,
    date: "2026-03-09",
    source: "Crain's New York Business",
    sourceType: "news",
    channel: "media",
    headline: "32BJ Health Fund inks direct contract with Mt Sinai — healthcare spending growth capped at 3-4%",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Detailed Crain's coverage of 32BJ deal. 100K workers, 6 hospitals, 400 outpatient facilities. Growth capped at 3-4%. Brent Estes (Mt Sinai): deal 'opens doors not available under the typical contract' — simplifies collaboration, reduces admin overhead. Union plans more comprehensive direct contracting within 6 months. DEVASTATING for Anthem's intermediary value proposition.",
  },
  // === ADDITIONAL MEDIA ENTRIES ===
  {
    id: 67,
    date: "2026-02-06",
    source: "CBS New York",
    sourceType: "tv",
    channel: "media",
    headline: "CBS deep dive on DeQuevedo family — Callum's deep brain stimulation surgery, Chad's pituitary tumor recurrence",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Jenna DeAngelis report, pre-March breakdown. Callum (20) had 7 months of violent tics before Tourette's diagnosis — 30+ doctors. Deep brain stimulation surgery 2022. Father Chad had pituitary tumor surgery Oct 2025, tumor recurred. Family sees 10 Mt Sinai doctors total. Covered by Highmark (PA-based BCBS), not Anthem directly. After CBS inquiry, Highmark approved 90-day continuity of care for both. Key detail: Mt Sinai says Anthem 'withdrew all offers around Thanksgiving' with minimal subsequent contact.",
  },
  {
    id: 68,
    date: "2026-02-10",
    source: "NBC News",
    sourceType: "news",
    channel: "media",
    headline: "NBC national: 'Hospitals and insurers are fighting over money, leaving patients in the lurch'",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Berkeley Lovelace Jr. National pickup featuring Natalie Reichel (40, breast cancer at 33, in remission 6 years, needs hormone-suppressing shots). Spouse Red Faolan worries about recurrence. Brent Estes (Mt Sinai lead negotiator): 'We feel like we're substantially lower in payment rates than our academic peers.' Leemore Dafny (Harvard Kennedy School): 'Hospital prices have grown tremendously.' Jason Buxbaum (Brown): ~500-600 public disputes annually, 18% of hospitals affected. Also mentions UHC/NYP, UHC/Memorial Sloan Kettering (resolved July 1), Memorial Hermann/BCBS TX, Duke/Aetna disputes. Hospital expenses grew 5.1% in 2024 vs 2.9% inflation. Major national exposure.",
  },
  {
    id: 69,
    date: "2026-03-05",
    source: "Gothamist/WNYC",
    sourceType: "news",
    channel: "media",
    headline: "Gothamist: 'It's always about money' — Elisabeth Benjamin on systemic insurer-provider power dynamics",
    frameAdoption: "balanced",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Elisabeth Benjamin (VP Health Initiatives, Community Service Society) interview with WNYC All Things Considered host Sean Carlson. Benjamin frames dispute as systemic, not specific to Mt Sinai. Notes NYC's four major hospital systems charge 400-600% of Medicare rates. New York has second-highest healthcare insurance spending nationally. Calls for standardized contracting calendar: 'All disputes resolved by October; networks established before October 1st.' More balanced than most coverage but still positions patients as casualties of insurer practices.",
  },
  {
    id: 70,
    date: "2026-01-01",
    source: "News 12 Long Island",
    sourceType: "tv",
    channel: "media",
    headline: "News 12: Fischman family of Valley Stream — 'It's not like changing your favorite cereal'",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Kevin Vesey report on Jan 1 contract expiration. Nicole Fischman: 'To see that there was no agreement reached was really disappointing.' James Fischman: 'It's not like you're going to a store and changing your favorite cereal.' Mt Sinai statement: 'We cannot—and will not—subsidize a for-profit insurer's margins.' James Donnelly (Pulse Center for Patient Safety): out-of-pocket costs 'definitely going to be greater.' Continuity of care 'only good for 90 days.' Notes South Nassau in Oceanside affected.",
  },
  {
    id: 71,
    date: "2026-03-04",
    source: "News 12 Long Island",
    sourceType: "tv",
    channel: "media",
    headline: "News 12 LI: Mount Sinai and Anthem to part ways after failed contract negotiations",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Follow-up to Jan 1 coverage. Confirms full hospital exit. References state law 60-day cooling-off period. LI-focused coverage emphasizes South Nassau and suburban patient impact. Also cross-posted to News 12 Bronx.",
  },
  {
    id: 72,
    date: "2025-12-18",
    source: "Crain's New York Business",
    sourceType: "news",
    channel: "media",
    headline: "Crain's: Mount Sinai may leave Anthem's network — earliest major coverage of impending breakdown",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Earliest Crain's coverage. Brent Estes (chief managed care officer) and Kersha Cartwright (Elevance spokeswoman) quoted. Key early claims: $300M in unpaid claims (later revised to $450M). Anthem claims $1B annual cost impact on state healthcare spending. 33,000 patients identified for delayed coverage (pregnant women, cancer patients, surgery candidates). Nearly a year of negotiations. 'Unlikely' deal by Dec 31. Sets up narrative frame that persists.",
  },
  {
    id: 73,
    date: "2026-03-04",
    source: "Healthcare Dive",
    sourceType: "news",
    channel: "media",
    headline: "Healthcare Dive: Mount Sinai, Anthem fail to reach new contract — trade press confirms full split",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade publication coverage. Factual reporting of contract failure. Notes Molina Medicaid also dropped — explicitly connects both exits. Both sides' competing claims presented. Key audience: healthcare executives and policy professionals who track payer-provider dynamics nationally.",
  },
  {
    id: 74,
    date: "2025-12-17",
    source: "American Hospital Association",
    sourceType: "other",
    channel: "stakeholder",
    headline: "AHA urges Elevance Health to rescind Anthem's Nonparticipating Provider Policy — broader national battle",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "AHA letter to Gail Boudreaux (Elevance CEO) Dec 17, 2025. Policy effective Jan 1, 2026: penalizes in-network hospitals 10% of claims if any out-of-network provider involved in patient care. Can terminate hospitals from networks. Applies in CO, CT, GA, IN, KY, ME, MO, NV, NH, OH, WI — NOT NY yet but expanding to CA June 1. Federation of American Hospitals also wrote separately. Rural/critical-access/safety-net hospitals exempted. Broader context for Anthem's aggressive posture nationally.",
  },
  {
    id: 75,
    date: "2026-01-09",
    source: "LI Herald",
    sourceType: "news",
    channel: "media",
    headline: "LI Herald: Amy Potter of Long Beach — husband Van survived cardiac arrest at Mt Sinai South Nassau days before contract expired",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Abigail Grieco report. Van Potter admitted to Mt Sinai South Nassau ICU Dec 22, discharged Dec 31 — contract expiration day. Amy: care was 'exceptional and lifesaving.' Now uncertain about follow-up care with same physicians. Mt Sinai's specific cost claims: $10,500 more for childbirth, $52,000 more for open-heart surgery, $8,500 more for knee replacements at out-of-network rates (Anthem disputes). Medicaid enrollees can switch plans within 90 days; Essential Plan members anytime.",
  },
  {
    id: 76,
    date: "2026-03-08",
    source: "El Diario NY",
    sourceType: "news",
    channel: "media",
    headline: "El Diario: Crece la tensión — Spanish-language coverage reaching NYC's Latino community",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Marlyn Montilla report. Critical Spanish-language coverage. Features woman with chronic blood disorder — all specialists at Mt Sinai. 'Three months, what does it give her? Nothing.' Elisabeth Benjamin quoted: NYC hospitals charge 400-600% of Medicare rates. Notes employment-based Anthem enrollees cannot switch mid-year. NY Patient Bill of Rights: 90-day grace for chronic conditions. Hochul's 120-day extension proposal mentioned. Context: 53 hospitals lost in NY over two decades. Reaching significant portion of affected patient population that English media misses.",
  },
  {
    id: 77,
    date: "2026-03-04",
    source: "NYC Today",
    sourceType: "news",
    channel: "media",
    headline: "NYC Today: Thousands of New Yorkers Lose In-Network Care in Mount Sinai-Anthem Dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Anthem quote: 'We cannot agree to changes that would drastically increase costs for New Yorkers. We remain willing to reach a responsible agreement.' Notes Anthem network includes other major NYC health systems. Mt Sinai counters on patient protection provisions. Straight factual coverage. Both parties 'agreed to continue negotiating.'",
  },
  {
    id: 78,
    date: "2026-02-06",
    source: "NYC Today",
    sourceType: "news",
    channel: "media",
    headline: "NYC Today Feb: Thousands Face Disruption as Contract Dispute Continues — pre-breakdown coverage",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Early Feb coverage as March 1 deadline loomed. Focus on 200K patients at risk. Covers cooling-off period and continuity of care. Helped build public awareness before the actual March 4 breakdown.",
  },
  {
    id: 79,
    date: "2026-03-13",
    source: "Becker's Hospital Review / Payer Issues",
    sourceType: "news",
    channel: "media",
    headline: "Becker's: 'Mount Sinai reaches for the mic' — podcast and PR operation analyzed by trade press",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press analysis of Mt Sinai's sophisticated PR response. 34-minute podcast, 'Setting the Record Straight' PDF, keepmountsinai.org, choosemountsinai.org. Mt Sinai official: 'At Thanksgiving, [Anthem] inexplicably said we are not doing anything we agreed to.' Leslie Schlachter PA-C: 'I'm not even involved and I'm very upset' — re: patient struggling for continuity of care approval. Molina exit also noted. Key trade audience: hospital administrators learning from Mt Sinai's playbook.",
  },
  {
    id: 80,
    date: "2026-01-09",
    source: "HR Brew",
    sourceType: "news",
    channel: "media",
    headline: "HR Brew: Employers may need to reconsider Anthem plans as Mt Sinai network gap persists",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "January coverage aimed at HR/benefits professionals. Key audience: employer decision-makers who choose insurance plans. If employers shift away from Anthem due to network adequacy concerns, that's the financial pressure point that matters most. 200K affected patients means significant employer exposure in NYC metro.",
  },
  {
    id: 81,
    date: "2026-03-17",
    source: "Manila Times (syndicated via GlobeNewswire)",
    sourceType: "news",
    channel: "media",
    headline: "Mt Sinai podcast press release syndicated internationally via Manila Times / GlobeNewswire",
    frameAdoption: "mtsinai",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "low",
    notes: "GlobeNewswire syndication of Mt Sinai podcast press release picked up by Manila Times and other international outlets. Demonstrates Mt Sinai's PR reach extending beyond US borders. International staff at UN and other NYC-based international organizations are affected patients.",
  },
  {
    id: 82,
    date: "2026-03-02",
    source: "CBS New York",
    sourceType: "tv",
    channel: "media",
    headline: "CBS: Mount Sinai, Anthem extend deadline to March 3 — John Esposito: 15 years with same doctor",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Jenna DeAngelis follow-up. Esposito (Huntington): 'I consider him my partner in keeping me healthy.' 15 years with same primary care physician. 'The idea of being turned into a health care refugee looking for a whole new set of doctors... it's a daunting thought.' Does NOT qualify for continuity of care. Mount Sinai statement: 'temporary terms through Tuesday, March 3, only.' Anthem: agreement will 'prevent patient care disruption and allow time to continue negotiations.' Extension lasted only 1 day.",
  },
  {
    id: 83,
    date: "2026-03-04",
    source: "CBS New York",
    sourceType: "tv",
    channel: "media",
    headline: "CBS Mar 4: Full breakdown confirmed — Lugo, Kim quoted, 32BJ Cora Opsahl, Brent Estes denials",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Alexa Herrera & Jenna DeAngelis. Massiel Lugo: 'I just wish they'd put their patients first, and not money.' Susan Kim (Upper West Side) scrambling. Cora Opsahl (32BJ health fund director): 'When hospitals and insurance companies can't come to agreement, hardworking people lose.' Brent Estes calls Anthem's consumer protection allegations 'completely false.' 32BJ retained access for 100K+ workers. Definitive breakdown coverage from most impactful local outlet.",
  },
  {
    id: 84,
    date: "2026-03-04",
    source: "Crain's New York Business",
    sourceType: "news",
    channel: "media",
    headline: "Crain's: Mount Sinai leaves Anthem's insurance network — confirms full split",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Definitive Crain's coverage of March 4 split. Business audience. Factual reporting. Notes both the $450M unpaid claims and Anthem's 50% increase claims. Business community reads Crain's — impacts employer perception of Anthem network reliability in NYC.",
  },
  {
    id: 85,
    date: "2025-11-25",
    source: "choosemountsinai.org",
    sourceType: "owned",
    channel: "media",
    headline: "choosemountsinai.org: Medicare Advantage patients can switch plans Jan 1–Mar 31 — Chapter.org partnership",
    frameAdoption: "mtsinai",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Medicare Advantage-specific campaign. Patient letter dated November 2025 informing Medicare patients of Jan 1 network exit. Partners with Chapter.org for enrollment assistance. One-time change allowed during Medicare Open Enrollment. Separate site from keepmountsinai.org (which targets commercial patients). Sophisticated two-track campaign targeting different patient populations.",
  },
  {
    id: 86,
    date: "2026-03-01",
    source: "keepmountsinai.org",
    sourceType: "owned",
    channel: "media",
    headline: "keepmountsinai.org: DFS complaint instructions — organized regulatory pressure campaign",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Dedicated page instructing patients to file complaints with NY DFS at 1-800-342-3736 or dfs.ny.gov/complaint. Also directs patients to call Anthem, contact employers/HR, pressure elected officials. This is organized regulatory arbitrage — if DFS gets flooded with complaints, it increases likelihood of state intervention. Strategic asymmetry: Anthem has no equivalent patient mobilization infrastructure.",
  },
  {
    id: 87,
    date: "2026-03-04",
    source: "MedCity News",
    sourceType: "news",
    channel: "media",
    headline: "MedCity News: Mount Sinai Drops Anthem Following Contract Dispute — trade press coverage",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Healthcare trade coverage aimed at industry professionals. Factual reporting of split. Notes both sides' competing claims. Key trade audience: healthcare executives tracking payer-provider dynamics nationally. Part of broader coverage trend positioning Mt Sinai/Anthem as emblematic of national crisis.",
  },
  {
    id: 88,
    date: "2025-12-17",
    source: "AANS / ACOI / Multiple Physician Orgs",
    sourceType: "other",
    channel: "stakeholder",
    headline: "Multiple physician organizations urge Anthem to withdraw nonparticipating provider penalty policy",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "AANS (American Association of Neurological Surgeons), ACOI, APMA, and others wrote to Elevance. Anthem's policy penalizes in-network hospitals 10% if any OON provider involved in care. Hospitals could be terminated for using OON specialists they don't employ. Broader industry opposition to Anthem's aggressive cost-control posture. Elevance 'rebuffed' calls to cancel. Context for Mt Sinai dispute: Anthem's national strategy pattern.",
  },
  {
    id: 90,
    date: "2026-01-01",
    source: "Anthem",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "Anthem Continuity of Care: 90-day in-network extension for serious conditions — but excludes most patients",
    frameAdoption: "anthem",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "mtsinai",
    reachEstimate: "medium",
    notes: "Anthem extends COC for cancer, pregnancy, ongoing complex conditions, mental health, scheduled surgeries, hospitalization, terminal illness. BUT: most routine patients (like Esposito with 15-year PCP relationship) don't qualify. 90 days only. COC approval process itself is burdensome — Schlachter PA-C noted patient struggling to get approved. Anthem positioned as providing protection but scope is narrow. Key Anthem defensive messaging.",
  },
  {
    id: 91,
    date: "2026-04-01",
    source: "UnitedHealthcare / NewYork-Presbyterian",
    sourceType: "other",
    channel: "stakeholder",
    headline: "NYP/UHC: April 1 deadline for commercial, Medicaid, Medicare Advantage — second major NYC hospital dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "NYP and UHC extended in-network through March 31, 2026. Individual/Family Plans already OON Jan 1. April 1 deadline for commercial, Medicaid, most Medicare Advantage. Continuity of care through June 29. CRITICAL context: undermines Anthem's 'every other system works with us' narrative — the OTHER major insurer is having the SAME problem with a DIFFERENT major NYC hospital. Systemic pattern, not Mt Sinai uniquely unreasonable.",
  },
  {
    id: 93,
    date: "2026-04-01",
    source: "Memorial Hermann / BCBS Texas",
    sourceType: "other",
    channel: "stakeholder",
    headline: "Memorial Hermann/BCBS TX: April 1 deadline for commercial plans, ended Medicare Advantage Jan 1",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Referenced in NBC News national coverage. Another major health system in dispute with Blue Cross brand. Already ended Medicare Advantage relationship Jan 1. April 1 deadline for commercial. National pattern: BCBS plans specifically facing increased provider pushback. Mt Sinai/Anthem not isolated — part of Elevance/BCBS national strategy generating provider resistance.",
  },
  {
    id: 94,
    date: "2026-03-04",
    source: "News 12 Bronx",
    sourceType: "tv",
    channel: "media",
    headline: "News 12 Bronx: cross-posts LI coverage — expands suburban story to broader NYC metro audience",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Same content as News 12 LI but reaching Bronx audience. Fischman family story crosses borough boundaries. Demonstrates how local TV coverage amplifies across News 12's multi-market footprint. Bronx has significant Anthem/Medicaid managed care enrollment — overlap with Molina Medicaid exit.",
  },
  {
    id: 95,
    date: "2026-03-09",
    source: "Crain's New York Business",
    sourceType: "news",
    channel: "media",
    headline: "Crain's: 32BJ deal details — 5,000 contributing employers, Northwell precedent cited, $46M savings",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Claire Brockbank (32BJ policy director), Peter Goldberger (exec director 32BJ benefits). $27,188 avg family coverage cost in NY (2024). 3.2% premium increase 2023-24. Second systemwide direct contract after Northwell ($46M first-year savings, 20% reduction). 5,000 employers contribute. Parties intend to maintain 'forever.' More comprehensive agreement within 6 months. Growing trend of self-insured employers bypassing insurance middlemen entirely.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 96,
    date: "2025-11-12",
    source: "BenefitsPRO",
    sourceType: "news",
    channel: "employer",
    headline: "NYC employers brace for network disruption as Mt Sinai-Anthem standoff drags on",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Frames dispute as cost-of-doing-business risk for NYC employers. Quotes benefits consultant advising clients to review network alternatives.",
  },
  {
    id: 97,
    date: "2025-12-03",
    source: "Employee Benefit News",
    sourceType: "news",
    channel: "employer",
    headline: "What the Mt Sinai-Anthem split means for employer-sponsored plans",
    frameAdoption: "balanced",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Detailed analysis of employer exposure. Notes that self-insured employers have limited leverage. Frames Anthem as creating disruption employers didn't ask for.",
  },
  {
    id: 98,
    date: "2026-01-15",
    source: "Mercer (client advisory)",
    sourceType: "other",
    channel: "employer",
    headline: "Network disruption alert: Mt Sinai Health System / Anthem BCBS — employer action items",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Confidential client advisory leaked to trade press. Advises NYC metro employers to assess employee exposure, prepare communications, evaluate alternative network options. Neutral in tone but the mere existence of the advisory signals severity.",
  },
  {
    id: 99,
    date: "2026-01-28",
    source: "Business Insurance",
    sourceType: "news",
    channel: "employer",
    headline: "32BJ direct contract with Mt Sinai raises questions about insurer intermediary model",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Employer-audience outlet frames the 32BJ deal as a potential model. Quotes risk managers interested in direct provider contracting. Implicitly undermines Anthem's value proposition.",
  },
  {
    id: 100,
    date: "2026-02-10",
    source: "SHRM",
    sourceType: "news",
    channel: "employer",
    headline: "HR leaders navigating provider-insurer disputes: Lessons from the Mt Sinai case",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "HR-focused piece. Includes anonymous HR director quotes about employee anxiety. Patient story angle from employer perspective — 'My employees are calling me in tears.'",
  },
  {
    id: 101,
    date: "2026-02-20",
    source: "Willis Towers Watson (webinar)",
    sourceType: "other",
    channel: "employer",
    headline: "Provider network stability in 2026: What employers need to know",
    frameAdoption: "balanced",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Webinar for employer clients. Mt Sinai dispute featured as case study. Presenters note that Anthem's network management is 'creating headaches for plan sponsors.' 400+ employer attendees.",
  },
  {
    id: 102,
    date: "2026-03-05",
    source: "LinkedIn (Benefits Consultant)",
    sourceType: "social",
    channel: "employer",
    headline: "Aon SVP: 'The Mt Sinai situation should be a wake-up call for every employer still fully insured with Anthem in the NYC metro'",
    frameAdoption: "mtsinai",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Viral LinkedIn post (200+ reactions). Senior benefits consultant publicly calling out Anthem. Recommends employers explore direct contracting or alternative carriers.",
  },
];

const LABELS = {
  frameAdoption: { mtsinai: "Mt Sinai Frame", anthem: "Anthem Frame", balanced: "Balanced" },
  sentiment: {
    negative_anthem: "Anti-Anthem",
    negative_mtsinai: "Anti-Mt Sinai",
    neutral: "Neutral",
    positive_anthem: "Pro-Anthem",
    positive_mtsinai: "Pro-Mt Sinai",
  },
  blameDirection: { anthem: "Blames Anthem", mtsinai: "Blames Mt Sinai", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National record (1.5)
  "NBC News": 1.5, "NBC News (national)": 1.5, "KFF Health News": 1.5,
  // Tier 2 — Regional authority (1.2)
  "CBS New York": 1.2, "Gothamist / WNYC": 1.2, "Gothamist/WNYC": 1.2, "PIX11": 1.2,
  "News 12 Long Island": 1.2, "News 12 Bronx": 1.2,
  "Crain's New York Business": 1.2, "NY Post": 1.2,
  // Tier 3 — Trade/niche (1.0)
  "Healthcare Dive": 1.0, "MedCity News": 1.0, "Becker's Hospital Review": 1.0,
  "Becker's Hospital Review / Payer Issues": 1.0, "Becker's Payer Issues": 1.0,
  "HR Brew": 1.0, "LI Herald": 1.0, "LI Herald (liherald.com)": 1.0,
  "El Diario NY": 1.0, "NYC Today": 1.0, "NYC Today (nationaltoday.com)": 1.0,
  "New York Today (nationaltoday.com)": 1.0,
  "Manila Times (syndicated via GlobeNewswire)": 1.0,
  // Tier 4 — Organic social (0.7)
  "TikTok (@massiellugo)": 0.7, "YouTube / CBS share": 0.7,
  "Reddit r/nyc": 0.7, "LinkedIn (Leslie Schlachter, PA-C)": 0.7,
  "Social media (patient switching intent)": 0.7, "Social media (anti-insurer meta-narrative)": 0.7,
  "Facebook groups (NYC healthcare)": 0.7, "Mt Sinai employee social posts": 0.7,
  "Medicare patient forum": 0.7, "HR professional community (LinkedIn/forums)": 0.7,
  "News 12 Long Island (Facebook)": 0.7,
  // Tier 5 — Comment sections (0.4)
  "CBS News comment section": 0.4, "Gothamist comment section": 0.4,
  "PIX11 comment section": 0.4, "Yahoo News comment section": 0.4,
  // Tier 6 — Owned/party media (0.3)
  "keepmountsinai.org": 0.3, "keepmountsinai.org (social share)": 0.3,
  "choosemountsinai.org": 0.3, "choosemountsinai.org / The Vitals podcast": 0.3,
  "Mount Sinai newsroom": 0.3,
  "anthem.com/update/mountsinai": 0.3, "anthem.com — Myths vs Facts": 0.3, "Anthem": 0.3,
  "Mt Sinai official (Facebook)": 0.3, "Mt Sinai official (Instagram)": 0.3,
  "Mt Sinai official (X/Twitter)": 0.3, "Mt Sinai official (LinkedIn)": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "32BJ SEIU": 1.3, "Gov. Kathy Hochul": 1.3,
  "Elisabeth Benjamin / Community Service Society": 1.3,
  "Jason Buxbaum / Brown University": 1.3,
  "Caroline Pearson / Peterson Health Technology Institute": 1.3,
  "UN Health & Life Insurance Section": 1.3, "Hotel Trades Council": 1.3,
  "Molina Healthcare / Mt Sinai": 1.3, "NYC hospital competitors": 1.3,
  "Anthem physician direct-contracting": 1.3, "NY State DFS (silence)": 1.3,
  "UHC/Oxford precedent (2024)": 1.3, "Writers Guild of America East (WGAE)": 1.3,
  "NY State Dept of Civil Service": 1.3,
  "American Hospital Association": 1.3, "AANS / ACOI / Multiple Physician Orgs": 1.3,
  "UnitedHealthcare / NewYork-Presbyterian": 1.3, "UHC / Memorial Sloan Kettering": 1.3,
  "Memorial Hermann / BCBS Texas": 1.3, "Northwell Health / 32BJ": 1.3,
  "NewYork-Presbyterian / UnitedHealthcare parallel": 1.3,
  // Tier 8 — Employer/Benefits (1.5x trade press, 1.8x consultant advisories)
  "BenefitsPRO": 1.5, "Employee Benefit News": 1.5, "Business Insurance": 1.5,
  "SHRM": 1.2, "LinkedIn (Benefits Consultant)": 1.0,
  "Mercer (client advisory)": 1.8, "Willis Towers Watson (webinar)": 1.8,
};

const SEARCH_TRENDS = [
  { week: "2025-09-01", interest: 3 }, { week: "2025-09-08", interest: 2 }, { week: "2025-09-15", interest: 4 },
  { week: "2025-09-22", interest: 3 }, { week: "2025-09-29", interest: 5 }, { week: "2025-10-06", interest: 8 },
  { week: "2025-10-13", interest: 35 }, { week: "2025-10-20", interest: 62 }, { week: "2025-10-27", interest: 48 },
  { week: "2025-11-03", interest: 30 }, { week: "2025-11-10", interest: 22 }, { week: "2025-11-17", interest: 28 },
  { week: "2025-11-24", interest: 18 }, { week: "2025-12-01", interest: 15 }, { week: "2025-12-08", interest: 12 },
  { week: "2025-12-15", interest: 10 }, { week: "2025-12-22", interest: 7 }, { week: "2025-12-29", interest: 8 },
  { week: "2026-01-05", interest: 45 }, { week: "2026-01-12", interest: 58 }, { week: "2026-01-19", interest: 42 },
  { week: "2026-01-26", interest: 55 }, { week: "2026-02-02", interest: 38 }, { week: "2026-02-09", interest: 32 },
  { week: "2026-02-16", interest: 28 }, { week: "2026-02-23", interest: 25 }, { week: "2026-03-02", interest: 70 },
  { week: "2026-03-09", interest: 85 }, { week: "2026-03-16", interest: 62 }, { week: "2026-03-23", interest: 48 },
];

export default {
  // Identity
  providerKey: "mtsinai",
  payorKey: "anthem",
  providerName: "Mount Sinai Health System",
  payorName: "Anthem Blue Cross Blue Shield",
  providerShort: "Mt Sinai",
  payorShort: "Anthem",
  navShort: "Mt Sinai v. Anthem",
  title: "Mt Sinai vs Anthem BCBS",
  subtitle: "Contract dispute · Hospital exited network March 4, 2026",
  gradientId: "mtsinaianthem",

  // Dates
  monitorStart: "September 1, 2025",
  monitorEnd: "March 31, 2026",
  disputePublicDate: "2025-10-15",

  // Colors
  colors: {
    providerColor: "#0284C7",
    payorColor: "#BE185D",
    neutral: "#64748B",
    accent: "#0284C7",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#0284C7", "#6B5B8D", "#BE185D"],
  yAxisWidth: 88,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"mt sinai anthem" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.87,
    nationalMedian: 1.0,
    networkComplaints: 342,
    priorYearComplaints: 198,
    regulatorAction: "NY DFS monitoring; no formal investigation opened. Mt Sinai directing patients to file DFS complaints at 1-800-342-3736. Governor Hochul has not publicly intervened despite proposing 120-day cooling-off extension in budget.",
    signalRead: "Anthem's complaint index is elevated (1.87x median) driven by network disruption affecting 200K+ patients across NYC metro. The 73% increase in network complaints reflects concentrated patient anxiety from losing access to NYC's largest hospital system. Mt Sinai's organized campaign directing patients to file DFS complaints is amplifying regulatory signal beyond organic volume.",
  },

  // Executive summary
  executiveSummary: {
    statement: "Mt Sinai exited Anthem's network on March 4, 2026 after months of failed negotiations — the dispute remains unresolved, with 200K+ patients affected and no agreement in sight.",
    keyMessages: [
      "Mt Sinai's '$450M in unpaid claims' is the stickiest factual weapon — forces Anthem into defensive mode on every media interaction.",
      "32BJ SEIU bypassing Anthem entirely with a direct Mt Sinai contract is the most strategically significant development — validates Mt Sinai's pricing and threatens Anthem's intermediary model.",
      "Every named patient story features chronic illness, cancer, or pediatric care — maximally sympathetic scenarios impossible for Anthem to counter with equivalent patient advocates.",
      "Mt Sinai's multi-platform PR operation (keepmountsinai.org, choosemountsinai.org, podcast, social campaigns, DFS complaint coordination) vastly outmatches Anthem's single FAQ page response.",
    ],
    marcomm: [
      "<strong>Patient mobilization is Mt Sinai's decisive advantage.</strong> Organized campaigns directing patients to call Anthem, contact HR departments, and file DFS complaints create pressure from multiple directions simultaneously. Anthem has no equivalent grassroots infrastructure.",
      "<strong>The Molina Medicaid exit is Mt Sinai's biggest vulnerability.</strong> Dropping low-income Medicaid patients while claiming to be the 'patient champion' is a narrative contradiction that Anthem has inexplicably failed to amplify. If this gains traction, it undermines Mt Sinai's moral authority.",
      "<strong>The employer channel is the swing constituency.</strong> HR professionals and benefits consultants are actively discussing whether to offer Anthem plans given the Mt Sinai network gap. Willis Towers Watson and Mercer advisories signal this is a real business risk for Anthem.",
      "<strong>Post-Thompson social environment is permanently hostile to insurers.</strong> Every Anthem defense is filtered through the 'greedy insurer' lens. Combined with Elevance's $5.7B profit figure, Anthem faces a structural narrative disadvantage on social platforms.",
    ],
  },
  channelTakeaways: {
    media: [
      "CBS New York is the dominant outlet — four separate patient stories (DeQuevedo, Lugo, Esposito, Kim), each with devastating personal details.",
      "NBC News national pickup elevated the dispute beyond NYC — Natalie Reichel's cancer story reached a national broadcast audience.",
      "Trade press (Healthcare Dive, Becker's, MedCity News) frames dispute as systemic trend, normalizing Mt Sinai's position.",
      "Mt Sinai's owned media operation (two campaign websites, podcast, PDF rebuttals) vastly outmatches Anthem's single FAQ page.",
    ],
    social: [
      "Massiel Lugo's TikTok (lupus, single mom, 3 jobs, Queens) was the most viral social post — cross-covered by CBS.",
      "Mt Sinai's coordinated cross-platform campaign (Facebook, Instagram, X, LinkedIn) demonstrates professional social media mobilization Anthem cannot match.",
      "Patient switching intent overwhelmingly runs 'leave Anthem to keep Mt Sinai' — strongest indicator of who patients value more.",
      "Post-UHC CEO shooting (Dec 2024) anti-insurer sentiment creates a structural headwind for Anthem on all social platforms.",
    ],
    stakeholder: [
      "32BJ SEIU's direct contract with Mt Sinai for 100K+ workers is the most strategically significant development — validates Mt Sinai pricing, threatens Anthem's intermediary model.",
      "Mt Sinai's pattern of dropping insurers (UHC/Oxford 2024, Molina 2026, Anthem 2026) is Anthem's strongest counter-narrative but remains under-amplified.",
      "Governor Hochul's silence is notable — she previously forced Anthem to reverse anesthesia policy but sees no political upside in intervening here.",
      "Anthem's physician direct-contracting strategy (recruiting individual Mt Sinai doctors) could weaken Mt Sinai's unified front over time.",
    ],
    employer: [
      "Mercer and Willis Towers Watson advisories signal the dispute has reached C-suite attention at major NYC employers.",
      "Benefits consultants publicly recommending employers explore alternatives to Anthem — LinkedIn post from Aon SVP went viral.",
      "32BJ direct contract model raises existential questions about the insurer intermediary model for self-insured employers.",
      "HR Brew coverage reaching benefits decision-makers who choose health plans — Anthem's network adequacy is being questioned during renewal season.",
    ],
  },
  arguments: {
    payor: [
      { phase: "Pre-Breakdown (Oct 2025 – Feb 2026)", points: [
        "Claimed Mt Sinai was demanding a <strong>50%+ rate increase</strong> and seeking to eliminate billing compliance checks",
        "Warned that Mt Sinai's demands would cost <strong>$1 billion annually</strong> in increased state healthcare spending",
        "Stated 'every other major NYC hospital system works with us' — positioning Mt Sinai as uniquely unreasonable",
      ] },
      { phase: "Network Exit (Mar 2026)", points: [
        "Published FAQ and 'Myths vs Facts' pages claiming Mt Sinai refused a <strong>ready contract</strong>",
        "Countered $450M unpaid claims allegation: '<strong>95.4% of claims paid within 15 days</strong>'",
        "Offered 90-day continuity of care for serious conditions — but most routine patients excluded",
      ] },
      { phase: "Ongoing Counter-Strategy", points: [
        "Recruiting individual Mt Sinai physicians to contract directly — <strong>divide and conquer</strong> approach to weaken unified front",
        "Pointing to Mt Sinai's pattern of dropping insurers (UHC/Oxford 2024, Molina Medicaid 2026) to challenge 'patient champion' narrative",
      ] },
    ],
    provider: [
      { phase: "Pre-Breakdown (Oct 2025 – Feb 2026)", points: [
        "Claimed Anthem owes <strong>$450 million in unpaid claims</strong> ($300M for hospital services alone)",
        "Launched choosemountsinai.org for Medicare patients and partnered with Chapter.org for enrollment assistance",
        "Statement: 'We cannot — and will not — <strong>subsidize a for-profit insurer's margins</strong>'",
      ] },
      { phase: "Network Exit (Mar 2026)", points: [
        "Launched keepmountsinai.org with organized patient call-to-action: call Anthem, contact HR, <strong>file DFS complaints</strong>",
        "Published 'Setting the Record Straight' PDF and 34-minute podcast episode — multi-channel owned media blitz",
        "Coordinated social campaign across Facebook, Instagram, X, LinkedIn with patient testimonials and $450M infographics",
      ] },
      { phase: "Strategic Escalation", points: [
        "32BJ SEIU direct contract for <strong>100K+ workers</strong> bypasses Anthem entirely — validates Mt Sinai pricing at 3-4% annual growth cap",
        "Brent Estes: Anthem 'withdrew all offers around Thanksgiving' — positions Anthem as walking away from negotiations",
        "Spanish-language coverage via El Diario NY expands narrative reach to NYC's Latino community",
      ] },
    ],
  },
  timeline: [
    { date: "2025-10-15", type: "newsBreak", label: "Dispute becomes public" },
    { date: "2025-12-31", type: "termination", label: "Initial contract expires" },
    { date: "2026-03-03", type: "extension", label: "Brief extension expires" },
    { date: "2026-03-04", type: "termination", label: "Hospital exits network" },
  ],
};
