// MU Health Care vs Anthem Blue Cross Blue Shield — PR War Room Config
// Dispute period: December 2024–July 2025. Contract expired April 1, 2025. Resolved July 15, 2025.

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2024-12-11",
    source: "ABC17 News",
    url: "https://abc17news.com/news/columbia/2024/12/11/mu-health-care-and-anthem-working-on-new-agreement/",
    sourceType: "tv",
    channel: "media",
    headline: "MU Health Care and Anthem working on new agreement ahead of March 31 contract expiration",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "First major coverage of upcoming contract deadline. MU Health began notifying patients of negotiations. Anthem expressed concern about MU Health's proposed 39% increase over three years. Sets stage for public dispute.",
  },
  {
    id: 2,
    date: "2025-02-11",
    source: "KBIA",
    url: "https://www.kbia.org/kbia-news/2025-02-11/mu-health-ends-in-network-coverage-for-anthem-medicare-advantage",
    sourceType: "radio",
    channel: "media",
    headline: "MU Health ends in-network coverage for Anthem Medicare Advantage",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "KBIA (NPR affiliate) reports Anthem stopped negotiating on Medicare Advantage contract. About 6,800 patients with MA plans affected effective April 1. First major escalation.",
  },
  {
    id: 3,
    date: "2025-02-11",
    source: "ABC17 News",
    url: "https://abc17news.com/news/columbia/2025/02/11/anthem-medicare-advantage-plans-no-longer-in-network-at-mu-health-care-starting-april-1/",
    sourceType: "tv",
    channel: "media",
    headline: "Anthem Medicare Advantage plans no longer in-network at MU Health Care starting April 1",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Local TV coverage of Medicare Advantage termination. Notes broader commercial contract also at risk with March 31 deadline.",
  },
  {
    id: 4,
    date: "2025-02-12",
    source: "Jefferson City News-Tribune",
    url: "https://www.newstribune.com/news/2025/feb/12/mu-health-care-drops-anthem-medicare-advantage/",
    sourceType: "news",
    channel: "media",
    headline: "MU Health Care drops Anthem Blue Cross Blue Shield Medicare Advantage plans",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Regional newspaper coverage. 'Drops' framing slightly favors MU narrative that Anthem forced the issue by refusing to negotiate.",
  },
  {
    id: 5,
    date: "2025-03-26",
    source: "KBIA",
    url: "https://www.kbia.org/kbia-news/2025-03-26/mu-health-and-united-extend-deal-as-anthem-contract-nears-expiration",
    sourceType: "radio",
    channel: "media",
    headline: "MU Health and United extend deal as Anthem contract nears expiration",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "IMPORTANT CONTRAST: MU Health reached a deal with UnitedHealthcare while Anthem talks stalled. Positions Anthem as the outlier refusing fair terms. MU can point to UHC deal as proof their rates are reasonable.",
  },
  {
    id: 6,
    date: "2025-03-31",
    source: "KOMU",
    url: "https://www.komu.com/news/midmissourinews/mu-health-care-will-likely-go-out-of-network-with-anthem-as-negotiation-deadline-looms/article_f7ab071c-7725-4d18-8837-ee4a11b46985.html",
    sourceType: "tv",
    channel: "media",
    headline: "MU Health Care will likely go out of network with Anthem as negotiation deadline looms",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "KOMU (NBC affiliate, University of Missouri owned) deadline-day coverage. 90,000 patients face out-of-network status. Maximum urgency framing.",
  },
  {
    id: 7,
    date: "2025-03-31",
    source: "ABC17 News",
    url: "https://abc17news.com/news/missouri/2025/03/31/anthem-mu-health-care-fail-to-reach-deal-mu-health-will-be-out-of-network-for-anthem-customers-on-tuesday/",
    sourceType: "tv",
    channel: "media",
    headline: "Anthem, MU Health Care fail to reach deal; MU Health will be out-of-network for Anthem customers on Tuesday",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Local TV confirms contract expiration. 1,200+ providers, 80 clinics, 7 hospitals go out-of-network for Anthem members.",
  },
  {
    id: 8,
    date: "2025-03-31",
    source: "KY3",
    url: "https://www.ky3.com/2025/03/31/anthem-blue-cross-blue-shield-ends-services-with-mu-health/",
    sourceType: "tv",
    channel: "media",
    headline: "Anthem Blue Cross and Blue Shield ends services with MU Health",
    frameAdoption: "anthem",
    sentiment: "negative_mu",
    patientStory: false,
    blameDirection: "mu",
    reachEstimate: "medium",
    notes: "Springfield station coverage. 'Ends services' framing is slightly misleading — Anthem stopped negotiating, but headline implies MU left. Reaches southwest Missouri market.",
  },
  {
    id: 9,
    date: "2025-03-31",
    source: "Fulton Sun / California Democrat",
    url: "https://www.californiademocrat.com/news/2025/mar/31/mu-health-care-anthem-negotiations-break-down/",
    sourceType: "news",
    channel: "media",
    headline: "Negotiations collapse as Anthem Blue Cross Blue Shield ends talks with MU Health Care",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "low",
    notes: "Rural mid-Missouri newspaper. 'Anthem ends talks' framing places blame on insurer. Important for rural audience — MU Health is often the only major provider.",
  },
  {
    id: 10,
    date: "2025-04-01",
    source: "Becker's Hospital Review",
    url: "https://www.beckershospitalreview.com/finance/mu-health-care-anthem-bcbs-split/",
    sourceType: "news",
    channel: "media",
    headline: "MU Health Care, Anthem BCBS split",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National trade press. Factual reporting for hospital executive audience. Notes the 39% rate increase request and Anthem's 1-2% counter. Positions this as a national trend.",
  },
  {
    id: 11,
    date: "2025-04-02",
    source: "Jefferson City News-Tribune",
    url: "https://www.newstribune.com/news/2025/apr/02/patients-seek-answers-after-anthem-mu-health/",
    sourceType: "news",
    channel: "media",
    headline: "Patients seek answers after Anthem, MU Health talks fail",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Patient-focused reporting in state capital newspaper. Jefferson City is 30 minutes from Columbia — many state workers use MU Health. Patient confusion and anxiety prominent.",
  },
  {
    id: 12,
    date: "2025-04-01",
    source: "The Maneater (MU student newspaper)",
    url: "https://themaneater.com/129564/news/mu-students-lose-healthcare-insurance-as-anthem-contract-ends/",
    sourceType: "news",
    channel: "media",
    headline: "MU students lose healthcare insurance as Anthem contract ends",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "low",
    notes: "University student paper. One MU senior said she has foregone healthcare since the split — vaccination that would have been free now costs $700 out-of-network. Students are a sympathetic, vocal demographic.",
  },
  {
    id: 13,
    date: "2025-04-01",
    source: "Columbia Missourian",
    url: "https://www.columbiamissourian.com/news/state_news/mu-health-care-drops-anthem-blue-cross-blue-shield-medicare-advantage-plan-for-in-network/article_bb8790a4-e894-11ef-b77a-836e0517b0cd.html",
    sourceType: "news",
    channel: "media",
    headline: "MU Health Care drops Anthem Blue Cross Blue Shield Medicare Advantage plan for in-network services, negotiations ongoing",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "University of Missouri journalism school paper. Respected local publication. Detailed factual reporting on contract breakdown.",
  },
  {
    id: 14,
    date: "2025-04-07",
    source: "KBIA / Missouri News Network",
    url: "https://www.krps.org/missouri-news/2025-04-07/thousands-of-missouri-construction-workers-with-anthem-health-insurance-left-scrambling",
    sourceType: "radio",
    channel: "media",
    headline: "Thousands of Missouri construction workers with Anthem health insurance left scrambling",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "NPR statewide. Over 15,000 unionized construction workers and families relied on MU Health through Anthem. Workers 'left scrambling' framing is strongly sympathetic. Syndicated across Missouri NPR stations.",
  },
  {
    id: 15,
    date: "2025-04-09",
    source: "ABC17 News",
    url: "https://abc17news.com/news/2025/04/09/mu-health-care-disputes-anthems-rate-increase-claims-as-negotiations-continue/",
    sourceType: "tv",
    channel: "media",
    headline: "MU Health Care disputes Anthem's rate-increase claims as negotiations continue",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "MU Health pushes back on '39% increase' framing. Says actual request was 11-13% annually, not 39% cumulative lump sum. Important framing battle over the numbers.",
  },
  {
    id: 16,
    date: "2025-04-24",
    source: "ABC17 News",
    url: "https://abc17news.com/news/missouri/2025/04/24/mu-health-care-says-it-has-lowered-its-rate-proposal-amid-anthem-contract-dispute/",
    sourceType: "tv",
    channel: "media",
    headline: "MU Health Care says it has lowered its rate proposal amid Anthem contract dispute",
    frameAdoption: "mu",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "MU Health announces it lowered rate request to single-digit annual increases over three years. 'We are not asking for 39%' — direct rebuttal to Anthem framing. Positions MU as willing to compromise while Anthem stays firm.",
  },
  {
    id: 17,
    date: "2025-05-01",
    source: "KOMU",
    url: "https://www.komu.com/news/midmissourinews/one-month-after-fallout-mu-health-care-and-anthem-blue-cross-blue-shield-remain-split/article_f88e8a41-f578-416e-8a14-2347b5b29732.html",
    sourceType: "tv",
    channel: "media",
    headline: "One month after fallout, MU Health Care and Anthem Blue Cross Blue Shield remain split",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "One-month anniversary coverage. Notes no formal negotiations taking place. Patient stories of driving hours for care. Rural access crisis becomes prominent narrative.",
  },
  {
    id: 18,
    date: "2025-05-07",
    source: "Missouri Independent",
    url: "https://missouriindependent.com/2025/05/07/university-of-missouri-health-care-anthem-negotiations-have-far-reaching-impact/",
    sourceType: "news",
    channel: "media",
    headline: "University of Missouri Health Care, Anthem negotiations have far-reaching impact",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "MAJOR INVESTIGATIVE PIECE. Missouri Independent is the state's top political/policy outlet. Impact reaches all 114 Missouri counties. Employers across state facing higher costs. Rural patient driving 3 hours each way for care. School districts warned of rate increases.",
  },
  {
    id: 19,
    date: "2025-05-07",
    source: "Jefferson City News-Tribune",
    url: "https://www.newstribune.com/news/2025/may/08/mu-health-care-anthem-negotiations-have-far/",
    sourceType: "news",
    channel: "media",
    headline: "MU Health Care, Anthem negotiations have far-reaching impact on employee benefits",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Syndicated from Missouri Independent. State capital audience — legislators and state workers read this paper. Employer benefits angle important for policy audience.",
  },
  {
    id: 20,
    date: "2025-06-16",
    source: "ABC17 News",
    url: "https://abc17news.com/news/missouri/2025/06/16/missouri-legislators-schedule-hearing-over-mu-health-care-anthem-contract-dispute/",
    sourceType: "tv",
    channel: "media",
    headline: "Missouri legislators schedule hearing over MU Health Care, Anthem contract dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "TURNING POINT: State Senate announces formal hearing. Senate President Pro Tem Cindy O'Laughlin drives the action. Signals political establishment is losing patience with both sides.",
  },
  {
    id: 21,
    date: "2025-06-17",
    source: "KBIA",
    url: "https://www.kbia.org/missouri-news/2025-06-17/state-senate-committee-sets-hearing-on-failed-mu-health-care-anthem-negotiations",
    sourceType: "radio",
    channel: "media",
    headline: "State Senate committee sets hearing on failed MU Health Care, Anthem negotiations",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "NPR affiliate. Senator Sandy Crawford's Insurance and Banking Committee to hold hearing. Notes 90,000 patients remain unprotected after months.",
  },
  {
    id: 22,
    date: "2025-06-30",
    source: "Missouri Independent",
    url: "https://missouriindependent.com/2025/06/30/mu-health-care-and-anthem-have-never-been-close-to-agreement-they-tell-senate-committee/",
    sourceType: "news",
    channel: "media",
    headline: "MU Health Care and Anthem 'have never been close' to agreement, they tell Senate committee",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CRITICAL COVERAGE. Senate hearing day. MU CEO Ric Ransom: 'The total economic value of every proposal from Anthem has been the same. Anthem never negotiated.' Anthem's Rich Novack offers CPI+1% (3.3%). Sen. Crawford reads patient letters aloud. Deeply impactful journalism.",
  },
  {
    id: 23,
    date: "2025-06-30",
    source: "KRCG (CBS affiliate)",
    url: "https://krcgtv.com/news/local/missouri-senate-committee-holds-hearing-on-failed-mu-health-care-anthem-negotiations",
    sourceType: "tv",
    channel: "media",
    headline: "Missouri Senate Committee holds hearing on failed MU Health Care, Anthem negotiations",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CBS affiliate live hearing coverage. Patient testimonials prominent: open-heart surgery child, autism spectrum child in rural Cairo, cancer survivor with Lynch syndrome. Sen. Crawford: 'Our purpose is to protect the 90,000 people not protected right now.'",
  },
  {
    id: 24,
    date: "2025-06-30",
    source: "ABC17 News",
    url: "https://abc17news.com/news/missouri/2025/06/30/anthem-claims-initial-progress-has-been-made-with-mu-health-care-following-senate-committee-hearing-monday/",
    sourceType: "tv",
    channel: "media",
    headline: "Anthem claims 'initial progress has been made' with MU Health Care following Senate committee hearing",
    frameAdoption: "anthem",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Post-hearing coverage. Anthem's surprise offer at hearing: CPI+1% annual increases. Anthem claims progress after hearing — but MU Health is skeptical. Private meeting in O'Laughlin's office occurred.",
  },
  {
    id: 25,
    date: "2025-07-01",
    source: "Fulton Sun / News-Tribune",
    url: "https://www.fultonsun.com/news/2025/jul/01/anthem-makes-suprise-offer-to-mu-health-care-at/",
    sourceType: "news",
    channel: "media",
    headline: "Anthem makes surprise offer to MU Health Care at Senate hearing",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Details Anthem's live offer at hearing: annual increases 1% over CPI (3.3% for current year). Rich Novack made offer publicly. MU Health skeptical — says Anthem's prior proposals all had same economic value.",
  },
  {
    id: 26,
    date: "2025-07-01",
    source: "KBIA / Columbia Missourian",
    url: "https://www.kbia.org/missouri-news-network/2025-07-01/senate-hearing-ends-in-failed-negotiations-between-anthem-and-mu-health-care",
    sourceType: "radio",
    channel: "media",
    headline: "Senate hearing ends in failed negotiations between Anthem and MU Health Care",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "NPR/university press. Notes hearing ended without agreement. Both sides met privately but no deal. O'Laughlin vows to continue pushing.",
  },
  {
    id: 27,
    date: "2025-07-08",
    source: "ABC17 News",
    url: "https://abc17news.com/news/top-stories/2025/07/08/missouri-senate-leader-demands-anthem-and-mu-health-care-reach-a-deal-this-week/",
    sourceType: "tv",
    channel: "media",
    headline: "Missouri Senate leader demands Anthem and MU Health Care reach a deal this week",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CRITICAL PRESSURE POINT. Senate President Pro Tem O'Laughlin publicly demands deal by end of week. Social media post: 'This contract needs renewed this week.' Political pressure escalates to maximum.",
  },
  {
    id: 28,
    date: "2025-07-09",
    source: "Missouri Independent",
    url: "https://missouriindependent.com/2025/07/09/mu-health-care-mulls-new-coverage-offer-from-anthem/",
    sourceType: "news",
    channel: "media",
    headline: "MU Health Care mulls new coverage offer from Anthem",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Anthem doubled their rate increase offer after Senate hearing. O'Laughlin notes Anthem will allow policy exceptions and increased physician payments. MU Health reviewing the new terms.",
  },
  {
    id: 29,
    date: "2025-07-14",
    source: "KBIA",
    url: "https://www.kbia.org/missouri-news/2025-07-14/senate-leader-alludes-to-deal-between-mu-health-care-anthem-details-next-week",
    sourceType: "radio",
    channel: "media",
    headline: "Senate leader alludes to deal between MU Health Care, Anthem: 'Details next week'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "O'Laughlin signals deal is imminent. 'Details next week' hints at resolution. Weeks of Senate pressure appear to have worked.",
  },
  {
    id: 30,
    date: "2025-07-15",
    source: "ABC17 News",
    url: "https://abc17news.com/news/columbia/2025/07/15/anthem-mu-health-care-reach-deal-to-bring-patients-back-into-network/",
    sourceType: "tv",
    channel: "media",
    headline: "Anthem, MU Health Care reach deal to bring patients back into network",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "RESOLUTION. Deal announced. Retroactive to April 1. Covers commercial and ACA marketplace plans. Does NOT include Medicare Advantage. About 90,000 patients restored.",
  },
  {
    id: 31,
    date: "2025-07-15",
    source: "Missourinet",
    url: "https://www.missourinet.com/2025/07/15/after-months-of-failed-negotiations-mu-health-care-and-anthem-bcbs-have-a-deal/",
    sourceType: "radio",
    channel: "media",
    headline: "After months of failed negotiations, MU Health Care and Anthem BCBS have a deal",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Statewide radio network coverage. Notes deal retroactive to April 1. Claims will be reprocessed as in-network. Patients eligible for reimbursement of out-of-pocket costs.",
  },
  {
    id: 32,
    date: "2025-07-15",
    source: "Missouri Independent",
    url: "https://missouriindependent.com/briefs/anthem-university-of-missouri-reach-agreement-on-health-care-coverage/",
    sourceType: "news",
    channel: "media",
    headline: "Anthem, University of Missouri reach agreement on health care coverage",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Key policy outlet confirms deal. Notes retroactive to April 1. Dr. Stevan Whitt: 'We understand this process created stress and concern for many.' Two weeks after Senate hearing where they said they'd 'never been close.'",
  },
  {
    id: 33,
    date: "2025-07-16",
    source: "Missourinet",
    url: "https://www.missourinet.com/2025/07/16/olaughlin-discusses-her-relentless-work-to-end-mu-health-vs-anthem-bcbs-dispute/",
    sourceType: "radio",
    channel: "media",
    headline: "O'Laughlin discusses her 'relentless' work to end MU Health vs. Anthem BCBS dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "O'Laughlin takes credit: 'Sometimes you win if you are relentless.' When asked about threatening university funding: 'Not in that many words, but of course they understand that.' Governor Kehoe also pressured both sides.",
  },
  {
    id: 34,
    date: "2025-07-15",
    source: "KOMU",
    url: "https://www.komu.com/news/midmissourinews/anthem-and-mu-health-care-reach-deal-months-after-commercial-contracts-expire/article_e1b88349-ca86-44c6-83d5-7037cbef40e3.html",
    sourceType: "tv",
    channel: "media",
    headline: "Anthem and MU Health Care reach deal months after commercial contracts expire",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "NBC affiliate resolution coverage. 'Months after' framing emphasizes the prolonged disruption. Notes Medicare Advantage plans remain excluded from the deal.",
  },
  {
    id: 35,
    date: "2025-07-15",
    source: "The Missouri Times",
    url: "https://themissouritimes.com/behind-the-scenes-of-the-anthem-mu-deal/",
    sourceType: "news",
    channel: "media",
    headline: "Behind the Scenes of the Anthem/MU Deal",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Political insider coverage. Governor Kehoe said if no agreement by Friday, 'both sides were to be in his office.' Anthem doubled their rate increase offer. O'Laughlin's office became the negotiation venue. Senate pressure was the decisive factor.",
  },
  // === MU HEALTH OWNED MEDIA ===
  {
    id: 36,
    date: "2024-12-11",
    source: "muhealth.org — Press Release",
    url: "https://www.muhealth.org/for-media/press-releases/mu-health-care-working-anthem-new-agreement",
    sourceType: "owned",
    channel: "media",
    headline: "MU Health Care Working with Anthem on New Agreement — patient notification begins",
    frameAdoption: "mu",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "First public notification. MU Health frames itself as 'working in good faith.' Sets patient-centric tone early. Establishes MU Health as the communicator — Anthem is reactive.",
  },
  {
    id: 37,
    date: "2025-04-01",
    source: "muhealth.org — Press Release",
    url: "https://www.muhealth.org/for-media/press-releases/anthem-removes-access-mu-health-care-thousands-patients",
    sourceType: "owned",
    channel: "media",
    headline: "Anthem Removes Access to MU Health Care for Thousands of Patients",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "CRITICAL FRAMING. Headline says 'Anthem Removes Access' — places blame squarely on insurer. Notes Anthem notified MU on March 31 that it 'no longer wishes to negotiate.' Established dedicated call center (573-650-5409). Syndicated to KXEO and NewsBreak.",
  },
  {
    id: 38,
    date: "2025-04-01",
    source: "muhealth.org — Anthem FAQ Page",
    url: "https://www.muhealth.org/anthem/faq",
    sourceType: "owned",
    channel: "media",
    headline: "MU Health Care creates dedicated Anthem dispute FAQ page for patients",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Patient-facing resource page. Continuity of care information. Directs patients to call center. Part of organized communication strategy that positioned MU Health as the advocate and Anthem as the problem.",
  },
  {
    id: 39,
    date: "2025-06-30",
    source: "muhealth.org — Press Release",
    url: "https://www.muhealth.org/for-media/press-releases/mu-health-care-advocates-patients-missouri-state-senate-hearing",
    sourceType: "owned",
    channel: "media",
    headline: "MU Health Care Advocates for Patients in Missouri State Senate Hearing",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "'Advocates for Patients' framing positions MU as patient champion. CEO Ransom: Anthem rates are 10-20% lower than what other insurers pay MU Health. 7% annual operating cost increases vs Anthem's 1-2% offers.",
  },
  {
    id: 40,
    date: "2025-07-15",
    source: "muhealth.org — Press Release",
    url: "https://www.muhealth.org/for-media/press-releases/anthem-and-mu-health-care-announce-new-agreement",
    sourceType: "owned",
    channel: "media",
    headline: "Anthem Blue Cross and Blue Shield and MU Health Care Announce New Agreement",
    frameAdoption: "mu",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution press release. Dr. Stevan Whitt (CMO): 'Throughout this negotiation, our patients have been our top priority.' 'Deeply grateful for the patience and trust.' Victory framing — MU held firm and got better terms.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 41,
    date: "2025-04-01",
    source: "Social media (patient anxiety)",
    sourceType: "social",
    channel: "social",
    headline: "Anthem patients flood social media with confusion and anger as MU Health goes out-of-network",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Day-one social media reaction. Patients discovering they need new doctors, new hospitals. Rural patients particularly vocal about lack of alternatives. Facebook community groups in central Missouri become support forums.",
  },
  {
    id: 42,
    date: "2025-04-26",
    source: "Social media (town hall reaction)",
    sourceType: "social",
    channel: "social",
    headline: "LiUNA Local 955 town hall generates social media coverage — Anthem not present",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Union-organized town hall at American Legion Post 202 in Columbia. MU Health had representatives; Anthem did not attend. Anthem's absence was widely criticized. Nick McSwain (union steward): 'This insurance corporation's actions are morally repugnant.'",
  },
  {
    id: 43,
    date: "2025-05-15",
    source: "Social media (rural patient stories)",
    sourceType: "social",
    channel: "social",
    headline: "Rural Missouri patients share stories of driving 3+ hours for care after losing MU Health access",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Organic sharing on Facebook and local news comment sections. Cairo, MO mother: nearest in-network hospital is 3 hours away vs 45-minute drive to MU Health. 'A different ball game.' Rural network adequacy crisis becomes central narrative.",
  },
  {
    id: 44,
    date: "2025-06-30",
    source: "Social media (Senate hearing reaction)",
    sourceType: "social",
    channel: "social",
    headline: "Senate hearing clips go viral — patient testimonials dominate social media conversation",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Senate hearing generated significant social media engagement. Patient stories read by Sen. Crawford were shared widely. Open-heart surgery child, autism spectrum child, cancer survivor with Lynch syndrome — all maximally sympathetic.",
  },
  {
    id: 45,
    date: "2025-07-08",
    source: "Sen. Cindy O'Laughlin (social media)",
    sourceType: "social",
    channel: "social",
    headline: "O'Laughlin posts on social media: 'This contract needs renewed this week'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Senate President Pro Tem uses social media to publicly pressure both sides. 'I have contacted a few other senators to get their input, and they agree; sign the contract.' Unusual direct political pressure via social media.",
  },
  {
    id: 46,
    date: "2025-04-26",
    source: "ABC17 News / Social",
    url: "https://abc17news.com/news/local-news/2025/04/26/locals-voice-frustrations-over-anthem-and-mu-health-care-negotiations-during-saturday-town-hall/",
    sourceType: "tv",
    channel: "social",
    headline: "Locals voice frustrations over Anthem and MU Health Care negotiations during Saturday town hall",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "TV coverage of union-organized town hall. City of Columbia workers, construction laborers, veterans all affected. Anthem's absence noted. Online petition launched telling Anthem Missouri President Stephanie Vojicic to 'stop playing games with our lives.'",
  },
  {
    id: 47,
    date: "2025-04-01",
    source: "LiUNA Local 955 (online petition)",
    sourceType: "social",
    channel: "social",
    headline: "Local 955 launches online petition: 'Tell Anthem to stop playing games with our lives and settle with MU Healthcare'",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Organized labor petition targeting Anthem Missouri President Stephanie Vojicic by name. Union mobilization adds organized political pressure beyond individual patient complaints.",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 48,
    date: "2025-04-01",
    source: "Missouri Dept. of Commerce and Insurance (DCI)",
    url: "https://dci.mo.gov/node/1506",
    sourceType: "news",
    channel: "stakeholder",
    headline: "DCI publishes consumer FAQ: 'What consumers need to know about the MU Healthcare and Anthem impasse'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "State regulator acknowledges dispute. Director Angela Nelson later testified DCI has 'no real authority' over many commercial insurance products. Reveals regulatory gap — Missourians have little recourse when coverage fails.",
  },
  {
    id: 49,
    date: "2025-04-07",
    source: "LiUNA Local 955 (union statement)",
    url: "https://labortribune.com/laborers-local-955-condemns-anthem-for-health-insurance-coverage-loss-with-mu-health-care/",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Laborers Local 955 condemns Anthem for health insurance coverage loss with MU Health Care",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "UNION INTERVENTION. Published in The Labor Tribune. Nick McSwain: 'Anthem's denial of claims and refusal to pay bills on time hurts our union siblings at MU Health Care's fight for fair wages.' 15,000+ construction workers and families affected. Organized labor fully aligned with MU Health.",
  },
  {
    id: 50,
    date: "2025-04-07",
    source: "InsuranceNewsNet (national trade)",
    url: "https://insurancenewsnet.com/oarticle/thousands-of-missouri-construction-workers-with-anthem-health-insurance-left-scrambling",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Thousands of Missouri construction workers with Anthem health insurance left scrambling",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "National insurance trade press picks up the story. Anthem's reputation with insurance industry audience takes a hit. 'Left scrambling' framing is strongly anti-Anthem.",
  },
  {
    id: 51,
    date: "2025-06-13",
    source: "Sen. Cindy O'Laughlin (R-Shelbina)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Missouri Senate President Pro Tem announces formal hearing on MU Health/Anthem dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "POLITICAL ESCALATION. Senate President Pro Tem — the most powerful state senator — calls for formal hearing. Signals this is no longer just a business dispute but a political crisis. Crawford's Insurance and Banking Committee to hold hearing June 30.",
  },
  {
    id: 52,
    date: "2025-06-30",
    source: "Sen. Sandy Crawford (R-Buffalo), Chair, Insurance and Banking Committee",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Sen. Crawford reads patient letters aloud at hearing: 'Our purpose is to protect the 90,000 people not protected right now'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Hearing chair personalizes the crisis by reading constituent letters. Open-heart surgery family, autism spectrum child (Stephanie Timmerman from Cairo), cancer survivor Sandy Smith with Lynch syndrome. Puts human faces on 90,000 number.",
  },
  {
    id: 53,
    date: "2025-06-30",
    source: "MU Health CEO Ric Ransom (Senate testimony)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "MU CEO Ransom: 'Anthem never negotiated' — total economic value of every Anthem proposal was the same",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "KEY TESTIMONY. Ransom: Anthem rates 10-20% lower than other insurers. 7% annual operating cost increases. MU offered compromise; Anthem offered 1% for physicians, 2% for hospitals. 'In the most literal ways, Anthem never negotiated.'",
  },
  {
    id: 54,
    date: "2025-06-30",
    source: "Rich Novack, Elevance Health (Anthem parent) — Senate testimony",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Anthem's Novack offers CPI+1% at hearing: 'We believe we have countered multiple times'",
    frameAdoption: "anthem",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "mu",
    reachEstimate: "high",
    notes: "Anthem's primary public defense. Novack admits continuity of care process was 'clunky' and 'we have not done as well as we should have.' CPI+1% (3.3%) offer made live at hearing. Defensive posture on process failures.",
  },
  {
    id: 55,
    date: "2025-06-30",
    source: "Director Angela Nelson, Missouri DCI (Senate testimony)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Missouri DCI Director: agency has 'no real authority' over many commercial insurance products",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "REGULATORY GAP EXPOSED. Missouri's insurance regulator says it cannot protect consumers in disputes like this. Reveals systemic vulnerability for patients — no regulatory safety net when insurer-provider negotiations fail.",
  },
  {
    id: 56,
    date: "2025-06-30",
    source: "Stephanie Timmerman, rural mother (Senate testimony)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Mother from Cairo, MO: 'The number of tears I've shed worrying about his out-of-network care has been extremely stressful'",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "MOST IMPACTFUL PATIENT STORY. Son Colton has autism spectrum disorder, receives specialized care at MU Health. Nearest in-network alternative is 3 hours away vs 45-minute drive. 'This level of coordinated specialized pediatric care is not replaceable in rural Missouri.'",
  },
  {
    id: 57,
    date: "2025-06-30",
    source: "Sandy Smith, cancer survivor (Senate testimony)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Cancer survivor with Lynch syndrome: 'I can't just go to anybody that's not familiar with that condition'",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Cancer patient reliant on MU Health since 2016. Lynch syndrome increases susceptibility to multiple cancers. Cannot switch to generic provider. Specialized care argument mirrors MSK/UHC dynamics.",
  },
  {
    id: 58,
    date: "2025-06-30",
    source: "Open-heart surgery family (Senate testimony)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Family whose daughter had open-heart surgery at MU as a newborn fears losing access for future surgeries",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Daughter had open-heart surgery as newborn, again at age 2, now 4 — may need future surgeries. Family forced to seek care elsewhere with Anthem coverage no longer accepted. Pediatric cardiac care is irreplaceable.",
  },
  {
    id: 59,
    date: "2025-07-08",
    source: "Gov. Mike Kehoe (private pressure)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Governor Kehoe threatens to summon both sides to his office if no deal by Friday",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "EXECUTIVE INTERVENTION. Behind-the-scenes pressure. Kehoe said if no agreement by Friday, both sides would be called to the Governor's office. Combined with O'Laughlin's Senate pressure, creates unified political front. Kehoe later praised for helping resolve dispute.",
  },
  {
    id: 60,
    date: "2025-05-07",
    source: "Missouri school districts (employer impact)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "School districts warned dispute will drive up insurance rates for employees statewide",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Missouri Independent reporting. Dispute's ripple effects reach school districts across the state. Any individual receiving care through MU Health system will see higher costs. Employer impact extends far beyond Boone County.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 61,
    date: "2025-04-01",
    source: "MCHCP (Missouri Consolidated Health Care Plan)",
    url: "https://www.mchcp.org/MUNotice.asp",
    sourceType: "owned",
    channel: "employer",
    headline: "MCHCP posts notice for state employees: MU Health Care out of Anthem network",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CRITICAL EMPLOYER CHANNEL. MCHCP manages health benefits for Missouri state employees. One year into a 5-year renewable contract with Anthem. State workers in mid-Missouri heavily rely on MU Health. Creates direct employer pressure on Anthem.",
  },
  {
    id: 62,
    date: "2025-04-01",
    source: "City of Columbia (employer impact)",
    sourceType: "news",
    channel: "employer",
    headline: "City of Columbia workers with Anthem insurance lose in-network access to MU Health",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Municipal employer directly impacted. City of Columbia workers are LiUNA Local 955 members. Municipal government employees losing access to the city's major health system creates local political pressure on Anthem.",
  },
  {
    id: 63,
    date: "2025-04-07",
    source: "Construction employer trusts (multi-employer plans)",
    sourceType: "news",
    channel: "employer",
    headline: "Over 15,000 construction workers and families lose MU Health access through Anthem employer trusts",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Multi-employer trust plans for construction unions are a major Anthem employer segment. 15,000+ workers and families affected. These are workers building Missouri infrastructure — sympathetic blue-collar demographic.",
  },
  {
    id: 64,
    date: "2025-05-07",
    source: "Columbia Missourian (employer benefits reporting)",
    url: "https://www.columbiamissourian.com/news/higher_education/mu-health-care-anthem-negotiations-have-far-reaching-impact-on-employee-benefits/article_4efaaee7-2497-4c19-bbcb-51915802d83e.html",
    sourceType: "news",
    channel: "employer",
    headline: "MU Health Care, Anthem negotiations have far-reaching impact on employee benefits",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "University press. Higher education benefits angle. MU employees themselves affected — the university's own workforce is caught in its health system's dispute with Anthem. Reaches all 114 Missouri counties.",
  },
  {
    id: 65,
    date: "2025-07-15",
    source: "TIG Advisors (benefits consultant)",
    url: "https://tigadvisors.com/anthem-mu-update/",
    sourceType: "news",
    channel: "employer",
    headline: "TIG Advisors: Anthem/MU Update — client advisory on resolution",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Benefits consulting firm client advisory. Notes retroactive claims reprocessing. Members eligible for reimbursement of out-of-pocket costs from April 1 through July 31. Employer relief framing.",
  },
  {
    id: 66,
    date: "2025-07-15",
    source: "The Missouri Times (MCHCP press release)",
    url: "https://themissouritimes.com/press-release-mu-health-and-anthem-reach-agreement-restore-network-access-for-mchcp-members/",
    sourceType: "news",
    channel: "employer",
    headline: "MU Health and Anthem reach agreement, restore network access for MCHCP members",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "State employee plan restoration. MCHCP confirms agreement effective retroactive to April 1. Eligible claims will be reprocessed as in-network. State workers — a politically influential group — can return to MU Health.",
  },
  {
    id: 67,
    date: "2025-02-12",
    source: "Springfield Business Journal",
    url: "https://sbj.net/stories/mu-health-care-to-drop-anthem-medicare-advantage-plans,98520",
    sourceType: "news",
    channel: "employer",
    headline: "MU Health Care to drop Anthem Medicare Advantage plans",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Southwest Missouri business press. Medicare Advantage termination reaches employer audience outside central Missouri. Notes potential broader commercial contract impact.",
  },
  {
    id: 68,
    date: "2025-02-11",
    source: "Trinity Assurance Group (insurance broker)",
    url: "https://www.trinityassurance.com/our-blog/mu-healthcare-leaves-anthem-medicare-advantage-network",
    sourceType: "news",
    channel: "employer",
    headline: "MU Healthcare Leaves Anthem Medicare Advantage Network — broker advisory",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Insurance broker client communication. Early advisory to employer clients about Medicare Advantage changes. Signals broker community tracking the dispute closely.",
  },
  // === ADDITIONAL MEDIA ===
  {
    id: 69,
    date: "2025-04-01",
    source: "KXEO (AM radio, mid-Missouri)",
    url: "https://kxeo.com/2025/04/01/anthem-removes-access-to-mu-health-care-for-thousands-of-patients/",
    sourceType: "radio",
    channel: "media",
    headline: "Anthem Removes Access To MU Health Care For Thousands Of Patients",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "low",
    notes: "Local AM radio station syndicating MU Health press release. Reaches rural mid-Missouri audience. MU Health's framing ('Anthem removes access') adopted wholesale.",
  },
  {
    id: 70,
    date: "2025-06-30",
    source: "KRCG (CBS affiliate)",
    url: "https://krcgtv.com/features/focus-on-your-health/mu-health-care-and-anthem-dispute-threatens-coverage-for-about-90000-patients-in-missouri",
    sourceType: "tv",
    channel: "media",
    headline: "MU Health Care and Anthem dispute threatens coverage for about 90,000 patients in Missouri",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Extended feature piece. 'Focus on Your Health' segment format gives extended airtime. 90,000 figure prominently featured. Patient impact stories anchor the coverage.",
  },
  {
    id: 71,
    date: "2025-06-30",
    source: "KRCG (CBS affiliate)",
    url: "https://krcgtv.com/news/local/residents-voice-concerns-ahead-of-hearing-on-failed-mu-health-care-anthem-negotiations",
    sourceType: "tv",
    channel: "media",
    headline: "Residents voice concerns ahead of hearing on failed MU Health Care, Anthem negotiations",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Pre-hearing resident interviews. Tyson Smith: 'I hear about it all the time from people — good people, who deserve quality healthcare.' Patient frustration prominent.",
  },
  {
    id: 72,
    date: "2025-07-08",
    source: "KRCG (CBS affiliate)",
    url: "https://krcgtv.com/news/local/leaders-urge-quick-resolution-to-anthem-mu-contract-dispute-affecting-90000-patients",
    sourceType: "tv",
    channel: "media",
    headline: "Leaders urge quick resolution to Anthem-MU contract dispute affecting 90,000 patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Political leaders publicly demanding resolution. Coverage of O'Laughlin's deadline demand. 'Leaders urge' framing positions the dispute as a failure by both parties.",
  },
  {
    id: 73,
    date: "2025-04-03",
    source: "Missourinet",
    url: "https://www.missourinet.com/2025/04/03/as-mu-healthcare-and-anthem-take-a-break-heres-what-customers-need-to-know/",
    sourceType: "radio",
    channel: "media",
    headline: "As MU Healthcare and Anthem take a break, here's what customers need to know",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Statewide radio network consumer guide. Practical information for patients navigating out-of-network status. 'Take a break' framing underplays the severity for affected patients.",
  },
  {
    id: 74,
    date: "2025-04-01",
    source: "KRCG (CBS affiliate)",
    url: "https://krcgtv.com/news/local/residents-apply-for-continuity-of-care-following-mu-health-care-anthem-impasse",
    sourceType: "tv",
    channel: "media",
    headline: "Residents apply for continuity of care following MU Health Care, Anthem impasse",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Continuity of care process reporting. Patient: took 24 days for Anthem to approve, never informed of status. MU Health called process 'difficult and confusing.' Process failures become a recurring narrative damaging Anthem.",
  },
  {
    id: 75,
    date: "2025-03-31",
    source: "Columbia Missourian",
    url: "https://www.columbiamissourian.com/news/local/thousands-face-coverage-loss-if-mu-health-care-anthem-don-t-reach-agreement-by-tuesday/article_1cea636c-d893-491c-bc40-d00c941c59e0.html",
    sourceType: "news",
    channel: "media",
    headline: "Thousands face coverage loss if MU Health Care, Anthem don't reach agreement by Tuesday",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Deadline-eve coverage. Columbia Missourian is the city's university-run daily. Reaches Columbia's educated, politically engaged population directly.",
  },
  {
    id: 76,
    date: "2025-05-07",
    source: "The Missouri Times",
    url: "https://themissouritimes.com/anthem-mu-health-care-dispute-could-leave-many-without-coverage/",
    sourceType: "news",
    channel: "media",
    headline: "Anthem-MU Health Care dispute could leave many without coverage",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "State political press. Key readership: legislators, lobbyists, political operatives. Positions dispute as a statewide political issue, not just a local healthcare matter.",
  },
  {
    id: 77,
    date: "2025-06-30",
    source: "The Missouri Times",
    url: "https://themissouritimes.com/missourians-left-behind-in-mu-anthem-dispute/",
    sourceType: "news",
    channel: "media",
    headline: "Missourians Left Behind in MU-Anthem Dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "'Left Behind' framing creates sympathy for patients. Detailed patient stories including rural access challenges. Missouri Times reaches political establishment audience.",
  },
  {
    id: 78,
    date: "2025-07-15",
    source: "KOMU (investigative)",
    url: "https://www.komu.com/news/acloserlook/anatomy-of-a-fallout-between-mu-health-care-and-anthem-blue-cross-blue-shield/article_68bb08fb-77f9-4960-adfe-8341387195e7.html",
    sourceType: "tv",
    channel: "media",
    headline: "Anatomy of a fallout between MU Health Care and Anthem Blue Cross Blue Shield",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "KOMU deep-dive investigative piece. 'A Closer Look' series. Full timeline from July 2024 initial proposal through resolution. Notes MU Health initially wanted 11-13% annually (39% cumulative over 3 years), later lowered to single digits. Anthem offered 1% physicians, 2% hospitals.",
  },
  {
    id: 79,
    date: "2025-06-30",
    source: "Columbia Missourian",
    url: "https://www.columbiamissourian.com/news/state_news/senate-hearing-ends-in-failed-negotiations-between-anthem-and-mu-health-care/article_355b6021-271a-40e5-9c27-b6b4f2fe0e59.html",
    sourceType: "news",
    channel: "media",
    headline: "Senate hearing ends in failed negotiations between Anthem and MU Health Care",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "University press. Detailed hearing coverage. Notes Anthem's surprise CPI+1% offer and MU Health's skepticism. Private meeting in O'Laughlin's office after public hearing.",
  },
  {
    id: 80,
    date: "2025-07-15",
    source: "Columbia Missourian",
    url: "https://www.columbiamissourian.com/news/local/mu-health-care-and-anthem-reach-a-deal-to-restore-coverage/article_7058c90a-c011-43e3-8a26-80f2b2b37ab9.html",
    sourceType: "news",
    channel: "media",
    headline: "MU Health and Anthem reach deal to restore coverage",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution coverage. Notes deal retroactive to April 1 but excludes Medicare Advantage plans. Approximately 6,800 MA patients remain out-of-network. Incomplete resolution.",
  },
  {
    id: 81,
    date: "2025-03-26",
    source: "KRCG (CBS affiliate)",
    url: "https://krcgtv.com/news/local/mu-health-care-reaches-deal-with-unitedhealthcare-while-negotiations-continue-with-anthem",
    sourceType: "tv",
    channel: "media",
    headline: "MU Health Care reaches deal with UnitedHealthcare while negotiations continue with Anthem",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "CRITICAL COMPARISON. MU Health extended its deal with UHC while Anthem talks stalled. Directly undermines Anthem's claim that MU rates are unreasonable — if UHC agrees, why can't Anthem?",
  },
  {
    id: 82,
    date: "2025-04-01",
    source: "93.9 The Eagle (Columbia radio)",
    url: "https://939theeagle.com/update-talks-between-anthem-and-mu-health-care-have-stalled/",
    sourceType: "radio",
    channel: "media",
    headline: "UPDATE: Talks between Anthem and MU Health Care have stalled",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Popular Columbia radio station. Reaches broad mid-Missouri audience including demographics that may not follow newspaper/TV coverage. Regular updates throughout dispute.",
  },
  {
    id: 83,
    date: "2025-07-15",
    source: "93.9 The Eagle",
    url: "https://939theeagle.com/mu-health-anthem-reach-agreement/",
    sourceType: "radio",
    channel: "media",
    headline: "MU Health, Anthem reach agreement",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution announcement. Brief, factual coverage for Columbia radio audience.",
  },
  {
    id: 84,
    date: "2025-07-15",
    source: "Fulton Sun / California Democrat",
    url: "https://www.californiademocrat.com/news/2025/jul/16/mu-health-care-anthem-blue-cross-reach-agreement-to-restore-in-network-access-for-members/",
    sourceType: "news",
    channel: "media",
    headline: "MU Health Care, Anthem Blue Cross reach agreement to restore in-network access for members",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Rural mid-Missouri newspapers. Dr. Whitt quote: 'Our patients have been our top priority.' Resolution reaches rural audience that was most affected by the access gap.",
  },
  {
    id: 85,
    date: "2025-04-01",
    source: "KRCG (CBS affiliate)",
    url: "https://krcgtv.com/news/local/mu-health-care-patients-express-concerns-after-being-forced-out-of-network",
    sourceType: "tv",
    channel: "media",
    headline: "MU Health Care patients express concerns after being forced out of network",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "'Forced out of network' framing places blame on external actor (Anthem). Patient voices dominate. Local TV reaches broad demographic in mid-Missouri.",
  },
  {
    id: 86,
    date: "2025-06-30",
    source: "KRCG (CBS affiliate)",
    url: "https://krcgtv.com/news/local/anthem-blue-cross-blue-shield-mu-health-care-dispute-to-be-topic-of-senate-hearing-contract-insurance-and-banking-committee-tonya-johnson-senator-cindy-olaughlin-sandy-crawford-randolph-audrain-boone-cole-callaway-howard-cooper-county",
    sourceType: "tv",
    channel: "media",
    headline: "Anthem Blue Cross Blue Shield, MU Health Care dispute to be topic of Senate hearing",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Pre-hearing coverage. Notes counties directly impacted: Randolph, Audrain, Boone, Cole, Callaway, Howard, Cooper — the heart of mid-Missouri.",
  },
  // === ADDITIONAL SOCIAL ===
  {
    id: 87,
    date: "2025-04-26",
    source: "KOMU (town hall coverage)",
    url: "https://www.komu.com/news/midmissourinews/town-hall-addresses-loss-of-health-care-access-for-thousands-of-mid-missourians/article_76c93be1-75ce-4274-a474-b2055ec66816.html",
    sourceType: "tv",
    channel: "social",
    headline: "Town hall addresses loss of health care access for thousands of mid-Missourians",
    frameAdoption: "mu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "LiUNA/Missouri Jobs with Justice town hall at American Legion Post 202. MU Health sent representatives; Anthem did not. City workers, laborers, veterans attended. Anthem's absence widely noted and criticized.",
  },
  {
    id: 88,
    date: "2025-06-30",
    source: "93.9 The Eagle (O'Laughlin social media post)",
    url: "https://939theeagle.com/update-missouri-senate-committee-schedules-june-30-hearing-on-dispute-between-mu-health-care-and-anthem/",
    sourceType: "radio",
    channel: "social",
    headline: "O'Laughlin posted on social media after hearing that both sides met privately and progress was possible",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Social media used by state's most powerful senator to signal progress. O'Laughlin uses social platforms as a negotiation pressure tool throughout the dispute.",
  },
];

const LABELS = {
  frameAdoption: { mu: "MU Frame", anthem: "Anthem Frame", balanced: "Balanced" },
  sentiment: {
    negative_anthem: "Anti-Anthem",
    negative_mu: "Anti-MU",
    neutral: "Neutral",
    positive_anthem: "Pro-Anthem",
    positive_mu: "Pro-MU",
  },
  blameDirection: { anthem: "Blames Anthem", mu: "Blames MU", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — Statewide authority / national trade (1.5)
  "Missouri Independent": 1.5, "Becker's Hospital Review": 1.5, "InsuranceNewsNet (national trade)": 1.5,
  // Tier 2 — Regional TV / major local (1.2)
  "KOMU": 1.2, "KRCG (CBS affiliate)": 1.2, "ABC17 News": 1.2, "KY3": 1.2,
  "Columbia Missourian": 1.2, "93.9 The Eagle (Columbia radio)": 1.0,
  // Tier 3 — NPR / statewide radio / political press (1.0)
  "KBIA": 1.0, "KBIA / Missouri News Network": 1.0, "KBIA / Columbia Missourian": 1.0,
  "Missourinet": 1.0, "The Missouri Times": 1.0,
  "Jefferson City News-Tribune": 1.0, "Fulton Sun / California Democrat": 1.0,
  "Springfield Business Journal": 1.0, "The Maneater (MU student newspaper)": 0.7,
  "KXEO (AM radio, mid-Missouri)": 0.7, "93.9 The Eagle": 1.0,
  // Tier 4 — Organic social (0.7)
  "Social media (patient anxiety)": 0.7, "Social media (town hall reaction)": 0.7,
  "Social media (rural patient stories)": 0.7, "Social media (Senate hearing reaction)": 0.7,
  "Sen. Cindy O'Laughlin (social media)": 0.7, "ABC17 News / Social": 0.7,
  "93.9 The Eagle (O'Laughlin social media post)": 0.7,
  "LiUNA Local 955 (online petition)": 0.7,
  // Tier 5 — Comment sections (0.4)
  // Tier 6 — Owned/party media (0.3)
  "muhealth.org — Press Release": 0.3, "muhealth.org — Anthem FAQ Page": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "Missouri Dept. of Commerce and Insurance (DCI)": 1.3,
  "LiUNA Local 955 (union statement)": 1.3,
  "Sen. Cindy O'Laughlin (R-Shelbina)": 1.3,
  "Sen. Sandy Crawford (R-Buffalo), Chair, Insurance and Banking Committee": 1.3,
  "MU Health CEO Ric Ransom (Senate testimony)": 1.3,
  "Rich Novack, Elevance Health (Anthem parent) — Senate testimony": 1.3,
  "Director Angela Nelson, Missouri DCI (Senate testimony)": 1.3,
  "Stephanie Timmerman, rural mother (Senate testimony)": 1.3,
  "Sandy Smith, cancer survivor (Senate testimony)": 1.3,
  "Open-heart surgery family (Senate testimony)": 1.3,
  "Gov. Mike Kehoe (private pressure)": 1.3,
  "Missouri school districts (employer impact)": 1.3,
  // Tier 8 — Employer/Benefits (1.5x trade, 1.0x broker)
  "MCHCP (Missouri Consolidated Health Care Plan)": 1.5,
  "City of Columbia (employer impact)": 1.0,
  "Construction employer trusts (multi-employer plans)": 1.0,
  "TIG Advisors (benefits consultant)": 1.0,
  "Trinity Assurance Group (insurance broker)": 1.0,
};

const SEARCH_TRENDS = [
  { week: "2024-12-09", interest: 5 },
  { week: "2024-12-16", interest: 4 },
  { week: "2024-12-23", interest: 3 },
  { week: "2024-12-30", interest: 3 },
  { week: "2025-01-06", interest: 4 },
  { week: "2025-01-13", interest: 4 },
  { week: "2025-01-20", interest: 5 },
  { week: "2025-01-27", interest: 6 },
  { week: "2025-02-03", interest: 12 },
  { week: "2025-02-10", interest: 25 },
  { week: "2025-02-17", interest: 18 },
  { week: "2025-02-24", interest: 15 },
  { week: "2025-03-03", interest: 14 },
  { week: "2025-03-10", interest: 16 },
  { week: "2025-03-17", interest: 22 },
  { week: "2025-03-24", interest: 55 },
  { week: "2025-03-31", interest: 100 },
  { week: "2025-04-07", interest: 72 },
  { week: "2025-04-14", interest: 45 },
  { week: "2025-04-21", interest: 50 },
  { week: "2025-04-28", interest: 38 },
  { week: "2025-05-05", interest: 35 },
  { week: "2025-05-12", interest: 28 },
  { week: "2025-05-19", interest: 22 },
  { week: "2025-05-26", interest: 20 },
  { week: "2025-06-02", interest: 18 },
  { week: "2025-06-09", interest: 22 },
  { week: "2025-06-16", interest: 40 },
  { week: "2025-06-23", interest: 55 },
  { week: "2025-06-30", interest: 90 },
  { week: "2025-07-07", interest: 65 },
  { week: "2025-07-14", interest: 80 },
  { week: "2025-07-21", interest: 30 },
];

export default {
  active: false,
  // Identity
  providerKey: "mu",
  payorKey: "anthem",
  providerName: "MU Health Care",
  payorName: "Anthem Blue Cross Blue Shield",
  providerShort: "MU",
  payorShort: "Anthem",
  navShort: "MU v. Anthem",
  title: "MU Health Care vs Anthem Blue Cross Blue Shield",
  subtitle: "Contract dispute · Resolved July 15, 2025",
  gradientId: "muanthem",

  // Dates
  monitorStart: "December 1, 2024",
  monitorEnd: "July 31, 2025",
  disputePublicDate: "2024-12-11",

  // Colors
  colors: {
    providerColor: "#F1B82D",
    payorColor: "#003DA5",
    neutral: "#64748B",
    accent: "#F1B82D",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#F1B82D", "#7A6E69", "#003DA5"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"MU Health Care Anthem" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.85,
    nationalMedian: 1.0,
    networkComplaints: 1420,
    priorYearComplaints: 980,
    regulatorAction: "Missouri DCI published consumer FAQ but Director Angela Nelson testified the agency has 'no real authority' over many commercial insurance products. No formal enforcement action taken. Senate Insurance and Banking Committee held formal hearing June 30.",
    signalRead: "Missouri's regulatory gap — DCI lacks authority over self-funded and many commercial plans — left 90,000 patients without recourse. The Senate hearing was an extraordinary intervention that substituted political pressure for regulatory enforcement. Anthem's complaint index reflects multi-state provider disputes.",
  },

  // Executive summary
  executiveSummary: {
    statement: "The dispute resulted in 3.5 months of actual out-of-network status (April 1 – July 15) affecting 90,000 patients — far longer than most provider-payor disputes. Resolution required direct intervention by the Missouri Senate President Pro Tem and Governor. The deal was retroactive to April 1, with 3.5% annual increases through 2028.",
    keyMessages: [
      "MU Health's comparison to the UnitedHealthcare deal was its stickiest argument: if UHC accepted MU's rates, Anthem's refusal appeared unreasonable.",
      "Anthem's 'continuity of care' process failures — described as 'clunky' by Anthem's own executive — handed MU Health a potent process narrative on top of the access narrative.",
      "Rural network adequacy was the dominant emotional frame: a mother driving 3 hours for autism care vs 45 minutes to MU Health is impossible for Anthem to counter.",
      "Organized labor (LiUNA Local 955, 15,000+ construction workers) provided political infrastructure that individual patients could not — union-organized town halls, petitions, and public pressure.",
    ],
    marcomm: [
      "<strong>Rural access is the trump card in mid-Missouri.</strong> MU Health serves patients in all 114 Missouri counties. For many rural patients, there is no comparable alternative within reasonable driving distance. Anthem cannot argue 'network adequacy' when the nearest in-network hospital is 3 hours away.",
      "<strong>The UHC comparison destroyed Anthem's 'unreasonable rates' narrative.</strong> MU Health extended its contract with UnitedHealthcare during the same period. If the nation's largest insurer accepts MU's terms, Anthem's claim that MU is overcharging collapses.",
      "<strong>Political pressure substituted for regulatory authority.</strong> Missouri's insurance regulator admitted it lacks enforcement power over most commercial plans. The Senate hearing and Governor's intervention were extraordinary — and highlight how exposed patients are in states with weak insurance regulation.",
      "<strong>Anthem's absence at the town hall was a PR disaster.</strong> When MU Health sent representatives to a union-organized community meeting and Anthem declined, it reinforced the narrative that Anthem doesn't face the communities it disrupts.",
    ],
  },
  channelTakeaways: {
    media: [
      "Missouri Independent's investigative pieces were the highest-impact coverage — reaching the state's political establishment and demonstrating statewide impact across all 114 counties.",
      "Local TV saturation (KOMU, KRCG, ABC17) ensured the dispute was inescapable in mid-Missouri's daily news diet for 3.5 months.",
      "KBIA/NPR statewide syndication ('Thousands of construction workers left scrambling') extended the story beyond central Missouri to a national public radio audience.",
      "MU Health's 'Anthem Removes Access' press release headline was adopted wholesale by multiple outlets — demonstrating effective framing that media ran without modification.",
    ],
    social: [
      "Sen. O'Laughlin's social media posts became negotiation tools — her 'this contract needs renewed this week' post created immediate pressure from the state's most powerful senator.",
      "LiUNA Local 955's online petition targeting Anthem Missouri President Stephanie Vojicic by name personalized corporate accountability.",
      "Rural patient stories shared on Facebook community groups created organic, deeply emotional content that amplified MU Health's position.",
      "Town hall social media coverage amplified Anthem's absence, creating lasting reputational damage in the Columbia community.",
    ],
    stakeholder: [
      "Senate hearing was the decisive turning point — patient testimonials read by Sen. Crawford made the 90,000 number human. Within two weeks, a deal materialized.",
      "Governor Kehoe's private threat to summon both sides to his office created executive-level pressure that complemented Senate action.",
      "LiUNA Local 955 provided organized political infrastructure: town halls, petitions, media coordination that individual patients cannot replicate.",
      "Missouri DCI's admission of 'no real authority' exposed a regulatory gap that may drive future legislative action on insurance oversight.",
    ],
    employer: [
      "MCHCP (state employee plan) was the critical employer pressure point — state workers losing access to the state university's health system is politically untenable.",
      "15,000+ construction workers through multi-employer trust plans demonstrated that Anthem's employer base was being directly harmed by the dispute.",
      "School districts warned of cascading rate increases, extending employer anxiety far beyond Anthem's direct customer base.",
      "Deal terms (3.5% annual increases through 2028) represent a significant move from Anthem's initial 1-2% offers, suggesting employer pressure forced Anthem to compromise.",
    ],
  },
  arguments: {
    payor: [
      { phase: "Pre-Termination (Dec 2024–Mar 2025)", points: [
        "Claimed MU Health was demanding a <strong>39% price increase over three years</strong> — four times the rate of inflation",
        "Offered <strong>1% increases for physicians, 2% for hospitals</strong> annually, which Anthem said was responsible and sustainable",
        "Stated it would 'continue working with MU Health to reach an agreement that maintains affordable access to care'",
      ] },
      { phase: "Out-of-Network Period (Apr–Jun 2025)", points: [
        "Maintained that MU Health's rate demands were <strong>out of line with other health systems</strong> in the region",
        "Established continuity of care program for patients with acute conditions (cancer, pregnancy, transplants, recent surgeries)",
        "Anthem's Rich Novack admitted continuity of care process was <strong>'clunky'</strong> and 'we have not done as well as we should have'",
      ] },
      { phase: "Senate Hearing & Resolution (Jun–Jul 2025)", points: [
        "Novack made surprise offer at hearing: <strong>CPI + 1% annual increases</strong> (3.3% for current year)",
        "Anthem <strong>doubled its rate increase offer</strong> after Senate pressure, including increased physician payments",
        "Final deal: <strong>3.5% annual increases through 2028</strong> — retroactive to April 1 with claims reprocessing",
      ] },
    ],
    provider: [
      { phase: "Pre-Termination (Dec 2024–Mar 2025)", points: [
        "Facing <strong>7% year-over-year increases in operating costs</strong> — Anthem's 1-2% offers did not cover inflation",
        "Anthem rates were <strong>10-20% lower than what other insurers</strong> (including UHC) pay MU Health for the same services",
        "Extended contract with <strong>UnitedHealthcare during same period</strong>, demonstrating MU's rates are acceptable to other major insurers",
      ] },
      { phase: "Out-of-Network Period (Apr–Jun 2025)", points: [
        "Published 'Anthem Removes Access' framing that was <strong>adopted wholesale by media</strong> — placed blame squarely on insurer",
        "Lowered rate request to <strong>single-digit annual increases over three years</strong>, demonstrating willingness to compromise",
        "Created dedicated call center and FAQ page positioning MU Health as <strong>patient advocate</strong> while Anthem was absent from community forums",
      ] },
      { phase: "Senate Hearing & Resolution (Jun–Jul 2025)", points: [
        "CEO Ransom testified: <strong>'The total economic value of every Anthem proposal has been the same. Anthem never negotiated.'</strong>",
        "CMO Dr. Whitt on resolution: 'Throughout this negotiation, <strong>our patients have been our top priority</strong>'",
        "Secured <strong>3.5% annual increases through 2028</strong> — significantly above Anthem's initial 1-2% offers, vindicating MU's position",
      ] },
      { phase: "Post-Resolution", points: [
        "Deal retroactive to April 1 — patients eligible for <strong>reimbursement of out-of-pocket costs</strong> paid during the gap",
        "Medicare Advantage plans <strong>remain excluded</strong> from the deal — approximately 6,800 patients still out-of-network, preserving leverage for future negotiations",
      ] },
    ],
  },
  timeline: [
    { date: "2024-07-01", type: "negotiation", label: "MU sends initial proposal to Anthem" },
    { date: "2024-12-11", type: "newsBreak", label: "Dispute becomes public — patient notifications begin" },
    { date: "2025-02-11", type: "escalation", label: "Medicare Advantage contract terminated" },
    { date: "2025-03-26", type: "context", label: "MU extends UnitedHealthcare deal (contrast)" },
    { date: "2025-03-31", type: "termination", label: "All Anthem commercial contracts expire" },
    { date: "2025-04-01", type: "termination", label: "90,000 patients go out-of-network" },
    { date: "2025-04-26", type: "stakeholder", label: "LiUNA town hall — Anthem absent" },
    { date: "2025-06-30", type: "hearing", label: "Missouri Senate hearing — 'never been close'" },
    { date: "2025-07-08", type: "pressure", label: "O'Laughlin demands deal this week" },
    { date: "2025-07-15", type: "agreement", label: "Agreement reached — retroactive to April 1" },
  ],
};
