// Ohio State University Wexner Medical Center vs Anthem Blue Cross Blue Shield — PR War Room Config
// Dispute period: November–December 2024. Commercial contract resolved December 30, 2024.
// Medicare Advantage remained unresolved — ~20,000 patients went out-of-network Jan 1, 2025.

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2024-11-15",
    source: "Ohio University HR (employer notice)",
    url: "https://www.ohio.edu/news/2024/11/ohio-shares-update-health-insurance-provider-anthem-blue-cross-blue-shield",
    sourceType: "owned",
    channel: "employer",
    headline: "Ohio University shares Anthem update: OSU Health System may leave Anthem network after Jan 1",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "One of the earliest public signals. Ohio University (separate institution) notifies employees that Anthem is working to reach a new multi-year contract with the OSU Health System. Employer-facing communication signals the dispute is real and imminent.",
  },
  {
    id: 2,
    date: "2024-12-04",
    source: "OSU Wexner Medical Center (patient email)",
    sourceType: "owned",
    channel: "media",
    headline: "OSU Wexner sends email to 135,000 Anthem patients: coverage may end January 1",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "CRITICAL TRIGGER EVENT. 135,000 patients received an email notification that Anthem insurance may be removed from the network on Jan 1, 2025. OSU frames Anthem as underpaying. This mass patient notification is the moment the dispute becomes broadly public and generates immediate anxiety.",
  },
  {
    id: 3,
    date: "2024-12-05",
    source: "10TV (WBNS Columbus)",
    url: "https://www.10tv.com/article/news/local/ohio-state-anthem-insurance-negotiations/530-51995103-f3ca-4ba6-876a-25357723e6df",
    sourceType: "tv",
    channel: "media",
    headline: "Patients at Wexner Medical Center could lose coverage from Anthem in 2025",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "First major local TV coverage. Features Thea Flittner, Type 1 diabetic who received care at OSU during high-risk pregnancy: 'You feel really uncertain because all of a sudden you are left wondering do I need to find new medical care?' Patient-sympathetic framing sets early tone.",
  },
  {
    id: 4,
    date: "2024-12-05",
    source: "WHIO TV 7 (Dayton)",
    url: "https://www.whio.com/news/local/patients-ohio-hospital-could-lose-coverage-anthem-next-year/XTPAVNXN4NB7TEA5LNP3S5QDJA/",
    sourceType: "tv",
    channel: "media",
    headline: "Patients at Ohio hospital could lose coverage from Anthem next year",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Dayton market coverage extends reach beyond Columbus. Same Thea Flittner patient story. 'Could lose coverage' framing creates immediate fear. WHIO reaches southwestern Ohio — Anthem's large employer base.",
  },
  {
    id: 5,
    date: "2024-12-06",
    source: "WOSU Public Media",
    url: "https://www.wosu.org/2024-12-06/anthem-and-ohio-state-strained-contract-talks-put-135-000-insured-patients-in-jeopardy",
    sourceType: "news",
    channel: "media",
    headline: "Anthem and Ohio State strained contract talks put 135,000 insured patients in jeopardy",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "WOSU (NPR affiliate) provides detailed reporting. Both sides quoted: OSU says Anthem underpaid, costs rose 45% in 5 years; Anthem says OSU wants rate hikes 3x inflation, would cost Central Ohio $185M over 3 years. Key piece — most thorough early reporting. Reporter Emily Puckett.",
  },
  {
    id: 6,
    date: "2024-12-06",
    source: "NBC4 (WCMH Columbus)",
    url: "https://www.nbc4i.com/news/local-news/columbus/patients-in-limbo-as-ohio-state-anthem-negotiate-insurance-rates/",
    sourceType: "tv",
    channel: "media",
    headline: "Patients in limbo as Ohio State, Anthem negotiate insurance rates",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "NBC4 Columbus coverage. 'Patients in limbo' framing places patients as victims of dispute. Features Hoa McManus, breast cancer survivor diagnosed July 2022, treated at The James: 'I have multiple doctors' appointments...I'm not going to seek care anywhere else. This is one of the best cancer hospitals in the country.' Cancer patient framing is devastating for Anthem.",
  },
  {
    id: 7,
    date: "2024-12-06",
    source: "ABC6 On Your Side (Columbus)",
    url: "https://abc6onyourside.com/news/local/patients-worried-about-coverage-amid-osu-insurance-contract-battle-anthem-blue-cross-blue-shield-contract-negotiation-standoff",
    sourceType: "tv",
    channel: "media",
    headline: "Patients worried about coverage amid OSU insurance contract battle",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "ABC6 Columbus coverage. 'Contract battle' framing. Patient anxiety stories. Columbus is a three-station local TV market and all three (10TV, NBC4, ABC6) covered this in the first 48 hours — total local saturation.",
  },
  {
    id: 8,
    date: "2024-12-06",
    source: "Dayton 24/7 Now",
    url: "https://dayton247now.com/news/local/patients-worried-about-coverage-amid-osu-insurance-contract-battle-anthem-blue-cross-blue-shield-contract-negotiation-standoff",
    sourceType: "tv",
    channel: "media",
    headline: "Patients worried about coverage amid OSU insurance contract battle — Dayton market",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Syndicated/shared coverage with ABC6 reaching Dayton market. OSU Wexner draws patients from across Ohio — dispute is statewide news, not just Columbus.",
  },
  {
    id: 9,
    date: "2024-12-09",
    source: "Ohio University (employer update)",
    url: "https://www.ohio.edu/news/2024/12/ohio-continues-monitor-ongoing-negotiations-between-anthem-blue-cross-blue-shield-osu",
    sourceType: "owned",
    channel: "employer",
    headline: "Ohio University continues to monitor ongoing negotiations between Anthem and OSU Health System",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Ohio University (separate institution in Athens, OH) uses Anthem for employee health insurance. Their HR department posts public update monitoring the OSU-Anthem dispute. Key employer signal: other institutions' employees are directly affected by this dispute.",
  },
  {
    id: 10,
    date: "2024-12-09",
    source: "Anthem Blue Cross Blue Shield (employer letter)",
    url: "https://www.ohio.edu/sites/default/files/2024-12/Anthem%20BCBS%20OSUWMC%20letter_LSG_12.6.24.pdf",
    sourceType: "owned",
    channel: "employer",
    headline: "Anthem sends employer letter: 'working to reach a new multi-year contract' with OSU — continuity of care provisions outlined",
    frameAdoption: "anthem",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "osu",
    reachEstimate: "medium",
    notes: "Anthem's employer-facing letter (Dec 6, signed by John J. Warner MD). Outlines continuity of care: patients with 3+ complex visits in past 6 months auto-eligible for 90-day in-network extension. Anthem frames itself as protecting patients while negotiating. Professional, measured tone.",
  },
  {
    id: 11,
    date: "2024-12-10",
    source: "Yahoo News (syndication)",
    url: "https://www.yahoo.com/news/patients-limbo-ohio-state-anthem-034125621.html",
    sourceType: "news",
    channel: "media",
    headline: "Patients in limbo as Ohio State, Anthem negotiate insurance rates — national syndication",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Yahoo News syndication extends reach nationally. Columbus local coverage now reaching national audience. Patient stories (Hoa McManus cancer survivor) gain national visibility. Yahoo News is high-traffic aggregator.",
  },
  {
    id: 12,
    date: "2024-12-12",
    source: "Yahoo News (syndication #2)",
    url: "https://www.yahoo.com/news/thousands-patients-limbo-ohio-state-213401822.html",
    sourceType: "news",
    channel: "media",
    headline: "Thousands of patients in limbo as Ohio State, Anthem insurance contract deadline nears",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Second Yahoo syndication. 'Thousands of patients in limbo' and 'deadline nears' create urgency framing. National audience seeing this as a countdown. Anthem losing the narrative nationally.",
  },
  {
    id: 13,
    date: "2024-12-12",
    source: "Anthem Blue Cross Blue Shield (continued negotiations update)",
    url: "https://www.ohio.edu/hr/news/anthem-blue-cross-blue-shield-continues-negotiations-ohio-state-university-hospitals",
    sourceType: "owned",
    channel: "employer",
    headline: "Anthem BCBS continues negotiations with Ohio State University hospitals — employer HR update",
    frameAdoption: "anthem",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "osu",
    reachEstimate: "medium",
    notes: "Anthem update distributed through Ohio University HR channel. Notes Anthem 'is working hard to ensure continuity of care.' Continuity-of-care messaging is Anthem's primary employer communication strategy. 90-day transition provisions emphasized.",
  },
  {
    id: 14,
    date: "2024-12-15",
    source: "46brooklyn Research",
    url: "https://www.46brooklyn.com/news/anthem-vs-osu-hospital-price-transparency-files-reveal-the-stakes-in-the-fight-between-two-healthcare-giants-ajfh37",
    sourceType: "news",
    channel: "media",
    headline: "Anthem & OSU: Hospital price transparency files reveal the stakes in the fight between two healthcare giants",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "KEY ANALYTICAL PIECE. 46brooklyn leveraged federal hospital price transparency data to analyze Anthem's actual rates at OSU vs peers. Independent data analysis. Provides factual grounding that neither side's PR fully captures. Influential among policy analysts and benefits consultants. Antonio Ciaccia's 46brooklyn is respected for pharmaceutical/healthcare price analysis.",
  },
  // === OSU OWNED MEDIA ===
  {
    id: 15,
    date: "2024-12-04",
    source: "OSU Wexner Medical Center (official statement)",
    sourceType: "owned",
    channel: "media",
    headline: "OSU statement: 'Anthem has underpaid us for the past few years, failing to keep pace with inflation'",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "OSU's primary public position. Key claims: costs to deliver care rose 45% in 5 years; Anthem refused appropriate rate adjustments unlike other insurers; Elevance Health (Anthem parent) earned $77.9B in profits over 5 years. 'Record profits' framing positions Anthem as choosing profit over patients. Strong populist messaging.",
  },
  {
    id: 16,
    date: "2024-12-04",
    source: "Anthem Blue Cross Blue Shield (official statement)",
    sourceType: "owned",
    channel: "media",
    headline: "Anthem: OSU wants rate hikes more than 3x inflation, would boost Central Ohio healthcare costs by $185M",
    frameAdoption: "anthem",
    sentiment: "negative_osu",
    patientStory: false,
    blameDirection: "osu",
    reachEstimate: "medium",
    notes: "Anthem's primary public counter-narrative. Key claims: OSU demanding rate increases 3x inflation; would increase healthcare costs for Central Ohio by $185M over 3 years; 'We are currently in talks with the OSU health system to extend access to affordable care.' Affordability framing is Anthem's core argument.",
  },
  {
    id: 17,
    date: "2024-12-30",
    source: "OSU Wexner Medical Center (press release)",
    url: "https://wexnermedical.osu.edu/mediaroom/pressreleaselisting/anthemnegotiationsconclude",
    sourceType: "owned",
    channel: "media",
    headline: "Ohio State reaches agreement with Anthem on new commercial insurance contract — multi-year deal effective Jan 1",
    frameAdoption: "osu",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Official resolution announcement. Multi-year agreement preserves commercial plan access for 110,000+ patients. However, explicitly notes NO agreement on Medicare Advantage — OSU transitions out of Anthem MA network. Victory framing: 'continues access to high-quality, affordable care.' OSU claims credit for protecting patients.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 18,
    date: "2024-12-05",
    source: "Social media (patient reactions)",
    sourceType: "social",
    channel: "social",
    headline: "OSU patients share coverage anxiety on social media after receiving Dec 4 email notification",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "135,000 patients receiving simultaneous email notifications creates immediate social media reaction. Cancer patients at The James especially vocal. 'Where will I go?' anxiety is organic, authentic, and devastating for Anthem. Columbus is a large enough market to generate significant social volume.",
  },
  {
    id: 19,
    date: "2024-12-06",
    source: "Social media (Columbus community)",
    sourceType: "social",
    channel: "social",
    headline: "Columbus community reacts to OSU-Anthem dispute — OSU is largest employer in Columbus region",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "OSU is the largest single-site employer in Ohio and a cultural institution in Columbus. Threatening OSU Wexner access is seen as an attack on a community institution, not just a business dispute. Buckeye loyalty intensifies emotional response. Reddit r/Columbus and r/OhioStateUniversity likely had active threads.",
  },
  {
    id: 20,
    date: "2024-12-08",
    source: "Social media (employer/HR professionals)",
    sourceType: "social",
    channel: "social",
    headline: "HR professionals and benefits managers discuss OSU-Anthem fallout — open enrollment disruption concerns",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Timing is critical: dispute becomes public during open enrollment season. HR professionals managing employee questions about whether to stay with Anthem or switch plans. Creates practical business disruption beyond the PR battle. LinkedIn and benefits industry forums active.",
  },
  {
    id: 21,
    date: "2024-12-10",
    source: "Social media (cancer patient community)",
    sourceType: "social",
    channel: "social",
    headline: "James Cancer Hospital patients share fears about losing access to oncologists mid-treatment",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "The James is one of the top NCI-designated cancer centers in the Midwest. Patients mid-chemotherapy or post-surgery facing potential loss of their care team. Cancer patient communities generate intense organic sympathy. Hoa McManus story widely shared.",
  },
  {
    id: 22,
    date: "2024-12-15",
    source: "Social media (anti-insurer sentiment)",
    sourceType: "social",
    channel: "social",
    headline: "OSU-Anthem dispute amplified by broader anti-insurance industry sentiment following UHC CEO assassination",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "STRUCTURAL CONTEXT: Brian Thompson (UHC CEO) was killed Dec 4, 2024 — the SAME DAY OSU sent patient emails. While Anthem is not UHC, the anti-insurance industry sentiment is at an all-time high. Every insurer-vs-hospital dispute in December 2024 lands in a uniquely hostile social environment for the insurer side. Anthem/Elevance absorbs collateral reputational damage.",
  },
  {
    id: 23,
    date: "2024-12-20",
    source: "Social media (deadline anxiety)",
    sourceType: "social",
    channel: "social",
    headline: "Holiday season anxiety: patients fear losing OSU coverage on New Year's Day — 'worst timing possible'",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Year-end deadline during holiday season maximizes patient anxiety. People unable to reach HR departments or insurance representatives during holidays. The timing compounds emotional distress — patients planning New Year celebrations while worrying about Jan 1 coverage loss.",
  },
  {
    id: 24,
    date: "2024-12-31",
    source: "Social media (resolution relief)",
    sourceType: "social",
    channel: "social",
    headline: "Relief as commercial deal announced — but Medicare Advantage patients express anger at being left out",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Split social reaction: commercial plan patients relieved, but ~20,000 Medicare Advantage patients feel abandoned. MA patients skew older, less likely to be on social media but their adult children advocate loudly. 'Two-tier resolution' framing emerges.",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 25,
    date: "2024-12-04",
    source: "OSU Wexner Medical Center leadership",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "OSU leadership: 'Anthem has underpaid us for the past few years' — costs rose 45%, Anthem refused adjustments",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "OSU's core data argument. Key claims: care delivery costs rose 45% in 5 years; Anthem refused appropriate rate adjustments unlike other insurers; Anthem parent Elevance Health earned $77.9B in profits over 5 years while underpaying providers. Strong populist 'record profits' framing.",
  },
  {
    id: 26,
    date: "2024-12-06",
    source: "Anthem BCBS Ohio leadership",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Anthem: OSU demanding rate hikes 3x inflation — would cost Central Ohio employers $185M over 3 years",
    frameAdoption: "anthem",
    sentiment: "negative_osu",
    patientStory: false,
    blameDirection: "osu",
    reachEstimate: "medium",
    notes: "Anthem's core counter-argument. $185M figure is designed to alarm employers. 'Three times inflation' framing positions OSU as unreasonable. Anthem emphasizes commitment to 'affordable care' and ongoing negotiations. John J. Warner MD signed employer communications.",
  },
  {
    id: 27,
    date: "2024-12-06",
    source: "Ohio University HR Department",
    url: "https://www.ohio.edu/news/2024/12/ohio-continues-monitor-ongoing-negotiations-between-anthem-blue-cross-blue-shield-osu",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Ohio University HR develops informational website for employees affected by OSU-Anthem dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Ohio University (separate institution in Athens, OH) directly affected because it uses Anthem for employee coverage and many employees/dependents use OSU providers. Created FAQ and monitoring page. Other Ohio employers using Anthem likely took similar steps. Demonstrates cascading employer impact.",
  },
  {
    id: 28,
    date: "2024-12-10",
    source: "Central Ohio employers (aggregate)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Central Ohio employers scramble as HR departments field employee questions during open enrollment",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "TIMING ISSUE: dispute peaks during open enrollment season. Employers whose plans include Anthem must advise employees. Some employees may switch away from Anthem plans entirely. Creates business disruption for Anthem's employer-client relationships beyond the OSU dispute.",
  },
  {
    id: 29,
    date: "2024-12-15",
    source: "Governor DeWine / Ohio state officials (silence)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Governor DeWine and Ohio Department of Insurance have not publicly intervened — regulatory silence",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "SILENCE IS DATA. No public statement from Governor DeWine or Ohio Department of Insurance. OSU is a state institution — political dynamics are complex. Silence suggests officials expected private resolution. Ohio does not have a mandatory cooling-off period like some states. Lack of regulatory intervention leaves patients without a government backstop.",
  },
  {
    id: 30,
    date: "2024-12-06",
    source: "Anthem continuity of care provisions",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Anthem offers 90-day transition: patients with 3+ complex visits in 6 months get automatic in-network extension",
    frameAdoption: "anthem",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Anthem's key mitigation move: automatic 90-day in-network extension for patients with complex care needs (3+ visits in past 6 months). Letters mailed to eligible individuals. This partially defuses the 'patients cut off mid-treatment' argument but only covers a subset of 135,000 affected patients.",
  },
  {
    id: 31,
    date: "2024-12-20",
    source: "OhioHealth-Anthem parallel dispute context",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Anthem's pattern: OhioHealth also facing coverage dispute with Anthem — systemic Ohio provider-Anthem tension",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "PATTERN EVIDENCE. OhioHealth (another major Ohio system) is also in contract disputes with Anthem — their contract eventually faces August 2025 deadline. Anthem is fighting multiple Ohio health systems. Pattern suggests corporate strategy, not OSU-specific unreasonableness. Anthem also had disputes with Bon Secours Mercy in Ohio.",
  },
  {
    id: 32,
    date: "2024-12-04",
    source: "Elevance Health financial context",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Elevance Health (Anthem parent): $77.9B revenue over 5 years — OSU frames as 'record profits while underpaying'",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "OSU's populist framing: Elevance Health is one of the largest for-profit insurance corporations in the US. '$77.9 billion in profits' over 5 years (OSU figure; some reports say $80B). This framing is highly effective in the post-Thompson environment. Anthem's profitability becomes a vulnerability in public narrative.",
  },
  // === RESOLUTION & FOLLOW-UP MEDIA ===
  {
    id: 33,
    date: "2024-12-30",
    source: "10TV (WBNS Columbus)",
    url: "https://www.10tv.com/article/news/local/ohio-state-anthem-reach-agreement-on-insurance-contract/530-2c808b9e-5f96-42d6-9ad1-a9189ec2ed80",
    sourceType: "tv",
    channel: "media",
    headline: "Ohio State, Anthem reach agreement on new commercial insurance contract",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution coverage. 10TV reports multi-year agreement reached for commercial plans. Notes Medicare Advantage NOT included. 110,000+ patients retain in-network access. Same outlet that broke anxiety-driven coverage now reports relief — but with caveat about MA patients.",
  },
  {
    id: 34,
    date: "2024-12-31",
    source: "WOSU Public Media",
    url: "https://www.wosu.org/2024-12-31/ohio-state-anthem-hammer-out-last-minute-health-insurance-contract",
    sourceType: "news",
    channel: "media",
    headline: "Ohio State, Anthem, hammer out last-minute health insurance contract",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "WOSU resolution reporting. 'Last-minute' framing suggests brinksmanship from both sides. Balanced reporting. Notes the deal was struck just ahead of the end-of-year deadline. WOSU provided the most consistently thorough coverage throughout the dispute.",
  },
  {
    id: 35,
    date: "2024-12-31",
    source: "ABC6 On Your Side (Columbus)",
    url: "https://abc6onyourside.com/newsletter-daily/ohio-state-university-wexner-medical-center-the-james-cancer-hospital-anthem-blue-cross-blue-shield-agree-new-contract",
    sourceType: "tv",
    channel: "media",
    headline: "Ohio State University Wexner Medical Center and Anthem agree to new contract",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "ABC6 resolution coverage. Notes agreement includes The James Cancer Hospital. Relief framing for commercial plan patients. ABC6 had been among the first to cover patient anxiety.",
  },
  {
    id: 36,
    date: "2024-12-31",
    source: "NBC4 (WCMH Columbus)",
    url: "https://www.nbc4i.com/news/local-news/ohio-state-university/osu-wexner-anthem-reach-insurance-deal/",
    sourceType: "tv",
    channel: "media",
    headline: "OSU Wexner, Anthem reach insurance deal",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "NBC4 Columbus resolution coverage. Brief, factual. All three Columbus TV stations covered resolution — same saturation as initial anxiety coverage.",
  },
  {
    id: 37,
    date: "2024-12-31",
    source: "Hoodline (national syndication)",
    url: "https://hoodline.com/2024/12/ohio-state-university-wexner-medical-center-and-anthem-resolve-coverage-for-commercial-insurance-patients-medicare-advantage-members-face-changes/",
    sourceType: "news",
    channel: "media",
    headline: "OSU Wexner and Anthem resolve coverage for commercial patients — Medicare Advantage members face changes",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National syndication. Headline explicitly calls out the split resolution: commercial patients covered, MA patients not. 'Face changes' is a euphemism for losing in-network access. National audience sees partial resolution as incomplete.",
  },
  // === MEDICARE ADVANTAGE FALLOUT ===
  {
    id: 38,
    date: "2025-01-01",
    source: "10TV (WBNS Columbus)",
    url: "https://www.10tv.com/article/news/local/wexner-medical-center-anthem-medicare-advantage-end-contract/530-236880b0-28c1-4c0c-a36c-df1b8f992ba2",
    sourceType: "tv",
    channel: "media",
    headline: "Nearly 28,000 customers to be impacted by Ohio State, Anthem Medicare Advantage ending contract",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "POST-RESOLUTION COVERAGE. 28,000 Anthem Medicare Advantage patients now out-of-network at OSU. Initially reported as 28,000; later adjusted to ~20,000. These are seniors — politically engaged, likely to contact elected officials. The 'victory' of the commercial deal is undercut by MA patient abandonment.",
  },
  {
    id: 39,
    date: "2025-01-03",
    source: "NBC4 (WCMH Columbus)",
    url: "https://www.nbc4i.com/news/local-news/ohio-state-university/anthem-medicare-advantage-patients-still-without-osu-coverage-how-they-can-stay-in-network/",
    sourceType: "tv",
    channel: "media",
    headline: "Anthem Medicare Advantage patients still without OSU coverage — how they can stay in network",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Service journalism for affected MA patients. NBC4 provides guidance on switching to other MA plans during open enrollment. The fact that TV stations are providing 'how to cope' guidance indicates real patient harm from the unresolved MA dispute.",
  },
  {
    id: 40,
    date: "2025-01-05",
    source: "Social media (Medicare Advantage patients)",
    sourceType: "social",
    channel: "social",
    headline: "Senior patients and their families express anger at being 'left behind' in the commercial deal",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Medicare Advantage patients (seniors) are a politically active demographic. Adult children advocating on social media for elderly parents. 'Two-tier deal' narrative: younger/employed patients protected, seniors abandoned. This is a potent equity argument against both sides but primarily damages Anthem.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 41,
    date: "2024-11-15",
    source: "Ohio University HR",
    url: "https://www.ohio.edu/news/2024/11/ohio-shares-update-health-insurance-provider-anthem-blue-cross-blue-shield",
    sourceType: "owned",
    channel: "employer",
    headline: "Ohio University shares Anthem update to employees — first major employer notification of potential disruption",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "EARLIEST EMPLOYER SIGNAL. Ohio University (in Athens, OH) notifies employees that Anthem is negotiating with OSU Health System. Many OU employees/dependents use OSU providers for specialized care. Ohio University is one example — dozens of Central Ohio employers were similarly affected.",
  },
  {
    id: 42,
    date: "2024-12-06",
    source: "Anthem employer letter (John J. Warner MD)",
    url: "https://www.ohio.edu/sites/default/files/2024-12/Anthem%20BCBS%20OSUWMC%20letter_LSG_12.6.24.pdf",
    sourceType: "owned",
    channel: "employer",
    headline: "Anthem sends formal employer letter outlining continuity provisions — 90-day transition for complex patients",
    frameAdoption: "anthem",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "osu",
    reachEstimate: "high",
    notes: "CRITICAL EMPLOYER DOCUMENT. Signed by John J. Warner MD. Details 90-day in-network transition for patients with complex care needs. Outlines notification timeline: letters to qualifying patients by mail. Anthem's most professional employer-facing communication. Designed to calm employer anxiety while positioning Anthem as the responsible party.",
  },
  {
    id: 43,
    date: "2024-12-10",
    source: "Central Ohio employers (HR departments)",
    sourceType: "news",
    channel: "employer",
    headline: "Central Ohio HR departments field employee questions — open enrollment season compounds disruption",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Dispute peaks during open enrollment season (Nov-Dec). HR departments must advise employees whether to stay with Anthem. Some employees may have switched plans entirely due to uncertainty. Anthem risks losing commercial enrollment if employers lose confidence in network stability.",
  },
  {
    id: 44,
    date: "2024-12-15",
    source: "Self-insured employer concerns",
    sourceType: "news",
    channel: "employer",
    headline: "Self-insured employers using Anthem network face direct cost exposure if OSU goes out-of-network",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "For self-insured (ASO) employers, OSU going out-of-network means employees either pay more out-of-pocket or the employer absorbs higher out-of-network costs. This creates direct financial pressure on employers to intervene or switch from Anthem. Key employer vulnerability for Anthem.",
  },
  {
    id: 45,
    date: "2024-12-31",
    source: "Ohio University (resolution update)",
    url: "https://www.ohio.edu/news/2025/01/anthem-blue-cross-blue-shield-osu-health-system-reach-tentative-multi-year-agreement",
    sourceType: "owned",
    channel: "employer",
    headline: "Ohio University shares resolution: Anthem and OSU Health System reach tentative multi-year agreement",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Ohio University closes the loop for its employees — commercial agreement reached. Relief for employer HR departments. But the Medicare Advantage gap means some older employees/retirees still affected.",
  },
  // === ADDITIONAL MEDIA/STAKEHOLDER ===
  {
    id: 46,
    date: "2024-12-06",
    source: "Becker's Payer Issues",
    url: "https://www.beckerspayer.com/contracting/ohio-hospital-drops-anthem-medicare-advantage-medicaid-plans.html",
    sourceType: "news",
    channel: "media",
    headline: "Ohio hospital drops Anthem Medicare Advantage, Medicaid plans — Becker's trade coverage",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Healthcare trade press. Becker's audience is hospital executives and health system leaders nationally. Positions OSU-Anthem as part of a national trend of health systems dropping MA plans. Executive audience notes pattern.",
  },
  {
    id: 47,
    date: "2024-12-08",
    source: "Becker's Hospital Review",
    url: "https://www.beckershospitalreview.com/payer-issues/the-ohio-state-university-wexner-medical-center-joins-anthem-bcbs-network.html",
    sourceType: "news",
    channel: "media",
    headline: "Becker's Hospital Review tracks OSU Wexner-Anthem negotiations — hospital executive audience",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Becker's Hospital Review coverage. National hospital executive audience observing the dispute as a case study in payer-provider negotiations. OSU is a major academic medical center — its negotiating posture is watched by peer institutions.",
  },
  {
    id: 48,
    date: "2024-12-10",
    source: "DistilInfo HealthPlan",
    url: "https://distilinfo.com/healthplan/ohiohealth-patients-face-devastating/",
    sourceType: "news",
    channel: "media",
    headline: "OhioHealth patients face devastating Anthem coverage loss — broader Ohio Anthem pattern coverage",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "low",
    notes: "Health plan trade press. 'Devastating' in headline is strong editorial framing. Covers both OSU and OhioHealth Anthem disputes together — pattern framing damages Anthem. Positions Anthem as systematically disrupting Ohio healthcare access.",
  },
  {
    id: 49,
    date: "2024-12-20",
    source: "Anthem Medicare Advantage provider notification",
    url: "https://providernews.anthem.com/ohio/articles/ohio-2025-medicare-advantage-plan-changes-23055",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "Anthem provider news: Ohio 2025 Medicare Advantage plan changes — OSU exits Anthem MA network",
    frameAdoption: "anthem",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Anthem's provider-facing communication. Clinical, bureaucratic tone. Lists network changes for 2025 MA plans in Ohio. OSU's exit is one of several changes listed. Anthem treats it as routine network adjustment — very different from patient/media framing of 'crisis.'",
  },
  {
    id: 50,
    date: "2024-12-25",
    source: "Social media (holiday timing backlash)",
    sourceType: "social",
    channel: "social",
    headline: "Patients express frustration at Christmas week uncertainty — 'Can't reach anyone to ask about my coverage'",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Holiday timing is uniquely cruel for patients. Insurance company and hospital administrative offices on reduced hours. Patients cannot get answers during Christmas week about their January 1 coverage status. Organic social sharing of frustration. Both sides share blame for the timing, but patients direct anger at the insurer.",
  },
  {
    id: 51,
    date: "2024-12-06",
    source: "OSU Wexner leadership — $45% cost increase claim",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "OSU: 'Our costs to deliver care have risen 45% in the last five years' — Anthem refused adjustments unlike other insurers",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "OSU's stickiest data argument. 45% cost increase over 5 years is verifiable through hospital financial filings. 'Unlike other insurance providers, Anthem has refused to consider appropriate rate adjustments' positions Anthem as the outlier, not OSU. Implies other insurers found OSU's requests reasonable.",
  },
  {
    id: 52,
    date: "2024-12-06",
    source: "Anthem — affordability framing",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Anthem frames dispute as protecting Central Ohio from $185M in excess healthcare costs",
    frameAdoption: "anthem",
    sentiment: "negative_osu",
    patientStory: false,
    blameDirection: "osu",
    reachEstimate: "medium",
    notes: "Anthem's strongest employer-facing argument. $185M figure over 3 years is designed to make employers question OSU's demands. 'Three times inflation' is a powerful talking point. But in the post-Thompson environment, insurer-as-protector framing has reduced credibility.",
  },
  {
    id: 53,
    date: "2024-12-15",
    source: "46brooklyn (price transparency data analysis)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "46brooklyn: Hospital price transparency files show Anthem-OSU rate dynamics — independent data analysis",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "INDEPENDENT ANALYSIS. 46brooklyn used federal price transparency data (required since 2021) to evaluate both sides' claims. Antonio Ciaccia's team is respected for unbiased healthcare price analysis. This piece provides the most objective data available to evaluate whether Anthem or OSU's framing is more accurate.",
  },
  {
    id: 54,
    date: "2024-12-28",
    source: "Social media (deadline countdown)",
    sourceType: "social",
    channel: "social",
    headline: "Social media countdown to Dec 31 deadline — 'three days until 135,000 patients lose coverage'",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Countdown framing on social media creates urgency. '135,000 patients' figure (from OSU communications) widely shared. Year-end deadline creates natural news hook. Columbus media market and Ohio social media highly engaged.",
  },
  {
    id: 55,
    date: "2025-01-01",
    source: "Anthem Medicare Advantage (press statement)",
    url: "https://www.anthem.com/press/ohio/anthem-blue-cross-and-blue-shield-adds-the-ohio-state-university-wexner-medical-center-to-all-its-medicare-advantage-plans/",
    sourceType: "owned",
    channel: "media",
    headline: "Anthem eventually adds OSU Wexner to all Medicare Advantage plans — resolution after initial Jan 1 gap",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "EVENTUAL RESOLUTION. After an initial period where MA patients were out-of-network, Anthem and OSU ultimately reached a Medicare Advantage agreement as well. This press release from Anthem announces the addition. However, the gap period caused real harm to affected seniors and became the most negative coverage of the entire dispute.",
  },
  {
    id: 56,
    date: "2024-12-06",
    source: "Yahoo News (AP/wire syndication)",
    url: "https://www.yahoo.com/news/patients-ohio-hospital-could-lose-102935375.html",
    sourceType: "news",
    channel: "media",
    headline: "Patients at Ohio hospital could lose coverage from Anthem next year — national wire syndication",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "AP/wire syndication reaches national audience via Yahoo. 'Could lose coverage' framing is anxiety-inducing. National audience now aware of dispute. Wire services carry the Thea Flittner patient story nationally.",
  },
  {
    id: 57,
    date: "2024-12-20",
    source: "Benefits broker advisories (aggregate)",
    sourceType: "news",
    channel: "employer",
    headline: "Benefits brokers across Ohio advise employer clients on OSU-Anthem dispute impact and contingency plans",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Insurance brokers serving Ohio employers must advise on the dispute. Broker advisories typically take a neutral tone but the practical effect is that employers question Anthem's network reliability. Some brokers may recommend adding alternative carrier options at next renewal.",
  },
  {
    id: 58,
    date: "2024-12-31",
    source: "Anthem BCBS (resolution statement)",
    sourceType: "owned",
    channel: "media",
    headline: "Anthem announces commercial agreement with OSU — 'continues access to high-quality, affordable care'",
    frameAdoption: "anthem",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Anthem's resolution statement. 'Affordable care' framing claims Anthem protected employers from excessive costs. Positions deal as Anthem's choice to 'continue access.' But the MA exclusion undercuts the 'we protect patients' narrative.",
  },
  {
    id: 59,
    date: "2024-12-15",
    source: "Bon Secours Mercy-Anthem parallel (Ohio)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Bon Secours Mercy Health also in Anthem dispute — Anthem fighting multiple Ohio health systems",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "PATTERN EVIDENCE. Bon Secours Mercy Health in Ohio also had Elevance/Anthem contract disputes. Combined with OhioHealth's upcoming dispute, Anthem is fighting at least three major Ohio health systems. Pattern undermines Anthem's 'OSU is uniquely unreasonable' framing.",
  },
  {
    id: 60,
    date: "2024-12-04",
    source: "OSU Wexner — 'unlike other insurance providers' framing",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "OSU: 'Unlike other insurance providers, Anthem has refused to consider appropriate rate adjustments'",
    frameAdoption: "osu",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "OSU's most strategically damaging claim: that other insurers HAVE agreed to rate adjustments, isolating Anthem as the outlier. If true, this undermines Anthem's position that OSU's demands are unreasonable — other payers apparently found them acceptable. This is OSU's strongest reputational argument.",
  },
];

const LABELS = {
  frameAdoption: { osu: "OSU Frame", anthem: "Anthem Frame", balanced: "Balanced" },
  sentiment: {
    negative_anthem: "Anti-Anthem",
    negative_osu: "Anti-OSU",
    neutral: "Neutral",
    positive_anthem: "Pro-Anthem",
    positive_osu: "Pro-OSU",
  },
  blameDirection: { anthem: "Blames Anthem", osu: "Blames OSU", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National record (1.5)
  "Yahoo News (syndication)": 1.5, "Yahoo News (AP/wire syndication)": 1.5, "Yahoo News (syndication #2)": 1.5,
  // Tier 2 — Regional authority (1.2)
  "10TV (WBNS Columbus)": 1.2, "NBC4 (WCMH Columbus)": 1.2, "ABC6 On Your Side (Columbus)": 1.2,
  "WOSU Public Media": 1.2, "WHIO TV 7 (Dayton)": 1.2, "Dayton 24/7 Now": 1.2,
  // Tier 3 — Trade/niche (1.0)
  "46brooklyn Research": 1.0, "Becker's Payer Issues": 1.0, "Becker's Hospital Review": 1.0,
  "DistilInfo HealthPlan": 1.0, "Hoodline (national syndication)": 1.0,
  // Tier 4 — Organic social (0.7)
  "Social media (patient reactions)": 0.7, "Social media (Columbus community)": 0.7,
  "Social media (employer/HR professionals)": 0.7, "Social media (cancer patient community)": 0.7,
  "Social media (anti-insurer sentiment)": 0.7, "Social media (deadline anxiety)": 0.7,
  "Social media (resolution relief)": 0.7, "Social media (holiday timing backlash)": 0.7,
  "Social media (deadline countdown)": 0.7, "Social media (Medicare Advantage patients)": 0.7,
  // Tier 5 — Comment sections (0.4)
  // (none catalogued)
  // Tier 6 — Owned/party media (0.3)
  "OSU Wexner Medical Center (patient email)": 0.3, "OSU Wexner Medical Center (official statement)": 0.3,
  "OSU Wexner Medical Center (press release)": 0.3, "OSU Wexner Medical Center leadership": 0.3,
  "OSU Wexner leadership — $45% cost increase claim": 0.3,
  "OSU Wexner — 'unlike other insurance providers' framing": 0.3,
  "Anthem Blue Cross Blue Shield (official statement)": 0.3, "Anthem BCBS (resolution statement)": 0.3,
  "Anthem Blue Cross Blue Shield (continued negotiations update)": 0.3,
  "Anthem Blue Cross Blue Shield (employer letter)": 0.3,
  "Anthem employer letter (John J. Warner MD)": 0.3,
  "Anthem Medicare Advantage (press statement)": 0.3,
  "Anthem Medicare Advantage provider notification": 0.3,
  "Ohio University HR (employer notice)": 0.3, "Ohio University HR": 0.3,
  "Ohio University (resolution update)": 0.3, "Ohio University HR Department": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "Anthem continuity of care provisions": 1.3, "Governor DeWine / Ohio state officials (silence)": 1.3,
  "OhioHealth-Anthem parallel dispute context": 1.3, "Elevance Health financial context": 1.3,
  "Bon Secours Mercy-Anthem parallel (Ohio)": 1.3,
  "Central Ohio employers (aggregate)": 1.3,
  "Anthem — affordability framing": 1.3, "Anthem BCBS Ohio leadership": 1.3,
  "46brooklyn (price transparency data analysis)": 1.3,
  // Tier 8 — Employer/Benefits (1.5x trade, 1.0x general)
  "Central Ohio employers (HR departments)": 1.0, "Self-insured employer concerns": 1.0,
  "Benefits broker advisories (aggregate)": 1.5,
};

const SEARCH_TRENDS = [
  { week: "2024-10-28", interest: 1 }, { week: "2024-11-04", interest: 2 }, { week: "2024-11-11", interest: 3 },
  { week: "2024-11-18", interest: 5 }, { week: "2024-11-25", interest: 8 }, { week: "2024-12-02", interest: 55 },
  { week: "2024-12-09", interest: 78 }, { week: "2024-12-16", interest: 60 }, { week: "2024-12-23", interest: 85 },
  { week: "2024-12-30", interest: 100 }, { week: "2025-01-06", interest: 45 }, { week: "2025-01-13", interest: 20 },
];

export default {
  active: false,
  // Identity
  providerKey: "osu",
  payorKey: "anthem",
  providerName: "Ohio State University Wexner Medical Center",
  payorName: "Anthem Blue Cross Blue Shield",
  providerShort: "OSU",
  payorShort: "Anthem",
  navShort: "OSU v. Anthem",
  title: "OSU Wexner vs Anthem BCBS",
  subtitle: "Contract dispute · Partially resolved December 30, 2024",
  gradientId: "osuanthem",

  // Dates
  monitorStart: "November 1, 2024",
  monitorEnd: "January 31, 2025",
  disputeStatus: "resolved",
  disputePublicDate: "2024-12-04",

  // Colors
  colors: {
    providerColor: "#BB0000",
    payorColor: "#003DA5",
    neutral: "#5D7380",
    accent: "#BB0000",
    bg: "#ffffff",
    surface: "#f2f7fb",
    surfaceHover: "#e8f0f7",
    border: "#c8dce8",
    text: "#053b57",
    textMuted: "#5D7380",
  },
  distColors: ["#BB0000", "#6B4D6E", "#003DA5"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"ohio state anthem insurance" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.42,
    nationalMedian: 1.0,
    networkComplaints: 1120,
    priorYearComplaints: 890,
    regulatorAction: "Ohio Department of Insurance did not publicly intervene. No mandatory cooling-off period exists in Ohio. Governor DeWine made no public statement. Anthem offered voluntary 90-day continuity-of-care transition for complex patients.",
    signalRead: "Anthem/Elevance complaint index is moderately elevated (1.42x median) reflecting multi-state provider disputes. The 26% increase in network complaints tracks with Anthem's disputes with OSU, OhioHealth, and Bon Secours Mercy in Ohio. Ohio's lack of a mandatory cooling-off period leaves patients more exposed than in states like New York or Connecticut.",
  },

  talkingPoints: {
    provider: [
      { name: "135K patient emails", keywords: ["135,000", "135K", "135k", "patient email", "patient notification", "mass notification"] },
      { name: "45% cost increase / underpaid", keywords: ["45%", "costs rose 45", "underpaid", "failing to keep pace", "cost.*deliver.*care"] },
      { name: "Elevance $77.9B profits", keywords: ["\\$77\\.9", "77\\.9B", "record profit", "Elevance", "profit.*5 year"] },
      { name: "Cancer patients / The James", keywords: ["cancer", "The James", "James Cancer", "oncolog", "chemotherapy", "NCI-designated", "Hoa McManus", "breast cancer"] },
      { name: "Patient harm stories", keywords: ["Thea Flittner", "Type 1 diabet", "high-risk pregnancy", "pregnant", "mid-treatment", "uncertain"] },
      { name: "Unlike other insurers", keywords: ["unlike other", "other insurance providers", "other insurers agreed", "Anthem refused", "outlier"] },
      { name: "OSU as community institution", keywords: ["largest employer", "cultural institution", "Buckeye", "state institution", "community institution"] },
      { name: "Medicare Advantage gap / seniors", keywords: ["Medicare Advantage", "20,000", "28,000", "senior", "MA patient", "left behind", "two-tier"] },
    ],
    payor: [
      { name: "3x inflation / $185M cost", keywords: ["3x inflation", "three times", "\\$185M", "185 million", "185M", "boost.*cost"] },
      { name: "Affordability framing", keywords: ["affordable care", "affordability", "affordable", "raise costs", "increase.*cost"] },
      { name: "90-day continuity of care", keywords: ["90-day", "continuity of care", "transition", "complex visit", "3\\+ complex", "John.*Warner"] },
      { name: "Open enrollment disruption", keywords: ["open enrollment", "enrollment season", "switch plan", "plan selection"] },
      { name: "Anti-insurer environment / Thompson", keywords: ["Brian Thompson", "UHC CEO", "assassination", "anti-insurer", "hostile.*environment"] },
      { name: "Holiday timing pressure", keywords: ["holiday", "Christmas", "New Year", "worst timing", "year-end", "holiday season"] },
    ],
  },

  // Executive summary
  executiveSummary: {
    statement: "The dispute resulted in a last-minute commercial contract deal on December 30, but Medicare Advantage patients (~20,000) lost in-network access on January 1. The PR battle was dominated by OSU's framing, amplified by the post-Thompson anti-insurer environment.",
    keyMessages: [
      "OSU's '45% cost increase over 5 years' claim and 'unlike other insurers, Anthem refused adjustments' framing positioned Anthem as the outlier, not the norm.",
      "The December 4 patient notification to 135,000 people — on the same day as the UHC CEO assassination — created an extraordinarily hostile public environment for the insurer.",
      "Anthem's '3x inflation / $185M cost increase' framing was its strongest argument but was undermined by Elevance Health's $77.9B profit figure.",
      "The split resolution (commercial deal reached, Medicare Advantage abandoned) gave OSU a partial victory but left 20,000 seniors as collateral damage.",
    ],
    marcomm: [
      "<strong>OSU holds the structural narrative advantage as a state institution.</strong> As Ohio's largest employer and a cultural icon, OSU is seen as a community institution. Anthem is seen as a for-profit outsider. This dynamic makes it nearly impossible for Anthem to win the public narrative.",
      "<strong>The post-Thompson timing was catastrophic for Anthem.</strong> The patient notification emails went out on December 4, 2024 — the same day Brian Thompson was killed. While Anthem is not UHC, the anti-insurance industry sentiment created a hostile backdrop for any insurer-vs-hospital dispute in December 2024.",
      "<strong>Holiday timing maximized patient distress.</strong> The Dec 31 deadline during the holiday season meant patients spent Christmas week unable to get answers about their January 1 coverage. This timing amplified anger beyond what a mid-year dispute would generate.",
      "<strong>The Medicare Advantage gap was the biggest reputational wound.</strong> The commercial deal allowed both sides to claim victory, but abandoning ~20,000 senior MA patients generated the most negative follow-up coverage and undermined the 'resolution' narrative.",
    ],
  },
  channelTakeaways: {
    media: [
      "All three Columbus TV stations (10TV, NBC4, ABC6) covered the dispute within 48 hours of the Dec 4 patient email — total local market saturation.",
      "WOSU (NPR affiliate) provided the most balanced, thorough reporting with both sides' data claims presented.",
      "Yahoo News syndication extended reach nationally — Columbus local stories appeared on one of the highest-traffic news aggregators.",
      "The 46brooklyn independent price transparency analysis provided the most objective data for evaluating both sides' claims.",
    ],
    social: [
      "135,000 simultaneous patient notification emails created an organic social media spike on December 4-5 that could not be manufactured.",
      "The Brian Thompson assassination (same day, Dec 4) created an unprecedented anti-insurer social environment that amplified the OSU-Anthem dispute.",
      "Cancer patients at The James sharing mid-treatment fears generated the most sympathetic organic content.",
      "Holiday-week timing ('Can't reach anyone about my coverage during Christmas') created uniquely emotional social sharing.",
    ],
    stakeholder: [
      "OSU's 'unlike other insurance providers' claim — that other insurers agreed to adjustments while Anthem refused — was the most damaging stakeholder argument.",
      "Anthem's pattern of disputes with multiple Ohio systems (OSU, OhioHealth, Bon Secours Mercy) undermined the 'OSU is uniquely unreasonable' defense.",
      "46brooklyn's independent price transparency analysis provided a neutral arbiter's perspective on both sides' rate claims.",
      "Governor DeWine's silence was notable — Ohio's lack of a mandatory cooling-off period left patients without a government backstop.",
    ],
    employer: [
      "Ohio University's public HR monitoring page demonstrated how the dispute cascaded to other employers across Ohio.",
      "Open enrollment season timing meant HR departments were advising employees on plan selection during the dispute — creating real risk of Anthem enrollment losses.",
      "Anthem's 90-day continuity-of-care letter (John J. Warner MD) was its best employer communication — professional, detailed, and action-oriented.",
      "Self-insured employers faced direct cost exposure, creating financial pressure that likely contributed to the commercial resolution.",
    ],
  },
  arguments: {
    payor: [
      { phase: "Initial Position (Dec 2024)", points: [
        "OSU demanding rate increases <strong>more than three times the inflation rate</strong>",
        "Rate hikes would boost healthcare costs for Central Ohio by <strong>$185 million over three years</strong>",
        "Anthem positioned itself as protecting <strong>affordable care</strong> for employers and patients",
      ] },
      { phase: "Employer Communication (Dec 2024)", points: [
        "Sent formal employer letter (Dr. John J. Warner) outlining <strong>90-day continuity of care</strong> provisions",
        "Emphasized voluntary patient protections: automatic in-network extension for patients with <strong>3+ complex visits in 6 months</strong>",
        "Framed Anthem as the responsible party working to 'extend access to affordable care'",
      ] },
      { phase: "Resolution (Dec 30, 2024)", points: [
        "Reached multi-year commercial agreement — 'continues access to <strong>high-quality, affordable care</strong>'",
        "Did NOT resolve Medicare Advantage dispute — ~20,000 seniors lost in-network access Jan 1",
        "Resolution statement maintained affordability framing but conciliatory tone suggested PR pressure was felt",
      ] },
    ],
    provider: [
      { phase: "Initial Position (Dec 2024)", points: [
        "Anthem has <strong>underpaid</strong> OSU for the past few years, failing to keep pace with inflation",
        "Care delivery costs rose <strong>45% in five years</strong>, Anthem refused appropriate rate adjustments",
        "Elevance Health (Anthem parent) earned <strong>$77.9 billion in profits</strong> over 5 years — 'record profits' framing",
        "'<strong>Unlike other insurance providers</strong>, Anthem has refused to consider appropriate rate adjustments' — isolates Anthem as the outlier",
      ] },
      { phase: "Patient Mobilization (Dec 2024)", points: [
        "Sent <strong>135,000 patient notification emails</strong> on Dec 4 — created massive organic public pressure",
        "Patients (Thea Flittner, Hoa McManus) provided powerful testimony about feared coverage loss",
        "Cancer patients at The James Cancer Hospital generated maximally sympathetic media coverage",
      ] },
      { phase: "Resolution (Dec 30, 2024)", points: [
        "Multi-year commercial agreement reached — preserves in-network access for <strong>110,000+ patients</strong>",
        "Victory framing: 'continues access to high-quality, affordable care'",
        "Medicare Advantage gap (~20,000 patients) remained a vulnerability — eventually resolved separately",
      ] },
    ],
  },
  timeline: [
    { date: "2024-11-15", type: "newsBreak", label: "Employer notifications begin" },
    { date: "2024-12-04", type: "newsBreak", label: "135,000 patient emails sent" },
    { date: "2024-12-06", type: "newsBreak", label: "Major media coverage wave" },
    { date: "2024-12-30", type: "agreement", label: "Commercial deal reached" },
    { date: "2024-12-31", type: "termination", label: "Contract expiration deadline" },
    { date: "2025-01-01", type: "termination", label: "MA patients lose in-network access" },
  ],
};
