// Piedmont Medical Center vs Cigna (SC) — PR War Room Config
// Dispute period: October–December 2025. Resolved December 31, 2025.
// Part of national Tenet Healthcare / Cigna contract dispute.

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2025-10-15",
    source: "Becker's Hospital Review",
    url: "https://www.beckershospitalreview.com/payer-issues/tenet-cigna-dispute-heats-up-ahead-of-contract-deadline.html",
    sourceType: "news",
    channel: "media",
    headline: "Tenet, Cigna dispute heats up ahead of contract deadline — national contract covering 64 hospitals at risk",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Early trade coverage of the brewing national Tenet/Cigna dispute. Notes contract expiration Dec 31. Tenet operates 64 hospitals, ~370 ASCs, and 2,000+ employed providers. Piedmont Medical Center in Rock Hill one of many facilities affected.",
  },
  {
    id: 2,
    date: "2025-10-22",
    source: "Healthcare Uncovered (Wendell Potter Substack)",
    url: "https://healthcareuncovered.substack.com/p/battle-between-health-care-giants",
    sourceType: "opinion",
    channel: "media",
    headline: "Battle Between Health Care Giants Puts Patient Access in Jeopardy — Cigna slashing ASC reimbursement",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Wendell Potter (former Cigna executive turned whistleblower) covers dispute. Notes Cigna trying to slash reimbursement for outpatient care at hundreds of Tenet ASCs. Cigna's proposal includes rate increases 'well below inflation' and cuts to physician/ambulatory reimbursement. Powerful credibility — insider critic of insurance industry.",
  },
  {
    id: 3,
    date: "2025-11-05",
    source: "ABC15 Arizona",
    url: "https://www.abc15.com/news/business/cigna-and-tenet-healthcare-locked-in-contract-dispute-affecting-413-000-arizona-enrollees",
    sourceType: "tv",
    channel: "media",
    headline: "Cigna and Tenet Healthcare locked in contract dispute affecting 413,000 Arizona enrollees",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "First major local TV coverage of national dispute via Arizona Abrazo Health angle. 413,000 enrollees at risk. Establishes scale of the Tenet/Cigna standoff that includes Piedmont Medical Center. Patient access framing favors hospital system.",
  },
  {
    id: 4,
    date: "2025-11-12",
    source: "Becker's ASC Review",
    url: "https://www.beckersasc.com/asc-coding-billing-and-collections/arizona-cigna-enrollees-may-lose-access-to-tenet-sites-amid-dispute/",
    sourceType: "news",
    channel: "media",
    headline: "Arizona Cigna enrollees may lose access to Tenet sites amid dispute — ASC reimbursement cuts at center",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "ASC-focused trade press. Notes Cigna wants to cut payments for ambulatory surgery centers while Tenet operates the largest ASC network nationally. Piedmont Medical Center's ambulatory network in York County directly affected.",
  },
  {
    id: 5,
    date: "2025-11-18",
    source: "Becker's Payer Issues",
    url: "https://www.beckerspayer.com/payer/tenet-on-cigna-dispute-being-forced-out-of-network-is-unsureance.html",
    sourceType: "news",
    channel: "media",
    headline: "Tenet on Cigna dispute: Being forced out of network is 'unsure-ance'",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Tenet's 'unsure-ance' branding campaign in paid media. Clever wordplay — 'If you have Cigna, you have health unsureance.' Ran in local newspapers across Tenet markets. Framing places blame on Cigna for creating uncertainty. Aggressive PR tactic.",
  },
  {
    id: 6,
    date: "2025-11-20",
    source: "FTI Consulting (Payer-Provider Dispute Tracker)",
    url: "https://fticommunications.com/q3-2025-health-insurance-payer-provider-dispute-update/",
    sourceType: "news",
    channel: "media",
    headline: "FTI: At least 90 payer-provider contract disputes in 2025, up from 51 in 2022 — Cigna among most active",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "FTI Consulting data: 51 disputes (2022), 86 (2023), 133 (2024), 90+ through Q3 2025. Cigna identified as one of the most active insurers in disputes. Systemic trend data normalizes Piedmont's position — Cigna is a serial disputant.",
  },
  {
    id: 7,
    date: "2025-11-25",
    source: "Yahoo Finance",
    url: "https://finance.yahoo.com/news/investors-reacting-tenet-healthcare-thc-010434224.html",
    sourceType: "news",
    channel: "media",
    headline: "How Investors Are Reacting To Tenet Healthcare (THC) Cigna Dispute Over Abrazo Reimbursement Rates",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Investor-facing coverage. Financial press notes Cigna shares already under pressure from pharmacy-benefit margin warnings (stock fell 17% in Oct). Tenet dispute adds operational risk. Market audience cares about resolution probability.",
  },
  {
    id: 8,
    date: "2025-12-01",
    source: "STAT News",
    url: "https://www.statnews.com/2025/09/29/cigna-downcoding-prior-authorization-doctors-bureaucracy/",
    sourceType: "news",
    channel: "media",
    headline: "An insurance company is introducing a new threat to American medicine — Cigna's downcoding policy",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "CRITICAL CONTEXT. STAT News investigative piece on Cigna's Oct 1 E/M downcoding policy (R49) — auto-reduces physician billing codes. AMA, CMA, and multiple state medical societies pushed back. Cigna paused policy under pressure. Broader evidence of Cigna's aggressive cost-containment posture during contract negotiations.",
  },
  {
    id: 9,
    date: "2025-12-05",
    source: "KTSM (El Paso)",
    url: "https://www.ktsm.com/news/cigna-tenet-healthcares-negotiation-impasse-could-cost-hundreds-of-episd-employees-coverage/",
    sourceType: "tv",
    channel: "media",
    headline: "Cigna, Tenet Healthcare's negotiation impasse could cost hundreds of EPISD employees coverage",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "El Paso Independent School District employees face losing in-network access to Hospitals of Providence (Tenet). Public employer angle amplifies sympathy — school district workers and their families. Same national contract affecting Piedmont.",
  },
  {
    id: 10,
    date: "2025-12-10",
    source: "localmemphis.com",
    url: "https://www.localmemphis.com/article/news/local/if-no-deal-is-struck-between-st-francis-hospital-and-cigna-healthcare-some-patients-may-pay-the-price/522-b616c8ed-65bb-40bb-889d-9187886b21ae",
    sourceType: "tv",
    channel: "media",
    headline: "Cigna Healthcare responds to claims over contract dispute with St. Francis Hospital — 'stoking fear as a negotiating tactic'",
    frameAdoption: "cigna",
    sentiment: "negative_piedmont",
    patientStory: false,
    blameDirection: "piedmont",
    reachEstimate: "medium",
    notes: "RARE CIGNA-FAVORABLE FRAMING. Cigna spokesperson: 'It's disappointing that St. Francis Hospital's for-profit owner Tenet Healthcare Corporation is stoking fear among patients in Memphis as a negotiating tactic.' Cigna's strongest counter-narrative: Tenet seeking rates 'far beyond what is reasonable.'",
  },
  {
    id: 11,
    date: "2025-12-12",
    source: "Becker's Payer Issues",
    url: "https://www.beckerspayer.com/payer/tenet-cigna-hit-contract-snag-for-memphis-hospitals-6-things-to-know/",
    sourceType: "news",
    channel: "media",
    headline: "Tenet, Cigna hit contract snag for Memphis hospitals: 6 things to know",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press listicle format. Key detail: major Memphis employers (MLGW, Shelby County Government, Shelby County Schools) all offer Cigna plans with Tenet hospitals in-network. Employer vulnerability applies equally to Rock Hill/York County employers using Cigna with Piedmont.",
  },
  {
    id: 12,
    date: "2025-12-15",
    source: "Insurance News Net / South Florida Sun Sentinel",
    url: "https://insurancenewsnet.com/oarticle/disputes-between-major-health-insurers-south-florida-hospitals-threaten-higher-costs-for-patients",
    sourceType: "news",
    channel: "media",
    headline: "Disputes between major health insurers, South Florida hospitals threaten higher costs for patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Palm Beach Health Network (Tenet) angle. 1.3 million Floridians at risk of losing access to two Level I trauma centers and region's only children's hospital. Cigna dispute covered alongside Florida Blue disputes. Multi-front insurer aggression pattern.",
  },
  {
    id: 13,
    date: "2025-12-18",
    source: "WRHI (Rock Hill)",
    url: "https://www.wrhi.com/2025/12/release-piedmont-medical-center-puts-out-alert-that-many-patience-will-lose-in-network-access-if-cigna-continues-to-refuse-to-negotiate-on-contract-renewal-208712",
    sourceType: "radio",
    channel: "media",
    headline: "Piedmont Medical Center puts out alert that many patients will lose in-network access if Cigna continues to refuse to negotiate on contract renewal",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "PRIMARY LOCAL COVERAGE. WRHI is Rock Hill's hometown radio/news station. Piedmont framing: 'Cigna continues to refuse to negotiate in good faith.' Notes 282-bed Level III trauma hospital, Level III NICU. Contract expiration Dec 31. Emergency care protected by law regardless. PPO patients can use out-of-network benefits; HMO patients may lose all non-emergent coverage.",
  },
  {
    id: 14,
    date: "2025-12-18",
    source: "WRHI (Rock Hill)",
    sourceType: "radio",
    channel: "media",
    headline: "Local businesses warned: employees who chose Cigna with promise of Piedmont in-network access face disruption",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "EMPLOYER ANGLE in WRHI coverage. Many York County businesses selected Cigna specifically because Piedmont Medical Center was in-network. Those employers now face broken promises to employees. Direct employer-channel pressure on Cigna.",
  },
  {
    id: 15,
    date: "2025-12-20",
    source: "Hoodline / KSAT San Antonio",
    url: "https://hoodline.com/2025/12/san-antonio-braces-for-hospital-shakeup-as-cigna-contract-clock-ticks-down/",
    sourceType: "news",
    channel: "media",
    headline: "San Antonio Families Face Health Coverage Risk Over Cigna Deal — 1.4 million Texas families at risk",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Baptist Health System (Tenet) in San Antonio. 1.4 million Texas families could be placed out of network. Massive scale number reinforces that Piedmont's situation is part of Cigna's nationwide aggression against Tenet facilities.",
  },
  {
    id: 16,
    date: "2025-12-22",
    source: "Becker's ASC Review",
    url: "https://www.beckersasc.com/asc-coding-billing-and-collections/the-deadline-is-here-tenet-s-outpatient-facilities-will-go-out-of-network-if-cigna-contract-expires.html",
    sourceType: "news",
    channel: "media",
    headline: "The deadline is here: Tenet's outpatient facilities will go out of network if Cigna contract expires",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "ASC-focused trade press. Emphasizes that ~370 ambulatory surgery centers are at stake — not just hospitals. Piedmont's ambulatory/outpatient network in York County included. Cigna insists on state-based contracts vs Tenet's preferred national deal.",
  },
  {
    id: 17,
    date: "2025-12-27",
    source: "CBS12 (West Palm Beach)",
    url: "https://cbs12.com/news/local/tenet-and-cigna-reach-agreement-to-keep-palm-beach-health-network-in-network-for-patients-south-florida-news-palm-beach-county-january-1-2026",
    sourceType: "tv",
    channel: "media",
    headline: "Tenet and Cigna reach agreement to keep Palm Beach Health Network in-network for patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Early resolution signal from Florida market. Palm Beach agreement preserves access to two Level I trauma centers and children's hospital for 1.3M Floridians. Suggests national deal taking shape — positive signal for Piedmont.",
  },
  {
    id: 18,
    date: "2025-12-29",
    source: "KSAT (San Antonio)",
    url: "https://www.ksat.com/news/local/2025/12/29/baptist-health-cigna-contract-dispute-could-lead-to-disruption-in-care/",
    sourceType: "tv",
    channel: "media",
    headline: "Baptist Health, Cigna reach agreement to keep patients in-network — Texas families relieved",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Texas Baptist Health (Tenet) resolution. 1.4M families no longer at risk. Pattern of market-by-market announcements ahead of Dec 31 national deadline. Piedmont's situation still unresolved at this point.",
  },
  {
    id: 19,
    date: "2025-12-31",
    source: "Becker's Payer Issues",
    url: "https://www.beckerspayer.com/contracting/tenet-cigna-tensions-heat-up-as-contract-deadline-nears/",
    sourceType: "news",
    channel: "media",
    headline: "Cigna, Tenet reach agreement after tense negotiations — national contract preserved",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "RESOLUTION. Cigna spokesperson confirmed Dec 31. Agreement covers Tenet hospitals, physicians, and ASCs. No interruption in coverage. 11 months of negotiations. Terms not disclosed. Negotiations centered on prior authorization safeguards, physician-led medical decisions, and fair emergency reimbursement.",
  },
  {
    id: 20,
    date: "2025-12-31",
    source: "Healthcare Finance News",
    url: "https://www.healthcarefinancenews.com/news/tenet-and-cigna-reach-multi-year-contract-agreement",
    sourceType: "news",
    channel: "media",
    headline: "Tenet and Cigna reach multi-year contract agreement — uninterrupted in-network access",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press resolution. Multi-year deal. Cigna commercial customers retain uninterrupted access. All Tenet facilities remain in-network for Cigna-HealthSpring Medicare Advantage. Terms not released. Piedmont Medical Center included in national resolution.",
  },
  // === PIEDMONT / TENET OWNED MEDIA ===
  {
    id: 21,
    date: "2025-11-01",
    source: "KeepYourHealthcareAccess.com (Tenet campaign site)",
    url: "https://www.keepyourhealthcareaccess.com/",
    sourceType: "owned",
    channel: "media",
    headline: "Tenet launches KeepYourHealthcareAccess.com — patient petition and advocacy campaign against Cigna",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "National advocacy website with local market contact info for Cigna leaders. Online petition for patients to sign. FAQ explains out-of-network implications. Piedmont Medical Center directed patients to this site. Aggressive public-pressure campaign — unusual scale for hospital system.",
  },
  {
    id: 22,
    date: "2025-12-18",
    source: "Piedmont Medical Center (press release via WRHI)",
    sourceType: "owned",
    channel: "media",
    headline: "Piedmont Medical Center: 'Cigna has refused reasonable rate increases' — patients urged to act",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Official Piedmont Medical Center statement. Key framing: Cigna 'refusing to negotiate in good faith.' 282-bed Level III trauma hospital with Level III NICU serving York County and beyond. Patients directed to KeepYourHealthcareAccess.com to urge Cigna to keep providers in-network.",
  },
  {
    id: 23,
    date: "2025-12-18",
    source: "PiedmontMedicalCenter.com (network interruption notice)",
    sourceType: "owned",
    channel: "media",
    headline: "Piedmont Medical Center posts Cigna network interruption alert on hospital website",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Website banner for Cigna plan members. Links to potential network interruption info. Patient-facing communication coordinated with national Tenet campaign. Covers both Rock Hill and Fort Mill facilities.",
  },
  {
    id: 24,
    date: "2025-12-20",
    source: "KeepYourHealthcareAccess.com FAQ",
    url: "https://www.keepyourhealthcareaccess.com/faq/",
    sourceType: "owned",
    channel: "media",
    headline: "Tenet FAQ: 'If Tenet becomes out-of-network, Cigna may cover less or none of the cost of care'",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "FAQ details: out-of-pocket costs may increase significantly, fewer choices for in-network care. Tenet's position: Cigna's offer 'well below inflation' and would 'reduce reimbursement for physicians and ambulatory surgery centers.' Meanwhile Cigna reported premium revenue increases of 10% per member for employer products.",
  },
  // === CIGNA OWNED MEDIA ===
  {
    id: 25,
    date: "2025-12-10",
    source: "Cigna Healthcare (public statement)",
    sourceType: "owned",
    channel: "media",
    headline: "Cigna: Tenet seeking rates 'far beyond what is reasonable' — would make hospitals 'much more expensive than other local facilities'",
    frameAdoption: "cigna",
    sentiment: "negative_piedmont",
    patientStory: false,
    blameDirection: "piedmont",
    reachEstimate: "medium",
    notes: "Cigna's primary counter-narrative. Frames Tenet/Piedmont as demanding excessive rate hikes that exceed inflation. Claims commitment to 'market-competitive rates.' Accuses Tenet of 'stoking fear among patients as a negotiating tactic.' Corporate defensive tone. No patient voices.",
  },
  {
    id: 26,
    date: "2025-12-15",
    source: "Cigna Healthcare (employer communications)",
    sourceType: "owned",
    channel: "employer",
    headline: "Cigna notifies employers: Tenet/Piedmont facilities may leave network Jan 1 — Tenet demanding above-inflation increases",
    frameAdoption: "cigna",
    sentiment: "negative_piedmont",
    patientStory: false,
    blameDirection: "piedmont",
    reachEstimate: "high",
    notes: "Employer notification channel. Cigna frames to self-insured employers: Tenet's rate demands would increase employer costs beyond inflation. Self-insured employer plans would lose access immediately with no transition period. Key employer-pressure tactic.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 27,
    date: "2025-12-18",
    source: "Social media (York County patients)",
    sourceType: "social",
    channel: "social",
    headline: "York County patients share concerns about losing Piedmont in-network access on Facebook community groups",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Local Facebook community groups in Rock Hill, Fort Mill, and York County. Patients express anxiety about losing access to only major hospital in immediate area. Rural/suburban SC community has fewer alternatives than urban markets. Piedmont is the dominant healthcare provider in York County.",
  },
  {
    id: 28,
    date: "2025-12-19",
    source: "Social media (Rock Hill community)",
    sourceType: "social",
    channel: "social",
    headline: "Rock Hill residents react to Piedmont/Cigna news: 'Where are we supposed to go?'",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "GEOGRAPHIC VULNERABILITY. Unlike urban markets with multiple hospital options, Rock Hill/York County residents have limited alternatives. Nearest comparable facilities in Charlotte require crossing state lines into NC. 'Where are we supposed to go?' captures the unique anxiety of patients in single-hospital communities.",
  },
  {
    id: 29,
    date: "2025-12-20",
    source: "X/Twitter (Tenet/Cigna national conversation)",
    sourceType: "social",
    channel: "social",
    headline: "National Tenet/Cigna dispute drives social media engagement across all affected markets",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "National social conversation aggregates patient anxiety from AZ, FL, TX, TN, SC, and other Tenet markets. Anti-insurer sentiment elevated. Cigna's simultaneous disputes with UNC Health, Allegheny Health Network, and others compound negative perception.",
  },
  {
    id: 30,
    date: "2025-12-22",
    source: "Social media (NICU parents)",
    sourceType: "social",
    channel: "social",
    headline: "Parents of NICU babies at Piedmont express fear over potential Cigna coverage loss",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Piedmont Medical Center operates a Level III NICU — advanced neonatal care. Parents of premature or critically ill infants face devastating prospect of losing in-network access. NICU families are maximally sympathetic — rivals cancer patients in emotional impact. Piedmont's NICU serves broad region.",
  },
  {
    id: 31,
    date: "2025-12-25",
    source: "Social media (holiday timing anger)",
    sourceType: "social",
    channel: "social",
    headline: "Patients angered by Dec 31 deadline during holidays: 'Cigna is ruining Christmas with healthcare anxiety'",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Holiday timing amplifies public anger. Families dealing with contract uncertainty between Christmas and New Year's. Open enrollment already passed for many — patients feel trapped. Year-end deadline creates maximum emotional pressure.",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 32,
    date: "2025-10-30",
    source: "Cigna Q3 2025 earnings — margin pressure disclosure",
    url: "https://invezz.com/news/2025/10/30/cigna-shares-plunge-as-company-warns-of-margin-pressure-in-pharmacy-benefit-unit/",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Cigna warns of margin pressure in pharmacy unit — stock falls 17%; aggressive cost containment strategy evident",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "STRUCTURAL CONTEXT. Cigna shares tumbled 17% after CEO David Cordani warned of margin pressure in Express Scripts PBM division. Medical loss ratio rose to 84.8% from 82.8%. Under intense investor pressure to control costs — provides context for aggressive reimbursement posture with Tenet/Piedmont.",
  },
  {
    id: 33,
    date: "2025-10-01",
    source: "Cigna E/M downcoding policy (R49)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Cigna launches E/M downcoding policy, auto-reducing physician billing codes — paused after AMA pushback",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "PATTERN EVIDENCE. Cigna's Oct 1 policy auto-downcodes physician E/M visits, reducing reimbursement. AMA, state medical societies, and CA DMHC pushed back. Policy paused under pressure. Demonstrates Cigna's systematic approach to reducing provider payments — same dynamic driving Tenet/Piedmont contract dispute.",
  },
  {
    id: 34,
    date: "2025-10-07",
    source: "Cigna $5.7M ghost network settlement",
    url: "https://www.pollockcohen.com/media/media-mentions/2025-10-07-cigna-agrees-to-5.7-million-settlement-in-ghost-network-class-action",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Cigna agrees to $5.7M settlement over 'ghost network' allegations — inaccurate provider directories",
    frameAdoption: "balanced",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "ERISA class action. Cigna settled claims of misleading members with inaccurate provider directories — listing out-of-network providers as in-network. Ironic context: Cigna's own directory accuracy under legal challenge while simultaneously threatening to remove real in-network providers like Piedmont.",
  },
  {
    id: 35,
    date: "2025-12-01",
    source: "Cigna/UNC Health dispute — parallel in neighboring NC",
    sourceType: "news",
    channel: "stakeholder",
    headline: "UNC Health and Cigna let contract expire Nov 30 — 65,000 NC patients forced out of network",
    frameAdoption: "balanced",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "CRITICAL PARALLEL. UNC Health (just across state line in NC) let Cigna contract expire Nov 30. 65,000 patients lost in-network access. Cigna claimed UNC demanding 40% increase. Eventually resolved retroactively to Dec 1. Rock Hill patients could see Charlotte/UNC coverage disrupted simultaneously. WRAL covered extensively including parents of critically ill baby.",
  },
  {
    id: 36,
    date: "2025-07-01",
    source: "Cigna/Allegheny Health Network dispute — parallel",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Allegheny Health Network and Cigna resolve contract dispute after June 30 deadline — 20,000 patients affected",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "PATTERN: Cigna's second dispute with Allegheny Health in two years. 3-year deal through June 2028. 20,000 affected members. Pattern of serial Cigna disputes across the country undermines 'Piedmont is uniquely unreasonable' framing.",
  },
  {
    id: 37,
    date: "2025-12-18",
    source: "Piedmont Medical Center (community statement)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Piedmont: 'Thousands of families are left in limbo, hoping Cigna will put patients first, not profits'",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Piedmont's most emotionally charged public statement. 'Patients first, not profits' is devastating framing against a for-profit insurer. Notes Cigna's 'refused reasonable rate increases.' Hospital positions itself as community advocate against corporate insurer.",
  },
  {
    id: 38,
    date: "2025-12-20",
    source: "Tenet Healthcare national negotiation update",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Tenet: Cigna's proposal would 'put patient care and access at risk' — rates below inflation, physician reimbursement cuts",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Tenet's national-level statement. Key data point: Cigna reporting 10% premium revenue increases per member for employer products while proposing below-inflation rate increases to hospitals. Asymmetry argument: Cigna raises premiums but refuses to pay providers fairly.",
  },
  {
    id: 39,
    date: "2025-12-31",
    source: "Cigna spokesperson (resolution statement)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Cigna confirms agreement with Tenet: 'continue providing in-network healthcare with no interruption'",
    frameAdoption: "cigna",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Cigna's resolution statement. Concise corporate language. 'No interruption' suggests Cigna claiming credit for continuity despite being the party threatening to terminate. Contrast with Tenet's relief framing.",
  },
  {
    id: 40,
    date: "2025-12-22",
    source: "19 Tenet hospitals vs Cigna lawsuit (background)",
    url: "https://www.beckerspayer.com/payer/19-tenet-hospitals-sue-cigna-over-alleged-low-reimbursement-rates-denied-claims/",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Background: 19 Tenet hospitals previously sued Cigna over low reimbursement and denied emergency claims",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "HISTORICAL CONTEXT. Tenet hospitals in AZ, FL, TN, AL, SC, and MA sued Cigna for 'ongoing pattern of financial misconduct' — reimbursing at artificially low rates and arbitrarily denying emergency care claims. South Carolina hospitals included in the lawsuit. Pattern of Cigna underpayment predates current contract dispute.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 41,
    date: "2025-11-15",
    source: "Tenet broker advisory",
    sourceType: "owned",
    channel: "employer",
    headline: "Tenet urges brokers to alert employer clients about 'potential disruption ahead of open enrollment'",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Critical employer channel activation. Tenet encouraged benefits brokers to warn employer clients and help them 'evaluate alternative health plans.' Timing during open enrollment season maximizes pressure — employers considering switching away from Cigna entirely.",
  },
  {
    id: 42,
    date: "2025-12-05",
    source: "KTSM (El Paso) — EPISD employer story",
    sourceType: "tv",
    channel: "employer",
    headline: "El Paso school district employees face losing hospital coverage — hundreds of EPISD staff affected",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Public school district as affected employer. School workers — sympathetic, modest-income workforce. Hospitals of Providence (Tenet) is key provider. Same dynamic applies to York County school districts and public employers using Cigna with Piedmont in-network.",
  },
  {
    id: 43,
    date: "2025-12-18",
    source: "York County employer impact (WRHI reporting)",
    sourceType: "news",
    channel: "employer",
    headline: "Local businesses warned: employees chose Cigna plans with promise of Piedmont access that may disappear",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "WRHI coverage highlights employer impact. Many York County businesses selected Cigna specifically because Piedmont was in-network. City of Rock Hill offers Cigna dental plans. Small/mid-size employers in Rock Hill, Fort Mill, and York have limited leverage but significant employee anxiety.",
  },
  {
    id: 44,
    date: "2025-12-10",
    source: "Memphis employer impact (MLGW, Shelby County)",
    sourceType: "news",
    channel: "employer",
    headline: "Major Memphis employers with Cigna plans face St. Francis disruption — MLGW, County Government, Schools affected",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Memphis public employers as parallel case. MLGW (Memphis Light Gas and Water), Shelby County Government, and Shelby County Schools all offer Cigna with Tenet's St. Francis in-network. Pattern evidence that employer disruption is a national Cigna/Tenet issue, not Piedmont-specific.",
  },
  {
    id: 45,
    date: "2025-12-20",
    source: "Benefits broker communications (York County)",
    sourceType: "news",
    channel: "employer",
    headline: "Local insurance brokers advise York County employers on Piedmont/Cigna disruption contingency planning",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Benefits brokers serving Rock Hill/Fort Mill/York employers issue advisories. Open enrollment already closed for many employers — limited options for mid-year plan changes. Employer frustration directed at Cigna for creating uncertainty after enrollment decisions were locked in.",
  },
  // === ADDITIONAL MEDIA ===
  {
    id: 46,
    date: "2025-12-28",
    source: "iHeart Radio Florida affiliates",
    url: "https://wiod.iheart.com/featured/florida-news/content/2026-01-02-more-than-million-floridians-saved-from-losing-coverage-at-7-hospitals/",
    sourceType: "radio",
    channel: "media",
    headline: "More Than A Million Floridians Saved From Losing Coverage At 7 Hospitals — Tenet/Cigna deal",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Syndicated across iHeart Florida affiliates (WIOD, WJNO, Real Radio 92.1, 95.3 WDAE). 'Saved from losing coverage' framing implies Cigna was threatening access. Resolution coverage still carries anti-insurer undertone. Broad radio reach.",
  },
  {
    id: 47,
    date: "2025-12-30",
    source: "RTT News / MarketScreener",
    url: "https://www.rttnews.com/473014/tenet-healthcare-reaches-multi-year-deal-with-cigna-to-expand-its-network.aspx",
    sourceType: "news",
    channel: "media",
    headline: "Tenet Healthcare Reaches Agreement With Cigna Corporation on Multi-Year Contract",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Financial wire service. Investor audience. Multi-year agreement confirmed. No terms disclosed. Covers all Tenet facilities including Piedmont Medical Center. Stock market angle — resolves uncertainty for THC and CI shareholders.",
  },
  {
    id: 48,
    date: "2025-12-31",
    source: "HealthLeaders Media",
    url: "https://www.healthleadersmedia.com/finance/tenet-cigna-ink-multi-year-deal",
    sourceType: "news",
    channel: "media",
    headline: "Tenet, Cigna Ink Multi-Year Deal — uninterrupted access preserved",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Healthcare executive audience. Resolution framing. Notes deal reached on the deadline day — brinksmanship from both sides. Terms undisclosed.",
  },
  {
    id: 49,
    date: "2025-12-18",
    source: "Piedmont Medical Center (NICU and community services context)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Piedmont Medical Center — 282-bed Level III trauma center, Level III NICU, heart/vascular center — community's primary hospital",
    frameAdoption: "piedmont",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "COMMUNITY CONTEXT. Piedmont serves York County as primary acute care hospital since 1983. Level III trauma, Level III NICU, comprehensive heart/vascular center. Fort Mill campus (100 beds, opened Sept 2022). Freestanding ED in Fort Mill. Dominant provider in fast-growing Charlotte metro exurb. Losing in-network access would devastate community healthcare infrastructure.",
  },
  {
    id: 50,
    date: "2025-12-22",
    source: "Social media (Charlotte metro spillover)",
    sourceType: "social",
    channel: "social",
    headline: "Charlotte-area social media discusses Piedmont/Cigna dispute — Rock Hill patients part of greater Charlotte healthcare market",
    frameAdoption: "piedmont",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Rock Hill is part of the greater Charlotte metropolitan area. Charlotte social media users discuss Piedmont dispute alongside UNC Health/Cigna dispute across state line. Double disruption: SC patients losing Piedmont AND potentially facing UNC Health/Cigna issues if seeking care in NC. Cigna's multi-front war creates compounding anxiety.",
  },
];

const LABELS = {
  frameAdoption: { piedmont: "Piedmont Frame", cigna: "Cigna Frame", balanced: "Balanced" },
  sentiment: {
    negative_cigna: "Anti-Cigna",
    negative_piedmont: "Anti-Piedmont",
    neutral: "Neutral",
    positive_cigna: "Pro-Cigna",
    positive_piedmont: "Pro-Piedmont",
  },
  blameDirection: { cigna: "Blames Cigna", piedmont: "Blames Piedmont", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National record (1.5)
  "STAT News": 1.5, "Healthcare Finance News": 1.5, "Yahoo Finance": 1.5, "NBC News": 1.5,
  "Insurance News Net / South Florida Sun Sentinel": 1.5,
  // Tier 2 — Regional authority (1.2)
  "WRHI (Rock Hill)": 1.2, "KSAT (San Antonio)": 1.2, "CBS12 (West Palm Beach)": 1.2,
  "ABC15 Arizona": 1.2, "KTSM (El Paso)": 1.2, "localmemphis.com": 1.2,
  "Hoodline / KSAT San Antonio": 1.2, "iHeart Radio Florida affiliates": 1.2,
  // Tier 3 — Trade/niche (1.0)
  "Becker's Hospital Review": 1.0, "Becker's Payer Issues": 1.0, "Becker's ASC Review": 1.0,
  "FTI Consulting (Payer-Provider Dispute Tracker)": 1.0,
  "Healthcare Uncovered (Wendell Potter Substack)": 1.0,
  "HealthLeaders Media": 1.0, "RTT News / MarketScreener": 1.0,
  // Tier 4 — Organic social (0.7)
  "Social media (York County patients)": 0.7, "Social media (Rock Hill community)": 0.7,
  "X/Twitter (Tenet/Cigna national conversation)": 0.7, "Social media (NICU parents)": 0.7,
  "Social media (holiday timing anger)": 0.7, "Social media (Charlotte metro spillover)": 0.7,
  // Tier 5 — Comment sections (0.4)
  // (none tracked)
  // Tier 6 — Owned/party media (0.3)
  "KeepYourHealthcareAccess.com (Tenet campaign site)": 0.3,
  "Piedmont Medical Center (press release via WRHI)": 0.3,
  "PiedmontMedicalCenter.com (network interruption notice)": 0.3,
  "KeepYourHealthcareAccess.com FAQ": 0.3,
  "Cigna Healthcare (public statement)": 0.3, "Cigna Healthcare (employer communications)": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "Cigna Q3 2025 earnings — margin pressure disclosure": 1.3,
  "Cigna E/M downcoding policy (R49)": 1.3,
  "Cigna $5.7M ghost network settlement": 1.3,
  "Cigna/UNC Health dispute — parallel in neighboring NC": 1.3,
  "Cigna/Allegheny Health Network dispute — parallel": 1.3,
  "Piedmont Medical Center (community statement)": 1.3,
  "Tenet Healthcare national negotiation update": 1.3,
  "Cigna spokesperson (resolution statement)": 1.3,
  "19 Tenet hospitals vs Cigna lawsuit (background)": 1.3,
  "Piedmont Medical Center (NICU and community services context)": 1.3,
  // Tier 8 — Employer/Benefits (1.5x trade, 1.8x consultant)
  "Tenet broker advisory": 1.5, "KTSM (El Paso) — EPISD employer story": 1.5,
  "York County employer impact (WRHI reporting)": 1.5,
  "Memphis employer impact (MLGW, Shelby County)": 1.5,
  "Benefits broker communications (York County)": 1.0,
};

const SEARCH_TRENDS = [
  { week: "2025-10-06", interest: 2 }, { week: "2025-10-13", interest: 3 }, { week: "2025-10-20", interest: 5 },
  { week: "2025-10-27", interest: 6 }, { week: "2025-11-03", interest: 10 }, { week: "2025-11-10", interest: 12 },
  { week: "2025-11-17", interest: 15 }, { week: "2025-11-24", interest: 20 }, { week: "2025-12-01", interest: 30 },
  { week: "2025-12-08", interest: 45 }, { week: "2025-12-15", interest: 70 }, { week: "2025-12-22", interest: 90 },
  { week: "2025-12-29", interest: 100 },
];

export default {
  // Identity
  providerKey: "piedmont",
  payorKey: "cigna",
  providerName: "Piedmont Medical Center",
  payorName: "Cigna Healthcare",
  providerShort: "Piedmont",
  payorShort: "Cigna",
  navShort: "Piedmont v. Cigna",
  title: "Piedmont Medical Center vs Cigna (SC)",
  subtitle: "Contract dispute · Resolved December 31, 2025",
  gradientId: "piedmontcigna",

  // Dates
  monitorStart: "October 1, 2025",
  monitorEnd: "December 31, 2025",
  disputePublicDate: "2025-12-18",

  // Colors
  colors: {
    providerColor: "#1B6B3A",
    payorColor: "#E85D1A",
    neutral: "#64748B",
    accent: "#1B6B3A",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#1B6B3A", "#5A7568", "#E85D1A"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"piedmont medical center cigna" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.82,
    nationalMedian: 1.0,
    networkComplaints: 1423,
    priorYearComplaints: 967,
    regulatorAction: "South Carolina Department of Insurance did not publicly intervene. No formal investigation opened. SC has limited surprise billing protections compared to states with stronger consumer protection frameworks. Emergency care coverage protected by federal law regardless of network status.",
    signalRead: "Cigna's national complaint index is elevated (1.82x median) driven by multi-state provider disputes in 2025. The 47% increase in network complaints reflects Cigna's aggressive posture across Tenet markets and parallel disputes with UNC Health, Allegheny Health Network, ProMedica, and Jefferson Health. Cigna's simultaneous E/M downcoding controversy and $5.7M ghost network settlement compound reputational risk.",
  },

  // Executive summary
  executiveSummary: {
    statement: "The dispute resolved via the national Tenet/Cigna multi-year agreement confirmed December 31, 2025 — no actual disruption occurred for Piedmont patients, but the 11-month negotiation and holiday-season brinkmanship generated significant community anxiety in York County.",
    keyMessages: [
      "Piedmont Medical Center is York County's dominant healthcare provider (282-bed Level III trauma, Level III NICU) — losing in-network access would devastate a community with limited alternatives.",
      "The dispute was part of a massive national Tenet/Cigna standoff affecting 64 hospitals, ~370 ASCs, and 2,000+ providers across the country — Piedmont was one local front in a corporate-level war.",
      "Cigna's simultaneous disputes with UNC Health (65,000 patients, contract lapsed Nov 30), Allegheny Health, and others demonstrate a pattern of aggressive cost containment across 2025.",
      "Cigna's investor pressure (stock -17% on margin warnings, rising MLR of 84.8%) provides context for why they pushed such aggressive reimbursement terms against hospital systems.",
    ],
    marcomm: [
      "<strong>Single-hospital communities are uniquely vulnerable.</strong> Unlike NYC (MSK/UHC) or other urban disputes where patients have alternatives, Rock Hill residents depend on Piedmont. 'Where are we supposed to go?' is the defining question — and Cigna has no good answer.",
      "<strong>The national Tenet campaign was unusually aggressive.</strong> KeepYourHealthcareAccess.com, the 'unsure-ance' branding, broker mobilization, and patient petitions represent a coordinated corporate PR offensive that exceeded typical hospital system dispute tactics.",
      "<strong>Holiday timing amplified public anger.</strong> A December 31 deadline during the holiday season — after open enrollment had closed — trapped patients and employers with no recourse. This timing maximized anti-Cigna sentiment.",
      "<strong>Cross-border compounding risk for Rock Hill.</strong> With Cigna's UNC Health contract also disrupted (Nov 30 expiration), Rock Hill patients faced the prospect of losing access to BOTH Piedmont (SC) and UNC facilities (NC) simultaneously — a unique geographic vulnerability.",
    ],
  },
  channelTakeaways: {
    media: [
      "WRHI was the primary local outlet — Rock Hill's hometown radio station carried the press release and employer impact angle directly.",
      "National trade press (Becker's, Healthcare Finance News, HealthLeaders) covered the dispute extensively as part of the broader Tenet/Cigna standoff across multiple Becker's verticals.",
      "ABC15 Arizona and KSAT San Antonio coverage of parallel Tenet markets (413K AZ enrollees, 1.4M TX families) established the scale that put Piedmont's situation in national context.",
      "Wendell Potter's Healthcare Uncovered newsletter added credible insider critique of Cigna's ASC reimbursement cuts — former Cigna executive as whistleblower is uniquely damaging.",
    ],
    social: [
      "York County Facebook community groups were the primary social channel — Rock Hill/Fort Mill residents expressed 'where are we supposed to go?' anxiety about limited hospital alternatives.",
      "NICU parent communities generated intense emotional engagement — Piedmont's Level III NICU serves a broad region with few alternatives for advanced neonatal care.",
      "Charlotte metro social media amplified the dispute as Rock Hill patients recognized cross-border compounding risk with UNC Health/Cigna disruption in NC.",
      "Holiday timing (Christmas-to-New-Year's deadline) drove organic anger on social platforms — 'Cigna is ruining Christmas with healthcare anxiety.'",
    ],
    stakeholder: [
      "Cigna's Q3 2025 earnings revealed margin pressure (stock -17%, MLR 84.8%) — provides structural context for aggressive reimbursement posture against Tenet/Piedmont.",
      "Cigna's E/M downcoding policy (paused after AMA pushback) and $5.7M ghost network settlement compound reputational damage during the dispute period.",
      "The 19-hospital Tenet vs Cigna lawsuit (including SC facilities) for 'pattern of financial misconduct' provides historical evidence of Cigna underpayment practices.",
      "Parallel Cigna disputes with UNC Health (65K patients), Allegheny Health (20K patients), and others create pattern evidence of serial insurer aggression in 2025.",
    ],
    employer: [
      "York County employers who selected Cigna specifically for Piedmont in-network access faced broken promises to employees — direct trust damage to Cigna's employer relationships.",
      "Tenet's broker advisory urged employers to 'evaluate alternative health plans' — active campaign to encourage employer defection from Cigna during open enrollment.",
      "EPISD (El Paso) and Memphis public employer stories (MLGW, Shelby County Schools) demonstrate that employer disruption was a national Tenet/Cigna pattern, not Piedmont-specific.",
      "Open enrollment had already closed for many employers when the December deadline approached — employers and employees felt trapped with no ability to switch plans.",
    ],
  },
  arguments: {
    payor: [
      { phase: "Early (Oct–Nov 2025)", points: ["Positioned Tenet as seeking rates <strong>'far beyond what is reasonable'</strong> for a for-profit hospital chain", "Accused Tenet/Piedmont of <strong>'stoking fear among patients as a negotiating tactic'</strong>", "Insisted on state-based contracts vs Tenet's preferred national deal — complicating local resolution"] },
      { phase: "Deadline Pressure (Dec 2025)", points: ["Launched 'Save Our Healthcare' counter-messaging — but Cigna's corporate tone was less effective than Tenet's patient-access framing", "Cigna shares already under pressure from pharmacy-benefit margin warnings (stock fell 17% in Oct) — financial headwinds limited Cigna's leverage"] },
      { phase: "Resolution (Dec 2025)", points: ["National Tenet/Cigna agreement on December 31 included Piedmont Medical Center — no interruption in coverage", "Multi-year deal with terms not disclosed; negotiations centered on prior authorization and fair emergency reimbursement"] },
    ],
    provider: [
      { phase: "Early (Oct–Nov 2025)", points: ["Piedmont framed Cigna as <strong>'refusing to negotiate in good faith'</strong> on rate increases for its 282-bed Level III trauma hospital", "Tenet's national 'unsure-ance' campaign applied locally: <strong>'If you have Cigna, you have health unsureance'</strong>", "FTI data showed Cigna among <strong>most active insurers in disputes</strong> nationally — 51 (2022) to 133 (2024) — normalizing Piedmont's position"] },
      { phase: "Escalation (Dec 2025)", points: ["WRHI (Rock Hill hometown radio) coverage that local businesses <strong>chose Cigna specifically because Piedmont was in-network</strong> — broken promise framing", "Cited Cigna's <strong>rate offers 'well below inflation'</strong> and proposed <strong>cuts to physician and ASC reimbursement</strong>", "Wendell Potter (former Cigna executive turned whistleblower) lent powerful insider credibility to Piedmont's position", "Directed patients to KeepYourHealthcareAccess.com — coordinated with national Tenet campaign"] },
      { phase: "Resolution (Dec 2025)", points: ["Included in national Tenet/Cigna resolution December 31 — multi-year deal preserved in-network access", "York County employers and patients avoided disruption as market-by-market deals (Palm Beach, San Antonio) built momentum toward deadline"] },
    ],
  },
  timeline: [
    { date: "2025-10-15", type: "newsBreak", label: "News breaks publicly" },
    { date: "2025-12-31", type: "termination", label: "Contract set to terminate" },
    { date: "2025-12-31", type: "agreement", label: "Agreement reached" },
  ],
};
