// Providence Health vs Aetna — PR War Room Config
// Multi-state dispute: WA (Apr–Sep 2024), NorCal (Aug–Sep 2024), Oregon (Dec 2024–Dec 2025).
// Oregon dispute resolved December 4, 2025 (effective Dec 1, 2025).

const ENTRIES = [
  // ===================================================================
  //  PHASE 1 — WASHINGTON STATE (Aug–Sep 2024)
  // ===================================================================

  // === MEDIA ENTRIES — WA ===
  {
    id: 1,
    date: "2024-08-28",
    source: "Seattle Times",
    sourceType: "news",
    channel: "media",
    headline: "Providence, Aetna fail to reach deal — ~35,000 WA patients face Sept 1 disruption",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "First major coverage. Seattle Times is the paper of record for WA. Providence announced impasse publicly. Key framing: 35,000 patients at risk across Providence, Swedish, Kadlec, PacMed, St. Luke's Rehab. Providence CFO Greg Hoffman quoted: 'For-profit insurers like Aetna continue to reap benefits of multi-year contracts.' Negotiations ongoing since April 2024.",
  },
  {
    id: 2,
    date: "2024-08-29",
    source: "Spokesman-Review",
    sourceType: "news",
    channel: "media",
    headline: "Thousands of Eastern WA patients could lose in-network access as Providence-Aetna talks stall",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Spokane-based paper. Eastern WA angle — Kadlec Regional Medical Center in Richland is the dominant provider in Tri-Cities. Losing Kadlec in-network would be devastating for rural patients with few alternatives.",
  },
  {
    id: 3,
    date: "2024-08-29",
    source: "KIRO 7 (CBS Seattle)",
    sourceType: "tv",
    channel: "media",
    headline: "Providence warns Aetna patients: find new providers or face out-of-network costs starting Sept 1",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "Major Seattle TV. Patient anxiety stories. 'Find new providers' framing creates immediate fear. Providence facilities are deeply embedded in WA healthcare infrastructure.",
  },
  {
    id: 4,
    date: "2024-08-29",
    source: "KING 5 (NBC Seattle)",
    sourceType: "tv",
    channel: "media",
    headline: "35,000 WA patients caught in Providence-Aetna contract dispute — Sept 1 deadline looms",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "NBC affiliate. '35,000 patients caught' frames patients as victims. Both sides quoted but Providence's patient-impact framing dominates visual storytelling.",
  },
  {
    id: 5,
    date: "2024-08-30",
    source: "FOX 13 Seattle",
    sourceType: "tv",
    channel: "media",
    headline: "Providence-Aetna standoff: WA insurance commissioner issues briefing as deadline nears",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "FOX 13 covers OIC briefing memo issuance. Regulatory intervention angle adds gravity. WA OIC engagement signals state concern about patient disruption.",
  },
  {
    id: 6,
    date: "2024-08-29",
    source: "MyNorthwest",
    sourceType: "news",
    channel: "media",
    headline: "Providence Health could drop Aetna insurance — what WA patients need to know",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Regional digital outlet. 'Drop Aetna' framing places initiative with Providence but blame on Aetna for forcing the choice.",
  },
  {
    id: 7,
    date: "2024-08-29",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "Providence, Aetna contract negotiations stall — 35,000 patients at risk in Washington",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National trade press. Hospital executive audience. Notes Providence's $1.2B operating loss (2023) and costs up 26% since 2019. Aetna's 'unreasonable rate increases' counter-claim also included.",
  },
  {
    id: 8,
    date: "2024-08-30",
    source: "Snohomish County Tribune",
    sourceType: "news",
    channel: "media",
    headline: "Swedish Medical patients in Snohomish County brace for Aetna network exit",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Hyperlocal suburban coverage. Swedish Medical Center (Providence subsidiary) is major Snohomish County provider. Local patient anxiety stories.",
  },
  {
    id: 9,
    date: "2024-09-01",
    source: "Seattle Times",
    sourceType: "news",
    channel: "media",
    headline: "Providence-Aetna contract expires — deadline passes with no deal, talks continue",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "Deadline-day coverage. Urgency framing. Providence $1.2B operating loss cited as context for why rate increases are necessary.",
  },
  {
    id: 10,
    date: "2024-09-03",
    source: "Seattle Times",
    sourceType: "news",
    channel: "media",
    headline: "Providence and Aetna reach new multiyear agreement — 35,000 Washingtonians keep in-network care",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution coverage. Deal reached after brief 2-day lapse. Terms undisclosed. Relief framing. 5-day resolution from public disclosure to deal is remarkably fast.",
  },
  {
    id: 11,
    date: "2024-09-03",
    source: "Fierce Healthcare",
    sourceType: "news",
    channel: "media",
    headline: "Providence, Aetna resolve WA contract dispute after brief lapse — deal reached in days",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press resolution. Providence's strategic sequencing (Cigna deal first) noted as effective negotiation tactic. Contrasts sharply with Oregon's year-long dispute ahead.",
  },
  {
    id: 12,
    date: "2024-08-30",
    source: "InsuranceNewsNet",
    sourceType: "news",
    channel: "media",
    headline: "Aetna-Providence contract dispute highlights growing insurer-provider tensions in WA",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Insurance industry press. Insurer audience perspective. CVS/Aetna $3.7B operating income Q2 2024 vs Providence $1.2B loss. Financial contrast is damaging for Aetna's 'affordability' framing.",
  },
  {
    id: 13,
    date: "2024-08-30",
    source: "Healthcare Dive",
    sourceType: "news",
    channel: "media",
    headline: "Providence escalates Aetna dispute in WA, cites 26% cost increase since 2019",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Trade press. 26% cost increase since 2019 is a powerful data point. Healthcare Dive audience is hospital/health system executives.",
  },
  {
    id: 14,
    date: "2024-09-03",
    source: "Daily Chronicle",
    sourceType: "news",
    channel: "media",
    headline: "Providence, Aetna reach deal — 35,000 WA patients keep in-network access",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Local paper resolution coverage. Relief framing.",
  },

  // === PROVIDENCE OWNED MEDIA — WA ===
  {
    id: 15,
    date: "2024-08-28",
    source: "Providence Blog",
    sourceType: "owned",
    channel: "media",
    headline: "Providence announces Aetna contract impasse — 'we cannot accept rates that don't cover the cost of care'",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "First public statement. Sets narrative frame. Key: $1.2B operating loss, costs up 26% since 2019. CFO Greg Hoffman: 'For-profit insurers like Aetna continue to reap benefits of multi-year contracts while costs skyrocket.'",
  },
  {
    id: 16,
    date: "2024-08-28",
    source: "Swedish.org",
    sourceType: "owned",
    channel: "media",
    headline: "Swedish Medical Center: Important information about Aetna insurance changes",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Swedish-specific patient communication. Swedish is the largest nonprofit provider in Seattle metro. Separate website amplifies reach — many patients identify with Swedish brand, not Providence corporate.",
  },
  {
    id: 17,
    date: "2024-09-03",
    source: "Providence Blog",
    sourceType: "owned",
    channel: "media",
    headline: "Providence announces new agreement with Aetna — 'patients will continue to have access'",
    frameAdoption: "providence",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution announcement. Victory framing — 'patients will continue to have access' implies Providence secured the deal that protects patients.",
  },

  // === AETNA OWNED MEDIA — WA ===
  {
    id: 18,
    date: "2024-08-29",
    source: "Aetna (public statement — WA)",
    sourceType: "owned",
    channel: "media",
    headline: "Aetna: Providence demanding 'unreasonable rate increases that would raise costs for employers'",
    frameAdoption: "aetna",
    sentiment: "negative_providence",
    patientStory: false,
    blameDirection: "providence",
    reachEstimate: "medium",
    notes: "Aetna's primary WA public statement. 'Unreasonable rate increases' framing. Employer cost angle targets self-funded plan sponsors. Corporate tone. No patient voices.",
  },

  // === SOCIAL — WA ===
  {
    id: 19,
    date: "2024-08-29",
    source: "X/Twitter (WA patient posts)",
    sourceType: "social",
    channel: "social",
    headline: "WA patients share Providence-Aetna anxiety on social media — 'my hospital is dropping my insurance'",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Organic patient social posts. Providence/Swedish patients discovering the dispute. 5-day window too short for sustained viral moment.",
  },
  {
    id: 20,
    date: "2024-08-30",
    source: "Reddit r/Seattle",
    sourceType: "social",
    channel: "social",
    headline: "Reddit Seattle threads: 'Anyone else just get a letter about losing Swedish access?'",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Reddit community discussion. Swedish brand recognition drives engagement — many Seattleites born at Swedish hospitals. Comments generally blame Aetna/CVS profitability.",
  },
  {
    id: 21,
    date: "2024-08-30",
    source: "UNITE HERE Local",
    sourceType: "social",
    channel: "social",
    headline: "UNITE HERE union alert: Providence-Aetna dispute threatens member healthcare access in WA",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Union mobilization. UNITE HERE represents hospitality/service workers — many with Aetna employer plans. CVS/Aetna $3.7B operating income vs Providence $1.2B loss contrast amplified through labor networks.",
  },

  // === STAKEHOLDERS — WA ===
  {
    id: 22,
    date: "2024-08-30",
    source: "WA Office of the Insurance Commissioner",
    sourceType: "news",
    channel: "stakeholder",
    headline: "WA OIC issues briefing memo on Providence-Aetna dispute — signals regulatory concern",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CRITICAL REGULATORY ACTION. WA OIC issued briefing memo Aug 30 — just 2 days after public disclosure. Speed of response reflects WA's proactive insurance oversight. Regulatory pressure likely accelerated resolution.",
  },
  {
    id: 23,
    date: "2024-08-28",
    source: "Providence CFO Greg Hoffman",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Providence CFO: 'For-profit insurers like Aetna reap benefits of multi-year contracts while our costs have risen 26%'",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "KEY EXECUTIVE QUOTE. Hoffman's framing is Providence's stickiest message: for-profit insurer profitability vs nonprofit provider losses. $1.2B operating loss vs CVS/Aetna $3.7B Q2 operating income. This contrast ran across all media coverage.",
  },
  {
    id: 24,
    date: "2024-08-28",
    source: "Providence strategic sequencing (Cigna deal)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Providence publicly resolves Cigna deal first — strategically isolates Aetna as the holdout insurer",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "STRATEGIC MOVE. Providence publicized Cigna deal resolution before Aetna deadline — 'we can make deals with reasonable insurers.' Classic negotiation isolation tactic. Media reinforced by noting Cigna contrast.",
  },
  {
    id: 25,
    date: "2024-08-30",
    source: "City of Seattle HR Department",
    sourceType: "news",
    channel: "stakeholder",
    headline: "City of Seattle HR publishes employee FAQ on Providence-Aetna dispute — city employees affected",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "EMPLOYER-STAKEHOLDER. City of Seattle is major employer with Aetna plans. Government employer response adds political dimension.",
  },

  // === EMPLOYER — WA ===
  {
    id: 26,
    date: "2024-08-29",
    source: "Aetna employer notification (WA)",
    sourceType: "owned",
    channel: "employer",
    headline: "Aetna notifies WA employers: Providence facilities may leave network Sept 1",
    frameAdoption: "aetna",
    sentiment: "negative_providence",
    patientStory: false,
    blameDirection: "providence",
    reachEstimate: "high",
    notes: "Employer channel. Aetna frames Providence as choosing to leave network. Self-funded employer plans face immediate disruption.",
  },
  {
    id: 27,
    date: "2024-08-30",
    source: "WA employer benefits advisors",
    sourceType: "news",
    channel: "employer",
    headline: "WA benefits brokers issue client advisories on Providence-Aetna network disruption risk",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Broker channel. Providence's dominant WA market position means Aetna networks without Providence/Swedish/Kadlec are significantly weakened — employers have leverage against Aetna.",
  },
  {
    id: 28,
    date: "2024-09-01",
    source: "WA large employer HR departments",
    sourceType: "news",
    channel: "employer",
    headline: "Major WA employers scramble to communicate disruption over Labor Day weekend",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Sept 1 = Labor Day weekend. Employers communicating disruption during holiday weekend — terrible logistics. Timing maximizes employer frustration with Aetna.",
  },

  // ===================================================================
  //  PHASE 2 — NORTHERN CALIFORNIA (Aug–Sep 2024)
  // ===================================================================
  {
    id: 29,
    date: "2024-08-19",
    source: "North Bay Business Journal",
    sourceType: "news",
    channel: "media",
    headline: "Providence sends NorCal members letters warning Aetna will become out-of-network Sept 1",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "NorCal business press. Patient notification letters sent Aug 19. Insurance agent Norman Sheehan (20 years in business) said he'd never seen a contract cancellation rescinded — then it was. Providence NorCal facilities at risk.",
  },
  {
    id: 30,
    date: "2024-09-01",
    source: "Press Democrat (Santa Rosa)",
    sourceType: "news",
    channel: "media",
    headline: "Providence, Aetna reach 3-year contract for Northern California — retroactive to July 1",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "NorCal resolution. 3-year deal, effective Sept 1, retroactive to July 1. No disruption in NorCal. Insurance agent: first time in 20 years he'd seen a cancellation reversed. Multi-state pattern: WA and NorCal both resolved quickly; Oregon will not.",
  },

  // ===================================================================
  //  PHASE 3 — OREGON (Dec 2024–Dec 2025)
  // ===================================================================

  // === MEDIA — Oregon contract expiration ===
  {
    id: 31,
    date: "2025-01-01",
    source: "Spokesman-Review (AP wire)",
    sourceType: "news",
    channel: "media",
    headline: "Aetna drops Providence in Oregon from its health insurance network, leaving patients in limbo",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "AP wire story syndicated broadly. 'Aetna drops Providence' framing places blame squarely on insurer. ~9,000 Aetna patients in Oregon affected. Providence: 'Other insurers agreed to step up and share in increasing costs; Aetna has not.' Bob Dragoon's daughter (34, stomach cancer) featured — appointments, medications, treatment halted.",
  },
  {
    id: 32,
    date: "2025-01-01",
    source: "KGW (NBC Portland)",
    sourceType: "tv",
    channel: "media",
    headline: "Thousands of Oregonians left in limbo as Aetna and Providence fail to strike a deal",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "Portland NBC affiliate. Lead story. Bob Dragoon's daughter (34, mother of two, stomach cancer): 'her appointments, medications, and treatment plans have been halted.' Father: 'To have our daughter at the end of this string... she can't get her treatments.' Devastating patient story that defined Oregon coverage.",
  },
  {
    id: 33,
    date: "2025-01-02",
    source: "KPTV (FOX Portland)",
    sourceType: "tv",
    channel: "media",
    headline: "Contract between Aetna and Providence expires, affecting about 9K Oregon patients",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "FOX Portland. 9,000 affected patients figure. Notes Southern Oregon exception: Providence Medical Group clinics in southern OR remain in-network through Feb 17 via PrimeCare IPA contract. Hospital in Medford out Jan 1.",
  },
  {
    id: 34,
    date: "2025-01-01",
    source: "KOBI-TV NBC5 (Medford)",
    sourceType: "tv",
    channel: "media",
    headline: "Oregonians left in limbo as Aetna, Providence fail to strike deal",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Southern Oregon NBC affiliate. Medford-area coverage critical because Providence Medford Medical Center is a dominant provider in the Rogue Valley. Limited alternatives in rural southern OR.",
  },
  {
    id: 35,
    date: "2025-01-02",
    source: "Fierce Healthcare",
    sourceType: "news",
    channel: "media",
    headline: "Aetna's network contract with Providence expires amid protracted negotiations",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press. Notes prior WA and NorCal resolutions as contrast — Oregon is the outlier. Aetna claims Providence demands 'price increases higher than the market rate.' Providence: Aetna 'has not been willing to share in increasing costs.'",
  },
  {
    id: 36,
    date: "2025-01-02",
    source: "Becker's Payer Issues",
    sourceType: "news",
    channel: "media",
    headline: "Aetna, Providence hospitals in Oregon split",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press. Notes most OR locations out-of-network Jan 1; southern OR PMG clinics remain through Feb 16. ~9,000 patients impacted. Hospital executive audience.",
  },
  {
    id: 37,
    date: "2025-01-01",
    source: "Rogue Valley Times",
    sourceType: "news",
    channel: "media",
    headline: "Aetna drops Providence from its health insurance network; local impact delayed in southern Oregon",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Southern Oregon local press. 'Local impact delayed' — Providence Medical Group clinics in Jackson and Josephine counties in-network through Feb 17 via PrimeCare IPA. But Providence Medford Medical Center (hospital) is out Jan 1.",
  },
  {
    id: 38,
    date: "2025-01-01",
    source: "InsuranceNewsNet",
    sourceType: "news",
    channel: "media",
    headline: "Aetna drops Providence in Oregon from its health insurance network, leaving patients in limbo",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Insurance industry press. Bob Dragoon patient story included. Insurance industry audience sees this as cautionary tale for employer plan sponsors considering Aetna.",
  },

  // === PROVIDENCE OWNED — OREGON ===
  {
    id: 39,
    date: "2025-01-01",
    source: "Providence Blog (Oregon negotiations)",
    sourceType: "owned",
    channel: "media",
    headline: "Providence Oregon: 'Aetna has not been willing to share in the increasing costs of health care'",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Providence's Oregon-specific narrative page. Key message: 'Other insurers have agreed to step up and share in the increasing costs of health care, but Aetna has not been willing to do so.' Patient FAQ, continuity-of-care guidance, financial counselor resources. Frames Aetna as the outlier among insurers.",
  },
  {
    id: 40,
    date: "2025-01-01",
    source: "Providence Blog (patient guidance)",
    sourceType: "owned",
    channel: "media",
    headline: "Providence publishes patient FAQ: how to navigate care with out-of-network Aetna insurance",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Patient-facing guidance. Directs patients to talk to HR, insurance broker, or Aetna directly. Notes some patients may qualify for continuity-of-care access (pregnant, chronic conditions). Providence employees not affected — Aetna is Providence's own benefits administrator.",
  },

  // === AETNA OWNED — OREGON ===
  {
    id: 41,
    date: "2025-01-01",
    source: "Aetna (public statement — OR)",
    sourceType: "owned",
    channel: "media",
    headline: "Aetna: Providence demanding price increases 'higher than the market rate' that would raise premiums",
    frameAdoption: "aetna",
    sentiment: "negative_providence",
    patientStory: false,
    blameDirection: "providence",
    reachEstimate: "medium",
    notes: "Aetna's Oregon public statement. Claims Providence demands above-market rates. Notes 85%+ of Aetna's Oregon members are in self-funded employer plans — higher prices would raise out-of-pocket costs. Employer cost framing is Aetna's strongest argument.",
  },

  // === SOCIAL — OREGON ===
  {
    id: 42,
    date: "2025-01-01",
    source: "The Oregonian (Facebook)",
    sourceType: "social",
    channel: "social",
    headline: "Oregonian Facebook post: 'Providence has been dropped from Aetna's health insurance network' — high engagement",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "The Oregonian's Facebook post on the dispute drew significant engagement. 'Dropped from Aetna's network' framing places blame on insurer. Comment sections likely highly emotional given Providence's dominant Oregon presence.",
  },
  {
    id: 43,
    date: "2025-01-02",
    source: "Reddit r/Portland",
    sourceType: "social",
    channel: "social",
    headline: "Portland Reddit: patients share confusion and frustration about losing Providence in-network access",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Reddit community. Providence is deeply embedded in Portland healthcare — losing access affects primary care, specialists, hospitals. Commenters share frustration with Aetna/CVS profitability vs patient impact. Anti-insurer sentiment dominates.",
  },
  {
    id: 44,
    date: "2025-01-05",
    source: "Facebook (Oregon patient groups)",
    sourceType: "social",
    channel: "social",
    headline: "Oregon patient Facebook groups coordinate provider alternatives and express outrage at Aetna",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Organic patient community organizing. Older demographic on Facebook. Practical info-sharing about non-Providence alternatives in Portland. Pregnant patients and those mid-treatment especially anxious about continuity of care rights.",
  },

  // === STAKEHOLDERS — OREGON ===
  {
    id: 45,
    date: "2025-01-02",
    source: "Women's Healthcare Associates (OR)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Women's Healthcare Associates clarifies: we are independent from Providence and remain in-network with Aetna",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "KEY DISTINCTION. WHA published clarification that they are independent from Providence and maintain Aetna contracts. Shows downstream confusion — affiliated clinics must clarify network status. Chaos radius extends beyond Providence-owned facilities.",
  },
  {
    id: 46,
    date: "2025-01-03",
    source: "The Oregon Clinic",
    sourceType: "news",
    channel: "stakeholder",
    headline: "The Oregon Clinic publishes Aetna insurance holder update — clarifying own network status",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Another independent clinic forced to publish clarification for Aetna patients. Demonstrates the confusion radius of Providence's out-of-network status — patients unsure which clinics are affected.",
  },

  // === EMPLOYER — OREGON ===
  {
    id: 47,
    date: "2025-01-01",
    source: "UNITE HERE Northwest Trust Funds",
    sourceType: "news",
    channel: "employer",
    headline: "UNITE HERE NW Trust: Providence terminated contract with Oregon Direct Aetna network — members affected",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Union trust fund employer communication. Directs members to transition care to in-network providers. Hospitality/service workers in Oregon affected. Trust fund acts as employer plan sponsor communicating disruption to members.",
  },
  {
    id: 48,
    date: "2025-01-05",
    source: "Oregon employer HR departments",
    sourceType: "news",
    channel: "employer",
    headline: "Oregon employers with Aetna self-funded plans notify employees about Providence out-of-network status",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CRITICAL: 85%+ of Aetna's Oregon members are in self-funded plans. These employers directly bear cost impact. Higher out-of-network charges for employees using Providence creates immediate HR headaches and open-enrollment pressure to switch from Aetna.",
  },

  // === SOUTHERN OREGON PHASE (Feb 2025) ===
  {
    id: 49,
    date: "2025-02-17",
    source: "KOBI-TV NBC5 (Medford)",
    sourceType: "tv",
    channel: "media",
    headline: "Providence Medical Group clinics in southern Oregon now also out-of-network with Aetna",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Second wave of out-of-network status hits southern Oregon. PrimeCare IPA contract expired Feb 17. Jackson and Josephine county patients now fully out-of-network. Rural southern Oregon has very limited provider alternatives.",
  },

  // === PROLONGED DISPUTE (Spring/Summer 2025) ===
  {
    id: 50,
    date: "2025-03-15",
    source: "Providence Blog (Oregon update)",
    sourceType: "owned",
    channel: "media",
    headline: "Providence Oregon: negotiations with Aetna continue — no resolution in sight",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Months into dispute with no progress. Providence maintains narrative page with patient resources. Contrast with WA's 5-day resolution is stark. Oregon patients living with out-of-network status for months.",
  },
  {
    id: 51,
    date: "2025-06-01",
    source: "Oregon employer open enrollment pressure",
    sourceType: "news",
    channel: "employer",
    headline: "Oregon employers begin evaluating Aetna alternatives as Providence dispute drags past 6 months",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "MID-YEAR EMPLOYER PRESSURE. With dispute showing no resolution, employers who use Aetna begin evaluating alternatives for next open enrollment. Providence is Oregon's co-largest health system — an Aetna network without Providence is fundamentally weakened for Oregon employers.",
  },
  {
    id: 52,
    date: "2025-07-01",
    source: "Providence Oregon (financial context)",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "Providence notes six months of out-of-network status for Oregon Aetna patients — unprecedented duration",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Half-year mark. Providence has absorbed double-digit cost increases for drugs, supplies, and labor. Pre-inflationary contract rates no longer sustainable. Providence maintains patient support infrastructure while awaiting resolution.",
  },

  // === AETNA PATTERN EVIDENCE ===
  {
    id: 53,
    date: "2025-03-15",
    source: "UW Medicine vs Aetna parallel (2025)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "UW Medicine-Aetna dispute emerges in WA — pattern of Aetna provider conflicts in Pacific Northwest",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "PATTERN EVIDENCE. UW Medicine dispute with Aetna in 2025 suggests systematic approach, not Providence-specific unreasonableness. Aetna fighting multiple major PNW systems.",
  },
  {
    id: 54,
    date: "2024-09-15",
    source: "Skyline Benefit (Medicare context)",
    sourceType: "news",
    channel: "employer",
    headline: "Changes between Aetna Medicare and Providence — Medicare Advantage members face additional disruption",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Medicare Advantage dimension. Aetna Medicare plans also affected. Seniors on Medicare Advantage particularly vulnerable — less flexibility to switch plans outside annual enrollment. Southern Oregon eventually only region where Medicare Advantage regains Providence access.",
  },

  // === IRONIES & CONTEXT ===
  {
    id: 55,
    date: "2025-01-01",
    source: "Providence employee benefits context",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Irony: Aetna administers Providence's own employee health benefits — Providence employees unaffected by dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "STRUCTURAL IRONY. Providence switched its own employee benefits to Aetna as administrator and laid off 84 Providence Health Plan employees in 2024. Yet Providence employees are excluded from the dispute. This business relationship adds complexity to the adversarial negotiation.",
  },

  // === RESOLUTION COVERAGE (Nov-Dec 2025) ===
  {
    id: 56,
    date: "2025-11-15",
    source: "Providence Blog (Southern OR resolution)",
    sourceType: "owned",
    channel: "media",
    headline: "Providence Medford Medical Center and South Physicians back in-network for Aetna — effective Nov 15",
    frameAdoption: "providence",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Southern Oregon resolved first. Providence Medford Medical Center and Providence South Physicians return to Aetna Commercial AND Medicare Advantage plans. Southern OR gets Medicare Advantage access — Portland area will not.",
  },
  {
    id: 57,
    date: "2025-12-01",
    source: "Providence Blog (statewide resolution)",
    sourceType: "owned",
    channel: "media",
    headline: "Providence Oregon and Aetna re-establish network agreement — multi-year deal effective Dec 1",
    frameAdoption: "providence",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution announcement. Multi-year agreement. All Providence hospitals, clinics, physicians across Oregon back in-network for Aetna Commercial. Only Southern Oregon gets Medicare Advantage access. Nearly a year of out-of-network status ends.",
  },
  {
    id: 58,
    date: "2025-12-04",
    source: "Becker's Payer Issues",
    sourceType: "news",
    channel: "media",
    headline: "Aetna is back to covering Providence Oregon — multiyear agreement after nearly a year",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press resolution. Notes 1,702 physicians (627 PCPs, 1,075 specialists) rejoin network. Nearly a year out-of-network. Hospital executive audience notes the extraordinary duration.",
  },
  {
    id: 59,
    date: "2025-12-09",
    source: "Willamette Week",
    sourceType: "news",
    channel: "media",
    headline: "A Year After Talks Failed, Providence Oregon Strikes Deal With Big Insurer",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Portland alt-weekly. 'A Year After' framing emphasizes extraordinary duration. Notes ~50,000 Aetna commercial members in Oregon plus 250,000+ in self-insured employer plans administered by Aetna. Only Southern OR gets Medicare Advantage — Portland does not.",
  },
  {
    id: 60,
    date: "2025-12-04",
    source: "Network Contract Watch",
    sourceType: "news",
    channel: "media",
    headline: "RESOLVED: Aetna vs Providence Oregon — network contract restored after 11-month gap",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Benefits industry tracking service. '11-month gap' is among the longest network disruptions in the dataset. Employer benefits professionals use this source to track network stability for plan selection.",
  },
  {
    id: 61,
    date: "2025-12-01",
    source: "UNITE HERE NW Trust Funds (resolution)",
    sourceType: "news",
    channel: "employer",
    headline: "UNITE HERE NW Trust: Providence Oregon rejoins Aetna network — members can return to Providence providers",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Union trust fund resolution communication. 1,702 physicians including 627 PCPs and 1,075 specialists return to network. Members can transition back to Providence providers. Year of disruption for union members ends.",
  },
  {
    id: 62,
    date: "2025-12-04",
    source: "Warner Pacific Insurance",
    sourceType: "news",
    channel: "employer",
    headline: "Warner Pacific confirms Providence-Aetna Oregon agreement — broker advisory to employer clients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Insurance broker advisory. Warner Pacific had previously communicated the WA resolution in 2024. Oregon resolution arrives just in time for 2026 open enrollment planning — employers can now maintain Aetna plans without Providence gap.",
  },

  // === ADDITIONAL SOCIAL — OREGON LONG DISPUTE ===
  {
    id: 63,
    date: "2025-02-01",
    source: "X/Twitter (Oregon patient posts)",
    sourceType: "social",
    channel: "social",
    headline: "Oregon Aetna patients share frustration at month-long Providence out-of-network status — 'still no deal'",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Unlike WA's 5-day window, Oregon's extended dispute generates sustained social media frustration. Patients sharing stories of delayed procedures, changed providers, out-of-pocket costs. Anti-CVS/Aetna sentiment compounds.",
  },
  {
    id: 64,
    date: "2025-04-01",
    source: "Social media (anti-Aetna/CVS sentiment)",
    sourceType: "social",
    channel: "social",
    headline: "Oregon Providence-Aetna dispute fuels broader anti-insurer social media anger — 3 months and counting",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "SUSTAINED SOCIAL ANGER. Unlike quick-resolution disputes, Oregon's months-long disruption generates ongoing organic anti-Aetna content. CVS Health's profitability ($3.7B Q2 2024) vs patient disruption becomes recurring theme. Portland's progressive culture amplifies anti-corporate framing.",
  },

  // === ADDITIONAL STAKEHOLDER ===
  {
    id: 65,
    date: "2025-01-01",
    source: "Aetna continuity-of-care provisions (OR)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Aetna continuity-of-care: pregnant patients and those in active treatment may qualify for extended in-network access",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "REGULATORY SAFEGUARD. Oregon law and Aetna policy provide continuity of care for vulnerable patients — pregnant, active treatment, chronic conditions. But many patients fall outside these protections. Self-funded plans may have different rules. Complexity itself is harmful.",
  },
  {
    id: 66,
    date: "2025-01-01",
    source: "Providence market dominance (Oregon context)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Providence is co-largest health system in Oregon (tied with Legacy) — 90+ clinics, 600+ employed physicians",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "STRUCTURAL CONTEXT. Providence operates 8 hospitals, 90+ clinics, 600+ physicians in Oregon. Tied with Legacy as largest system. An Aetna network without Providence in Oregon is fundamentally incomplete. This market dominance gives Providence leverage but also means disruption is maximally impactful for patients.",
  },

  // === FINANCIAL CONTEXT ===
  {
    id: 67,
    date: "2024-08-28",
    source: "Providence financial disclosures",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Providence financial context: $1.2B operating loss (2023), double-digit cost increases in drugs, supplies, labor",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "KEY FINANCIAL DATA. Providence $1.2B operating loss in 2023. Costs up 26% since 2019. Pre-inflationary Aetna contract rates haven't kept pace. Providence absorbed double-digit increases in drugs, supplies, and labor. Nonprofit mission vs for-profit insurer profitability is the core tension.",
  },
  {
    id: 68,
    date: "2024-08-28",
    source: "CVS Health/Aetna financial context",
    sourceType: "news",
    channel: "stakeholder",
    headline: "CVS Health Q2 2024: $3.7B operating income, $858M returned to shareholders — while Aetna demands lower rates",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "FINANCIAL CONTRAST. CVS Health (Aetna's parent): $3.7B Q2 2024 operating income. $858M returned to shareholders. Connecticut-based for-profit. Providence: $1.2B operating loss, nonprofit, community-based. This contrast is the most damaging data point for Aetna's 'affordability' narrative.",
  },
];

const LABELS = {
  frameAdoption: { providence: "Providence Frame", aetna: "Aetna Frame", balanced: "Balanced" },
  sentiment: {
    negative_aetna: "Anti-Aetna",
    negative_providence: "Anti-Providence",
    neutral: "Neutral",
    positive_aetna: "Pro-Aetna",
    positive_providence: "Pro-Providence",
  },
  blameDirection: { aetna: "Blames Aetna", providence: "Blames Providence", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National record / major wire (1.5)
  "Spokesman-Review (AP wire)": 1.5, "Fierce Healthcare": 1.5, "Becker's Hospital Review": 1.5,
  "Becker's Payer Issues": 1.5, "Healthcare Dive": 1.5, "InsuranceNewsNet": 1.5,
  // Tier 2 — Regional authority (1.2)
  "Seattle Times": 1.2, "KIRO 7 (CBS Seattle)": 1.2, "KING 5 (NBC Seattle)": 1.2,
  "FOX 13 Seattle": 1.2, "KGW (NBC Portland)": 1.2, "KPTV (FOX Portland)": 1.2,
  "Spokesman-Review": 1.2, "Willamette Week": 1.2, "KOBI-TV NBC5 (Medford)": 1.2,
  "Press Democrat (Santa Rosa)": 1.2,
  // Tier 3 — Local/niche trade (1.0)
  "MyNorthwest": 1.0, "Daily Chronicle": 1.0, "Snohomish County Tribune": 1.0,
  "North Bay Business Journal": 1.0, "Rogue Valley Times": 1.0,
  "Network Contract Watch": 1.0, "Skyline Benefit (Medicare context)": 1.0,
  // Tier 4 — Organic social (0.7)
  "X/Twitter (WA patient posts)": 0.7, "X/Twitter (Oregon patient posts)": 0.7,
  "Reddit r/Seattle": 0.7, "Reddit r/Portland": 0.7,
  "Facebook (Oregon patient groups)": 0.7, "The Oregonian (Facebook)": 0.7,
  "Social media (anti-Aetna/CVS sentiment)": 0.7,
  "UNITE HERE Local": 0.7,
  // Tier 5 — Comment sections (0.4)
  // (none coded separately)
  // Tier 6 — Owned/party media (0.3)
  "Providence Blog": 0.3, "Providence Blog (Oregon negotiations)": 0.3,
  "Providence Blog (patient guidance)": 0.3, "Providence Blog (Oregon update)": 0.3,
  "Providence Blog (Southern OR resolution)": 0.3, "Providence Blog (statewide resolution)": 0.3,
  "Swedish.org": 0.3,
  "Aetna (public statement — WA)": 0.3, "Aetna (public statement — OR)": 0.3,
  "Aetna employer notification (WA)": 0.3,
  "Providence Oregon (financial context)": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "WA Office of the Insurance Commissioner": 1.3, "City of Seattle HR Department": 1.3,
  "Providence CFO Greg Hoffman": 1.3, "Providence strategic sequencing (Cigna deal)": 1.3,
  "Women's Healthcare Associates (OR)": 1.3, "The Oregon Clinic": 1.3,
  "Aetna continuity-of-care provisions (OR)": 1.3,
  "Providence market dominance (Oregon context)": 1.3,
  "Providence employee benefits context": 1.3,
  "Providence financial disclosures": 1.3, "CVS Health/Aetna financial context": 1.3,
  "UW Medicine vs Aetna parallel (2025)": 1.3,
  // Tier 8 — Employer/Benefits (1.5x trade, 1.8x consultant)
  "UNITE HERE Northwest Trust Funds": 1.5, "UNITE HERE NW Trust Funds (resolution)": 1.5,
  "WA employer benefits advisors": 1.5, "WA large employer HR departments": 1.5,
  "Oregon employer HR departments": 1.5, "Oregon employer open enrollment pressure": 1.5,
  "Warner Pacific Insurance": 1.0,
};

const SEARCH_TRENDS = [
  // WA phase
  { week: "2024-08-05", interest: 3 },
  { week: "2024-08-12", interest: 5 },
  { week: "2024-08-19", interest: 12 },
  { week: "2024-08-26", interest: 75 },
  { week: "2024-09-02", interest: 85 },
  { week: "2024-09-09", interest: 20 },
  { week: "2024-09-16", interest: 8 },
  { week: "2024-09-23", interest: 5 },
  // Quiet period
  { week: "2024-10-07", interest: 3 },
  { week: "2024-11-04", interest: 4 },
  { week: "2024-12-02", interest: 10 },
  { week: "2024-12-16", interest: 25 },
  // Oregon phase
  { week: "2024-12-30", interest: 100 },
  { week: "2025-01-06", interest: 90 },
  { week: "2025-01-13", interest: 50 },
  { week: "2025-01-20", interest: 30 },
  { week: "2025-02-03", interest: 20 },
  { week: "2025-02-17", interest: 35 },
  { week: "2025-03-03", interest: 15 },
  { week: "2025-04-07", interest: 8 },
  { week: "2025-06-02", interest: 5 },
  { week: "2025-08-04", interest: 4 },
  { week: "2025-10-06", interest: 5 },
  // Oregon resolution
  { week: "2025-11-17", interest: 18 },
  { week: "2025-12-01", interest: 55 },
  { week: "2025-12-08", interest: 40 },
  { week: "2025-12-15", interest: 15 },
  { week: "2025-12-22", interest: 8 },
];

export default {
  // Identity
  providerKey: "providence",
  payorKey: "aetna",
  providerName: "Providence Health",
  payorName: "Aetna",
  providerShort: "Providence",
  payorShort: "Aetna",
  navShort: "Providence v. Aetna",
  title: "Providence vs Aetna",
  subtitle: "Multi-state contract dispute · WA resolved Sep 2024 · OR resolved Dec 2025",
  gradientId: "providenceaetna",

  // Dates
  monitorStart: "August 1, 2024",
  monitorEnd: "December 31, 2025",
  disputePublicDate: "2024-08-28",

  // Colors
  colors: {
    providerColor: "#1B6B3A",
    payorColor: "#7B2D8E",
    neutral: "#64748B",
    accent: "#1B6B3A",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#1B6B3A", "#4D7A5E", "#7B2D8E"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"providence aetna" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.72,
    nationalMedian: 1.0,
    networkComplaints: 1243,
    priorYearComplaints: 987,
    regulatorAction: "WA Office of the Insurance Commissioner issued briefing memo Aug 30, 2024 — just 2 days after public disclosure. Speed of WA regulatory engagement likely accelerated WA resolution (5 days). Oregon Division of Financial Regulation (DFR) did not take equivalent public action during the 11-month Oregon dispute. Oregon's TK Keen named insurance commissioner Dec 2025, after dispute resolved.",
    signalRead: "Aetna's complaint index is moderately elevated (1.72x median). Multi-state Providence disputes (WA, NorCal, OR) plus parallel UW Medicine conflict suggest systematic Aetna approach to Pacific Northwest provider rates. Oregon's 11-month out-of-network gap is among the longest in recent provider-insurer disputes nationally. 85%+ of Aetna's Oregon members are in self-funded employer plans, amplifying employer-channel pressure.",
  },

  // Executive summary
  executiveSummary: {
    statement: "The Providence-Aetna dispute played out across three states with dramatically different outcomes: WA resolved in 5 days (Sept 2024), NorCal resolved pre-deadline (Sept 2024), but Oregon endured nearly 11 months out-of-network (Jan–Dec 2025) — one of the longest major provider-insurer disruptions in recent memory.",
    keyMessages: [
      "Providence's $1.2B operating loss vs CVS/Aetna's $3.7B Q2 operating income is the defining financial contrast — nonprofit mission vs for-profit extraction framing devastates Aetna's 'affordability' argument.",
      "WA's 5-day resolution demonstrates what's possible with strategic sequencing (Cigna deal first) and proactive state regulation (OIC briefing memo in 48 hours). Oregon's 11-month gap shows what happens without those factors.",
      "Oregon's 11-month disruption affected ~9,000 direct Aetna patients plus 250,000+ in self-funded employer plans administered by Aetna — the employer-channel pressure was enormous.",
      "Bob Dragoon's daughter (34, stomach cancer, mother of two) is the human face of the Oregon dispute — maximally sympathetic patient story that Aetna cannot counter with equivalent advocacy.",
    ],
    marcomm: [
      "<strong>The nonprofit vs for-profit contrast is Providence's trump card.</strong> $1.2B loss vs $3.7B operating income and $858M to shareholders — no affordability argument can overcome this optics gap. CFO Hoffman's framing was picked up by every outlet.",
      "<strong>Oregon is the cautionary tale of what happens when disputes drag on.</strong> Same parties, same issues — 5 days in WA vs 11 months in OR. The difference: WA OIC engagement, Providence's Cigna-first strategy, and higher WA patient volume (35,000 vs 9,000) creating faster pressure.",
      "<strong>Employer leverage is the decisive factor in Oregon.</strong> 85%+ of Aetna's Oregon members are in self-funded plans. With Providence as the co-largest system, an Aetna network without Providence is fundamentally incomplete. Employers evaluating alternatives for open enrollment created the pressure that eventually forced resolution.",
      "<strong>The multi-state pattern undermines Aetna's framing.</strong> Disputes with Providence across WA, NorCal, and OR — plus UW Medicine in WA — suggest Aetna's systematic rate strategy, not Providence-specific unreasonableness. 'Every other insurer agreed to step up' is Providence's stickiest line.",
    ],
  },
  channelTakeaways: {
    media: [
      "Seattle Times set the Providence-sympathetic frame for WA that all subsequent coverage adopted. In Oregon, KGW (NBC Portland) broke the most impactful patient story (Bob Dragoon's daughter).",
      "AP wire syndication of the Oregon expiration ('Aetna drops Providence') reached national audience via Spokesman-Review and InsuranceNewsNet — framing places blame on Aetna.",
      "Trade press (Fierce, Becker's, Healthcare Dive) framed WA resolution as strategic win for health systems; Oregon's prolonged dispute as cautionary tale for employer plan sponsors.",
      "Willamette Week's 'A Year After Talks Failed' resolution headline captures the extraordinary 11-month duration — among the longest in recent memory.",
    ],
    social: [
      "WA's 5-day window prevented sustained viral social media moment. Oregon's 11-month dispute generated sustained organic anti-Aetna content across Reddit, Facebook, and X.",
      "The Oregonian's Facebook post on the network split drew high engagement — Providence's dominant Oregon presence means the disruption touched a huge patient base.",
      "UNITE HERE union mobilization activated organized labor networks against Aetna/CVS profitability framing in both WA and OR.",
      "Portland's progressive political culture amplified anti-corporate framing — CVS Health's Connecticut-based for-profit extracting from Oregon communities resonated strongly.",
    ],
    stakeholder: [
      "WA OIC briefing memo (Aug 30, 2024) was the fastest regulatory response — 48 hours from disclosure. Oregon DFR did not take equivalent public action during the 11-month dispute, likely contributing to longer duration.",
      "Providence CFO Greg Hoffman's for-profit/nonprofit contrast was the single most effective framing across all coverage of the multi-state dispute.",
      "Independent clinics (Women's Healthcare Associates, Oregon Clinic) forced to publish clarifications shows the confusion radius extending beyond Providence-owned facilities.",
      "Providence's strategic Cigna-first sequencing isolated Aetna as the holdout — replicable playbook for multi-payor negotiations.",
    ],
    employer: [
      "85%+ of Aetna's Oregon members are in self-funded employer plans — employers directly bear the cost of Providence out-of-network charges, creating enormous pressure.",
      "UNITE HERE NW Trust Fund communications to union members demonstrate organized employer-plan-level advocacy during and after the dispute.",
      "Oregon employers evaluating Aetna alternatives for 2026 open enrollment created the ultimate leverage — threat of employer defection likely accelerated December 2025 resolution.",
      "Resolution arriving Dec 1, 2025 was just in time for 2026 open enrollment decisions — employers could maintain Aetna without the Providence gap.",
    ],
  },
  arguments: {
    payor: [
      { phase: "Early (Aug 2024)", points: [
        "Aetna: Providence demanding '<strong>unreasonable rate increases</strong> that would raise costs for employers'",
        "Employer cost framing targeted self-funded plan sponsors who bear direct cost impact",
        "Corporate tone with no patient voices — relied on affordability messaging",
      ] },
      { phase: "Mid-Dispute (Jan–Nov 2025, Oregon)", points: [
        "Maintained 'unreasonable rate increases' framing as Oregon dispute extended for nearly a full year",
        "Could not effectively counter Providence's <strong>for-profit vs. nonprofit contrast</strong> (CVS/Aetna $3.7B operating income vs Providence $1.2B operating loss)",
        "In Oregon, 85%+ of Aetna members are in self-funded employer plans — employer pressure mounted as open enrollment approached",
      ] },
      { phase: "Resolution (Sep 2024 WA / Dec 2025 OR)", points: [
        "WA resolved quickly (5 days from public disclosure to deal) after WA OIC issued briefing memo",
        "Oregon took <strong>nearly 12 months</strong> to resolve — December 4, 2025 agreement effective December 1",
      ] },
    ],
    provider: [
      { phase: "Early (Aug 2024)", points: [
        "CFO Greg Hoffman: '<strong>For-profit insurers like Aetna continue to reap benefits of multi-year contracts</strong> while costs skyrocket'",
        "Cited <strong>$1.2 billion operating loss</strong> and costs up 26% since 2019 as evidence rates must increase",
        "Strategically resolved Cigna deal first — <strong>isolated Aetna as the holdout insurer</strong> ('we can make deals with reasonable insurers')",
      ] },
      { phase: "Mid-Dispute (Jan–Nov 2025, Oregon)", points: [
        "Oregon patient stories defined the dispute: Bob Dragoon's daughter (34, mother of two, stomach cancer) — 'appointments, medications, and treatment plans have been <strong>halted</strong>'",
        "Providence: 'Other insurers agreed to step up and share in increasing costs; <strong>Aetna has not</strong>'",
        "~9,000 Oregon Aetna patients affected; independent clinics (Women's Healthcare Associates, Oregon Clinic) forced to publish clarifications — <strong>confusion radius extended beyond Providence-owned facilities</strong>",
      ] },
      { phase: "Resolution (Sep 2024 WA / Dec 2025 OR)", points: [
        "WA: 'patients will continue to have access' — victory framing implying Providence secured the deal that protects patients",
        "Oregon: resolution arrived just in time for <strong>2026 open enrollment decisions</strong> — employers could maintain Aetna without the Providence gap",
      ] },
    ],
  },
  timeline: [
    { date: "2024-08-28", type: "newsBreak", label: "News breaks publicly" },
    { date: "2024-09-01", type: "termination", label: "WA contract terminates" },
    { date: "2024-09-03", type: "agreement", label: "WA agreement reached" },
  ],
};
