// Providence Health vs Aetna — PR War Room Config
// Dispute period: Aug–Sep 2024. Washington State. Resolved September 3, 2024.

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2024-08-28",
    source: "Seattle Times",
    sourceType: "news",
    channel: "media",
    headline: "Providence, Aetna fail to reach deal — ~35,000 WA patients face Sept 1 disruption",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "First major coverage. Seattle Times is the paper of record for WA. Providence announced impasse publicly. Key framing: 35,000 patients at risk across Providence, Swedish, Kadlec, PacMed, St. Luke's Rehab. Providence CFO Greg Hoffman quoted: 'For-profit insurers like Aetna continue to reap benefits of multi-year contracts.'",
  },
  {
    id: 2,
    date: "2024-09-01",
    source: "Seattle Times",
    sourceType: "news",
    channel: "media",
    headline: "Providence-Aetna contract expires — deadline passes with no deal, talks continue",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "Deadline-day coverage. Providence facilities listed: Providence, Swedish, Kadlec, PacMed, St. Luke's Rehab. Urgency framing. Patient anxiety. Providence $1.2B operating loss (2023) cited as context for why rate increases are necessary.",
  },
  {
    id: 3,
    date: "2024-08-29",
    source: "Spokesman-Review",
    sourceType: "news",
    channel: "media",
    headline: "Thousands of Eastern WA patients could lose in-network access as Providence-Aetna talks stall",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Spokane-based paper. Eastern WA angle — Kadlec Regional Medical Center in Richland is the dominant provider in Tri-Cities. Losing Kadlec in-network would be devastating for rural patients with few alternatives.",
  },
  {
    id: 4,
    date: "2024-08-29",
    source: "KIRO 7 (CBS Seattle)",
    sourceType: "tv",
    channel: "media",
    headline: "Providence warns Aetna patients: find new providers or face out-of-network costs starting Sept 1",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "Major Seattle TV. Patient anxiety stories. Providence framing dominates — 'find new providers' creates immediate fear. Providence facilities are deeply embedded in WA healthcare infrastructure.",
  },
  {
    id: 5,
    date: "2024-08-29",
    source: "KING 5 (NBC Seattle)",
    sourceType: "tv",
    channel: "media",
    headline: "35,000 WA patients caught in Providence-Aetna contract dispute — Sept 1 deadline looms",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "NBC affiliate. '35,000 patients caught' frames patients as victims of insurer intransigence. Both sides quoted but Providence's patient-impact framing dominates the visual storytelling.",
  },
  {
    id: 6,
    date: "2024-08-30",
    source: "FOX 13 Seattle",
    sourceType: "tv",
    channel: "media",
    headline: "Providence-Aetna standoff: WA insurance commissioner issues briefing as deadline nears",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "FOX 13 covers OIC briefing memo issuance. Regulatory intervention angle adds gravity. Both sides quoted. WA OIC engagement signals state concern about patient disruption.",
  },
  {
    id: 7,
    date: "2024-08-29",
    source: "MyNorthwest",
    sourceType: "news",
    channel: "media",
    headline: "Providence Health could drop Aetna insurance — what WA patients need to know",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Regional digital outlet. 'Drop Aetna' framing places initiative with Providence but blame on Aetna for forcing the choice. Practical patient guidance angle.",
  },
  {
    id: 8,
    date: "2024-08-29",
    source: "Daily Chronicle",
    sourceType: "news",
    channel: "media",
    headline: "Providence-Aetna dispute puts WA patients in limbo ahead of Sept 1",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Local paper coverage. 'Patients in limbo' framing. Community-level impact stories.",
  },
  {
    id: 9,
    date: "2024-09-03",
    source: "Daily Chronicle",
    sourceType: "news",
    channel: "media",
    headline: "Providence, Aetna reach deal — 35,000 WA patients keep in-network access",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Resolution coverage. Relief framing. Deal announced Sept 3 after brief 2-day lapse.",
  },
  {
    id: 10,
    date: "2024-08-30",
    source: "Snohomish County Tribune",
    sourceType: "news",
    channel: "media",
    headline: "Swedish Medical patients in Snohomish County brace for Aetna network exit",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Hyperlocal suburban coverage. Swedish Medical Center (Providence subsidiary) is major Snohomish County provider. Local patient anxiety stories. Suburban family demographic.",
  },
  {
    id: 11,
    date: "2024-08-29",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "Providence, Aetna contract negotiations stall — 35,000 patients at risk in Washington",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National trade press. Hospital executive audience. Notes Providence's $1.2B operating loss and costs up 26% since 2019. Aetna's 'unreasonable rate increases' counter-claim also included.",
  },
  {
    id: 12,
    date: "2024-09-03",
    source: "Fierce Healthcare",
    sourceType: "news",
    channel: "media",
    headline: "Providence, Aetna resolve WA contract dispute after brief lapse — deal reached in 5 days",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press resolution coverage. '5 days' speed noted — contrasts sharply with Oregon's year-long dispute. Providence's strategic sequencing (Cigna deal first) noted as effective negotiation tactic.",
  },
  {
    id: 13,
    date: "2024-08-30",
    source: "InsuranceNewsNet",
    sourceType: "news",
    channel: "media",
    headline: "Aetna-Providence contract dispute highlights growing insurer-provider tensions in WA",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Insurance industry trade press. Insurer audience perspective. Notes CVS/Aetna $3.7B operating income Q2 2024 alongside Providence $1.2B loss. Financial contrast is damaging for Aetna's 'affordability' framing.",
  },
  {
    id: 14,
    date: "2024-08-30",
    source: "Healthcare Dive",
    sourceType: "news",
    channel: "media",
    headline: "Providence escalates Aetna dispute in WA, cites 26% cost increase since 2019",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Trade press. Providence's cost data framing. 26% cost increase since 2019 is a powerful data point — justifies rate increase demands. Healthcare Dive audience is hospital/health system executives.",
  },
  {
    id: 15,
    date: "2024-09-03",
    source: "Health Leaders",
    sourceType: "news",
    channel: "media",
    headline: "Providence-Aetna deal signals strategic win for health systems in contract disputes",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Trade press analysis. Notes Providence's strategic sequencing: publicly resolved Cigna deal first, isolating Aetna. 5-day resolution in WA vs year-long Oregon dispute. Health system audience — Providence as model.",
  },
  {
    id: 16,
    date: "2024-08-30",
    source: "North Bay Business Journal",
    sourceType: "news",
    channel: "media",
    headline: "Providence's WA insurance disputes echo across multi-state health system",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Northern California business press. Providence operates across 7 states — WA dispute has implications for CA, OR, AK, MT markets. Employer audience concerned about network stability.",
  },
  // === PROVIDENCE OWNED MEDIA ===
  {
    id: 17,
    date: "2024-08-28",
    source: "Providence Blog",
    sourceType: "owned",
    channel: "media",
    headline: "Providence announces Aetna contract impasse — 'we cannot accept rates that don't cover the cost of care'",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "First public statement. Sets the narrative frame. Key message: operating loss of $1.2B, costs up 26% since 2019. 'For-profit insurers like Aetna continue to reap benefits of multi-year contracts while costs skyrocket.' CFO Greg Hoffman quoted.",
  },
  {
    id: 18,
    date: "2024-08-30",
    source: "Providence Blog",
    sourceType: "owned",
    channel: "media",
    headline: "Providence patient FAQ: What to do if you have Aetna insurance at Providence or Swedish facilities",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Patient-facing guidance. Lists all affected facilities: Providence, Swedish, Kadlec, PacMed, St. Luke's Rehab. Directs patients to financial counselors. Implicitly blames Aetna by emphasizing Providence's willingness to negotiate.",
  },
  {
    id: 19,
    date: "2024-09-03",
    source: "Providence Blog",
    sourceType: "owned",
    channel: "media",
    headline: "Providence announces new agreement with Aetna — 'patients will continue to have access'",
    frameAdoption: "providence",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution announcement. Victory framing — 'patients will continue to have access' implies Providence secured the deal that protects patients. Brief 2-day disruption minimized.",
  },
  {
    id: 20,
    date: "2024-08-28",
    source: "Swedish.org",
    sourceType: "owned",
    channel: "media",
    headline: "Swedish Medical Center: Important information about Aetna insurance changes",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Swedish-specific patient communication. Swedish is the largest nonprofit provider in Seattle metro. Separate website from Providence amplifies reach. Many patients identify with Swedish brand, not Providence corporate.",
  },
  {
    id: 21,
    date: "2024-09-03",
    source: "Swedish.org",
    sourceType: "owned",
    channel: "media",
    headline: "Swedish Medical Center: Aetna agreement reached — your care continues uninterrupted",
    frameAdoption: "providence",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution announcement on Swedish-branded site. 'Uninterrupted' framing despite 2-day lapse. Patient relief messaging.",
  },
  // === OREGON CONTEXT ENTRIES ===
  {
    id: 22,
    date: "2025-01-15",
    source: "Spokesman-Review",
    sourceType: "news",
    channel: "media",
    headline: "Providence-Aetna Oregon dispute drags on — Dec 31, 2024 expiration still unresolved months later",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "OREGON CONTEXT. OR contract expired Dec 31, 2024 — took approximately a year to resolve vs WA's 5 days. Same parties, vastly different outcomes. Demonstrates Providence's strategic success in WA by contrast.",
  },
  {
    id: 23,
    date: "2025-01-10",
    source: "KGW (NBC Portland)",
    sourceType: "tv",
    channel: "media",
    headline: "Oregon Providence-Aetna patients stuck without resolution — months of out-of-network limbo",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "OREGON CONTEXT. Portland NBC affiliate. Patient stories from OR — months of disruption vs WA's 2-day blip. Bob Dragoon's daughter (34, stomach cancer) featured in OR coverage. Devastating patient story that shows what happens when disputes drag on.",
  },
  {
    id: 24,
    date: "2025-01-12",
    source: "KPTV (FOX Portland)",
    sourceType: "tv",
    channel: "media",
    headline: "Providence-Aetna OR stalemate continues — cancer patients seeking alternatives",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "OREGON CONTEXT. FOX Portland affiliate. Cancer patient angle. OR's protracted dispute provides the cautionary tale that WA avoided through Providence's strategic approach.",
  },
  {
    id: 25,
    date: "2025-01-20",
    source: "Willamette Week",
    sourceType: "news",
    channel: "media",
    headline: "Portland patients caught in Providence-Aetna crossfire — no end in sight",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "OREGON CONTEXT. Portland alt-weekly. 'No end in sight' framing. Willamette Week audience skews younger, politically engaged. Critical of both corporate healthcare players but Aetna/CVS profitability is the sharper target.",
  },
  // === UNION/ADVOCACY ENTRIES ===
  {
    id: 26,
    date: "2024-08-30",
    source: "UNITE HERE Local",
    sourceType: "social",
    channel: "social",
    headline: "UNITE HERE union alert: Providence-Aetna dispute threatens member healthcare access in WA",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Union mobilization. UNITE HERE represents hospitality/service workers — many with Aetna employer plans. Union framing blames Aetna/CVS profitability. Activates organized labor network to pressure Aetna.",
  },
  {
    id: 27,
    date: "2024-09-01",
    source: "UNITE HERE (social media)",
    sourceType: "social",
    channel: "social",
    headline: "UNITE HERE shares CVS/Aetna $3.7B operating income vs Providence $1.2B loss — 'who's really driving costs?'",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Financial contrast messaging. CVS/Aetna Q2 2024: $3.7B operating income, $858M returned to shareholders. Providence 2023: $1.2B operating loss. Union channels amplify this comparison to organized labor networks across WA.",
  },
  // === AETNA OWNED MEDIA ===
  {
    id: 28,
    date: "2024-08-29",
    source: "Aetna (public statement)",
    sourceType: "owned",
    channel: "media",
    headline: "Aetna: Providence demanding 'unreasonable rate increases that would raise costs for employers'",
    frameAdoption: "aetna",
    sentiment: "negative_providence",
    patientStory: false,
    blameDirection: "providence",
    reachEstimate: "medium",
    notes: "Aetna's primary public statement. 'Unreasonable rate increases' is their key framing. Employer cost angle targets self-funded plan sponsors. Corporate tone. No patient voices. Defensive positioning against Providence's first-mover narrative advantage.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 29,
    date: "2024-08-29",
    source: "X/Twitter (WA patient posts)",
    sourceType: "social",
    channel: "social",
    headline: "WA patients share Providence-Aetna anxiety on social media — 'just found out my hospital is dropping my insurance'",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Organic patient social posts. Providence/Swedish patients discovering the dispute. 5-day window too short for sustained viral moment, but initial anxiety posts are intense. Many patients confused about what happens Sept 1.",
  },
  {
    id: 30,
    date: "2024-08-30",
    source: "Reddit r/Seattle",
    sourceType: "social",
    channel: "social",
    headline: "Reddit Seattle threads on Providence-Aetna: 'Anyone else just get a letter about losing Swedish access?'",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Reddit Seattle community discussion. Swedish brand recognition drives engagement — many Seattleites born at Swedish hospitals. Comment threads generally blame Aetna/CVS profitability. Some defend Aetna on cost-control grounds.",
  },
  {
    id: 31,
    date: "2024-09-01",
    source: "Facebook (Providence patient groups)",
    sourceType: "social",
    channel: "social",
    headline: "Providence patient Facebook groups share Sept 1 deadline anxiety and provider alternatives",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Facebook patient community. Older demographic. Practical information sharing about alternatives. Anxiety about continuity of care, especially for chronic conditions and pregnancies at Swedish.",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 32,
    date: "2024-08-30",
    source: "WA Office of the Insurance Commissioner",
    sourceType: "news",
    channel: "stakeholder",
    headline: "WA OIC issues briefing memo on Providence-Aetna dispute — signals regulatory concern",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CRITICAL REGULATORY ACTION. WA OIC issued briefing memo Aug 30 — just 2 days after public disclosure. Speed of regulatory response reflects WA's proactive insurance oversight. Memo outlines patient protections and continuity-of-care requirements. Regulatory pressure likely accelerated resolution.",
  },
  {
    id: 33,
    date: "2024-08-30",
    source: "City of Seattle HR Department",
    sourceType: "news",
    channel: "stakeholder",
    headline: "City of Seattle HR publishes employee FAQ on Providence-Aetna dispute — city employees affected",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "EMPLOYER-STAKEHOLDER. City of Seattle is major employer with Aetna plans. HR FAQ signals institutional-level concern. Government employer response adds political dimension — elected officials' employees directly affected.",
  },
  {
    id: 34,
    date: "2024-08-29",
    source: "Providence financial counselors",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "Providence deploys financial counselors to help Aetna patients navigate coverage transition",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Patient support infrastructure. Providence's proactive counselor deployment frames them as protecting patients while Aetna forces disruption. Operational PR — demonstrates institutional readiness and patient-first positioning.",
  },
  {
    id: 35,
    date: "2024-08-28",
    source: "Aetna Whole Health WA (carveout)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Aetna Whole Health product in WA — carveout arrangement adds complexity to dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Aetna Whole Health is a narrower network product in WA. Carveout arrangements mean some Aetna members have different Providence access terms. Adds complexity to patient communication — not all Aetna members equally affected.",
  },
  {
    id: 36,
    date: "2024-08-28",
    source: "Providence CFO Greg Hoffman",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Providence CFO: 'For-profit insurers like Aetna continue to reap benefits of multi-year contracts while our costs have risen 26%'",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "KEY EXECUTIVE QUOTE. Greg Hoffman's framing is Providence's stickiest message: for-profit insurer profitability vs nonprofit provider losses. $1.2B operating loss (2023) vs CVS/Aetna $3.7B Q2 operating income. This contrast was picked up across all media coverage.",
  },
  {
    id: 37,
    date: "2024-08-28",
    source: "Providence strategic sequencing (Cigna deal)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Providence publicly resolves Cigna deal first — strategically isolates Aetna as the holdout insurer",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "STRATEGIC MOVE. Providence publicized Cigna deal resolution before Aetna deadline — framing: 'we can make deals with reasonable insurers, Aetna is the problem.' Classic negotiation isolation tactic. Media coverage reinforced this by noting Cigna deal as contrast.",
  },
  {
    id: 38,
    date: "2025-03-15",
    source: "UW Medicine vs Aetna parallel (2025)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "UW Medicine-Aetna dispute emerges in 2025 — pattern of Aetna WA provider conflicts",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "PATTERN EVIDENCE. UW Medicine parallel dispute with Aetna in 2025 suggests Aetna's WA network strategy is systematically aggressive. Providence was not uniquely unreasonable — Aetna is fighting multiple major WA systems.",
  },
  // === PATIENT STORY (OREGON CONTEXT) ===
  {
    id: 39,
    date: "2025-01-10",
    source: "KGW (NBC Portland) — Bob Dragoon interview",
    sourceType: "tv",
    channel: "media",
    headline: "Bob Dragoon's daughter (34, stomach cancer) loses Providence in-network access in OR — 'she's fighting for her life'",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "NAMED PATIENT STORY. Bob Dragoon's daughter, 34, with stomach cancer, lost in-network Providence access in Oregon dispute. Father advocates publicly. Maximally sympathetic: young woman, cancer, disrupted care. OR dispute's length created patient stories WA's 5-day window did not. This is the human face of what WA narrowly avoided.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 40,
    date: "2024-08-29",
    source: "Aetna employer notification (WA)",
    sourceType: "owned",
    channel: "employer",
    headline: "Aetna notifies WA employers: Providence facilities may leave network Sept 1",
    frameAdoption: "aetna",
    sentiment: "negative_providence",
    patientStory: false,
    blameDirection: "providence",
    reachEstimate: "high",
    notes: "Employer channel. Aetna frames Providence as choosing to leave network. Self-funded employer plans face immediate disruption. Key for employer perception — Aetna tries to position Providence as the aggressor.",
  },
  {
    id: 41,
    date: "2024-08-30",
    source: "WA employer benefits advisors",
    sourceType: "news",
    channel: "employer",
    headline: "WA benefits brokers issue client advisories on Providence-Aetna network disruption risk",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Broker channel. Benefits advisors across WA issued client communications about potential disruption. Providence's dominant market position in WA means Aetna networks without Providence are significantly weakened.",
  },
  {
    id: 42,
    date: "2024-09-01",
    source: "WA large employer HR departments",
    sourceType: "news",
    channel: "employer",
    headline: "Major WA employers scramble to communicate Providence-Aetna disruption to employees over Labor Day weekend",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Sept 1 = Labor Day weekend. Employers caught communicating disruption during holiday weekend — terrible optics and logistics. Timing maximizes employer frustration with Aetna for not resolving sooner.",
  },
  // === ADDITIONAL CONTEXT ===
  {
    id: 43,
    date: "2024-08-29",
    source: "Providence Blog (financial context)",
    sourceType: "owned",
    channel: "media",
    headline: "Providence details financial pressure: $1.2B operating loss, costs up 26% since 2019, workforce crisis",
    frameAdoption: "providence",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Detailed financial case. Providence 2023: $1.2B operating loss. Costs up 26% since 2019. Workforce shortages driving labor costs. 'We cannot continue to provide care at rates that don't cover costs.' Data-driven counter to Aetna's affordability framing.",
  },
  {
    id: 44,
    date: "2024-09-03",
    source: "Providence Blog (OR vs WA comparison)",
    sourceType: "owned",
    channel: "media",
    headline: "Providence notes WA resolution speed (5 days) as evidence of good-faith negotiation",
    frameAdoption: "providence",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Implicit comparison to OR dispute (Dec 31, 2024 expiration, ~year to resolve). WA's 5-day resolution framed as evidence that rapid deals are possible when both sides negotiate in good faith. Subtle dig at Aetna's OR posture.",
  },
];

const LABELS = {
  frameAdoption: { providence: "Providence Frame", aetna: "Aetna Frame", balanced: "Balanced" },
  sentiment: {
    negative_aetna: "Anti-Aetna",
    negative_providence: "Anti-Providence",
    neutral: "Neutral",
    positive_aetna: "Pro-Aetna",
    positive_providence: "Pro-Providence",
  },
  blameDirection: { aetna: "Blames Aetna", providence: "Blames Providence", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National/major trade (1.5)
  "Becker's Hospital Review": 1.5, "Fierce Healthcare": 1.5, "Healthcare Dive": 1.5,
  "Health Leaders": 1.5, "InsuranceNewsNet": 1.5,
  // Tier 2 — Regional authority (1.2)
  "Seattle Times": 1.2, "Spokesman-Review": 1.2, "KIRO 7 (CBS Seattle)": 1.2,
  "KING 5 (NBC Seattle)": 1.2, "FOX 13 Seattle": 1.2, "KGW (NBC Portland)": 1.2,
  "KPTV (FOX Portland)": 1.2, "Willamette Week": 1.2,
  // Tier 3 — Local/niche (1.0)
  "MyNorthwest": 1.0, "Daily Chronicle": 1.0, "Snohomish County Tribune": 1.0,
  "North Bay Business Journal": 1.0,
  // Tier 4 — Organic social (0.7)
  "X/Twitter (WA patient posts)": 0.7, "Reddit r/Seattle": 0.7,
  "Facebook (Providence patient groups)": 0.7, "UNITE HERE Local": 0.7,
  "UNITE HERE (social media)": 0.7,
  // Tier 5 — Owned/party media (0.3)
  "Providence Blog": 0.3, "Providence Blog (financial context)": 0.3,
  "Providence Blog (OR vs WA comparison)": 0.3,
  "Swedish.org": 0.3, "Aetna (public statement)": 0.3,
  "Aetna employer notification (WA)": 0.3,
  // Tier 6 — Stakeholder actions (1.3)
  "WA Office of the Insurance Commissioner": 1.3, "City of Seattle HR Department": 1.3,
  "Providence financial counselors": 1.3, "Providence CFO Greg Hoffman": 1.3,
  "Providence strategic sequencing (Cigna deal)": 1.3,
  "Aetna Whole Health WA (carveout)": 1.3, "UW Medicine vs Aetna parallel (2025)": 1.3,
  "KGW (NBC Portland) — Bob Dragoon interview": 1.3,
  // Tier 7 — Employer/Benefits (1.5x trade)
  "WA employer benefits advisors": 1.5, "WA large employer HR departments": 1.5,
};

const SEARCH_TRENDS = [
  { week: "2024-08-01", interest: 5 },
  { week: "2024-08-08", interest: 7 },
  { week: "2024-08-15", interest: 8 },
  { week: "2024-08-22", interest: 10 },
  { week: "2024-08-28", interest: 80 },
  { week: "2024-08-29", interest: 90 },
  { week: "2024-09-01", interest: 100 },
  { week: "2024-09-03", interest: 85 },
  { week: "2024-09-10", interest: 20 },
  { week: "2024-09-17", interest: 10 },
  { week: "2024-09-24", interest: 5 },
];

export default {
  // Identity
  providerKey: "providence",
  payorKey: "aetna",
  providerName: "Providence Health",
  payorName: "Aetna",
  providerShort: "Providence",
  payorShort: "Aetna",
  navShort: "Providence v. Aetna",
  title: "Providence vs Aetna",
  subtitle: "Contract dispute · Washington State · Resolved September 3, 2024",
  gradientId: "providenceaetna",

  // Dates
  monitorStart: "August 1, 2024",
  monitorEnd: "September 30, 2024",
  disputePublicDate: "2024-08-28",

  // Colors
  colors: {
    providerColor: "#1B6B3A",
    payorColor: "#7B2D8E",
    neutral: "#64748B",
    accent: "#1B6B3A",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#1B6B3A", "#4D7A5E", "#7B2D8E"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"providence aetna washington" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.72,
    nationalMedian: 1.0,
    networkComplaints: 1243,
    priorYearComplaints: 987,
    regulatorAction: "WA Office of the Insurance Commissioner issued briefing memo Aug 30 — just 2 days after public disclosure. Speed of regulatory engagement likely accelerated resolution. No formal enforcement action required due to rapid deal Sept 3.",
    signalRead: "Aetna's WA complaint index is moderately elevated (1.72x median). The Providence dispute added to existing Aetna-provider tensions across WA. UW Medicine parallel dispute in 2025 suggests systemic pattern in Aetna's WA network strategy rather than Providence-specific issue.",
  },

  // Executive summary
  executiveSummary: {
    statement: "The dispute resolved in just 5 days (Sept 1 expiration, deal Sept 3) — a remarkably fast resolution driven by Providence's strategic sequencing, WA OIC regulatory pressure, and Aetna's weakened negotiating position after Providence publicly isolated them by resolving with Cigna first.",
    keyMessages: [
      "Providence's $1.2B operating loss vs CVS/Aetna's $3.7B Q2 operating income is the defining financial contrast — nonprofit mission vs for-profit extraction.",
      "Strategic sequencing (Cigna deal publicized first) isolated Aetna as the lone holdout insurer, making 'Providence is unreasonable' framing untenable.",
      "WA's 5-day resolution vs Oregon's ~year-long dispute demonstrates that state regulatory environment and provider strategy dramatically affect outcomes.",
      "No named WA patient stories emerged due to the 5-day window — but Oregon's Bob Dragoon story shows the human cost when disputes drag on.",
    ],
    marcomm: [
      "<strong>The nonprofit vs for-profit contrast is Providence's trump card.</strong> $1.2B loss vs $3.7B operating income and $858M to shareholders — no affordability argument can overcome this optics gap. CFO Hoffman's quote crystallized it perfectly.",
      "<strong>Strategic sequencing is the playbook innovation.</strong> Resolving Cigna first and publicizing it isolated Aetna as the lone holdout. This is replicable for any multi-payor negotiation — resolve the easier deal first, publicly.",
      "<strong>Speed killed Aetna's counter-narrative.</strong> 5 days was not enough time for Aetna to build employer coalition support, generate counter-media, or shift blame effectively. Providence's first-mover advantage in media framing was never challenged.",
      "<strong>Oregon is the cautionary tale that WA avoided.</strong> Same parties, same issues, ~year to resolve in OR vs 5 days in WA. The difference: WA OIC engagement, Providence's learned strategy, and Aetna's weakened position after WA publicly exposed the pattern.",
    ],
  },
  channelTakeaways: {
    media: [
      "Seattle Times broke the story and set the Providence-sympathetic frame that all subsequent coverage adopted.",
      "TV stations (KIRO 7, KING 5, FOX 13) amplified patient anxiety angle — 35,000 patients across 5 facility brands created broad local impact.",
      "Trade press (Becker's, Fierce, Health Leaders) framed the resolution as a strategic win for health systems — Providence as a negotiation model.",
      "Oregon context coverage (KGW, KPTV, Willamette Week) provides the cautionary tale — Bob Dragoon's daughter story is the human cost of protracted disputes.",
    ],
    social: [
      "5-day window prevented sustained viral social media moment — dispute resolved before organic outrage could fully develop.",
      "UNITE HERE union alerts activated organized labor networks against Aetna/CVS profitability framing.",
      "Reddit r/Seattle and Facebook Providence patient groups generated localized anxiety but without the national amplification seen in longer disputes.",
      "Swedish brand recognition drove significant engagement — many Seattle residents identify with Swedish more than Providence corporate.",
    ],
    stakeholder: [
      "WA OIC briefing memo (Aug 30) was the fastest regulatory response in the dataset — 2 days from public disclosure to formal regulatory engagement.",
      "Providence CFO Greg Hoffman's for-profit/nonprofit contrast was the single most effective framing of the entire dispute.",
      "Providence's Cigna-first sequencing strategy is the key tactical innovation — isolating Aetna as the holdout undermined their negotiating position.",
      "UW Medicine parallel dispute with Aetna (2025) confirms pattern of Aetna WA network aggression — Providence was not uniquely unreasonable.",
    ],
    employer: [
      "City of Seattle HR FAQ signals government employer concern — elected officials' employees directly affected by Aetna network disruption.",
      "Sept 1 = Labor Day weekend timing maximized employer frustration with Aetna for not resolving before holiday.",
      "Providence's dominant WA market position means Aetna networks without Providence/Swedish/Kadlec are significantly weakened — employer leverage against Aetna.",
    ],
  },
};
