// Providence vs Cigna — PR War Room Config
// Dispute period: July–August 2024. Resolved August 8, 2024 (before September 1 deadline).
// Short-lived public dispute in WA. Providence resolved Cigna first, then isolated Aetna.

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2024-07-16",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "Providence, Cigna fail to reach contract agreement in Washington — patients face potential disruption",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press first coverage. Balanced reporting on contract impasse. Notes Providence's 51 hospitals and 1,100+ clinics across 7 states. Hospital executive audience.",
  },
  {
    id: 2,
    date: "2024-07-18",
    source: "Fierce Healthcare",
    sourceType: "news",
    channel: "media",
    headline: "Providence-Cigna contract dispute threatens network access in Washington state",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press. Notes Providence's operating loss of $1.2B in 2023 and costs up 26% since 2019. Frames as financial sustainability issue for health system.",
  },
  {
    id: 3,
    date: "2024-07-22",
    source: "Seattle Times",
    sourceType: "news",
    channel: "media",
    headline: "Providence, Swedish hospitals at odds with insurer Cigna over contract in Washington",
    frameAdoption: "providence",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Key regional outlet. Names WA entities: Providence, Swedish, Kadlec, PacMed, Health Connect Partners, INHS, St. Luke's Rehab. Local readership highly engaged with hospital access stories.",
  },
  {
    id: 4,
    date: "2024-07-23",
    source: "KIRO 7",
    sourceType: "tv",
    channel: "media",
    headline: "Providence and Cigna contract talks stall — WA patients worry about losing hospital access",
    frameAdoption: "providence",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Seattle TV market. Patient anxiety framing. Providence's WA footprint (Swedish, Kadlec) makes this a broad regional access story.",
  },
  {
    id: 5,
    date: "2024-07-25",
    source: "MyNorthwest",
    sourceType: "news",
    channel: "media",
    headline: "Providence-Cigna contract dispute could leave Washington patients scrambling for care",
    frameAdoption: "providence",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Regional digital outlet. 'Scrambling for care' framing places burden on patients. Covers Swedish and Kadlec specifically.",
  },
  {
    id: 6,
    date: "2024-07-26",
    source: "Daily Chronicle",
    sourceType: "news",
    channel: "media",
    headline: "Providence hospitals warn patients of potential Cigna network exit in WA",
    frameAdoption: "providence",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Local outlet. Providence-sympathetic framing — 'warn patients' positions Providence as protecting, Cigna as threatening.",
  },
  {
    id: 7,
    date: "2024-07-28",
    source: "Daily Chronicle",
    sourceType: "news",
    channel: "media",
    headline: "Community concern grows over Providence-Cigna contract standoff",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Follow-up coverage. Community reaction angle. Notes concurrent Aetna dispute amplifying local anxiety.",
  },
  {
    id: 8,
    date: "2024-07-29",
    source: "Snohomish County Tribune",
    sourceType: "news",
    channel: "media",
    headline: "Swedish hospital patients face uncertainty as Providence-Cigna contract expires",
    frameAdoption: "providence",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Hyperlocal outlet. Swedish is a major employer and care provider in Snohomish County. Local impact angle resonates with community.",
  },
  {
    id: 9,
    date: "2024-07-30",
    source: "KIRO 7",
    sourceType: "tv",
    channel: "media",
    headline: "Deadline looms for Providence and Cigna to reach deal — patients urged to check coverage",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Second KIRO segment. Urgency framing as deadline approaches. Practical guidance for patients. TV audience skews older — key commercial insurance demographic.",
  },
  {
    id: 10,
    date: "2024-08-01",
    source: "Healthcare Dive",
    sourceType: "news",
    channel: "media",
    headline: "Providence faces multiple insurer disputes as operating losses mount — Cigna, Aetna, Blue Shield",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National trade. Systemic framing — notes concurrent disputes with Aetna (WA/OR), Blue Shield (CA), and UHC (MA). Providence's $1.2B operating loss contextualized against costs up ~20% since pandemic.",
  },
  {
    id: 11,
    date: "2024-08-08",
    source: "Providence Blog",
    url: "https://blog.providence.org/south-puget-sound-medical-staff-updates/providence-and-cigna-reach-tentative-agreement-on-commercial-contract-for-wa-negotiations-with-aetna-continue",
    sourceType: "owned",
    channel: "media",
    headline: "Providence and Cigna reach tentative agreement — continuity of care preserved for WA patients",
    frameAdoption: "providence",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "RESOLUTION ANNOUNCEMENT. Providence claims credit for 'preserving continuity of care.' Tentative agreement reached before Sept 1 deadline. Victory framing — resolved quickly, patients protected.",
  },
  {
    id: 12,
    date: "2024-08-09",
    source: "Providence Blog",
    url: "https://blog.providence.org/washington/faq-providence-cigna-negotiations-in-washington",
    sourceType: "owned",
    channel: "media",
    headline: "Providence-Cigna FAQ: What the new agreement means for your care",
    frameAdoption: "providence",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Patient-facing FAQ. Reassurance messaging. Directs patients to continue scheduling normally. Professional communication strategy.",
  },
  {
    id: 13,
    date: "2024-08-15",
    source: "Providence Blog",
    url: "https://blog.providence.org/northwest-everett/providence-has-renewed-our-contracts-with-cigna-in-washington",
    sourceType: "owned",
    channel: "media",
    headline: "Providence announces renewed contracts with Cigna across Washington entities",
    frameAdoption: "providence",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Final confirmation post. Lists all WA entities covered: Providence, Swedish, Kadlec, PacMed, Health Connect Partners, INHS, St. Luke's Rehab. Strategic: resolving Cigna first isolates Aetna.",
  },
  {
    id: 14,
    date: "2024-07-20",
    source: "Swedish.org",
    sourceType: "owned",
    channel: "media",
    headline: "Swedish Health Services: Important update on Cigna insurance coverage",
    frameAdoption: "providence",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Swedish-branded patient communication. Swedish is Providence's most prominent WA brand. Directs patients to contact Cigna with questions — subtly shifts burden to insurer.",
  },
  {
    id: 15,
    date: "2024-08-10",
    source: "Swedish.org",
    sourceType: "owned",
    channel: "media",
    headline: "Swedish confirms renewed Cigna contract — patients can continue care uninterrupted",
    frameAdoption: "providence",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution confirmation from Swedish. 'Uninterrupted' framing claims credit for preventing disruption.",
  },
  {
    id: 16,
    date: "2024-08-28",
    source: "Seattle Times",
    url: "https://www.seattletimes.com/seattle-news/health/35000-providence-patients-in-wa-could-soon-lose-in-network-coverage/",
    sourceType: "news",
    channel: "media",
    headline: "35,000 Aetna patients face Providence network exit — Cigna resolved but Aetna deadline looms Sept 1",
    frameAdoption: "providence",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CRITICAL CONTEXT: 35K Aetna patients quantified. Cigna resolution referenced as contrast — Providence willing to deal, Aetna is the holdout. Providence's strategy of resolving Cigna first is working narratively.",
  },
  {
    id: 17,
    date: "2024-09-03",
    source: "Seattle Times",
    url: "https://www.seattletimes.com/seattle-news/health/providence-and-aetna-reach-new-multiyear-agreement/",
    sourceType: "news",
    channel: "media",
    headline: "Providence and Aetna reach last-minute agreement — all WA insurer disputes resolved",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Aetna resolution coverage. Providence's sequential strategy succeeded: Cigna first (Aug 8), then Aetna (early Sept). Both resolved before actual patient disruption.",
  },
  {
    id: 18,
    date: "2024-08-05",
    source: "NBC News",
    sourceType: "news",
    channel: "media",
    headline: "Hospitals and insurers battle over rates as patients get caught in crossfire — national trend piece",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "National trend coverage. Providence/Cigna mentioned alongside other disputes. Systemic framing normalizes Providence's position. Notes rising hospital costs and insurer profit margins.",
  },
  {
    id: 19,
    date: "2024-07-30",
    source: "KFF Health News",
    sourceType: "news",
    channel: "media",
    headline: "Hospital-insurer contract disputes rising nationally — patients bear the burden",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "KFF policy coverage. Trend piece referencing multiple disputes including Providence/Cigna. Gold standard for health policy analysis.",
  },
  {
    id: 20,
    date: "2024-08-20",
    source: "KFF Health News",
    sourceType: "news",
    channel: "media",
    headline: "When your hospital and insurer can't agree: navigating network disruptions",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Patient-focused explainer. Providence/Cigna cited as recent example. Systemic framing helps Providence — dispute is industry-wide, not Providence-specific.",
  },
  {
    id: 21,
    date: "2024-08-02",
    source: "HFMA",
    sourceType: "news",
    channel: "media",
    headline: "Providence's financial pressures: $1.2B operating loss, costs up 26% since 2019",
    frameAdoption: "providence",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Healthcare Financial Management Association. Financial context: Providence operating loss $1.2B (2023), costs up 26% since 2019. Contrasts with Cigna's $6.7B operating earnings (2022) and $9B in dividends/buybacks.",
  },
  {
    id: 22,
    date: "2024-07-25",
    source: "DistilINFO",
    sourceType: "news",
    channel: "media",
    headline: "Providence-Cigna contract dispute adds to wave of hospital-insurer standoffs",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Health IT trade press. Systemic framing. Notes multiple concurrent Providence disputes.",
  },
  {
    id: 23,
    date: "2024-07-22",
    source: "FTI Consulting data",
    sourceType: "news",
    channel: "media",
    headline: "FTI data: Hospital cost increases outpacing commercial reimbursement rates by wide margin",
    frameAdoption: "providence",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Consulting firm data supporting Providence's cost narrative. Hospital costs up ~20% since pandemic while insurer reimbursement lags. Provides third-party validation for rate increase requests.",
  },
  {
    id: 24,
    date: "2024-08-01",
    source: "FTI Consulting data",
    sourceType: "news",
    channel: "media",
    headline: "FTI analysis: Insurer operating earnings vs hospital operating margins — growing divergence",
    frameAdoption: "providence",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Second FTI data point. Cigna's $6.7B operating earnings and $9B dividends/buybacks vs Providence's $1.2B loss. Powerful contrast used in Providence's public messaging.",
  },
  {
    id: 25,
    date: "2024-07-18",
    source: "Cigna Newsroom",
    sourceType: "owned",
    channel: "media",
    headline: "Cigna statement on Providence contract negotiations in Washington and Oregon",
    frameAdoption: "cigna",
    sentiment: "negative_providence",
    patientStory: false,
    blameDirection: "providence",
    reachEstimate: "medium",
    notes: "Cigna's public position. References prior Oregon resolution (2023) as evidence of willingness to negotiate. Corporate tone. Notes commitment to 'affordable, quality care.'",
  },
  // === OREGON CONTEXT ENTRIES ===
  {
    id: 26,
    date: "2024-07-20",
    source: "Spokesman-Review",
    sourceType: "news",
    channel: "media",
    headline: "Providence contract disputes stretch across Pacific Northwest — Spokane patients watch WA situation",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Eastern WA/Spokane outlet. Notes Providence's multi-state footprint and concurrent disputes. Kadlec in Tri-Cities specifically mentioned.",
  },
  {
    id: 27,
    date: "2024-07-24",
    source: "KGW",
    sourceType: "tv",
    channel: "media",
    headline: "Providence-insurer disputes in Oregon context — patients caught between hospitals and insurers",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Portland TV. Oregon context for Providence disputes. Cross-state coverage amplifies perception of systemic insurer underpayment.",
  },
  {
    id: 28,
    date: "2024-07-26",
    source: "KPTV",
    sourceType: "tv",
    channel: "media",
    headline: "Oregon Providence patients nervously watch WA Cigna dispute unfold",
    frameAdoption: "providence",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Portland FOX affiliate. Patient anxiety extends across state lines given Providence's OR/WA footprint.",
  },
  {
    id: 29,
    date: "2024-07-28",
    source: "Willamette Week",
    sourceType: "news",
    channel: "media",
    headline: "Providence's insurer battles: What Oregon patients need to know about the Cigna and Aetna disputes",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Portland alt-weekly. Explainer format. Notes Providence's concurrent Aetna WA/OR and Blue Shield CA disputes alongside Cigna WA.",
  },
  {
    id: 30,
    date: "2024-07-30",
    source: "Providence Blog (OR)",
    url: "https://blog.providence.org/providence-oregon-provider-updates/important-update-providence-and-cigna-negotiations",
    sourceType: "owned",
    channel: "media",
    headline: "Providence Oregon: Update on insurance negotiations affecting Pacific Northwest patients",
    frameAdoption: "providence",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Oregon-specific Providence communication. Cross-references WA Cigna situation. Coordinated messaging across state entities.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 31,
    date: "2024-07-22",
    source: "Facebook (Providence patient groups)",
    sourceType: "social",
    channel: "social",
    headline: "Providence patients share Cigna contract concerns on Facebook community groups",
    frameAdoption: "providence",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Organic patient discussion. Facebook groups for Swedish, Providence patients. Anxiety about losing access to established providers. Older demographic skews toward commercial insurance.",
  },
  {
    id: 32,
    date: "2024-07-25",
    source: "Nextdoor (WA communities)",
    sourceType: "social",
    channel: "social",
    headline: "Nextdoor threads in Seattle-area neighborhoods: 'Has anyone else gotten the letter about Providence and Cigna?'",
    frameAdoption: "providence",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Hyperlocal social platform. Neighborhood-level discussion. Providence/Swedish patients in Seattle, Bellevue, Everett communities. High credibility among neighbors sharing personal experience.",
  },
  {
    id: 33,
    date: "2024-07-28",
    source: "Providence MyChart messages",
    sourceType: "owned",
    channel: "social",
    headline: "Providence sends MyChart notifications to Cigna patients about contract status",
    frameAdoption: "providence",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "DIRECT PATIENT CHANNEL. MyChart messages reach patients directly in their health portal. High open rate. Providence controls the narrative at point of patient engagement. Directs patients to contact Cigna.",
  },
  // === PATIENT ENTRIES ===
  {
    id: 34,
    date: "2024-07-24",
    source: "KGW (OR context)",
    sourceType: "tv",
    channel: "media",
    headline: "Bob Dragoon's daughter (34, stomach cancer) fears losing Providence access amid insurer disputes in Oregon",
    frameAdoption: "providence",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "NAMED PATIENT (OR context). Bob Dragoon's daughter, 34, battling stomach cancer. Fear of losing Providence oncology access. Young cancer patient with parent advocate — highly sympathetic. Oregon dispute context but amplifies WA narrative.",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 35,
    date: "2024-07-22",
    source: "WA Office of Insurance Commissioner (OIC)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "WA OIC monitoring Providence-Cigna contract dispute — briefing issued to stakeholders",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "State regulator engagement. OIC monitoring but not formally intervening in short-lived dispute. Briefing signals seriousness without escalation.",
  },
  {
    id: 36,
    date: "2024-07-25",
    source: "City of Seattle HR",
    sourceType: "news",
    channel: "stakeholder",
    headline: "City of Seattle HR department issues advisory to employees on Providence-Cigna contract status",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Major public employer in WA. City employees with Cigna plans using Providence/Swedish facilities. Employer advisory signals material impact on workforce. Government employer action adds political dimension.",
  },
  {
    id: 37,
    date: "2024-08-01",
    source: "WA Attorney General enforcement context",
    sourceType: "news",
    channel: "stakeholder",
    headline: "WA AG context: $157.8M in healthcare enforcement actions — regulatory environment is active",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "REGULATORY CONTEXT. WA AG has pursued $157.8M in healthcare enforcement. Active regulatory environment creates backdrop pressure on both parties to resolve quickly. Neither side wants AG attention.",
  },
  {
    id: 38,
    date: "2024-07-28",
    source: "UNITE HERE",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "UNITE HERE union monitors Providence-Cigna dispute impact on hospitality worker health benefits",
    frameAdoption: "providence",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Union stakeholder. Hospitality workers with Cigna plans relying on Providence/Swedish facilities in Seattle metro. Labor voice adds political pressure.",
  },
  {
    id: 39,
    date: "2024-08-01",
    source: "NW Women's HealthCare",
    sourceType: "news",
    channel: "stakeholder",
    headline: "NW Women's HealthCare publishes FAQ on Providence-Cigna dispute for OB/GYN patients",
    frameAdoption: "providence",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Affiliated practice FAQ. OB/GYN patients mid-pregnancy concerned about hospital access. Highly sympathetic patient population. Practice-level communication amplifies Providence messaging.",
  },
  {
    id: 40,
    date: "2024-07-30",
    source: "LA/Orange County HR departments (SoCal parallel)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Southern California public employers monitor Providence insurer disputes — potential spillover concern",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "SoCal parallel. Providence's 7-state footprint means disputes in WA create anxiety in CA employer markets. LA/Orange County HR tracking situation alongside Blue Shield CA dispute.",
  },
  {
    id: 41,
    date: "2024-08-05",
    source: "Providence health plan sale exploration",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Providence exploring sale of health plan division — strategic repositioning amid insurer disputes",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Strategic context. Providence considering health plan sale signals financial restructuring. May indicate system pivoting away from insurance business to focus on care delivery. Adds complexity to insurer negotiation dynamics.",
  },
];

const LABELS = {
  frameAdoption: { providence: "Providence Frame", cigna: "Cigna Frame", balanced: "Balanced" },
  sentiment: {
    negative_cigna: "Anti-Cigna",
    negative_providence: "Anti-Providence",
    neutral: "Neutral",
    positive_cigna: "Pro-Cigna",
    positive_providence: "Pro-Providence",
  },
  blameDirection: { cigna: "Blames Cigna", providence: "Blames Providence", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National record (1.5)
  "NBC News": 1.5, "KFF Health News": 1.5,
  // Tier 2 — Regional authority (1.2)
  "Seattle Times": 1.2, "KIRO 7": 1.2, "KGW": 1.2, "KPTV": 1.2, "Spokesman-Review": 1.2,
  // Tier 3 — Trade/niche (1.0)
  "Becker's Hospital Review": 1.0, "Fierce Healthcare": 1.0, "Healthcare Dive": 1.0,
  "HFMA": 1.0, "DistilINFO": 1.0, "MyNorthwest": 1.0, "Willamette Week": 1.0,
  "Daily Chronicle": 1.0, "Snohomish County Tribune": 1.0,
  "FTI Consulting data": 1.0,
  // Tier 4 — Organic social (0.7)
  "Facebook (Providence patient groups)": 0.7, "Nextdoor (WA communities)": 0.7,
  // Tier 5 — Comment sections (0.4)
  // Tier 6 — Owned/party media (0.3)
  "Providence Blog": 0.3, "Providence Blog (OR)": 0.3, "Swedish.org": 0.3,
  "Providence MyChart messages": 0.3, "Cigna Newsroom": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "WA Office of Insurance Commissioner (OIC)": 1.3, "City of Seattle HR": 1.3,
  "WA Attorney General enforcement context": 1.3, "UNITE HERE": 1.3,
  "NW Women's HealthCare": 1.3, "LA/Orange County HR departments (SoCal parallel)": 1.3,
  "Providence health plan sale exploration": 1.3,
  // Tier 8 — Employer/Benefits (1.5)
  "Bob Dragoon's daughter (34, stomach cancer)": 1.2,
  "KGW (OR context)": 1.2,
};

const SEARCH_TRENDS = [
  { week: "2024-07-01", interest: 3 }, { week: "2024-07-15", interest: 10 },
  { week: "2024-08-01", interest: 15 }, { week: "2024-08-08", interest: 40 },
  { week: "2024-08-28", interest: 80 }, { week: "2024-08-29", interest: 80 },
  { week: "2024-09-01", interest: 100 }, { week: "2024-09-03", interest: 70 },
  { week: "2024-09-15", interest: 10 },
];

export default {
  active: false,
  // Identity
  providerKey: "providence",
  payorKey: "cigna",
  providerName: "Providence",
  payorName: "Cigna",
  providerShort: "Providence",
  payorShort: "Cigna",
  navShort: "Providence v. Cigna",
  title: "Providence vs Cigna",
  subtitle: "Contract dispute · WA · Resolved August 8, 2024",
  gradientId: "providencecigna",

  // Dates
  monitorStart: "July 1, 2024",
  monitorEnd: "September 30, 2024",
  disputeStatus: "resolved",
  disputePublicDate: "2024-07-15",

  // Colors
  colors: {
    providerColor: "#1B6B3A",
    payorColor: "#E87722",
    neutral: "#5D7380",
    accent: "#1B6B3A",
    bg: "#ffffff",
    surface: "#f2f7fb",
    surfaceHover: "#e8f0f7",
    border: "#c8dce8",
    text: "#053b57",
    textMuted: "#5D7380",
  },
  distColors: ["#1B6B3A", "#4A7A56", "#E87722"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"providence cigna contract washington" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.42,
    nationalMedian: 1.0,
    networkComplaints: 892,
    priorYearComplaints: 734,
    regulatorAction: "WA OIC monitored dispute but did not formally intervene. WA AG context of $157.8M in healthcare enforcement actions created backdrop pressure. Dispute resolved too quickly (under 4 weeks public) for regulatory escalation.",
    signalRead: "Cigna's complaint index is modestly elevated (1.42x median). The short duration of the public dispute limited complaint accumulation. Providence's strategy of resolving Cigna first, then isolating Aetna, minimized regulatory exposure on this front.",
  },

  talkingPoints: {
    provider: [
      { name: "$1.2B loss vs Cigna $6.7B earnings", keywords: ["\\$1\\.2B", "1\\.2 billion", "operating loss", "\\$6\\.7B", "6\\.7B", "\\$9B.*dividend", "9B.*buyback"] },
      { name: "Costs up 26% since 2019", keywords: ["26%", "costs up 26", "cost.*since 2019", "cost.*risen", "20%.*pandemic"] },
      { name: "FTI cost data / third-party validation", keywords: ["FTI", "hospital cost.*outpac", "reimbursement.*lag", "third-party", "divergence"] },
      { name: "Patient access / network disruption", keywords: ["lose.*access", "network exit", "disruption", "scrambling for care", "lose.*hospital"] },
      { name: "Swedish brand impact", keywords: ["Swedish", "Swedish Health", "Swedish Medical", "Swedish.*brand"] },
      { name: "MyChart / direct patient messaging", keywords: ["MyChart", "patient portal", "direct.*channel", "contact Cigna"] },
      { name: "Speed of resolution", keywords: ["four weeks", "under 4 weeks", "quickly", "speed", "prevented.*escalation"] },
      { name: "Sequential strategy / isolate Aetna", keywords: ["Cigna.*first", "resolved.*first", "isolat.*Aetna", "35,000.*Aetna", "holdout", "divide-and-conquer"] },
    ],
    payor: [
      { name: "Affordable quality care", keywords: ["affordable", "quality care", "affordable.*care", "commitment.*affordable"] },
      { name: "Prior Oregon resolution precedent", keywords: ["Oregon resolution", "prior.*resolution", "2023.*resolution", "willingness.*negotiate"] },
      { name: "Concurrent Providence disputes", keywords: ["concurrent", "multiple.*disput", "Aetna.*Blue Shield.*UHC", "maybe Providence.*problem", "Providence.*the problem"] },
      { name: "Regulatory environment / AG", keywords: ["\\$157\\.8M", "157\\.8M", "AG.*enforcement", "Attorney General", "regulat", "OIC"] },
      { name: "Providence financial distress", keywords: ["\\$1\\.2B.*loss", "financial pressur", "operating loss.*mount", "health plan sale", "restructur"] },
      { name: "Employer / union impact", keywords: ["City of Seattle", "UNITE HERE", "employer.*advis", "hospitality worker"] },
    ],
  },

  // Executive summary
  executiveSummary: {
    statement: "Providence resolved the Cigna dispute in under four weeks of public tension (Aug 8, before Sept 1 deadline), then strategically used the resolution to isolate Aetna as the lone holdout. A short-lived dispute with no quantified patient disruption.",
    keyMessages: [
      "Providence's $1.2B operating loss (2023) vs Cigna's $6.7B operating earnings and $9B dividends/buybacks is a devastating financial contrast that anchors the cost narrative.",
      "The dispute was strategically sequenced: Cigna resolved first, then used as precedent to pressure Aetna — classic divide-and-conquer negotiation.",
      "Patients at risk were never publicly quantified, limiting the emotional intensity compared to disputes with named patient counts.",
      "WA's active regulatory environment ($157.8M AG enforcement) created mutual pressure to resolve quickly without formal state intervention.",
    ],
    marcomm: [
      "<strong>Speed was the strategy.</strong> Providence resolved Cigna in under four weeks of public dispute, preventing the emotional escalation that longer disputes generate. This limited media oxygen and kept the narrative manageable for both sides.",
      "<strong>The financial contrast is Providence's strongest card.</strong> A $1.2B operating loss vs $6.7B insurer earnings and $9B in shareholder returns is a simple, powerful message that resonates with patients, media, and regulators alike.",
      "<strong>Sequential resolution was masterful.</strong> By resolving Cigna first, Providence demonstrated willingness to negotiate — making Aetna look unreasonable as the sole holdout with 35,000 patients at risk.",
      "<strong>Concurrent disputes are a double-edged sword.</strong> Providence fighting Cigna, Aetna, Blue Shield, and UHC simultaneously risks the 'maybe Providence is the problem' counter-narrative. Speed of resolution mitigates this risk.",
    ],
  },
  channelTakeaways: {
    media: [
      "Seattle Times was the anchor regional outlet — two key stories framing the dispute and later providing Aetna contrast (35K patients).",
      "KIRO 7 provided the primary TV coverage in the Seattle market with two segments driving patient awareness.",
      "Trade press (Becker's, Fierce, Healthcare Dive) framed this as part of a systemic trend, normalizing Providence's position.",
      "Oregon outlets (KGW, KPTV, Willamette Week) extended coverage across state lines given Providence's PNW footprint.",
    ],
    social: [
      "Facebook and Nextdoor generated organic community discussion but at lower intensity than longer disputes.",
      "Providence's MyChart messaging was the highest-impact direct patient channel — controlled narrative at point of care.",
      "Short dispute duration limited viral social media escalation compared to multi-month standoffs.",
    ],
    stakeholder: [
      "WA OIC monitored but did not intervene — dispute resolved before regulatory escalation was needed.",
      "City of Seattle HR advisory added political dimension as a major public employer with affected workers.",
      "WA AG's $157.8M enforcement track record created background pressure for quick resolution.",
      "Providence exploring health plan sale added strategic complexity to the negotiation dynamic.",
    ],
    employer: [
      "City of Seattle HR was the most visible employer stakeholder, issuing direct employee advisories.",
      "LA/Orange County HR departments tracked the dispute for potential spillover to Providence's SoCal operations.",
      "UNITE HERE union engagement added labor voice to the predominantly corporate negotiation.",
    ],
  },
  arguments: {
    payor: [
      { phase: "Early (Jul 2024)", points: ["Cigna Newsroom referenced prior Oregon resolution (2023) as evidence of <strong>willingness to negotiate</strong>", "Maintained corporate commitment to 'affordable, quality care' — standard insurer affordability framing"] },
      { phase: "Resolution (Aug 2024)", points: ["Agreed to renewed contracts across all WA entities — Providence, Swedish, Kadlec, PacMed, Health Connect Partners, INHS, St. Luke's Rehab", "Cigna resolved before Aetna, avoiding the <strong>'sole holdout'</strong> narrative that later damaged Aetna"] },
    ],
    provider: [
      { phase: "Early (Jul 2024)", points: ["Cited <strong>$1.2B operating loss (2023)</strong> and costs up 26% since 2019 as core financial justification", "Contrasted Providence's losses against Cigna's <strong>$6.7B operating earnings and $9B in dividends/buybacks</strong> — devastating financial comparison", "FTI Consulting data provided third-party validation that hospital costs outpaced commercial reimbursement"] },
      { phase: "Mid-Dispute (Jul–Aug 2024)", points: ["Swedish-branded patient communications and <strong>MyChart messaging</strong> controlled the narrative at point of care", "Directed patients to contact Cigna with questions — subtly shifted the burden to the insurer", "WA regulatory environment ($157.8M AG enforcement) created mutual pressure for quick resolution"] },
      { phase: "Resolution (Aug 2024)", points: ["Resolved Cigna in under four weeks of public tension — <strong>speed prevented emotional escalation</strong>", "Strategically resolved Cigna first, then used it as precedent to isolate Aetna as the <strong>sole holdout with 35,000 patients at risk</strong>", "Sequential resolution was described as 'masterful' divide-and-conquer negotiation"] },
    ],
  },
  timeline: [
    { date: "2024-07-16", type: "newsBreak", label: "News breaks publicly" },
    { date: "2024-08-08", type: "agreement", label: "Agreement reached" },
  ],
};
