// Scripps Health vs Anthem Blue Cross — PR War Room Config
// Dispute period: October 2024–May 2025. Extended May 6, 2025 (through Sept 2026).

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2024-10-17",
    source: "San Diego Union-Tribune",
    sourceType: "news",
    channel: "media",
    headline: "Scripps Health warns 125,000+ patients it may leave Anthem network — letters sent",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "FIRST MAJOR COVERAGE. Scripps sends letters to 125,000+ Anthem policyholders warning of potential network exit. Sets the dispute's public narrative. ~14,000 Covered California enrollees among those affected. Scripps fires first public salvo.",
  },
  {
    id: 2,
    date: "2024-10-18",
    source: "NBC 7 San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "Scripps Health may drop Anthem insurance — 125,000 patients notified",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Local NBC affiliate picks up story immediately. 125,000 number dominates framing. Patient anxiety begins.",
  },
  {
    id: 3,
    date: "2024-10-18",
    source: "Fox 5 San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "Scripps Health warns patients about Anthem contract — could lose access to 5 hospitals, 30 clinics",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Fox 5 emphasizes scale: 5 hospital campuses, 30 outpatient centers, ~3,000 affiliated physicians. Infrastructure framing makes the stakes visceral.",
  },
  {
    id: 4,
    date: "2024-10-19",
    source: "CBS 8 San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "Scripps-Anthem contract dispute could displace thousands of San Diego patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CBS 8 provides balanced initial coverage. Both sides quoted. 'Displace' framing is patient-sympathetic.",
  },
  {
    id: 5,
    date: "2024-10-21",
    source: "10News ABC San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "Patients scramble after Scripps Health warns of Anthem Blue Cross split",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "10News begins its deep patient-story coverage. 'Scramble' framing places burden on patients. Susan Beeson (Carlsbad) featured: rescheduling surgery to beat potential deadline.",
  },
  {
    id: 6,
    date: "2024-11-15",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "Scripps Health may exit Anthem network over reimbursement dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press picks up dispute. Notes Scripps lost ~$75M/yr on Medicare Advantage before exiting Jan 2024. Hospital executive audience sees pattern of payer underpayment.",
  },
  {
    id: 7,
    date: "2024-12-07",
    source: "San Diego Union-Tribune (column)",
    sourceType: "opinion",
    channel: "media",
    headline: "Column: Scripps-Anthem fight shows how insurance companies squeeze hospitals — and patients pay",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Opinion column with systemic framing. Cites Scripps compensation costs up >8%/yr, pharma >14%/yr (2021-2024). Anthem/Elevance $108.92B total assets. Rhonda Guaderrama: 12-year patient, 'stressful and really mad.'",
  },
  {
    id: 8,
    date: "2024-12-18",
    source: "10News ABC San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "Angel Coronel's brain surgery recovery threatened by Scripps-Anthem dispute — daily rehab at $1,000+/day",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "MOST IMPACTFUL PATIENT STORY. Angel Coronel: brain surgery recovery, daily rehabilitation at $1,000+/day. 10News follows him in multi-part series. Brain rehab patient losing access is maximally sympathetic.",
  },
  {
    id: 9,
    date: "2024-12-20",
    source: "Fox 5 San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "Countdown to deadline: Scripps patients face Jan 1 Anthem network exit",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Deadline anxiety coverage intensifies. Kirsten Lozano (Escondido, 51): ulcerative colitis, authorizations repeatedly canceled. Fox 5 covers multiple patient stories in final weeks.",
  },
  {
    id: 10,
    date: "2024-12-23",
    source: "CBS 8 San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "Scripps patients racing to get care before Anthem deadline — Susan Beeson reschedules surgery",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Susan Beeson (Carlsbad) rescheduled surgery to beat Dec 31 deadline. Holiday-season coverage amplifies emotional resonance. 'Racing to get care' is devastating framing.",
  },
  {
    id: 11,
    date: "2024-12-27",
    source: "10News ABC San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "Angel Coronel update: brain rehab patient faces uncertain future as Scripps-Anthem deadline looms",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Continuation of Angel Coronel series. 10News commitment to following one patient creates narrative arc that builds audience investment. Daily rehab at $1,000+/day OON would be catastrophic.",
  },
  {
    id: 12,
    date: "2024-12-30",
    source: "California Healthline",
    sourceType: "news",
    channel: "media",
    headline: "Scripps Health, Anthem Blue Cross fail to reach deal — 125,000 patients face network exit",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Statewide health policy outlet. Balanced framing but patient-impact focus. Notes ~14,000 Covered California enrollees affected. California Healthline is KFF's state partner — high credibility.",
  },
  {
    id: 13,
    date: "2024-12-31",
    source: "San Diego Union-Tribune",
    sourceType: "news",
    channel: "media",
    headline: "Scripps Health goes out of network for Anthem as contract expires with no deal",
    frameAdoption: "balanced",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Deadline-day coverage. Contract officially expires. 'No deal' framing. 125,000 patients now out-of-network. The largest provider-payor split in San Diego history.",
  },
  {
    id: 14,
    date: "2025-01-01",
    source: "NBC 7 San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "New Year, new reality: Scripps out of network for all Anthem plans starting today",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Jan 1 coverage. New Year framing amplifies disruption. Patients waking up to new OON reality. Multiple patient stories. Regina Key (Solana Beach): 'rollercoaster ride.'",
  },
  {
    id: 15,
    date: "2025-01-01",
    source: "Fox 5 San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "Scripps-Anthem split takes effect — patients scramble for alternatives on New Year's Day",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "New Year's Day coverage. Pregnant Reddit user featured (c-section in 2 weeks). Unnamed patient: husband's oncology team at Scripps. Fox 5 continues aggressive patient-story focus.",
  },
  {
    id: 16,
    date: "2025-01-02",
    source: "10News ABC San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "Angel Coronel faces out-of-network costs for brain rehab — 10News continues series",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Post-split Angel Coronel update. Now actually OON. $1,000+/day rehab costs without in-network coverage. 10News series becomes the defining patient narrative of this dispute.",
  },
  {
    id: 17,
    date: "2025-01-03",
    source: "KPBS",
    sourceType: "news",
    channel: "media",
    headline: "Scripps Health drops out of Anthem network — what patients need to know",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "KPBS (NPR affiliate) provides service journalism. Balanced, explanatory coverage. KPBS audience is educated, policy-oriented. High credibility in San Diego market.",
  },
  {
    id: 18,
    date: "2025-01-07",
    source: "CBS 8 San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "Patients caught in Scripps-Anthem dispute share stories of denied claims and delayed care",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Post-split patient impact stories. Claims data emerging: Anthem denied 2,300 claims ($34M total). Appeals recovered only $6.5M. CBS 8 documents the real-world impact.",
  },
  {
    id: 19,
    date: "2025-01-10",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "Scripps CEO Van Gorder: hospitals face 'hospital deserts' as insurers underpay",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Van Gorder 'hospital deserts' quote. Systemic framing: Scripps is the 'vanguard of ugly few years between hospitals and commercial insurance.' Trade audience receptive to provider-side framing.",
  },
  {
    id: 20,
    date: "2025-01-15",
    source: "InsuranceNewsNet",
    sourceType: "news",
    channel: "media",
    headline: "Anthem-Scripps dispute leaves 125,000 San Diego patients without in-network access",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Insurance trade press. Balanced framing for insurance industry audience. Notes Anthem/Elevance $108.92B total assets context.",
  },
  {
    id: 21,
    date: "2025-01-22",
    source: "San Diego Union-Tribune",
    sourceType: "news",
    channel: "media",
    headline: "Systemic investigation: how insurer tactics — delay, deny, don't pay — are squeezing San Diego hospitals",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "MAJOR INVESTIGATIVE PIECE. Van Gorder: 'delay, deny or don't pay.' 800+ instances of Anthem reversing prior authorization after billing. Anthem denied 2,300 claims ($34M); appeals recovered only $6.5M. Systemic framing is devastating for Anthem.",
  },
  {
    id: 22,
    date: "2025-01-28",
    source: "HealthLeaders",
    sourceType: "news",
    channel: "media",
    headline: "Scripps Health vs Anthem: a case study in hospital-insurer brinksmanship",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Healthcare executive trade outlet. Case study framing. Notes Scripps compensation costs up >8%/yr, pharma >14%/yr. Balanced but cost-pressure narrative favors provider side.",
  },
  {
    id: 23,
    date: "2025-02-05",
    source: "BenefitPro",
    sourceType: "news",
    channel: "media",
    headline: "Anthem-Scripps split highlights growing employer exposure to network disruptions",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Benefits industry trade. Employer-focused framing. Notes ~10,000 UFCW Local 135 union workers affected. Employer audience concerned about workforce disruption.",
  },
  {
    id: 24,
    date: "2025-02-12",
    source: "Physicians News Network",
    sourceType: "news",
    channel: "media",
    headline: "San Diego physicians caught in Scripps-Anthem crossfire — prior auths reversed after billing",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "low",
    notes: "Physician-focused outlet. 800+ instances of Anthem reversing prior authorization after billing cited. Physician audience deeply sympathetic to Scripps. ~3,000 Scripps-affiliated physicians affected.",
  },
  {
    id: 25,
    date: "2025-02-20",
    source: "WSWS (World Socialist Web Site)",
    sourceType: "opinion",
    channel: "media",
    headline: "Scripps-Anthem dispute exposes for-profit healthcare system — both sides profiting while patients suffer",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Anti-both systemic critique. Blames for-profit healthcare model. Does not favor either party. Low mainstream reach but contributes to systemic narrative.",
  },
  {
    id: 26,
    date: "2025-03-01",
    source: "10News ABC San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "Kirsten Lozano: ulcerative colitis patient says Anthem keeps canceling her authorizations",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Kirsten Lozano (Escondido, 51): ulcerative colitis. Authorizations repeatedly canceled by Anthem. 10News continues deep patient-story coverage months into the dispute.",
  },
  {
    id: 27,
    date: "2025-03-10",
    source: "Coast News Group",
    sourceType: "news",
    channel: "media",
    headline: "North County patients struggle with Scripps-Anthem split — finding new doctors difficult",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "low",
    notes: "Hyper-local North County coverage. Patient difficulty finding alternative providers. Scripps dominates North County healthcare landscape — few alternatives.",
  },
  {
    id: 28,
    date: "2025-03-15",
    source: "Coast News Group",
    sourceType: "news",
    channel: "media",
    headline: "Carlsbad, Encinitas residents bear brunt of Scripps-Anthem dispute — community impact deepens",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "low",
    notes: "Second Coast News piece. Community-level impact. Affluent coastal communities with political influence. Local coverage sustains pressure.",
  },
  {
    id: 29,
    date: "2025-03-22",
    source: "Times of San Diego",
    sourceType: "news",
    channel: "media",
    headline: "Scripps-Anthem standoff enters fourth month with no resolution in sight",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Online-only San Diego outlet. Duration framing — 'fourth month' emphasizes how long patients have been affected. No resolution in sight increases pressure on both sides.",
  },
  {
    id: 30,
    date: "2025-04-01",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "Scripps Health CEO: insurers creating 'hospital deserts' through systematic underpayment",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Van Gorder 'hospital deserts' framing gains traction in trade press. Becker's covers his broader critique of commercial insurance model. Scripps lost ~$75M/yr on Medicare Advantage before exiting.",
  },
  {
    id: 31,
    date: "2025-04-10",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "Scripps Health among hospitals exiting Medicare Advantage plans over reimbursement shortfalls",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Broader MA exit trend piece. Scripps exited MA Jan 2024 after losing ~$75M/yr. Pattern evidence: payer underpayment is systemic. Hospital executive audience.",
  },
  {
    id: 32,
    date: "2025-04-18",
    source: "Fox 5 San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "Lisa Schmidt: rare disease patient forced to travel to Cleveland for surgery due to Anthem dispute",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Lisa Schmidt: Ehlers-Danlos syndrome, POTS, gastroparesis, MALS. Forced to travel to Cleveland for surgery because Scripps specialists no longer in-network. Rare disease patient traveling across country is powerful imagery.",
  },
  {
    id: 33,
    date: "2025-05-06",
    source: "San Diego Union-Tribune",
    sourceType: "news",
    channel: "media",
    headline: "Scripps Health, Anthem Blue Cross reach extension agreement — retroactive to Jan 1",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "RESOLUTION COVERAGE. Extension agreement, not a new contract. Retroactive to Jan 1. Neale: 'This is an extension, it is not a new agreement.' Key distinction — dispute is paused, not resolved.",
  },
  {
    id: 34,
    date: "2025-05-06",
    source: "NBC 7 San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "Breaking: Scripps and Anthem agree to extension — patients can return to Scripps doctors",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution day TV coverage. Relief framing. Patients can return to in-network Scripps care. Retroactive to Jan 1 means claims during gap period should be reprocessed.",
  },
  {
    id: 35,
    date: "2025-05-06",
    source: "10News ABC San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "Scripps-Anthem extension deal: Angel Coronel and other patients can resume in-network care",
    frameAdoption: "scripps",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "10News closes the Angel Coronel narrative arc. Patient can resume in-network rehab. Retroactive coverage means past OON costs should be resolved. Satisfying narrative conclusion.",
  },
  {
    id: 36,
    date: "2025-05-07",
    source: "CBS 8 San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "Scripps-Anthem deal details: extension through Sept 2026, retroactive to Jan 1",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Details emerge: extension through September 2026. Not a permanent resolution. CBS 8 notes patients should watch for claim reprocessing issues.",
  },
  {
    id: 37,
    date: "2025-05-07",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "Scripps Health, Anthem reunite after 4-month network split — extension, not new deal",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press resolution coverage. 'Reunite' framing. Emphasizes this is extension not new agreement. Trade audience notes underlying economics unresolved.",
  },
  {
    id: 38,
    date: "2025-05-19",
    source: "San Diego Union-Tribune",
    sourceType: "news",
    channel: "media",
    headline: "Rocky return: Scripps patients report confusion, billing issues as Anthem extension takes effect",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "POST-RESOLUTION PROBLEMS. Even after extension, patients report billing confusion, claim reprocessing delays, authorization issues. 'Rocky return' framing suggests Anthem implementation is problematic. Story continues beyond the deal.",
  },
  // === SCRIPPS OWNED MEDIA ===
  {
    id: 39,
    date: "2024-10-17",
    source: "Scripps Health (patient letters)",
    sourceType: "owned",
    channel: "media",
    headline: "Scripps sends letters to 125,000+ Anthem patients warning of potential network exit",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Direct patient communication. 125,000+ letters. First-mover advantage in framing — patients hear from Scripps before Anthem. Sets Scripps as the party informing and protecting patients.",
  },
  {
    id: 40,
    date: "2025-01-05",
    source: "Scripps Health (public statement)",
    sourceType: "owned",
    channel: "media",
    headline: "Scripps CEO Van Gorder: 'vanguard of ugly few years between hospitals and commercial insurance'",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Van Gorder positions Scripps as canary in the coal mine. 'Delay, deny or don't pay' becomes Scripps' stickiest talking point. Systemic framing elevates beyond local dispute.",
  },
  // === ANTHEM OWNED MEDIA ===
  {
    id: 41,
    date: "2024-12-30",
    source: "Anthem Blue Cross (public statement)",
    sourceType: "owned",
    channel: "media",
    headline: "Anthem: we offered a 'fair and competitive' rate increase; Scripps demands are unsustainable",
    frameAdoption: "anthem",
    sentiment: "negative_scripps",
    patientStory: false,
    blameDirection: "scripps",
    reachEstimate: "medium",
    notes: "Anthem's primary public statement. 'Fair and competitive' framing. Claims Scripps demands would raise premiums for employers and consumers. Defensive corporate tone. No patient voices.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 42,
    date: "2024-12-28",
    source: "Reddit (r/sandiego, r/insurance)",
    sourceType: "social",
    channel: "social",
    headline: "Pregnant Reddit user: 'c-section scheduled in 2 weeks and my doctor is at Scripps — what do I do?'",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "VIRAL PATIENT POST. Pregnant woman with c-section in 2 weeks. Scripps OB. Deadline in days. Maximally sympathetic — imminent childbirth + loss of chosen provider. Reddit comments overwhelmingly blame Anthem.",
  },
  {
    id: 43,
    date: "2025-01-02",
    source: "Social media (San Diego community)",
    sourceType: "social",
    channel: "social",
    headline: "San Diego social media erupts over Scripps-Anthem split — patients share disruption stories",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Organic social media response post-split. Facebook community groups, Nextdoor, Twitter. Scripps is deeply embedded in San Diego identity — community rallies around hospital system.",
  },
  {
    id: 44,
    date: "2025-01-15",
    source: "Reddit (r/sandiego)",
    sourceType: "social",
    channel: "social",
    headline: "Reddit thread: 'Husband's oncology team is at Scripps — Anthem dispute is terrifying'",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Unnamed patient's spouse: oncology team at Scripps. Cancer care disruption framing. Reddit comments provide practical advice but blame Anthem for the situation.",
  },
  {
    id: 45,
    date: "2025-02-10",
    source: "Social media (patient advocacy)",
    sourceType: "social",
    channel: "social",
    headline: "Lisa Schmidt shares rare disease journey on social — Ehlers-Danlos community amplifies Scripps story",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Lisa Schmidt: Ehlers-Danlos syndrome, POTS, gastroparesis, MALS. Rare disease communities are tight-knit and vocal online. Her story of traveling to Cleveland for surgery spreads through patient advocacy networks.",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 46,
    date: "2024-12-31",
    source: "State Sen. Catherine Blakespear",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "State Sen. Blakespear sends formal letter to DMHC demanding intervention in Scripps-Anthem dispute",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "POLITICAL INTERVENTION. Formal letter to DMHC on deadline day. State legislator puts public pressure on regulator. Blakespear represents coastal San Diego — Scripps heartland. Significant political signal.",
  },
  {
    id: 47,
    date: "2025-01-03",
    source: "DMHC (Dept of Managed Health Care)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "DMHC acknowledges Blakespear letter, opens enforcement database entries on Anthem",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Regulatory response. DMHC enforcement database entries. Not a formal investigation but creates regulatory paper trail. Signals state is watching Anthem's conduct.",
  },
  {
    id: 48,
    date: "2025-01-05",
    source: "Covered California",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Covered California creates special enrollment period (60 days) for affected Anthem policyholders",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CRITICAL REGULATORY ACTION. 60-day special enrollment for ~14,000 Covered California enrollees. Allows switching to plans with Scripps in-network. Unusual intervention signals severity of disruption. Benefits Scripps patients directly.",
  },
  {
    id: 49,
    date: "2025-01-10",
    source: "UFCW Local 135",
    sourceType: "news",
    channel: "stakeholder",
    headline: "UFCW Local 135 issues member bulletin: ~10,000 union workers affected by Scripps-Anthem split",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "UNION RESPONSE. ~10,000 UFCW Local 135 members affected. Multiple bulletins issued. Union framing blames Anthem. Organized labor channel creates political pressure beyond individual patient stories.",
  },
  {
    id: 50,
    date: "2025-01-12",
    source: "Nathan Kaufman (Kaufman Strategic Advisors)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Kaufman: 'insurance cartels like Anthem are a commodity... delivery systems are not'",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Industry expert quote. 'Insurance cartels' is the strongest third-party anti-Anthem framing. Kaufman Strategic Advisors has healthcare executive credibility. Quoted in multiple outlets.",
  },
  {
    id: 51,
    date: "2025-01-15",
    source: "Legal Aid Society of San Diego",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Legal Aid Society issues guidance for low-income Anthem patients affected by Scripps exit",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Legal aid response signals vulnerable populations affected. Low-income patients have fewest alternatives. Adds equity dimension to dispute narrative.",
  },
  {
    id: 52,
    date: "2025-01-18",
    source: "General Atomics (employer)",
    sourceType: "news",
    channel: "employer",
    headline: "General Atomics creates special enrollment for employees affected by Scripps-Anthem dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Major San Diego employer acts independently. General Atomics (defense contractor) opens special enrollment so employees can switch from Anthem to plans with Scripps in-network. Employer-level action signals severity.",
  },
  {
    id: 53,
    date: "2025-01-20",
    source: "Jessica Schulte Walker (insurance broker)",
    sourceType: "opinion",
    channel: "employer",
    headline: "Broker: 'Half my work is now helping Scripps patients navigate the Anthem dispute'",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "low",
    notes: "Jessica Schulte Walker: half her work consumed by Scripps patients. Broker testimony validates scale of disruption. Quoted in local media.",
  },
  {
    id: 54,
    date: "2025-01-22",
    source: "Rady Children's Hospital",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Rady Children's Hospital distributes internal FAQ on Scripps-Anthem dispute impact",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Rady Children's (separate system) creates internal FAQ for staff and families. Indicates ripple effects across San Diego healthcare ecosystem. Pediatric families affected by specialist referral disruptions.",
  },
  {
    id: 55,
    date: "2025-02-01",
    source: "UFCW Local 135 (follow-up bulletin)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "UFCW Local 135: union members report claim denials, care disruptions — demands Anthem accountability",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "medium",
    notes: "Follow-up union bulletin. Members reporting real claim denials. Union escalates rhetoric. Organized labor pressure on Anthem continues. ~10,000 members as ongoing constituency.",
  },
  {
    id: 56,
    date: "2025-02-15",
    source: "Neale, Scripps spokesperson",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "Scripps spokesperson Neale: 'This is an extension, it is not a new agreement' — dispute not over",
    frameAdoption: "scripps",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Quoted post-extension. Critical framing: extension, not resolution. Signals Scripps views underlying economic dispute as unresolved. Sets expectations for potential future disruption.",
  },
  {
    id: 57,
    date: "2025-03-20",
    source: "San Diego Union-Tribune (Jan 2024 systemic piece)",
    sourceType: "news",
    channel: "media",
    headline: "U-T investigation: Anthem's prior auth reversal pattern — 800+ instances at Scripps alone",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: false,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Deep investigative reporting. 800+ instances of Anthem approving prior authorization then reversing after service delivered. Scripps left holding the bill. $34M in denied claims. This is the most damaging data point for Anthem in the entire dispute.",
  },
  {
    id: 58,
    date: "2025-04-05",
    source: "10News ABC San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "Regina Key (Solana Beach): 'It's been a rollercoaster ride' — months of Scripps-Anthem uncertainty",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Regina Key (Solana Beach): 'rollercoaster ride' quote. Months of uncertainty for established patients. 10News continues patient-story approach deep into the dispute.",
  },
  {
    id: 59,
    date: "2025-04-20",
    source: "CBS 8 San Diego",
    sourceType: "tv",
    channel: "media",
    headline: "Months into Scripps-Anthem split, patients still struggling — when will it end?",
    frameAdoption: "scripps",
    sentiment: "negative_anthem",
    patientStory: true,
    blameDirection: "anthem",
    reachEstimate: "high",
    notes: "Duration fatigue coverage. Nearly 4 months OON. CBS 8 patient stories show ongoing harm. 'When will it end' captures patient exhaustion.",
  },
  {
    id: 60,
    date: "2025-05-06",
    source: "California Healthline",
    sourceType: "news",
    channel: "media",
    headline: "Scripps, Anthem reach extension — but underlying economics remain unresolved",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Policy outlet frames extension as temporary fix. Underlying cost pressures (compensation +8%/yr, pharma +14%/yr) unresolved. Notes extension through Sept 2026 — clock is ticking again.",
  },
];

const LABELS = {
  frameAdoption: { scripps: "Scripps Frame", anthem: "Anthem Frame", balanced: "Balanced" },
  sentiment: {
    negative_anthem: "Anti-Anthem",
    negative_scripps: "Anti-Scripps",
    neutral: "Neutral",
    positive_anthem: "Pro-Anthem",
    positive_scripps: "Pro-Scripps",
  },
  blameDirection: { anthem: "Blames Anthem", scripps: "Blames Scripps", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — Regional authority / statewide (1.5)
  "San Diego Union-Tribune": 1.5, "California Healthline": 1.5, "KPBS": 1.5,
  // Tier 2 — Local TV (1.2)
  "NBC 7 San Diego": 1.2, "Fox 5 San Diego": 1.2, "CBS 8 San Diego": 1.2,
  "10News ABC San Diego": 1.2,
  // Tier 3 — Trade/niche (1.0)
  "Becker's Hospital Review": 1.0, "InsuranceNewsNet": 1.0, "BenefitPro": 1.0,
  "HealthLeaders": 1.0, "Physicians News Network": 1.0, "Times of San Diego": 1.0,
  "Coast News Group": 1.0, "WSWS (World Socialist Web Site)": 1.0,
  // Tier 4 — Organic social (0.7)
  "Reddit (r/sandiego, r/insurance)": 0.7, "Reddit (r/sandiego)": 0.7,
  "Social media (San Diego community)": 0.7, "Social media (patient advocacy)": 0.7,
  // Tier 5 — Owned/party media (0.3)
  "Scripps Health (patient letters)": 0.3, "Scripps Health (public statement)": 0.3,
  "Anthem Blue Cross (public statement)": 0.3, "Neale, Scripps spokesperson": 0.3,
  // Tier 6 — Stakeholder actions (1.3)
  "State Sen. Catherine Blakespear": 1.3, "DMHC (Dept of Managed Health Care)": 1.3,
  "Covered California": 1.3, "UFCW Local 135": 1.3, "UFCW Local 135 (follow-up bulletin)": 1.3,
  "Nathan Kaufman (Kaufman Strategic Advisors)": 1.3,
  "Legal Aid Society of San Diego": 1.3, "Rady Children's Hospital": 1.3,
  // Tier 7 — Employer/Benefits (1.5x consultant, 1.0x broker)
  "General Atomics (employer)": 1.5,
  "Jessica Schulte Walker (insurance broker)": 1.0,
  // Column/opinion within major outlets
  "San Diego Union-Tribune (column)": 1.5,
  "San Diego Union-Tribune (Jan 2024 systemic piece)": 1.5,
};

const SEARCH_TRENDS = [
  { week: "2024-10-07", interest: 5 }, { week: "2024-10-14", interest: 55 }, { week: "2024-10-21", interest: 40 },
  { week: "2024-10-28", interest: 20 }, { week: "2024-11-04", interest: 12 }, { week: "2024-11-11", interest: 10 },
  { week: "2024-11-18", interest: 8 }, { week: "2024-11-25", interest: 9 }, { week: "2024-12-02", interest: 15 },
  { week: "2024-12-09", interest: 25 }, { week: "2024-12-16", interest: 45 }, { week: "2024-12-23", interest: 75 },
  { week: "2024-12-30", interest: 100 }, { week: "2025-01-06", interest: 85 }, { week: "2025-01-13", interest: 55 },
  { week: "2025-01-20", interest: 50 }, { week: "2025-01-27", interest: 35 }, { week: "2025-02-03", interest: 25 },
  { week: "2025-02-10", interest: 20 }, { week: "2025-02-17", interest: 18 }, { week: "2025-02-24", interest: 15 },
  { week: "2025-03-03", interest: 18 }, { week: "2025-03-10", interest: 15 }, { week: "2025-03-17", interest: 12 },
  { week: "2025-03-24", interest: 10 }, { week: "2025-03-31", interest: 12 }, { week: "2025-04-07", interest: 15 },
  { week: "2025-04-14", interest: 18 }, { week: "2025-04-21", interest: 20 }, { week: "2025-04-28", interest: 30 },
  { week: "2025-05-05", interest: 70 }, { week: "2025-05-12", interest: 45 }, { week: "2025-05-19", interest: 30 },
  { week: "2025-05-26", interest: 15 },
];

export default {
  // Identity
  providerKey: "scripps",
  payorKey: "anthem",
  providerName: "Scripps Health",
  payorName: "Anthem Blue Cross",
  providerShort: "Scripps",
  payorShort: "Anthem",
  navShort: "Scripps v. Anthem",
  title: "Scripps Health vs Anthem Blue Cross",
  subtitle: "Contract dispute · Extended May 6, 2025 (through Sept 2026)",
  gradientId: "scrippsanthem",

  // Dates
  monitorStart: "October 1, 2024",
  monitorEnd: "May 31, 2025",
  disputePublicDate: "2024-10-17",

  // Colors
  colors: {
    providerColor: "#006B3F",
    payorColor: "#1B3A8E",
    neutral: "#64748B",
    accent: "#006B3F",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#006B3F", "#4A7A6B", "#1B3A8E"],
  yAxisWidth: 82,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"scripps health anthem blue cross" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.87,
    nationalMedian: 1.0,
    networkComplaints: 1523,
    priorYearComplaints: 982,
    regulatorAction: "DMHC opened enforcement database entries after State Sen. Blakespear's formal letter. Covered California created 60-day special enrollment period for ~14,000 affected enrollees. No formal DMHC investigation opened.",
    signalRead: "Anthem's complaint index is elevated (1.87x median) driven by network access disruptions in California. The 55% increase in network complaints reflects the Scripps split's impact on 125,000+ policyholders. DMHC enforcement entries and Covered California's special enrollment signal regulatory concern without formal intervention.",
  },

  // Executive summary
  executiveSummary: {
    statement: "The dispute resulted in a 4-month out-of-network period (Jan 1 – May 6, 2025) before an extension agreement retroactive to Jan 1. This is not a new contract — the underlying economic dispute remains unresolved through Sept 2026.",
    keyMessages: [
      "Anthem's prior authorization reversal pattern (800+ instances, $34M in denied claims) is the most damaging factual finding — systemic 'delay, deny, don't pay' framing is sticky and hard to counter.",
      "Named patient stories span brain rehab (Angel Coronel), rare disease (Lisa Schmidt), pregnancy, oncology, and chronic illness — nearly impossible for Anthem to counter with equivalent patient advocates.",
      "Scripps CEO Van Gorder's 'hospital deserts' and 'vanguard of ugly few years' framing positions this as a systemic industry battle, not a local contract dispute.",
      "The extension (not new agreement) means this dispute could reignite — PR infrastructure from both sides remains in place.",
    ],
    marcomm: [
      "<strong>The prior auth reversal data is devastating.</strong> 800+ instances of Anthem approving care then reversing after billing — with only $6.5M recovered on $34M in denied claims — is the single most damaging data point. It validates 'delay, deny, don't pay' as documented practice, not rhetoric.",
      "<strong>Scripps' community embeddedness is a structural advantage.</strong> Five hospital campuses, 30 outpatient centers, ~3,000 physicians — Scripps IS San Diego healthcare for many residents. Anthem is a faceless insurer. Community identity always beats corporate brand in local disputes.",
      "<strong>Union and political channels created sustained pressure.</strong> UFCW Local 135 (~10,000 members) and State Sen. Blakespear provided organized institutional pressure that individual patient stories alone cannot generate. Multi-channel pressure forced the extension.",
      "<strong>The extension is a ceasefire, not a peace treaty.</strong> Neale's explicit framing — 'this is an extension, it is not a new agreement' — signals the economic fundamentals are unresolved. Both sides should prepare for potential Round 2 in 2026.",
    ],
  },
  channelTakeaways: {
    media: [
      "10News' Angel Coronel series was the single most impactful patient narrative — multi-part brain rehab coverage built audience investment over months.",
      "San Diego Union-Tribune's investigative piece on 800+ prior auth reversals provided the factual backbone for Scripps' 'delay, deny, don't pay' framing.",
      "All four local TV stations (NBC 7, Fox 5, CBS 8, 10News) provided sustained coverage over 7 months — unusual duration for a local dispute.",
      "Trade press (Becker's, HealthLeaders, California Healthline) elevated Van Gorder's 'hospital deserts' framing to a national audience.",
    ],
    social: [
      "Pregnant Reddit user's c-section post became the most viral organic social moment — imminent childbirth plus loss of chosen provider is maximally sympathetic.",
      "Lisa Schmidt's rare disease story spread through Ehlers-Danlos community networks — niche patient advocacy groups amplified beyond San Diego.",
      "San Diego community identity rallied around Scripps — social media framing was overwhelmingly pro-Scripps, anti-Anthem.",
      "Duration of dispute (4+ months OON) sustained social media engagement far longer than typical provider-payor disputes.",
    ],
    stakeholder: [
      "State Sen. Blakespear's formal DMHC letter on deadline day was the most significant political intervention — created regulatory paper trail for Anthem.",
      "Covered California's 60-day special enrollment was the most impactful regulatory action — gave 14,000 enrollees an escape valve.",
      "UFCW Local 135 bulletins organized ~10,000 union workers as a sustained pressure constituency — institutional voice beyond individual patients.",
      "Nathan Kaufman's 'insurance cartels' quote was the stickiest third-party expert framing — gave media a quotable independent voice.",
    ],
    employer: [
      "General Atomics' independent special enrollment action signals how seriously major employers took the disruption — defense contractor workforce affected.",
      "Broker Jessica Schulte Walker's testimony ('half my work') validated the scale of patient-level disruption through an independent professional voice.",
      "~10,000 UFCW Local 135 workers created direct employer pressure — union benefits are a negotiated contract item, not just an insurance product.",
    ],
  },
  timeline: [
    { date: "2024-10-17", type: "newsBreak", label: "News breaks publicly" },
    { date: "2025-01-01", type: "termination", label: "Contract terminates" },
    { date: "2025-05-06", type: "extension", label: "Extension agreement through Sept 2026" },
  ],
};
