// Spartanburg Regional Healthcare System vs Cigna — PR War Room Config
// Dispute period: June 2024–February 2025. Contract expired Dec 31, 2024. Resolved with multi-year agreement early 2025.
// Prior dispute: June 2020–January 2022 (18 months out-of-network). This is the SECOND cycle.

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2024-11-20",
    source: "Fox Carolina",
    sourceType: "tv",
    channel: "media",
    headline: "Bon Secours, Spartanburg Regional announces Cigna contracts to end in December",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "First major TV coverage. Both Bon Secours St. Francis and Spartanburg Regional announced simultaneously — dual-system announcement amplifies story. Fox Carolina is primary Upstate SC TV outlet. Frames as mutual impasse after 6+ months of negotiations.",
  },
  {
    id: 2,
    date: "2024-11-20",
    source: "WSPA 7News",
    sourceType: "tv",
    channel: "media",
    headline: "Spartanburg Regional, Cigna insurance agreement ends Dec. 31",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "WSPA is CBS affiliate for Spartanburg market. Spartanburg Regional rep quoted: 'Cigna is not recognizing rising labor and supply costs.' Cigna counters with '23% rate increase' framing. WSPA becomes primary local outlet for patient-impact angle.",
  },
  {
    id: 3,
    date: "2024-11-20",
    source: "Greenville News",
    sourceType: "news",
    channel: "media",
    headline: "Spartanburg Regional, Cigna to end insurance agreement; how will this affect patients?",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Greenville News (Gannett/USA Today Network) is the paper of record for Upstate SC. Patient-impact framing in headline. Notes negotiations ongoing for six months. Both sides' rate claims presented. Syndicated to Yahoo News for national reach.",
  },
  {
    id: 4,
    date: "2024-11-20",
    source: "Greenville Business Magazine",
    sourceType: "news",
    channel: "media",
    headline: "A Change in Health Insurance for Bon Secours Patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Business press. Covers Bon Secours side of simultaneous Cigna disputes. Employer-focused audience. Notes Bon Secours also ending Cigna Medicare Advantage plan participation effective Jan 1, 2025.",
  },
  {
    id: 5,
    date: "2024-11-21",
    source: "Spartanburg Herald-Journal",
    sourceType: "news",
    channel: "media",
    headline: "Spartanburg Regional Healthcare System's agreement will soon end with Cigna",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Hometown paper. SRHS is the dominant employer and healthcare provider in Spartanburg County. Herald-Journal coverage carries weight with local officials and employers. Spartanburg Regional framing: Cigna's position 'in stark contrast to other major national insurers.'",
  },
  {
    id: 6,
    date: "2024-11-22",
    source: "Fox Carolina (video segment)",
    sourceType: "tv",
    channel: "media",
    headline: "Bon Secours, Spartanburg Regional announces Cigna contracts to end in December — follow-up TV segment",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Extended video follow-up with patient guidance. Multiple Fox Carolina segments through November signal sustained Upstate TV interest. Greenville-Spartanburg-Asheville DMA reaches ~800K households.",
  },
  {
    id: 7,
    date: "2024-12-01",
    source: "Becker's Payer Issues",
    sourceType: "news",
    channel: "media",
    headline: "South Carolina health system's contract with Cigna expires",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National trade press coverage. Notes SRHS's two-year contract with Cigna expired March 31, 2020, and the parties severed network June 1, 2020, over 'double-digit increase' demand. 18-month prior disruption is critical context — shows pattern. Hospital executive audience.",
  },
  {
    id: 8,
    date: "2024-12-05",
    source: "WSPA 7News",
    sourceType: "tv",
    channel: "media",
    headline: "Some Spartanburg Regional patients could lose health insurance coverage: What to know",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Patient-impact focus as deadline nears. WSPA provides guidance: call Cigna, file transition of care forms. Notes Cigna members 'may be responsible for higher out-of-network costs.' Emergency access remains. Continuity of care available for 'certain conditions' only for limited time.",
  },
  {
    id: 9,
    date: "2024-12-10",
    source: "WYFF 4 (NBC Greenville)",
    sourceType: "tv",
    channel: "media",
    headline: "Spartanburg Regional, Cigna contract expiration impacts Upstate patients ahead of holidays",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "NBC affiliate coverage. Holiday timing amplifies patient anxiety — people facing care disruption during Christmas/New Year. Upstate SC has limited hospital alternatives, making out-of-network status more acute than in urban markets.",
  },
  {
    id: 10,
    date: "2024-12-15",
    source: "WHNS Fox Carolina",
    sourceType: "tv",
    channel: "media",
    headline: "Cigna patients at Spartanburg Regional face out-of-network costs starting January 1",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Countdown coverage as Jan 1 deadline approaches. SRHS has 6 hospital campuses and 700+ physicians — patients in Cherokee, Union, Spartanburg counties have few alternatives. Rural healthcare access angle is powerful framing.",
  },
  {
    id: 11,
    date: "2024-12-20",
    source: "Post and Courier (Greenville)",
    sourceType: "news",
    channel: "media",
    headline: "Spartanburg Regional and Cigna remain at impasse as contract expiration looms",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Post and Courier is South Carolina's largest newspaper. Greenville edition reaches Upstate audience. Balanced coverage but 'impasse' framing increases urgency. Notes SRHS is only Level I Trauma Center in the region.",
  },
  {
    id: 12,
    date: "2024-12-31",
    source: "WSPA 7News",
    sourceType: "tv",
    channel: "media",
    headline: "Spartanburg Regional, Cigna contract officially expires — patients now out of network",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Deadline-day coverage. Contract officially expired. WSPA is the most consistent local outlet covering this dispute. Cigna patients at SRHS now face out-of-network costs effective January 1. Cigna Medicare contracts remain in network.",
  },
  {
    id: 13,
    date: "2025-01-02",
    source: "Becker's Payer Issues",
    sourceType: "news",
    channel: "media",
    headline: "South Carolina health system's contract with Cigna expires — second time in four years",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press notes this is the SECOND Cigna network disruption for SRHS since 2020. Pattern framing undermines Cigna's 'unreasonable demands' narrative — suggests systemic underpayment rather than provider greed.",
  },
  {
    id: 14,
    date: "2025-01-08",
    source: "Fox Carolina",
    sourceType: "tv",
    channel: "media",
    headline: "Spartanburg Regional patients navigate out-of-network reality with Cigna in new year",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Post-expiration patient impact. Patients describe confusion about coverage, concern about surprise bills. SRHS directs patients to file continuity of care requests with Cigna. SC law provides 90-day continuation for 'serious medical conditions.'",
  },
  {
    id: 15,
    date: "2025-01-15",
    source: "South Carolina Public Radio",
    sourceType: "radio",
    channel: "media",
    headline: "Spartanburg Regional patients face higher costs as Cigna contract dispute continues into 2025",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Public radio coverage reaches policy-attentive audience across the state. Notes Spartanburg Regional also had prior Aetna disputes — pattern of SRHS vs multiple insurers provides counter-narrative for Cigna.",
  },
  {
    id: 16,
    date: "2025-01-20",
    source: "Greenville News",
    sourceType: "news",
    channel: "media",
    headline: "Upstate SC hospital system and Cigna still at odds — patients caught in the middle",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Greenville News follow-up. 'Caught in the middle' framing blames both parties. Notes 10,000 associates at SRHS — system is among Spartanburg County's largest employers. Syndicated via USA Today Network.",
  },
  {
    id: 17,
    date: "2025-02-01",
    source: "Greenville Business Magazine",
    sourceType: "news",
    channel: "media",
    headline: "Disputes Between Health Systems and Insurers Bring Challenges to Patients — Spartanburg Regional featured",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Systemic framing piece featuring SRHS/Cigna alongside other Upstate disputes (Prisma/UHC, Bon Secours/Cigna). Normalizes SRHS position by showing pattern across region. Employer/business audience — key for sentiment among Cigna's corporate clients.",
  },
  {
    id: 18,
    date: "2025-02-10",
    source: "WSPA 7News",
    sourceType: "tv",
    channel: "media",
    headline: "Cigna and Spartanburg Regional Healthcare System reach agreement for customer access",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "RESOLUTION COVERAGE. Multi-year agreement announced. WSPA reports deal ensures Cigna customers access to SRHS's six hospital campuses, facilities, and 700+ physician network. Mirrors 2022 resolution after 18-month gap. Relief framing.",
  },
  {
    id: 19,
    date: "2025-02-10",
    source: "Cigna Newsroom",
    sourceType: "owned",
    channel: "media",
    headline: "Cigna and Spartanburg Regional Healthcare System Reach Agreement — multi-year deal",
    frameAdoption: "cigna",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Cigna's official press release. Frames agreement as providing 'access to quality, affordable care.' Multi-year term. Covers six hospital campuses and 700+ physicians. Cigna claims credit for protecting affordability while restoring access.",
  },
  {
    id: 20,
    date: "2025-02-10",
    source: "Becker's Payer Issues",
    sourceType: "news",
    channel: "media",
    headline: "Cigna reaches multiyear agreement with Spartanburg Regional Healthcare System",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press resolution. Notes prior 2020 disruption — Becker's explicitly connects the two cycles, reinforcing pattern narrative. Neither side disclosed rate terms. Hospital executive audience tracks these resolutions.",
  },
  {
    id: 21,
    date: "2025-02-10",
    source: "Discover Health (Cigna)",
    sourceType: "owned",
    channel: "media",
    headline: "Cigna and Spartanburg Regional Healthcare System reach agreement",
    frameAdoption: "cigna",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Cigna's consumer health portal. Patient-facing resolution notice. Directs members back to in-network access. Multi-year agreement covers hospitals, facilities, and physician network across the Carolinas.",
  },
  {
    id: 22,
    date: "2025-02-11",
    source: "Fox Carolina",
    sourceType: "tv",
    channel: "media",
    headline: "Spartanburg Regional and Cigna reach new multi-year deal — patients can return to in-network care",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution coverage on Fox Carolina. Relief angle. Notes approximately 6-week gap where patients were out of network (Jan 1 – mid-Feb 2025). Much shorter disruption than 2020's 18-month gap.",
  },
  // === SPARTANBURG REGIONAL OWNED MEDIA ===
  {
    id: 23,
    date: "2024-11-15",
    source: "spartanburgregional.com — Cigna Member Information",
    sourceType: "owned",
    channel: "media",
    headline: "SRHS publishes 'Important Information for all Cigna members' — patient guidance page",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Dedicated patient-facing page. Key messages: 'Cigna's position is in stark contrast to other major national insurers who recognize and agree that increases are necessary.' Directs patients to contact Cigna for continuity of care. Positions SRHS as willing to negotiate; Cigna as outlier.",
  },
  {
    id: 24,
    date: "2024-11-20",
    source: "spartanburgregional.com — Press Statement",
    sourceType: "owned",
    channel: "media",
    headline: "Spartanburg Regional: 'We have been negotiating in good faith for more than six months'",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Official statement. Key claim: other major national insurers (BCBS, Aetna at the time) recognize rising labor/supply costs. Implies Cigna is the outlier refusing fair rates. 'Good faith' language positions SRHS as reasonable party.",
  },
  {
    id: 25,
    date: "2025-02-10",
    source: "spartanburgregional.com — Resolution Announcement",
    sourceType: "owned",
    channel: "media",
    headline: "Spartanburg Regional announces new multi-year agreement with Cigna — in-network access restored",
    frameAdoption: "spartanburg",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Victory framing. 'Restored' implies Cigna disrupted access. Multi-year agreement suggests SRHS achieved sustainable rate increases. Updates Cigna member information page to confirm in-network status.",
  },
  // === CIGNA OWNED MEDIA ===
  {
    id: 26,
    date: "2024-11-20",
    source: "Cigna Healthcare (public statement)",
    sourceType: "owned",
    channel: "media",
    headline: "Cigna: Spartanburg Regional's 'unreasonable demands for a 23% rate increase would significantly raise costs for local employers'",
    frameAdoption: "cigna",
    sentiment: "negative_spartanburg",
    patientStory: false,
    blameDirection: "spartanburg",
    reachEstimate: "medium",
    notes: "Cigna's primary public statement. Key claims: 23% rate increase demand, 'more than four times the current inflation rate for medical services,' current rates 'already more than cover the costs Spartanburg Regional incurs.' Employer-focused affordability framing.",
  },
  {
    id: 27,
    date: "2024-12-15",
    source: "Cigna Healthcare (member notification)",
    sourceType: "owned",
    channel: "media",
    headline: "Cigna notifies members of Spartanburg Regional out-of-network transition — continuity of care guidance",
    frameAdoption: "cigna",
    sentiment: "negative_spartanburg",
    patientStory: false,
    blameDirection: "spartanburg",
    reachEstimate: "medium",
    notes: "Direct member communication. Cigna frames SRHS as choosing to leave network. Provides continuity of care transition form link. Member anxiety likely high — SRHS is dominant provider in Spartanburg County.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 28,
    date: "2024-11-20",
    source: "Greenville News (Facebook post)",
    sourceType: "social",
    channel: "social",
    headline: "Greenville News posts Spartanburg Regional/Cigna story on Facebook — high engagement from Upstate residents",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Facebook post generated significant local engagement. Upstate SC residents express frustration with Cigna. Comment sections skew heavily anti-insurer in rural/suburban markets where hospital systems are community anchors. SRHS employs 10,000 in the region.",
  },
  {
    id: 29,
    date: "2024-11-22",
    source: "Social media (Upstate SC community groups)",
    sourceType: "social",
    channel: "social",
    headline: "Spartanburg and Cherokee County Facebook groups discuss Cigna contract loss — 'where will we go?'",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "CRITICAL LOCAL SOCIAL SIGNAL. In rural Upstate SC, SRHS is often the ONLY hospital system within reasonable distance. Cherokee Medical Center, Union Medical Center serve areas with no alternatives. 'Where will we go?' is devastating framing for Cigna.",
  },
  {
    id: 30,
    date: "2024-12-01",
    source: "Social media (patient anxiety posts)",
    sourceType: "social",
    channel: "social",
    headline: "Cigna patients share concerns about losing Spartanburg Regional access — cancer patients at Gibbs Cancer Center especially worried",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Gibbs Cancer Center & Research Institute (part of SRHS) serves cancer patients across the Upstate with locations in Spartanburg, Greer, Union, and Gaffney. Cancer patients in active treatment facing network disruption mirrors MSK/UHC dynamic at smaller scale.",
  },
  {
    id: 31,
    date: "2024-12-10",
    source: "Facebook/NextDoor (Spartanburg area)",
    sourceType: "social",
    channel: "social",
    headline: "Local social media discussions about open enrollment — some switching away from Cigna to avoid SRHS disruption",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Open enrollment timing (Nov-Dec) means some employees can switch insurers. Cigna risks losing commercial lives in Upstate SC if employers or employees switch to BCBS or other carriers that maintain SRHS network status. Competitive pressure on Cigna.",
  },
  {
    id: 32,
    date: "2024-12-20",
    source: "Social media (holiday anxiety)",
    sourceType: "social",
    channel: "social",
    headline: "Patients express anxiety about losing hospital access during holidays — 'What if there's an emergency?'",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Holiday timing amplifies anxiety. SRHS operates the region's only Level I Trauma Center. Emergency access is preserved regardless of network status, but patients don't always know this. Fear of financial exposure in emergencies is powerful.",
  },
  {
    id: 33,
    date: "2025-01-05",
    source: "Social media (post-expiration frustration)",
    sourceType: "social",
    channel: "social",
    headline: "Cigna patients report confusion about out-of-network billing at Spartanburg Regional facilities",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Post-expiration social posts. Patients unsure which services are covered under continuity of care vs. full out-of-network. Confusion itself generates blame directed at Cigna — patients expected to navigate complex forms during health crises.",
  },
  {
    id: 34,
    date: "2025-02-10",
    source: "Social media (resolution relief)",
    sourceType: "social",
    channel: "social",
    headline: "Upstate SC residents express relief at Cigna-Spartanburg Regional agreement — 'finally'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Resolution relief posts. 'Finally' implies blame for unnecessary delay. 6-week gap was disruptive but far shorter than 2020's 18-month disruption. Some patients still express distrust of Cigna's long-term commitment.",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 35,
    date: "2024-11-20",
    source: "Spartanburg Regional spokesperson",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "SRHS: 'Cigna's position is in stark contrast to other major national insurers who recognize rising labor and supply costs'",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "SRHS's stickiest argument: positioning Cigna as the outlier among national insurers. If BCBS and Aetna agreed to rate increases, Cigna's refusal appears unreasonable rather than principled. This framing was adopted by multiple media outlets.",
  },
  {
    id: 36,
    date: "2024-11-20",
    source: "Cigna Healthcare spokesman",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Cigna: 23% rate increase is 'more than four times the current inflation rate for medical services'",
    frameAdoption: "cigna",
    sentiment: "negative_spartanburg",
    patientStory: false,
    blameDirection: "spartanburg",
    reachEstimate: "high",
    notes: "Cigna's strongest data point. 23% vs. ~5% medical CPI is attention-getting for employers. 'Current rates already more than cover the costs' is direct challenge to SRHS. Employer-facing affordability framing is Cigna's primary strategy.",
  },
  {
    id: 37,
    date: "2024-11-25",
    source: "SC Department of Insurance (regulatory context)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "SC law provides 90-day continuation of care for serious medical conditions during network transitions",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "SC Code 38-71-243: 90-day continuation of care for serious medical conditions. Insurer must provide in-network-level benefits during transition. Broader than NY's 60-day rule for fully insured. However, does not cover routine care — majority of patients still face out-of-network costs.",
  },
  {
    id: 38,
    date: "2024-12-01",
    source: "Bon Secours St. Francis (parallel dispute)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Bon Secours St. Francis also ends Cigna contract simultaneously — Cigna fighting two Upstate SC systems at once",
    frameAdoption: "balanced",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "PATTERN EVIDENCE: Cigna losing both major Upstate SC health systems simultaneously. Bon Secours said Cigna rates were 'not keeping pace with inflation and are below fair market standards.' Two independent systems making same claim strengthens provider narrative.",
  },
  {
    id: 39,
    date: "2024-12-10",
    source: "Cigna 2020 precedent (historical context)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "SRHS and Cigna were out-of-network for 18 months from June 2020 to January 2022 — this is round two",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "CRITICAL HISTORICAL CONTEXT. Prior 18-month disruption (June 2020–Jan 2022) over 'double-digit increase' demand. Multi-year agreement from 2022 lasted only ~3 years before breaking down again. Repeat pattern suggests structural pricing conflict, not isolated negotiation failure.",
  },
  {
    id: 40,
    date: "2024-12-15",
    source: "Cigna multi-system dispute pattern (national)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Cigna fighting contract disputes with multiple systems nationally — Jefferson Health, Ballad Health, Tenet, SRHS",
    frameAdoption: "balanced",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "133 public disputes in 2024. Cigna simultaneously fighting Jefferson Health (Philadelphia), Ballad Health (Appalachia), Tenet (64 hospitals), UNC Health, and SRHS. Hospital wage index up 20% since 2020; Cigna rates up ~3%. Pattern evidence of systemic Cigna underpayment.",
  },
  {
    id: 41,
    date: "2024-12-20",
    source: "Upstate SC legislators (silence)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "SC state legislators have not publicly intervened in Spartanburg Regional/Cigna dispute — regulatory silence",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "SILENCE IS DATA. No public statements from Spartanburg-area legislators. SRHS is a major employer and community institution — political relationships are strong but intervention not triggered. SC's lighter regulatory environment compared to NY means less state leverage.",
  },
  {
    id: 42,
    date: "2025-01-10",
    source: "SC No Surprises Act protections",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Federal No Surprises Act protects emergency patients from balance billing regardless of network status",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "No Surprises Act (2022) ensures emergency care at SRHS's Level I Trauma Center won't result in surprise bills. However, scheduled/elective care is NOT protected — patients still face out-of-network costs for planned procedures, ongoing treatment, specialist visits.",
  },
  {
    id: 43,
    date: "2025-01-15",
    source: "Spartanburg Area Chamber of Commerce (context)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Spartanburg business community monitors Cigna/SRHS dispute — employer benefit costs in focus",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Spartanburg has significant manufacturing base (BMW, Michelin nearby). Large employers offering Cigna plans face employee disruption. Counter-pressure: SRHS's 23% demand would increase employer costs. Employers caught between workforce retention and cost containment.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 44,
    date: "2024-11-20",
    source: "Cigna employer messaging",
    sourceType: "owned",
    channel: "employer",
    headline: "Cigna frames to employers: 23% rate hike would 'significantly raise costs for local employers, their employees and their families'",
    frameAdoption: "cigna",
    sentiment: "negative_spartanburg",
    patientStory: false,
    blameDirection: "spartanburg",
    reachEstimate: "high",
    notes: "Cigna's STRONGEST employer argument. Direct appeal to Upstate SC employers: your costs will rise 23% if SRHS gets its way. Self-insured employers especially sensitive to rate increases. Open enrollment timing means employers must decide on 2025 plan offerings.",
  },
  {
    id: 45,
    date: "2024-12-01",
    source: "Benefits brokers (Upstate SC)",
    sourceType: "news",
    channel: "employer",
    headline: "Upstate SC benefits brokers advise employer clients on Cigna/SRHS network disruption — open enrollment impact",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Broker channel is critical in mid-market employer segment. Employers Network (Spartanburg-based benefits firm) and regional brokers advising clients. Some employers may have switched away from Cigna during open enrollment to avoid SRHS disruption.",
  },
  {
    id: 46,
    date: "2024-12-10",
    source: "Employer open enrollment communications",
    sourceType: "news",
    channel: "employer",
    headline: "Upstate employers communicate SRHS/Cigna disruption to employees during open enrollment — some add BCBS alternatives",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Open enrollment (Nov-Dec) overlap with dispute is strategically significant. Employees can switch plans. Employers offering only Cigna face backlash from workforce that relies on SRHS. Competitive pressure on Cigna to resolve before losing commercial lives.",
  },
  {
    id: 47,
    date: "2025-01-05",
    source: "Self-insured employer impact (Upstate SC manufacturing)",
    sourceType: "news",
    channel: "employer",
    headline: "Self-insured Upstate SC employers face direct cost impact — SRHS out-of-network means higher claims costs",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Self-insured employers face a dilemma: out-of-network SRHS claims cost MORE than in-network rates. In Spartanburg County, SRHS is so dominant that employees will still use it — just at higher cost to the plan. This creates employer pressure on Cigna to resolve, not SRHS.",
  },
  {
    id: 48,
    date: "2025-02-10",
    source: "Employer benefit plan updates",
    sourceType: "news",
    channel: "employer",
    headline: "Cigna/SRHS agreement restores in-network access for Upstate employer plans — brokers communicate resolution",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution communicated through broker channel to employer clients. Multi-year deal provides planning stability. But 6-week gap and second disruption in 4 years may damage Cigna's credibility with Upstate SC employers long-term.",
  },
  // === ADDITIONAL MEDIA/CONTEXT ===
  {
    id: 49,
    date: "2024-11-20",
    source: "NewsBreak",
    sourceType: "news",
    channel: "media",
    headline: "Bon Secours, Spartanburg Regional announces Cigna contracts to end in December",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "NewsBreak syndication of Fox Carolina content. Digital-first news aggregator reaches mobile audiences that may not watch local TV. Extends geographic reach beyond Greenville-Spartanburg DMA.",
  },
  {
    id: 50,
    date: "2024-11-21",
    source: "Yahoo News (syndicated)",
    sourceType: "news",
    channel: "media",
    headline: "Spartanburg Regional, Cigna to end insurance agreement; how will this affect patients?",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Yahoo News syndication of Greenville News content. National reach. Yahoo syndication significantly expands audience beyond Upstate SC — creates national awareness of the dispute among health policy watchers.",
  },
  {
    id: 51,
    date: "2024-12-05",
    source: "Yahoo Finance",
    sourceType: "news",
    channel: "media",
    headline: "Cigna Insurance and Spartanburg Regional Healthcare System reach agreement — coverage of prior 2022 resolution surfaces",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Yahoo Finance surfacing prior 2022 resolution in context of new dispute. Investor/business audience. Historical pattern of disputes and resolutions is relevant to Cigna's (Cigna Group / CI) investor narrative about provider relations.",
  },
  {
    id: 52,
    date: "2024-11-25",
    source: "SRHS Level I Trauma Center context",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Spartanburg Medical Center is the region's only Level I Trauma Center — network loss creates access crisis framing",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "STRUCTURAL ADVANTAGE FOR SRHS: As the only Level I Trauma Center in the region, SRHS is irreplaceable for serious injuries. Emergency access is preserved by law, but the trauma center's status underscores SRHS's essential role. No alternative exists within 50+ miles for many patients.",
  },
  {
    id: 53,
    date: "2024-12-08",
    source: "Gibbs Cancer Center & Research Institute context",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Gibbs Cancer Center patients with Cigna face network disruption — four locations across Upstate SC",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Gibbs Cancer Center (part of SRHS) has locations in Spartanburg, Greer, Union, and Gaffney. Cancer patients in active chemotherapy/radiation facing network disruption is maximally sympathetic framing. Mirrors MSK/UHC cancer treatment disruption angle at regional scale.",
  },
  {
    id: 54,
    date: "2024-12-18",
    source: "Pelham Medical Center / Cherokee Medical Center context",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Rural SRHS campuses in Cherokee and Union counties — patients have no nearby hospital alternatives",
    frameAdoption: "spartanburg",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "RURAL ACCESS ANGLE: Cherokee Medical Center (Gaffney) and Union Medical Center (Union) serve communities where SRHS is the only hospital. Rural patients cannot simply switch providers. This creates a structural imbalance — Cigna's network disruption has disproportionate impact on vulnerable rural populations.",
  },
  {
    id: 55,
    date: "2025-01-20",
    source: "UNC Health / Cigna parallel (North Carolina)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "UNC Health and Cigna also in contract dispute — 50,000+ patients affected across North Carolina",
    frameAdoption: "balanced",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "PARALLEL DISPUTE: UNC Health and Cigna contract dispute affecting 50,000+ patients in neighboring state. Combined with Bon Secours and SRHS in SC, Cigna is fighting major systems across the Carolinas simultaneously. Regional pattern evidence strengthens SRHS's negotiating position.",
  },
  {
    id: 56,
    date: "2025-01-25",
    source: "Jefferson Health / Cigna parallel (Philadelphia)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Jefferson Health goes out of network with Cigna — national pattern of Cigna disputes accelerating",
    frameAdoption: "balanced",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Jefferson Health (18 hospitals, Philadelphia) also went out-of-network with Cigna. Healthcare Dive coverage. Combined with UNC Health, Ballad Health, Tenet, SRHS — Cigna is in disputes with systems representing hundreds of hospitals nationally.",
  },
];

const LABELS = {
  frameAdoption: { spartanburg: "SRHS Frame", cigna: "Cigna Frame", balanced: "Balanced" },
  sentiment: {
    negative_cigna: "Anti-Cigna",
    negative_spartanburg: "Anti-SRHS",
    neutral: "Neutral",
    positive_cigna: "Pro-Cigna",
    positive_spartanburg: "Pro-SRHS",
  },
  blameDirection: { cigna: "Blames Cigna", spartanburg: "Blames SRHS", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National record (1.5)
  "Yahoo News (syndicated)": 1.5, "Yahoo Finance": 1.5,
  // Tier 2 — Regional authority (1.2)
  "Fox Carolina": 1.2, "WSPA 7News": 1.2, "WYFF 4 (NBC Greenville)": 1.2, "WHNS Fox Carolina": 1.2,
  "Greenville News": 1.2, "Spartanburg Herald-Journal": 1.2, "Post and Courier (Greenville)": 1.2,
  "South Carolina Public Radio": 1.2,
  // Tier 3 — Trade/niche (1.0)
  "Becker's Payer Issues": 1.0, "Greenville Business Magazine": 1.0, "NewsBreak": 1.0,
  "Fox Carolina (video segment)": 1.0,
  // Tier 4 — Organic social (0.7)
  "Greenville News (Facebook post)": 0.7, "Social media (Upstate SC community groups)": 0.7,
  "Social media (patient anxiety posts)": 0.7, "Facebook/NextDoor (Spartanburg area)": 0.7,
  "Social media (holiday anxiety)": 0.7, "Social media (post-expiration frustration)": 0.7,
  "Social media (resolution relief)": 0.7,
  // Tier 5 — Comment sections (0.4)
  // Tier 6 — Owned/party media (0.3)
  "spartanburgregional.com — Cigna Member Information": 0.3,
  "spartanburgregional.com — Press Statement": 0.3,
  "spartanburgregional.com — Resolution Announcement": 0.3,
  "Cigna Healthcare (public statement)": 0.3, "Cigna Healthcare (member notification)": 0.3,
  "Cigna Newsroom": 0.3, "Discover Health (Cigna)": 0.3, "Cigna employer messaging": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "Spartanburg Regional spokesperson": 1.3, "Cigna Healthcare spokesman": 1.3,
  "SC Department of Insurance (regulatory context)": 1.3,
  "Bon Secours St. Francis (parallel dispute)": 1.3,
  "Cigna 2020 precedent (historical context)": 1.3,
  "Cigna multi-system dispute pattern (national)": 1.3,
  "Upstate SC legislators (silence)": 1.3,
  "SC No Surprises Act protections": 1.3,
  "Spartanburg Area Chamber of Commerce (context)": 1.3,
  "SRHS Level I Trauma Center context": 1.3,
  "Gibbs Cancer Center & Research Institute context": 1.3,
  "Pelham Medical Center / Cherokee Medical Center context": 1.3,
  "UNC Health / Cigna parallel (North Carolina)": 1.3,
  "Jefferson Health / Cigna parallel (Philadelphia)": 1.3,
  // Tier 8 — Employer/Benefits (1.5x trade, 1.0x local)
  "Benefits brokers (Upstate SC)": 1.5,
  "Employer open enrollment communications": 1.0,
  "Self-insured employer impact (Upstate SC manufacturing)": 1.0,
  "Employer benefit plan updates": 1.0,
};

const SEARCH_TRENDS = [
  { week: "2024-10-07", interest: 2 }, { week: "2024-10-14", interest: 3 }, { week: "2024-10-21", interest: 3 },
  { week: "2024-10-28", interest: 5 }, { week: "2024-11-04", interest: 8 }, { week: "2024-11-11", interest: 12 },
  { week: "2024-11-18", interest: 75 }, { week: "2024-11-25", interest: 60 }, { week: "2024-12-02", interest: 55 },
  { week: "2024-12-09", interest: 65 }, { week: "2024-12-16", interest: 70 }, { week: "2024-12-23", interest: 85 },
  { week: "2024-12-30", interest: 100 }, { week: "2025-01-06", interest: 80 }, { week: "2025-01-13", interest: 50 },
  { week: "2025-01-20", interest: 35 }, { week: "2025-01-27", interest: 25 }, { week: "2025-02-03", interest: 40 },
  { week: "2025-02-10", interest: 70 }, { week: "2025-02-17", interest: 20 }, { week: "2025-02-24", interest: 10 },
];

export default {
  // Identity
  providerKey: "spartanburg",
  payorKey: "cigna",
  providerName: "Spartanburg Regional Healthcare System",
  payorName: "Cigna Healthcare",
  providerShort: "SRHS",
  payorShort: "Cigna",
  navShort: "SRHS v. Cigna",
  title: "Spartanburg Regional vs Cigna",
  subtitle: "Contract dispute · Resolved February 2025 (multi-year agreement)",
  gradientId: "spartanburgcigna",

  // Dates
  monitorStart: "October 1, 2024",
  monitorEnd: "February 28, 2025",
  disputePublicDate: "2024-11-20",

  // Colors
  colors: {
    providerColor: "#003366",
    payorColor: "#ED6C2B",
    neutral: "#64748B",
    accent: "#003366",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#003366", "#4A6A8A", "#ED6C2B"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"spartanburg regional cigna" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.72,
    nationalMedian: 1.0,
    networkComplaints: 1245,
    priorYearComplaints: 890,
    regulatorAction: "SC Department of Insurance did not publicly intervene. SC Code 38-71-243 provides 90-day continuation of care for serious medical conditions. Federal No Surprises Act protects emergency patients from balance billing. No formal SCDOI investigation opened.",
    signalRead: "Cigna's national complaint index is elevated (1.72x median) driven by simultaneous disputes with multiple health systems across the Southeast and Mid-Atlantic. The 40% increase in network complaints reflects Cigna's aggressive posture on rate negotiations as hospital costs have risen 20% since 2020 while Cigna rates rose ~3%. This is the SECOND Spartanburg Regional disruption in four years — pattern erodes employer confidence.",
  },

  // Executive summary
  executiveSummary: {
    statement: "The dispute resolved with a multi-year agreement in February 2025 after a 6-week out-of-network gap (Jan 1 – mid-Feb). This was the second Cigna network disruption for SRHS in four years, following an 18-month gap from June 2020 to January 2022.",
    keyMessages: [
      "SRHS's 'Cigna is the outlier among national insurers' framing was its stickiest argument — BCBS and Aetna had agreed to rate increases, isolating Cigna.",
      "Rural access angle is uniquely powerful: Cherokee Medical Center and Union Medical Center serve communities where SRHS is the ONLY hospital. Patients literally cannot go elsewhere.",
      "Cigna fighting simultaneous disputes with Bon Secours (SC), UNC Health (NC), Jefferson Health (PA), Ballad Health, and Tenet nationally undermines 'SRHS is unreasonable' framing.",
      "Second disruption in four years damages Cigna's long-term credibility with Upstate SC employers — even if 23% rate claim has employer appeal.",
    ],
    marcomm: [
      "<strong>The 'only hospital' framing is devastating.</strong> In rural Upstate SC, SRHS is the sole provider for multiple counties. No amount of affordability messaging can overcome the reality that Cigna's network disruption left communities without a nearby in-network hospital.",
      "<strong>Repeat disruption is Cigna's biggest vulnerability.</strong> Two network breaks in four years (2020 and 2024) signals to employers that Cigna cannot maintain stable provider relationships in the Upstate SC market. Employer confidence is the long-term casualty.",
      "<strong>Open enrollment timing was strategically significant.</strong> The dispute peaked during November-December open enrollment, when employers and employees could switch away from Cigna. This created competitive pressure that likely accelerated resolution.",
      "<strong>Cigna's 23% rate claim is its strongest card but has diminishing returns.</strong> Hospital wage index up 20% since 2020 while Cigna rates rose ~3% provides SRHS with a powerful counter-narrative about structural underpayment. The math increasingly favors the provider.",
    ],
  },
  channelTakeaways: {
    media: [
      "WSPA (CBS) and Fox Carolina provided the most consistent local coverage — multiple segments from announcement through resolution.",
      "Greenville News (USA Today Network) syndication to Yahoo News extended reach nationally beyond the Upstate SC media market.",
      "Becker's Payer Issues explicitly connected 2020 and 2024 disputes, reinforcing 'pattern of Cigna disruption' narrative for hospital executives.",
      "Holiday timing (contract expiring Dec 31) amplified patient anxiety and ensured maximum media attention at year-end.",
    ],
    social: [
      "Facebook community groups in Spartanburg and Cherokee counties generated intense local engagement — 'where will we go?' captures rural access anxiety.",
      "Gibbs Cancer Center patients in active treatment created maximally sympathetic social content — cancer disruption angle mirrors MSK/UHC dynamic.",
      "Open enrollment overlap meant social media discussions influenced real switching decisions — Cigna at risk of losing commercial lives.",
      "Post-expiration confusion about out-of-network billing generated blame directed at Cigna — patients expected to navigate complex forms during health crises.",
    ],
    stakeholder: [
      "SRHS positioned Cigna as the 'outlier' among national insurers — BCBS and Aetna agreed to rate increases, making Cigna's refusal appear unreasonable.",
      "Simultaneous Cigna disputes with Bon Secours (SC), UNC Health (NC), Jefferson Health (PA), Ballad, and Tenet created national pattern evidence.",
      "SC's 90-day continuation of care law provided some protection but only for serious medical conditions — routine care patients bore full impact.",
      "SRHS's Level I Trauma Center status and sole-provider position in rural counties gave it structural leverage that Cigna could not overcome.",
    ],
    employer: [
      "Cigna's 23% rate increase framing is its strongest employer-facing argument, but the 'only hospital in the county' reality creates counter-pressure employers cannot ignore.",
      "Open enrollment timing (Nov-Dec) meant employers had to make plan decisions during active dispute — some likely added BCBS alternatives.",
      "Self-insured employers face a paradox: out-of-network SRHS claims cost MORE than in-network rates because SRHS is so dominant employees still use it.",
      "Second disruption in four years damages Cigna's network reliability reputation with Upstate SC employers and brokers.",
    ],
  },
};
