// Tenet Healthcare / Baptist Health vs Cigna — PR War Room Config
// Dispute period: ~February–December 2025. Resolved December 31, 2025.
// National multi-state contract dispute: 64 hospitals, ~370 ASCs, 2,000 providers across 7+ states.

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2025-10-02",
    source: "Cronkite News / Arizona PBS",
    url: "https://cronkitenews.azpbs.org/2025/10/02/arizona-medical-providers-patients-facing-rising-insurance-claim-denials/",
    sourceType: "news",
    channel: "media",
    headline: "Arizona AG Kris Mayes launches Consumer Fraud Act investigation into insurance claim denials — Cigna cited",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Arizona AG investigation into rising insurance claim denials. Arizona's in-network denial rate 21% in 2023, above national 19% average. Cigna specifically cited for denying 80 claims from a single Gilbert sports medicine practice. Cigna's new E&M Coding Accuracy policy (R49) criticized for restructuring claims to reimburse at lower rates. Structural regulatory headwind for Cigna during Tenet negotiations.",
  },
  {
    id: 2,
    date: "2025-10-15",
    source: "Becker's Hospital Review",
    url: "https://www.beckershospitalreview.com/payer-issues/tenet-on-cigna-dispute-being-forced-out-of-network-is-unsureance.html",
    sourceType: "news",
    channel: "media",
    headline: "Tenet on Cigna dispute: Being forced out of network is 'unsure-ance'",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Tenet spokesperson Lesley Bogdanow: 'If Tenet is forced out of network, consumers are paying premiums for a partial network with fewer providers.' Introduced 'unsureance' framing — sticky messaging. 11 months of failed negotiations at this point. Cigna accused of demanding 'excessive, unreasonable rate cuts.'",
  },
  {
    id: 3,
    date: "2025-10-15",
    source: "Becker's Payer Issues",
    url: "https://www.beckerspayer.com/payer/tenet-cigna-dispute-heats-up-ahead-of-contract-deadline/",
    sourceType: "news",
    channel: "media",
    headline: "Tenet, Cigna dispute heats up ahead of contract deadline — 64 hospitals at stake",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press. Details scope: 64 hospitals, nearly 370 ASCs, 2,000 providers. Contract expiration Dec 31. States at risk: Alabama, Arizona, California, Florida, South Carolina, Tennessee, Texas. Both sides' positions presented.",
  },
  {
    id: 4,
    date: "2025-10-20",
    source: "Becker's ASC Review",
    url: "https://www.beckersasc.com/asc-coding-billing-and-collections/arizona-cigna-enrollees-may-lose-access-to-tenet-sites-amid-dispute/",
    sourceType: "news",
    channel: "media",
    headline: "Arizona Cigna enrollees may lose access to Tenet sites amid dispute — 413K affected",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "ASC-focused trade coverage. Highlights Cigna trying to slash reimbursement for outpatient care at hundreds of ambulatory surgical centers. 413,000 Arizona enrollees could lose Abrazo Health network access. ASC angle especially important given Tenet's USPI subsidiary dominance.",
  },
  {
    id: 5,
    date: "2025-11-05",
    source: "ABC15 Phoenix",
    url: "https://www.abc15.com/news/business/cigna-and-tenet-healthcare-locked-in-contract-dispute-affecting-413-000-arizona-enrollees",
    sourceType: "tv",
    channel: "media",
    headline: "Cigna and Tenet Healthcare locked in contract dispute affecting 413,000 Arizona enrollees",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Major Phoenix TV affiliate. 413K figure is attention-grabbing for Arizona audience. Abrazo Health is significant safety-net system in Phoenix metro. Cigna's 'low annual rate increases well below inflation' framing favors Tenet. Consumer-facing coverage amplifies patient anxiety.",
  },
  {
    id: 6,
    date: "2025-11-08",
    source: "Phoenix Business Journal (Facebook)",
    sourceType: "social",
    channel: "social",
    headline: "Cigna-Tenet dispute affects 413K in AZ — shared on Phoenix Business Journal Facebook",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Social amplification of business press coverage. Comment sections reflect employer and patient anxiety in Phoenix metro area. Arizona employer decision-makers engaged.",
  },
  {
    id: 7,
    date: "2025-11-10",
    source: "Yahoo Finance",
    url: "https://finance.yahoo.com/news/investors-reacting-tenet-healthcare-thc-010434224.html",
    sourceType: "news",
    channel: "media",
    headline: "How Investors Are Reacting To Tenet Healthcare (THC) Cigna Dispute Over Abrazo Reimbursement Rates",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Investor audience. Share price reaction 'muted' — investors did not see single contract as thesis-breaker. But noted reimbursement tensions can pressure margins. THC stock quietly climbing despite dispute noise. Policy risk around ACA subsidies also flagged.",
  },
  {
    id: 8,
    date: "2025-11-12",
    source: "Simply Wall St",
    url: "https://simplywall.st/stocks/us/healthcare/nyse-thc/tenet-healthcare/news/tenet-healthcare-thc-valuation-check-as-policy-debates-and-c",
    sourceType: "news",
    channel: "media",
    headline: "Tenet Healthcare (THC): Valuation Check as Policy Debates and Cigna Dispute Draw Investor Focus",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Investment analysis platform. Frames dispute as near-term catalyst and risk. Tenet's $20B+ annual revenue gives negotiating leverage. Investor consensus: dispute likely to resolve but terms matter for margin outlook.",
  },
  {
    id: 9,
    date: "2025-11-15",
    source: "Cigna (member notification letters)",
    sourceType: "owned",
    channel: "employer",
    headline: "Cigna mails notification letters to impacted members across 7 states warning of potential network disruption",
    frameAdoption: "cigna",
    sentiment: "negative_tenet",
    patientStory: false,
    blameDirection: "tenet",
    reachEstimate: "high",
    notes: "CRITICAL EMPLOYER CHANNEL. Cigna letters mailed Nov 15 to members in AL, AZ, CA, FL, SC, TN, TX. Creates direct patient anxiety and employer inquiries. Frames Tenet as seeking above-market rates. Triggers broker and HR department scramble for alternatives.",
  },
  {
    id: 10,
    date: "2025-11-20",
    source: "Telegram & Gazette (Worcester, MA)",
    sourceType: "news",
    channel: "media",
    headline: "Tenet runs 'unsure-ance' print ad: 'If you have Cigna, you have health unsureance'",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "PAID MEDIA CAMPAIGN. Tenet placed newspaper ads with 'unsure' emphasized in different color. Direct-to-consumer advertising escalation. Worcester is MetroWest Boston market — Tenet has facilities there. Unusual for hospital system to buy print ads attacking insurer.",
  },
  {
    id: 11,
    date: "2025-11-22",
    source: "Healthcare Uncovered (Substack)",
    url: "https://healthcareuncovered.substack.com/p/battle-between-health-care-giants",
    sourceType: "opinion",
    channel: "media",
    headline: "Battle Between Health Care Giants Puts Patient Access in Jeopardy — deep dive on Tenet/Cigna",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Independent health policy newsletter. Detailed analysis of dispute dynamics. Frames as corporate giants fighting while patients suffer. Cigna's algorithm-based claim denials (PXDX) referenced as pattern of cost-cutting at patient expense.",
  },
  {
    id: 12,
    date: "2025-12-01",
    source: "keepyourhealthcareaccess.com",
    url: "https://www.keepyourhealthcareaccess.com/",
    sourceType: "owned",
    channel: "media",
    headline: "Tenet launches 'Keep Your Healthcare Access' campaign website with petition and Cigna executive contact info",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "OWNED MEDIA ESCALATION. Dedicated campaign site features: patient petition, contact information for Cigna leaders in each market, FAQ explaining dispute from Tenet's perspective. Urges Cigna to 'negotiate on fair and reasonable terms.' Professional PR campaign infrastructure.",
  },
  {
    id: 13,
    date: "2025-12-01",
    source: "keepyourhealthcareaccess.com/faq",
    url: "https://www.keepyourhealthcareaccess.com/faq/",
    sourceType: "owned",
    channel: "media",
    headline: "Tenet FAQ: Cigna's proposal includes 'very low annual rate increases, well below inflation' and cuts to physician/ASC payments",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "FAQ details Tenet's key arguments: Cigna's rates below inflation, inconsistent with other national payors, and Cigna wants to CUT payments for physicians and ASCs. Notes Cigna reported 10% increase in premium revenue per member while refusing fair provider rates. Effective data-driven counter-narrative.",
  },
  {
    id: 14,
    date: "2025-12-05",
    source: "Cigna ('Save Our Healthcare' counter-site)",
    sourceType: "owned",
    channel: "media",
    headline: "Cigna responds: 'Tenet Healthcare is putting its business ahead of people in the communities where they operate'",
    frameAdoption: "cigna",
    sentiment: "negative_tenet",
    patientStory: false,
    blameDirection: "tenet",
    reachEstimate: "medium",
    notes: "Cigna's counter-campaign website. Frames Tenet as corporate chain prioritizing profit. 'Despite our repeated efforts to find common ground.' Both sides now running dueling public campaigns — rare escalation. Cigna's corporate tone less effective than Tenet's patient-access framing.",
  },
  {
    id: 15,
    date: "2025-12-10",
    source: "KTSM 9 News (El Paso)",
    url: "https://www.ktsm.com/news/cigna-tenet-healthcares-negotiation-impasse-could-cost-hundreds-of-episd-employees-coverage/",
    sourceType: "tv",
    channel: "media",
    headline: "Cigna, Tenet Healthcare's negotiation impasse could cost hundreds of EPISD employees coverage",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "EMPLOYER IMPACT STORY. El Paso Independent School District employees with Cigna notified by Hospitals of Providence they may lose in-network access. Public school employee angle is politically potent — taxpayer-funded workers losing healthcare access. Creates pressure from municipal employers on Cigna.",
  },
  {
    id: 16,
    date: "2025-12-10",
    source: "KTSM 9 News (video)",
    url: "https://www.ktsm.com/video/cigna-tenet-dispute-may-impact-healthcare-for-episd-staff/11216344/",
    sourceType: "tv",
    channel: "media",
    headline: "Cigna-Tenet dispute may impact healthcare for EPISD staff — TV segment",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Video segment amplifying print story. Visual of school employees worried about healthcare coverage is compelling local TV content. El Paso border community depends heavily on Hospitals of Providence system.",
  },
  {
    id: 17,
    date: "2025-12-12",
    source: "localmemphis.com (ABC affiliate)",
    url: "https://www.localmemphis.com/article/news/local/if-no-deal-is-struck-between-st-francis-hospital-and-cigna-healthcare-some-patients-may-pay-the-price/522-b616c8ed-65bb-40bb-889d-9187886b21ae",
    sourceType: "tv",
    channel: "media",
    headline: "Cigna Healthcare responds to claims over contract dispute with St. Francis Hospital — 'some patients may pay the price'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: true,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Memphis market coverage. Cigna accused Tenet of 'stoking fear among patients in Memphis as a negotiating tactic.' Tenet responded: 'Cigna insists on misrepresenting the facts and taking steps backwards, demanding excessive, unreasonable rate cuts.' Both sides quoted — rare balanced local coverage. St. Francis Hospital is major Memphis provider.",
  },
  {
    id: 18,
    date: "2025-12-12",
    source: "Becker's Payer Issues",
    url: "https://www.beckerspayer.com/payer/tenet-cigna-hit-contract-snag-for-memphis-hospitals-6-things-to-know/",
    sourceType: "news",
    channel: "media",
    headline: "Tenet, Cigna hit contract snag for Memphis hospitals: 6 things to know",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press Memphis-specific analysis. Six-point breakdown. Hospital leaders cited rising costs (overhead, Rx, healthcare costs) as making it difficult to continue without fair reimbursement. Emergency care would continue at in-network level regardless.",
  },
  {
    id: 19,
    date: "2025-12-15",
    source: "WRHI (Rock Hill, SC)",
    url: "https://www.wrhi.com/2025/12/release-piedmont-medical-center-puts-out-alert-that-many-patience-will-lose-in-network-access-if-cigna-continues-to-refuse-to-negotiate-on-contract-renewal-208712",
    sourceType: "radio",
    channel: "media",
    headline: "Piedmont Medical Center puts out alert: many patients will lose in-network access if Cigna continues to refuse to negotiate",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "South Carolina local radio. Piedmont Medical Center is Tenet-owned facility in Rock Hill. 'Refuses to negotiate' framing places blame squarely on Cigna. Rural/suburban SC patients have fewer alternative hospital options — heightens access anxiety.",
  },
  {
    id: 20,
    date: "2025-12-18",
    source: "South Florida Hospital News",
    url: "https://southfloridahospitalnews.com/healthcare-stress-for-the-holidays-as-insurance-dispute-threatens-access-to-doctors-and-hospitals/",
    sourceType: "news",
    channel: "media",
    headline: "Healthcare Stress for the Holidays as Insurance Dispute Threatens Access to Doctors and Hospitals",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Florida healthcare trade press. 'Healthcare Stress for the Holidays' is potent emotional framing. Over 13,000 Palm Beach patients could lose in-network access. Cigna 'refuses to pay fair rates that reflect current healthcare costs.' Out-of-pocket increases of $6,000+ annually for affected families.",
  },
  {
    id: 21,
    date: "2025-12-20",
    source: "InsuranceNewsNet",
    url: "https://insurancenewsnet.com/oarticle/disputes-between-major-health-insurers-south-florida-hospitals-threaten-higher-costs-for-patients",
    sourceType: "news",
    channel: "media",
    headline: "Disputes between major health insurers, South Florida hospitals threaten higher costs for patients — Cigna/Tenet and Florida Blue/Broward Health",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Insurance industry press. Multiple simultaneous Florida disputes: Cigna/Tenet AND Florida Blue/Broward Health. Pattern framing suggests systemic insurer behavior. 40,000+ policyholders affected across Florida disputes combined.",
  },
  {
    id: 22,
    date: "2025-12-20",
    source: "Live Insurance News",
    url: "https://www.liveinsurancenews.com/south-floridas-health-standoff/8568197/",
    sourceType: "news",
    channel: "media",
    headline: "South Florida's Healthcare Standoff: Patients Caught in the Crossfire",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "'Patients Caught in the Crossfire' framing is anti-insurer. Highlights Palm Beach County's two Level I trauma centers and only children's hospital at stake. Access to critical emergency infrastructure is maximally sympathetic angle.",
  },
  {
    id: 23,
    date: "2025-12-22",
    source: "Tennessee Dept. of Finance & Administration",
    url: "https://www.tn.gov/partnersforhealth/health-options/carrier-network/network-updates.html",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Tennessee state government posts Carrier Network Updates flagging Tenet/Cigna disruption for state employees",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "STATE GOVERNMENT STAKEHOLDER. Tennessee Partners for Health posting network disruption updates for state employees. Government intervention in carrier network disputes signals severity. Memphis St. Francis Hospital is key Tenet facility in TN.",
  },
  {
    id: 24,
    date: "2025-12-24",
    source: "Hoodline (San Antonio)",
    url: "https://hoodline.com/2025/12/san-antonio-braces-for-hospital-shakeup-as-cigna-contract-clock-ticks-down/",
    sourceType: "news",
    channel: "media",
    headline: "San Antonio Families Face Health Coverage Risk Over Cigna Deal — 1.4M Texas families affected",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "MAJOR TEXAS IMPACT. 1.4 million Texas families could be placed out of network. Baptist Health System is major San Antonio provider. Holiday timing amplifies emotional resonance — families worried about healthcare over Christmas. Baptist Health employs thousands in San Antonio.",
  },
  {
    id: 25,
    date: "2025-12-27",
    source: "Hall Benefits Law",
    url: "https://hallbenefitslaw.com/healthcare-system-sues-cigna-over-emergency-care-reimbursements/",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Healthcare System Sues Cigna Over Emergency Care Reimbursements — Tenet/Cigna litigation history analyzed",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Legal analysis. References 2022 lawsuit where 19 Tenet hospitals sued Cigna over low reimbursement rates and denied emergency care claims across AZ, FL, TN, AL, SC, MA. Pattern evidence: Cigna has a long history of underpaying Tenet facilities. EMTALA and Connecticut Unfair Trade Practices Act violations alleged.",
  },
  {
    id: 26,
    date: "2025-12-29",
    source: "KSAT 12 San Antonio (TV)",
    url: "https://www.ksat.com/news/local/2025/12/29/baptist-health-cigna-contract-dispute-could-lead-to-disruption-in-care/",
    sourceType: "tv",
    channel: "media",
    headline: "Baptist Health-Cigna contract dispute could lead to disruption in care — KSAT investigation",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Major San Antonio TV affiliate. Two days before deadline. 1.4M Texas families at risk. Baptist Health is backbone of San Antonio healthcare. KSAT is dominant news source in San Antonio DMA. Holiday timing creates maximum viewer anxiety.",
  },
  {
    id: 27,
    date: "2025-12-29",
    source: "KSAT 12 San Antonio (video)",
    url: "https://www.ksat.com/video/news/2025/12/29/baptist-health-cigna-contract-dispute-could-lead-to-disruption-in-care/",
    sourceType: "tv",
    channel: "media",
    headline: "Baptist Health-Cigna contract dispute could lead to disruption in care — TV segment",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Video segment with reporter standup. Visual of Baptist Health facilities. Community impact framing. Broadcast between Christmas and New Year — captive audience, high emotional resonance.",
  },
  {
    id: 28,
    date: "2025-12-29",
    source: "KSAT 12 (Facebook post)",
    sourceType: "social",
    channel: "social",
    headline: "KSAT posts Baptist Health-Cigna dispute story to Facebook: 'Should the two sides be unable to reach terms before the Dec. 31 deadline...'",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Social amplification of KSAT TV coverage. Facebook comment sections in San Antonio likely highly emotional — Baptist Health serves working-class and military families. Social sharing extends reach beyond TV broadcast audience.",
  },
  {
    id: 29,
    date: "2025-12-29",
    source: "KSAT 12 (X/Twitter post)",
    sourceType: "social",
    channel: "social",
    headline: "KSAT tweets Baptist Health-Cigna dispute story — social amplification",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "X/Twitter amplification. @ksatnews post. Healthcare access disputes trend on X given ongoing anti-insurer sentiment nationally.",
  },
  {
    id: 30,
    date: "2025-12-29",
    source: "El-Balad.com",
    url: "https://www.el-balad.com/6805582",
    sourceType: "news",
    channel: "media",
    headline: "Contract Dispute Between Baptist Health and Cigna May Disrupt Patient Care",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Wire pickup extending reach internationally. Demonstrates story's wire syndication breadth. Factual reporting of dispute and deadline.",
  },
  {
    id: 31,
    date: "2025-12-30",
    source: "CBS12 West Palm Beach",
    url: "https://cbs12.com/news/local/tenet-and-cigna-reach-agreement-to-keep-palm-beach-health-network-in-network-for-patients-south-florida-news-palm-beach-county-january-1-2026",
    sourceType: "tv",
    channel: "media",
    headline: "Tenet and Cigna reach agreement to keep Palm Beach Health Network in-network for patients",
    frameAdoption: "tenet",
    sentiment: "positive_tenet",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "South Florida TV coverage of resolution. Negotiations centered on 'physician-led medical decisions, prior authorization safeguards, and fair reimbursement for emergency care — issues that have drawn scrutiny toward Cigna's use of algorithms in claim denials.' Palm Beach County's two Level I trauma centers and only children's hospital preserved in-network.",
  },
  {
    id: 32,
    date: "2025-12-30",
    source: "Becker's ASC Review",
    url: "https://www.beckersasc.com/asc-coding-billing-and-collections/the-deadline-is-here-tenet-s-outpatient-facilities-will-go-out-of-network-if-cigna-contract-expires.html",
    sourceType: "news",
    channel: "media",
    headline: "The deadline is here: Tenet's outpatient facilities will go out of network if Cigna contract expires",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press deadline-day coverage. ASC focus — Tenet's ~370 ambulatory surgery centers are significant part of dispute. USPI (Tenet's ASC subsidiary) is largest ASC operator in the US.",
  },
  {
    id: 33,
    date: "2025-12-31",
    source: "Becker's Payer Issues",
    url: "https://www.beckerspayer.com/contracting/tenet-cigna-tensions-heat-up-as-contract-deadline-nears/",
    sourceType: "news",
    channel: "media",
    headline: "Cigna, Tenet reach agreement after tense negotiations — confirmed Dec 31",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "RESOLUTION. Cigna spokesperson confirmed Dec 31 to Becker's: 'An agreement has been reached with Tenet Healthcare, their physicians and ambulatory surgery centers to continue providing in-network healthcare with no interruption in coverage for our customers.' Trade press breaks resolution news.",
  },
  {
    id: 34,
    date: "2025-12-31",
    source: "Becker's ASC Review",
    url: "https://www.beckersasc.com/asc-coding-billing-and-collections/tenet-cigna-reach-agreement-after-lengthy-dispute-3-insights.html",
    sourceType: "news",
    channel: "media",
    headline: "Tenet & Cigna reach agreement after lengthy dispute — 3 insights",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "ASC-focused resolution analysis. All Tenet facilities remain in-network for Cigna-HealthSpring Medicare Advantage plans. Multi-year deal. Terms not disclosed. ASC access was key negotiating leverage for Tenet.",
  },
  {
    id: 35,
    date: "2025-12-31",
    source: "KSAT 12 San Antonio",
    url: "https://www.ksat.com/news/local/2025/12/29/baptist-health-cigna-contract-dispute-could-lead-to-disruption-in-care/",
    sourceType: "tv",
    channel: "media",
    headline: "Baptist Health, Cigna reach agreement to keep patients in-network",
    frameAdoption: "tenet",
    sentiment: "positive_tenet",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution coverage in San Antonio. 'Keep patients in-network' framing credits Tenet/Baptist for protecting access. Relief framing after days of anxiety coverage in San Antonio market.",
  },
  {
    id: 36,
    date: "2025-12-31",
    source: "Healthcare Finance News",
    url: "https://www.healthcarefinancenews.com/news/tenet-and-cigna-reach-multi-year-contract-agreement",
    sourceType: "news",
    channel: "media",
    headline: "Tenet and Cigna reach multi-year contract agreement — uninterrupted in-network access preserved",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "National healthcare finance trade press. Multi-year agreement confirmed. 'Cigna's commercial customers will have uninterrupted, in-network access to Tenet Healthcare facilities and affiliated providers.' Medicare Advantage plans also preserved. CFO/finance audience.",
  },
  {
    id: 37,
    date: "2025-12-31",
    source: "HealthLeaders Media",
    url: "https://www.healthleadersmedia.com/finance/tenet-cigna-ink-multi-year-deal",
    sourceType: "news",
    channel: "media",
    headline: "Tenet, Cigna Ink Multi-Year Deal",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Hospital executive audience. 'Ink Multi-Year Deal' frames as business resolution. Terms not disclosed. Hospital leadership readership notes pattern of insurer-provider brinksmanship.",
  },
  {
    id: 38,
    date: "2025-12-31",
    source: "RTTNews",
    url: "https://www.rttnews.com/473014/tenet-healthcare-reaches-multi-year-deal-with-cigna-to-expand-its-network.aspx",
    sourceType: "news",
    channel: "media",
    headline: "Tenet Healthcare Reaches Agreement With Cigna On Multi-Year Contract",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Financial wire service. Investor-focused coverage. THC stock impact angle. Brief factual reporting of resolution.",
  },
  {
    id: 39,
    date: "2025-12-31",
    source: "MarketScreener",
    url: "https://www.marketscreener.com/quote/stock/TENET-HEALTHCARE-CORPORAT-11877509/news/Tenet-Healthcare-Corporation-Reaches-Agreement-with-Cigna-Corporation-on-Multi-Year-Contract-34466056/",
    sourceType: "news",
    channel: "media",
    headline: "Tenet Healthcare Corporation Reaches Agreement with Cigna Corporation on Multi-Year Contract",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Investor platform. Resolution news distributed across financial media. Tenet stock watchers note dispute resolution removes near-term overhang.",
  },
  {
    id: 40,
    date: "2025-12-31",
    source: "DistilINFO Healthplan",
    url: "https://distilinfo.com/healthplan/tenet-cigna-signs-contract-to-extend-network-access/",
    sourceType: "news",
    channel: "media",
    headline: "Tenet-Cigna sign contract to extend network access",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Health plan trade press. Factual resolution coverage. Payer audience notes Cigna's concession after months of brinksmanship.",
  },
  // === TENET OWNED MEDIA ===
  {
    id: 41,
    date: "2025-10-10",
    source: "Tenet Healthcare (broker/agent notification)",
    sourceType: "owned",
    channel: "employer",
    headline: "Tenet notifies health care agents and brokers that Cigna negotiations have stalled — 64 hospitals and 370 ASCs at risk",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "CRITICAL EMPLOYER CHANNEL. First formal broker notification. Triggers benefits consultant cascade — brokers must advise employer clients on contingency plans. Creates downstream pressure on Cigna from employer accounts. Tenet frames Cigna as offering below-inflation rates.",
  },
  {
    id: 42,
    date: "2025-12-01",
    source: "Tenet Healthcare (press statement)",
    sourceType: "owned",
    channel: "media",
    headline: "Tenet: 'While we are negotiating in good faith, Cigna has proposed contract terms that could put patient care and access at risk'",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Key Tenet framing: Cigna reported 10% increase in premium revenue per member while refusing fair provider rates. Effective hypocrisy argument — insurer profits up, provider payments flat or cut. Data point widely cited by media.",
  },
  {
    id: 43,
    date: "2025-12-15",
    source: "Baptist Health System (patient notification)",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "Baptist Health System San Antonio sends patient notifications about potential Cigna out-of-network status",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Direct patient communication. Baptist Health is beloved San Antonio institution — local identity framing. Military families, working-class families in San Antonio deeply dependent on Baptist Health. Creates grassroots pressure on Cigna.",
  },
  {
    id: 44,
    date: "2025-12-20",
    source: "Hospitals of Providence (El Paso patient notification)",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "Hospitals of Providence notifies EPISD employees and El Paso patients of potential Cigna out-of-network status",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "El Paso-specific patient outreach. Hospitals of Providence is dominant hospital system in El Paso. Border community with limited alternative options. Public school district employees especially affected.",
  },
  {
    id: 45,
    date: "2025-12-22",
    source: "Abrazo Health (Arizona patient notification)",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "Abrazo Health sends notifications to 413K Arizona Cigna enrollees about potential network disruption",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Arizona-specific patient outreach. 413,000 enrollees is massive footprint. Abrazo operates safety-net hospitals in Phoenix metro area. Many patients have limited alternatives for emergency and specialty care.",
  },
  // === CIGNA OWNED MEDIA ===
  {
    id: 46,
    date: "2025-11-15",
    source: "Cigna Healthcare (public statement)",
    sourceType: "owned",
    channel: "media",
    headline: "Cigna: 'Tenet Healthcare is a national healthcare chain putting its business ahead of people in the communities where they operate'",
    frameAdoption: "cigna",
    sentiment: "negative_tenet",
    patientStory: false,
    blameDirection: "tenet",
    reachEstimate: "medium",
    notes: "Cigna's primary counter-narrative. Frames Tenet as corporate chain vs community. 'Despite our repeated efforts to find common ground.' Defensive corporate tone. 'Healthcare chain' language attempts to depersonalize Tenet's local hospital brands.",
  },
  {
    id: 47,
    date: "2025-12-12",
    source: "Cigna Healthcare (Memphis statement)",
    sourceType: "owned",
    channel: "media",
    headline: "Cigna accuses Tenet of 'stoking fear among patients in Memphis as a negotiating tactic'",
    frameAdoption: "cigna",
    sentiment: "negative_tenet",
    patientStory: false,
    blameDirection: "tenet",
    reachEstimate: "medium",
    notes: "Cigna's most aggressive public statement. 'Tenet and St. Francis are seeking rates and terms that would inflate the cost of health care services far beyond what is reasonable.' Claims Tenet using patient fear as leverage. Tenet responded: 'Cigna insists on misrepresenting the facts.'",
  },
  {
    id: 48,
    date: "2025-12-31",
    source: "Cigna spokesperson Madeline Ziomek",
    sourceType: "owned",
    channel: "media",
    headline: "Cigna confirms resolution: 'An agreement has been reached... to continue providing in-network health care with no interruption'",
    frameAdoption: "cigna",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution statement from named Cigna spokesperson to Becker's. Conciliatory tone. 'No interruption in coverage' frames as Cigna protecting members. Does not disclose terms — suggests Cigna may have conceded on rates.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 49,
    date: "2025-12-10",
    source: "Social media (San Antonio community)",
    sourceType: "social",
    channel: "social",
    headline: "San Antonio residents share Baptist Health/Cigna dispute on social media — anxiety about losing 'their hospital'",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Baptist Health has deep community identity in San Antonio. Patients view it as 'their' hospital, not a corporate chain. Social sharing emphasizes personal healthcare relationships at risk. Military community (Ft. Sam Houston, Lackland) especially vocal.",
  },
  {
    id: 50,
    date: "2025-12-15",
    source: "Social media (Arizona patient community)",
    sourceType: "social",
    channel: "social",
    headline: "Arizona patients share fears about losing Abrazo Health network access — Cigna blamed",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Arizona social media engagement around 413K enrollee figure. Abrazo hospitals serve underserved communities in Phoenix. Patients with limited English proficiency especially vulnerable to network disruption. Community advocacy groups amplify.",
  },
  {
    id: 51,
    date: "2025-12-20",
    source: "Social media (anti-insurer meta-narrative)",
    sourceType: "social",
    channel: "social",
    headline: "Tenet/Cigna dispute fuels broader anti-insurer social media sentiment — PXDX algorithm controversy resurfaces",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "STRUCTURAL CONTEXT: Cigna's PXDX algorithm controversy (ProPublica 2023) — doctors denying claims in 1.2 seconds without reading them, 300K claims denied in 2 months — creates permanent reputational liability. Every Cigna dispute now framed through 'algorithm denials' lens. Congressional investigation ongoing. Class action lawsuit advancing in federal court.",
  },
  {
    id: 52,
    date: "2025-12-28",
    source: "Social media (El Paso community)",
    sourceType: "social",
    channel: "social",
    headline: "El Paso EPISD employees share Cigna/Hospitals of Providence dispute on social media — public employee healthcare anxiety",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Public school employee angle resonates strongly. Teachers and staff sharing concerns about losing access to only major hospital system in El Paso. Border community healthcare access is already strained.",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 53,
    date: "2025-10-02",
    source: "Arizona AG Kris Mayes",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Arizona AG opens Consumer Fraud Act investigation into insurance claim denials — Cigna among targets",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "REGULATORY STAKEHOLDER. AG Mayes investigating whether private health insurers violated Arizona Consumer Fraud Act through false pretense or concealment. Cigna's E&M Coding Accuracy policy and claim denials under scrutiny. Creates regulatory backdrop that disadvantages Cigna during Tenet negotiations.",
  },
  {
    id: 54,
    date: "2025-11-01",
    source: "ProPublica PXDX investigation (ongoing impact)",
    url: "https://www.propublica.org/article/cigna-pxdx-medical-health-insurance-rejection-claims",
    sourceType: "news",
    channel: "stakeholder",
    headline: "ProPublica PXDX investigation: Cigna used algorithm to auto-deny 300,000 claims in 2 months — ongoing class action",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "PATTERN EVIDENCE. 2023 ProPublica investigation revealed Cigna's PXDX system: single doctor could deny 60,000 claims/month, 1.2 seconds per denial, no patient file review. Federal judge advanced class action (Kisting-Leung v. Cigna). Congressional Energy & Commerce Committee investigation. $172M DOJ False Claims Act settlement. Permanent reputational damage.",
  },
  {
    id: 55,
    date: "2025-11-20",
    source: "Lesley Bogdanow, Tenet Healthcare spokesperson",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Tenet spokesperson: 'Cigna shouldn't get to choose where patients go... that's what Cigna is trying to do'",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Named spokesperson with consistent messaging. Key framing: forced out of network = 'unsureance.' Tenet had been negotiating in good faith for close to a year. Cigna 'repeatedly made unreasonable demands.' Effective media surrogate providing quotable sound bites.",
  },
  {
    id: 56,
    date: "2025-12-01",
    source: "19 Tenet hospitals vs Cigna lawsuit (2022 precedent)",
    url: "https://www.beckerspayer.com/payer/19-tenet-hospitals-sue-cigna-over-alleged-low-reimbursement-rates-denied-claims/",
    sourceType: "news",
    channel: "stakeholder",
    headline: "19 Tenet hospitals sued Cigna in 2022 over low reimbursement rates and denied emergency claims across 6 states",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "LITIGATION PATTERN. Hospitals across AZ, FL, TN, AL, SC, MA alleged 'ongoing pattern of financial misconduct.' Cigna's 'narrow networks' and 'unilateral payment methodology' resulting in 'steeply discounted payments.' EMTALA violations alleged. Demonstrates multi-year history of Cigna underpayment — not a new dispute.",
  },
  {
    id: 57,
    date: "2025-12-08",
    source: "Baptist Memorial v. Cigna (W.D. Tennessee)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Federal court grants Baptist Memorial's motion to remand in Cigna case — Chief Judge Lipman ruling",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Legal proceeding. Baptist Memorial Health Care Corporation v. Cigna HealthCare of Tennessee (Case No. 2:2025cv02750). Court sided with Baptist on procedural motion. Active litigation running parallel to contract negotiations adds pressure on Cigna.",
  },
  {
    id: 58,
    date: "2025-12-15",
    source: "Sixth Circuit Court of Appeals (Cigna precedent)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Sixth Circuit rejects hospitals' expanded payment claim against Cigna — but affirms right to challenge reimbursement methodology",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "AMISUB v. Cigna Health & Life. Sixth Circuit ruled against hospitals seeking 'full value' for emergency services. But litigation confirms broader pattern of Cigna reimbursement disputes with hospital systems across the country. Legal landscape complex.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 59,
    date: "2025-10-15",
    source: "Employer/broker communications (national)",
    sourceType: "owned",
    channel: "employer",
    headline: "Benefits brokers begin advising employer clients about potential Tenet/Cigna network disruption across 7 states",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "EMPLOYER CHANNEL ACTIVATION. Multi-state employer plans with Cigna face potential loss of 64 hospitals and 370 ASCs. Self-funded employers especially exposed. Open enrollment timing (Oct-Nov) amplifies employer anxiety — some employers may switch away from Cigna for 2026.",
  },
  {
    id: 60,
    date: "2025-12-10",
    source: "EPISD (El Paso ISD) employee benefits",
    sourceType: "news",
    channel: "employer",
    headline: "EPISD employee benefits office scrambles to advise hundreds of Cigna-covered employees about potential Tenet network loss",
    frameAdoption: "tenet",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "PUBLIC EMPLOYER IMPACT. School district HR departments forced to field questions from worried employees. Public sector employers cannot easily switch insurers mid-year. Creates political pressure — elected school board members face constituent complaints about healthcare access.",
  },
  // === POST-RESOLUTION COVERAGE ===
  {
    id: 61,
    date: "2025-12-31",
    source: "Spot On Florida (Southeast FL)",
    url: "https://spotonflorida.com/southeast-florida/5906448/tenet-and-cigna-reach-agreement-to-keep.html",
    sourceType: "news",
    channel: "media",
    headline: "Tenet and Cigna reach agreement to keep Palm Beach Health Network in-network for patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Regional Florida outlet. Resolution coverage. 1.3 million Floridians preserved in-network access. Palm Beach County trauma centers and children's hospital access preserved.",
  },
  {
    id: 62,
    date: "2025-12-31",
    source: "NewsRadio WIOD / iHeart Florida affiliates",
    url: "https://wiod.iheart.com/featured/florida-news/content/2026-01-02-more-than-million-floridians-saved-from-losing-coverage-at-7-hospitals/",
    sourceType: "radio",
    channel: "media",
    headline: "More Than A Million Floridians Saved From Losing Coverage At 7 Hospitals",
    frameAdoption: "tenet",
    sentiment: "positive_tenet",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "iHeart Radio Florida network. 'Saved From Losing Coverage' implies Tenet fought to protect patients. Syndicated across WIOD, Vero Patriot, Real Radio 92.1, 1290 WJNO — wide Florida radio footprint. 'More Than A Million' headline maximizes perceived impact.",
  },
  {
    id: 63,
    date: "2025-12-31",
    source: "Cigna (continuity of care notice)",
    sourceType: "owned",
    channel: "employer",
    headline: "Cigna issues continuity of care guidance: patients undergoing certain treatments may continue in-network access during transition",
    frameAdoption: "cigna",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Cigna's member protection framing. Continuity of care provisions would have applied if contract lapsed — determined by Cigna. Moot point given resolution, but signals Cigna was preparing for potential disruption scenario.",
  },
  {
    id: 64,
    date: "2025-12-31",
    source: "Tenet Healthcare (resolution press statement)",
    sourceType: "owned",
    channel: "media",
    headline: "Tenet emphasizes resolution 'reflects its commitment to patient-first principles' — multi-year agreement secured",
    frameAdoption: "tenet",
    sentiment: "positive_tenet",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Victory framing. 'Patient-first principles' implies Cigna was not patient-first. Multi-year agreement suggests Tenet secured favorable terms. No rate details disclosed — typical of resolved disputes. Tenet claims credit for protecting access.",
  },
  {
    id: 65,
    date: "2025-12-31",
    source: "Justia (case law database)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Baptist Memorial v. Cigna Tennessee litigation continues alongside contract resolution — separate tracks",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Legal database tracking. Contract resolution does not necessarily resolve separate reimbursement litigation. Multiple Tenet/Cigna cases remain active in federal courts. Ongoing litigation leverage for future negotiations.",
  },
];

const LABELS = {
  frameAdoption: { tenet: "Tenet Frame", cigna: "Cigna Frame", balanced: "Balanced" },
  sentiment: {
    negative_cigna: "Anti-Cigna",
    negative_tenet: "Anti-Tenet",
    neutral: "Neutral",
    positive_cigna: "Pro-Cigna",
    positive_tenet: "Pro-Tenet",
  },
  blameDirection: { cigna: "Blames Cigna", tenet: "Blames Tenet", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National record (1.5)
  "Healthcare Finance News": 1.5, "Yahoo Finance": 1.5, "CBS12 West Palm Beach": 1.5,
  "ABC15 Phoenix": 1.5, "ProPublica PXDX investigation (ongoing impact)": 1.5,
  // Tier 2 — Regional authority (1.2)
  "KSAT 12 San Antonio (TV)": 1.2, "KSAT 12 San Antonio (video)": 1.2, "KSAT 12 San Antonio": 1.2,
  "KTSM 9 News (El Paso)": 1.2, "KTSM 9 News (video)": 1.2,
  "localmemphis.com (ABC affiliate)": 1.2, "Cronkite News / Arizona PBS": 1.2,
  "NewsRadio WIOD / iHeart Florida affiliates": 1.2,
  // Tier 3 — Trade/niche (1.0)
  "Becker's Hospital Review": 1.0, "Becker's Payer Issues": 1.0, "Becker's ASC Review": 1.0,
  "HealthLeaders Media": 1.0, "South Florida Hospital News": 1.0, "InsuranceNewsNet": 1.0,
  "Live Insurance News": 1.0, "Simply Wall St": 1.0, "RTTNews": 1.0, "MarketScreener": 1.0,
  "DistilINFO Healthplan": 1.0, "Hoodline (San Antonio)": 1.0, "Spot On Florida (Southeast FL)": 1.0,
  "El-Balad.com": 1.0, "Telegram & Gazette (Worcester, MA)": 1.0,
  "WRHI (Rock Hill, SC)": 1.0, "Hall Benefits Law": 1.0, "Justia (case law database)": 1.0,
  "Healthcare Uncovered (Substack)": 1.0,
  // Tier 4 — Organic social (0.7)
  "KSAT 12 (Facebook post)": 0.7, "KSAT 12 (X/Twitter post)": 0.7,
  "Phoenix Business Journal (Facebook)": 0.7,
  "Social media (San Antonio community)": 0.7, "Social media (Arizona patient community)": 0.7,
  "Social media (anti-insurer meta-narrative)": 0.7, "Social media (El Paso community)": 0.7,
  // Tier 5 — Comment sections (0.4)
  // (none tracked individually in this dispute)
  // Tier 6 — Owned/party media (0.3)
  "keepyourhealthcareaccess.com": 0.3, "keepyourhealthcareaccess.com/faq": 0.3,
  "Tenet Healthcare (broker/agent notification)": 0.3, "Tenet Healthcare (press statement)": 0.3,
  "Tenet Healthcare (resolution press statement)": 0.3,
  "Baptist Health System (patient notification)": 0.3,
  "Hospitals of Providence (El Paso patient notification)": 0.3,
  "Abrazo Health (Arizona patient notification)": 0.3,
  "Cigna Healthcare (public statement)": 0.3, "Cigna Healthcare (Memphis statement)": 0.3,
  "Cigna ('Save Our Healthcare' counter-site)": 0.3, "Cigna spokesperson Madeline Ziomek": 0.3,
  "Cigna (member notification letters)": 0.3, "Cigna (continuity of care notice)": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "Arizona AG Kris Mayes": 1.3, "Lesley Bogdanow, Tenet Healthcare spokesperson": 1.3,
  "Tennessee Dept. of Finance & Administration": 1.3,
  "19 Tenet hospitals vs Cigna lawsuit (2022 precedent)": 1.3,
  "Baptist Memorial v. Cigna (W.D. Tennessee)": 1.3,
  "Sixth Circuit Court of Appeals (Cigna precedent)": 1.3,
  // Tier 8 — Employer/Benefits (1.5x trade, 1.8x consultant)
  "EPISD (El Paso ISD) employee benefits": 1.5,
  "Employer/broker communications (national)": 1.5,
};

const SEARCH_TRENDS = [
  { week: "2025-09-01", interest: 2 }, { week: "2025-09-08", interest: 3 }, { week: "2025-09-15", interest: 3 },
  { week: "2025-09-22", interest: 5 }, { week: "2025-09-29", interest: 8 }, { week: "2025-10-06", interest: 12 },
  { week: "2025-10-13", interest: 18 }, { week: "2025-10-20", interest: 22 }, { week: "2025-10-27", interest: 20 },
  { week: "2025-11-03", interest: 25 }, { week: "2025-11-10", interest: 30 }, { week: "2025-11-17", interest: 35 },
  { week: "2025-11-24", interest: 28 }, { week: "2025-12-01", interest: 40 }, { week: "2025-12-08", interest: 55 },
  { week: "2025-12-15", interest: 70 }, { week: "2025-12-22", interest: 88 }, { week: "2025-12-29", interest: 100 },
];

export default {
  active: false,
  // Identity
  providerKey: "tenet",
  payorKey: "cigna",
  providerName: "Tenet Healthcare / Baptist Health",
  payorName: "Cigna Healthcare",
  providerShort: "Tenet",
  payorShort: "Cigna",
  navShort: "Tenet v. Cigna",
  title: "Tenet/Baptist vs Cigna",
  subtitle: "National contract dispute · Resolved December 31, 2025",
  gradientId: "tenetcigna",

  // Dates
  monitorStart: "September 1, 2025",
  monitorEnd: "December 31, 2025",
  disputePublicDate: "2025-10-02",

  // Colors
  colors: {
    providerColor: "#003366",
    payorColor: "#E8700A",
    neutral: "#64748B",
    accent: "#003366",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#003366", "#5A6B7F", "#E8700A"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"tenet healthcare cigna contract dispute" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.87,
    nationalMedian: 1.0,
    networkComplaints: 2340,
    priorYearComplaints: 1680,
    regulatorAction: "Arizona AG Kris Mayes opened Consumer Fraud Act investigation into insurance claim denials (Oct 2025), with Cigna among targets. Tennessee Dept. of Finance & Administration posted carrier network updates for state employees. No formal multi-state regulatory intervention, but AG investigation creates backdrop of regulatory scrutiny.",
    signalRead: "Cigna's national complaint index is elevated (1.87x median) driven by PXDX algorithm denial controversy, multi-state provider disputes, and rising claim denial rates. The 39% increase in network complaints reflects Cigna's aggressive reimbursement posture across hospital systems (Tenet, BJC, Piedmont). Arizona's 21% denial rate (above 19% national average) adds state-specific regulatory risk.",
  },

  // Executive summary
  executiveSummary: {
    statement: "The dispute resolved via 11th-hour deal on December 31, 2025 — no actual disruption occurred, but Cigna sustained significant PR damage across 7 states over 11 months of failed negotiations.",
    keyMessages: [
      "Tenet's 'Cigna reported 10% premium revenue growth per member while refusing fair provider rates' is the stickiest hypocrisy argument — pits Cigna's profitability against its reimbursement offers.",
      "The multi-state, multi-brand nature of this dispute (Baptist Health, Abrazo Health, Hospitals of Providence, Piedmont Medical Center, St. Francis Hospital, Palm Beach Health Network) made Cigna appear to be fighting an entire healthcare system, not a single hospital.",
      "Cigna's PXDX algorithm controversy (ProPublica 2023, ongoing class action, congressional investigation) creates permanent reputational liability that colors every subsequent dispute — 'algorithm denials' is now Cigna's defining narrative.",
      "Holiday timing (dispute peak Dec 22-31) maximized emotional resonance — families worried about losing healthcare access over Christmas and New Year. 'Healthcare Stress for the Holidays' framing was devastating.",
    ],
    marcomm: [
      "<strong>Multi-state footprint is Tenet's structural advantage.</strong> With 64 hospitals and 370 ASCs across 7 states, every local market generates its own media cycle. Cigna had to fight a PR war on seven fronts simultaneously — KSAT in San Antonio, KTSM in El Paso, ABC15 in Phoenix, localmemphis.com in Memphis, CBS12 in Palm Beach, WRHI in Rock Hill. No single Cigna communications team can manage that many local narratives.",
      "<strong>Local hospital brands trump corporate identity.</strong> Patients think of 'Baptist Health' and 'Abrazo Health,' not 'Tenet Healthcare Corporation.' This gives Tenet a community-identity advantage that Cigna's 'national healthcare chain' framing cannot overcome. Employers also identify with local facilities, not parent corporations.",
      "<strong>The PXDX overhang is permanent.</strong> Cigna's algorithm-based claim denial controversy (300,000 claims denied in 2 months, 1.2 seconds per denial, no file review) means every Cigna dispute will be framed through the 'algorithm denials' lens. Congressional and class action scrutiny ongoing. This is Cigna's equivalent of UHC's post-Thompson social media problem.",
      "<strong>Employer channel was the decisive pressure point.</strong> Public school districts (EPISD), state employee plans (Tennessee), and self-funded employers across 7 states all faced potential network disruption during open enrollment season. Brokers advising clients to consider switching away from Cigna created commercial pressure that PR alone could not achieve.",
    ],
  },
  channelTakeaways: {
    media: [
      "KSAT San Antonio was the highest-impact outlet — 1.4M Texas families affected is the largest single-market figure, and Baptist Health's community identity in San Antonio is unmatched.",
      "ABC15 Phoenix's 413K Arizona enrollee figure was the most-cited statistic nationally — clean number, easy to grasp, widely syndicated.",
      "Trade press (Becker's, Healthcare Finance News, HealthLeaders) provided sustained coverage over months — unusual for provider-payor disputes, reflecting multi-state scale.",
      "iHeart Radio Florida network's 'More Than A Million Floridians Saved' headline gave Tenet a victory narrative that framed resolution as rescue from Cigna's threat.",
      "Tenet's 'unsureance' paid media campaign in the Telegram & Gazette was an unusual direct-to-consumer advertising escalation for a hospital system.",
    ],
    social: [
      "KSAT Facebook and Twitter posts amplified San Antonio coverage into social feeds — comment sections reflected deep community attachment to Baptist Health.",
      "Cigna's PXDX algorithm controversy provided a ready-made anti-Cigna narrative that social media users attached to the Tenet dispute. Every mention of Cigna now triggers 'algorithm denials' association.",
      "Phoenix Business Journal's Facebook distribution reached Arizona employer decision-makers in social context — more casual, emotional engagement than business press alone.",
      "El Paso community social media activity around EPISD employees created grassroots pressure that complemented formal media coverage.",
    ],
    stakeholder: [
      "Arizona AG Kris Mayes' Consumer Fraud Act investigation into insurance claim denials created regulatory headwind for Cigna during Tenet negotiations — even though the investigation was not Tenet-specific, it colored the environment.",
      "19 Tenet hospitals' 2022 lawsuit against Cigna provided litigation pattern evidence: 'ongoing pattern of financial misconduct' across 6 states. Not a new dispute — this is a multi-year reimbursement conflict.",
      "Tennessee state government posting carrier network updates for state employees demonstrated that government entities were actively tracking the dispute's potential impact on their workforce.",
      "Baptist Memorial v. Cigna federal court proceedings running parallel to contract negotiations added litigation pressure — court granted Baptist's motion to remand (Dec 8), a procedural win for the hospital system.",
    ],
    employer: [
      "Tenet's broker/agent notification in October triggered a cascade of employer contingency planning across 7 states — benefits consultants had to advise clients during open enrollment season, creating downstream pressure on Cigna.",
      "EPISD (El Paso ISD) is the employer impact story that resonated most — public school employees losing hospital access is politically toxic for Cigna. Elected school board members face constituent pressure.",
      "Cigna's November 15 member notification letters across 7 states simultaneously created employer panic at scale — HR departments flooded with employee questions during the holidays.",
      "Open enrollment timing (Oct-Nov) meant some employers may have begun exploring alternatives to Cigna for 2026, creating commercial pressure beyond the immediate dispute.",
    ],
  },
  arguments: {
    payor: [
      { phase: "Early (Oct–Nov 2025)", points: ["Mailed notification letters to members across <strong>7 states</strong> warning of potential network disruption — creating direct patient and employer anxiety", "Framed Tenet as seeking rates <strong>'far beyond what is reasonable'</strong> and putting 'business ahead of people in the communities where they operate'", "Accused Tenet of <strong>'stoking fear among patients as a negotiating tactic'</strong> (Memphis market)"] },
      { phase: "Counter-Campaign (Dec 2025)", points: ["Launched 'Save Our Healthcare' counter-site — framed Tenet as a for-profit chain prioritizing shareholders", "Insisted on <strong>state-based contracts</strong> vs Tenet's preferred national deal structure", "Corporate tone was less effective than Tenet's patient-access and 'unsure-ance' framing"] },
      { phase: "Resolution (Dec 2025)", points: ["Agreed to multi-year deal on December 31 — all 64 hospitals, ~370 ASCs, and 2,000 providers remain in-network", "Negotiations centered on prior authorization safeguards, physician-led medical decisions, and fair emergency reimbursement"] },
    ],
    provider: [
      { phase: "Early (Oct 2025)", points: ["Spokesperson Lesley Bogdanow introduced <strong>'unsure-ance'</strong> framing: 'If Tenet is forced out of network, consumers are paying premiums for a partial network with fewer providers'", "Accused Cigna of demanding <strong>'excessive, unreasonable rate cuts'</strong> after 11 months of failed negotiations", "Quantified massive scale: 64 hospitals, ~370 ASCs, 2,000 providers across AL, AZ, CA, FL, SC, TN, TX"] },
      { phase: "Escalation (Nov–Dec 2025)", points: ["Launched <strong>KeepYourHealthcareAccess.com</strong> campaign site with patient petition and Cigna executive contact info", "Ran paid newspaper ads with 'unsure-ance' messaging — unusual for hospital systems to buy print ads attacking insurers", "Cited Cigna's <strong>10% premium revenue increase per member</strong> while refusing fair provider rates", "Arizona AG investigation into Cigna claim denials and Cigna's paused E&M downcoding policy (R49) created regulatory headwinds"] },
      { phase: "Resolution (Dec 2025)", points: ["Multi-year national contract preserved on December 31 — no interruption in coverage", "Market-by-market announcements (Palm Beach, Texas Baptist, national) built momentum toward deadline-day resolution", "2022 lawsuit where 19 Tenet hospitals sued Cigna over emergency care reimbursement provided legal leverage backdrop"] },
    ],
  },
  timeline: [
    { date: "2025-10-02", type: "newsBreak", label: "News breaks publicly" },
    { date: "2025-12-31", type: "termination", label: "Contract set to terminate" },
    { date: "2025-12-31", type: "agreement", label: "Agreement reached" },
  ],
};
