// UNC Health vs Cigna — PR War Room Config
// Dispute period: July–December 2025. 12-day gap Dec 1-12. Resolved December 12, 2025.

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2025-07-02",
    source: "Axios Raleigh",
    url: "https://www.axios.com/local/raleigh/2025/07/02/unc-health-s-latest-contract-dispute",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health's latest contract dispute — Cigna negotiations stall, 60,000+ patients at risk",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "First major public reporting. Axios Raleigh breaks news that UNC Health and Cigna have failed to reach agreement. UNC Health spokesperson says system 'not satisfied with Cigna's reimbursement rates, its use of prior authorization and how often the insurer is denying coverage.' Cigna counters UNC demands 'well above market levels.' Sets narrative framework early.",
  },
  {
    id: 2,
    date: "2025-07-15",
    source: "WRAL",
    sourceType: "tv",
    channel: "media",
    headline: "UNC Health warns patients about Cigna contract dispute — 65,000 members could lose in-network access",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "WRAL is the dominant Triangle TV station. First of 7+ WRAL stories. UNC Health frames dispute around patient access and Cigna's excessive prior authorization practices. 65,000 member figure becomes standard across all coverage.",
  },
  {
    id: 3,
    date: "2025-07-20",
    source: "CBS17",
    url: "https://www.cbs17.com/news/north-carolina-news/unc-health-warns-cigna-coverage-may-change-this-year-for-patients-if-fair-agreement-not-reached/",
    sourceType: "tv",
    channel: "media",
    headline: "Cigna members could lose coverage at UNC Health in late 2025 — patients told to prepare",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CBS17 first story. 'Could lose coverage' framing. Patient preparation angle — service journalism that inherently positions patients as victims of institutional dispute. Nov 30 deadline introduced to public.",
  },
  {
    id: 4,
    date: "2025-08-15",
    source: "ABC11 / WTVD",
    sourceType: "tv",
    channel: "media",
    headline: "Another NC hospital and insurance company threaten end of in-network coverage — UNC/UHC precedent cited",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "ABC11 contextualizes UNC-Cigna within broader NC provider-payor trend. Cites UNC's prior dispute with UnitedHealthcare (resolved March 2024) as pattern evidence. Systemic framing — 'another' dispute normalizes UNC's position.",
  },
  {
    id: 5,
    date: "2025-09-18",
    source: "WRAL",
    url: "https://www.wral.com/lifestyles/health/nc-parents-critically-ill-baby-unc-cigna-stalemate-december-2025/",
    sourceType: "tv",
    channel: "media",
    headline: "'Incredible stress': Parents of sick baby scramble for care amid UNC Health-Cigna stalemate",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "CRITICAL PATIENT STORY. Patric Pederson and 11-month-old son Stanley. In first year of life, UNC doctors helped Stanley survive bacterial meningitis, respiratory syncytial virus (RSV), and strokes. 'Incredible stress' of potentially losing access to Stanley's care team. Sick baby story is maximally sympathetic — impossible for Cigna to counter.",
  },
  {
    id: 6,
    date: "2025-10-05",
    source: "WRAL",
    url: "https://www.wral.com/news/local/apex-leaders-unc-health-cigna-contract-resolution-town-workers-coverage-december-2025/",
    sourceType: "tv",
    channel: "media",
    headline: "Town of Apex pressuring Cigna and UNC Health to strike new deal — 850 employees affected",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Municipal government story. Town of Apex (Mayor Jacques Gilbert, Town Manager Randy Vosburg) in 'near constant contact' with both parties. 850+ employees and families affected. Gilbert: 'I am extremely concerned. Anything that impacts our staff and their families.' Concrete employer defection threat.",
  },
  {
    id: 7,
    date: "2025-10-22",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health-Cigna contract dispute: what to know — Cigna claims rate increase demanded 'well above market levels'",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press roundup. Cigna's claim that UNC demands rate increases 'well above market levels.' UNC counters with grievances about inadequate rates, excessive prior auth, and high denial rates. Hospital executive audience.",
  },
  {
    id: 8,
    date: "2025-11-01",
    source: "CBS17",
    sourceType: "tv",
    channel: "media",
    headline: "UNC Health announces Cigna customers will no longer be in network — open enrollment warning",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "CBS17 second major story. Coincides with start of Cigna open enrollment (Nov 1-Dec 15). UNC Health encourages employers and patients to consider alternative plans. Open enrollment timing makes dispute actionable — patients can switch.",
  },
  {
    id: 9,
    date: "2025-11-05",
    source: "WRAL",
    sourceType: "tv",
    channel: "media",
    headline: "Cancer survivor Becky Pezzoni fears losing UNC Rex — 'the patient got lost in all of this'",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "CRITICAL PATIENT STORY. Becky Pezzoni: cancer survivor, credits UNC Rex with saving her life. Employer only offers Cigna — no choice. Four prescriptions at risk. 'God forbid something happens where it comes back... How do you make that decision between the hospital system that you literally trust with your life or the cost?' Trapped-patient narrative is devastating for Cigna.",
  },
  {
    id: 10,
    date: "2025-11-10",
    source: "WBT Radio Charlotte",
    sourceType: "radio",
    channel: "media",
    headline: "UNC Health ends Cigna contract after negotiations fall through — Charlotte audience briefed",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Charlotte radio extends coverage beyond Triangle market. WBT is legacy AM talk station with older demographic — key insurance consumer audience. UNC Health has clinics statewide including western NC. First major non-Triangle media.",
  },
  {
    id: 11,
    date: "2025-11-12",
    source: "ABC11 / WTVD",
    sourceType: "tv",
    channel: "media",
    headline: "Diabetic man nearly died from coma, now fears losing UNC doctors — Jon Markle on fixed income",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Jon Markle (~80, Raleigh): diabetic, nearly died from coma. 'I am on a very fixed income. I don't have a lot of money. I can't afford to do that every time I see a doctor or a specialist.' Elderly patient on fixed income — deeply sympathetic. ABC11/WTVD is second-largest Triangle TV station.",
  },
  {
    id: 12,
    date: "2025-11-18",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health-Cigna talks deadlocked: Cigna cites rate demands, UNC cites 30% denial rate and downcoded claims",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Second Becker's piece. Both sides' claims presented. Cigna alleges rate hike demand; UNC's grievances: inadequate rates, excessive prior authorization expanded beyond MRIs to routine labs/meds/specialty visits, 30% denial rate, downcoded claims, delayed payments. Trade press gives UNC's operational grievances equal weight.",
  },
  {
    id: 13,
    date: "2025-11-20",
    source: "HealthLeaders",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health-Cigna standoff highlights prior auth and denial rate tensions in provider-payor disputes",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Trade press. Focuses on UNC's operational grievances — prior auth burden (each authorization with delays, follow-up calls, peer-to-peer reviews, staff time) and denial rates. Systemic framing positions Cigna's administrative practices as root cause. Healthcare executive audience.",
  },
  {
    id: 14,
    date: "2025-11-22",
    source: "ABC11 / WTVD",
    sourceType: "tv",
    channel: "media",
    headline: "Zack Roscoe: 'the richest country in the world and this is how it impacts the people'",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Zack Roscoe patient story. Populist framing — 'richest country in the world' resonates broadly. Connects individual dispute to systemic healthcare frustration. Strong soundbite for social sharing.",
  },
  {
    id: 15,
    date: "2025-11-25",
    source: "WRAL",
    url: "https://www.wral.com/news/local/unc-health-cigna-contract-deadlock-65000-patients-risk-out-of-network-dec-1-2025/",
    sourceType: "tv",
    channel: "media",
    headline: "UNC Health-Cigna: OT copay jumps $25 to $468, doctor visit $30 to $165 if contract expires",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "CRITICAL COST DATA. Specific out-of-pocket examples: occupational therapy copay $25 to $468 (19x increase), doctor visit $30 to $165 (5.5x increase). Concrete dollar figures make abstract dispute tangible for every viewer. Most-cited statistic in the dispute.",
  },
  {
    id: 16,
    date: "2025-11-26",
    source: "CBS17",
    sourceType: "tv",
    channel: "media",
    headline: "Thanksgiving week: UNC-Cigna patients face uncertain holiday as deadline hits in days",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Thanksgiving timing amplifies emotional resonance. Families worried about healthcare access over the holidays. CBS17 third major story. Holiday news cycle has lower competition — dispute gets more airtime.",
  },
  {
    id: 17,
    date: "2025-11-27",
    source: "WRAL",
    url: "https://www.wral.com/lifestyle/health/cigna-unc-health-agreement-deadline-december-2025/",
    sourceType: "tv",
    channel: "media",
    headline: "Cigna and UNC Health struggle to reach agreement — deadline in 3 days",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "WRAL pre-deadline coverage. 'Struggle to reach agreement' framing. Balanced but urgency inherently pressures the party perceived as obstructing (Cigna, per earlier coverage).",
  },
  {
    id: 18,
    date: "2025-11-28",
    source: "Yahoo News",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health-Cigna talks fail, leaving over 65,000 patients without in-network coverage",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Yahoo News syndication gives national reach. 'Talks fail' places blame on process breakdown. Yahoo audience skews older — key health insurance consumer demographic. Thanksgiving Day publication maximizes family conversation.",
  },
  {
    id: 19,
    date: "2025-11-28",
    source: "ABC11 / WTVD (Thanksgiving)",
    sourceType: "tv",
    channel: "media",
    headline: "ABC11 Thanksgiving coverage: NC families worried about healthcare access heading into holidays",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Holiday timing amplifies emotional resonance. Third ABC11 story. Families gathering for Thanksgiving discussing healthcare anxiety. Emotional peak of pre-gap coverage.",
  },
  {
    id: 20,
    date: "2025-11-29",
    source: "Yahoo News",
    sourceType: "news",
    channel: "media",
    headline: "What NC patients need to know as UNC Health-Cigna contract expires tomorrow",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Eve-of-expiration Yahoo piece. Service journalism framing — 'what you need to know' — positions patients as victims needing guidance. Second Yahoo story shows sustained national interest.",
  },
  {
    id: 21,
    date: "2025-11-30",
    source: "WRAL",
    url: "https://www.wral.com/lifestyles/health/unc-health-cigna-contract-dispute-2025/",
    sourceType: "tv",
    channel: "media",
    headline: "Contract expires tonight: UNC Health and Cigna unable to reach agreement — gap begins Dec 1",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Deadline-day coverage. Unlike MSK/UHC (resolved at 11th hour), this dispute actually goes through to contract expiration. WRAL covers the moment of failure. Three-year contract officially expires at midnight. Gap begins Dec 1.",
  },
  {
    id: 22,
    date: "2025-12-01",
    source: "ABC11 / WTVD",
    url: "https://abc11.com/post/cigna-unc-health-patients-now-network-contract-deadline-passes/18233949/",
    sourceType: "tv",
    channel: "media",
    headline: "Cigna, UNC Health patients now out-of-network as contract deadline passes — at least 65,000 affected",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Day 1 of gap. 'Deadline passes' and 'at least 65,000' create maximum urgency. Unlike many disputes that resolve pre-deadline, patients are actually experiencing disruption. ABC11 fourth story.",
  },
  {
    id: 23,
    date: "2025-12-01",
    source: "WRAL",
    sourceType: "tv",
    channel: "media",
    headline: "Day 1: UNC Health officially out-of-network for Cigna — patients already facing higher bills",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Gap Day 1 WRAL coverage. 'Already facing higher bills' — immediate tangible harm. UNC Health sent notification letters to all 65,000 affected Cigna members. Real financial impact from day one.",
  },
  {
    id: 24,
    date: "2025-12-01",
    source: "CBS17",
    sourceType: "tv",
    channel: "media",
    headline: "UNC Health now out of network for Cigna customers — what patients need to do",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "CBS17 Gap Day 1. Service journalism — 'what patients need to do.' Continuity of care options for hospitalized, pregnant, or active-treatment patients. CBS17 fourth story. Triangle TV trifecta all covering Day 1.",
  },
  {
    id: 25,
    date: "2025-12-02",
    source: "RevQuest RCM",
    url: "https://www.revquestrcm.com/post/unc-health-cigna-contract-dispute-termination",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health-Cigna contract gap: revenue cycle implications for providers and patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Revenue cycle management trade press. Technical analysis of billing implications during gap period. Notes complexity of retroactive claims if/when resolved. RCM professional audience.",
  },
  {
    id: 26,
    date: "2025-12-03",
    source: "The Local Reporter",
    url: "https://thelocalreporter.press/cigna-unc-health-contract-dispute-continues-affecting-50000-patients/",
    sourceType: "news",
    channel: "media",
    headline: "Cigna-UNC Health contract dispute continues, affecting 50,000 patients — rural NC communities hardest hit",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Local/community journalism. Rural access angle — UNC Health operates dozens of clinics statewide, often the only major system in rural areas. Limited alternatives makes disruption more severe. 50,000 figure (vs 65,000) may reflect commercial-only count.",
  },
  {
    id: 27,
    date: "2025-12-03",
    source: "InsuraSales",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health-Cigna dispute: broker guidance for affected employer groups in North Carolina",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Insurance sales/broker trade outlet. Practical guidance for brokers managing employer accounts affected by the gap. Employer channel crossover.",
  },
  {
    id: 28,
    date: "2025-12-03",
    source: "DistilInfo",
    url: "https://distilinfo.com/healthplan/unc-health-cigna-contract-expires-2025/",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health Cigna contract expires 2025 — network gap enters third day, no resolution in sight",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Health IT/health plan trade press. 'No resolution in sight' framing extends uncertainty narrative. Each day of gap compounds PR damage to Cigna.",
  },
  {
    id: 29,
    date: "2025-12-04",
    source: "WRAL",
    url: "https://www.wral.com/lifestyles/health/unc-health-cigna-contract-expires-nc-december-2025/",
    sourceType: "tv",
    channel: "media",
    headline: "Check other health care contracts in NC — WRAL investigates pattern of provider-payor disputes",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "WRAL systemic analysis. Examines Duke/Aetna, WakeMed/UHC, and other NC disputes alongside UNC/Cigna. Pattern framing normalizes UNC's position — not uniquely aggressive. WRAL establishing itself as the beat reporter on NC healthcare disputes.",
  },
  {
    id: 30,
    date: "2025-12-05",
    source: "Avery Journal",
    url: "https://www.averyjournal.com/news/unc-health-will-no-longer-accept-three-medicare-advantage-plans-effective-jan-1/article_0cb69d9c-39a5-4f43-a429-f5bb48e3bc1e.html",
    sourceType: "news",
    channel: "media",
    headline: "Mountain communities feel impact — UNC Health will no longer accept three Medicare Advantage plans Jan 1",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Avery County community newspaper (western NC mountains). UNC Health presence in rural Appalachian communities makes dispute personal. Also covers separate Medicare Advantage plan exits (Cigna/HCSC, Humana, WellCare) effective Jan 1 — compounding disruption.",
  },
  {
    id: 31,
    date: "2025-12-05",
    source: "Watauga Democrat",
    url: "https://www.wataugademocrat.com/news/local/unc-health-will-no-longer-accept-three-medicare-advantage-plans-effective-jan-1/article_6e43258e-ffe6-4c16-8c1e-906fc1b25054.html",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health will no longer accept three Medicare Advantage plans — Boone-area patients affected",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Watauga County community newspaper. Boone/App State area. Medicare Advantage exit compounds Cigna commercial dispute. Community papers humanize dispute beyond Triangle metro.",
  },
  {
    id: 32,
    date: "2025-12-06",
    source: "Broad River Insurance",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health leaving major Medicare Advantage networks in 2026: what NC residents need to know",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Insurance advisory firm publishes detailed guide for NC Medicare beneficiaries. UNC Health drops HCSC (Cigna Medicare), Humana, and WellCare MA plans Jan 1. Recommends Chapter Medicare advisory service. Compound disruption: commercial gap AND MA exits simultaneously.",
  },
  {
    id: 33,
    date: "2025-12-08",
    source: "CBS17",
    sourceType: "tv",
    channel: "media",
    headline: "One week into gap: UNC Health and Cigna still negotiating — patients bearing the cost",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Week-mark coverage. 'Patients bearing the cost' framing. CBS17 fifth major story. Each day of gap generates new coverage cycle and compounds narrative damage to Cigna.",
  },
  {
    id: 34,
    date: "2025-12-08",
    source: "ABC11 / WTVD",
    url: "https://abc11.com/post/unc-health-cigna-insurance-negotiations-new-contract/18202154/",
    sourceType: "tv",
    channel: "media",
    headline: "UNC Health, Cigna still in negotiations over new contract — patients urged to contact Cigna for continuity of care",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "ABC11 mid-gap update. Service journalism — advises patients hospitalized, pregnant, or in active treatment to contact Cigna for continuity of care. Balanced but 'contact Cigna' framing places burden on insurer.",
  },
  {
    id: 35,
    date: "2025-12-10",
    source: "WRAL",
    sourceType: "tv",
    channel: "media",
    headline: "Signs of progress: UNC Health and Cigna reportedly nearing agreement after 10-day gap",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "WRAL reports progress in negotiations. Relief-anticipation framing. 10-day gap is already longest in recent NC provider-payor disputes.",
  },
  {
    id: 36,
    date: "2025-12-12",
    source: "WRAL",
    url: "https://www.wral.com/news/local/cigna-unc-health-agreement-end-standoff-dec-2025/",
    sourceType: "tv",
    channel: "media",
    headline: "Cigna and UNC Health reach agreement to end healthcare standoff — retroactive to Dec 1",
    frameAdoption: "unc",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "RESOLUTION. WRAL breaks the agreement news. Retroactive to Dec 1 means patients will not bear gap-period costs. Commercial plans only — Medicare Advantage dropped separately. WRAL's 7th story shows sustained dominance of this beat. 'Standoff' framing.",
  },
  {
    id: 37,
    date: "2025-12-12",
    source: "ABC11 / WTVD",
    url: "https://abc11.com/post/cigna-unc-health-sign-long-term-agreement-ending-contract-stalemate/18280747/",
    sourceType: "tv",
    channel: "media",
    headline: "Cigna, UNC Health sign long-term agreement ending contract stalemate",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "ABC11 resolution coverage. 'Long-term agreement' and 'ending stalemate' framing. Quotes Dr. Matt Ewend (UNC CCO) and James Day (Cigna HC Carolinas GM). Fifth ABC11 story.",
  },
  {
    id: 38,
    date: "2025-12-12",
    source: "CBS17",
    url: "https://www.cbs17.com/news/local-news/orange-county-news/unc-health-cigna-healthcare-reach-new-contract-agreement/",
    sourceType: "tv",
    channel: "media",
    headline: "UNC Health, Cigna Healthcare reach new contract agreement — patients can resume in-network care",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "CBS17 resolution. 'Resume in-network care' — relief framing. Notes patients who paid upfront during gap will be refunded. Sixth CBS17 story.",
  },
  {
    id: 39,
    date: "2025-12-12",
    source: "Becker's Payer Issues",
    url: "https://www.beckerspayer.com/contracting/unc-health-cigna-reach-long-term-agreement/",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health, Cigna reach 'long-term' agreement — Becker's covers resolution",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press resolution. 'Long-term' in quotes suggests skepticism. Notes deal retroactive to Dec 1. Hospital executive audience. Third Becker's story on this dispute.",
  },
  {
    id: 40,
    date: "2025-12-12",
    source: "Yahoo News",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health, Cigna agree to new contract, restoring coverage for 65,000 patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Third Yahoo piece. National syndication of resolution. 'Restoring coverage' framing implies coverage should never have been disrupted. 65,000 figure in headline for maximum impact.",
  },
  // === PROVIDER OWNED MEDIA ===
  {
    id: 41,
    date: "2025-07-02",
    source: "UNC Health Newsroom",
    sourceType: "owned",
    channel: "media",
    headline: "UNC Health seeks fair agreement with Cigna — cites reimbursement rates, prior auth burden, denial practices",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "First UNC Health official statement. 'Seeks fair agreement' implies Cigna is being unfair. Lists grievances: inadequate rates, excessive prior authorization, high denial rates, downcoded claims. Sets UNC's narrative framework for entire dispute. States UNC 'engaged with Cigna for nearly two years.'",
  },
  {
    id: 42,
    date: "2025-11-15",
    source: "UNC Health Newsroom",
    sourceType: "owned",
    channel: "media",
    headline: "UNC Health urges employers and patients to consider alternative plans during open enrollment",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Strategic open enrollment advisory. UNC Health encourages both employers and patients with Cigna coverage to consider alternative plans that include UNC Health in network for 2026. Direct market pressure on Cigna during enrollment window.",
  },
  {
    id: 43,
    date: "2025-12-01",
    source: "UNC Health Newsroom",
    url: "https://news.unchealthcare.org/2025/12/unc-health-unable-to-reach-a-new-and-fair-agreement-with-cigna",
    sourceType: "owned",
    channel: "media",
    headline: "UNC Health unable to reach a new and fair agreement with Cigna — patients advised of options",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Gap-day statement. 'Despite trying to negotiate in good faith with Cigna for months, UNC Health has been unable to reach a new and fair agreement.' Notes continuity of care options for hospitalized, pregnant, or active-treatment patients. Positions UNC as trying to help patients Cigna is harming.",
  },
  {
    id: 44,
    date: "2025-12-12",
    source: "UNC Health Newsroom",
    url: "https://news.unchealthcare.org/2025/12/unc-health-cigna-healthcare-sign-long-term-agreement-to-continue-delivering-affordable-in-network-care-for-patients/",
    sourceType: "owned",
    channel: "media",
    headline: "UNC Health signs long-term agreement with Cigna — Dr. Matt Ewend: 'eliminate obstacles to care'",
    frameAdoption: "unc",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution press release. Dr. Matt Ewend (Chief Clinical Officer): 'Our patients will not face increased costs and the stress of going out of network or seeking new providers for their care. We look forward to working with Cigna Healthcare in the coming years to improve access, reduce costs and eliminate obstacles to care.' 'Eliminate obstacles' implies Cigna was the obstacle.",
  },
  // === CIGNA OWNED MEDIA ===
  {
    id: 45,
    date: "2025-07-15",
    source: "Cigna Healthcare (public statement)",
    sourceType: "owned",
    channel: "media",
    headline: "Cigna: UNC Health demanding rate increases 'well above market levels' — offered contract extension",
    frameAdoption: "cigna",
    sentiment: "negative_unc",
    patientStory: false,
    blameDirection: "unc",
    reachEstimate: "medium",
    notes: "Cigna's primary public framing. 'Our goal is to keep UNC Health in network, and we have offered to extend our current contract.' Positions Cigna as reasonable party offering stability. 'Well above market levels' is Cigna's stickiest talking point. No patient voices.",
  },
  {
    id: 46,
    date: "2025-12-12",
    source: "Cigna Healthcare (resolution statement)",
    sourceType: "owned",
    channel: "media",
    headline: "James Day, Cigna HC Carolinas GM: 'pleased to have reached a deal' — affordable quality care commitment",
    frameAdoption: "cigna",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "James Day (General Manager, Cigna Healthcare Carolinas): 'Cigna Healthcare is pleased to have reached a deal with UNC Health, allowing us to continue in-network coverage for the customers we jointly serve.' Conciliatory tone. 'Pleased' suggests relief — Cigna felt the pressure.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 47,
    date: "2025-07-10",
    source: "UNC Health (Facebook)",
    sourceType: "social",
    channel: "social",
    headline: "UNC Health Facebook post: 'We are committed to reaching a fair agreement with Cigna for our patients'",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Official UNC Health Facebook. 'Fair agreement' and 'for our patients' framing positions UNC as patient advocate vs Cigna. Comment sections filled with affected patients sharing stories. Facebook reaches older NC demographic.",
  },
  {
    id: 48,
    date: "2025-09-15",
    source: "UNC Health (LinkedIn)",
    sourceType: "social",
    channel: "social",
    headline: "UNC Health LinkedIn update on Cigna negotiations — professional audience, employer decision-makers",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "LinkedIn reaches NC employer/HR decision-makers. Professional tone but same 'fair agreement' framing. Employer audience is critical — they choose Cigna or alternatives for employee benefits.",
  },
  {
    id: 49,
    date: "2025-11-26",
    source: "NC Hospital Association (Facebook)",
    sourceType: "social",
    channel: "social",
    headline: "NC Hospital Association shares UNC Health-Cigna update — industry solidarity signal",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "NCHA amplification. Steve Lawler's 'Be a good partner' position directed at Cigna. Industry association backing gives UNC institutional credibility. Reaches broader NC hospital community audience.",
  },
  {
    id: 50,
    date: "2025-11-30",
    source: "ABC11 EyewitnessNews (X/Twitter)",
    sourceType: "social",
    channel: "social",
    headline: "ABC11 tweets: 'UNC Health, Cigna still in negotiations over new contract' — social amplification of TV coverage",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "TV station social amplification. ABC11's tweet extends reach beyond broadcast audience. Deadline-day timing maximizes engagement. Social sharing of local TV news amplifies beyond DMA.",
  },
  {
    id: 51,
    date: "2025-12-04",
    source: "Social media (NC patient community)",
    sourceType: "social",
    channel: "social",
    headline: "NC patient communities share UNC-Cigna disruption stories — fear, frustration, calls to switch insurers",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Organic social sharing during gap period. Patient communities on Facebook groups, Reddit r/NorthCarolina, Nextdoor. 'Switch insurers' sentiment creates direct market pressure on Cigna from consumer base.",
  },
  {
    id: 52,
    date: "2025-12-06",
    source: "Social media (employer/HR forums)",
    sourceType: "social",
    channel: "social",
    headline: "NC employer and HR professionals discuss Cigna alternatives in wake of UNC Health gap",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Employer decision-maker social channels. HR professionals and benefits managers sharing concerns about Cigna network reliability. Open enrollment timing (Q4) amplifies switching risk for Cigna.",
  },
  {
    id: 53,
    date: "2025-12-08",
    source: "UNC Health (Facebook — gap update)",
    sourceType: "social",
    channel: "social",
    headline: "UNC Health Facebook: 'We continue to negotiate in good faith — our patients deserve access to their doctors'",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Mid-gap social update. 'Good faith' and 'deserve access' framing. High comment engagement from affected patients. UNC maintains patient-advocate positioning throughout 12-day gap.",
  },
  {
    id: 54,
    date: "2025-12-12",
    source: "UNC Health (Facebook — resolution)",
    sourceType: "social",
    channel: "social",
    headline: "UNC Health announces agreement on Facebook: 'signed an agreement with Cigna Healthcare'",
    frameAdoption: "unc",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution announcement on social. Relief framing. High engagement expected given anxiety in previous posts' comment sections. UNC claims agency in resolution.",
  },
  {
    id: 55,
    date: "2025-12-12",
    source: "UNC Health (LinkedIn — resolution)",
    sourceType: "social",
    channel: "social",
    headline: "UNC Health LinkedIn resolution post — professional audience, employer reassurance",
    frameAdoption: "unc",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "LinkedIn resolution post reaches employer/HR audience. Reassurance for employer clients that network access is restored. Professional tone but same UNC-as-advocate framing.",
  },
  {
    id: 56,
    date: "2025-12-12",
    source: "NC Hospital Association (Facebook — resolution)",
    sourceType: "social",
    channel: "social",
    headline: "NCHA shares resolution news — industry solidarity maintained through to resolution",
    frameAdoption: "unc",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "NCHA amplifies resolution. Industry association maintained support throughout 12-day gap. Signals to other NC insurers that hospital association will back providers in disputes.",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 57,
    date: "2025-10-05",
    source: "Town of Apex — Mayor Jacques Gilbert",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Apex Mayor Gilbert: 'extremely concerned' — town exploring 'everything on the table' including switching from Cigna",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "CRITICAL EMPLOYER DEFECTION SIGNAL. Town of Apex (fastest-growing municipality in NC) publicly considers dropping Cigna. Mayor Gilbert: 'I am extremely concerned. Anything that impacts our staff and their families.' 850+ employees affected. Municipal government action creates political pressure Cigna cannot easily counter.",
  },
  {
    id: 58,
    date: "2025-10-05",
    source: "Town of Apex — Manager Randy Vosburg",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Apex Town Manager Vosburg: town in 'near constant contact' with both parties, leveraging municipal position",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Town Manager operational perspective. Vosburg says town sent 'texts, emails and phone calls to both UNC and Cigna, had a meeting with Cigna, and made them very aware of the town's position.' Active municipal lobbying on behalf of employees.",
  },
  {
    id: 59,
    date: "2025-11-10",
    source: "NC Hospital Association — Steve Lawler",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "NCHA President Steve Lawler to Cigna: 'Be a good partner' — industry association backs UNC Health",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "NC Hospital Association president publicly sides with UNC Health. Steve Lawler (former ECU Health CEO) 'Be a good partner' is polished but pointed rebuke of Cigna's negotiating posture. Industry solidarity strengthens UNC's position.",
  },
  {
    id: 60,
    date: "2025-11-18",
    source: "Governor Josh Stein (public acknowledgment)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Gov. Stein: 'I can imagine a scenario where the state would need to step in' — stops short of intervention",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "GOVERNOR POSTURE. Stein: 'I can imagine a scenario where the consequences [are] really grave and impacts a large number of people where the state would need to step in or urge... to knock heads, but these are private parties that need to do what they need to do.' Implied threat without action. NC lacks equivalent of NY 60-day cooling-off rule.",
  },
  {
    id: 61,
    date: "2025-11-20",
    source: "NC Department of Insurance",
    sourceType: "news",
    channel: "stakeholder",
    headline: "NC DOI establishes complaint pathway for patients affected by UNC Health-Cigna dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Regulatory response. NC DOI creates formal complaint mechanism. While not direct intervention, complaint volume becomes data point that pressures Cigna. Regulatory attention is inherently negative for insurer.",
  },
  {
    id: 62,
    date: "2025-11-25",
    source: "Duke/Aetna, WakeMed/UHC, UNC/UHC (2024) precedents",
    sourceType: "news",
    channel: "stakeholder",
    headline: "NC pattern: Duke/Aetna, WakeMed/UHC, UNC/UHC (2024) disputes establish recurring provider-payor tension",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "PATTERN EVIDENCE. Multiple recent NC provider-payor disputes. UNC signed long-term deal with UHC in March 2024 after similar brinksmanship. UNC spokesperson at that time: UNC 'has not taken an action like this in more than a decade.' Systemic framing normalizes UNC's position.",
  },
  {
    id: 63,
    date: "2025-12-01",
    source: "Cigna continuity of care provision",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Cigna offers limited continuity of care — hospitalized, pregnant, or active-treatment patients may qualify",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "REGULATORY GAP. Cigna's continuity of care covers hospitalized, pregnant, or active-treatment patients for limited time — but patients must contact Cigna directly. No automatic protection. Burden on patient to navigate bureaucracy during health crisis.",
  },
  {
    id: 64,
    date: "2025-12-12",
    source: "Dr. Matt Ewend, Chief Clinical Officer, UNC Health",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Dr. Ewend: 'We look forward to working with Cigna to improve access, reduce costs and eliminate obstacles to care'",
    frameAdoption: "unc",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution statement from UNC's top clinical leader. 'Eliminate obstacles to care' implies Cigna's prior auth and denial practices were the obstacles. Forward-looking tone but embedded critique. CCO title gives clinical credibility.",
  },
  {
    id: 65,
    date: "2025-12-12",
    source: "James Day, GM Cigna Healthcare Carolinas",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Cigna's James Day: 'pleased to have reached a deal' — affordable quality care for North Carolinians",
    frameAdoption: "cigna",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Cigna resolution statement. Conciliatory. 'Pleased to have reached a deal' suggests relief — Cigna felt the 12-day gap pressure. 'Continue to provide affordable, quality care' reclaims affordability framing. Regional GM rather than national exec suggests controlled response.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 66,
    date: "2025-10-15",
    source: "Apex Town Council (employer action)",
    sourceType: "owned",
    channel: "employer",
    headline: "Town of Apex sends formal communications to both Cigna and UNC Health — leverages municipal purchasing power",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "CRITICAL EMPLOYER ACTION. Town Manager Vosburg confirmed the town sent 'texts, emails and phone calls to both UNC and Cigna, had a meeting with Cigna, and made them very aware of the town's position.' Municipal employer directly lobbying insurer is rare and signals serious defection risk.",
  },
  {
    id: 67,
    date: "2025-11-01",
    source: "UNC Health (employer advisory)",
    sourceType: "owned",
    channel: "employer",
    headline: "UNC Health urges NC employers to consider alternative insurance plans during open enrollment",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "STRATEGIC EMPLOYER PRESSURE. UNC Health directly targets employer decision-makers during Cigna open enrollment (Nov 1-Dec 15). Suggests employers switch to plans that include UNC Health for 2026. Market pressure tactic — threatens Cigna's NC employer base.",
  },
  {
    id: 68,
    date: "2025-12-03",
    source: "InsuraSales (broker advisory)",
    sourceType: "news",
    channel: "employer",
    headline: "InsuraSales distributes broker guidance for employer groups affected by UNC-Cigna gap",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Insurance broker trade channel. Each advisory reinforces Cigna's network reliability problem to the people who make insurance purchasing decisions. Gap timing during open enrollment maximizes employer switching risk.",
  },
  {
    id: 69,
    date: "2025-12-08",
    source: "NC employer open enrollment impact",
    sourceType: "news",
    channel: "employer",
    headline: "Open enrollment closes Dec 15 — NC employers face Cigna decision with UNC Health still out-of-network",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "STRUCTURAL TIMING. Cigna open enrollment (Nov 1-Dec 15) overlaps perfectly with the gap period. Employers making 2026 insurance decisions DURING active network disruption. Worst possible timing for Cigna. Resolution on Dec 12 came just 3 days before enrollment closed.",
  },
];

const LABELS = {
  frameAdoption: { unc: "UNC Frame", cigna: "Cigna Frame", balanced: "Balanced" },
  sentiment: {
    negative_cigna: "Anti-Cigna",
    negative_unc: "Anti-UNC",
    neutral: "Neutral",
    positive_cigna: "Pro-Cigna",
    positive_unc: "Pro-UNC",
  },
  blameDirection: { cigna: "Blames Cigna", unc: "Blames UNC", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National/major syndication (1.5)
  "Yahoo News": 1.5,
  // Tier 2 — Regional authority (1.2)
  "WRAL": 1.2, "ABC11 / WTVD": 1.2, "CBS17": 1.2, "Axios Raleigh": 1.2,
  "ABC11 / WTVD (Thanksgiving)": 1.2, "ABC11 EyewitnessNews (X/Twitter)": 1.2,
  // Tier 3 — Trade/niche (1.0)
  "Becker's Hospital Review": 1.0, "Becker's Payer Issues": 1.0, "HealthLeaders": 1.0,
  "WBT Radio Charlotte": 1.0, "RevQuest RCM": 1.0, "InsuraSales": 1.0, "DistilInfo": 1.0,
  "The Local Reporter": 1.0, "Broad River Insurance": 1.0,
  // Tier 3.5 — Community papers (0.8)
  "Avery Journal": 0.8, "Watauga Democrat": 0.8,
  // Tier 4 — Organic social (0.7)
  "Social media (NC patient community)": 0.7,
  "Social media (employer/HR forums)": 0.7,
  // Tier 5 — Comment sections (0.4)
  // Tier 6 — Owned/party media (0.3)
  "UNC Health Newsroom": 0.3,
  "UNC Health (Facebook)": 0.3, "UNC Health (LinkedIn)": 0.3,
  "UNC Health (Facebook — gap update)": 0.3, "UNC Health (Facebook — resolution)": 0.3,
  "UNC Health (LinkedIn — resolution)": 0.3,
  "UNC Health (employer advisory)": 0.3,
  "NC Hospital Association (Facebook)": 0.3, "NC Hospital Association (Facebook — resolution)": 0.3,
  "Cigna Healthcare (public statement)": 0.3, "Cigna Healthcare (resolution statement)": 0.3,
  "Apex Town Council (employer action)": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "Town of Apex — Mayor Jacques Gilbert": 1.3, "Town of Apex — Manager Randy Vosburg": 1.3,
  "NC Hospital Association — Steve Lawler": 1.3,
  "Governor Josh Stein (public acknowledgment)": 1.3, "NC Department of Insurance": 1.3,
  "Duke/Aetna, WakeMed/UHC, UNC/UHC (2024) precedents": 1.3,
  "Cigna continuity of care provision": 1.3,
  "Dr. Matt Ewend, Chief Clinical Officer, UNC Health": 1.3,
  "James Day, GM Cigna Healthcare Carolinas": 1.3,
  // Tier 8 — Employer/Benefits (1.5x trade, 1.0x broker)
  "NC employer open enrollment impact": 1.5,
  "InsuraSales (broker advisory)": 1.0,
};

const SEARCH_TRENDS = [
  { week: "2025-07-07", interest: 15 }, { week: "2025-07-14", interest: 10 },
  { week: "2025-07-21", interest: 8 }, { week: "2025-07-28", interest: 6 },
  { week: "2025-08-04", interest: 5 }, { week: "2025-08-18", interest: 5 },
  { week: "2025-09-01", interest: 4 }, { week: "2025-09-15", interest: 8 },
  { week: "2025-10-06", interest: 12 }, { week: "2025-10-20", interest: 10 },
  { week: "2025-11-03", interest: 22 }, { week: "2025-11-10", interest: 30 },
  { week: "2025-11-17", interest: 45 }, { week: "2025-11-24", interest: 78 },
  { week: "2025-12-01", interest: 100 }, { week: "2025-12-08", interest: 85 },
  { week: "2025-12-15", interest: 90 }, { week: "2025-12-22", interest: 12 },
  { week: "2025-12-29", interest: 5 },
];

export default {
  active: false,
  // Identity
  providerKey: "unc",
  payorKey: "cigna",
  providerName: "UNC Health",
  payorName: "Cigna",
  providerShort: "UNC",
  payorShort: "Cigna",
  navShort: "UNC v. Cigna",
  title: "UNC Health vs Cigna",
  subtitle: "Contract dispute \u00b7 Resolved December 12, 2025",
  gradientId: "unccigna",

  // Dates
  monitorStart: "July 1, 2025",
  monitorEnd: "December 31, 2025",
  disputePublicDate: "2025-07-02",

  // Colors
  colors: {
    providerColor: "#4B9CD3",
    payorColor: "#E87722",
    neutral: "#64748B",
    accent: "#4B9CD3",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#4B9CD3", "#7A8FA8", "#E87722"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"UNC Health Cigna" \u00b7 weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.72,
    nationalMedian: 1.0,
    networkComplaints: 1243,
    priorYearComplaints: 891,
    regulatorAction: "NC Department of Insurance established complaint pathway for affected patients. Governor Stein acknowledged dispute publicly but stopped short of formal intervention, stating 'these are private parties that need to do what they need to do.' NC lacks equivalent of NY 60-day cooling-off rule — no automatic transitional coverage.",
    signalRead: "Cigna's complaint index is elevated (1.72x median) driven by prior auth burden and network disruption in NC. The 40% increase in network complaints reflects growing provider dissatisfaction with Cigna's denial practices and downcoding. The 12-day actual coverage gap is rare — most disputes resolve pre-deadline — and generated sustained media cycles that compounded Cigna's reputational damage in the state.",
  },

  talkingPoints: {
    provider: [
      { name: "65K patients at risk", keywords: ["65,000", "60,000", "65K", "60K", "patients at risk", "lose.*access", "out.?of.?network"] },
      { name: "Patient harm stories", keywords: ["pederson", "stanley", "baby", "meningitis", "becky pezzoni", "cancer survivor", "jon markle", "diabetic", "zack roscoe"] },
      { name: "Prior auth / 30% denial rate", keywords: ["prior auth", "30%.*denial", "denial rate", "downcod", "denied.*coverage", "delayed payment"] },
      { name: "Copay shock ($25 to $468)", keywords: ["\\$25.*\\$468", "\\$30.*\\$165", "copay.*jump", "ot copay", "out-of-pocket"] },
      { name: "12-day actual gap", keywords: ["12.?day", "coverage gap", "dec 1.*dec 12", "actual.*gap", "actual.*disruption"] },
      { name: "Rural NC / mountain communities", keywords: ["rural", "avery", "watauga", "mountain", "boone", "no alternative", "only.*system"] },
      { name: "Open enrollment pressure", keywords: ["open enrollment", "consider alternative", "switching.*cigna", "enrollment.*close"] },
      { name: "Apex municipal defection", keywords: ["apex", "mayor gilbert", "town.*apex", "850 employee", "vosburg", "municipal"] },
    ],
    payor: [
      { name: "Above market rate demands", keywords: ["above market", "well above", "market level", "rate demand"] },
      { name: "Affordability for employers", keywords: ["affordab", "employer", "families", "cost.*increase", "premium"] },
      { name: "Offered contract extension", keywords: ["offered.*extension", "contract extension", "extension.*offered"] },
      { name: "Cigna protecting access", keywords: ["quality.*affordable", "affordable.*care", "access.*care", "committed.*access"] },
      { name: "NC pattern / UNC serial disputes", keywords: ["duke.*aetna", "wakemed", "nc pattern", "recurring.*dispute", "serial"] },
      { name: "Continuity of care offered", keywords: ["continuity of care", "hospitalized", "active.?treatment", "pregnant"] },
    ],
  },

  // Executive summary
  executiveSummary: {
    statement: "The dispute resulted in a 12-day actual coverage gap (Dec 1-12) affecting 65,000 Cigna commercial members — unlike most provider-payor disputes which resolve at the deadline. Retroactive coverage to Dec 1 mitigated patient financial harm, but the gap itself was a significant PR defeat for Cigna in North Carolina.",
    keyMessages: [
      "UNC's operational grievances (prior auth escalation beyond MRIs to routine labs/meds/visits, 30% denial rate, downcoded claims, delayed payments) resonated more with media than Cigna's 'above market rates' framing.",
      "Concrete patient cost examples ($25 to $468 OT copay, $30 to $165 doctor visit) made abstract dispute tangible, shareable, and devastating for Cigna's 'affordability' narrative.",
      "The actual 12-day gap is highly unusual — each day generated a new coverage cycle compounding Cigna's narrative damage. Resolution on Dec 12 came just 3 days before Cigna open enrollment closed.",
      "Municipal employer defection threat (Town of Apex, 850 employees, Mayor Gilbert 'extremely concerned') created political and market pressure that went beyond standard corporate negotiations.",
    ],
    marcomm: [
      "<strong>Sick babies and cancer survivors are unbeatable narratives.</strong> Patric Pederson's 11-month-old Stanley (meningitis, RSV, strokes) and Becky Pezzoni's cancer survival story gave UNC narrative advantages Cigna could never counter with equivalent patient advocates.",
      "<strong>The 12-day gap was Cigna's worst-case outcome.</strong> Every day patients were actually out-of-network generated new media cycles, social media outrage, and employer anxiety. Resolution at deadline is bad; actual disruption is catastrophic for insurer reputation. The gap coincided perfectly with open enrollment.",
      "<strong>Rural NC coverage extended narrative statewide.</strong> Community papers in Avery and Watauga counties humanized the dispute for rural Appalachian audiences where UNC Health is often the only major system. Cigna's 'market rate' argument rings hollow when there is no alternative market.",
      "<strong>Open enrollment timing was strategically devastating for Cigna.</strong> The Nov 30 contract expiration landed during Cigna's open enrollment window (Nov 1-Dec 15). UNC Health explicitly urged employers and patients to consider alternatives. Resolution on Dec 12 came just before enrollment closed — but damage to Cigna's 2026 enrollment was already done.",
    ],
  },
  channelTakeaways: {
    media: [
      "WRAL dominated with 7+ stories including the most impactful patient narratives (Pederson baby, Pezzoni cancer survivor, $25-to-$468 copay jump).",
      "Triangle TV trifecta (WRAL, ABC11/WTVD, CBS17) provided saturating local coverage — every major station covered 5+ stories across the dispute lifecycle.",
      "Community papers (Avery Journal, Watauga Democrat) extended geographic reach to rural NC where UNC Health is essential infrastructure with no alternatives.",
      "Trade press (Becker's, HealthLeaders) gave UNC's operational grievances (denial rates, downcoding, prior auth expansion) equal or greater weight than Cigna's rate claims.",
      "Yahoo News syndication gave three stories national reach — unusual for a regional dispute, reflecting the 65,000 patient scale.",
    ],
    social: [
      "UNC Health maintained consistent 'fair agreement' and 'patient advocate' framing across Facebook and LinkedIn throughout the full dispute timeline.",
      "NC Hospital Association amplified UNC's position through social channels — Steve Lawler's 'Be a good partner' became an institutional rallying cry.",
      "Organic patient community posts during 12-day gap generated employer-switching sentiment that directly threatened Cigna's NC market share.",
      "Open enrollment timing (Q4) amplified social discussion among HR professionals considering Cigna alternatives for 2026 plans.",
    ],
    stakeholder: [
      "Town of Apex's public consideration of dropping Cigna (850 employees, Mayor Gilbert, Manager Vosburg 'near constant contact') was the most impactful employer-stakeholder action.",
      "NCHA President Steve Lawler's public backing gave UNC institutional credibility from the state hospital association.",
      "Governor Stein's 'private parties' comment was strategically neutral — did not back Cigna, kept implied threat of state intervention in reserve.",
      "NC DOI complaint pathway created regulatory documentation of patient harm — data that pressures Cigna in future NC rate negotiations.",
      "Pattern evidence (Duke/Aetna, WakeMed/UHC, UNC/UHC 2024) framed the dispute as systemic NC trend, not UNC-specific aggression.",
    ],
    employer: [
      "Municipal employer defection threat (Apex) created concrete market risk for Cigna beyond reputational damage — government employer switching sends signal to private employers.",
      "UNC Health's direct appeal to employers during open enrollment ('consider alternative plans') was an aggressive market pressure tactic rarely seen from providers.",
      "Broker channels (InsuraSales) distributed gap guidance to employer accounts — each advisory reinforced Cigna's network reliability problem.",
      "Resolution on Dec 12 (3 days before Cigna open enrollment close) likely prevented worst-case employer defection, but damage to Cigna's 2026 enrollment pipeline was already substantial.",
    ],
  },
  arguments: {
    payor: [
      { phase: "Early (Jul 2025)", points: [
        "Cigna countered that UNC Health demands were '<strong>well above market levels</strong>'",
        "Positioned dispute as a rate issue — UNC was asking for too much money",
        "Corporate statements framed Cigna as protecting affordability for employers and families",
      ] },
      { phase: "Mid-Dispute (Oct–Nov 2025)", points: [
        "Maintained 'above market' framing as UNC Health publicized operational grievances about Cigna practices",
        "Could not effectively counter UNC's <strong>30% denial rate</strong> and downcoded claims data",
        "Cigna's pattern of national disputes (Hartford, Hackensack Meridian, Tenet, Baptist, Bon Secours, Piedmont) undermined 'UNC is uniquely unreasonable' framing",
      ] },
      { phase: "Resolution (Dec 2025)", points: [
        "Agreement reached December 12 after a <strong>12-day actual out-of-network gap</strong> (Dec 1–12)",
        "Resolution came just 3 days before Cigna open enrollment close — preventing worst-case employer defections",
      ] },
    ],
    provider: [
      { phase: "Early (Jul 2025)", points: [
        "UNC Health spokesperson: system 'not satisfied with Cigna's reimbursement rates, its <strong>use of prior authorization and how often the insurer is denying coverage</strong>'",
        "Framed dispute around three grievances: inadequate rates, excessive prior authorization, and <strong>30% denial rate with downcoded claims</strong>",
        "65,000 affected members figure became the standard across all coverage",
      ] },
      { phase: "Mid-Dispute (Sep–Nov 2025)", points: [
        "Patient stories built sustained pressure: Patric Pederson's 11-month-old son Stanley (meningitis, RSV, strokes) — '<strong>incredible stress</strong>'; Becky Pezzoni (cancer survivor): '<strong>the patient got lost in all of this</strong>'; Jon Markle (~80, diabetic): 'I am on a very fixed income'",
        "Published devastating cost data: OT copay <strong>$25 to $468</strong> (19x), doctor visit <strong>$30 to $165</strong> (5.5x) if contract expired",
        "Encouraged employers to consider alternative plans during open enrollment — <strong>aggressive market pressure tactic</strong>; Town of Apex (850 employees) publicly pressured Cigna",
      ] },
      { phase: "Resolution (Dec 2025)", points: [
        "Agreement reached Dec 12 after 12-day gap with real patient disruption — unlike most disputes that resolve pre-deadline",
        "NCHA President Steve Lawler gave UNC institutional backing from the state hospital association",
      ] },
    ],
  },
  timeline: [
    { date: "2025-07-02", type: "newsBreak", label: "News breaks publicly" },
    { date: "2025-11-30", type: "termination", label: "Contract terminates" },
    { date: "2025-12-12", type: "agreement", label: "Agreement reached" },
  ],
};
