// UNC Health vs Cigna — PR War Room Config
// Dispute period: July–December 2025. 12-day gap Dec 1-12. Resolved December 12, 2025.

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2025-07-02",
    source: "Axios Raleigh",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health, Cigna contract dispute goes public — patients warned of potential out-of-network status",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "First major public reporting of the dispute. Axios Raleigh breaks news that UNC Health and Cigna have failed to reach agreement. ~65,000 Cigna commercial members in NC potentially affected. Sets the narrative early with patient-impact framing.",
  },
  {
    id: 2,
    date: "2025-07-15",
    source: "WRAL",
    sourceType: "tv",
    channel: "media",
    headline: "UNC Health warns patients about Cigna contract dispute — 65,000 members could lose in-network access",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "WRAL is the dominant Triangle TV station. First of 7+ WRAL stories. UNC Health frames dispute around patient access. 65,000 member figure becomes standard across all coverage.",
  },
  {
    id: 3,
    date: "2025-09-18",
    source: "WRAL",
    sourceType: "tv",
    channel: "media",
    headline: "Father of sick baby caught in UNC Health-Cigna dispute — Patric Pederson: 'incredible stress'",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "CRITICAL PATIENT STORY. Patric Pederson's 11-month-old son Stanley survived meningitis, RSV, and strokes at UNC Hospitals. 'Incredible stress' of potentially losing access to Stanley's care team. Sick baby story is maximally sympathetic — impossible for Cigna to counter.",
  },
  {
    id: 4,
    date: "2025-10-08",
    source: "WRAL",
    sourceType: "tv",
    channel: "media",
    headline: "Town of Apex weighs switching from Cigna over UNC Health dispute — 850 employees affected",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Municipal government story. Town of Apex (Mayor Jacques Gilbert, Manager Randy Vosburg) considers 'everything on the table' including switching away from Cigna for 850 town employees. Concrete employer defection threat amplifies pressure on Cigna.",
  },
  {
    id: 5,
    date: "2025-10-22",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health-Cigna contract dispute: what to know — Cigna claims 40% rate increase demanded",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press roundup. Cigna's claim that UNC demanded a 40% rate increase over 3 years (revised from earlier 32% claim). UNC counters with grievances about inadequate rates and excessive prior auth. Hospital executive audience.",
  },
  {
    id: 6,
    date: "2025-11-05",
    source: "WRAL",
    sourceType: "tv",
    channel: "media",
    headline: "Cancer survivor Becky Pezzoni fears losing UNC Rex access — employer only offers Cigna, 4 prescriptions at risk",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "CRITICAL PATIENT STORY. Becky Pezzoni: cancer survivor, credits UNC Rex with saving her life. Employer only offers Cigna — no choice. Four prescriptions at risk. 'The patient got lost in this.' Trapped-patient narrative is devastating for Cigna.",
  },
  {
    id: 7,
    date: "2025-11-12",
    source: "ABC11 / WTVD",
    sourceType: "tv",
    channel: "media",
    headline: "Diabetic man nearly died from coma, now fears losing UNC doctors — Jon Markle on fixed income",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Jon Markle (~80, Raleigh): diabetic, nearly died from coma, fixed income. Cannot afford out-of-network costs. Elderly patient on fixed income is deeply sympathetic. ABC11/WTVD is second-largest Triangle TV station.",
  },
  {
    id: 8,
    date: "2025-11-15",
    source: "CBS17",
    sourceType: "tv",
    channel: "media",
    headline: "UNC Health-Cigna deadline looms — patients scramble for alternatives as Nov 30 approaches",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "CBS17 deadline preview. Urgency framing as Nov 30 contract expiration approaches. Patient scramble angle places blame on the disruption itself.",
  },
  {
    id: 9,
    date: "2025-11-19",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "Cigna accuses UNC Health of demanding 40% rate hike — UNC cites 30% denial rate, downcoded claims",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Second Becker's piece. Both sides' claims presented. Cigna's 40% hike allegation vs UNC's grievances: inadequate rates, excessive prior authorization, 30% denial rate for 'medical necessity,' downcoded claims. Trade press gives UNC's operational grievances equal weight.",
  },
  {
    id: 10,
    date: "2025-11-20",
    source: "HealthLeaders",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health-Cigna standoff highlights prior auth and denial rate tensions in provider-payor disputes",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Trade press. Focuses on UNC's operational grievances — prior auth burden and 30% denial rate. Systemic framing positions Cigna's administrative practices as root cause. Healthcare executive audience.",
  },
  {
    id: 11,
    date: "2025-11-22",
    source: "ABC11 / WTVD",
    sourceType: "tv",
    channel: "media",
    headline: "Zack Roscoe: 'richest country in the world and this is how it impacts the people'",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Zack Roscoe patient story. Populist framing — 'richest country in the world' resonates broadly. Connects individual dispute to systemic healthcare frustration. Strong soundbite for social sharing.",
  },
  {
    id: 12,
    date: "2025-11-25",
    source: "WRAL",
    sourceType: "tv",
    channel: "media",
    headline: "UNC Health-Cigna contract expires in days — patient cost examples: OT copay jumps $25 to $468",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "CRITICAL COST DATA. Specific out-of-pocket examples: occupational therapy copay $25 to $468 (19x increase), doctor visit $30 to $165 (5.5x). Concrete dollar figures make abstract dispute tangible for every viewer.",
  },
  {
    id: 13,
    date: "2025-11-26",
    source: "CBS17",
    sourceType: "tv",
    channel: "media",
    headline: "Thanksgiving week coverage: UNC-Cigna patients face uncertain holiday as deadline hits",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Thanksgiving timing amplifies emotional resonance. Families worried about healthcare access over the holidays. CBS17 second major story.",
  },
  {
    id: 14,
    date: "2025-11-27",
    source: "WBT Radio",
    sourceType: "radio",
    channel: "media",
    headline: "WBT Radio Charlotte covers UNC Health-Cigna dispute — statewide reach beyond Triangle",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Charlotte radio extends coverage beyond Triangle market. UNC Health has clinics statewide including western NC. WBT is legacy AM talk station with older demographic — key insurance consumer audience.",
  },
  {
    id: 15,
    date: "2025-11-28",
    source: "Yahoo News",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health, Cigna contract dispute could affect thousands in North Carolina",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Yahoo News syndication gives national reach. 'Could affect thousands' understatement of 65,000 figure. Yahoo audience skews older — key health insurance consumer demographic.",
  },
  {
    id: 16,
    date: "2025-11-29",
    source: "Yahoo News",
    sourceType: "news",
    channel: "media",
    headline: "What NC patients need to know as UNC Health-Cigna contract expires tomorrow",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Eve-of-expiration Yahoo piece. Service journalism framing — 'what you need to know' — positions patients as victims needing guidance. Second Yahoo story shows sustained national interest.",
  },
  {
    id: 17,
    date: "2025-11-30",
    source: "WRAL",
    sourceType: "tv",
    channel: "media",
    headline: "Contract expires tonight: UNC Health and Cigna unable to reach agreement — gap begins Dec 1",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Deadline-day coverage. Unlike MSK/UHC (resolved at 11th hour), this dispute actually went through to contract expiration. WRAL covers the moment of failure. Gap officially begins Dec 1.",
  },
  {
    id: 18,
    date: "2025-12-01",
    source: "ABC11 / WTVD",
    sourceType: "tv",
    channel: "media",
    headline: "UNC Health now out-of-network for Cigna patients — 65,000 members face higher costs starting today",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Day 1 of gap. 'Starting today' creates maximum urgency. 65,000 figure repeated. Unlike many disputes that resolve pre-deadline, patients are actually experiencing disruption.",
  },
  {
    id: 19,
    date: "2025-12-02",
    source: "RevQuest RCM",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health-Cigna contract gap: revenue cycle implications for providers and patients",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Revenue cycle management trade press. Technical analysis of billing implications during gap period. Notes complexity of retroactive claims if/when resolved. RCM professional audience.",
  },
  {
    id: 20,
    date: "2025-12-03",
    source: "InsuraSales",
    sourceType: "news",
    channel: "media",
    headline: "Cigna-UNC Health dispute: broker guidance for affected employer groups in North Carolina",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Insurance sales/broker trade outlet. Practical guidance for brokers managing employer accounts affected by the gap. Employer channel crossover.",
  },
  {
    id: 21,
    date: "2025-12-03",
    source: "DistilInfo",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health network gap with Cigna enters third day — no resolution in sight",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Health IT trade press. 'No resolution in sight' framing extends uncertainty narrative. Each day of gap compounds PR damage to Cigna.",
  },
  {
    id: 22,
    date: "2025-12-04",
    source: "The Local Reporter",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health-Cigna dispute hits rural NC communities hardest — limited provider alternatives",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Local/community journalism. Rural access angle — UNC Health operates dozens of clinics statewide, often the only major system in rural areas. Limited alternatives makes disruption more severe for rural patients.",
  },
  {
    id: 23,
    date: "2025-12-05",
    source: "Avery Journal",
    sourceType: "news",
    channel: "media",
    headline: "Mountain communities feel impact of UNC Health-Cigna dispute — patients face long drives for care",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Avery County community newspaper (western NC mountains). UNC Health presence in rural Appalachian communities makes dispute feel personal. Limited healthcare infrastructure means patients can't easily switch providers.",
  },
  {
    id: 24,
    date: "2025-12-05",
    source: "Watauga Democrat",
    sourceType: "news",
    channel: "media",
    headline: "Watauga County residents caught in UNC Health-Cigna crossfire — Boone-area patients affected",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "low",
    notes: "Watauga County community newspaper. Boone/App State area. Community papers humanize dispute beyond Triangle metro. Rural NC coverage extends geographic narrative reach.",
  },
  {
    id: 25,
    date: "2025-12-06",
    source: "RevQuest RCM",
    sourceType: "news",
    channel: "media",
    headline: "UNC Health-Cigna gap week one: claims processing, patient billing, and retroactivity questions",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Second RevQuest piece. Technical focus on claims processing during gap. Key question: will resolution include retroactive coverage back to Dec 1? (Answer: yes, it did.) RCM audience tracking operational impact.",
  },
  {
    id: 26,
    date: "2025-12-08",
    source: "CBS17",
    sourceType: "tv",
    channel: "media",
    headline: "One week into gap: UNC Health and Cigna still negotiating — patients bearing the cost",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Week-mark coverage. 'Patients bearing the cost' framing. CBS17 third major story. Each day of gap generates new coverage cycle and compounds narrative damage.",
  },
  {
    id: 27,
    date: "2025-12-10",
    source: "WRAL",
    sourceType: "tv",
    channel: "media",
    headline: "Signs of progress: UNC Health and Cigna reportedly nearing agreement after 10-day gap",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "WRAL reports progress in negotiations. Relief-anticipation framing. 10-day gap already longest in recent NC provider-payor disputes.",
  },
  {
    id: 28,
    date: "2025-12-12",
    source: "WRAL",
    sourceType: "tv",
    channel: "media",
    headline: "UNC Health and Cigna reach agreement — new contract signed, retroactive to December 1",
    frameAdoption: "unc",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "RESOLUTION. WRAL breaks the agreement news. Retroactive to Dec 1 means patients will not bear gap-period costs. Commercial plans only — Medicare Advantage dropped separately. WRAL's 7th story shows sustained dominance of this beat.",
  },
  // === PROVIDER OWNED MEDIA ===
  {
    id: 29,
    date: "2025-07-02",
    source: "UNC Health Newsroom",
    sourceType: "owned",
    channel: "media",
    headline: "UNC Health seeks fair agreement with Cigna — patients may be affected if contract not renewed",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "First UNC Health official statement. 'Seeks fair agreement' implies Cigna is being unfair. Lists grievances: inadequate rates, excessive prior authorization, high denial rates, downcoded claims. Sets UNC's narrative framework for entire dispute.",
  },
  {
    id: 30,
    date: "2025-12-01",
    source: "UNC Health Newsroom",
    sourceType: "owned",
    channel: "media",
    headline: "UNC Health unable to reach agreement with Cigna — contract expires, patients advised of options",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Gap-day statement. 'Unable to reach agreement' places blame on Cigna's unwillingness. Patient advisory with practical guidance. Positions UNC as trying to help patients Cigna is harming.",
  },
  {
    id: 31,
    date: "2025-12-12",
    source: "UNC Health Newsroom",
    sourceType: "owned",
    channel: "media",
    headline: "UNC Health signs new agreement with Cigna — coverage retroactive to December 1 for commercial members",
    frameAdoption: "unc",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution announcement. Retroactive coverage is the key detail — patients will not bear gap costs. 'Commercial members' clarifies scope — Medicare Advantage was dropped separately. Victory framing: UNC secured sustainable terms.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 32,
    date: "2025-07-10",
    source: "UNC Health (Facebook)",
    sourceType: "social",
    channel: "social",
    headline: "UNC Health Facebook post: 'We are committed to reaching a fair agreement with Cigna for our patients'",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Official UNC Health Facebook. 'Fair agreement' and 'for our patients' framing positions UNC as patient advocate vs Cigna. Comment sections likely filled with affected patients sharing stories. Facebook reaches older NC demographic.",
  },
  {
    id: 33,
    date: "2025-09-15",
    source: "UNC Health (LinkedIn)",
    sourceType: "social",
    channel: "social",
    headline: "UNC Health LinkedIn update on Cigna negotiations — professional audience, employer decision-makers",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "LinkedIn reaches NC employer/HR decision-makers. Professional tone but same 'fair agreement' framing. Employer audience is critical — they choose Cigna or alternatives for employee benefits.",
  },
  {
    id: 34,
    date: "2025-11-26",
    source: "NC Hospital Association (Facebook)",
    sourceType: "social",
    channel: "social",
    headline: "NC Hospital Association shares UNC Health-Cigna update — Steve Lawler: 'Be a good partner'",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "NCHA amplification. Steve Lawler's 'Be a good partner' directed at Cigna. Industry association backing gives UNC institutional credibility. Reaches broader NC hospital community audience.",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 35,
    date: "2025-10-05",
    source: "Town of Apex — Mayor Jacques Gilbert",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Apex Mayor Gilbert: town exploring 'everything on the table' including switching from Cigna — 850 employees",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "CRITICAL EMPLOYER DEFECTION SIGNAL. Town of Apex (fastest-growing municipality in NC) publicly considering dropping Cigna. Mayor Gilbert and Manager Randy Vosburg quoted. 850 employees. Municipal government action creates political pressure Cigna cannot easily counter.",
  },
  {
    id: 36,
    date: "2025-10-05",
    source: "Town of Apex — Manager Randy Vosburg",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Apex Town Manager Vosburg: 'everything on the table' to protect employee access to UNC Health",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Town Manager operational perspective. Administrative leader confirming political will to act. 'Protect employee access' positions Cigna as threat to municipal workforce healthcare.",
  },
  {
    id: 37,
    date: "2025-11-10",
    source: "NC Hospital Association — Steve Lawler",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "NCHA President Steve Lawler to Cigna: 'Be a good partner' — industry association backs UNC Health",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "NC Hospital Association president publicly sides with UNC Health. 'Be a good partner' is a polished but pointed rebuke of Cigna's negotiating posture. Industry solidarity strengthens UNC's position and signals Cigna is outlier.",
  },
  {
    id: 38,
    date: "2025-11-18",
    source: "Governor Josh Stein (acknowledgment)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Governor Stein acknowledges UNC Health-Cigna dispute but does not formally intervene",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "GOVERNOR POSTURE. Stein acknowledged the dispute publicly but stopped short of formal intervention or executive pressure. NC does not have equivalent of NY's 60-day cooling-off rule. Silence benefits UNC — governor not backing Cigna.",
  },
  {
    id: 39,
    date: "2025-11-20",
    source: "NC Department of Insurance",
    sourceType: "news",
    channel: "stakeholder",
    headline: "NC DOI establishes complaint pathway for patients affected by UNC Health-Cigna dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Regulatory response. NC DOI creates formal complaint mechanism. While not direct intervention, complaint volume becomes data point that pressures Cigna. Regulatory attention is inherently negative for insurer.",
  },
  {
    id: 40,
    date: "2025-11-25",
    source: "Duke/Aetna, WakeMed/UHC, UNC/UHC (2024) precedents",
    sourceType: "news",
    channel: "stakeholder",
    headline: "NC pattern: Duke/Aetna, WakeMed/UHC, UNC/UHC (2024) disputes establish recurring provider-payor tension",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "PATTERN EVIDENCE. Multiple recent NC provider-payor disputes: Duke vs Aetna, WakeMed vs UHC, UNC vs UHC in 2024. Systemic framing normalizes UNC's position — not uniquely aggressive, responding to industry-wide insurer behavior.",
  },
  // === PATIENT STORIES (additional detail entries) ===
  {
    id: 41,
    date: "2025-09-18",
    source: "WRAL (Pederson family follow-up)",
    sourceType: "tv",
    channel: "media",
    headline: "Patric Pederson: baby Stanley survived meningitis, RSV, strokes at UNC — 'can't imagine going anywhere else'",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Extended Pederson family coverage. 11-month-old Stanley's medical history (meningitis, RSV, strokes) makes UNC his essential care team. Parent's fear of losing specialists who saved child's life. Most emotionally powerful patient story in the dispute.",
  },
  {
    id: 42,
    date: "2025-11-05",
    source: "WRAL (Pezzoni profile)",
    sourceType: "tv",
    channel: "media",
    headline: "Becky Pezzoni: 'the patient got lost in this' — cancer survivor with 4 Rx at risk, no insurer choice",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "'The patient got lost' becomes recurring quote in coverage. Pezzoni's lack of choice (employer only offers Cigna) highlights structural trap. 4 prescriptions at risk makes disruption concrete and ongoing, not hypothetical.",
  },
  {
    id: 43,
    date: "2025-11-25",
    source: "WRAL (cost impact story)",
    sourceType: "tv",
    channel: "media",
    headline: "Unnamed patient: occupational therapy copay would jump from $25 to $468 if contract expires",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "$25 to $468 copay jump (19x) is the single most-cited statistic in the dispute. Concrete, shocking dollar figure cuts through policy complexity. Doctor visit $30 to $165 (5.5x) also cited. Makes abstract dispute tangible for every viewer.",
  },
  // === ADDITIONAL MEDIA ===
  {
    id: 44,
    date: "2025-11-28",
    source: "ABC11 / WTVD (Thanksgiving special)",
    sourceType: "tv",
    channel: "media",
    headline: "ABC11 Thanksgiving coverage: NC families worried about healthcare access heading into holidays",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Holiday timing amplifies emotional resonance. Third ABC11 story. Families gathering for Thanksgiving discussing healthcare anxiety. Emotional peak of pre-gap coverage.",
  },
  {
    id: 45,
    date: "2025-12-01",
    source: "WRAL (day-of gap coverage)",
    sourceType: "tv",
    channel: "media",
    headline: "Day 1: UNC Health officially out-of-network for Cigna — patients already facing higher bills",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "high",
    notes: "Gap Day 1 coverage. 'Already facing higher bills' — immediate tangible harm. Unlike disputes that resolve before deadline, patients are experiencing real financial impact from day one.",
  },
  {
    id: 46,
    date: "2025-12-04",
    source: "Social media (NC patient community)",
    sourceType: "social",
    channel: "social",
    headline: "NC patient communities share UNC-Cigna disruption stories — fear, frustration, calls to switch insurers",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: true,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Organic social sharing during gap period. Patient communities on Facebook groups, Reddit r/NorthCarolina, Nextdoor. 'Switch insurers' sentiment creates direct market pressure on Cigna from consumer base.",
  },
  {
    id: 47,
    date: "2025-12-06",
    source: "Social media (employer/HR forums)",
    sourceType: "social",
    channel: "social",
    headline: "NC employer and HR professionals discuss Cigna alternatives in wake of UNC Health gap",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Employer decision-maker social channels. HR professionals and benefits managers sharing concerns about Cigna network reliability. Open enrollment timing (many companies in Q4) amplifies switching risk for Cigna.",
  },
  {
    id: 48,
    date: "2025-12-08",
    source: "UNC Health (Facebook — gap update)",
    sourceType: "social",
    channel: "social",
    headline: "UNC Health Facebook: 'We continue to negotiate in good faith — our patients deserve access to their doctors'",
    frameAdoption: "unc",
    sentiment: "negative_cigna",
    patientStory: false,
    blameDirection: "cigna",
    reachEstimate: "medium",
    notes: "Mid-gap social update. 'Good faith' and 'deserve access' framing. High comment engagement from affected patients. UNC maintains patient-advocate positioning throughout gap.",
  },
  {
    id: 49,
    date: "2025-12-12",
    source: "UNC Health (Facebook — resolution)",
    sourceType: "social",
    channel: "social",
    headline: "UNC Health announces agreement on Facebook: 'We're pleased to share that we've reached a new contract with Cigna'",
    frameAdoption: "unc",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution announcement on social. Relief framing. High engagement expected given anxiety in previous posts' comment sections. 'We've reached' — UNC claims agency in resolution.",
  },
  {
    id: 50,
    date: "2025-12-12",
    source: "UNC Health (LinkedIn — resolution)",
    sourceType: "social",
    channel: "social",
    headline: "UNC Health LinkedIn resolution post — professional audience, employer reassurance",
    frameAdoption: "unc",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "LinkedIn resolution post reaches employer/HR audience. Reassurance for employer clients that network access is restored. Professional tone but same UNC-as-advocate framing.",
  },
  {
    id: 51,
    date: "2025-12-12",
    source: "NC Hospital Association (Facebook — resolution)",
    sourceType: "social",
    channel: "social",
    headline: "NCHA shares resolution news — industry solidarity through to resolution",
    frameAdoption: "unc",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "NCHA amplifies resolution. Industry association maintained support throughout. Signals to other NC insurers that hospital association will back providers in disputes.",
  },
];

const LABELS = {
  frameAdoption: { unc: "UNC Frame", cigna: "Cigna Frame", balanced: "Balanced" },
  sentiment: {
    negative_cigna: "Anti-Cigna",
    negative_unc: "Anti-UNC",
    neutral: "Neutral",
    positive_cigna: "Pro-Cigna",
    positive_unc: "Pro-UNC",
  },
  blameDirection: { cigna: "Blames Cigna", unc: "Blames UNC", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National/major syndication (1.5)
  "Yahoo News": 1.5,
  // Tier 2 — Regional authority (1.2)
  "WRAL": 1.2, "ABC11 / WTVD": 1.2, "CBS17": 1.2, "Axios Raleigh": 1.2,
  "WRAL (Pederson family follow-up)": 1.2, "WRAL (Pezzoni profile)": 1.2,
  "WRAL (cost impact story)": 1.2, "WRAL (day-of gap coverage)": 1.2,
  "ABC11 / WTVD (Thanksgiving special)": 1.2,
  // Tier 3 — Trade/niche (1.0)
  "Becker's Hospital Review": 1.0, "HealthLeaders": 1.0, "WBT Radio": 1.0,
  "RevQuest RCM": 1.0, "InsuraSales": 1.0, "DistilInfo": 1.0,
  "The Local Reporter": 1.0,
  // Tier 3.5 — Community papers (0.8)
  "Avery Journal": 0.8, "Watauga Democrat": 0.8,
  // Tier 4 — Organic social (0.7)
  "Social media (NC patient community)": 0.7,
  "Social media (employer/HR forums)": 0.7,
  // Tier 6 — Owned/party media (0.3)
  "UNC Health Newsroom": 0.3,
  "UNC Health (Facebook)": 0.3, "UNC Health (LinkedIn)": 0.3,
  "UNC Health (Facebook — gap update)": 0.3, "UNC Health (Facebook — resolution)": 0.3,
  "UNC Health (LinkedIn — resolution)": 0.3,
  "NC Hospital Association (Facebook)": 0.3, "NC Hospital Association (Facebook — resolution)": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "Town of Apex — Mayor Jacques Gilbert": 1.3, "Town of Apex — Manager Randy Vosburg": 1.3,
  "NC Hospital Association — Steve Lawler": 1.3,
  "Governor Josh Stein (acknowledgment)": 1.3, "NC Department of Insurance": 1.3,
  "Duke/Aetna, WakeMed/UHC, UNC/UHC (2024) precedents": 1.3,
};

const SEARCH_TRENDS = [
  { week: "2025-07-02", interest: 15 }, { week: "2025-07-14", interest: 10 },
  { week: "2025-08-01", interest: 8 }, { week: "2025-08-15", interest: 8 },
  { week: "2025-09-01", interest: 5 }, { week: "2025-09-15", interest: 5 },
  { week: "2025-10-01", interest: 10 }, { week: "2025-10-15", interest: 10 },
  { week: "2025-11-01", interest: 20 }, { week: "2025-11-15", interest: 40 },
  { week: "2025-11-26", interest: 75 }, { week: "2025-11-30", interest: 100 },
  { week: "2025-12-05", interest: 80 }, { week: "2025-12-12", interest: 95 },
  { week: "2025-12-20", interest: 15 }, { week: "2025-12-31", interest: 5 },
];

export default {
  // Identity
  providerKey: "unc",
  payorKey: "cigna",
  providerName: "UNC Health",
  payorName: "Cigna",
  providerShort: "UNC",
  payorShort: "Cigna",
  navShort: "UNC v. Cigna",
  title: "UNC Health vs Cigna",
  subtitle: "Contract dispute \u00b7 Resolved December 12, 2025",
  gradientId: "unccigna",

  // Dates
  monitorStart: "July 1, 2025",
  monitorEnd: "December 31, 2025",
  disputePublicDate: "2025-07-02",

  // Colors
  colors: {
    providerColor: "#4B9CD3",
    payorColor: "#E87722",
    neutral: "#64748B",
    accent: "#4B9CD3",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#4B9CD3", "#7A8FA8", "#E87722"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"UNC Health Cigna" \u00b7 weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.72,
    nationalMedian: 1.0,
    networkComplaints: 1243,
    priorYearComplaints: 891,
    regulatorAction: "NC Department of Insurance established complaint pathway for affected patients. Governor Stein acknowledged dispute but did not formally intervene. No equivalent of NY 60-day cooling-off rule in NC.",
    signalRead: "Cigna's complaint index is elevated (1.72x median) driven by prior auth burden and network disruption in NC. The 40% increase in network complaints reflects growing provider dissatisfaction with Cigna's denial practices and downcoding. The 12-day actual gap is rare — most disputes resolve pre-deadline.",
  },

  // Executive summary
  executiveSummary: {
    statement: "The dispute resulted in a 12-day actual gap (Dec 1-12) before resolution — unlike most provider-payor disputes which resolve at the deadline. Retroactive coverage to Dec 1 mitigated patient financial harm, but the gap itself was a PR defeat for Cigna.",
    keyMessages: [
      "UNC's operational grievances (30% denial rate, downcoded claims, excessive prior auth) resonated more with media than Cigna's '40% rate hike' framing.",
      "Concrete patient cost examples ($25\u2192$468 OT copay, $30\u2192$165 doctor visit) made abstract dispute tangible and shareable.",
      "The actual 12-day gap is unusual — most disputes resolve pre-deadline. Each day of gap generated new coverage cycle compounding Cigna's narrative damage.",
      "Municipal employer defection threat (Town of Apex, 850 employees) created political and market pressure Cigna could not ignore.",
    ],
    marcomm: [
      "<strong>Sick babies and cancer survivors are unbeatable narratives.</strong> Patric Pederson's 11-month-old Stanley (meningitis, RSV, strokes) and Becky Pezzoni's cancer survival story gave UNC narrative advantages Cigna could never counter with equivalent patient advocates.",
      "<strong>The 12-day gap was Cigna's worst-case outcome.</strong> Every day patients were actually out-of-network generated new media cycles, social media outrage, and employer anxiety. Resolution at deadline is bad; actual disruption is catastrophic for insurer reputation.",
      "<strong>Rural NC coverage extended narrative beyond Triangle.</strong> Community papers in Avery and Watauga counties humanized the dispute for rural Appalachian audiences where UNC is often the only major system. Cigna has no comparable rural presence story.",
      "<strong>NC pattern evidence undermines 'UNC is uniquely unreasonable' framing.</strong> Duke/Aetna, WakeMed/UHC, and UNC/UHC (2024) disputes establish that NC provider-payor tension is systemic, not UNC-specific.",
    ],
  },
  channelTakeaways: {
    media: [
      "WRAL dominated with 7+ stories including the most impactful patient narratives (Pederson baby, Pezzoni cancer survivor, cost examples).",
      "Triangle TV trifecta (WRAL, ABC11, CBS17) provided saturating local coverage — every major station covered multiple angles.",
      "Community papers (Avery Journal, Watauga Democrat) extended geographic reach to rural NC where UNC is essential infrastructure.",
      "Trade press (Becker's, HealthLeaders) gave UNC's operational grievances (denial rates, downcoding) equal weight to Cigna's rate claims.",
    ],
    social: [
      "UNC Health's Facebook and LinkedIn maintained consistent 'fair agreement' and 'patient advocate' framing throughout dispute.",
      "NC Hospital Association amplified UNC's position through social channels — industry solidarity signal.",
      "Organic patient community posts during 12-day gap generated employer-switching sentiment that directly threatened Cigna's NC market share.",
      "Open enrollment timing (Q4) amplified social discussion among HR professionals considering Cigna alternatives.",
    ],
    stakeholder: [
      "Town of Apex's public consideration of dropping Cigna (850 employees) was the most impactful employer-stakeholder action in the dispute.",
      "NCHA President Steve Lawler's 'Be a good partner' gave UNC institutional backing from the state hospital association.",
      "Governor Stein's acknowledgment without intervention was strategically neutral — did not back Cigna, did not create political risk for UNC.",
      "NC DOI complaint pathway created regulatory documentation of patient harm — data that pressures Cigna in future rate negotiations.",
    ],
    employer: [
      "Municipal employer defection threats (Apex) created concrete market risk for Cigna beyond reputational damage.",
      "Open enrollment season timing meant employers were actively evaluating Cigna alternatives during peak dispute coverage.",
      "Broker channels (InsuraSales) distributed gap guidance to employer accounts — each advisory reinforced Cigna's network reliability problem.",
    ],
  },
};
