// UW Medicine vs Aetna — PR War Room Config
// Dispute period: June 1–July 3, 2025. 33-day out-of-network gap. Resolved with retroactive contract.

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2025-05-29",
    source: "Seattle Times",
    url: "https://www.seattletimes.com/seattle-news/health/uw-medicine-and-aetna-fail-to-reach-contract-thousands-of-patients-notified/",
    sourceType: "news",
    channel: "media",
    headline: "UW Medicine and Aetna fail to reach contract — ~53,000 patients face out-of-network costs starting June 1",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "First major coverage. Seattle Times is dominant regional paper. ~53,000 patients notified who had at least one visit in past two years. Affected facilities: Harborview Medical Center, UW Medical Center (Montlake + Northwest), Fred Hutch Cancer Center, Valley Medical Center. UW Medicine CEO Tim Dellit: 'fair, sustainable and in the best interests of our patients.' Aetna rates described as lowest of any commercial payor in the market.",
  },
  {
    id: 2,
    date: "2025-05-30",
    source: "KIRO 7",
    url: "https://www.kiro7.com/news/health/uw-medicine-aetna-health-insurance-still-far-deal-contract-nears-expiration/BTCUKIN6ZZF4HHHZ3HM2AMN3W4/",
    sourceType: "tv",
    channel: "media",
    headline: "UW Medicine drops out of Aetna network — thousands of patients scramble for answers before June 1 deadline",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "Lead local TV coverage on eve of contract expiration. 'Drops out' framing places responsibility on the contract failure dynamics rather than UW Medicine's choice. Patient anxiety stories. KIRO 7 (CBS affiliate) reaches broad Seattle-Tacoma DMA. Both sides quoted but patient stories favor UW Medicine side.",
  },
  {
    id: 3,
    date: "2025-05-30",
    source: "FOX 13 Seattle",
    sourceType: "tv",
    channel: "media",
    headline: "Aetna patients lose in-network access to UW Medicine facilities and Fred Hutch starting June 1",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "FOX 13 coverage. 'Lose in-network access' is direct and alarming. Lists all affected facilities including trauma center (Harborview) and cancer center (Fred Hutch). Fred Hutch inclusion makes cancer patient disruption angle unavoidable.",
  },
  {
    id: 4,
    date: "2025-05-30",
    source: "Shoreline Area News",
    url: "https://www.shorelineareanews.com/2025/05/aetna-and-uw-medicine-at-odds-over.html",
    sourceType: "news",
    channel: "media",
    headline: "UW Medicine-Aetna contract lapse affects Shoreline patients who rely on UW Medical Center Northwest",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Hyperlocal coverage. UW Medical Center Northwest campus is physically in Shoreline. Local patients directly affected by network gap. Community-level awareness building. Comment sections on Shoreline Area News show patient frustration and anger directed at Aetna.",
  },
  {
    id: 5,
    date: "2025-06-01",
    source: "KING 5",
    sourceType: "tv",
    channel: "media",
    headline: "Sharon Zimmerman, rare cancer patient at Fred Hutch, fears losing UW Medicine access — 'I'm going to choose my life'",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "KEY PATIENT STORY. Sharon Zimmerman: rare cancer, in active treatment at UW Medicine/Fred Hutch Cancer Center. Quote: 'When it comes down to my life vs insurance, I'm going to choose my life.' KING 5 (NBC affiliate) — highest-reach single patient story in the dispute. Cancer patient facing access loss at a nationally ranked cancer center is maximally sympathetic framing. Defining segment of the entire dispute.",
  },
  {
    id: 6,
    date: "2025-06-01",
    source: "Becker's Payer Issues",
    url: "https://www.beckerspayer.com/contracting/aetna-uw-medicine-to-split-on-june-1/",
    sourceType: "news",
    channel: "media",
    headline: "Aetna, UW Medicine go out of network — 53,000 patients affected, Boeing retiees exempt under PPO ESA",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National healthcare trade press. Notes Boeing retirees on Aetna PPO ESA Medicare Advantage plan are exempt from disruption — creating a two-tier patient experience that invites equity criticism. 53,000 figure established as benchmark. Hospital/payer executive audience.",
  },
  {
    id: 7,
    date: "2025-06-01",
    source: "InsuranceNewsNet",
    sourceType: "news",
    channel: "media",
    headline: "Aetna loses UW Medicine from network as contract expires — CVS Health Aetna segment lost $924M in 2024",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Insurance trade press. Financial context: CVS Health parent company $372.8B revenue in 2024 but Aetna insurance segment lost $924M. Losses create corporate pressure to hold provider rates down, explaining Aetna's hard bargaining. But revenue figure undermines 'we can't afford it' argument.",
  },
  {
    id: 8,
    date: "2025-06-02",
    source: "MyNorthwest",
    url: "https://mynorthwest.com/local/uw-medicine-aetna-contract-deal/4093928",
    sourceType: "news",
    channel: "media",
    headline: "UW Medicine, Aetna still far apart from contract agreement — patients scramble across Puget Sound",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Regional digital news. 'Still far apart' framing on day two of gap signals no quick resolution. UW Medicine quoted: 'Unfortunately, despite our best efforts, we have not been able to reach a fair agreement with Aetna that is financially feasible.' Aetna: claims UW Medicine 'continues to demand unreasonable rates.'",
  },
  {
    id: 9,
    date: "2025-06-03",
    source: "The Daily (UW)",
    url: "https://www.dailyuw.com/article/uw-medicine-and-aetna-fail-to-reach-final-contract-agreement-thousands-of-patients-left-out-of-network-20250605",
    sourceType: "news",
    channel: "media",
    headline: "UW Medicine and Aetna fail to reach final contract agreement — thousands of patients left out of network",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "University of Washington student newspaper. Important for campus community — UW students and staff rely on UW Medicine as primary care. Notes transition-of-care coverage available case-by-case for cancer patients and pregnant patients. Adds 'university community' angle to dispute.",
  },
  {
    id: 10,
    date: "2025-06-03",
    source: "EIN Presswire",
    sourceType: "news",
    channel: "media",
    headline: "UW Medicine contract dispute with Aetna highlights growing provider-payor tensions in Pacific Northwest",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Wire service distribution. Frames dispute as part of broader PNW trend — Providence-Aetna precedent in Washington State referenced. Wire pickup extends reach beyond Seattle market.",
  },
  {
    id: 11,
    date: "2025-06-04",
    source: "Daily Chronicle",
    url: "https://chronline.com/stories/uw-medicine-and-aetna-fail-to-reach-contract-thousands-of-patients-notified,382032",
    sourceType: "news",
    channel: "media",
    headline: "Aetna patients in Washington face uncertain access to UW Medicine hospitals and clinics",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Regional coverage syndicated from Seattle Times reporting. 'Uncertain access' framing emphasizes patient impact. Lists full facility scope including Harborview trauma center angle. Reaches audiences beyond Seattle metro.",
  },
  {
    id: 12,
    date: "2025-06-05",
    source: "Seattle Times (Editorial Board)",
    url: "https://www.seattletimes.com/opinion/patients-hurt-most-by-aetna-uw-medicine-contract-failure/",
    sourceType: "opinion",
    channel: "media",
    headline: "Seattle Times editorial: Patients hurt most by Aetna-UW Medicine contract failure",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Editorial board weigh-in. 'Patients hurt most' headline — 'patients as pawns' framing criticizes both sides but implicitly pressures the party with more leverage to settle. Editorial boards carry outsized influence with local policymakers and employer HR departments. Most influential opinion piece of the dispute.",
  },
  {
    id: 13,
    date: "2025-06-05",
    source: "Healthcare Dive",
    sourceType: "news",
    channel: "media",
    headline: "UW Medicine joins growing list of providers dropping Aetna over reimbursement rates",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "National healthcare trade. 'Growing list' framing positions Aetna as serially underpaying providers — not just UW Medicine but a pattern. Notes Aetna rates described as lowest of any commercial payor at UW Medicine. Providence-Aetna WA precedent cited. Industry audience.",
  },
  {
    id: 14,
    date: "2025-06-10",
    source: "KIRO 7",
    sourceType: "tv",
    channel: "media",
    headline: "Patients caught in limbo as UW Medicine-Aetna dispute drags on — no resolution in sight after 10 days",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "Mid-gap follow-up. 'Limbo' and 'drags on' framing increases pressure. Patient interviews reinforce hardship angle — delayed appointments, scrambling for alternatives. Ten days into gap with no public progress toward resolution.",
  },
  {
    id: 15,
    date: "2025-06-10",
    source: "Shoreline Area News",
    sourceType: "news",
    channel: "media",
    headline: "Shoreline residents seek alternatives as UW Medicine-Aetna gap continues into second week",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Follow-up hyperlocal coverage. Patients actively seeking alternatives demonstrates real disruption to care continuity. UW Medical Center Northwest campus is anchor healthcare institution for Shoreline community. Reader comments describe Aetna as 'not caring for its members.'",
  },
  {
    id: 16,
    date: "2025-06-15",
    source: "FOX 13 Seattle",
    sourceType: "tv",
    channel: "media",
    headline: "UW Medicine-Aetna standoff enters third week — patients weigh switching insurers mid-year",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "Third-week follow-up. Patients considering mid-year insurer switches signals extreme severity — switching insurers is a drastic step. 'Standoff' language implies both sides dug in but patient stories consistently favor UW Medicine.",
  },
  {
    id: 17,
    date: "2025-06-20",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "UW Medicine-Aetna dispute enters fourth week with no resolution — longest active gap in Washington State",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press follow-up. 'Fourth week' and 'longest active gap in WA' framing amplifies severity. National hospital executive audience tracking dispute duration as benchmark. Becker's also covered Providence-Aetna precedent.",
  },
  {
    id: 18,
    date: "2025-06-25",
    source: "Healthcare Dive",
    sourceType: "news",
    channel: "media",
    headline: "Aetna's Washington network shrinks further as UW Medicine gap persists — Providence precedent looms",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Trade press. 'Shrinks further' positions Aetna as having a WA-specific network adequacy problem. Providence precedent cited as pattern evidence. Industry analysts questioning Aetna's WA market viability for employer accounts.",
  },
  {
    id: 19,
    date: "2025-06-27",
    source: "BellevueSeattle.com",
    sourceType: "news",
    channel: "media",
    headline: "Starting June 1, Aetna may no longer be contracted with UW Medicine — Eastside patients affected",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Eastside community news. Bellevue/Eastside is high-income tech worker demographic — many with employer-sponsored Aetna plans. Valley Medical Center in Renton serves South King County and Eastside communities. Extends geographic footprint of coverage.",
  },
  {
    id: 20,
    date: "2025-07-03",
    source: "Seattle Times",
    url: "https://www.seattletimes.com/seattle-news/health/uw-medicine-and-aetna-reach-new-contract-agreement/",
    sourceType: "news",
    channel: "media",
    headline: "UW Medicine and Aetna reach new contract agreement — retroactive to June 1, runs through January 1, 2027",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution coverage. Retroactive provision means 33-day gap is papered over contractually — services during gap covered at in-network rates. But patients experienced real anxiety, delayed care, and some switched providers. Contract runs through Jan 1, 2027. Neither side disclosed specific rate terms.",
  },
  {
    id: 21,
    date: "2025-07-03",
    source: "KIRO 7",
    url: "https://www.kiro7.com/news/local/uw-aetna-reach-new-agreement-heres-what-that-means-you/UGZRGLTE3NERFLP3P4OJM4X2UA/",
    sourceType: "tv",
    channel: "media",
    headline: "UW and Aetna reach new agreement — here's what that means for patients after 33-day gap",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution coverage. '33-day gap' quantifies disruption duration in headline. Retroactive provision noted but damage to patient trust already done. KIRO 7 provided most consistent coverage arc: pre-deadline, mid-gap, resolution.",
  },
  {
    id: 22,
    date: "2025-07-03",
    source: "FOX 13 Seattle",
    url: "https://www.fox13seattle.com/news/uw-medicine-aetna-agreement-patient-coverage",
    sourceType: "tv",
    channel: "media",
    headline: "New contract ensures UW Medicine remains in-network for Aetna patients — coverage retroactive to June 1",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "FOX 13 resolution coverage. 'Ensures remains in-network' frames deal as preserving access UW Medicine fought for. Notes agreement covers Harborview, UW Medical Center, Valley Medical Center, and Fred Hutch physician services.",
  },
  {
    id: 23,
    date: "2025-07-03",
    source: "Shoreline Area News",
    sourceType: "news",
    channel: "media",
    headline: "Relief for Shoreline patients: UW Medicine and Aetna reach retroactive agreement after month-long gap",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Resolution coverage at hyperlocal level. 'Relief' framing acknowledges patient hardship during the 33-day gap. Third Shoreline Area News piece — complete coverage arc at community level.",
  },
  {
    id: 24,
    date: "2025-07-03",
    source: "InsuranceNewsNet",
    sourceType: "news",
    channel: "media",
    headline: "Aetna resolves UW Medicine dispute with retroactive deal — Aetna segment losses continue to pressure CVS Health",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Insurance trade resolution coverage. Financial framing — Aetna's $924M segment loss context. Retroactive provision noted. CVS Health investor implications. Resolution doesn't change Aetna's structural financial challenges.",
  },
  {
    id: 25,
    date: "2025-07-03",
    source: "EIN Presswire",
    sourceType: "news",
    channel: "media",
    headline: "UW Medicine and Aetna announce new agreement ending 33-day network gap in Washington State",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Wire service resolution coverage. '33-day network gap' quantifies the disruption in headline — becomes the benchmark figure for this dispute in all subsequent references.",
  },
  // === UW MEDICINE OWNED MEDIA ===
  {
    id: 26,
    date: "2025-05-29",
    source: "UW Medicine Newsroom",
    url: "https://newsroom.uw.edu/news-releases/statement-contract-negotiations-with-aetna/",
    sourceType: "owned",
    channel: "media",
    headline: "UW Medicine statement: Unable to reach fair agreement with Aetna — rates are lowest of any commercial payor",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Official UW Medicine statement setting the provider narrative. CEO Tim Dellit: 'fair, sustainable and in the best interests of our patients.' Key data point: Aetna's reimbursement rates are the lowest compared to other insurance companies in the market. 'Lowest rates' framing is UW Medicine's stickiest argument — other payors pay more for the same care.",
  },
  {
    id: 27,
    date: "2025-04-15",
    source: "UW Medicine (patient notification letters)",
    sourceType: "owned",
    channel: "media",
    headline: "UW Medicine begins notifying Aetna patients of possible June 1 contract termination — directs to resources",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Patient notification campaign began in April 2025. ~53,000 patients who had at least one visit in the past two years received letters. Early notification demonstrates UW Medicine's patient-first communication approach. Includes information about transition-of-care options.",
  },
  {
    id: 28,
    date: "2025-06-01",
    source: "UW Medicine (LinkedIn)",
    sourceType: "social",
    channel: "media",
    headline: "UW Medicine LinkedIn: Notifying patients and community of Aetna contract lapse, directing to FAQ and resources",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "LinkedIn reaches professional and employer audience. UW Medicine is one of WA's largest employers (~30,000 employees). Post directs patients to FAQ and alternative coverage options. Professional network amplification reaches HR decision-makers.",
  },
  {
    id: 29,
    date: "2025-06-01",
    source: "UW Medicine (Facebook)",
    sourceType: "social",
    channel: "media",
    headline: "UW Medicine Facebook: Patient notification about Aetna contract gap and care continuity options",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Facebook reaches older patient demographic most likely to be in active treatment and on Medicare Advantage plans. Comment sections filled with patient anxiety and anger directed at Aetna. One commenter describes Aetna's provider list 'shrinking each year.'",
  },
  {
    id: 30,
    date: "2025-07-03",
    source: "UW Medicine Newsroom",
    sourceType: "owned",
    channel: "media",
    headline: "UW Medicine announces new agreement with Aetna — retroactive coverage ensures patients covered since June 1",
    frameAdoption: "uw",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Resolution announcement. 'Ensures patients covered' frames UW Medicine as having secured patient protection. Retroactive to June 1. Agreement covers Harborview, UW Medical Center (Montlake + Northwest), Valley Medical Center, UW Medicine Primary Care, and physician services at Fred Hutch.",
  },
  // === AETNA OWNED MEDIA ===
  {
    id: 31,
    date: "2025-05-31",
    source: "Aetna (public statement)",
    sourceType: "owned",
    channel: "media",
    headline: "Aetna: UW Medicine continues to demand unreasonable rates that would raise premiums for members",
    frameAdoption: "aetna",
    sentiment: "negative_uw",
    patientStory: false,
    blameDirection: "uw",
    reachEstimate: "medium",
    notes: "Aetna's primary defensive statement. Told Seattle Times they made 'every effort' to reach agreement but UW Medicine demands 'unreasonable rates.' Affordability framing targets employer audience. Defensive corporate tone. No patient voices. Quoted in most coverage but did not set the narrative.",
  },
  {
    id: 32,
    date: "2025-05-31",
    source: "Aetna (member notification)",
    sourceType: "owned",
    channel: "employer",
    headline: "Aetna notifies members: Network agreement with UW Medicine ends May 31 — alternative providers available",
    frameAdoption: "aetna",
    sentiment: "negative_uw",
    patientStory: false,
    blameDirection: "uw",
    reachEstimate: "medium",
    notes: "Direct member communication. Frames UW Medicine as choosing to leave network. Directs members to alternative in-network providers. Implicit message: Aetna's network is adequate without UW Medicine. But losing Harborview (only Level I trauma center in WA) makes this claim untenable.",
  },
  // === REGULATORY / WA OIC ===
  {
    id: 33,
    date: "2025-06-02",
    source: "WA OIC (Medium blog)",
    sourceType: "owned",
    channel: "media",
    headline: "WA Insurance Commissioner: What to know about UW Medicine and Aetna's split — patient rights and options",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Commissioner Patty Kuderer's office published patient guidance. Key points: transition-of-care forms available for cancer/pregnant patients; No Surprises Act protections apply; OIC cannot compel Medicare Advantage network changes (federal CMS jurisdiction). The fact that a state regulator published guidance signals significance of disruption.",
  },
  {
    id: 34,
    date: "2025-06-02",
    source: "WA OIC (Facebook)",
    sourceType: "social",
    channel: "media",
    headline: "WA Insurance Commissioner Facebook: Patient rights and protections during UW Medicine-Aetna gap",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Social amplification of OIC guidance. Directs patients to call Aetna for transition-of-care forms. Notes Medicare Advantage plans regulated by federal CMS, not state OIC — regulatory gap for MA enrollees.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 35,
    date: "2025-06-01",
    source: "Social media (Boeing employee)",
    sourceType: "social",
    channel: "social",
    headline: "Boeing employee urges colleagues to pressure HR to switch from Aetna — 'UW Medicine, Fred Hutch, Children's all out of network'",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "CRITICAL EMPLOYER SIGNAL. Boeing is WA's largest private employer with Aetna as a plan option. Employee calling for dumping Aetna entirely. Lists UW Medicine, Fred Hutch Cancer Center, and Children's Hospital as all out of network — devastating for Aetna's network adequacy claim. Direct commercial threat to Aetna's employer relationship.",
  },
  {
    id: 36,
    date: "2025-06-03",
    source: "Social media (Costco employee)",
    sourceType: "social",
    channel: "social",
    headline: "Costco employee notes shrinking Aetna network in WA — losing UW Medicine makes plan 'nearly useless'",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Another major WA employer signal. 'Shrinking network' and 'nearly useless' are devastating for Aetna's employer value proposition. Costco HQ is in Issaquah — core UW Medicine/Valley Medical Center service area. Employer-level frustration spreading across WA's largest companies.",
  },
  {
    id: 37,
    date: "2025-06-05",
    source: "Social media (Boeing retiree)",
    sourceType: "social",
    channel: "social",
    headline: "Boeing retiree on Aetna Medicare Advantage: 'leaving us stranded' without access to UW Medicine doctors",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Medicare Advantage angle. Retirees on MA plans are especially vulnerable — limited ability to switch plans mid-year. 'Leaving us stranded' is powerful emotional language. Boeing retiree community is large and politically active in WA. Note: Boeing retirees on PPO ESA plan were exempt, creating two-tier experience.",
  },
  {
    id: 38,
    date: "2025-06-08",
    source: "Social media (Shoreline Area News comments)",
    sourceType: "social",
    channel: "social",
    headline: "Community comments accuse Aetna of 'scare tactics' and being 'dangerous and greedy' — shrinking provider list",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Comment section reaction on community news site. Reader: Aetna 'not caring for its members' and provider list 'shrinking each year as medical entities refuse to do business with them.' Another calls negotiations 'scare tactics' that are 'dangerous and greedy.' Organic grassroots sentiment overwhelmingly anti-Aetna.",
  },
  {
    id: 39,
    date: "2025-06-10",
    source: "Social media (patient anxiety thread)",
    sourceType: "social",
    channel: "social",
    headline: "Patients share stories of delayed appointments, scrambling for new providers during UW Medicine-Aetna gap",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Organic patient stories during active gap. Unlike disputes resolved before lapse, this one had a real 33-day gap — patients experienced actual disruption, not just anxiety. Reports of delayed appointments, referral complications, out-of-pocket cost fears. Some patients report UW Medicine cancelling appointments during gap.",
  },
  {
    id: 40,
    date: "2025-06-15",
    source: "Social media (WA healthcare workers)",
    sourceType: "social",
    channel: "social",
    headline: "UW Medicine staff share frustration on social media — front-line workers fielding patient confusion daily",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Healthcare worker perspective. Staff dealing with patient confusion, rescheduling, and care coordination challenges. Humanizes UW Medicine side — workers as secondary victims of dispute. SEIU 1199NW represents many UW Medicine workers, adding labor angle.",
  },
  {
    id: 41,
    date: "2025-06-20",
    source: "Social media (general criticism)",
    sourceType: "social",
    channel: "social",
    headline: "Social posts link Aetna underpayment to CVS Health corporate cost-cutting — 'profits over patients'",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "CVS Health parent company connection invites 'corporate greed' framing. Aetna segment $924M loss in 2024 creates complex dynamic — Aetna is losing money but CVS parent has massive revenue. 'Profits over patients' framing resonates with general public skepticism of insurance companies.",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 42,
    date: "2025-06-01",
    source: "CEO Tim Dellit, MD (UW Medicine)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "UW Medicine CEO Dellit: Agreement must be 'fair, sustainable and in the best interests of our patients and employees'",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "CEO public framing. 'Fair, sustainable' implies Aetna's rates are neither. 'Best interests of our patients' positions UW Medicine as patient advocate, not profit-seeker. Dellit is a physician-CEO (MD) — clinician credibility. Key data: Aetna's reimbursement rates are the lowest of any commercial payor at UW Medicine. Quoted across all major coverage.",
  },
  {
    id: 43,
    date: "2025-06-02",
    source: "WA OIC Commissioner Patty Kuderer",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Commissioner Kuderer: OIC monitoring UW Medicine-Aetna dispute, ensuring patient protections enforced",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "State insurance commissioner publicly monitoring dispute. Kuderer's office references No Surprises Act protections and WA state continuity-of-care requirements. Regulatory attention increases pressure on both parties but especially Aetna as the insurer subject to OIC jurisdiction. Notes OIC cannot compel Medicare Advantage changes (federal CMS).",
  },
  {
    id: 44,
    date: "2025-06-05",
    source: "City of Seattle HR FAQ",
    url: "https://www.seattle.gov/documents/Departments/HumanResources/Benefits/News/UW_FAQ_.pdf",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "City of Seattle publishes employee FAQ on UW Medicine-Aetna dispute — directs affected city staff to alternatives",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Municipal employer response. City of Seattle is a major employer offering Aetna plans. The fact that a city government had to publish a detailed FAQ (hosted as PDF on seattle.gov) about an insurer's network gap is significant. Signals employer-level administrative burden and concern.",
  },
  {
    id: 45,
    date: "2025-06-08",
    source: "UNITE HERE NW Health & Welfare Trust",
    sourceType: "news",
    channel: "stakeholder",
    headline: "UNITE HERE Northwest Trust alerts hospitality worker members about UW Medicine-Aetna access disruption",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Union trust fund alert. UNITE HERE represents hotel, food service, and hospitality workers on Aetna Choice POS II plan. Lower-wage workers most vulnerable to network disruption and out-of-pocket costs. Blue-collar worker impact angle amplifies equity dimension of dispute.",
  },
  {
    id: 46,
    date: "2025-06-01",
    source: "No Surprises Act protections (federal)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Federal No Surprises Act provides some continuity protections — but gaps remain for routine care and new referrals",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Regulatory framework. No Surprises Act (effective Jan 2022) provides some protections for patients mid-treatment. However, coverage is not comprehensive — many patients face disruption for routine care, preventive visits, and new specialist referrals. WA OIC references these protections but acknowledges limitations.",
  },
  {
    id: 47,
    date: "2025-05-29",
    source: "Providence-Aetna WA precedent",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Providence Health previously clashed with Aetna in WA and OR — pattern of Aetna underpaying Pacific NW providers",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "PATTERN EVIDENCE. Providence, the largest health system in WA/OR, had its own Aetna contract dispute. Providence Oregon went out of network Jan 1, 2025 and didn't rejoin until Dec 1, 2025. Multiple PNW providers flagging Aetna's rates as unsustainably low undermines Aetna's framing that UW Medicine is uniquely expensive.",
  },
  {
    id: 48,
    date: "2025-05-29",
    source: "UW Medicine-Premera Blue Cross precedent (2023)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "UW Medicine precedent: 2023 Premera dispute threatened 175,000 patients — resolved before gap, but pattern of WA disputes",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "PRIOR UW MEDICINE DISPUTE. In 2023, UW Medicine and Premera Blue Cross negotiated down to the wire with 175,000-235,000 patients at risk. Resolved before July 1, 2023 with a 3-year contract. Context shows UW Medicine has been in this position before — but the Aetna dispute is the first where the gap actually occurred.",
  },
  {
    id: 49,
    date: "2025-06-10",
    source: "CVS Health / Aetna financials",
    sourceType: "news",
    channel: "stakeholder",
    headline: "CVS/Aetna context: $372.8B revenue in 2024 but Aetna segment lost $924M — cost-cutting imperative drives disputes",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "FINANCIAL CONTEXT. CVS Health parent company $372.8B revenue. Aetna insurance segment lost $924M in 2024. Financial losses create corporate pressure to hold down provider rates, explaining Aetna's hard bargaining. Revenue figure undermines 'we can't afford fair rates' argument. Structural pressure won't ease soon.",
  },
  {
    id: 50,
    date: "2025-06-01",
    source: "Harborview Medical Center — Level I trauma status",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Harborview is WA's only Level I trauma center and regional safety net — network gap creates unique access crisis",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "STRUCTURAL LEVERAGE. Harborview is the only designated Level I adult and pediatric trauma and burn center in Washington, serving as regional referral center for WA, AK, MT, and ID. It is the county safety-net hospital. Losing Harborview access — even temporarily — is a network adequacy crisis with no substitute. This is UW Medicine's strongest structural argument.",
  },
  {
    id: 51,
    date: "2025-06-12",
    source: "UNITE HERE (ongoing member alerts)",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "UNITE HERE issues multiple member alerts about Aetna-UW Medicine gap affecting hospitality workers and families",
    frameAdoption: "uw",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Ongoing union communications throughout the gap. Hospitality workers often have limited provider options and less financial ability to absorb out-of-network costs. Union framing emphasizes corporate insurer vs working families dynamic. UNITE HERE members on Aetna Choice POS II — directly impacted.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 52,
    date: "2025-06-01",
    source: "Boeing HR communications",
    sourceType: "owned",
    channel: "employer",
    headline: "Boeing notifies employees of UW Medicine-Aetna network disruption — directs to alternative in-network providers",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Boeing is WA's largest private employer. Internal HR communication to Aetna-enrolled employees creates direct employer pressure on Aetna. Administrative burden of redirecting employees and managing disruption frustration. Boeing retirees on PPO ESA exempt — but active employees are not.",
  },
  {
    id: 53,
    date: "2025-06-03",
    source: "Amazon / major WA tech employer HR",
    sourceType: "owned",
    channel: "employer",
    headline: "Major WA tech employers field employee questions about UW Medicine access under Aetna plans",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Amazon, Microsoft, Costco, and other major WA employers with Aetna plan options face employee disruption inquiries. Seattle tech employers compete fiercely on benefits — Aetna network instability becomes a competitive disadvantage. Each employer interaction is an implicit threat to Aetna's commercial relationship.",
  },
  {
    id: 54,
    date: "2025-06-15",
    source: "WA employer benefits advisors",
    sourceType: "news",
    channel: "employer",
    headline: "Benefits consultants advise WA employers to consider Aetna alternatives at next renewal if network instability continues",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Broker/consultant channel. Network disruption directly impacts Aetna's competitive position for employer renewals. Providence precedent + UW Medicine gap creates narrative of Aetna network instability in WA market. Benefits advisors influence employer purchasing decisions at scale.",
  },
  {
    id: 55,
    date: "2025-07-03",
    source: "UNITE HERE Northwest Trust (resolution update)",
    url: "https://uniteherenwtrusts.com/update-uw-medicine-rejoins-aetna-network/",
    sourceType: "owned",
    channel: "employer",
    headline: "UNITE HERE Trust: UW Medicine rejoins Aetna network — agreement retroactive from June 1 through January 2027",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Union trust resolution notification to members. Confirms retroactive coverage — services during 33-day gap will be covered at in-network rates. Relief communication to hospitality workers who endured the most financially vulnerable period of the dispute.",
  },
];

const LABELS = {
  frameAdoption: { uw: "UW Med Frame", aetna: "Aetna Frame", balanced: "Balanced" },
  sentiment: {
    negative_aetna: "Anti-Aetna",
    negative_uw: "Anti-UW Med",
    neutral: "Neutral",
    positive_aetna: "Pro-Aetna",
    positive_uw: "Pro-UW Med",
  },
  blameDirection: { aetna: "Blames Aetna", uw: "Blames UW Med", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — Regional paper of record (1.5)
  "Seattle Times": 1.5, "Seattle Times (Editorial Board)": 1.5,
  // Tier 2 — Regional TV authority (1.2)
  "KIRO 7": 1.2, "KING 5": 1.2, "FOX 13 Seattle": 1.2,
  // Tier 3 — Trade/digital news (1.0)
  "Becker's Payer Issues": 1.0, "Becker's Hospital Review": 1.0,
  "Healthcare Dive": 1.0, "InsuranceNewsNet": 1.0,
  "EIN Presswire": 1.0, "Daily Chronicle": 1.0, "MyNorthwest": 1.0,
  "The Daily (UW)": 1.0, "Shoreline Area News": 1.0, "BellevueSeattle.com": 1.0,
  // Tier 4 — Organic social (0.7)
  "Social media (Boeing employee)": 0.7, "Social media (Costco employee)": 0.7,
  "Social media (Boeing retiree)": 0.7, "Social media (general criticism)": 0.7,
  "Social media (patient anxiety thread)": 0.7, "Social media (WA healthcare workers)": 0.7,
  "Social media (Shoreline Area News comments)": 0.7,
  // Tier 5 — Comment sections (0.4)
  // (comments folded into Tier 4 social for this dispute)
  // Tier 6 — Owned/party media (0.3)
  "UW Medicine Newsroom": 0.3, "UW Medicine (patient notification letters)": 0.3,
  "UW Medicine (LinkedIn)": 0.3, "UW Medicine (Facebook)": 0.3,
  "Aetna (public statement)": 0.3, "Aetna (member notification)": 0.3,
  "WA OIC (Medium blog)": 0.3, "WA OIC (Facebook)": 0.3,
  "Boeing HR communications": 0.3, "Amazon / major WA tech employer HR": 0.3,
  "UNITE HERE (ongoing member alerts)": 0.3,
  "UNITE HERE Northwest Trust (resolution update)": 0.3,
  "City of Seattle HR FAQ": 0.3,
  // Tier 7 — Stakeholder actions (1.3)
  "WA OIC Commissioner Patty Kuderer": 1.3,
  "UNITE HERE NW Health & Welfare Trust": 1.3,
  "No Surprises Act protections (federal)": 1.3,
  "Providence-Aetna WA precedent": 1.3,
  "UW Medicine-Premera Blue Cross precedent (2023)": 1.3,
  "CEO Tim Dellit, MD (UW Medicine)": 1.3,
  "CVS Health / Aetna financials": 1.3,
  "Harborview Medical Center — Level I trauma status": 1.3,
  // Tier 8 — Employer/Benefits (1.5x trade, 1.8x consultant)
  "WA employer benefits advisors": 1.5,
};

const SEARCH_TRENDS = [
  { week: "2025-04-28", interest: 3 },
  { week: "2025-05-05", interest: 5 },
  { week: "2025-05-12", interest: 8 },
  { week: "2025-05-19", interest: 12 },
  { week: "2025-05-26", interest: 55 },
  { week: "2025-06-02", interest: 100 },
  { week: "2025-06-09", interest: 65 },
  { week: "2025-06-16", interest: 40 },
  { week: "2025-06-23", interest: 35 },
  { week: "2025-06-30", interest: 85 },
  { week: "2025-07-07", interest: 25 },
  { week: "2025-07-14", interest: 8 },
  { week: "2025-07-21", interest: 3 },
];

export default {
  active: false,
  // Identity
  providerKey: "uw",
  payorKey: "aetna",
  providerName: "UW Medicine",
  payorName: "Aetna",
  providerShort: "UW Med",
  payorShort: "Aetna",
  navShort: "UW Med v. Aetna",
  title: "UW Medicine vs Aetna",
  subtitle: "Contract dispute · 33-day gap June 1–July 3, 2025",
  gradientId: "uwaetna",

  // Dates
  monitorStart: "April 15, 2025",
  monitorEnd: "July 31, 2025",
  disputeStatus: "resolved",
  disputePublicDate: "2025-05-29",

  // Colors
  colors: {
    providerColor: "#4B2D8E",
    payorColor: "#C17B2D",
    neutral: "#5D7380",
    accent: "#4B2D8E",
    bg: "#ffffff",
    surface: "#f2f7fb",
    surfaceHover: "#e8f0f7",
    border: "#c8dce8",
    text: "#053b57",
    textMuted: "#5D7380",
  },
  distColors: ["#4B2D8E", "#7A5CAE", "#C17B2D"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"uw medicine aetna" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.87,
    nationalMedian: 1.0,
    networkComplaints: 1203,
    priorYearComplaints: 892,
    regulatorAction: "WA OIC Commissioner Kuderer publicly monitored dispute and published patient guidance via Medium blog and social media. No Surprises Act protections referenced for patients in active treatment. No formal enforcement action taken. OIC noted it cannot compel Medicare Advantage network changes (federal CMS jurisdiction).",
    signalRead: "Aetna's WA network adequacy is under sustained pressure from multiple provider disputes (Providence in WA/OR, now UW Medicine). The Aetna segment's $924M loss in 2024 creates corporate incentive to hold rates down, but repeated network gaps — especially one lasting 33 days — threaten employer retention in the WA market. Medicare Advantage enrollees are the most vulnerable population, with limited mid-year switching options.",
  },

  talkingPoints: {
    provider: [
      { name: "53K patients affected", keywords: ["53,000", "53K", "thousands.*patient", "patients face", "patients.*scramble"] },
      { name: "Lowest rates of any payor", keywords: ["lowest.*rate", "lowest.*commercial", "lowest.*payor", "fair.*sustainable"] },
      { name: "Harborview / only trauma center", keywords: ["harborview", "level i trauma", "level 1 trauma", "trauma center", "safety.?net", "only.*trauma"] },
      { name: "Fred Hutch cancer access", keywords: ["fred hutch", "cancer.*center", "rare cancer", "sharon zimmerman", "choose my life"] },
      { name: "33-day actual gap", keywords: ["33.?day", "june 1.*july 3", "month.?long gap", "actual.*gap", "actual.*disruption"] },
      { name: "CVS/Aetna $924M loss", keywords: ["\\$924M", "924.*million", "cvs.*loss", "aetna.*loss", "cost.?cutting", "segment.*loss"] },
      { name: "Providence precedent / pattern", keywords: ["providence", "pattern", "serial", "pacific n", "pnw.*provider", "wa.*or.*dispute"] },
      { name: "Employer revolt (Boeing/Costco)", keywords: ["boeing", "costco", "amazon", "dump aetna", "nearly useless", "switching.*aetna", "employer.*alternative"] },
    ],
    payor: [
      { name: "Unreasonable rate demands", keywords: ["unreasonable.*rate", "inflated.*pricing", "demand.*rate", "raise.*premium"] },
      { name: "Negotiating in good faith", keywords: ["good faith", "negotiating.*fair", "fair terms"] },
      { name: "Boeing retirees exempt", keywords: ["boeing.*retiree", "ppo esa", "exempt", "boeing.*exempt"] },
      { name: "Alternative providers available", keywords: ["alternative.*provider", "alternative.*available", "other.*provider"] },
      { name: "Protecting member costs", keywords: ["cost.*member", "premium.*member", "affordab", "raise.*cost"] },
      { name: "UW Medicine scare tactics", keywords: ["scare tactic", "dangerous.*greedy", "backfir"] },
      { name: "UNITE HERE / union workers", keywords: ["unite here", "hospitality", "trust.*member", "union.*member"] },
    ],
  },

  // Executive summary
  executiveSummary: {
    statement: "Unlike most high-profile provider-payor disputes that resolve before the deadline, the UW Medicine-Aetna gap lasted a full 33 days (June 1–July 3, 2025). Patients experienced real disruption — delayed appointments, cancelled visits, scrambled referrals — not just anxiety. The retroactive contract (through Jan 1, 2027) papers over the billing gap but does not undo delayed care or eroded patient trust in Aetna's network reliability.",
    keyMessages: [
      "Aetna's rates were the lowest of any commercial payor at UW Medicine — 'fair and sustainable' framing immediately puts Aetna on the defensive across all audiences.",
      "Sharon Zimmerman's rare cancer story (KING 5: 'I'm going to choose my life') is the defining patient narrative — impossible for Aetna to counter with equivalent patient advocates.",
      "Harborview Medical Center is WA's only Level I trauma center and regional safety net (serves WA, AK, MT, ID). Losing Harborview access — even temporarily — is a network adequacy crisis with no substitute.",
      "Boeing and Costco employee social posts urging HR to dump Aetna represent direct commercial threats to Aetna's largest WA employer relationships.",
      "Providence-Aetna precedent in WA/OR creates pattern evidence — Aetna is serially underpaying Pacific NW providers, not a UW Medicine-specific problem.",
    ],
    marcomm: [
      "<strong>The 33-day gap is the story.</strong> Most disputes resolve before patients feel impact. This one didn't. Every day of actual disruption generated organic patient stories that no PR strategy can counter. The retroactive contract provides financial remedy but the reputational damage to Aetna from real care delays is permanent in the minds of affected patients.",
      "<strong>Harborview is the trump card.</strong> Harborview Medical Center is the only Level I adult and pediatric trauma and burn center in Washington and the regional safety-net hospital serving four states. Losing Harborview access — even temporarily — is a network adequacy crisis, not merely a contract dispute. Regulators, employers, and patients all understand this distinction.",
      "<strong>Employer revolt is Aetna's real risk.</strong> Boeing, Costco, Amazon, City of Seattle — WA's largest employers all have Aetna options. Social posts from Boeing and Costco employees urging HR to dump Aetna represent the commercial consequence Aetna fears most. Benefits consultants advising alternatives at renewal is the ultimate downstream threat.",
      "<strong>Medicare Advantage enrollees are the most vulnerable population.</strong> MA patients cannot easily switch plans mid-year, and WA OIC cannot compel network changes for federally regulated MA plans. Boeing retirees on Aetna MA — 'leaving us stranded' — represent the most sympathetic and politically active affected group. The Boeing PPO ESA exemption creates a visible two-tier inequity.",
    ],
  },
  channelTakeaways: {
    media: [
      "Seattle Times provided the dominant narrative arc — contract failure, editorial board criticism ('patients hurt most'), and resolution coverage. Three major pieces bookending the dispute.",
      "KING 5's Sharon Zimmerman story (rare cancer at Fred Hutch, 'I'm going to choose my life') is the single most impactful piece across all channels — broadcast reach plus maximally sympathetic subject.",
      "Four local TV stations (KIRO 7, KING 5, FOX 13, plus follow-ups) ensured saturation coverage across the Seattle-Tacoma DMA throughout the 33-day gap.",
      "Trade press (Becker's, Healthcare Dive, InsuranceNewsNet) framed Aetna's WA network as shrinking — Providence precedent cited as pattern evidence of systemic PNW underpayment.",
      "Hyperlocal coverage (Shoreline Area News x3, BellevueSeattle.com) demonstrates community-level impact near UW Medical Center Northwest and Valley Medical Center campuses.",
    ],
    social: [
      "Boeing employee urging HR to dump Aetna — listing UW Medicine, Fred Hutch, and Children's Hospital all out of network — is the most commercially threatening social post of the dispute.",
      "Costco employee 'nearly useless' network comment and Boeing retiree 'leaving us stranded' create cross-demographic anti-Aetna opposition spanning active workers and retirees.",
      "'Scare tactics' and 'dangerous and greedy' community comments suggest Aetna's defensive messaging backfired with patients who blamed the insurer, not the provider.",
      "Healthcare worker social posts humanize UW Medicine side — front-line staff fielding patient confusion daily adds labor dimension via SEIU 1199NW worker base.",
      "The 33-day actual gap generated organic patient disruption stories (delayed appointments, cancelled visits) that shorter disputes — resolved before deadline — never produce.",
    ],
    stakeholder: [
      "WA OIC Commissioner Kuderer monitoring dispute and publishing patient guidance signals regulatory seriousness — but OIC's inability to compel MA network changes exposes a regulatory gap.",
      "City of Seattle publishing a detailed employee FAQ (seattle.gov) demonstrates municipal-employer-level concern about Aetna network reliability — a government entity forced to manage an insurer's failure.",
      "UNITE HERE NW Trust alerts bring blue-collar hospitality worker vulnerability into the dispute narrative — the most financially exposed population during out-of-network gaps.",
      "Providence-Aetna WA/OR precedent is the most damaging stakeholder data point — establishes pattern of Aetna underpaying PNW providers across multiple states and systems.",
      "Harborview's status as WA's only Level I trauma center serving four states makes any network gap a regional public health issue, not merely a commercial dispute.",
    ],
    employer: [
      "Boeing, Amazon, Costco, and City of Seattle all had to manage employee disruption — administrative burden alone pressures Aetna at renewal conversations.",
      "Benefits consultants advising WA employers to consider Aetna alternatives at next renewal represents the ultimate commercial consequence of network instability.",
      "UNITE HERE Northwest Trust resolution notification demonstrates union trust funds as an employer-channel amplifier — hospitality workers experienced the gap most acutely.",
      "Aetna's 'lowest rates of any commercial payor' positioning may save money short-term but costs employer trust when networks fail — and WA employers now have two data points (Providence + UW Medicine).",
    ],
  },
  arguments: {
    payor: [
      { phase: "Pre-Deadline (May 2025)", points: ["Claimed UW Medicine was demanding <strong>unreasonable rates</strong> that would increase costs for members", "Positioned Aetna as protecting patients from inflated hospital pricing"] },
      { phase: "During Gap (Jun 2025)", points: ["Maintained that Aetna was negotiating in good faith while UW Medicine refused to agree to fair terms", "Noted Boeing retirees on PPO ESA Medicare Advantage were exempt — signaling Aetna's willingness to protect some populations"] },
      { phase: "Resolution (Jul 2025)", points: ["Agreed to retroactive contract covering the 33-day gap, effective through January 1, 2027", "Did not disclose rate terms — resolution framing was neutral"] },
    ],
    provider: [
      { phase: "Pre-Deadline (May 2025)", points: ["CEO Tim Dellit framed the dispute as seeking rates that are <strong>'fair, sustainable and in the best interests of our patients'</strong>", "Established that Aetna's reimbursement rates were the <strong>lowest of any commercial payor</strong> in the market — stickiest argument of the dispute"] },
      { phase: "During Gap (Jun 2025)", points: ["Emphasized that despite 'best efforts,' UW Medicine could not reach a <strong>financially feasible</strong> agreement with Aetna", "Leveraged patient stories — Sharon Zimmerman (rare cancer, Fred Hutch) became the defining human face of the dispute", "Cited Providence-Aetna WA precedent to establish a <strong>pattern of Aetna underpaying PNW providers</strong>"] },
      { phase: "Resolution (Jul 2025)", points: ["Secured a retroactive agreement papering over the 33-day gap — patients treated during the gap covered at in-network rates", "Contract through Jan 2027 signals meaningful rate improvement achieved"] },
    ],
  },
  timeline: [
    { date: "2025-05-29", type: "newsBreak", label: "News breaks publicly" },
    { date: "2025-06-01", type: "termination", label: "Contract terminates" },
    { date: "2025-07-03", type: "agreement", label: "Agreement reached" },
  ],
};
