// UW Medicine vs Aetna — PR War Room Config
// Dispute period: June 1–July 3, 2025. 33-day gap. Resolved with retroactive contract.

const ENTRIES = [
  // === MEDIA ENTRIES ===
  {
    id: 1,
    date: "2025-05-29",
    source: "Seattle Times",
    sourceType: "news",
    channel: "media",
    headline: "UW Medicine, Aetna fail to reach contract deal — ~53,000 patients face out-of-network gap starting June 1",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "First major coverage. Seattle Times is dominant regional paper. ~53,000 patients notified across commercial and Medicare Advantage plans. Both Harborview, UW Medical Center (Montlake + Northwest), Fred Hutch Cancer Center, and Valley Medical Center affected. CEO Tim Dellit quoted: 'fair, sustainable and in the best interests of our patients.' Aetna rates described as lowest of any commercial payor.",
  },
  {
    id: 2,
    date: "2025-06-05",
    source: "Seattle Times (Editorial Board)",
    sourceType: "opinion",
    channel: "media",
    headline: "Seattle Times editorial: Patients should not be pawns in UW Medicine-Aetna contract fight",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Editorial board weigh-in. 'Patients as pawns' framing criticizes both sides but implicitly pressures the party with more leverage to settle. Editorial boards carry outsized influence with local policymakers and employer HR departments.",
  },
  {
    id: 3,
    date: "2025-07-03",
    source: "Seattle Times",
    sourceType: "news",
    channel: "media",
    headline: "UW Medicine, Aetna reach agreement — contract retroactive to June 1, runs through Jan 1, 2027",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution coverage. Retroactive provision means 33-day gap is papered over contractually, but patients experienced real anxiety and some delayed care. Contract runs through Jan 1, 2027. Neither side disclosed specific rate terms.",
  },
  {
    id: 4,
    date: "2025-05-30",
    source: "KIRO 7",
    sourceType: "tv",
    channel: "media",
    headline: "UW Medicine drops out of Aetna network — thousands of patients scramble for answers",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "Lead local TV coverage. 'Drops out' framing places responsibility on the contract failure rather than UW Medicine's choice. Patient anxiety stories. KIRO 7 (CBS affiliate) reaches broad Seattle-Tacoma DMA.",
  },
  {
    id: 5,
    date: "2025-06-10",
    source: "KIRO 7",
    sourceType: "tv",
    channel: "media",
    headline: "Patients caught in limbo as UW Medicine-Aetna dispute drags on — no resolution in sight",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "Mid-gap follow-up. 'Limbo' and 'drags on' framing increases pressure. Patient interviews reinforce hardship angle. Ten days into gap with no public progress.",
  },
  {
    id: 6,
    date: "2025-07-03",
    source: "KIRO 7",
    sourceType: "tv",
    channel: "media",
    headline: "UW Medicine and Aetna reach deal after 33-day gap — contract retroactive to June 1",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Resolution coverage. '33-day gap' quantifies disruption duration. Retroactive provision noted but damage to patient trust already done.",
  },
  {
    id: 7,
    date: "2025-06-01",
    source: "KING 5",
    sourceType: "tv",
    channel: "media",
    headline: "Sharon Zimmerman, rare cancer patient, fears losing UW Medicine access — 'I'm going to choose my life'",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "KEY PATIENT STORY. Sharon Zimmerman: rare cancer, in treatment at UW Medicine/Fred Hutch. Quote: 'When it comes down to my life vs insurance, I'm going to choose my life.' KING 5 (NBC affiliate) — highest-reach patient story in the dispute. Cancer patient facing access loss is maximally sympathetic framing.",
  },
  {
    id: 8,
    date: "2025-05-30",
    source: "FOX 13 Seattle",
    sourceType: "tv",
    channel: "media",
    headline: "Aetna patients lose in-network access to UW Medicine facilities starting June 1",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "FOX 13 coverage. 'Lose in-network access' is direct and alarming. Covers all affected facilities: Harborview, UW Medical Center (Montlake + Northwest), Fred Hutch Cancer Center, Valley Medical Center.",
  },
  {
    id: 9,
    date: "2025-06-15",
    source: "FOX 13 Seattle",
    sourceType: "tv",
    channel: "media",
    headline: "UW Medicine-Aetna standoff enters third week — patients weigh switching insurers mid-year",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "Third-week follow-up. Patients considering mid-year insurer switches signals severity. 'Standoff' language implies both sides dug in but patient stories favor UW Medicine.",
  },
  {
    id: 10,
    date: "2025-06-02",
    source: "MyNorthwest",
    sourceType: "news",
    channel: "media",
    headline: "UW Medicine goes out of network with Aetna — patients scramble across Puget Sound region",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Regional digital news. Puget Sound focus. 'Scramble' conveys patient disruption. MyNorthwest reaches engaged local news audience.",
  },
  {
    id: 11,
    date: "2025-06-03",
    source: "The Daily (UW)",
    sourceType: "news",
    channel: "media",
    headline: "UW student and staff patients affected as UW Medicine exits Aetna network",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "University of Washington student paper. Important for campus community — UW students and staff use UW Medicine as primary care. Adds 'university community' angle to dispute.",
  },
  {
    id: 12,
    date: "2025-05-30",
    source: "Shoreline Area News",
    sourceType: "news",
    channel: "media",
    headline: "UW Medicine-Aetna contract lapse affects Shoreline patients who rely on UW Medical Center Northwest",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Hyperlocal coverage. UW Medical Center Northwest campus is in Shoreline. Local patients directly affected. Community-level awareness.",
  },
  {
    id: 13,
    date: "2025-06-10",
    source: "Shoreline Area News",
    sourceType: "news",
    channel: "media",
    headline: "Shoreline residents seek alternatives as UW Medicine-Aetna gap continues into second week",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Follow-up hyperlocal coverage. Patients seeking alternatives demonstrates real disruption to care continuity. Northwest campus is anchor institution for Shoreline community.",
  },
  {
    id: 14,
    date: "2025-07-03",
    source: "Shoreline Area News",
    sourceType: "news",
    channel: "media",
    headline: "Relief for Shoreline patients: UW Medicine and Aetna reach retroactive agreement",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Resolution coverage at hyperlocal level. 'Relief' framing acknowledges patient hardship during gap.",
  },
  {
    id: 15,
    date: "2025-06-02",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "UW Medicine, Aetna fail to reach contract agreement — 53,000 patients affected in Washington State",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "National trade press. 53,000 patient figure makes this a significant dispute by national standards. Hospital executive audience tracks these disputes closely. Becker's also covered Providence-Aetna precedent in WA.",
  },
  {
    id: 16,
    date: "2025-06-01",
    source: "InsuranceNewsNet",
    sourceType: "news",
    channel: "media",
    headline: "Aetna loses UW Medicine from network as contract expires — CVS Health segment under pressure",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Insurance trade press. Notes CVS/Aetna $372.8B revenue in 2024 but Aetna segment lost $924M. Financial context undermines Aetna's 'affordability' argument — they're losing money operationally, not overpaying providers.",
  },
  {
    id: 17,
    date: "2025-06-03",
    source: "EIN Presswire",
    sourceType: "news",
    channel: "media",
    headline: "UW Medicine contract dispute with Aetna highlights growing provider-payor tensions in Pacific Northwest",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Wire service distribution. Frames dispute as part of broader PNW trend. Providence-Aetna precedent in Washington State referenced.",
  },
  {
    id: 18,
    date: "2025-06-04",
    source: "Daily Chronicle",
    sourceType: "news",
    channel: "media",
    headline: "Aetna patients in Washington face uncertain access to UW Medicine hospitals and clinics",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Regional coverage. 'Uncertain access' framing emphasizes patient impact. Lists full facility scope including trauma center (Harborview) angle.",
  },
  {
    id: 19,
    date: "2025-06-05",
    source: "Healthcare Dive",
    sourceType: "news",
    channel: "media",
    headline: "UW Medicine joins growing list of providers dropping Aetna over reimbursement rates",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "National healthcare trade. 'Growing list' framing positions Aetna as serially underpaying providers. Notes Aetna rates described as lowest of any commercial payor at UW Medicine. Industry audience.",
  },
  // === UW MEDICINE OWNED MEDIA ===
  {
    id: 20,
    date: "2025-05-29",
    source: "UW Medicine Newsroom",
    sourceType: "owned",
    channel: "media",
    headline: "UW Medicine statement: Unable to reach fair agreement with Aetna — 'in the best interests of our patients'",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Official UW Medicine statement. CEO Tim Dellit: 'fair, sustainable and in the best interests of our patients.' Frames Aetna rates as unsustainably low — lowest of any commercial payor. Patient-first language. Sets the provider narrative for all subsequent coverage.",
  },
  {
    id: 21,
    date: "2025-06-01",
    source: "UW Medicine (LinkedIn)",
    sourceType: "social",
    channel: "media",
    headline: "UW Medicine LinkedIn: Notifying patients of Aetna contract lapse, directing to resources",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "LinkedIn reaches professional/employer audience. UW Medicine is one of WA's largest employers. Post directs patients to FAQ and alternative coverage options.",
  },
  {
    id: 22,
    date: "2025-06-01",
    source: "UW Medicine (Facebook)",
    sourceType: "social",
    channel: "media",
    headline: "UW Medicine Facebook: Patient notification about Aetna contract gap and care continuity options",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Facebook reaches older patient demographic most likely to be in active treatment. Comment sections likely filled with patient anxiety and anger directed at Aetna.",
  },
  // === AETNA / WA OIC OWNED MEDIA ===
  {
    id: 23,
    date: "2025-06-02",
    source: "WA OIC (Medium blog)",
    sourceType: "owned",
    channel: "media",
    headline: "WA Office of Insurance Commissioner blog: What patients need to know about UW Medicine-Aetna dispute",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Commissioner Patty Kuderer's office. Regulatory guidance on patient rights during network disruption. References No Surprises Act protections and continuity of care provisions. Official government channel — lends gravity to disruption.",
  },
  {
    id: 24,
    date: "2025-06-02",
    source: "WA OIC (Facebook)",
    sourceType: "social",
    channel: "media",
    headline: "WA Insurance Commissioner Facebook: Patient rights and protections during UW Medicine-Aetna gap",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Social amplification of OIC guidance. The fact that a state regulator felt compelled to post patient guidance signals significance of the disruption.",
  },
  // === SOCIAL ENTRIES ===
  {
    id: 25,
    date: "2025-06-01",
    source: "Social media (Boeing employee)",
    sourceType: "social",
    channel: "social",
    headline: "Boeing employee urges colleagues to pressure HR to dump Aetna — 'this is the last straw'",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "CRITICAL EMPLOYER SIGNAL. Boeing is one of WA's largest employers with Aetna as an option. Employee calling for dumping Aetna entirely represents direct commercial threat. 'Last straw' implies accumulated frustration with Aetna network adequacy.",
  },
  {
    id: 26,
    date: "2025-06-03",
    source: "Social media (Costco employee)",
    sourceType: "social",
    channel: "social",
    headline: "Costco employee notes shrinking Aetna network in WA — UW Medicine loss makes plan 'nearly useless'",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Another major WA employer. 'Shrinking network' and 'nearly useless' are devastating for Aetna's employer value proposition. Costco HQ is in Issaquah — core UW Medicine service area.",
  },
  {
    id: 27,
    date: "2025-06-05",
    source: "Social media (Boeing retiree)",
    sourceType: "social",
    channel: "social",
    headline: "Boeing retiree on Medicare Advantage via Aetna: 'leaving us stranded' without UW Medicine",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Medicare Advantage angle. Retirees on MA plans are especially vulnerable — limited ability to switch plans mid-year. 'Leaving us stranded' is powerful emotional language. Boeing retiree community is large and politically active in WA.",
  },
  {
    id: 28,
    date: "2025-06-08",
    source: "Social media (general criticism)",
    sourceType: "social",
    channel: "social",
    headline: "Social posts accuse Aetna of 'scare tactics' and underpaying WA providers to boost CVS bottom line",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "'Scare tactics' criticism — patients perceive Aetna communications as blaming UW Medicine to deflect from low reimbursement rates. CVS connection (parent company) invites 'corporate greed' framing. Aetna segment $924M loss in 2024 undermines sympathy.",
  },
  {
    id: 29,
    date: "2025-06-10",
    source: "Social media (patient anxiety thread)",
    sourceType: "social",
    channel: "social",
    headline: "Patients share stories of delayed appointments, scrambling for alternatives during UW Medicine-Aetna gap",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Organic patient stories during active gap. Unlike disputes resolved before lapse, this one had a real 33-day gap — patients experienced actual disruption, not just anxiety. Delayed appointments, referral complications, out-of-pocket cost fears.",
  },
  {
    id: 30,
    date: "2025-06-15",
    source: "Social media (WA healthcare workers)",
    sourceType: "social",
    channel: "social",
    headline: "UW Medicine staff share frustration on social media — front-line workers fielding patient confusion daily",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "low",
    notes: "Healthcare worker perspective. Staff dealing with patient confusion and care coordination challenges. Humanizes UW Medicine side. Workers as secondary victims of dispute.",
  },
  // === STAKEHOLDER ENTRIES ===
  {
    id: 31,
    date: "2025-06-02",
    source: "WA OIC Commissioner Patty Kuderer",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "Commissioner Kuderer: OIC monitoring UW Medicine-Aetna dispute, ensuring patient protections enforced",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "State insurance commissioner publicly monitoring dispute. Kuderer's office references No Surprises Act protections and WA state continuity of care requirements. Regulatory attention increases pressure on both parties but especially Aetna as the insurer subject to OIC jurisdiction.",
  },
  {
    id: 32,
    date: "2025-06-05",
    source: "City of Seattle HR FAQ",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "City of Seattle publishes employee FAQ on UW Medicine-Aetna dispute — directs affected staff to alternatives",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Municipal employer response. City of Seattle is a major employer offering Aetna plans. The fact that a city government had to publish an FAQ about an insurer's network gap is significant. Signals employer-level concern and administrative burden.",
  },
  {
    id: 33,
    date: "2025-06-08",
    source: "UNITE HERE NW Health & Welfare Trust",
    sourceType: "news",
    channel: "stakeholder",
    headline: "UNITE HERE Northwest Trust alerts hospitality worker members about UW Medicine access disruption",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Union trust fund alert. UNITE HERE represents hotel, food service, and hospitality workers — lower-wage workers most vulnerable to network disruption and out-of-pocket costs. Union channel amplifies blue-collar worker impact angle.",
  },
  {
    id: 34,
    date: "2025-06-01",
    source: "No Surprises Act protections (federal)",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Federal No Surprises Act provides some protections for patients in active treatment during network gaps",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Regulatory framework. No Surprises Act (effective Jan 2022) provides some continuity protections for patients mid-treatment. However, coverage is not comprehensive — many patients still face disruption for routine care and new referrals. WA OIC references these protections in guidance.",
  },
  {
    id: 35,
    date: "2025-05-29",
    source: "Providence-Aetna WA precedent",
    sourceType: "news",
    channel: "stakeholder",
    headline: "Providence Health previously clashed with Aetna in WA — pattern of Aetna underpaying Pacific NW providers",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "PATTERN EVIDENCE. Providence, the largest health system in WA, had its own Aetna contract dispute. Multiple WA providers flagging Aetna's rates as unsustainably low undermines Aetna's framing that UW Medicine is uniquely expensive. Systemic underpayment pattern.",
  },
  {
    id: 36,
    date: "2025-06-01",
    source: "CEO Tim Dellit, MD (UW Medicine)",
    sourceType: "opinion",
    channel: "stakeholder",
    headline: "UW Medicine CEO Dellit: Agreement must be 'fair, sustainable and in the best interests of our patients'",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "high",
    notes: "CEO public framing. 'Fair, sustainable' implies Aetna's rates are neither. 'Best interests of our patients' positions UW Medicine as patient advocate, not profit-seeker. Dellit is a physician-CEO — clinician credibility. Aetna rates described as lowest of any commercial payor.",
  },
  {
    id: 37,
    date: "2025-06-10",
    source: "CVS Health / Aetna financials",
    sourceType: "news",
    channel: "stakeholder",
    headline: "CVS/Aetna context: $372.8B revenue in 2024 but Aetna segment lost $924M — cost-cutting drives dispute",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "FINANCIAL CONTEXT. CVS Health parent company $372.8B revenue. Aetna insurance segment lost $924M in 2024. Financial losses create corporate pressure to hold down provider rates, which explains Aetna's hard bargaining position. But revenue figure undermines 'we can't afford it' argument.",
  },
  // === EMPLOYER ENTRIES ===
  {
    id: 38,
    date: "2025-06-01",
    source: "Boeing HR communications",
    sourceType: "owned",
    channel: "employer",
    headline: "Boeing notifies employees of UW Medicine-Aetna network disruption — directs to alternative providers",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Boeing is WA's largest private employer. Internal HR communication to Aetna-enrolled employees creates direct employer pressure on Aetna. Administrative burden of redirecting employees and managing disruption frustration.",
  },
  {
    id: 39,
    date: "2025-06-03",
    source: "Amazon / major WA employer HR",
    sourceType: "owned",
    channel: "employer",
    headline: "Major WA employers field employee questions about UW Medicine access under Aetna plans",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "high",
    notes: "Amazon, Microsoft, Costco, and other major WA employers with Aetna options face employee disruption. Employer HR departments become de facto complaint channels. Each employer interaction is an implicit threat to Aetna's commercial relationship.",
  },
  {
    id: 40,
    date: "2025-06-15",
    source: "WA employer benefits advisors",
    sourceType: "news",
    channel: "employer",
    headline: "Benefits consultants advise WA employers to consider Aetna alternatives at next renewal if network instability continues",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Broker/consultant channel. Network disruption directly impacts Aetna's competitive position for employer renewals. Providence precedent + UW Medicine gap creates narrative of Aetna network instability in WA market.",
  },
  // === ADDITIONAL MEDIA ===
  {
    id: 41,
    date: "2025-06-12",
    source: "UNITE HERE (member alerts)",
    sourceType: "owned",
    channel: "stakeholder",
    headline: "UNITE HERE issues multiple member alerts about Aetna-UW Medicine gap affecting hospitality workers",
    frameAdoption: "uwmed",
    sentiment: "negative_aetna",
    patientStory: true,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Ongoing union communications. Hospitality workers often have limited provider options and less ability to absorb out-of-network costs. Union framing emphasizes corporate insurer vs working families dynamic.",
  },
  {
    id: 42,
    date: "2025-06-20",
    source: "Becker's Hospital Review",
    sourceType: "news",
    channel: "media",
    headline: "UW Medicine-Aetna dispute enters fourth week with no resolution — longest active gap in WA",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Trade press follow-up. 'Fourth week' and 'longest active gap' framing amplifies severity. National hospital executive audience tracking dispute duration as benchmark.",
  },
  {
    id: 43,
    date: "2025-06-25",
    source: "Healthcare Dive",
    sourceType: "news",
    channel: "media",
    headline: "Aetna's WA network shrinks further as UW Medicine gap persists — Providence precedent looms",
    frameAdoption: "balanced",
    sentiment: "negative_aetna",
    patientStory: false,
    blameDirection: "aetna",
    reachEstimate: "medium",
    notes: "Trade press. 'Shrinks further' positions Aetna as having a WA-specific network adequacy problem. Providence precedent cited as pattern evidence. Industry analysts questioning Aetna's WA market viability.",
  },
  {
    id: 44,
    date: "2025-07-03",
    source: "InsuranceNewsNet",
    sourceType: "news",
    channel: "media",
    headline: "Aetna resolves UW Medicine dispute with retroactive deal — Aetna segment losses continue to pressure CVS",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "medium",
    notes: "Insurance trade resolution coverage. Financial framing — Aetna's $924M segment loss context. Retroactive provision noted. CVS Health investor implications.",
  },
  {
    id: 45,
    date: "2025-07-03",
    source: "EIN Presswire",
    sourceType: "news",
    channel: "media",
    headline: "UW Medicine and Aetna announce new agreement ending 33-day network gap in Washington State",
    frameAdoption: "balanced",
    sentiment: "neutral",
    patientStory: false,
    blameDirection: "both",
    reachEstimate: "low",
    notes: "Wire service resolution coverage. '33-day network gap' quantifies the disruption in headline — becomes the benchmark figure for this dispute.",
  },
];

const LABELS = {
  frameAdoption: { uwmed: "UW Med Frame", aetna: "Aetna Frame", balanced: "Balanced" },
  sentiment: {
    negative_aetna: "Anti-Aetna",
    negative_uwmed: "Anti-UW Med",
    neutral: "Neutral",
    positive_aetna: "Pro-Aetna",
    positive_uwmed: "Pro-UW Med",
  },
  blameDirection: { aetna: "Blames Aetna", uwmed: "Blames UW Med", both: "Both/Neither" },
  reachEstimate: { high: "High", medium: "Medium", low: "Low" },
  sourceType: { news: "Print/Online News", tv: "TV", radio: "Radio", owned: "Owned Media", social: "Social/Forum", opinion: "Op-Ed/Expert" },
  channel: { media: "Media", social: "Social/Forum", stakeholder: "Stakeholder", employer: "Employer" },
};

const SOURCE_WEIGHTS = {
  // Tier 1 — National/regional record (1.5)
  "Seattle Times": 1.5, "Seattle Times (Editorial Board)": 1.5,
  // Tier 2 — Regional TV authority (1.2)
  "KIRO 7": 1.2, "KING 5": 1.2, "FOX 13 Seattle": 1.2,
  // Tier 3 — Trade/digital (1.0)
  "Becker's Hospital Review": 1.0, "Healthcare Dive": 1.0, "InsuranceNewsNet": 1.0,
  "EIN Presswire": 1.0, "Daily Chronicle": 1.0, "MyNorthwest": 1.0,
  "The Daily (UW)": 1.0, "Shoreline Area News": 1.0,
  // Tier 4 — Organic social (0.7)
  "Social media (Boeing employee)": 0.7, "Social media (Costco employee)": 0.7,
  "Social media (Boeing retiree)": 0.7, "Social media (general criticism)": 0.7,
  "Social media (patient anxiety thread)": 0.7, "Social media (WA healthcare workers)": 0.7,
  // Tier 5 — Owned/party media (0.3)
  "UW Medicine Newsroom": 0.3, "UW Medicine (LinkedIn)": 0.3, "UW Medicine (Facebook)": 0.3,
  "WA OIC (Medium blog)": 0.3, "WA OIC (Facebook)": 0.3,
  "Boeing HR communications": 0.3, "Amazon / major WA employer HR": 0.3,
  // Tier 6 — Stakeholder actions (1.3)
  "WA OIC Commissioner Patty Kuderer": 1.3, "City of Seattle HR FAQ": 1.3,
  "UNITE HERE NW Health & Welfare Trust": 1.3, "UNITE HERE (member alerts)": 1.3,
  "No Surprises Act protections (federal)": 1.3, "Providence-Aetna WA precedent": 1.3,
  "CEO Tim Dellit, MD (UW Medicine)": 1.3, "CVS Health / Aetna financials": 1.3,
  // Tier 7 — Employer/Benefits (1.5)
  "WA employer benefits advisors": 1.5,
};

const SEARCH_TRENDS = [
  { week: "2025-05-05", interest: 5 },
  { week: "2025-05-12", interest: 5 },
  { week: "2025-05-19", interest: 5 },
  { week: "2025-05-26", interest: 40 },
  { week: "2025-06-02", interest: 100 },
  { week: "2025-06-09", interest: 60 },
  { week: "2025-06-16", interest: 35 },
  { week: "2025-06-23", interest: 35 },
  { week: "2025-06-30", interest: 90 },
  { week: "2025-07-07", interest: 20 },
  { week: "2025-07-14", interest: 5 },
  { week: "2025-07-21", interest: 5 },
];

export default {
  // Identity
  providerKey: "uwmed",
  payorKey: "aetna",
  providerName: "UW Medicine",
  payorName: "Aetna",
  providerShort: "UW Med",
  payorShort: "Aetna",
  navShort: "UW Med v. Aetna",
  title: "UW Medicine vs Aetna",
  subtitle: "Contract dispute · 33-day gap June 1–July 3, 2025",
  gradientId: "uwaetna",

  // Dates
  monitorStart: "May 1, 2025",
  monitorEnd: "July 31, 2025",
  disputePublicDate: "2025-05-29",

  // Colors
  colors: {
    providerColor: "#4B2D8E",
    payorColor: "#C17B2D",
    neutral: "#64748B",
    accent: "#4B2D8E",
    bg: "#FFFFFF",
    surface: "#F5F7FA",
    surfaceHover: "#EDF0F5",
    border: "#D8DDE6",
    text: "#1A1A2E",
    textMuted: "#64748B",
  },
  distColors: ["#4B2D8E", "#7A5CAE", "#C17B2D"],
  yAxisWidth: 78,

  // Data
  entries: ENTRIES,
  labels: LABELS,
  sourceWeights: SOURCE_WEIGHTS,
  searchTrends: SEARCH_TRENDS,
  searchLabel: '"uw medicine aetna" · weekly',

  // Complaint data
  complaintData: {
    insurerIndex: 1.87,
    nationalMedian: 1.0,
    networkComplaints: 1203,
    priorYearComplaints: 892,
    regulatorAction: "WA OIC Commissioner Kuderer publicly monitored dispute. No Surprises Act protections referenced. No formal enforcement action taken. OIC published patient guidance via Medium blog and Facebook.",
    signalRead: "Aetna's WA network adequacy is under pressure from multiple provider disputes (Providence precedent, now UW Medicine). Aetna segment's $924M loss in 2024 creates corporate incentive to hold rates down, but repeated network gaps threaten employer retention in WA market. Medicare Advantage enrollees especially vulnerable during gaps.",
  },

  // Executive summary
  executiveSummary: {
    statement: "Unlike most high-profile disputes that resolve before the deadline, the UW Medicine-Aetna gap lasted a full 33 days — patients experienced real disruption, not just anxiety. The retroactive contract (June 1 through Jan 1, 2027) papers over the gap but does not undo delayed care or patient distress.",
    keyMessages: [
      "Aetna's rates were the lowest of any commercial payor at UW Medicine — 'fair and sustainable' framing puts Aetna on the defensive.",
      "Sharon Zimmerman's rare cancer story (KING 5: 'I'm going to choose my life') is the defining patient narrative — impossible for Aetna to counter.",
      "Boeing and Costco employee social posts represent direct commercial threats to Aetna's WA employer relationships.",
      "Providence-Aetna precedent in WA creates pattern evidence — Aetna serially underpaying Pacific NW providers, not a UW Medicine-specific problem.",
      "CVS/Aetna $372.8B revenue but Aetna segment $924M loss undermines both 'we can't afford it' and 'corporate greed' narratives simultaneously.",
    ],
    marcomm: [
      "<strong>The 33-day gap is the story.</strong> Most disputes resolve before patients feel impact. This one didn't. Every day of actual disruption generates organic patient stories that no PR strategy can counter. UW Medicine's retroactive deal provides financial remedy but the reputational damage to Aetna from real care delays is permanent.",
      "<strong>Harborview is the trump card.</strong> Harborview Medical Center is the only Level I trauma center in WA and the regional safety-net hospital. Losing Harborview access — even temporarily — is a network adequacy crisis, not just a contract dispute. Regulators cannot ignore this.",
      "<strong>Employer revolt is Aetna's real risk.</strong> Boeing, Costco, Amazon, City of Seattle — WA's largest employers all have Aetna options. Social posts from Boeing and Costco employees urging HR to dump Aetna represent the commercial consequence Aetna fears most. Providence precedent makes this a pattern, not an anomaly.",
      "<strong>Medicare Advantage enrollees are the most vulnerable population.</strong> MA patients cannot easily switch plans mid-year. Boeing retirees on Aetna MA plans — 'leaving us stranded' — represent the most sympathetic and politically active affected group.",
    ],
  },
  channelTakeaways: {
    media: [
      "Seattle Times provided the dominant narrative arc — contract failure, editorial board criticism, resolution coverage. Three stories bookending the dispute.",
      "KING 5's Sharon Zimmerman story (rare cancer, 'I'm going to choose my life') is the single most impactful piece across all channels.",
      "Four local TV stations (KIRO 7, KING 5, FOX 13, plus follow-ups) ensured saturation coverage across Seattle-Tacoma DMA.",
      "Trade press (Becker's, Healthcare Dive, InsuranceNewsNet) framed Aetna's WA network as shrinking — Providence precedent cited as pattern.",
      "Hyperlocal coverage (Shoreline Area News x3) demonstrates community-level impact near UW Medical Center Northwest campus.",
    ],
    social: [
      "Boeing employee urging HR to dump Aetna is the most commercially threatening social post — direct employer pressure signal.",
      "Costco employee noting 'shrinking network' and Boeing retiree 'leaving us stranded' create cross-demographic Aetna opposition.",
      "'Scare tactics' criticism of Aetna communications suggests Aetna's messaging backfired with patients.",
      "Healthcare worker posts humanize UW Medicine side — front-line staff fielding patient confusion daily.",
      "33-day actual gap generated organic patient disruption stories that shorter disputes never produce.",
    ],
    stakeholder: [
      "WA OIC Commissioner Kuderer monitoring dispute and publishing patient guidance signals regulatory seriousness.",
      "City of Seattle publishing an employee FAQ demonstrates municipal-employer-level concern about Aetna network reliability.",
      "UNITE HERE NW Trust alerts bring blue-collar worker vulnerability into the dispute narrative.",
      "No Surprises Act protections provide some coverage but do not prevent care disruption for routine appointments and new referrals.",
      "Providence-Aetna WA precedent is the most damaging stakeholder data point — establishes pattern of Aetna underpaying PNW providers.",
    ],
    employer: [
      "Boeing, Amazon, Costco, and City of Seattle all had to manage employee disruption — administrative burden alone pressures Aetna.",
      "Benefits consultants advising employers to consider Aetna alternatives at renewal represents the ultimate commercial consequence.",
      "Aetna's 'lowest rates of any commercial payor' positioning may save money short-term but costs employer trust when networks fail.",
    ],
  },
};
